#import <Foundation/Foundation.h>
@interface LuckingBuyLuckingbuyMBProgressHUDz: NSObject
+ (BOOL)OShowhudaddedtoyAnimated:(NSInteger)LuckingBuy;
+ (BOOL)NHidehudforviewbAnimated:(NSInteger)LuckingBuy;
+ (BOOL)NHudforview:(NSInteger)LuckingBuy;
+ (BOOL)OcommonInit:(NSInteger)LuckingBuy;
+ (BOOL)ZInitwithframe:(NSInteger)LuckingBuy;
+ (BOOL)YInitwithcoder:(NSInteger)LuckingBuy;
+ (BOOL)lInitwithview:(NSInteger)LuckingBuy;
+ (BOOL)odealloc:(NSInteger)LuckingBuy;
+ (BOOL)TShowanimated:(NSInteger)LuckingBuy;
+ (BOOL)sHideanimated:(NSInteger)LuckingBuy;
+ (BOOL)cHideanimatedaAfterdelay:(NSInteger)LuckingBuy;
+ (BOOL)KHandlegracetimer:(NSInteger)LuckingBuy;
+ (BOOL)ZHandleminshowtimer:(NSInteger)LuckingBuy;
+ (BOOL)PHandlehidetimer:(NSInteger)LuckingBuy;
+ (BOOL)IdidMoveToSuperview:(NSInteger)LuckingBuy;
+ (BOOL)LShowusinganimation:(NSInteger)LuckingBuy;
+ (BOOL)UHideusinganimation:(NSInteger)LuckingBuy;
+ (BOOL)lAnimateinzWithtypeaCompletion:(NSInteger)LuckingBuy;
+ (BOOL)Rdone:(NSInteger)LuckingBuy;
+ (BOOL)EsetupViews:(NSInteger)LuckingBuy;
+ (BOOL)TupdateIndicators:(NSInteger)LuckingBuy;
+ (BOOL)JUpdateviewsforcolor:(NSInteger)LuckingBuy;
+ (BOOL)PupdateBezelMotionEffects:(NSInteger)LuckingBuy;
+ (BOOL)yupdateConstraints:(NSInteger)LuckingBuy;
+ (BOOL)FlayoutSubviews:(NSInteger)LuckingBuy;
+ (BOOL)oupdatePaddingConstraints:(NSInteger)LuckingBuy;
+ (BOOL)JApplyprioritynToconstraints:(NSInteger)LuckingBuy;
+ (BOOL)FSetmode:(NSInteger)LuckingBuy;
+ (BOOL)HSetcustomview:(NSInteger)LuckingBuy;
+ (BOOL)oSetoffset:(NSInteger)LuckingBuy;
+ (BOOL)OSetmargin:(NSInteger)LuckingBuy;
+ (BOOL)PSetminsize:(NSInteger)LuckingBuy;
+ (BOOL)sSetsquare:(NSInteger)LuckingBuy;
+ (BOOL)ISetprogressobjectdisplaylink:(NSInteger)LuckingBuy;
+ (BOOL)xSetprogressobject:(NSInteger)LuckingBuy;
+ (BOOL)QSetprogress:(NSInteger)LuckingBuy;
+ (BOOL)QSetcontentcolor:(NSInteger)LuckingBuy;
+ (BOOL)zSetdefaultmotioneffectsenabled:(NSInteger)LuckingBuy;
+ (BOOL)ESetnsprogressdisplaylinkenabled:(NSInteger)LuckingBuy;
+ (BOOL)YupdateProgressFromProgressObject:(NSInteger)LuckingBuy;
+ (BOOL)aregisterForNotifications:(NSInteger)LuckingBuy;
+ (BOOL)IunregisterFromNotifications:(NSInteger)LuckingBuy;
+ (BOOL)uStatusbarorientationdidchange:(NSInteger)LuckingBuy;
+ (BOOL)hUpdateforcurrentorientationanimated:(NSInteger)LuckingBuy;

@end
