package com.whaty.platform.sso.bean;

import java.util.HashSet;
import java.util.Set;

/**
 * PePriRole generated by MyEclipse Persistence Tools
 */

public class PePriRole implements java.io.Serializable {

	// Fields

	private String id;

	private String name;

	private Set prPriRoles = new HashSet(0);

	private Set ssoUsers = new HashSet(0);

	// Constructors

	/** default constructor */
	public PePriRole() {
	}

	/** minimal constructor */
	public PePriRole(String name) {
		this.name = name;
	}

	/** full constructor */
	public PePriRole(String name, Set prPriRoles, Set ssoUsers) {
		this.name = name;
		this.prPriRoles = prPriRoles;
		this.ssoUsers = ssoUsers;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getPrPriRoles() {
		return this.prPriRoles;
	}

	public void setPrPriRoles(Set prPriRoles) {
		this.prPriRoles = prPriRoles;
	}

	public Set getSsoUsers() {
		return this.ssoUsers;
	}

	public void setSsoUsers(Set ssoUsers) {
		this.ssoUsers = ssoUsers;
	}

}