package com.whaty.platform.sso.bean;

/**
 * PrPriRole generated by MyEclipse Persistence Tools
 */

public class PrPriRole implements java.io.Serializable {

	// Fields

	private String id;

	private PePriRole pePriRole;

	private PePriority pePriority;

	// Constructors

	/** default constructor */
	public PrPriRole() {
	}

	/** full constructor */
	public PrPriRole(PePriRole pePriRole, PePriority pePriority) {
		this.pePriRole = pePriRole;
		this.pePriority = pePriority;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public PePriRole getPePriRole() {
		return this.pePriRole;
	}

	public void setPePriRole(PePriRole pePriRole) {
		this.pePriRole = pePriRole;
	}

	public PePriority getPePriority() {
		return this.pePriority;
	}

	public void setPePriority(PePriority pePriority) {
		this.pePriority = pePriority;
	}

}