package com.whaty.platform.sso.bean;

import com.whaty.platform.entity.bean.PeEdutype;

/**
 * PrPriManagerEdutype generated by MyEclipse Persistence Tools
 */

public class PrPriManagerEdutype implements java.io.Serializable {

	// Fields

	private String id;

	private SsoUser ssoUser;

	private PeEdutype peEdutype;

	// Constructors

	/** default constructor */
	public PrPriManagerEdutype() {
	}

	/** full constructor */
	public PrPriManagerEdutype(SsoUser ssoUser, PeEdutype peEdutype) {
		this.ssoUser = ssoUser;
		this.peEdutype = peEdutype;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public SsoUser getSsoUser() {
		return this.ssoUser;
	}

	public void setSsoUser(SsoUser ssoUser) {
		this.ssoUser = ssoUser;
	}

	public PeEdutype getPeEdutype() {
		return this.peEdutype;
	}

	public void setPeEdutype(PeEdutype peEdutype) {
		this.peEdutype = peEdutype;
	}

}