package com.whaty.platform.sso.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.whaty.platform.entity.bean.EnumConst;
/**
 * SsoUser generated by MyEclipse Persistence Tools
 */

public class SsoUser implements java.io.Serializable {

	// Fields

	private String id;

	private EnumConst enumConstByFlagIsvalid;

	private PePriRole pePriRole;

	private EnumConst enumConstByUserType;

	private String loginId;

	private String password;

	private Long loginNum;

	private Date lastLoginDate;

	private String lastLoginIp;

	private Set prPriManagerSites = new HashSet(0);

	private Set peStudents = new HashSet(0);

	private Set prPriManagerMajors = new HashSet(0);

	private Set prPriManagerEdutypes = new HashSet(0);

	private Set peSitemanagers = new HashSet(0);

	private Set peManagers = new HashSet(0);

	private Set prPriManagerGrades = new HashSet(0);

	private Set peTeachers = new HashSet(0);
	
	private Set peBzzStudents=new HashSet(0);

	private Set peEnterpriseManager=new HashSet(0);
	
	private Set trainingCourseStudent=new HashSet(0);
	
	private Set prBzzPriManagerEnterprises=new HashSet(0);

	// Constructors

	/** default constructor */
	public SsoUser() {
	}

	/** minimal constructor */
	public SsoUser(String loginId, String password) {
		this.loginId = loginId;
		this.password = password;
	}

	/** full constructor */
	public SsoUser(EnumConst enumConstByFlagIsvalid, PePriRole pePriRole,
			EnumConst enumConstByUserType, String loginId, String password,
			Long loginNum, Date lastLoginDate, String lastLoginIp,
			Set prPriManagerSites, Set peStudents, Set prPriManagerMajors,
			Set prPriManagerEdutypes, Set peSitemanagers, Set peManagers,
			Set prPriManagerGrades, Set peTeachers,Set peBzzStudents,
			Set peEnterpriseManager,Set trainingCourseStudent,Set prBzzPriManagerEnterprises) {
		this.enumConstByFlagIsvalid = enumConstByFlagIsvalid;
		this.pePriRole = pePriRole;
		this.enumConstByUserType = enumConstByUserType;
		this.loginId = loginId;
		this.password = password;
		this.loginNum = loginNum;
		this.lastLoginDate = lastLoginDate;
		this.lastLoginIp = lastLoginIp;
		this.prPriManagerSites = prPriManagerSites;
		this.peStudents = peStudents;
		this.prPriManagerMajors = prPriManagerMajors;
		this.prPriManagerEdutypes = prPriManagerEdutypes;
		this.peSitemanagers = peSitemanagers;
		this.peManagers = peManagers;
		this.prPriManagerGrades = prPriManagerGrades;
		this.peTeachers = peTeachers;
		this.peBzzStudents=peBzzStudents;
		this.peEnterpriseManager=peEnterpriseManager;
		this.trainingCourseStudent=trainingCourseStudent;
		this.prBzzPriManagerEnterprises=prBzzPriManagerEnterprises;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public EnumConst getEnumConstByFlagIsvalid() {
		return this.enumConstByFlagIsvalid;
	}

	public void setEnumConstByFlagIsvalid(EnumConst enumConstByFlagIsvalid) {
		this.enumConstByFlagIsvalid = enumConstByFlagIsvalid;
	}

	public PePriRole getPePriRole() {
		return this.pePriRole;
	}

	public void setPePriRole(PePriRole pePriRole) {
		this.pePriRole = pePriRole;
	}

	public EnumConst getEnumConstByUserType() {
		return this.enumConstByUserType;
	}

	public void setEnumConstByUserType(EnumConst enumConstByUserType) {
		this.enumConstByUserType = enumConstByUserType;
	}

	public String getLoginId() {
		return this.loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Long getLoginNum() {
		return this.loginNum;
	}

	public void setLoginNum(Long loginNum) {
		this.loginNum = loginNum;
	}

	public Date getLastLoginDate() {
		return this.lastLoginDate;
	}

	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	public String getLastLoginIp() {
		return this.lastLoginIp;
	}

	public void setLastLoginIp(String lastLoginIp) {
		this.lastLoginIp = lastLoginIp;
	}

	public Set getPeStudents() {
		return this.peStudents;
	}

	public void setPeStudents(Set peStudents) {
		this.peStudents = peStudents;
	}

	public Set getPeSitemanagers() {
		return this.peSitemanagers;
	}

	public void setPeSitemanagers(Set peSitemanagers) {
		this.peSitemanagers = peSitemanagers;
	}

	public Set getPeManagers() {
		return this.peManagers;
	}

	public void setPeManagers(Set peManagers) {
		this.peManagers = peManagers;
	}

	public Set getPeTeachers() {
		return this.peTeachers;
	}

	public void setPeTeachers(Set peTeachers) {
		this.peTeachers = peTeachers;
	}

	public Set getPrPriManagerEdutypes() {
		return prPriManagerEdutypes;
	}

	public void setPrPriManagerEdutypes(Set prPriManagerEdutypes) {
		this.prPriManagerEdutypes = prPriManagerEdutypes;
	}

	public Set getPrPriManagerGrades() {
		return prPriManagerGrades;
	}

	public void setPrPriManagerGrades(Set prPriManagerGrades) {
		this.prPriManagerGrades = prPriManagerGrades;
	}

	public Set getPrPriManagerMajors() {
		return prPriManagerMajors;
	}

	public void setPrPriManagerMajors(Set prPriManagerMajors) {
		this.prPriManagerMajors = prPriManagerMajors;
	}

	public Set getPrPriManagerSites() {
		return prPriManagerSites;
	}

	public void setPrPriManagerSites(Set prPriManagerSites) {
		this.prPriManagerSites = prPriManagerSites;
	}
	
	public Set getPeBzzStudents(){
		return this.peBzzStudents;
	}
	
	public void setPeBzzStudents(Set peBzzStudents){
		this.peBzzStudents=peBzzStudents;
	}
	
	public Set getPeEnterpriseManager(){
		return this.peEnterpriseManager;
	}
	
	public void setPeEnterpriseManager(Set peEnterpriseManager){
		this.peEnterpriseManager=peEnterpriseManager;
	}

	public Set getTrainingCourseStudent() {
		return trainingCourseStudent;
	}

	public void setTrainingCourseStudent(Set trainingCourseStudent) {
		this.trainingCourseStudent = trainingCourseStudent;
	}

	public Set getPrBzzPriManagerEnterprises() {
		return prBzzPriManagerEnterprises;
	}

	public void setPrBzzPriManagerEnterprises(Set prBzzPriManagerEnterprises) {
		this.prBzzPriManagerEnterprises = prBzzPriManagerEnterprises;
	}

}