#import <Foundation/Foundation.h>
@interface ShoppingMBProgressHUDD: NSObject
+ (BOOL)xShowhudaddedtoqAnimated:(NSInteger)Shopping;
+ (BOOL)EHidehudforviewCAnimated:(NSInteger)Shopping;
+ (BOOL)DHudforview:(NSInteger)Shopping;
+ (BOOL)EcommonInit:(NSInteger)Shopping;
+ (BOOL)eInitwithframe:(NSInteger)Shopping;
+ (BOOL)sInitwithcoder:(NSInteger)Shopping;
+ (BOOL)SInitwithview:(NSInteger)Shopping;
+ (BOOL)Ydealloc:(NSInteger)Shopping;
+ (BOOL)tShowanimated:(NSInteger)Shopping;
+ (BOOL)cHideanimated:(NSInteger)Shopping;
+ (BOOL)wHideanimatedEAfterdelay:(NSInteger)Shopping;
+ (BOOL)XHandlegracetimer:(NSInteger)Shopping;
+ (BOOL)bHandleminshowtimer:(NSInteger)Shopping;
+ (BOOL)rHandlehidetimer:(NSInteger)Shopping;
+ (BOOL)jdidMoveToSuperview:(NSInteger)Shopping;
+ (BOOL)NShowusinganimation:(NSInteger)Shopping;
+ (BOOL)VHideusinganimation:(NSInteger)Shopping;
+ (BOOL)kAnimateinfWithtypeHCompletion:(NSInteger)Shopping;
+ (BOOL)gdone:(NSInteger)Shopping;
+ (BOOL)VsetupViews:(NSInteger)Shopping;
+ (BOOL)aupdateIndicators:(NSInteger)Shopping;
+ (BOOL)XUpdateviewsforcolor:(NSInteger)Shopping;
+ (BOOL)bupdateBezelMotionEffects:(NSInteger)Shopping;
+ (BOOL)BupdateConstraints:(NSInteger)Shopping;
+ (BOOL)UlayoutSubviews:(NSInteger)Shopping;
+ (BOOL)GupdatePaddingConstraints:(NSInteger)Shopping;
+ (BOOL)CApplypriorityuToconstraints:(NSInteger)Shopping;
+ (BOOL)hSetmode:(NSInteger)Shopping;
+ (BOOL)nSetcustomview:(NSInteger)Shopping;
+ (BOOL)PSetoffset:(NSInteger)Shopping;
+ (BOOL)ASetmargin:(NSInteger)Shopping;
+ (BOOL)lSetminsize:(NSInteger)Shopping;
+ (BOOL)CSetsquare:(NSInteger)Shopping;
+ (BOOL)DSetprogressobjectdisplaylink:(NSInteger)Shopping;
+ (BOOL)gSetprogressobject:(NSInteger)Shopping;
+ (BOOL)MSetprogress:(NSInteger)Shopping;
+ (BOOL)cSetcontentcolor:(NSInteger)Shopping;
+ (BOOL)TSetdefaultmotioneffectsenabled:(NSInteger)Shopping;
+ (BOOL)vSetnsprogressdisplaylinkenabled:(NSInteger)Shopping;
+ (BOOL)SupdateProgressFromProgressObject:(NSInteger)Shopping;
+ (BOOL)qregisterForNotifications:(NSInteger)Shopping;
+ (BOOL)tunregisterFromNotifications:(NSInteger)Shopping;
+ (BOOL)DStatusbarorientationdidchange:(NSInteger)Shopping;
+ (BOOL)IUpdateforcurrentorientationanimated:(NSInteger)Shopping;

@end
