package com.whaty.platform.entity.web.action.studentStatus.degree;

import com.whaty.platform.entity.exception.EntityException;
import com.whaty.platform.entity.util.Page;
import com.whaty.platform.entity.web.action.studentStatus.stuInfo.PeStudentInfoAction;
import com.whaty.platform.util.Const;

public class PeCanApplyDegreeAction extends PeStudentInfoAction {

	@Override
	public void initGrid() {
		this.getGridConfig().setCapability(false, false, false,true);
		this.getGridConfig().setTitle(this.getText("可申请学位但未申请学生列表"));
//		this.getGridConfig().addColumn(this.getText("id"), "id", false);
		this.getGridConfig().addColumn(this.getText("id"), "id", false,false,false,"");
		this.getGridConfig().addColumn(this.getText("学号"), "reg_no");
		this.getGridConfig().addColumn(this.getText("姓名"), "true_name");
		this.getGridConfig().addColumn(this.getText("学习中心"), "peSite.name");
		this.getGridConfig().addColumn(this.getText("年级"), "peGrade.name");
		this.getGridConfig().addColumn(this.getText("专业"), "peMajor.name");
		this.getGridConfig().addColumn(this.getText("层次"), "peEdutype.name");
		this.getGridConfig().addColumn(this.getText("入学时间"), "recruit_date");
		this.getGridConfig().addColumn(this.getText("获得专科学历时间"), "prStudentInfo.graduate_year");
		this.getGridConfig().addColumn(this.getText("学位英语成绩"),"score_degree_english", false,false,true,"");
		this.getGridConfig().addColumn(this.getText("毕业论文成绩"),"paper_score", false,false,true,"");
		this.getGridConfig().addColumn(this.getText("总学分"),"total_credit");
	}

	@Override
	public void setServletPath() {
		this.servletPath = "/entity/studentStatus/peCanApplyDegree";
	}
	
	@Override
	public Page list() {
		StringBuffer sql = new StringBuffer();
		sql.append(" select xx.id,                                                                    "); 
		sql.append("        xx.reg_no,                                                                ");
		sql.append("        xx.true_name,                                                             ");
		sql.append("        peSite.name s_name,                                                       ");
		sql.append("        peGrade.name g_name,                                                      ");
		sql.append("        peMajor.name m_name,                                                      ");
		sql.append("        peEdutype.name e_name,                                                    ");
		sql.append("        recruit_date,                                                             ");
		sql.append("        prStudentInfo.graduate_year,                                              ");
		sql.append("        xx.score_degree_english,                                                  ");
		sql.append("        xx.paper_score,                                                  ");
		sql.append("        total_credit                                                              ");
		sql.append("   from pe_site peSite,                                                           ");
		sql.append("        pe_major peMajor,                                                         ");
		sql.append("        pe_grade peGrade,                                                         ");
		sql.append("        pe_edutype peEdutype,                                                     ");
		sql.append("        pr_student_info prStudentInfo,                                            ");
		sql.append("        enum_const e1,                                                            ");
		sql.append("        enum_const e2,                                                            ");
		sql.append("        enum_const c1,                                                            ");
		sql.append("        (select s.id,                                                             ");
		sql.append("                s.fk_site_id,                                                     ");
		sql.append("                s.fk_major_id,                                                    ");
		sql.append("                s.fk_grade_id,                                                    ");
		sql.append("                s.fk_edutype_id,                                                  ");
		sql.append("                s.reg_no,                                                         ");
		sql.append("                s.true_name,                                                      ");
		sql.append("                s.recruit_date,                                                   ");
		sql.append("                s.fk_student_info_id,                                             ");
		sql.append("                s.score_unite_english_a,                                          ");
		sql.append("                s.score_unite_english_b,                                          ");
		sql.append("                s.score_unite_computer,                                           ");
		sql.append("                nvl(s.score_degree_english, 0) score_degree_english,              ");
		sql.append("                pu1.min_credit p_min_credit,                                      ");
		sql.append("                nvl(pu2.sum_credit, 0) p_sum_credit,                              ");
		sql.append("                pux1.min_credit px_min_credit,                                    ");
		sql.append("                nvl(pux2.sum_credit, 0) px_sum_credit,                            ");
		sql.append("                ma1.min_credit m_min_credit,                                      ");
		sql.append("                nvl(ma2.sum_credit, 0) m_sum_credit,                              ");
		sql.append("                max1.min_credit mx_min_credit,                                    ");
		sql.append("                nvl(max2.sum_credit, 0) mx_sum_credit,                            ");
		sql.append("                to1.graduate_min_credit,                                          ");
		sql.append("                to1.flag_degree_candisobey,                                       ");
		sql.append("                nvl(main_c.no_pass_main_c, 0) no_pass_main_c,                     ");
		sql.append("                to1.degree_avg_score,                                             ");
		sql.append("                nvl(to_score.score_total, 0) / nvl(c_num.c_sum, -1) avg_score,    ");
		sql.append("                to1.degree_paper_score,                                           ");
		sql.append("                nvl(to2.total_credit, 0) total_credit,                            ");
		sql.append("                nvl(pa1.paper_score, 0) paper_score                               ");
		sql.append("           from pe_student s,                                                     ");
		sql.append("                (select tpg.min_credit, s.id                                      ");
		sql.append("                   from pe_student           s,                                   ");
		sql.append("                        pe_tch_program       tp,                                  ");
		sql.append("                        pe_tch_program_group tpg                                  ");
		sql.append("                  where tp.fk_major_id = s.fk_major_id                            ");
		sql.append("                    and tp.fk_grade_id = s.fk_grade_id                            ");
		sql.append("                    and tp.flag_major_type = s.flag_major_type                    ");
		sql.append("                    and tp.fk_edutype_id = s.fk_edutype_id                        ");
		sql.append("                    and tp.id = tpg.fk_program_id                                 ");
		sql.append("                    and tpg.fk_coursegroup_id = '"+Const.publicrequired_id+"') pu1,                        ");
		sql.append("                (select nvl(sum(credit), 0) sum_credit, s_id                      ");
		sql.append("                   from (select tpc.credit,                                       ");
		sql.append("                                tpc.fk_course_id,                                 ");
		sql.append("                                tse.score_total,                                  ");
		sql.append("                                tse.fk_stu_id,                                    ");
		sql.append("                                tpg.fk_coursegroup_id,                            ");
		sql.append("                                tpg.fk_program_id,                                ");
		sql.append("                                tpg.min_credit                                    ");
		sql.append("                           from pr_tch_program_course tpc,                        ");
		sql.append("                                pr_tch_stu_elective   tse,                        ");
		sql.append("                                pe_tch_program_group  tpg                         ");
		sql.append("                          where tse.fk_tch_program_course = tpc.id                ");
		sql.append("                            and tpc.fk_programgroup_id = tpg.id                   ");
		sql.append("                            and tse.score_total >= "+Const.mustscore+") x1,                        ");
		sql.append("                        (select s.id s_id, tp.id tp_id, tp.graduate_min_credit    ");
		sql.append("                           from pe_student s, pe_tch_program tp                   ");
		sql.append("                          where tp.fk_major_id = s.fk_major_id                    ");
		sql.append("                            and tp.fk_grade_id = s.fk_grade_id                    ");
		sql.append("                    and tp.flag_major_type = s.flag_major_type                    ");
		sql.append("                            and tp.fk_edutype_id = s.fk_edutype_id) x2            ");
		sql.append("                  where x1.fk_stu_id = x2.s_id                                    ");
		sql.append("                    and x1.fk_program_id = tp_id                                  ");
		sql.append("                    and x1.fk_coursegroup_id = '"+Const.publicrequired_id+"'                               ");
		sql.append("                  group by s_id, fk_course_id) pu2,                               ");
		sql.append("                (select tpg.min_credit, s.id                                      ");
		sql.append("                   from pe_student           s,                                   ");
		sql.append("                        pe_tch_program       tp,                                  ");
		sql.append("                        pe_tch_program_group tpg                                  ");
		sql.append("                  where tp.fk_major_id = s.fk_major_id                            ");
		sql.append("                    and tp.fk_grade_id = s.fk_grade_id                            ");
		sql.append("                    and tp.flag_major_type = s.flag_major_type                    ");
		sql.append("                    and tp.fk_edutype_id = s.fk_edutype_id                        ");
		sql.append("                    and tp.id = tpg.fk_program_id                                 ");
		sql.append("                    and tpg.fk_coursegroup_id = '"+Const.majorrequired_id+"') ma1,                        ");
		sql.append("                (select nvl(sum(credit), 0) sum_credit, s_id                      ");
		sql.append("                   from (select tpc.credit,                                       ");
		sql.append("                                tpc.fk_course_id,                                 ");
		sql.append("                                tse.score_total,                                  ");
		sql.append("                                tse.fk_stu_id,                                    ");
		sql.append("                                tpg.fk_coursegroup_id,                            ");
		sql.append("                                tpg.fk_program_id,                                ");
		sql.append("                                tpg.min_credit                                    ");
		sql.append("                           from pr_tch_program_course tpc,                        ");
		sql.append("                                pr_tch_stu_elective   tse,                        ");
		sql.append("                                pe_tch_program_group  tpg                         ");
		sql.append("                          where tse.fk_tch_program_course = tpc.id                ");
		sql.append("                            and tpc.fk_programgroup_id = tpg.id                   ");
		sql.append("                            and tse.score_total >= "+Const.mustscore+") x1,                        ");
		sql.append("                        (select s.id s_id, tp.id tp_id, tp.graduate_min_credit    ");
		sql.append("                           from pe_student s, pe_tch_program tp                   ");
		sql.append("                          where tp.fk_major_id = s.fk_major_id                    ");
		sql.append("                            and tp.fk_grade_id = s.fk_grade_id                    ");
		sql.append("                    and tp.flag_major_type = s.flag_major_type                    ");
		sql.append("                            and tp.fk_edutype_id = s.fk_edutype_id) x2            ");
		sql.append("                  where x1.fk_stu_id = x2.s_id                                    ");
		sql.append("                    and x1.fk_program_id = tp_id                                  ");
		sql.append("                    and x1.fk_coursegroup_id = '"+Const.majorrequired_id+"'                               ");
		sql.append("                  group by s_id, fk_course_id) ma2,                               ");
		sql.append("                (select tpg.min_credit, s.id                                      ");
		sql.append("                   from pe_student           s,                                   ");
		sql.append("                        pe_tch_program       tp,                                  ");
		sql.append("                        pe_tch_program_group tpg                                  ");
		sql.append("                  where tp.fk_major_id = s.fk_major_id                            ");
		sql.append("                    and tp.fk_grade_id = s.fk_grade_id                            ");
		sql.append("                    and tp.fk_edutype_id = s.fk_edutype_id                        ");
		sql.append("                    and tp.flag_major_type = s.flag_major_type                    ");
		sql.append("                    and tp.id = tpg.fk_program_id                                 ");
		sql.append("                    and tpg.fk_coursegroup_id = '"+Const.publicalternation_id+"') max1,                       ");
		sql.append("                (select nvl(sum(credit), 0) sum_credit, s_id                      ");
		sql.append("                   from (select tpc.credit,                                       ");
		sql.append("                                tpc.fk_course_id,                                 ");
		sql.append("                                tse.score_total,                                  ");
		sql.append("                                tse.fk_stu_id,                                    ");
		sql.append("                                tpg.fk_coursegroup_id,                            ");
		sql.append("                                tpg.fk_program_id,                                ");
		sql.append("                                tpg.min_credit                                    ");
		sql.append("                           from pr_tch_program_course tpc,                        ");
		sql.append("                                pr_tch_stu_elective   tse,                        ");
		sql.append("                                pe_tch_program_group  tpg                         ");
		sql.append("                          where tse.fk_tch_program_course = tpc.id                ");
		sql.append("                            and tpc.fk_programgroup_id = tpg.id                   ");
		sql.append("                            and tse.score_total >= "+Const.mustscore+") x1,                        ");
		sql.append("                        (select s.id s_id, tp.id tp_id, tp.graduate_min_credit    ");
		sql.append("                           from pe_student s, pe_tch_program tp                   ");
		sql.append("                          where tp.fk_major_id = s.fk_major_id                    ");
		sql.append("                            and tp.fk_grade_id = s.fk_grade_id                    ");
		sql.append("                    and tp.flag_major_type = s.flag_major_type                    ");
		sql.append("                            and tp.fk_edutype_id = s.fk_edutype_id) x2            ");
		sql.append("                  where x1.fk_stu_id = x2.s_id                                    ");
		sql.append("                    and x1.fk_program_id = tp_id                                  ");
		sql.append("                    and x1.fk_coursegroup_id = '"+Const.publicalternation_id+"'                               ");
		sql.append("                  group by s_id, fk_course_id) max2,                              ");
		sql.append("                (select tpg.min_credit, s.id                                      ");
		sql.append("                   from pe_student           s,                                   ");
		sql.append("                        pe_tch_program       tp,                                  ");
		sql.append("                        pe_tch_program_group tpg                                  ");
		sql.append("                  where tp.fk_major_id = s.fk_major_id                            ");
		sql.append("                    and tp.fk_grade_id = s.fk_grade_id                            ");
		sql.append("                    and tp.fk_edutype_id = s.fk_edutype_id                        ");
		sql.append("                    and tp.flag_major_type = s.flag_major_type                    ");
		sql.append("                    and tp.id = tpg.fk_program_id                                 ");
		sql.append("                    and tpg.fk_coursegroup_id = '"+Const.publicalternation_id+"') pux1,                       ");
		sql.append("                (select nvl(sum(credit), 0) sum_credit, fk_stu_id                 ");
		sql.append("                   from (select tpc.credit,                                       ");
		sql.append("                                tpc.fk_course_id,                                 ");
		sql.append("                                tse.score_total,                                  ");
		sql.append("                                tse.fk_stu_id,                                    ");
		sql.append("                                tpg.fk_coursegroup_id,                            ");
		sql.append("                                tpg.fk_program_id,                                ");
		sql.append("                                tpg.min_credit                                    ");
		sql.append("                           from pr_tch_program_course tpc,                        ");
		sql.append("                                pr_tch_stu_elective   tse,                        ");
		sql.append("                                pe_tch_program_group  tpg                         ");
		sql.append("                          where tse.fk_tch_program_course = tpc.id                ");
		sql.append("                            and tpc.fk_programgroup_id = tpg.id                   ");
		sql.append("                            and tse.score_total >= "+Const.mustscore+"                             ");
		sql.append("                         minus                                                    ");
		sql.append("                         select x1.*                                              ");
		sql.append("                           from (select tpc.credit,                               ");
		sql.append("                                        tpc.fk_course_id,                         ");
		sql.append("                                        tse.score_total,                          ");
		sql.append("                                        tse.fk_stu_id,                            ");
		sql.append("                                        tpg.fk_coursegroup_id,                    ");
		sql.append("                                        tpg.fk_program_id,                        ");
		sql.append("                                        tpg.min_credit                            ");
		sql.append("                                   from pr_tch_program_course tpc,                ");
		sql.append("                                        pr_tch_stu_elective   tse,                ");
		sql.append("                                        pe_tch_program_group  tpg                 ");
		sql.append("                                  where tse.fk_tch_program_course = tpc.id        ");
		sql.append("                                    and tpc.fk_programgroup_id = tpg.id           ");
		sql.append("                                    and tse.score_total >= "+Const.mustscore+") x1,                ");
		sql.append("                                (select s.id s_id,                                ");
		sql.append("                                        tp.id tp_id,                              ");
		sql.append("                                        tp.graduate_min_credit                    ");
		sql.append("                                   from pe_student s, pe_tch_program tp           ");
		sql.append("                                  where tp.fk_major_id = s.fk_major_id            ");
		sql.append("                                    and tp.fk_grade_id = s.fk_grade_id            ");
		sql.append("                    and tp.flag_major_type = s.flag_major_type                    ");
		sql.append("                                    and tp.fk_edutype_id = s.fk_edutype_id) x2    ");
		sql.append("                          where x1.fk_stu_id = x2.s_id                            ");
		sql.append("                            and x1.fk_program_id = tp_id)                         ");
		sql.append("                  group by fk_stu_id) pux2,                                       ");
		sql.append("                (select tp.graduate_min_credit,                                   ");
		sql.append("                        s.id,                                                     ");
		sql.append("                        tp.flag_degree_candisobey,                                ");
		sql.append("                        tp.degree_avg_score,                                      ");
		sql.append("                        tp.degree_paper_score                                     ");
		sql.append("                   from pe_student s, pe_tch_program tp                           ");
		sql.append("                  where tp.fk_major_id = s.fk_major_id                            ");
		sql.append("                    and tp.fk_grade_id = s.fk_grade_id                            ");
		sql.append("                    and tp.flag_major_type = s.flag_major_type                    ");
		sql.append("                    and tp.fk_edutype_id = s.fk_edutype_id) to1,                  ");
		sql.append("                (select nvl(sum(pc.credit), 0) total_credit, fk_stu_id            ");
		sql.append("                   from pr_tch_stu_elective se, pr_tch_program_course pc          ");
		sql.append("                  where se.fk_tch_program_course = pc.id                          ");
		sql.append("                    and se.score_total >= "+Const.mustscore+"                                      ");
		sql.append("                  group by fk_stu_id) to2,                                        ");
		sql.append("                (select max(score_total) paper_score, fk_stu_id                   ");
		sql.append("                   from pr_tch_stu_paper                                          ");
		sql.append("                  group by fk_stu_id) pa1,                                        ");
		sql.append("                (select id, count(*) no_pass_main_c                               ");
		sql.append("                   from ((select id, score                                        ");
		sql.append("                            from (select s.id, tpc.fk_course_id                   ");
		sql.append("                                    from pe_student            s,                 ");
		sql.append("                                         pe_tch_program        tp,                ");
		sql.append("                                         pe_tch_program_group  tpg,               ");
		sql.append("                                         pr_tch_program_course tpc,               ");
		sql.append("                                         enum_const            ec                 ");
		sql.append("                                   where s.fk_edutype_id = tp.fk_edutype_id       ");
		sql.append("                                     and s.fk_grade_id = tp.fk_grade_id           ");
		sql.append("                                     and s.fk_major_id = tp.fk_major_id           ");
		sql.append("                    and tp.flag_major_type = s.flag_major_type                    ");
		sql.append("                                     and tpg.fk_program_id = tp.id                ");
		sql.append("                                     and tpc.fk_programgroup_id = tpg.id          ");
		sql.append("                                     and tpc.flag_is_main_course = ec.id          ");
		sql.append("                                     and ec.code = '1') kc,                       ");
		sql.append("                                 (select esmc.score,                              ");
		sql.append("                                         eomc.fk_course_id,                       ");
		sql.append("                                         esmc.fk_student_id                       ");
		sql.append("                                    from pr_exam_stu_maincourse  esmc,            ");
		sql.append("                                         pr_exam_open_maincourse eomc             ");
		sql.append("                                   where esmc.fk_exam_open_maincourse_id =        ");
		sql.append("                                         eomc.id) se                              ");
		sql.append("                           where kc.fk_course_id = se.fk_course_id(+)             ");
		sql.append("                             and kc.id = se.fk_student_id                         ");
		sql.append("                             and se.score < "+Const.mustmainscore+"))                                  ");
		sql.append("                  group by id) main_c,                                            ");
		sql.append("                (select nvl(sum(score_total), 0) score_total, fk_stu_id           ");
		sql.append("                   from (select nvl(se.score_total, 0) score_total,               ");
		sql.append("                                se.fk_stu_id                                      ");
		sql.append("                           from pr_tch_stu_elective   se,                         ");
		sql.append("                                pr_tch_program_course pc                          ");
		sql.append("                          where se.fk_tch_program_course = pc.id                  ");
		sql.append("                            and (se.id, se.fk_stu_id) in (                        ");
		sql.append("                            (select tse.id,                                       ");
		sql.append("                                    tse.fk_stu_id                                 ");
		sql.append("                             from pr_tch_program_course tpc,                      ");
		sql.append("                                  pr_tch_stu_elective   tse,                      ");
		sql.append("                                  pe_tch_program_group  tpg,                      ");
		sql.append("                                  pe_tch_coursegroup    tcg                       ");
		sql.append("                            where tse.fk_tch_program_course =                     ");
		sql.append("                                  tpc.id                                          ");
		sql.append("                              and tpg.fk_coursegroup_id =                         ");
		sql.append("                                  tcg.id                                          ");
		sql.append("                              and tpc.fk_programgroup_id =                        ");
		sql.append("                                  tpg.id                                          ");
		sql.append("                              and tse.score_total >= "+Const.mustscore+"                           ");
		sql.append("                           minus                                                  ");
		sql.append("                           select x1.id,                                          ");
		sql.append("                                  x1.fk_stu_id                                    ");
		sql.append("                             from (select tse.id,                                 ");
		sql.append("                                          tse.fk_stu_id,                          ");
		sql.append("                                          tpg.fk_program_id                       ");
		sql.append("                                     from pr_tch_program_course tpc,              ");
		sql.append("                                          pr_tch_stu_elective   tse,              ");
		sql.append("                                          pe_tch_program_group  tpg,              ");
		sql.append("                                          pe_tch_coursegroup    tcg               ");
		sql.append("                                    where tse.fk_tch_program_course =             ");
		sql.append("                                          tpc.id                                  ");
		sql.append("                                      and tpg.fk_coursegroup_id =                 ");
		sql.append("                                          tcg.id                                  ");
		sql.append("                                      and tpc.fk_programgroup_id =                ");
		sql.append("                                          tpg.id                                  ");
		sql.append("                                      and tse.score_total >= "+Const.mustscore+") x1,              ");
		sql.append("                                  (select s.id s_id,                              ");
		sql.append("                                          tp.id tp_id,                            ");
		sql.append("                                          tp.graduate_min_credit                  ");
		sql.append("                                     from pe_student     s,                       ");
		sql.append("                                          pe_tch_program tp                       ");
		sql.append("                                    where tp.fk_major_id =                        ");
		sql.append("                                          s.fk_major_id                           ");
		sql.append("                                      and tp.fk_grade_id =                        ");
		sql.append("                                          s.fk_grade_id                           ");
		sql.append("                    and tp.flag_major_type = s.flag_major_type                    ");
		sql.append("                                      and tp.fk_edutype_id =                      ");
		sql.append("                                          s.fk_edutype_id) x2                     ");
		sql.append("                            where x1.fk_stu_id =                                  ");
		sql.append("                                  x2.s_id                                         ");
		sql.append("                              and x1.fk_program_id =                              ");
		sql.append("                                  tp_id) union                                    ");
		sql.append("                           select x1.id, x1.fk_stu_id                             ");
		sql.append("                             from (select tpc.credit,                             ");
		sql.append("                                    tpc.fk_course_id,                             ");
		sql.append("                                    tse.score_total,                              ");
		sql.append("                                    tse.fk_stu_id,                                ");
		sql.append("                                    tse.id,                                       ");
		sql.append("                                    tcg.name,                                     ");
		sql.append("                                    tpg.fk_program_id,                            ");
		sql.append("                                    tpg.min_credit                                ");
		sql.append("                               from pr_tch_program_course tpc,                    ");
		sql.append("                                    pr_tch_stu_elective   tse,                    ");
		sql.append("                                    pe_tch_program_group  tpg,                    ");
		sql.append("                                    pe_tch_coursegroup    tcg                     ");
		sql.append("                              where tse.fk_tch_program_course =                   ");
		sql.append("                                    tpc.id                                        ");
		sql.append("                                and tpg.fk_coursegroup_id = tcg.id                ");
		sql.append("                                and tpc.fk_programgroup_id = tpg.id) x1,          ");
		sql.append("                            (select s.id s_id,                                    ");
		sql.append("                                    tp.id tp_id,                                  ");
		sql.append("                                    tp.graduate_min_credit                        ");
		sql.append("                               from pe_student s, pe_tch_program tp               ");
		sql.append("                              where tp.fk_major_id = s.fk_major_id                ");
		sql.append("                                and tp.fk_grade_id = s.fk_grade_id                ");
		sql.append("                    and tp.flag_major_type = s.flag_major_type                    ");
		sql.append("                                and tp.fk_edutype_id =                            ");
		sql.append("                                    s.fk_edutype_id) x2                           ");
		sql.append("                            where x1.fk_stu_id = x2.s_id                          ");
		sql.append("                              and x1.fk_program_id = tp_id)                       ");
		sql.append("                         )                                                        ");
		sql.append("                  group by fk_stu_id) to_score,                                   ");
		sql.append("                                                                                  ");
		sql.append("                (select nvl(count(*), -1) c_sum, fk_stu_id                        ");
		sql.append("                   from ((select tse.id, tse.fk_stu_id                            ");
		sql.append("                            from pr_tch_program_course tpc,                       ");
		sql.append("                                 pr_tch_stu_elective   tse,                       ");
		sql.append("                                 pe_tch_program_group  tpg,                       ");
		sql.append("                                 pe_tch_coursegroup    tcg                        ");
		sql.append("                           where tse.fk_tch_program_course = tpc.id               ");
		sql.append("                             and tpg.fk_coursegroup_id = tcg.id                   ");
		sql.append("                             and tpc.fk_programgroup_id = tpg.id                  ");
		sql.append("                             and tse.score_total >= "+Const.mustscore+"                            ");
		sql.append("                          minus                                                   ");
		sql.append("                          select x1.id, x1.fk_stu_id                              ");
		sql.append("                            from (select tse.id,                                  ");
		sql.append("                                         tse.fk_stu_id,                           ");
		sql.append("                                         tpg.fk_program_id                        ");
		sql.append("                                    from pr_tch_program_course tpc,               ");
		sql.append("                                         pr_tch_stu_elective   tse,               ");
		sql.append("                                         pe_tch_program_group  tpg,               ");
		sql.append("                                         pe_tch_coursegroup    tcg                ");
		sql.append("                                   where tse.fk_tch_program_course = tpc.id       ");
		sql.append("                                     and tpg.fk_coursegroup_id = tcg.id           ");
		sql.append("                                     and tpc.fk_programgroup_id = tpg.id          ");
		sql.append("                                     and tse.score_total >= "+Const.mustscore+") x1,               ");
		sql.append("                                 (select s.id s_id,                               ");
		sql.append("                                         tp.id tp_id,                             ");
		sql.append("                                         tp.graduate_min_credit                   ");
		sql.append("                                    from pe_student s, pe_tch_program tp          ");
		sql.append("                                   where tp.fk_major_id = s.fk_major_id           ");
		sql.append("                                     and tp.fk_grade_id = s.fk_grade_id           ");
		sql.append("                    and tp.flag_major_type = s.flag_major_type                    ");
		sql.append("                                     and tp.fk_edutype_id = s.fk_edutype_id) x2   ");
		sql.append("                           where x1.fk_stu_id = x2.s_id                           ");
		sql.append("                             and x1.fk_program_id = tp_id) union                  ");
		sql.append("                          select x1.id, x1.fk_stu_id                              ");
		sql.append("                            from (select tpc.credit,                              ");
		sql.append("                                         tpc.fk_course_id,                        ");
		sql.append("                                         tse.score_total,                         ");
		sql.append("                                         tse.fk_stu_id,                           ");
		sql.append("                                         tse.id,                                  ");
		sql.append("                                         tcg.name,                                ");
		sql.append("                                         tpg.fk_program_id,                       ");
		sql.append("                                         tpg.min_credit                           ");
		sql.append("                                    from pr_tch_program_course tpc,               ");
		sql.append("                                         pr_tch_stu_elective   tse,               ");
		sql.append("                                         pe_tch_program_group  tpg,               ");
		sql.append("                                         pe_tch_coursegroup    tcg                ");
		sql.append("                                   where tse.fk_tch_program_course = tpc.id       ");
		sql.append("                                     and tpg.fk_coursegroup_id = tcg.id           ");
		sql.append("                                     and tpc.fk_programgroup_id = tpg.id) x1,     ");
		sql.append("                                 (select s.id s_id,                               ");
		sql.append("                                         tp.id tp_id,                             ");
		sql.append("                                         tp.graduate_min_credit                   ");
		sql.append("                                    from pe_student s, pe_tch_program tp          ");
		sql.append("                                   where tp.fk_major_id = s.fk_major_id           ");
		sql.append("                                     and tp.fk_grade_id = s.fk_grade_id           ");
		sql.append("                    and tp.flag_major_type = s.flag_major_type                    ");
		sql.append("                                     and tp.fk_edutype_id = s.fk_edutype_id) x2   ");
		sql.append("                           where x1.fk_stu_id = x2.s_id                           ");
		sql.append("                             and x1.fk_program_id = tp_id)                        ");
		sql.append("                           group by fk_stu_id                                     ");
		sql.append("                 ) c_num                                                          ");
		sql.append("          where s.id = pu1.id(+)                                                  ");
		sql.append("            and s.id = pu2.s_id(+)                                                ");
		sql.append("            and s.id = ma1.id(+)                                                  ");
		sql.append("            and s.id = ma2.s_id(+)                                                ");
		sql.append("            and s.id = pux1.id(+)                                                 ");
		sql.append("            and s.id = pux2.fk_stu_id(+)                                          ");
		sql.append("            and s.id = max1.id(+)                                                 ");
		sql.append("            and s.id = max2.s_id(+)                                               ");
		sql.append("            and s.id = to1.id(+)                                                  ");
		sql.append("            and s.id = to2.fk_stu_id(+)                                           ");
		sql.append("            and s.id = main_c.id(+)                                               ");
		sql.append("            and s.id = to_score.fk_stu_id(+)                                      ");
		sql.append("            and s.id = c_num.fk_stu_id(+)                                         ");
		sql.append("            and s.id in ((select id                                               ");
		sql.append("                            from pe_student                                       ");
		sql.append("                          minus (select sa.fk_student_id                          ");
		sql.append("                                  from system_apply sa, enum_const e              ");
		sql.append("                                 where sa.apply_type = e.id                       ");
		sql.append("                                   and e.code = '9')) minus                       ");
		sql.append("           select e.fk_stu_id                                                     ");
		sql.append("             from pr_tch_stu_elective e, enum_const ec                            ");
		sql.append("            where e.flag_score_status = ec.id                                     ");
		sql.append("              and (ec.code = '3'or ec.code = '4')) and s.id = pa1.fk_stu_id(+)                     ");
		sql.append("         ) xx                                                                     ");
		sql.append("  where xx.fk_site_id = peSite.id                                                 ");
		sql.append("    and xx.fk_major_id = peMajor.id                                               ");
		sql.append("    and xx.fk_grade_id = peGrade.id                                               ");
		sql.append("    and xx.fk_edutype_id = peEdutype.id                                           ");
		sql.append("    and xx.fk_student_info_id = prStudentInfo.id                                  ");
		sql.append("    and e1.id(+) = xx.score_unite_english_a                                       ");
		sql.append("    and e2.id(+) = xx.score_unite_english_b                                       ");
		sql.append("    and c1.id(+) = xx.score_unite_computer                                        ");
		sql.append("    and p_min_credit <= p_sum_credit                                              ");
		sql.append("    and px_min_credit <= px_sum_credit                                            ");
		sql.append("    and m_min_credit <= m_sum_credit                                              ");
		sql.append("    and mx_min_credit <= mx_sum_credit                                            ");
		sql.append("    and graduate_min_credit <= total_credit                                       ");
		sql.append("    and avg_score >= degree_avg_score                                             ");
		sql.append("    and no_pass_main_c = 0                                                        ");
		sql.append("    and score_degree_english <= "+Const.mustEnglishDegreeScore+"                                                ");
		sql.append("    and paper_score >= degree_paper_score                                         ");
		sql.append("    and (e1.code = 0 or e2.code = 0)                                              ");
		sql.append("    and c1.code = 0                                                               ");
		this.setSqlCondition(sql);
		Page page = null;
		try {
			page = this.getGeneralService().getByPageSQL(sql.toString(), Integer.parseInt(this.getLimit()), Integer.parseInt(this.getStart()));
		} catch (EntityException e) {
			e.printStackTrace();
		}
		
		return page;
		//return super.list();
	}

}
