package com.whaty.platform.info.bean;

import java.util.HashSet;
import java.util.Set;


/**
 * InfoNewsType generated by MyEclipse - Hibernate Tools
 */

public class InfoNewsType  implements java.io.Serializable {


    // Fields    

     private String id;
     private InfoNewsType infoNewsType;
     private String name;
     private String note;
     private String status;
     private String tag;
     private Set infoUserRights = new HashSet(0);
     private Set infoNewsTypes = new HashSet(0);
     private Set infoNewses = new HashSet(0);


    // Constructors

    /** default constructor */
    public InfoNewsType() {
    }

    
    /** full constructor */
    public InfoNewsType(InfoNewsType infoNewsType, String name, String note, String status, String tag, Set infoUserRights, Set infoNewsTypes, Set infoNewses) {
        this.infoNewsType = infoNewsType;
        this.name = name;
        this.note = note;
        this.status = status;
        this.tag = tag;
        this.infoUserRights = infoUserRights;
        this.infoNewsTypes = infoNewsTypes;
        this.infoNewses = infoNewses;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public InfoNewsType getInfoNewsType() {
        return this.infoNewsType;
    }
    
    public void setInfoNewsType(InfoNewsType infoNewsType) {
        this.infoNewsType = infoNewsType;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public String getTag() {
        return this.tag;
    }
    
    public void setTag(String tag) {
        this.tag = tag;
    }

    public Set getInfoUserRights() {
        return this.infoUserRights;
    }
    
    public void setInfoUserRights(Set infoUserRights) {
        this.infoUserRights = infoUserRights;
    }

    public Set getInfoNewsTypes() {
        return this.infoNewsTypes;
    }
    
    public void setInfoNewsTypes(Set infoNewsTypes) {
        this.infoNewsTypes = infoNewsTypes;
    }

    public Set getInfoNewses() {
        return this.infoNewses;
    }
    
    public void setInfoNewses(Set infoNewses) {
        this.infoNewses = infoNewses;
    }
   








}