package com.whaty.platform.info.bean;

import java.util.Date;


/**
 * InfoNews generated by MyEclipse - Hibernate Tools
 */

public class InfoNews  implements java.io.Serializable {


    // Fields    

     private String id;
     private InfoNewsType infoNewsType;
     private String title;
     private String reporter;
     private Date reportDate;
     private String body;
     private Date submitDate;
     private SubmitManager submitManager;
     private Long isactive;
     private Long istop;
     private Long topSequence;
     private Long ispop;
     private String propertystring;
     private Long isconfirm;
     private String shortTitle;
     private String picLink;
     private ConfirmManager confirmManager;
     private Long readCount;
     private String displayDate;				//用于页面显示指定格式的reportDate字段


    // Constructors

    public String getDisplayDate() {
		return displayDate;
	}

	public void setDisplayDate(String displayDate) {
		this.displayDate = displayDate;
	}

	/** default constructor */
    public InfoNews() {
    }

	/** minimal constructor */
    public InfoNews(Date submitDate) {
        this.submitDate = submitDate;
    }
    
    /** full constructor */
    public InfoNews(InfoNewsType infoNewsType, String title, String reporter, Date reportDate, String body, Date submitDate, SubmitManager submitManager, Long isactive, Long istop, Long topSequence, Long ispop, String propertystring, Long isconfirm, String shortTitle, String picLink, ConfirmManager confirmManager, Long readCount) {
        this.infoNewsType = infoNewsType;
        this.title = title;
        this.reporter = reporter;
        this.reportDate = reportDate;
        this.body = body;
        this.submitDate = submitDate;
        this.submitManager = submitManager;
        this.isactive = isactive;
        this.istop = istop;
        this.topSequence = topSequence;
        this.ispop = ispop;
        this.propertystring = propertystring;
        this.isconfirm = isconfirm;
        this.shortTitle = shortTitle;
        this.picLink = picLink;
        this.readCount = readCount;
        this.confirmManager = confirmManager;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public InfoNewsType getInfoNewsType() {
        return this.infoNewsType;
    }
    
    public void setInfoNewsType(InfoNewsType infoNewsType) {
        this.infoNewsType = infoNewsType;
    }

    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    public String getReporter() {
        return this.reporter;
    }
    
    public void setReporter(String reporter) {
        this.reporter = reporter;
    }

    public Date getReportDate() {
        return this.reportDate;
    }
    
    public void setReportDate(Date reportDate) {
        this.reportDate = reportDate;
    }

    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }

    public Date getSubmitDate() {
        return this.submitDate;
    }
    
    public void setSubmitDate(Date submitDate) {
        this.submitDate = submitDate;
    }


    public Long getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Long isactive) {
        this.isactive = isactive;
    }

    public Long getIstop() {
        return this.istop;
    }
    
    public void setIstop(Long istop) {
        this.istop = istop;
    }

    public Long getTopSequence() {
        return this.topSequence;
    }
    
    public void setTopSequence(Long topSequence) {
        this.topSequence = topSequence;
    }

    public Long getIspop() {
        return this.ispop;
    }
    
    public void setIspop(Long ispop) {
        this.ispop = ispop;
    }

    public String getPropertystring() {
        return this.propertystring;
    }
    
    public void setPropertystring(String propertystring) {
        this.propertystring = propertystring;
    }

    public Long getIsconfirm() {
        return this.isconfirm;
    }
    
    public void setIsconfirm(Long isconfirm) {
        this.isconfirm = isconfirm;
    }

    public String getShortTitle() {
        return this.shortTitle;
    }
    
    public void setShortTitle(String shortTitle) {
        this.shortTitle = shortTitle;
    }

    public String getPicLink() {
        return this.picLink;
    }
    
    public void setPicLink(String picLink) {
        this.picLink = picLink;
    }


    public Long getReadCount() {
        return this.readCount;
    }
    
    public void setReadCount(Long readCount) {
        this.readCount = readCount;
    }

	public ConfirmManager getConfirmManager() {
		return confirmManager;
	}

	public void setConfirmManager(ConfirmManager confirmManager) {
		this.confirmManager = confirmManager;
	}

	public SubmitManager getSubmitManager() {
		return submitManager;
	}

	public void setSubmitManager(SubmitManager submitManager) {
		this.submitManager = submitManager;
	}







}