package cn.zeppin.product.utility;


public class TableColumn {

	public static final String[] TGgJgxxb = {"jrxkzh","xtjgdm","xtjgmc","tyshxydm","zczb","zcdq","clsj","yyzt","frxm","jgdz","yzbm","gsgs","cjrq"};
	public static final String[] TGgYgxxb = {"jrxkzh","xtjgdm","xtjgmc","yggh","ygxm","zjlx","zjhm","lxdh","ssbm","zw","sfgg","ygzt","cjrq"};
	public static final String[] TGgGdxxb = {"jrxkzh","xtjgdm","xtjgmc","gdmc","gdlx","gdlb","gdzjlx","gdzjhm","kgfs","cgbl","gdzt","cjrq"};
	public static final String[] TKjXtnbkmdzb = {"jrxkzh","xtjgdm","xtjgmc","xtkjkmbh","xtkjkmmc","xtxmbh","xtzxmbh","xtkjkmjc","sjkmbh","sjkmmc","gsywdl","gsywzl","cjrq"};
	public static final String[] TKjXtxmzzkjqkmb = {"jrxkzh","xtjgdm","xtjgmc","xtxmbh","xtzxmbh","kjrq","bszq","xtzzkjkmbh","xtzzkjkmmc","xtzzkjkmjc","xtzzkjkmlx","qcjfye","qcdfye","bqjffse","bqdffse","qmjfye","qmdfye","hsbz","cjrq"};
	public static final String[] TKjXtxmzcfztjb = {"jrxkzh","xtjgdm","xtjgmc","xtxmbh","xtzxmbh","xttjkmbh","xttjkmmc","xttjkmje","bszq","tjrq","bz","cjrq"};
	public static final String[] TKjGynbkmdzb = {"jrxkzh","gykjkmbh","gykjkmmc","gykjkmjc","sjkmbh","sjkmmc","gsywdl","gsywzl","cjrq"};
	public static final String[] TKjGyzzkjqkmb = {"jrxkzh","xtjgdm","xtjgmc","kjrq","bszq","gyzzkjkmbh","gyzzkjkmmc","gyzzkjkmjc","gyzzkjkmlx","qcjfye","qcdfye","bqjffse","bqdffse","qmjfye","qmdfye","hsbz","cjrq"};
	public static final String[] TKjGyzcfzkmtjb = {"jrxkzh","gytjkmbh","gytjkmmc","gytjkmje","qxlx","tjrq","bz","cjrq"};
	public static final String[] TKhXtkhgr = {"jrxkzh","xtjgdm","xtjgmc","khbh","khqc","zjlx","zjhm","ssgb","ssdq","jzdq","txdz","yzbm","sj","dh","cz","sfbgs","gllx","cjrq"};
	public static final String[] TKhXtkhjg = {"jrxkzh","xtjgdm","xtjgmc","khbh","khqc","khlx","zjlx","zjhm","tyshxydm","ssgb","ssdq","tsdz","yzbm","dh","cz","sfjtkh","ssjtkhbh","gllx","cjrq"};
	public static final String[] TKhJydsgr = {"jrxkzh","xtjgdm","xtjgmc","dsbh","syrqc","zjlx","zjhm","ssgb","ssdq","jzdz","zy","grnsr","jtnsr","gxlx","lxdh","czdh","yzbm","gzdwdz","cjrq"};
	public static final String[] TKhJydsjg = {"jrxkzh","xtjgdm","xtjgmc","dsbh","jydsqc","xhlb","shxydm","zjlx","zjhm","ssgb","ssdq","qygm","qyxz","hyfl","hymx","zclb","zczb","zcdz","fddbr","fddbrzjlx","fddbrzjhm","qyclrq","djdqrq","qyzzc","qyzfz","ssbz","ssd","sfjt","jtmc","snbz","jjcf","ptbz","ptzfmc","ptzfjb","gllx","czdh","yzbm","txdz","cjrq"};
	public static final String[] TKhJydsjggdxx = {"xtjgdm","jrxkzh","xtjgmc","shxydm","dsbh","gdlx","gdmc","kgfs","cgbl","zjlx","gdzjhm","cjrq"};
	public static final String[] TKhDsfhzjgxx = {"jrxkzh","xtjgdm","xtjgmc","dsfjgbh","shxydm","dsflx","dsfmc","zjlx","zjdm","fddbr","fddbrzjlx","fddbrzjhm","zczb","nbpj","clrq","sfdj","djlx","djrq","djbh","cjrq"};
	public static final String[] TKhTzgwhtb = {"xtjgdm","jrxkzh","xtjgmc","sjhtbh","hzhtmc","xtxmbh","xtzxmbm","tzgwjgbh","tzgwmc","qdrq","qzlsqk","gwfl","sfgt","gtje","ydcstzjm","ydtzblxz","ydyjx","ydbcx","ydpcx","dsfjglx","frdbmc","zjlx","zjhm","zczb","nbpj","cjrq"};
	public static final String[] TXmXtxmxx = {"jrxkzh","xtjgdm","xtjgmc","xtxmbm","xtzxmbh","xtxmqc","xtywfl","dyjhbz","xmclr","yjdqr","xmzzr","qxsm","slfs","syfs","xtgn","ywtz","strzz","glyyhcffs","yxfs","kfpd","jgsx","yxlhsyqbl","tzfw","glfs","hzms","xmhzly","hzjgbh","hzjgmc","sfjttj","jtnbjgmc","jfjzx","jzpgpd","jzplpd","zcglbgpd","xtxcgm","xtcsclfe","csrgjg","bsjtfs","xtbcl","zdyqsyl","zgyqsyl","ktqzz","kshbz","cpzxbz","zxjglx","zxxs","ztjd","xmtotbs","glmxm","ssbm","xmjlbh","xmzgbh","jsbz","sfxjl","sfsx","fgldbh","cjrq"};
	public static final String[] TXmXtzhxx = {"jrxkzh","xtjgdm","xtjgmc","xtxmbm","xtzxmbh","zhbh","xtzhzh","xtzhlx","zhzt","khjgmc","zjhm","zhdzpd","sftg","tgrmc","tgrjrxkz","zhswglfs","zhyjbgfs","ye","bz","cjrq"};
	public static final String[] TXmXtzjmjhtxx = {"jrxkzh","xtjgdm","xtjgmc","wtrbh","wtrlx","syqbh","xtxmbh","xtzxmbm","xtxmqc","nbhtbh","wbhtbh","wthtmc","xsfs","xssmc","jfzclx","wtrqc","htqdd","qdrq","wtje","sczjdzr","wtzjxz","sfjrjglccp","clcpbh","cjrq"};
	public static final String[] TXmXtzjyyhtxx = {"xtjgdm","jrxkzh","xtjgmc","xtxmbh","xtzxmbm","yyhtbh","yyhtmc","ywzl","dsflx","dsfbh","htqdrq","scfkrq","htdqrq","htqdje","htqyll","jydsnhzjcb","txhy","txhymx","zjtxdq","zjyyfs","hkfs","tqzz","tcfs","zcwjfl","bdzclx","bdzcmc","bdzcrzjz","yshth","ysdsflx","ysdsfbh","trzye","cjrq"};
	public static final String[] TXmFdcjsxmxx = {"jrxkzh","xtjgdm","xtjgmc","xtxmbh","xtzxmbm","trzhtbh","fdcxmlx","xmjtmc","xmdlwz","xxszdyb","kfszzjgdm","kfszz","ztzje","zjzmj","zzdmj","rjl","zbjbl","gytdsyz","gytdsyzh","jsydghxkz","jsydghxkzh","jzgcghxkz","jzgcghxkzh","jzgcsgxkz","jzgcsgxkzh","xmyjddkze","xmsfyjrsgjd","xmwgjd","sfqdysxkz","ysxkzhm","xmsfyksxs","xmxsjd","xmxshkze","xshkzjjkap","xtgsdxmdpj","cjrq"};
	public static final String[] TXmFfdcjsxmxx = {"xtjgdm","jrxkzh","xtjgmc","xtxmbm","xtzxmbm","trzhtbh","xmjtmc","xmlx","pzxmwjmc","pzxmwjbh","xmztzje","xmzbjbl","cjrq"};
	public static final String[] TXmXtdbhtb = {"xtjgdm","jrxkzh","xtjgmc","xtxmbm","xtzxmbm","dbhtbh","wbhtbh","dbhtlx","dblx","dbrlx","dbrbh","dbqsrq","dbdqrq","dbhtzt","dbhtqdrq","dbhtsxrq","dbhtdqrq","dbbz","dbzje","dbwpxh","bzlx","bzrlx","sfjkrglf","cjrq"};
	public static final String[] TXmXtdbgxb = {"xtjgdm","jrxkzh","xtjgmc","dbhtbh","bdbhtbh","cjrq"};
	public static final String[] TXmXtdzywb = {"xtjgdm","jrxkzh","xtjgmc","xtxmbm","xtzxmbm","zhdywbh","dbhth","zhdywmc","zhdywlx","zhdywzmjz","bz","yxrdjz","pgjz","pgrq","pgjgmc","zhdyl","dywsyqrmc","ydyjz","djrq","swsqrq","djjg","czjg","dbqsrq","dbdqrq","zypzzh","zypzlx","zypzhm","zypzje","zywbgfs","zywpgfs","zypzqfjg","zypzklrq","bxdh","hbrq","qzdjhm","qzmc","qzyxdqrq","djyxzzrq","sfnrbwhs","bwhsksrq","cjrq"};
	public static final String[] TXmXtxmsyqb = {"xtjgdm","jrxkzh","xtjgmc","syqbh","xtxmbm","xtzxmbm","syqlx","syqlbqsr","syqlbdqr","syqyxfs","syqkfpd","syfppd","syfpfs","fhfs","syljtfs","syqyqsyl","yqsylsm","cjrq"};
	public static final String[] TXmXtxmqsxx = {"xtjgdm","jrxkzh","xtjgmc","xtxmbm","xtzxmbmh","qsrq","sfaydrqqs","ssxtye","xtbjljjfe","xtsyljfpe","tzgwljjbbc","tzgwljyjbc","strljjbbc","strljyjbc","xtfy","xtfyl","sjsy","sjsyl","sjxtbcl","sunshie","shesuje","pfje","cjrq"};
	public static final String[] TXmXtxmyjhklypgb = {"jrxkzh","xtjgdm","xtjgmc","xtxmbm","xtzxmbh","xtxmqc","pgxh","jyxxjl","fdcsxsr","xtzczrhcsbx","tdcrsr","zxfyfh","zxsfh","bot","czdd","qtje","pgzq","pgrq","htbh","cjrq"};
	public static final String[] TJyXtzjmjjfpl = {"jrxkzh","xtjgdm","xtjgmc","jylsbh","jysj","ywbz","zjfx","xtxmbh","xtzxmbh","xthtbh","sypjbh","zrdjbh","srrlx","srrbh","fhfs","hsbz","dwjz","jyje","jyfe","jyfy","syje","bfzh","bfkhhmc","bfkhhbh","dfzh","dfkhhmc","dfkhhbh","cbmbz","cjrq"};
	public static final String[] TJyXtzjyyjyl = {"jrxkzh","xtjgdm","xtjgmc","jylsid","jysj","ywbs","zjfx","xtxmbm","xtzxmbm","trzhtbh","dsflx","dsfbh","bz","bj","sy","fy","bfzh","bfkhhmc","bfkhhbh","dfzh","dfkhhmc","dfkhhbh","jjbh","cbmbz","cjrq"};
	public static final String[] TJyQjglxxzq = {"xtjgdm","jrxkzh","xtjgmc","xtxmbh","xtzxmbh","xtzqzhzh","xtccdwjzjspd","xtccdwjzplpd","zjsdxtccdwjz","zjsdxtxmcygpje","zjsdxtxmcyzqje","zjsdxtxmcyjjje","zjsdxtxmcykddccye","zjsdxtxmcydddccye","zjsdxtxmcyjkddccye","zjsdxtxmcyktbzjzy","zjsdxtxmcydtbzjzy","zjsdxtxmqhzjzhjszbjye","zjsdxtxmcyqtyjzqje","zjsdxtxmccbl","xmclyljzzzl","bndxtljjzzzl","zjzjzjrq","zjzjzjje","ljzjzjje","zjqhzjrq","zjqhzjje","ljqhzjje","zcglbgpd","zjzcglbgrq","cjrq"};
	public static final String[] TJyQjglxxfzq = {"jrxkzh","xtjgdm","xtjgmc","xtxmbh","xtzxmbh","jydsbh","zcglbgpd","zxzcglbgrq","sfybzzj","bzjdwlyqk","zjsdrzye","sffszq","zjyczqdrq","zqcs","sffsjxhj","sfwaqhx","tqlxts","tqlxje","sfczyq","ljyqts","tqbjje","dzyl","zjqxtzcwjfl","zjsdtzye","tzbddzxpgrq","tzbddzxpgjz","sjdfzjly","cjrq"};
	public static final String[] TJyXtsypz = {"jrxkzh","xtjgdm","xtjgmc","sypjbh","xtxmbh","xtzxmbh","xthtbh","syqlbbm","syrlx","syrbh","syrztxz","sjcyxtfe","cjrq"};
	public static final String[] TJyXtsyqzrxx = {"xtjgdm","jrxkzh","xtjgmc","zrbh","xtxmbh","xtzxmbh","xthtbh","sypjbh","zrrq","crrlx","crrbh","srrlx","srrbh","zrfe","cjrq"};
	public static final String[] TGyGyzhxx = {"xtjgdm","jrxkzh","xtjgmc","zhbh","gyzhlc","zhzt","khjgmc","khjgzjhm","zhdzpd","khqy","sftg","zhswglfs","zhyjbgfs","ye","bz","cjrq"};
	public static final String[] TGyGyzzyyhtxx = {"xtjgdm","jrxkzh","xtjgmc","trzhtbh","wbhtbh","trzhtmc","gyywlb","dsflx","dsfbh","htqdrq","scfkrq","htdqrq","htqdje","sfbgscp","btzcpdm","ptzcpmc","htqyll","zhrzcb","yqsyl","bmmc","jbrbh","txdq","txhy","hymx","zjyyfs","hkfs","tqzz","tcfs","zcwjfl","bdzcmc","bdzclx","bdzcrzjz","rzhtdqrq","yshtbh","ysfqjglx","ysdslx","ysdsbh","cjrq"};
	public static final String[] TGyGyzjyyjyl = {"jrxkzh","xtjgdm","xtjgmc","jylsbh","jysj","ywbs","zjfx","htbh","jydsbh","jydslx","jybz","jhbj","jhsy","fy","bfzh","bfkhhmc","bfkhhbh","dfzh","dfkhhmc","dfkhhbh","jjbh","cbmbz","cjrq"};
	public static final String[] TGyGydbhtb = {"xtjgdm","jrxkzh","xtjgmc","dbhtbh","wbhtbh","dbhtlx","dblx","dbrlx","dbrbh","dbqsrq","dbdqrq","dbhtzt","dbhtqdrq","dbhtsxrq","dbhtdqrq","dbbz","dbzje","dbwpxh","dywlx","bzrlx","sfjkrglf","jlygh","cjrq"};
	public static final String[] TGyGydbgxb = {"xtjgdm","jrxkzh","xtjgmc","dbhtbh","bdbhtbh","cjrq"};
	public static final String[] TGyGydzywb = {"xtjgdm","jrxkzh","xtjgmc","zhdywbh","dbhth","zhdywmc","zhdywlx","zhdywzmjz","bz","yxrdjz","pgjz","pgrq","pgjgmc","zhdyl","dywsyqrmc","ydyjz","djrq","swsqrq","djjg","czjg","dbqsrq","dbdqrq","zypzzh","zypzlx","zypzhm","zypzje","zywbgfs","zywpgfs","zypzqfjg","zypzklrq","bxdh","hbrq","qzdjhm","qzmc","qzyxdqrq","djyxzzrq","sfnrbwhs","bwhsksrq","cjrq"};
	
}
