
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.1.120:3306/sdqz?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 
#    username:  litemall
#    password:  jf5FRnNTYb3XiPXk
    filters: log4j,wall,mergeStat
  redis:
    host: 127.0.0.1
    port: 6379
    password: 
#
#redis:
#    host: 127.0.0.1
#    port: 6379
#    password: liubo
#    keyPrefix: kingkongServer

