
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://rm-wz9m85c9959w8ufxxio.mysql.rds.aliyuncs.com:3306/sdqz?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Pdd2019__
    filters: log4j,wall,mergeStat
  redis:
    host: 120.78.225.33
    port: 6379
    password:
#redis:
#    host: 127.0.0.1
#    port: 6379
#    password: liubo
#    keyPrefix: kingkongServer

