USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TOPRIGHT @IN_OP_CODE INT
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    DECLARE @V_USER_ID INT
    SELECT @V_USER_ID = USER_ID FROM TSYSTEMINFO
    SELECT MENU_ID,FUNC_ID
    INTO #TEMPRIGHT
    FROM TROLERIGHT
    WHERE ROLE_ID IN(SELECT ROLE_ID FROM TOPROLE WHERE OP_CODE = @IN_OP_CODE)
    GROUP BY MENU_ID,FUNC_ID
    SELECT A.*, B.PARENT_ID,@IN_OP_CODE AS OP_CODE
        FROM #TEMPRIGHT A, TMENUINFO B
        WHERE A.MENU_ID = B.MENU_ID AND B.MENU_ID NOT LIKE '999%'
            AND (A.MENU_ID IN (SELECT MENU_ID FROM TMENUINFO WHERE USER_ID = @V_USER_ID OR USER_ID = 0))
            AND (A.FUNC_ID IN (SELECT FUNC_ID FROM TFUNCTYPE WHERE USER_ID = @V_USER_ID OR USER_ID = 0))
        ORDER BY A.MENU_ID, A.FUNC_ID
GO
