USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TPOSTSEND_PRODUCT
									@IN_PRODUCT_ID       INTEGER ,		   --产品ID
									@IN_CUST_NAME         NVARCHAR(50)='',	   --客户名称
									@IN_CONTRACT_SUB_BH	 VARCHAR(80)=''	   --合同编号
									
WITH ENCRYPTION
AS
    SET NOCOUNT ON

    SELECT A.PRODUCT_NAME, A.PRODUCT_ID,A.CONTRACT_SUB_BH,B.INPUT_DATE,B.POST_NO,B.POST_CONTENT,B.SUMMARY,B.SERIAL_NO,B.INPUT_MAN,D.CUST_ID,D.CUST_NAME 
		FROM INTRUST..TCONTRACT A LEFT JOIN TPOSTSEND B ON A.PRODUCT_ID=ISNULL (B.PRODUCT_ID,0) AND A.CONTRACT_SUB_BH = ISNULL (B.CONTRACT_SUB_BH,'')
			LEFT JOIN TCustomers D ON D.CUST_ID=A.CUST_ID
		WHERE A.PRODUCT_ID=@IN_PRODUCT_ID 
			AND (ISNULL(@IN_CUST_NAME,'') = '' OR D.CUST_NAME LIKE '%'+@IN_CUST_NAME+'%')
			AND (ISNULL(@IN_CONTRACT_SUB_BH,'') = '' OR A.CONTRACT_SUB_BH LIKE '%'+@IN_CONTRACT_SUB_BH+'%')
		ORDER BY A.QS_DATE DESC	
		
GO
