USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_DEL_TCUSTOMERCONTACTS    @IN_CONTACTID         INTEGER,         --联系人ID
                                             @IN_INPUT_MAN         INTEGER          --必要  操作员（CRM.TOPERATOR.OP_CODE）
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT, @IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)
    SELECT @V_RET_CODE = -10401000, @IBUSI_FLAG = 10401
    SELECT @SBUSI_NAME = N'删除客户联系人信息', @SSUMMARY = N'删除客户联系人信息'

    BEGIN TRANSACTION
    DELETE FROM  TCustomerContacts
    WHERE ContactID = @IN_CONTACTID
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    SET @SSUMMARY = N'删除客户联系人信息，操作员：' + CAST(@IN_INPUT_MAN AS NVARCHAR(10))
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION

    RETURN 100

GO
