USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_DEL_FAQ_CLASS @IN_FAQ_CLASS_NO     NVARCHAR(10), --知识库分类编号
                                  @IN_INPUT_MAN        INT
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    DECLARE @V_RET_CODE INT, @IBUSI_FLAG INT, @SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)
    SELECT @V_RET_CODE = -19004000, @IBUSI_FLAG = 19004
    SELECT @SBUSI_NAME = N'删除知识库分类', @SSUMMARY = N'删除知识库分类'
    IF NOT EXISTS(SELECT * FROM TMENUINFO WHERE MENU_ID LIKE 'W05%' AND MENU_ID <> 'W05' AND MENU_ID = @IN_FAQ_CLASS_NO)
        RETURN -20402001 --记录不存在
    IF EXISTS(SELECT 1 FROM TFAQS WHERE CLASS_NO = @IN_FAQ_CLASS_NO)
        RETURN @V_RET_CODE - 5 --分类下存在文章不能删除

    BEGIN TRANSACTION

    DELETE TMENUINFO WHERE MENU_ID LIKE 'W05%' AND MENU_ID <> 'W05' AND MENU_ID = @IN_FAQ_CLASS_NO
	DELETE TFUNCTYPE WHERE MENU_ID LIKE 'W05%' AND MENU_ID <> 'W05' AND MENU_ID = @IN_FAQ_CLASS_NO
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    DELETE TFUNCTYPE WHERE MENU_ID LIKE 'W05%' AND MENU_ID <> 'W05' AND MENU_ID = @IN_FAQ_CLASS_NO
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SELECT @SSUMMARY = N'删除知识库分类'
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
