USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_DEL_TGAINLEVEL @IN_SERIAL_NO     INTEGER,        --记录号
                                   @IN_INPUT_MAN     INTEGER         --操作员
WITH ENCRYPTION 
AS
    DECLARE @V_PRODUCT_ID INT,@V_PRODUCT_CODE NVARCHAR(6),@V_PRODUCT_NAME NVARCHAR(60)
    DECLARE @V_PROV_LEVEL_NAME NVARCHAR(20),@V_LOWER_LIMIT DECIMAL(16,2),@V_UPPER_LIMIT DECIMAL(16,2)
    DECLARE @IBUSI_FLAG INT
    DECLARE @SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    
    SET @IBUSI_FLAG = 3300109
    SET @SBUSI_NAME = N'删除收益级别'
    
    SELECT @V_PRODUCT_ID = A.PREPRODUCT_ID,@V_PRODUCT_NAME = B.PREPRODUCT_NAME,
           @V_PROV_LEVEL_NAME = A.PROV_LEVEL_NAME,@V_LOWER_LIMIT = A.LOWER_LIMIT,@V_UPPER_LIMIT = A.UPPER_LIMIT
        FROM TGAINLEVEL A LEFT JOIN TPREPRODUCT B ON A.PREPRODUCT_ID=B.PREPRODUCT_ID
        WHERE A.SERIAL_NO = @IN_SERIAL_NO
    
    SET @SSUMMARY = @SBUSI_NAME + N'，预发行产品，产品名称：' + @V_PRODUCT_NAME 
                                + N'，收益级别：' + @V_PROV_LEVEL_NAME
                                + N'，份额区间：' + CONVERT(VARCHAR,@V_LOWER_LIMIT) + '-' + CONVERT(VARCHAR,@V_UPPER_LIMIT)
    
    BEGIN TRY
    BEGIN TRANSACTION
        --业务处理
        DELETE FROM TGAINLEVELRATE WHERE DF_SERIAL_NO = @IN_SERIAL_NO
        DELETE FROM TGAINLEVEL WHERE SERIAL_NO = @IN_SERIAL_NO
        
        --日志记录
        INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
            VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
            
        COMMIT TRANSACTION
        RETURN 100
    END TRY
    
    --异常处理
    BEGIN CATCH
        IF @@TRANCOUNT > 0 BEGIN
            ROLLBACK TRANSACTION
        END
        DECLARE @V_ERROR_STR NVARCHAR(1000),@V_ERROR_NUMBER INT,@V_ERROR_SEVERITY INT,@V_ERROR_STATE INT,
                @V_ERROR_PROCEDURE sysname,@V_ERROR_LINE INT,@V_ERROR_MESSAGE NVARCHAR(4000)

        SELECT @V_ERROR_STR = N'Message:%s,Error:%d,Level:%d,State:%d,Procedure:%s,Line:%d',
               @V_ERROR_NUMBER = ERROR_NUMBER(),
               @V_ERROR_SEVERITY = ERROR_SEVERITY(),
               @V_ERROR_STATE = ERROR_STATE(),
               @V_ERROR_PROCEDURE = ERROR_PROCEDURE(),
               @V_ERROR_LINE = ERROR_LINE(),
               @V_ERROR_MESSAGE = ERROR_MESSAGE()

        RAISERROR(@V_ERROR_STR,@V_ERROR_SEVERITY,1,@V_ERROR_MESSAGE,@V_ERROR_NUMBER,@V_ERROR_SEVERITY,@V_ERROR_STATE,
                  @V_ERROR_PROCEDURE,@V_ERROR_LINE)

        RETURN -100
    END CATCH
GO
