USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_STAT_TOPERATOR_STATISTICS 	@IN_BEGIN_DATE  INTEGER = 0,
												@IN_CREATE_FLAG NVARCHAR , --  是  否，
												@IN_INPUT_MAN   INTEGER = 0
WITH ENCRYPTION
AS

IF @IN_CREATE_FLAG = '是'
BEGIN
	IF ISNULL(@IN_BEGIN_DATE,0) <> 0  --删除某一月的历史数据
		BEGIN
		DELETE TOPERATORSTATISTICS 
			WHERE ([年份] = LEFT(@IN_BEGIN_DATE,4))
				AND ([月份] = RIGHT(@IN_BEGIN_DATE,2))
		END
	ELSE
		DELETE TOPERATORSTATISTICS --删除全部数据

	--客户首次认购或者受益时间
	SELECT C.CUST_ID,MIN(C.BEN_DATE) AS 'FIRST_BUY_DATE' INTO #V_FIRT_BY_DATE
		FROM INTRUST..TBENIFITOR C GROUP BY CUST_ID
	
	--按渠道来统计中心员工销售的总规模，客户数.新增客户数、个人客户数、机构客户数、签约客户数、新增个人客户。。。
	INSERT INTO	TOPERATORSTATISTICS
    SELECT LEFT(ISNULL(A.CHANNEL_TYPE,''),6) AS CHANNEL_TYPE,'',
		   ISNULL(A.SERVICE_MAN,0) AS SERVICE_MAN,'',
		   LEFT(@IN_BEGIN_DATE,4),RIGHT(@IN_BEGIN_DATE,2),
		   SUM(A.RG_MONEY) AS TOTAL_RG_MONEY,		   
		   COUNT(CASE D.CUST_TYPE WHEN 1 THEN A.CUST_ID END) AS [个人客户数],
		   COUNT(CASE D.CUST_TYPE WHEN 2 THEN A.CUST_ID END) AS [机构客户数],
		   COUNT(A.CUST_ID) AS [签约客户总数],		   
		   COUNT(CASE WHEN D.CUST_TYPE=1 AND A.QS_DATE = C.FIRST_BUY_DATE THEN A.CUST_ID END) AS [新增个人客户数],
		   COUNT(CASE WHEN D.CUST_TYPE=2 AND A.QS_DATE = C.FIRST_BUY_DATE THEN A.CUST_ID END) AS [新增机构客户数],
		   COUNT(CASE WHEN A.QS_DATE = C.FIRST_BUY_DATE THEN A.CUST_ID END) AS [新增客户数],
		   COUNT(CASE WHEN A.RG_MONEY <3000000 THEN A.CUST_ID END) AS [300万以下客户数],
		   COUNT(CASE WHEN A.RG_MONEY >=10000000 AND A.RG_MONEY<50000000 THEN A.CUST_ID END) AS [1000万以上客户数],
		   COUNT(CASE WHEN A.RG_MONEY >=50000000 THEN A.CUST_ID END) AS [5000万以上客户数]
		FROM INTRUST..TCONTRACT A LEFT JOIN TCustomers D ON A.CUST_ID = D.CUST_ID
				LEFT JOIN #V_FIRT_BY_DATE C ON A.CUST_ID = C.CUST_ID,
			INTRUST..TPRODUCT B
		WHERE A.PRODUCT_ID = B.PRODUCT_ID
			AND (LEFT(B.START_DATE,6) = @IN_BEGIN_DATE OR ISNULL(@IN_BEGIN_DATE,0)=0) 
		GROUP BY LEFT(ISNULL(A.CHANNEL_TYPE,''),6),ISNULL(A.SERVICE_MAN,0)	
	
	UPDATE TOPERATORSTATISTICS SET CHANNEL_TYPE_NAME = C.TYPE_CONTENT,
								   SERVICE_MAN_NAME  = B.OP_NAME
		FROM TOPERATORSTATISTICS A LEFT JOIN TOPERATOR B ON A.SERVICE_MAN = B.OP_CODE
							       LEFT JOIN INTRUST..TDICTPARAM C ON A.CHANNEL_TYPE = TYPE_VALUE AND C.TYPE_ID = 5500
END

SELECT [年份],[月份],CHANNEL_TYPE_NAME,SERVICE_MAN_NAME,[募集规模],[签约客户总数],
		[300万以下客户数],[机构客户数],[个人客户数],[新增客户数],[新增机构客户],[新增个人客户],
		[新增1000万以上客户数],[新增5000万以上客户数]
	FROM TOPERATORSTATISTICS A 
		WHERE ([年份] = LEFT(@IN_BEGIN_DATE,4) OR ISNULL(@IN_BEGIN_DATE,0)=0)
			AND ([月份] = RIGHT(@IN_BEGIN_DATE,2) OR ISNULL(@IN_BEGIN_DATE,0)=0)
	ORDER BY [年份] DESC,[月份],A.CHANNEL_TYPE
	
RETURN 100 	
GO
