USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TCUSTGROUPS @IN_GROUPID      INT,   --给定节点标识
                                      @IN_INPUT_MAN    INT    --操作员

WITH ENCRYPTION
AS
    DECLARE @V_LEFT_ID INT,@V_RIGHT_ID INT,@V_LEVEL_ID INT
    IF EXISTS (SELECT 1 FROM TCustGroups WHERE GroupID = @IN_GROUPID)
    BEGIN
        SELECT @V_LEFT_ID = LEFT_ID,@V_RIGHT_ID = RIGHT_ID,@V_LEVEL_ID  = LEVEL_ID
        FROM TCustGroups WHERE GroupID = @IN_GROUPID
        SELECT GroupID,GroupName,LEFT_ID,RIGHT_ID,LEVEL_ID
        FROM TCustGroups WHERE LEVEL_ID = @V_LEVEL_ID + 1 AND LEFT_ID > @V_LEFT_ID AND LEFT_ID < @V_RIGHT_ID
        ORDER BY LEFT_ID ASC
    END
GO
