USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
 CREATE PROCEDURE SP_DEL_TCOMAINTAINMONEYMX @IN_MONEYMX_ID    INT,     --到账明细ID，自增长
                                            @IN_INPUT_MAN     INT               --录入人员，对应表TOPERATOR.OP_CODE  
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    DECLARE @V_WH_MONEY   DECIMAL(16,3)         --维护费金额
    DECLARE @V_COCONTRACTMAINTAIN_SUB_BH NVARCHAR(200)   --维护合同编号
    DECLARE @V_MAINTAIN_ID       INT   --维护费(维护合同)ID，对应合同TCOCONTRACTMAINTAIN. MAINTAIN_ID
    DECLARE @V_ARRIVE_TIME       INT   --到帐日期
    DECLARE @V_OLD_ARRIVE_MONEY  DECIMAL(16,3)  --旧到帐金额
    DECLARE @V_ARRIVE_MONEY      DECIMAL(16,3)       --实际已到帐金额
    
    SELECT @SBUSI_NAME = N'合同管理之删除维护合同到帐明细'
    SELECT @SSUMMARY = N'合同管理之删除维护合同到帐明细'
    SELECT @IBUSI_FLAG = 50001
    SELECT @V_RET_CODE = -50001000 
    
    SELECT @V_MAINTAIN_ID =MAINTAIN_ID,@V_OLD_ARRIVE_MONEY =ARRIVE_MONEY,@V_ARRIVE_TIME =ARRIVE_TIME FROM TCOMAINTAINMONEYMX WHERE MONEYMX_ID = @IN_MONEYMX_ID
    SELECT @V_COCONTRACTMAINTAIN_SUB_BH = COCONTRACTMAINTAIN_SUB_BH,@V_WH_MONEY = WH_MONEY,@V_ARRIVE_MONEY = ARRIVE_MONEY
        FROM TCOCONTRACTMAINTAIN WHERE MAINTAIN_ID =@V_MAINTAIN_ID
    
    BEGIN TRANSACTION
    
    DELETE FROM TCOMAINTAINMONEYMX WHERE MONEYMX_ID = @IN_MONEYMX_ID
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    --更新付款计划表中到帐金额
    UPDATE TCOCONTRACTMAINTAIN
        SET ARRIVE_MONEY = ISNULL(ARRIVE_MONEY,0) - ISNULL(@V_OLD_ARRIVE_MONEY,0),
            ARRIVEMONEY_FLAG =CASE WHEN (ISNULL(@V_ARRIVE_MONEY,0) - ISNULL(@V_OLD_ARRIVE_MONEY,0)) =0 THEN 1 WHEN (@V_WH_MONEY <=  (ISNULL(@V_ARRIVE_MONEY,0) - ISNULL(@V_OLD_ARRIVE_MONEY,0))) THEN 3 ELSE 2 END
        WHERE MAINTAIN_ID =@V_MAINTAIN_ID
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    --
    SELECT @SSUMMARY = N'合同管理之删除维护合同到帐明细，合同编号：'+@V_COCONTRACTMAINTAIN_SUB_BH + '，到帐日期：'+CONVERT(NVARCHAR(8),@V_ARRIVE_TIME)+'，到帐金额：'+CONVERT(VARCHAR(30),@V_OLD_ARRIVE_MONEY)
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    
    COMMIT TRANSACTION
    RETURN 100
GO
