USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TBENCHANGES @IN_BOOK_CODE INT,
                                      @IN_PRODUCT_ID INT,
                                      @IN_CONTRACT_BH VARCHAR(16),
                                      @IN_INPUT_MAN INT,
                                      @IN_BEGIN_DATE INT = NULL,
                                      @IN_END_DATE INT = NULL,
                                      @IN_FROM_CUST_NAME VARCHAR(60)=NULL,
                                      @IN_TO_CUST_NAME VARCHAR(60)=NULL,
                                      @IN_TRANS_TYPE VARCHAR(10)=NULL,
                                      @IN_CHECK_FLAG INT = 0,          --CHECK_FLAG = 11
                                      @IN_DF_REC_NO  INT = 0,           --ADD BY SHENKL 2006/12/22
                                      @IN_CONTRACT_SUB_BH VARCHAR(50) = NULL,  -- 合同编号查询  20080104 by wangc
                                      @IN_SUB_PRODUCT_ID  INT   =0          --子产品ID   20111112  LUOHH
WITH ENCRYPTION
AS
--20409: The Products can be accessed. START
    DECLARE @V_SW20409 INT
    SELECT @V_SW20409 = VALUE FROM INTRUST..TSYSCONTROL WHERE FLAG_TYPE = 'SW20409'
    DECLARE @V_PRODUCTS TABLE(PRODUCT_ID INT)
    IF @V_SW20409 = 1
        INSERT INTO @V_PRODUCTS
            SELECT PRODUCT_ID FROM INTRUST..TPRODUCT WHERE BOOK_CODE = @IN_BOOK_CODE
                AND(INTRUST_FLAG1 IN ( SELECT FUNC_ID-2040900 FROM INTRUST..TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID > 2040900 AND FUNC_ID <= 2040999 AND OP_CODE = @IN_INPUT_MAN )
                    OR PRODUCT_ID IN ( SELECT FUNC_ID FROM INTRUST..TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID < 2040900 AND OP_CODE = @IN_INPUT_MAN)
                    OR ADMIN_MANAGER = @IN_INPUT_MAN OR INPUT_MAN = @IN_INPUT_MAN OR ISNULL(@IN_INPUT_MAN,0)=0 
                    OR ADMIN_MANAGER IN(SELECT OP_CODE FROM INTRUST..TOPCUSTRIGHT WHERE ENABLE_OP_CODE = @IN_INPUT_MAN)
                    )
--20409: The Products can be accessed. END
  IF @IN_CHECK_FLAG = 11
    --受益查询：受益权 质押/冻结 查询
    SELECT A.*,D.CONTRACT_SUB_BH,B.CUST_NAME AS FROM_CUST_NAME,B.CUST_NO AS FROM_CUST_NO,C.CUST_NAME AS TO_CUST_NAME,C.CUST_NO AS TO_CUST_NO,E.LIST_NAME,E.LIST_NAME AS SUB_PRODUCT_NAME
    FROM INTRUST..TBENCHANGES A,INTRUST..TCUSTOMERINFO B,INTRUST..TCUSTOMERINFO C,INTRUST..TCONTRACT D LEFT JOIN INTRUST..TSUBPRODUCT E ON (D.SUB_PRODUCT_ID =E.SUB_PRODUCT_ID)
        WHERE A.BOOK_CODE = @IN_BOOK_CODE AND A.PRODUCT_ID = D.PRODUCT_ID AND A.CONTRACT_BH = D.CONTRACT_BH
            AND (A.PRODUCT_ID = @IN_PRODUCT_ID OR ISNULL(@IN_PRODUCT_ID,0) = 0)
            AND(@V_SW20409 = 0 OR @V_SW20409 IS NULL OR A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCTS))
            AND (A.CONTRACT_BH LIKE '%'+@IN_CONTRACT_BH+'%' OR ISNULL(@IN_CONTRACT_BH,'') = '')
            AND (D.CONTRACT_SUB_BH LIKE '%'+@IN_CONTRACT_SUB_BH+'%' OR ISNULL(@IN_CONTRACT_SUB_BH,'') = '')
            AND (ISNULL(@IN_SUB_PRODUCT_ID,0) =0 OR D.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID)
            AND(A.CHANGE_DATE >= @IN_BEGIN_DATE OR ISNULL(@IN_BEGIN_DATE,0) = 0)
            AND(A.CHANGE_DATE <= @IN_END_DATE OR ISNULL(@IN_END_DATE,0) = 0)
            AND A.FROM_CUST_ID=B.CUST_ID
            AND A.TO_CUST_ID=C.CUST_ID
            AND (A.TRANS_TYPE=@IN_TRANS_TYPE OR ISNULL(@IN_TRANS_TYPE,'')='')
            AND (B.CUST_NAME LIKE '%'+@IN_FROM_CUST_NAME+'%' OR ISNULL(@IN_FROM_CUST_NAME,'') = '')
            AND (C.CUST_NAME LIKE '%'+@IN_TO_CUST_NAME+'%' OR ISNULL(@IN_TO_CUST_NAME,'') = '')
        ORDER BY A.CHANGE_DATE DESC
  ELSE IF @IN_CHECK_FLAG = 12
    SELECT A.*,D.CONTRACT_SUB_BH,B.CUST_NAME AS FROM_CUST_NAME,B.CUST_NO AS FROM_CUST_NO,C.CUST_NAME AS TO_CUST_NAME,C.CUST_NO AS TO_CUST_NO,E.LIST_NAME,E.LIST_NAME AS SUB_PRODUCT_NAME
    FROM INTRUST..TBENCHANGES A,INTRUST..TCUSTOMERINFO B,INTRUST..TCUSTOMERINFO C,INTRUST..TCONTRACT D LEFT JOIN INTRUST..TSUBPRODUCT E ON (D.SUB_PRODUCT_ID =E.SUB_PRODUCT_ID)
        WHERE A.BOOK_CODE = @IN_BOOK_CODE AND A.PRODUCT_ID = D.PRODUCT_ID AND A.CONTRACT_BH = D.CONTRACT_BH
            AND (A.PRODUCT_ID = @IN_PRODUCT_ID OR ISNULL(@IN_PRODUCT_ID,0) = 0)
            AND(@V_SW20409 = 0 OR @V_SW20409 IS NULL OR A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCTS))
            AND (A.CONTRACT_BH LIKE '%'+@IN_CONTRACT_BH+'%' OR ISNULL(@IN_CONTRACT_BH,'') = '')
            AND (D.CONTRACT_SUB_BH LIKE '%'+@IN_CONTRACT_SUB_BH+'%' OR ISNULL(@IN_CONTRACT_SUB_BH,'') = '')
            AND (ISNULL(@IN_SUB_PRODUCT_ID,0) =0 OR D.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID)
            AND(A.CHANGE_DATE >= @IN_BEGIN_DATE OR ISNULL(@IN_BEGIN_DATE,0) = 0)
            AND(A.CHANGE_DATE <= @IN_END_DATE OR ISNULL(@IN_END_DATE,0) = 0)
            AND A.FROM_CUST_ID=B.CUST_ID
            AND A.TO_CUST_ID=C.CUST_ID
            AND (A.TRANS_TYPE=@IN_TRANS_TYPE OR (ISNULL(@IN_TRANS_TYPE,'')=''  AND A.TRANS_TYPE IN ('181501','181502','181503')))
            AND (B.CUST_NAME LIKE '%'+@IN_FROM_CUST_NAME+'%' OR ISNULL(@IN_FROM_CUST_NAME,'') = '')
            AND (C.CUST_NAME LIKE '%'+@IN_TO_CUST_NAME+'%' OR ISNULL(@IN_TO_CUST_NAME,'') = '')
            AND (A.FROM_LIST_ID = @IN_DF_REC_NO OR A.TO_LIST_ID = @IN_DF_REC_NO)
        ORDER BY A.CHANGE_DATE DESC
  ELSE
    SELECT A.*,D.CONTRACT_SUB_BH,B.CUST_NAME AS FROM_CUST_NAME,B.CUST_NO AS FROM_CUST_NO,C.CUST_NAME AS TO_CUST_NAME,C.CUST_NO AS TO_CUST_NO,E.LIST_NAME,E.LIST_NAME AS SUB_PRODUCT_NAME
    FROM INTRUST..TBENCHANGES A,INTRUST..TCUSTOMERINFO B,INTRUST..TCUSTOMERINFO C,INTRUST..TCONTRACT D LEFT JOIN INTRUST..TSUBPRODUCT E ON (D.SUB_PRODUCT_ID =E.SUB_PRODUCT_ID)
        WHERE A.BOOK_CODE = @IN_BOOK_CODE AND A.PRODUCT_ID = D.PRODUCT_ID AND A.CONTRACT_BH = D.CONTRACT_BH
            AND (A.PRODUCT_ID = @IN_PRODUCT_ID OR ISNULL(@IN_PRODUCT_ID,0) = 0)
            AND(@V_SW20409 = 0 OR @V_SW20409 IS NULL OR A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCTS))
            AND (A.CONTRACT_BH LIKE '%'+@IN_CONTRACT_BH+'%' OR ISNULL(@IN_CONTRACT_BH,'') = '')
            AND (D.CONTRACT_SUB_BH LIKE '%'+@IN_CONTRACT_SUB_BH+'%' OR ISNULL(@IN_CONTRACT_SUB_BH,'') = '')
            AND (ISNULL(@IN_SUB_PRODUCT_ID,0) =0 OR D.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID)
            AND(A.CHANGE_DATE >= @IN_BEGIN_DATE OR ISNULL(@IN_BEGIN_DATE,0) = 0)
            AND(A.CHANGE_DATE <= @IN_END_DATE OR ISNULL(@IN_END_DATE,0) = 0)
            AND A.FROM_CUST_ID=B.CUST_ID
            AND A.TO_CUST_ID=C.CUST_ID
            AND (A.CHECK_FLAG = @IN_CHECK_FLAG OR ISNULL(@IN_CHECK_FLAG,0) = 0)
            AND (A.TRANS_TYPE=@IN_TRANS_TYPE OR (ISNULL(@IN_TRANS_TYPE,'')=''  AND A.TRANS_TYPE IN ('181501','181502','181503')))
            AND (B.CUST_NAME LIKE '%'+@IN_FROM_CUST_NAME+'%' OR ISNULL(@IN_FROM_CUST_NAME,'') = '')
            AND (C.CUST_NAME LIKE '%'+@IN_TO_CUST_NAME+'%' OR ISNULL(@IN_TO_CUST_NAME,'') = '')
            AND (A.DF_REC_NO = @IN_DF_REC_NO  OR ISNULL(@IN_DF_REC_NO,0) = 0)
            AND ISNULL(A.PL_FLAG,1) = 1
        ORDER BY A.CHANGE_DATE DESC
GO
