USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_THOLIDAYS @IN_HOLIDAY_ID      INT = NULL,         --节假日ID
                                    @IN_HOLIDAY_NAME    NVARCHAR(60) = '',  --节假日名称
                                    @IN_INPUT_MAN       INT = NULL
WITH ENCRYPTION
AS
    IF @IN_HOLIDAY_ID IS NULL SET @IN_HOLIDAY_ID = 0
    IF @IN_HOLIDAY_NAME IS NULL SET @IN_HOLIDAY_NAME = ''
    IF @IN_HOLIDAY_ID <> 0
        SELECT *, CASE CAL_FLAG WHEN 1 THEN N'公历' ELSE N'农历' END AS CAL_FLAG_NAME,
               CASE CREATE_TASK WHEN 1 THEN N'是' ELSE N'否' END AS CREATE_TASK_NAME,
               CASE CAL_FLAG WHEN 1 THEN N'公历：' ELSE N'农历：' END + dbo.fn_getmonthday(HOLIDAY_DAY) AS HOLIDAY_DATE_CN
        FROM THOLIDAYS WHERE HOLIDAY_ID = @IN_HOLIDAY_ID
    ELSE
        SELECT *, CASE CAL_FLAG WHEN 1 THEN N'公历' ELSE N'农历' END AS CAL_FLAG_NAME,
               CASE CREATE_TASK WHEN 1 THEN N'是' ELSE N'否' END AS CREATE_TASK_NAME,
               CASE CAL_FLAG WHEN 1 THEN N'公历：' ELSE N'农历：' END + dbo.fn_getmonthday(HOLIDAY_DAY) AS HOLIDAY_DATE_CN
        FROM THOLIDAYS
        WHERE (HOLIDAY_NAME LIKE '%'+@IN_HOLIDAY_NAME+'%')
GO
