USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TSCHEDULES_LEADER
                                 @IN_OP_CODE             INT,              --员工编号
                                 @IN_BEGIN_DATE          INT = 0,          --起始时间
                                 @IN_END_DATE            INT = 0,          --结束时间
                                 @IN_SCHEDULE_TYPE       INT,              --日程类型 --约会/活动/计划
                                 @IN_INPUT_MAN           INT               --操作员
                                        
WITH ENCRYPTION
AS
    DECLARE @V_DATE INT, @V_OP_NAME NVARCHAR(20)
    
    SELECT @V_DATE=CAST(CONVERT(VARCHAR,GETDATE(),112) AS INT)
    IF ISNULL(@IN_BEGIN_DATE,0)=0 SET @IN_BEGIN_DATE=@V_DATE
    IF ISNULL(@IN_END_DATE,0)=0 SET @IN_END_DATE=@V_DATE
    IF EXISTS (SELECT * FROM TOPROLE WHERE OP_CODE=@IN_INPUT_MAN AND ROLE_ID=1)   
    BEGIN --管理员，能看所有的员工
		SELECT SCHEDULE_NAME,OP_NAME,CONTENT,START_DATE,END_DATE FROM TSCHEDULES
			WHERE (OP_CODE=@IN_OP_CODE OR ISNULL(@IN_OP_CODE,0)=0)
			    AND dbo.GETDATEINT(START_DATE) >= @IN_BEGIN_DATE
				AND dbo.GETDATEINT(START_DATE) <= @IN_END_DATE
				AND (SCHEDULE_TYPE = @IN_SCHEDULE_TYPE OR ISNULL(@IN_SCHEDULE_TYPE,0) = 0 )
		RETURN 100
    END
    
    --取出操作员的下属员工
    DECLARE @V_TEMP_OPCODE TABLE(OP_CODE INT,OP_NAME NVARCHAR(200))
    INSERT INTO @V_TEMP_OPCODE(OP_CODE,OP_NAME)
		EXEC SP_GET_OPERATOR_MEMBERS @IN_INPUT_MAN
    /*SELECT @V_OP_NAME=OP_NAME FROM TOPERATOR WHERE OP_CODE=@IN_INPUT_MAN
    INSERT INTO @V_TEMP_OPCODE
		SELECT MANAGERID FROM TManagerTeamMembers WHERE TEAM_ID IN (SELECT TEAM_ID FROM TManagerTeams WHERE LEADER=@IN_INPUT_MAN)
		UNION SELECT @IN_INPUT_MAN -- 自己
		
	INSERT INTO @V_TEMP_OPCODE
		SELECT OP_CODE FROM TOPERATOR  O
			WHERE DEPART_ID =(SELECT DEPART_ID FROM TOPERATOR WHERE OP_CODE=@IN_INPUT_MAN) --本部门
				AND EXISTS (SELECT * FROM TDEPARTMENT WHERE LEADER_MAN=@V_OP_NAME) --部门领导
				AND OP_CODE NOT IN (SELECT OP_CODE FROM @V_TEMP_OPCODE)
	*/
    SELECT A.OP_CODE,SCHEDULE_NAME,A.OP_NAME,CONTENT,START_DATE,END_DATE
        FROM @V_TEMP_OPCODE A 
            JOIN TSCHEDULES B ON A.OP_CODE=B.OP_CODE
        WHERE (A.OP_CODE = @IN_OP_CODE OR ISNULL(@IN_OP_CODE,0)=0)
            AND (dbo.GETDATEINT(START_DATE) >= @IN_BEGIN_DATE OR ISNULL(B.START_DATE,0)=0)
            AND (dbo.GETDATEINT(START_DATE) <= @IN_END_DATE OR ISNULL(B.START_DATE,0)=0)
            AND (SCHEDULE_TYPE = @IN_SCHEDULE_TYPE OR ISNULL(@IN_SCHEDULE_TYPE,0) = 0 )
           
    RETURN 100
GO
