USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TINIPARAM @IN_TYPE_ID INT,
                                    @IN_TYPE_VALUE NVARCHAR(30)
WITH ENCRYPTION
AS
    SELECT * FROM TINIPARAM
        WHERE (TYPE_ID = @IN_TYPE_ID OR ISNULL(@IN_TYPE_ID,0) = 0) AND
              (TYPE_VALUE LIKE '%' + @IN_TYPE_VALUE + '%' OR ISNULL(@IN_TYPE_VALUE,'') = N'')
        ORDER BY TYPE_ID,TYPE_VALUE
GO
