USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
--DROP PROCEDURE SP2_QUERY_TPRODUCT_PAGE
--SP2_QUERY_TPRODUCT_PAGE 1,0,'','','',0,0,0,0,0,0,0,0,888
CREATE PROCEDURE SP2_QUERY_TPRODUCT_PAGE
				   @IN_BOOK_CODE       INT,
                   @IN_PRODUCT_ID      INT,
                   @IN_PRODUCT_CODE    NVARCHAR(6),
                   @IN_PRODUCT_NAME    NVARCHAR(60),
                   @IN_PRODUCT_STATUS  NVARCHAR(10),      --产品状态
                   @IN_OPEN_FLAG       INT,               --发行方式 1开放式2封闭式
                   @IN_START_DATE      INT,
                   @IN_END_DATE        INT,
                   @IN_CHECK_FLAG      INT,               --是否审核
                   @IN_INTRUST_FLAG1   INT,               --集合标志
                   @IN_SALE_STATUS     INT,               --CRM产品销售参数审核状态 -9为设置，1为审核，2已审核
                   @IN_PAGE_INDEX      INT,               --页码
                   @IN_PAGE_SIZE       INT,               --页宽
                   @IN_INPUT_MAN       INT
WITH ENCRYPTION
AS
    DECLARE @V_SINGLE INT,@V_ITEMFLAG INT
    DECLARE @V_RECORD_TOTAL INT
    SELECT @V_SINGLE = VALUE FROM TSYSCONTROL WHERE FLAG_TYPE = 'SINGLE'
    SELECT @V_ITEMFLAG =VALUE FROM INTRUST..TSYSCONTROL WHERE FLAG_TYPE = 'ITEMFLAG'
    IF ISNULL(@V_ITEMFLAG,0) =0
        SET @V_ITEMFLAG =2
    SELECT @V_SINGLE = ISNULL(@V_SINGLE,0)
    SELECT A.*, GR_NUM = 0, GR_MONEY = CONVERT(DEC(16,3),0.00),JG_NUM = 0, JG_MONEY = CONVERT(DEC(16,3),0.00), B.CURRENCY_NAME ,A.PRODUCT_ID AS SPEC_PRODUCT_ID,
           ADD_UP_4001 = CONVERT(DEC(16,3),0.00),
          '非银信合作' AS WITH_BANK_FLAG_NAME,
          '非证信合作' AS WITH_SECURITY_FLAG_NAME,
          '非私募基金合作' AS WITH_PRIVATE_FLAG_NAME,
          '非信政合作' AS WITH_GOV_FLAG_NAME, 
          CASE BUSINESS_END_FLAG WHEN 2 THEN '清算期' WHEN 3 THEN '业务结束' WHEN 4 THEN '产品结束' ELSE '正常' END AS BUSINESS_END_FLAG_NAME,
          C.DEPART_NAME,
          0 AS PRINCIPAL_COUNT1,CONVERT(DEC(16,2),0.00) AS PRINCIPAL_AMOUNT1,
          0 AS PRINCIPAL_COUNT2,CONVERT(DEC(16,2),0.00) AS PRINCIPAL_AMOUNT2,
          0 AS PRINCIPAL_COUNT3,CONVERT(DEC(16,2),0.00) AS PRINCIPAL_AMOUNT3,
          A2.OP_NAME AS ADMIN_MANAGER_NAME,
          GRHT_NUM = 0,JGHT_NUM = 0, FACTHT_NUM = 0
        INTO #TEMP_QUERY_TPRODUCT
        FROM INTRUST..TPRODUCT A LEFT JOIN INTRUST..TOPERATOR A2 ON A.ADMIN_MANAGER = A2.OP_CODE, INTRUST..TCURRENCY B,INTRUST..TDEPARTMENT C
        WHERE A.BOOK_CODE  = @IN_BOOK_CODE AND A.CURRENCY_ID = B.CURRENCY_ID AND A.DEPART_ID = C.DEPART_ID
            AND(A.PRODUCT_CODE LIKE '%'+@IN_PRODUCT_CODE+'%' OR @IN_PRODUCT_CODE IS NULL OR @IN_PRODUCT_CODE = '')
            AND(A.PRODUCT_NAME LIKE '%'+@IN_PRODUCT_NAME+'%' OR @IN_PRODUCT_NAME IS NULL OR @IN_PRODUCT_NAME = '')
            AND(A.PRODUCT_STATUS = @IN_PRODUCT_STATUS OR @IN_PRODUCT_STATUS IS NULL OR @IN_PRODUCT_STATUS = '')
            --AND(@V_SW20409 = 0 OR @V_SW20409 IS NULL OR A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCTS))
            AND(A.INTRUST_FLAG1 = @IN_INTRUST_FLAG1 OR @IN_INTRUST_FLAG1 IS NULL OR @IN_INTRUST_FLAG1 = 0)
            AND(A.CHECK_FLAG = @IN_CHECK_FLAG OR ISNULL(@IN_CHECK_FLAG,0) = 0)
            AND(A.OPEN_FLAG = @IN_OPEN_FLAG OR ISNULL(@IN_OPEN_FLAG,0) = 0)
            AND A.APPROVAL_FLAG = 1 AND A.FINANCIAL_CONSULTANT <> 1
            AND (ISNULL(@IN_START_DATE,0)=0 OR A.START_DATE >= @IN_START_DATE)
            AND (ISNULL(@IN_END_DATE,0)=0 OR A.START_DATE <= @IN_END_DATE)
            AND A.INTRUST_FLAG1=2
        ORDER BY A.PRODUCT_CODE DESC
    IF @IN_PRODUCT_STATUS = '110203'   -- 查询正常期产品, 把业务结束的数据删除
        DELETE FROM #TEMP_QUERY_TPRODUCT WHERE PRODUCT_STATUS = '110203' AND BUSINESS_END_FLAG IN(3,4)
    --更新产品的认购信息
    UPDATE #TEMP_QUERY_TPRODUCT SET GR_NUM=B.PERSON_COUNT,GR_MONEY =B.PERSON_MONEY,JG_NUM =B.ORG_COUNT,JG_MONEY =B.ORG_MONEY
		FROM #TEMP_QUERY_TPRODUCT A LEFT JOIN INTRUST..TPRODUCTSALE B ON A.PRODUCT_ID=B.PRODUCT_ID
		WHERE ISNULL(A.FLAG3,0)=1
	--个人
	UPDATE #TEMP_QUERY_TPRODUCT SET GR_NUM=ISNULL(B.GR_NUM,0),GR_MONEY =ISNULL(B.GR_MONEY,0),GRHT_NUM=ISNULL(B.GRHT_NUM,0)
		FROM #TEMP_QUERY_TPRODUCT A LEFT JOIN (SELECT PRODUCT_ID,COUNT(0) GR_NUM,SUM(RG_MONEY) GR_MONEY,COUNT(DISTINCT CONTRACT_SUB_BH) GRHT_NUM FROM INTRUST..TCONTRACT X LEFT JOIN INTRUST..TCUSTOMERINFO Y ON X.CUST_ID=Y.CUST_ID WHERE Y.CUST_TYPE=1 AND X.HT_STATUS<>'120104' AND X.CHECK_FLAG=2 GROUP BY PRODUCT_ID) B ON A.PRODUCT_ID=B.PRODUCT_ID
		WHERE ISNULL(A.FLAG3,0)<>1
	--机构
	UPDATE #TEMP_QUERY_TPRODUCT SET JG_NUM=ISNULL(B.JG_NUM,0),GR_MONEY =ISNULL(B.JG_MONEY,0),JGHT_NUM=ISNULL(B.JGHT_NUM,0)
		FROM #TEMP_QUERY_TPRODUCT A LEFT JOIN (SELECT PRODUCT_ID,COUNT(0) JG_NUM,SUM(RG_MONEY) JG_MONEY,COUNT(DISTINCT CONTRACT_SUB_BH) JGHT_NUM FROM INTRUST..TCONTRACT X LEFT JOIN INTRUST..TCUSTOMERINFO Y ON X.CUST_ID=Y.CUST_ID WHERE Y.CUST_TYPE=2 AND X.HT_STATUS<>'120104' AND X.CHECK_FLAG=2 GROUP BY PRODUCT_ID) B ON A.PRODUCT_ID=B.PRODUCT_ID
		WHERE ISNULL(A.FLAG3,0)<>1
	--合计
	UPDATE #TEMP_QUERY_TPRODUCT SET FACTHT_NUM=ISNULL(JGHT_NUM,0) + ISNULL(GRHT_NUM,0),
            FACT_NUM =  ISNULL(JG_NUM,0) + ISNULL(GR_NUM,0),
            FACT_MONEY = ISNULL(JG_MONEY,0.00) + ISNULL(GR_MONEY,0.00)
    UPDATE #TEMP_QUERY_TPRODUCT SET NATRUST_TYPE = CASE B.FIELD_VALUE WHEN '1:融资类' THEN '114302' WHEN '2:投资类' THEN '114301' ELSE '114303' END
			,NATRUST_TYPE_NAME =CASE B.FIELD_VALUE WHEN '1:融资类' THEN '融资型信托' WHEN '2:投资类' THEN '投资型信托' ELSE '管理型信托' END
		FROM #TEMP_QUERY_TPRODUCT A LEFT JOIN INTRUST..TPRODUCTADDINFO B ON B.DF_SERIAL_NO=1 AND A.PRODUCT_ID=B.PRODUCT_ID
    IF @V_ITEMFLAG =1   --有中后期管理
    BEGIN
        UPDATE #TEMP_QUERY_TPRODUCT
            SET WITH_BANK_FLAG_NAME ='银信合作'
            FROM #TEMP_QUERY_TPRODUCT A,INTRUST..TITEM B
                    WHERE A.BOOK_CODE =@IN_BOOK_CODE AND A.ITEM_ID =B.ITEM_ID AND B.WITH_BANK_FLAG =1
        --
        UPDATE #TEMP_QUERY_TPRODUCT
            SET WITH_SECURITY_FLAG_NAME ='证信合作'
            FROM #TEMP_QUERY_TPRODUCT A,INTRUST..TITEM B
                    WHERE A.BOOK_CODE =@IN_BOOK_CODE AND A.ITEM_ID =B.ITEM_ID AND B.WITH_SECURITY_FLAG =1
        --
        UPDATE #TEMP_QUERY_TPRODUCT
            SET WITH_PRIVATE_FLAG_NAME ='私募基金合作'
            FROM #TEMP_QUERY_TPRODUCT A,INTRUST..TITEM B
                    WHERE A.BOOK_CODE =@IN_BOOK_CODE AND A.ITEM_ID =B.ITEM_ID AND B.WITH_PRIVATE_FLAG =1
        --
        UPDATE #TEMP_QUERY_TPRODUCT
            SET WITH_GOV_FLAG_NAME ='信政合作'
            FROM #TEMP_QUERY_TPRODUCT A,INTRUST..TITEM B
                    WHERE A.BOOK_CODE =@IN_BOOK_CODE AND A.ITEM_ID =B.ITEM_ID AND B.WITH_GOV_FLAG =1
    END
    ELSE
    BEGIN
        UPDATE #TEMP_QUERY_TPRODUCT
            SET WITH_BANK_FLAG_NAME ='银信合作'
            FROM #TEMP_QUERY_TPRODUCT A,INTRUST..TPRODUCTADDINFO B
                WHERE A.BOOK_CODE =@IN_BOOK_CODE AND A.PRODUCT_ID =B.PRODUCT_ID AND B.TB_FLAG =1
                    AND B.FIELD_CAPTION LIKE N'%合作方式%' AND B.FIELD_VALUE LIKE N'%银信合作%'
        --
        UPDATE #TEMP_QUERY_TPRODUCT
            SET WITH_SECURITY_FLAG_NAME ='证信合作'
            FROM #TEMP_QUERY_TPRODUCT A,INTRUST..TPRODUCTADDINFO B
                    WHERE A.BOOK_CODE =@IN_BOOK_CODE AND A.PRODUCT_ID =B.PRODUCT_ID AND B.TB_FLAG =1
                        AND B.FIELD_CAPTION LIKE N'%合作方式%' AND B.FIELD_VALUE LIKE N'%证信合作%'
        --
        UPDATE #TEMP_QUERY_TPRODUCT
            SET WITH_PRIVATE_FLAG_NAME ='私募基金合作'
            FROM #TEMP_QUERY_TPRODUCT A,INTRUST..TPRODUCTADDINFO B
                    WHERE A.BOOK_CODE =@IN_BOOK_CODE AND A.PRODUCT_ID =B.PRODUCT_ID AND B.TB_FLAG =1
                        AND B.FIELD_CAPTION LIKE N'%合作方式%' AND B.FIELD_VALUE LIKE N'%私募基金合作%'
        --
        UPDATE #TEMP_QUERY_TPRODUCT
            SET WITH_GOV_FLAG_NAME ='信政合作'
            FROM #TEMP_QUERY_TPRODUCT A,INTRUST..TPRODUCTADDINFO B
                    WHERE A.BOOK_CODE =@IN_BOOK_CODE AND A.PRODUCT_ID =B.PRODUCT_ID AND B.TB_FLAG =1
                        AND B.FIELD_CAPTION LIKE N'%合作方式%' AND B.FIELD_VALUE LIKE N'%信政合作%'
    END
    --更新总资产
   /* UPDATE #TEMP_QUERY_TPRODUCT
        SET TOTAL_MONEY = B.FUND_MONEY_OUT2
        FROM #TEMP_QUERY_TPRODUCT A,INTRUSTHistory..HZCFZB B
        WHERE A.PRODUCT_ID = B.PRODUCT_ID
            AND B.ITEM_ID = 119
    --更新实收信托
    UPDATE #TEMP_QUERY_TPRODUCT
        SET TOTAL_MONEY = B.FUND_MONEY_IN2
        FROM #TEMP_QUERY_TPRODUCT A,INTRUSTHistory..HZCFZB B
        WHERE A.PRODUCT_ID = B.PRODUCT_ID
            AND B.ITEM_ID = 114
    --更新累计实收信托
    UPDATE #TEMP_QUERY_TPRODUCT
        SET ADD_UP_4001 = B.ADD_UP_4001
        FROM #TEMP_QUERY_TPRODUCT A,
            (SELECT PRODUCT_ID,ISNULL(SUM(DR_BALANCE),0) AS ADD_UP_4001 FROM INTRUST..TUNPOSTLIST B1
                                        WHERE SUBSTRING(SUB_CODE,1,4) = '4001' AND CHECK_FLAG =2 AND
                                              NOT EXISTS(SELECT POST_BH FROM INTRUST..TUNPOSTLIST B2 
                                                            WHERE LEFT(SUB_CODE,4) = '4001' AND B1.POST_BH = B2.POST_BH
                                                            GROUP BY POST_BH HAVING SUM(CR_BALANCE) = SUM(DR_BALANCE)
                                                        )
                                        GROUP BY PRODUCT_ID
            ) B
            WHERE A.PRODUCT_ID = B.PRODUCT_ID
    */
    IF ISNULL(@IN_PAGE_INDEX,0)<=0
		SET @IN_PAGE_INDEX=1
	IF ISNULL(@IN_PAGE_SIZE,0)<=0
	BEGIN
		SELECT @IN_PAGE_SIZE=PAGESIZE FROM TOPERATOR WHERE OP_CODE=@IN_INPUT_MAN
		IF ISNULL(@IN_PAGE_SIZE,0)<=0
			SET @IN_PAGE_SIZE=20
	END
	SELECT @V_RECORD_TOTAL=COUNT(0) FROM #TEMP_QUERY_TPRODUCT
	SELECT * FROM (
		SELECT A.*,ROW_NUMBER() OVER(ORDER BY A.PRODUCT_CODE DESC) RID,@V_RECORD_TOTAL AS RECORD_TOTAL FROM #TEMP_QUERY_TPRODUCT A 
    ) M WHERE M.RID>=(@IN_PAGE_INDEX-1)*@IN_PAGE_SIZE+1
			AND M.RID<=@IN_PAGE_INDEX*@IN_PAGE_SIZE
    
GO
