USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_CHANGECUSTOMER_SROCRE   @IN_CUST_NAME    NVARCHAR(200),
												  @IN_CUST_TYPE	   INT,
												  @IN_SUBJECT_ID   INT,
												  @IN_RATING_NO    NVARCHAR(60),
												  @IN_RATING_NAME  NVARCHAR(60),
												  @IN_INPUT_MAN    INT,
												  @IN_PX_NAME	   NVARCHAR(60),
												  @IN_CUST_ID	   NVARCHAR(max)
WITH ENCRYPTION
AS

	DECLARE @V_TEMP_TABLE TABLE(OPERAND_NO NVARCHAR(60),OPERAND_NAME NVARCHAR(60),CUST_ID INT,CUST_NUM INT,CUST_SOURCE INT)
	DECLARE @V_SQL NVARCHAR(max)
	INSERT INTO @V_TEMP_TABLE
	SELECT C.OPERAND_NO,C.OPERAND_NAME,A.CUST_ID,A.CUST_NUM,A.CUST_SOURCE--,A.REGULATION,A.SCORING_DATE 
			FROM TCustScoreDetail A LEFT JOIN TScoreOperand C ON A.SUBJECT_ID = C.SUBJECT_ID AND A.OPERAND_ID = C.OPERAND_ID
			WHERE  END_DATE = 21001231
	
	SELECT A.CUST_ID,COUNT(A.PRODUCT_ID)AS NUM
		INTO #TEMP_NUM 
	FROM (SELECT CUST_ID,PRODUCT_ID FROM INTRUST..TBENIFITOR 
		GROUP BY CUST_ID,PRODUCT_ID) A
	GROUP BY A.CUST_ID
	
	
	SELECT CUST_ID AS CUST_ID,
			MAX(CASE OPERAND_NAME WHEN '累计投资金额' THEN CUST_NUM ELSE 0 END)CUST_NUM,
			MAX(CASE OPERAND_NAME WHEN '累计投资金额' THEN CUST_SOURCE ELSE 0 END)ALL_MONEY,
			MAX(CASE OPERAND_NAME WHEN '投资项目数量' THEN CUST_SOURCE ELSE 0 END)ITEM_NUM,
			MAX(CASE OPERAND_NAME WHEN '投资项目风险取值' THEN CUST_SOURCE ELSE 0 END)FX_LEVEL,
			MAX(CASE OPERAND_NAME WHEN '年龄阶段' THEN CUST_SOURCE ELSE 0 END)AGE_LEVEL,
			MAX(CASE OPERAND_NAME WHEN '自由现金流' THEN CUST_SOURCE ELSE 0 END)FREE_OF_FLOW,
			MAX(CASE OPERAND_NAME WHEN '债务压力' THEN CUST_SOURCE ELSE 0 END)BUREND_OF_DEBT
			INTO #TEMP_QUERY_TCustomersExt				
		FROM @V_TEMP_TABLE
		GROUP BY CUST_ID
	

    BEGIN
	SELECT A.CUST_ID,B.CUST_NAME,A.RATING_NAME,CASE B.SEX WHEN 1 THEN '男' WHEN 2 THEN '女' ELSE '' END SEX,E.CURRENT_SOURCE
		,A.RATING_DATE,F.CUST_NUM AS TOTAL_MONEY,B.AGE,C.NUM,F.ALL_MONEY,F.ITEM_NUM,F.FX_LEVEL,F.AGE_LEVEL,F.FREE_OF_FLOW,F.BUREND_OF_DEBT 
	INTO #TEMP_QUERY_TCUSTRATING
	FROM TCUSTRATING A
		LEFT JOIN  #TEMP_QUERY_TCustomersExt F ON A.CUST_ID = F.CUST_ID
		LEFT JOIN #TEMP_NUM C ON A.CUST_ID = C.CUST_ID
		LEFT JOIN TCustScore E ON A.CUST_ID = E.CUST_ID AND E.END_DATE = 21001231
		,TCUSTOMERS B
	WHERE A.END_DATE = 21001231
		AND A.CUST_ID = B.CUST_ID
		AND (B.CUST_NAME LIKE '%'+@IN_CUST_NAME+'%' OR ISNULL(@IN_CUST_NAME,'')='')
		AND (B.CUST_TYPE = @IN_CUST_TYPE OR ISNULL(@IN_CUST_TYPE,0)=0)
		AND (A.SUBJECT_ID = @IN_SUBJECT_ID OR ISNULL(@IN_SUBJECT_ID,0)=0)
		AND (A.RATING_NO LIKE '%'+@IN_RATING_NO+'%' OR ISNULL(@IN_RATING_NO,'')='')
		AND (A.RATING_NAME LIKE '%'+@IN_RATING_NAME+'%' OR ISNULL(@IN_RATING_NAME,'')='')
	ORDER BY A.RATING_NAME ,A.CUST_ID	
    END
	
	SET @V_SQL = 'SELECT * FROM  #TEMP_QUERY_TCUSTRATING WHERE CUST_ID IN('+@IN_CUST_ID+') ORDER BY RATING_NAME'
	IF ISNULL(@IN_PX_NAME,'')<>''
	BEGIN
		SET @V_SQL = @V_SQL+','+@IN_PX_NAME
	END

	EXECUTE(@V_SQL)	
	
    RETURN 100
GO
