USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_ADD_TDICTPARAM  @IN_TYPE_ID        INT,
                                    @IN_TYPE_NAME      NVARCHAR(20),
                                    @IN_TYPE_VALUE     NVARCHAR(10),
                                    @IN_TYPE_CONTENT   NVARCHAR(256),
                                    @IN_INPUT_MAN      INT,
                                    @IN_ADDITIVE_VALUE NVARCHAR(256) = NULL,
                                    @IN_AML_VALUE      NVARCHAR(20) = NULL
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT
    DECLARE @IBUSI_FLAG INT
    DECLARE @SBUSI_NAME NVARCHAR(40)
    DECLARE @SSUMMARY NVARCHAR(200)
    SELECT @V_RET_CODE = -10201000
    SELECT @IBUSI_FLAG = 10201
    SELECT @SBUSI_NAME = N'增加字典参数'
    SELECT @SSUMMARY = N'增加字典参数'

    IF EXISTS(SELECT * FROM TDICTPARAM WHERE TYPE_VALUE = @IN_TYPE_VALUE)
       RETURN @V_RET_CODE-1   -- 参数值已存在

    BEGIN TRANSACTION

    INSERT INTO TDICTPARAM(TYPE_ID,TYPE_NAME,TYPE_VALUE,TYPE_CONTENT,ADDITIVE_VALUE,AML_VALUE)
    VALUES
        (@IN_TYPE_ID,@IN_TYPE_NAME,@IN_TYPE_VALUE,@IN_TYPE_CONTENT,@IN_ADDITIVE_VALUE,@IN_AML_VALUE)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SELECT @SSUMMARY = N'增加字典参数，参数值：' + RTRIM(@IN_TYPE_VALUE) + N'，参数说明：' + @IN_TYPE_CONTENT
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
