USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TGAINTOTAL @IN_BOOK_CODE INT,
                                     @IN_PRODUCT_ID INT,
                                     @IN_SY_TYPE VARCHAR(10) = NULL,
                                     @IN_SY_DATE INT = NULL,
                                     @IN_INPUT_MAN INT = NULL,
                                     @IN_SUB_PRODUCT_ID  INT   =0          --子产品ID   20111112  LUOHH
WITH ENCRYPTION
AS
--20409: The Products can be accessed. START
    DECLARE @V_SW20409 INT
    SELECT @V_SW20409 = VALUE FROM TSYSCONTROL WHERE FLAG_TYPE = 'SW20409'
    DECLARE @V_PRODUCTS TABLE(PRODUCT_ID INT)
    IF @V_SW20409 = 1
        INSERT INTO @V_PRODUCTS
            SELECT PRODUCT_ID FROM INTRUST..TPRODUCT WHERE BOOK_CODE = @IN_BOOK_CODE
                AND(INTRUST_FLAG1 IN ( SELECT FUNC_ID-2040900 FROM TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID > 2040900 AND FUNC_ID <= 2040902 AND OP_CODE = @IN_INPUT_MAN )
                    OR DEPART_ID IN (SELECT B.DEPART_ID FROM TOPRIGHT A,TOPERATOR B WHERE A.OP_CODE = B.OP_CODE AND A.MENU_ID = '20409' AND A.FUNC_ID = 2040903 AND A.OP_CODE = @IN_INPUT_MAN)                   
                    OR PRODUCT_ID IN ( SELECT FUNC_ID FROM TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID < 2040900 AND OP_CODE = @IN_INPUT_MAN)
                    OR ADMIN_MANAGER = @IN_INPUT_MAN OR INPUT_MAN = @IN_INPUT_MAN 
                    OR SUB_MAN = @IN_INPUT_MAN OR SUB_MAN2 = @IN_INPUT_MAN
                    OR CASH_MAN = @IN_INPUT_MAN OR CASH_MAN2 = @IN_INPUT_MAN
					OR ADMIN_MANAGER IN(SELECT OP_CODE FROM INTRUST..TOPCUSTRIGHT WHERE ENABLE_OP_CODE = @IN_INPUT_MAN) OR ISNULL(@IN_INPUT_MAN,0)=0 )
--20409: The Products can be accessed. END
    SELECT A.*,B.LIST_NAME,B.LIST_NAME AS SUB_PRODUCT_NAME 
    FROM INTRUST..TGAINTOTAL A LEFT JOIN INTRUST..TSUBPRODUCT B ON (A.SUB_PRODUCT_ID =B.SUB_PRODUCT_ID)
        WHERE A.BOOK_CODE = @IN_BOOK_CODE
        AND (A.PRODUCT_ID = @IN_PRODUCT_ID OR ISNULL(@IN_PRODUCT_ID,0) = 0)
        AND (ISNULL(@IN_SUB_PRODUCT_ID,0) = 0 OR A.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID)
        AND(@V_SW20409 = 0 OR @V_SW20409 IS NULL OR A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCTS))
        AND (A.SY_TYPE = @IN_SY_TYPE OR ISNULL(@IN_SY_TYPE,'') = '')
        AND (A.SY_DATE = @IN_SY_DATE OR ISNULL(@IN_SY_DATE,0) = 0 )
GO
