USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TPRODUCT_MARKETING @IN_PRODUCT_ID   	INT,            --产品ID
                                             @IN_TEAM_ID      	INT,            --团队ID
                                             @IN_LEADER_NAME  	INT,            --团队经理（销售经理）]
                                             @IN_INPUT_MAN    	INT,            --操作员
											 @IN_PRODUCT_FLAG 	INT = 2,		--是否统计产品 		1是   2否
											 @IN_TEAM_FLAG		INT	= 2,		--是否统计团队  	1是   2否
											 @IN_SALE_FLAG		INT = 2			--是否统计销售经理	1是   2否
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    DECLARE @V_DT_INTRUST INT , @V_DATE_TYPE INT
    SELECT @V_DT_INTRUST = VALUE FROM TSYSCONTROL WHERE FLAG_TYPE = N'DT_INTRUST'

    CREATE TABLE #TEMP_TPRODUCT_MARKETING
    (
        SERIAL_NO      	INT NOT NULL IDENTITY,
        PRODUCT_ID     	INT,
        PRODUCT_CODE   	NVARCHAR(12),
        PRODUCT_NAME   	NVARCHAR(120),
        TEAM_ID        	INT,            --团队ID
        TEAM_NO        	NVARCHAR(60),   --团队编号
        TEAM_NAME      	NVARCHAR(160),  --团队名称
        QUOTAMONEY     	DEC(16,3),      --团队配额
        LINK_MAN       	INT,            --销售人员
        LINK_MAN_NAME  	NVARCHAR(40),   --销售人员名称
        RG_MONEY       	DEC(16,3),      --认购金额
        TO_MONEY       	DEC(16,3),      --缴款金额
        DATE_TYPE		INT				--数据类型，每插入一次编号一次。
    )
    BEGIN
        INSERT INTO #TEMP_TPRODUCT_MARKETING(PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,LINK_MAN,RG_MONEY,TO_MONEY,DATE_TYPE)
            SELECT B.PRODUCT_ID,B.PRODUCT_CODE,B.PRODUCT_NAME,A.LINK_MAN,A.RG_MONEY,A.TO_MONEY,1
                FROM INTRUST.dbo.TCONTRACT A, INTRUST.dbo.TPRODUCT B
                WHERE B.PRODUCT_STATUS = '110202' AND A.PRODUCT_ID = B.PRODUCT_ID
        SELECT @V_DATE_TYPE = MAX(DATE_TYPE) FROM #TEMP_TPRODUCT_MARKETING        
    END
    UPDATE #TEMP_TPRODUCT_MARKETING
        SET TEAM_ID = ISNULL(B.TEAM_ID,0), TEAM_NO = ISNULL(B.TEAM_NO,''), TEAM_NAME = ISNULL(B.TEAM_NAME,'')
        FROM #TEMP_TPRODUCT_MARKETING A, TMANAGERTEAMS B
        WHERE A.LINK_MAN = ISNULL(B.LEADER,0)
            AND(B.LEADER = @IN_LEADER_NAME OR ISNULL(@IN_LEADER_NAME,0)=0)
    UPDATE #TEMP_TPRODUCT_MARKETING
        SET TEAM_ID = ISNULL(B.TEAM_ID,0), TEAM_NO = ISNULL(B.TEAM_NO,''), TEAM_NAME = ISNULL(B.TEAM_NAME,'')
        FROM #TEMP_TPRODUCT_MARKETING A, TMANAGERTEAMMEMBERS B
        WHERE A.LINK_MAN = B.MANAGERID
    UPDATE #TEMP_TPRODUCT_MARKETING
        SET QUOTAMONEY = B.QUOTAMONEY
        FROM #TEMP_TPRODUCT_MARKETING A, TTEAMQUOTA B
        WHERE A.TEAM_ID = B.TEAM_ID AND A.PRODUCT_ID = B.PRODUCT_ID
    UPDATE #TEMP_TPRODUCT_MARKETING
        SET LINK_MAN_NAME = ISNULL(B.OP_NAME,'')
        FROM #TEMP_TPRODUCT_MARKETING A, TOPERATOR B
        WHERE A.LINK_MAN = ISNULL(B.OP_CODE,0)
           
	
	--对明细数据 三个维度总和GROUP BY一次
	BEGIN
		INSERT INTO #TEMP_TPRODUCT_MARKETING(PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,LINK_MAN,LINK_MAN_NAME,
											TEAM_ID,TEAM_NO,TEAM_NAME,RG_MONEY,TO_MONEY,QUOTAMONEY)
			SELECT PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,LINK_MAN,LINK_MAN_NAME,TEAM_ID,TEAM_NO,TEAM_NAME,
											SUM(RG_MONEY) AS RG_MONEY ,SUM(TO_MONEY) AS TO_MONEY,SUM(QUOTAMONEY) AS	QUOTAMONEY
				FROM  #TEMP_TPRODUCT_MARKETING	
				WHERE (PRODUCT_ID = @IN_PRODUCT_ID OR @IN_PRODUCT_ID IS NULL OR @IN_PRODUCT_ID = 0)
		    	AND(TEAM_ID = @IN_TEAM_ID OR @IN_TEAM_ID IS NULL OR @IN_TEAM_ID = 0 OR TEAM_ID IS NULL)
                AND(LINK_MAN = @IN_LEADER_NAME OR ISNULL(@IN_LEADER_NAME,0)=0)                
			GROUP BY PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,LINK_MAN,LINK_MAN_NAME,TEAM_ID,TEAM_NO,TEAM_NAME		
		UPDATE 	#TEMP_TPRODUCT_MARKETING SET DATE_TYPE = @V_DATE_TYPE+1 WHERE DATE_TYPE IS NULL
		SELECT @V_DATE_TYPE = MAX(DATE_TYPE) FROM #TEMP_TPRODUCT_MARKETING			
	END																							
	
	IF @IN_TEAM_FLAG = 2	--不按团队来统计 
	BEGIN
		INSERT INTO #TEMP_TPRODUCT_MARKETING(LINK_MAN,LINK_MAN_NAME,RG_MONEY,TO_MONEY,QUOTAMONEY,PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME)
			SELECT LINK_MAN,LINK_MAN_NAME,SUM(RG_MONEY) AS RG_MONEY,SUM(TO_MONEY) AS TO_MONEY,SUM(QUOTAMONEY) AS QUOTAMONEY,PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME
				FROM #TEMP_TPRODUCT_MARKETING WHERE DATE_TYPE = @V_DATE_TYPE
				GROUP BY LINK_MAN,LINK_MAN_NAME,PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME
		UPDATE 	#TEMP_TPRODUCT_MARKETING SET DATE_TYPE = @V_DATE_TYPE+1 WHERE DATE_TYPE IS NULL
		SELECT @V_DATE_TYPE = MAX(DATE_TYPE) FROM #TEMP_TPRODUCT_MARKETING
	END 
	
	IF @IN_SALE_FLAG = 2	--不按销售经理来统计 
	BEGIN
		INSERT INTO #TEMP_TPRODUCT_MARKETING(TEAM_ID,TEAM_NO,TEAM_NAME,RG_MONEY,TO_MONEY,QUOTAMONEY,PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME)
			SELECT TEAM_ID,TEAM_NO,TEAM_NAME,SUM(RG_MONEY) AS RG_MONEY,SUM(TO_MONEY) AS TO_MONEY,SUM(QUOTAMONEY) AS QUOTAMONEY,PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME
				FROM #TEMP_TPRODUCT_MARKETING WHERE DATE_TYPE = @V_DATE_TYPE
				GROUP BY TEAM_ID,TEAM_NO,TEAM_NAME,PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME
		UPDATE 	#TEMP_TPRODUCT_MARKETING SET DATE_TYPE = @V_DATE_TYPE+1 WHERE DATE_TYPE IS NULL
		SELECT @V_DATE_TYPE = MAX(DATE_TYPE) FROM #TEMP_TPRODUCT_MARKETING
	END  
	
	IF @IN_PRODUCT_FLAG = 2   --不按产品来统计 
    BEGIN    
    	INSERT INTO #TEMP_TPRODUCT_MARKETING(TEAM_ID,TEAM_NO,TEAM_NAME,LINK_MAN,LINK_MAN_NAME,RG_MONEY,TO_MONEY,QUOTAMONEY)
		    SELECT TEAM_ID,TEAM_NO,TEAM_NAME,LINK_MAN,LINK_MAN_NAME,SUM(RG_MONEY) AS RG_MONEY,SUM(TO_MONEY) AS TO_MONEY,SUM(QUOTAMONEY) AS QUOTAMONEY
		    	FROM #TEMP_TPRODUCT_MARKETING WHERE DATE_TYPE = @V_DATE_TYPE
		    GROUP BY TEAM_ID,TEAM_NO,TEAM_NAME,LINK_MAN,LINK_MAN_NAME
		UPDATE 	#TEMP_TPRODUCT_MARKETING SET DATE_TYPE = @V_DATE_TYPE+1 WHERE DATE_TYPE IS NULL
		SELECT @V_DATE_TYPE = MAX(DATE_TYPE) FROM #TEMP_TPRODUCT_MARKETING    
	END

		
	SELECT * FROM #TEMP_TPRODUCT_MARKETING WHERE (DATE_TYPE = @V_DATE_TYPE)
			AND (PRODUCT_ID=@IN_PRODUCT_ID OR ISNULL(@IN_PRODUCT_ID,0)=0)
			AND (TEAM_ID=@IN_TEAM_ID OR ISNULL(@IN_TEAM_ID,0)=0)
		
       
GO
