USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TCONTRACT_END @IN_BOOK_CODE INT,
                                        @IN_PRODUCT_ID INT,
                                        @IN_CONTRACT_BH VARCHAR(13),
                                        @IN_BEGIN_DATE INT,
                                        @IN_END_DATE INT,
                                        @IN_INPUT_MAN INT,
                                        @IN_CONTRACT_SUB_BH VARCHAR(50) = NULL, -- 合同编号查询  20080104 by wangc
                                        @IN_SUB_PRODUCT_ID        INT   =0    --子产品ID   20111112  LUOHH
WITH ENCRYPTION
AS
--20409: The Products can be accessed. START
    DECLARE @V_SW20409 INT
    SELECT @V_SW20409 = VALUE FROM TSYSCONTROL WHERE FLAG_TYPE = 'SW20409'
    DECLARE @V_PRODUCTS TABLE(PRODUCT_ID INT)
    IF @V_SW20409 = 1
        INSERT INTO @V_PRODUCTS
            SELECT PRODUCT_ID FROM INTRUST..TPRODUCT WHERE BOOK_CODE = @IN_BOOK_CODE
                AND(INTRUST_FLAG1 IN ( SELECT FUNC_ID-2040900 FROM TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID > 2040900 AND FUNC_ID <= 2040902 AND OP_CODE = @IN_INPUT_MAN )
                    OR DEPART_ID IN (SELECT B.DEPART_ID FROM TOPRIGHT A,TOPERATOR B WHERE A.OP_CODE = B.OP_CODE AND A.MENU_ID = '20409' AND A.FUNC_ID = 2040903 AND A.OP_CODE = @IN_INPUT_MAN)
                    OR PRODUCT_ID IN ( SELECT FUNC_ID FROM TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID < 2040900 AND OP_CODE = @IN_INPUT_MAN)
                    OR ADMIN_MANAGER = @IN_INPUT_MAN OR INPUT_MAN = @IN_INPUT_MAN OR ISNULL(@IN_INPUT_MAN,0)=0 
                    OR SUB_MAN = @IN_INPUT_MAN OR SUB_MAN2 = @IN_INPUT_MAN
                    OR CASH_MAN = @IN_INPUT_MAN OR CASH_MAN2 = @IN_INPUT_MAN
                    OR ADMIN_MANAGER IN(SELECT OP_CODE FROM INTRUST..TOPCUSTRIGHT WHERE ENABLE_OP_CODE = @IN_INPUT_MAN))
--20409: The Products can be accessed. END
      SELECT B.CUST_NO,B.CUST_NAME,A.CONTRACT_SUB_BH,A.CONTRACT_BH,A.PRODUCT_NAME,A.RG_MONEY,A.CURRENCY_ID,A.END_DATE,A.START_DATE,C.LIST_NAME,C.LIST_NAME AS SUB_PRODUCT_NAME
      FROM INTRUST..TCONTRACT A LEFT JOIN INTRUST..TSUBPRODUCT C ON (A.SUB_PRODUCT_ID =C.SUB_PRODUCT_ID),INTRUST..TCUSTOMERINFO B
        WHERE A.BOOK_CODE = @IN_BOOK_CODE
            AND (A.PRODUCT_ID = @IN_PRODUCT_ID OR ISNULL(@IN_PRODUCT_ID,0) = 0)
            AND (ISNULL(@IN_SUB_PRODUCT_ID,0) =0 OR A.SUB_PRODUCT_ID =@IN_SUB_PRODUCT_ID)
            AND (A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM INTRUST..TPRODUCT WHERE PRODUCT_STATUS IN('110203','110204')))
            AND (A.CONTRACT_BH LIKE @IN_CONTRACT_BH+'%' OR ISNULL(@IN_CONTRACT_BH,'') = '')
            AND (A.CONTRACT_SUB_BH LIKE @IN_CONTRACT_SUB_BH+'%' OR ISNULL(@IN_CONTRACT_SUB_BH,'') = '')
            AND(A.END_DATE <= @IN_END_DATE OR ISNULL(@IN_END_DATE,0) = 0)
            AND(A.END_DATE >= @IN_BEGIN_DATE OR ISNULL(@IN_BEGIN_DATE,0) = 0)
            AND A.CUST_ID = B.CUST_ID
            AND(@V_SW20409 = 0 OR @V_SW20409 IS NULL OR A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCTS))
        ORDER BY A.PRODUCT_ID,A.CONTRACT_BH
GO
