USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_COPY_TROLERIGHT @IN_FROM_ROLE_ID     INT,        --源角色
                                    @IN_TO_ROLE_ID       INT,        --目的角色
                                    @IN_INPUT_MAN        INT         --操作员
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT
    DECLARE @SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)
    SELECT @V_RET_CODE = -10701000, @IBUSI_FLAG = 10701
    SELECT @SBUSI_NAME = N'角色权限复制', @SSUMMARY = N'角色权限复制'

    IF NOT EXISTS(SELECT 1 FROM TROLE WHERE ROLE_ID = @IN_FROM_ROLE_ID)
        RETURN @V_RET_CODE - 1      --源角色不存在
    IF NOT EXISTS(SELECT 1 FROM TROLE WHERE ROLE_ID = @IN_TO_ROLE_ID)
        RETURN @V_RET_CODE - 2      --目的角色不存在
    IF @IN_FROM_ROLE_ID = @IN_TO_ROLE_ID
        RETURN @V_RET_CODE - 3      --源角色与目的角色不能相同
    BEGIN TRANSACTION

    INSERT INTO TROLERIGHT(ROLE_ID,MENU_ID,FUNC_ID)
        SELECT @IN_TO_ROLE_ID,A.MENU_ID,A.FUNC_ID
            FROM TROLERIGHT A
            WHERE A.ROLE_ID = @IN_FROM_ROLE_ID AND
                NOT EXISTS(SELECT 1 FROM TROLERIGHT B WHERE B.ROLE_ID = @IN_TO_ROLE_ID AND A.MENU_ID = B.MENU_ID AND A.FUNC_ID = B.FUNC_ID)

    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END


    SET @SSUMMARY = N'角色权限复制，从角色编号：' + CONVERT(NVARCHAR(8),@IN_FROM_ROLE_ID) + N'到角色:' + CONVERT(NVARCHAR(8),@IN_TO_ROLE_ID)
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
