USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TCUSTOMER_SOURCE_DETAIL @IN_CUST_ID      INT,
												  @IN_INPUT_MAN	   INT
                                     
WITH ENCRYPTION
AS
    BEGIN
        SELECT C.CUST_NAME,B.PRODUCT_CODE,B.PRODUCT_NAME,D.CONTRACT_SUB_BH,A.BEN_AMOUNT,D.RG_MONEY,A.BEN_DATE,D.START_DATE
			FROM INTRUST..TBENIFITOR A LEFT JOIN INTRUST..TCONTRACT D ON A.PRODUCT_ID = D.PRODUCT_ID AND A.CUST_ID = D.CUST_ID AND A.CONTRACT_BH = D.CONTRACT_BH
			,INTRUST..TPRODUCT B,TCUSTOMERS C
			WHERE  A.CUST_ID= @IN_CUST_ID
			AND A.CUST_ID = C.CUST_ID
			AND A.PRODUCT_ID = B.PRODUCT_ID
			ORDER BY A.CUST_ID,B.PRODUCT_CODE,A.PRODUCT_ID,C.CUST_NAME,B.PRODUCT_NAME,D.CONTRACT_SUB_BH,A.TO_AMOUNT,D.RG_MONEY,A.BEN_DATE,D.START_DATE

    END
    RETURN 100
GO
