USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TDICTPARAM_VALUE  @IN_TYPE_VALUE NVARCHAR(10),
                                            @OUT_TYPE_CONTENT NVARCHAR(100) OUTPUT
WITH ENCRYPTION
AS

    SELECT @OUT_TYPE_CONTENT =TYPE_CONTENT
    FROM TDICTPARAM
    WHERE TYPE_VALUE = @IN_TYPE_VALUE
GO
