USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
/*
MODI BY JINXR 2009/7/30 查询性能优化
收益分配查询与打印
*/
CREATE PROCEDURE SP_QUERY_TDEPLOY_DETAIL @IN_BOOK_CODE INT,
                                             @IN_PRODUCT_ID INT,
                                             @IN_CONTRACT_BH VARCHAR(16),
                                             @IN_CUST_NO VARCHAR(8),
                                             @IN_CUST_NAME VARCHAR(100),
                                             @IN_INPUT_MAN INT = NULL,
                                             @IN_SY_TYPE1 VARCHAR(10)=NULL,
                                             @IN_SY_TYPE2 VARCHAR(10)=NULL,
                                             @IN_SY_TYPE3 VARCHAR(10)=NULL,
                                             @IN_SY_TYPE4 VARCHAR(10)=NULL,
                                             @IN_SY_TYPE5 VARCHAR(10)=NULL,
                                             @IN_PROV_LEVEL VARCHAR(10)=NULL,
                                             @IN_BEGIN_DATE INT = 0,
                                             @IN_END_DATE INT = 0,
                                             @IN_PRODUCT_NAME VARCHAR(100)=NULL,
                                             @IN_PZ_FLAG INT= 0 ,
                                             @IN_FP_FLAG INT= 0 ,
                                             @IN_CONTRACT_SUB_BH VARCHAR(50)=NULL,
                                             @IN_SUB_PRODUCT_ID     INT   =0,          --子产品ID   20111112  LUOHH
                                             @IN_LINK_MAN     INT   =0
WITH ENCRYPTION
AS
--20409: The Products can be accessed. START
    DECLARE @V_SW20409 INT
    SELECT @V_SW20409 = VALUE FROM TSYSCONTROL WHERE FLAG_TYPE = 'SW20409'
    DECLARE @V_PRODUCTS TABLE(PRODUCT_ID INT)
    DECLARE @V_USER_ID INT
    SELECT @V_USER_ID = USER_ID FROM TSYSTEMINFO
    IF @V_SW20409 = 1
        INSERT INTO @V_PRODUCTS
            SELECT PRODUCT_ID FROM INTRUST..TPRODUCT WHERE BOOK_CODE = @IN_BOOK_CODE
                AND(INTRUST_FLAG1 IN ( SELECT FUNC_ID-2040900 FROM TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID > 2040900 AND FUNC_ID <= 2040902 AND OP_CODE = @IN_INPUT_MAN )
                    OR DEPART_ID IN (SELECT B.DEPART_ID FROM TOPRIGHT A,TOPERATOR B WHERE A.OP_CODE = B.OP_CODE AND A.MENU_ID = '20409' AND A.FUNC_ID = 2040903 AND A.OP_CODE = @IN_INPUT_MAN)
                    OR PRODUCT_ID IN ( SELECT FUNC_ID FROM TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID < 2040900 AND OP_CODE = @IN_INPUT_MAN)
                    OR ADMIN_MANAGER = @IN_INPUT_MAN OR INPUT_MAN = @IN_INPUT_MAN
                    OR SUB_MAN = @IN_INPUT_MAN OR SUB_MAN2 = @IN_INPUT_MAN
                    OR CASH_MAN = @IN_INPUT_MAN OR CASH_MAN2 = @IN_INPUT_MAN
					OR ADMIN_MANAGER IN(SELECT OP_CODE FROM INTRUST..TOPCUSTRIGHT WHERE ENABLE_OP_CODE = @IN_INPUT_MAN) OR ISNULL(@IN_INPUT_MAN,0)=0 )
    --20409: The Products can be accessed. END
    IF @IN_BEGIN_DATE IS NULL SELECT @IN_BEGIN_DATE = 0
    IF @IN_END_DATE IS NULL SELECT @IN_END_DATE = 0
    IF @V_USER_ID = 24 BEGIN
		SELECT C.BANK_ACCT,C.BANK_NAME+ISNULL(C.BANK_SUB_NAME,'') AS BANK_NAME,A.*,B.CUST_NO,B.CUST_NAME,E.CONTRACT_SUB_BH,C.CUST_ACCT_NAME,B.CARD_ID,C.BANK_ID,D.PRODUCT_NAME,C.PROV_LEVEL_NAME,F.LIST_NAME,F.LIST_NAME AS SUB_PRODUCT_NAME
			FROM INTRUST..TDEPLOY A,INTRUST..TCUSTOMERINFO B,INTRUST..TBENIFITOR C,INTRUST..TPRODUCT D,INTRUST..TCONTRACT E LEFT JOIN INTRUST..TSUBPRODUCT F ON (E.SUB_PRODUCT_ID =F.SUB_PRODUCT_ID)
			WHERE A.CUST_ID = B.CUST_ID AND A.BOOK_CODE  = @IN_BOOK_CODE AND A.PRODUCT_ID=D.PRODUCT_ID
				AND (C.PRODUCT_ID = E.PRODUCT_ID AND C.CONTRACT_BH = E.CONTRACT_BH)
				AND (A.PRODUCT_ID = @IN_PRODUCT_ID OR ISNULL(@IN_PRODUCT_ID,0) = 0)
				AND (A.CONTRACT_BH LIKE '%'+@IN_CONTRACT_BH+'%' OR ISNULL(@IN_CONTRACT_BH,'') = '')
				AND (E.CONTRACT_SUB_BH LIKE '%'+@IN_CONTRACT_SUB_BH+'%' OR ISNULL(@IN_CONTRACT_SUB_BH,'') = '')
				AND (B.CUST_NO LIKE '%'+@IN_CUST_NO OR B.CUST_NO LIKE @IN_CUST_NO+'_______' OR ISNULL(@IN_CUST_NO,'') = '')
				AND (B.CUST_NAME LIKE '%'+@IN_CUST_NAME+'%' OR ISNULL(@IN_CUST_NAME,'') = '')
				AND (@V_SW20409 = 0 OR @V_SW20409 IS NULL OR A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCTS))
				AND A.SY_TYPE IN(@IN_SY_TYPE1,@IN_SY_TYPE2 ,@IN_SY_TYPE3,@IN_SY_TYPE4,@IN_SY_TYPE5)
				AND A.PRODUCT_ID=C.PRODUCT_ID AND A.CONTRACT_BH=C.CONTRACT_BH AND A.LIST_ID=C.LIST_ID
				AND (C.PROV_LEVEL = @IN_PROV_LEVEL OR ISNULL(@IN_PROV_LEVEL,'')='')
				AND (A.SY_DATE >= @IN_BEGIN_DATE OR @IN_BEGIN_DATE = 0)
				AND (A.SY_DATE <= @IN_END_DATE OR @IN_END_DATE = 0)
				AND (A.PZ_FLAG=@IN_PZ_FLAG OR ISNULL(@IN_PZ_FLAG,0)= 0)
				AND (A.FP_FLAG=@IN_FP_FLAG OR ISNULL(@IN_FP_FLAG,0)= 0)
				AND (D.PRODUCT_NAME LIKE '%'+@IN_PRODUCT_NAME+'%' OR ISNULL(@IN_PRODUCT_NAME,'') = '')
				AND (ISNULL(@IN_SUB_PRODUCT_ID,0) =0 OR E.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID)
				AND (ISNULL(@IN_LINK_MAN,0) = 0 OR E.LINK_MAN = @IN_LINK_MAN)
			ORDER BY A.PRODUCT_ID,A.CONTRACT_BH, A.CUST_ID
    END
    ELSE BEGIN
		SELECT C.BANK_ACCT,C.BANK_NAME+ISNULL(C.BANK_SUB_NAME,'') AS BANK_NAME,A.*,B.CUST_NO,B.CUST_NAME,E.CONTRACT_SUB_BH,C.CUST_ACCT_NAME,B.CARD_ID,C.BANK_ID,D.PRODUCT_NAME,C.PROV_LEVEL_NAME,F.LIST_NAME,F.LIST_NAME AS SUB_PRODUCT_NAME
			FROM INTRUST..TDEPLOY A,INTRUST..TCUSTOMERINFO B,INTRUST..TBENIFITOR C,INTRUST..TPRODUCT D,INTRUST..TCONTRACT E LEFT JOIN INTRUST..TSUBPRODUCT F ON (E.SUB_PRODUCT_ID =F.SUB_PRODUCT_ID)
			WHERE A.CUST_ID = B.CUST_ID AND A.BOOK_CODE  = @IN_BOOK_CODE AND A.PRODUCT_ID=D.PRODUCT_ID
				AND (C.PRODUCT_ID = E.PRODUCT_ID AND C.CONTRACT_BH = E.CONTRACT_BH)
				AND (A.PRODUCT_ID = @IN_PRODUCT_ID OR ISNULL(@IN_PRODUCT_ID,0) = 0)
				AND (A.CONTRACT_BH LIKE '%'+@IN_CONTRACT_BH+'%' OR ISNULL(@IN_CONTRACT_BH,'') = '')
				AND (E.CONTRACT_SUB_BH LIKE '%'+@IN_CONTRACT_SUB_BH+'%' OR ISNULL(@IN_CONTRACT_SUB_BH,'') = '')
				AND (B.CUST_NO LIKE '%'+@IN_CUST_NO OR B.CUST_NO LIKE @IN_CUST_NO+'_______' OR ISNULL(@IN_CUST_NO,'') = '')
				AND (B.CUST_NAME LIKE '%'+@IN_CUST_NAME+'%' OR ISNULL(@IN_CUST_NAME,'') = '')
				AND (@V_SW20409 = 0 OR @V_SW20409 IS NULL OR A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCTS))
				AND A.SY_TYPE IN(@IN_SY_TYPE1,@IN_SY_TYPE2 ,@IN_SY_TYPE3,@IN_SY_TYPE4,@IN_SY_TYPE5)
				AND A.PRODUCT_ID=C.PRODUCT_ID AND A.CONTRACT_BH=C.CONTRACT_BH AND A.LIST_ID=C.LIST_ID
				AND (C.PROV_LEVEL = @IN_PROV_LEVEL OR ISNULL(@IN_PROV_LEVEL,'')='')
				AND (A.SY_DATE >= @IN_BEGIN_DATE OR @IN_BEGIN_DATE = 0)
				AND (A.SY_DATE <= @IN_END_DATE OR @IN_END_DATE = 0)
				AND (A.PZ_FLAG=@IN_PZ_FLAG OR ISNULL(@IN_PZ_FLAG,0)= 0)
				AND (A.FP_FLAG=@IN_FP_FLAG OR ISNULL(@IN_FP_FLAG,0)= 0)
				AND (D.PRODUCT_NAME LIKE '%'+@IN_PRODUCT_NAME+'%' OR ISNULL(@IN_PRODUCT_NAME,'') = '')
				AND (ISNULL(@IN_SUB_PRODUCT_ID,0) =0 OR E.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID)
				AND (ISNULL(@IN_LINK_MAN,0) = 0 OR E.LINK_MAN = @IN_LINK_MAN)
			ORDER BY A.PRODUCT_ID,C.PROV_LEVEL,A.CONTRACT_BH, A.CUST_ID
    END
GO
