USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE SP_ADD_TATTACHMENTTYPE @IN_ATTACHMENT_TYPE_NAME        NVARCHAR(30),  --附件类别名称
                                        @IN_ATTACHMENT_TYPE_SUMMARY     NVARCHAR(200), --附件类别描述
                                        @IN_IS_NECESSARY                INT,           --是否必要附件 1是 2否
                                        @IN_DF_TABLE_ID                 INT,           --对应表ID，取1010字典参数值后2位转换为整数
                                        @IN_DF_TABLE_NAME               NVARCHAR(60),  --对应DF_TABLE_ID的表名
                                        @IN_INPUT_MAN                   INT            --操作员
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200),@TABLE_ID NVARCHAR(60)
    SELECT @TABLE_ID = '1010'+@IN_DF_TABLE_NAME
    SELECT @SBUSI_NAME = N'增加文件附件类别'
    SELECT @SSUMMARY = N'增加文件附件类别'
    SELECT @IBUSI_FLAG = 10120
    SELECT @V_RET_CODE = -10120000

    IF EXISTS(SELECT * FROM TATTACHMENTTYPE WHERE DF_TABLE_ID = @IN_DF_TABLE_ID AND ATTACHMENT_TYPE_NAME = @IN_ATTACHMENT_TYPE_NAME)
        RETURN @V_RET_CODE - 1   -- 附件类别已存在

    BEGIN TRANSACTION

    SELECT @IN_DF_TABLE_NAME=TYPE_CONTENT FROM TDICTPARAM WHERE (TYPE_VALUE = @TABLE_ID)
    INSERT INTO TATTACHMENTTYPE(ATTACHMENT_TYPE_NAME,ATTACHMENT_TYPE_SUMMARY,IS_NECESSARY,DF_TABLE_ID,
                        DF_TABLE_NAME) VALUES(@IN_ATTACHMENT_TYPE_NAME,@IN_ATTACHMENT_TYPE_SUMMARY,
                        @IN_IS_NECESSARY,@IN_DF_TABLE_ID,@IN_DF_TABLE_NAME)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SELECT @SSUMMARY = N'增加文件附件类别：'+@IN_DF_TABLE_NAME+N':'+@IN_ATTACHMENT_TYPE_NAME
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
