USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_SALE_COST_PRODUCT @IN_PRODUCT_ID          INT,
                                            @IN_CELL_ID             INT,
                                            @IN_INPUT_MAN           INT = NULL
WITH ENCRYPTION
AS
    DECLARE @V_DT_INTRUST INT
    SELECT @V_DT_INTRUST = VALUE FROM TSYSCONTROL WHERE FLAG_TYPE = N'DT_INTRUST'
    CREATE TABLE #CELL_ALL(CELL_ID      INT,
                           CELL_CODE    NVARCHAR(20),
                           CELL_NAME    NVARCHAR(120),
                           CELL_TYPE    INT,
                           PRODUCT_ID   INT,
                           PRODUCT_CODE NVARCHAR(20),
                           PRODUCT_NAME NVARCHAR(120))
    IF @IN_CELL_ID IS NOT NULL AND @IN_CELL_ID <> 0
    BEGIN
        IF @V_DT_INTRUST = 1 --启用分布式
            INSERT INTO #CELL_ALL(CELL_ID,CELL_CODE,CELL_NAME,PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME)
                SELECT SERIAL_NO,CELL_CODE,CELL_NAME,PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME FROM SRV_Intrust.INTRUST.dbo.TPRODUCT_CELL
                WHERE SERIAL_NO = @IN_CELL_ID
        ELSE IF (@V_DT_INTRUST = 2) AND EXISTS(SELECT * FROM master..sysdatabases WHERE NAME = N'INTRUST') --本地信托数据库
            INSERT INTO #CELL_ALL(CELL_ID,CELL_CODE,CELL_NAME,PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME)
                SELECT SERIAL_NO,CELL_CODE,CELL_NAME,PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME FROM INTRUST..TPRODUCT_CELL
                WHERE SERIAL_NO = @IN_CELL_ID
        WHILE @@ROWCOUNT > 0
        BEGIN
            IF @V_DT_INTRUST = 1 --启用分布式
                INSERT INTO #CELL_ALL(CELL_ID)
                    SELECT A.SUB_CELL_ID
                    FROM  SRV_Intrust.INTRUST.dbo.TPRODUCT_CELL_DETAIL A, #CELL_ALL B
                    WHERE A.DF_SERIAL_NO = B.CELL_ID AND A.SUB_CELL_ID NOT IN(SELECT CELL_ID FROM #CELL_ALL)
            ELSE IF (@V_DT_INTRUST = 2) AND EXISTS(SELECT * FROM master..sysdatabases WHERE NAME = N'INTRUST') --本地信托数据库
                INSERT INTO #CELL_ALL(CELL_ID)
                    SELECT A.SUB_CELL_ID
                    FROM  INTRUST..TPRODUCT_CELL_DETAIL A, #CELL_ALL B
                    WHERE A.DF_SERIAL_NO = B.CELL_ID AND A.SUB_CELL_ID NOT IN(SELECT CELL_ID FROM #CELL_ALL)
        END
        IF @V_DT_INTRUST = 1 --启用分布式
            UPDATE #CELL_ALL
                SET CELL_CODE = B.CELL_CODE,
                    CELL_NAME = B.CELL_NAME,
                    CELL_TYPE = B.CELL_TYPE,
                    PRODUCT_ID = B.PRODUCT_ID,
                    PRODUCT_CODE = B.PRODUCT_CODE,
                    PRODUCT_NAME = B.PRODUCT_NAME
                FROM #CELL_ALL A , SRV_Intrust.INTRUST.dbo.TPRODUCT_CELL B
                WHERE A.CELL_ID = B.SERIAL_NO
        ELSE IF (@V_DT_INTRUST = 2) AND EXISTS(SELECT * FROM master..sysdatabases WHERE NAME = N'INTRUST') --本地信托数据库
            UPDATE #CELL_ALL
                SET CELL_CODE = B.CELL_CODE,
                    CELL_NAME = B.CELL_NAME,
                    CELL_TYPE = B.CELL_TYPE,
                    PRODUCT_ID = B.PRODUCT_ID,
                    PRODUCT_CODE = B.PRODUCT_CODE,
                    PRODUCT_NAME = B.PRODUCT_NAME
                FROM #CELL_ALL A , INTRUST..TPRODUCT_CELL B
                WHERE A.CELL_ID = B.SERIAL_NO
    END

    IF @V_DT_INTRUST = 1 --启用分布式
    BEGIN
        SELECT C.PRODUCT_ID,C.PRODUCT_CODE,C.PRODUCT_NAME,C.FACT_MONEY,SUM(B.ACTIVITY_FEE/A.RG_TIMES) AS ACTIVITY_FEE
            FROM TCUSTOMERS A LEFT JOIN TCUSTSERVICEINFO B ON(A.CUST_ID = B.CUST_ID)
                 RIGHT JOIN SRV_Intrust.INTRUST.dbo.TCONTRACT D ON(A.CUST_ID = D.CUST_ID)
                 RIGHT JOIN SRV_Intrust.INTRUST.dbo.TPRODUCT C ON(C.PRODUCT_ID = D.PRODUCT_ID AND D.CHECK_FLAG = 2 )
            WHERE (C.PRODUCT_ID = @IN_PRODUCT_ID OR @IN_PRODUCT_ID = 0 OR @IN_PRODUCT_ID IS NULL)
               AND (C.PRODUCT_ID IN (SELECT PRODUCT_ID FROM #CELL_ALL) OR NOT EXISTS(SELECT 1 FROM #CELL_ALL) )
            GROUP BY C.PRODUCT_ID,C.PRODUCT_CODE,C.PRODUCT_NAME,C.FACT_MONEY
    END
    ELSE IF (@V_DT_INTRUST = 2) AND EXISTS(SELECT * FROM master..sysdatabases WHERE NAME = N'INTRUST') --本地信托数据库
    BEGIN
        SELECT C.PRODUCT_ID,C.PRODUCT_CODE,C.PRODUCT_NAME,C.FACT_MONEY,SUM(B.ACTIVITY_FEE/A.RG_TIMES) AS ACTIVITY_FEE
            FROM TCUSTOMERS A LEFT JOIN TCUSTSERVICEINFO B ON(A.CUST_ID = B.CUST_ID)
                 RIGHT JOIN INTRUST..TCONTRACT D ON(A.CUST_ID = D.CUST_ID)
                 RIGHT JOIN INTRUST..TPRODUCT C ON(C.PRODUCT_ID = D.PRODUCT_ID AND D.CHECK_FLAG = 2 )
            WHERE (C.PRODUCT_ID = @IN_PRODUCT_ID OR @IN_PRODUCT_ID = 0 OR @IN_PRODUCT_ID IS NULL)
               AND (C.PRODUCT_ID IN (SELECT PRODUCT_ID FROM #CELL_ALL) OR NOT EXISTS(SELECT 1 FROM #CELL_ALL) )
            GROUP BY C.PRODUCT_ID,C.PRODUCT_CODE,C.PRODUCT_NAME,C.FACT_MONEY
    END

GO
