USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TPRODUCTIntroduction
				@IN_PRODUCT_ID      INTEGER,         --产品ID
				@IN_PRE_PRODUCT_ID  INTEGER,         --预发行产品ID
				@IN_INPUT_MAN       INTEGER          --录入人
WITH ENCRYPTION
AS
    SELECT * 
      FROM TPRODUCTIntroduction
      WHERE @IN_PRODUCT_ID>0 AND PRODUCT_ID=@IN_PRODUCT_ID
        OR @IN_PRE_PRODUCT_ID>0 AND PRE_PRODUCT_ID=@IN_PRE_PRODUCT_ID
GO
