USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TBENIFITOR_MODIUNCHECK @IN_FUNCTION_ID    INT,        --100帐号修改时调用返回受益人信息，@IN_CONTRACT_BH或@IN_CUST_NO必输入一项
                                                                                --200审核时调用，返回修改未审核记录，@IN_CONTRACT_BH和@IN_CUST_NO无效
                                                                                --300财务审核时调用，返回修改未审核记录，@IN_CONTRACT_BH和@IN_CUST_NO无效
                                                 @IN_BOOK_CODE          INTEGER,
                                                 @IN_SERIAL_NO          INTEGER,
                                                 @IN_CONTRACT_BH        VARCHAR(16),
                                                 @IN_CARD_ID            VARCHAR(20),
                                                 @IN_PRODUCT_ID         INTEGER     = NULL,
                                                 @IN_PRODUCT_NAME       VARCHAR(60) = NULL,
                                                 @IN_INPUT_MAN          INTEGER     = NULL,
                                                 @IN_CUST_NAME          VARCHAR(60) = NULL,
                                                 @IN_CONTRACT_SUB_BH    VARCHAR(50) = NULL,
                                                 @IN_SUB_PRODUCT_ID     INTEGER     = 0,
                                                 @IN_START_DATE         INTEGER     = 0, --开始时间
                                                 @IN_END_DATE           INTEGER     = 0  --结束时间
WITH ENCRYPTION
AS
    --20409: The Products can be accessed. START
    DECLARE @V_SW20409 INT
    SELECT @V_SW20409 = VALUE FROM INTRUST..TSYSCONTROL WHERE FLAG_TYPE = 'SW20409'
    DECLARE @V_PRODUCTS TABLE(PRODUCT_ID INT)
    IF @V_SW20409 = 1
        INSERT INTO @V_PRODUCTS
            SELECT PRODUCT_ID FROM INTRUST..TPRODUCT WHERE BOOK_CODE = @IN_BOOK_CODE
                AND(INTRUST_FLAG1 IN ( SELECT FUNC_ID-2040900 FROM INTRUST..TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID > 2040900 AND FUNC_ID <= 2040902 AND OP_CODE = @IN_INPUT_MAN )
                    OR DEPART_ID IN (SELECT B.DEPART_ID FROM INTRUST..TOPRIGHT A,TOPERATOR B WHERE A.OP_CODE = B.OP_CODE AND A.MENU_ID = '20409' AND A.FUNC_ID = 2040903 AND A.OP_CODE = @IN_INPUT_MAN)
                    OR PRODUCT_ID IN ( SELECT FUNC_ID FROM INTRUST..TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID < 2040900 AND OP_CODE = @IN_INPUT_MAN)
                    OR ADMIN_MANAGER = @IN_INPUT_MAN OR INPUT_MAN = @IN_INPUT_MAN OR ISNULL(@IN_INPUT_MAN,0)=0
                    OR SUB_MAN = @IN_INPUT_MAN OR SUB_MAN2 = @IN_INPUT_MAN
                    OR CASH_MAN = @IN_INPUT_MAN OR CASH_MAN2 = @IN_INPUT_MAN
                    OR ADMIN_MANAGER IN(SELECT OP_CODE FROM INTRUST..TOPCUSTRIGHT WHERE ENABLE_OP_CODE = @IN_INPUT_MAN)
                    )
    --20409: The Products can be accessed. END
    IF (@IN_FUNCTION_ID = 100) BEGIN		
        SELECT A.SERIAL_NO,D.CONTRACT_SUB_BH,B.CUST_NO,B.CUST_NAME,B.CARD_ID,A.BANK_ID,A.BANK_SUB_NAME,A.BANK_PROVINCE,A.BANK_CITY,A.BANK_ACCT,A.CUST_ACCT_NAME,A.ACCT_CHG_REASON
            FROM INTRUST..TBENIFITOR A, INTRUST..TCUSTOMERINFO B,INTRUST..TPRODUCT C,INTRUST..TCONTRACT D LEFT JOIN INTRUST..TSUBPRODUCT E ON (D.SUB_PRODUCT_ID = E.SUB_PRODUCT_ID)
                WHERE A.CUST_ID = B.CUST_ID AND A.PRODUCT_ID = C.PRODUCT_ID AND A.BOOK_CODE = @IN_BOOK_CODE AND
                     (A.PRODUCT_ID = D.PRODUCT_ID AND A.CONTRACT_BH = D.CONTRACT_BH) AND
                     (A.CONTRACT_BH = @IN_CONTRACT_BH OR ISNULL(@IN_CONTRACT_BH,'') = '') AND
                     (D.CONTRACT_SUB_BH LIKE '%'+@IN_CONTRACT_SUB_BH+'%' OR ISNULL(@IN_CONTRACT_SUB_BH,'') = '') AND
                     (B.CARD_ID LIKE @IN_CARD_ID+'%' OR ISNULL(@IN_CARD_ID,'') = '') AND
                     (A.SERIAL_NO = @IN_SERIAL_NO OR ISNULL(@IN_SERIAL_NO,0) = 0) AND
                     (A.PRODUCT_ID = @IN_PRODUCT_ID OR ISNULL(@IN_PRODUCT_ID,0) = 0) AND
                     (ISNULL(@IN_SUB_PRODUCT_ID,0) =0 OR D.SUB_PRODUCT_ID =@IN_SUB_PRODUCT_ID) AND
                     (@V_SW20409 = 0 OR @V_SW20409 IS NULL OR A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCTS)) AND
                     B.CUST_NAME LIKE '%' + @IN_CUST_NAME + '%' AND --A.BEN_AMOUNT <> 0 AND
                     (C.PRODUCT_NAME LIKE  '%' + @IN_PRODUCT_NAME + '%' OR ISNULL(@IN_PRODUCT_NAME,'') = '') AND
                     (A.MODI_BANK_DATE >= @IN_START_DATE OR ISNULL(@IN_START_DATE,0) = 0) AND
                     (A.MODI_BANK_DATE <= @IN_END_DATE OR ISNULL(@IN_END_DATE,0) = 0) 
    END
    ELSE IF (@IN_FUNCTION_ID = 200)
        SELECT A.*,B.CUST_NO,B.CUST_NAME,D.CONTRACT_SUB_BH,B.CARD_ID,C.PRODUCT_CODE,C.PRODUCT_NAME,E.LIST_NAME,E.LIST_NAME AS SUB_PRODUCT_NAME
            FROM INTRUST..TBENIFITOR A,INTRUST..TCUSTOMERINFO B,INTRUST..TPRODUCT C,INTRUST..TCONTRACT D LEFT JOIN INTRUST..TSUBPRODUCT E ON (D.SUB_PRODUCT_ID = E.SUB_PRODUCT_ID)
            WHERE A.BOOK_CODE = @IN_BOOK_CODE AND A.MODI_ACCT_CHECK_FLAG = 0 AND
                 (A.PRODUCT_ID = D.PRODUCT_ID AND A.CONTRACT_BH = D.CONTRACT_BH) AND
                 (A.SERIAL_NO = @IN_SERIAL_NO OR ISNULL(@IN_SERIAL_NO,0) = 0) AND
                 (A.PRODUCT_ID = @IN_PRODUCT_ID OR ISNULL(@IN_PRODUCT_ID,0) = 0) AND
                 (ISNULL(@IN_SUB_PRODUCT_ID,0) =0 OR D.SUB_PRODUCT_ID =@IN_SUB_PRODUCT_ID) AND
                 (@V_SW20409 = 0 OR @V_SW20409 IS NULL OR A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCTS)) AND
                 A.CUST_ID = B.CUST_ID AND A.PRODUCT_ID = C.PRODUCT_ID AND B.CUST_NAME LIKE '%' + @IN_CUST_NAME + '%' AND
                 (C.PRODUCT_NAME LIKE  '%' + @IN_PRODUCT_NAME + '%' OR ISNULL(@IN_PRODUCT_NAME,'') = '') AND
                 (A.MODI_BANK_DATE >= @IN_START_DATE OR ISNULL(@IN_START_DATE,0) = 0) AND
                 (A.MODI_BANK_DATE <= @IN_END_DATE OR ISNULL(@IN_END_DATE,0) = 0) 
    ELSE IF (@IN_FUNCTION_ID = 300)
        SELECT A.*,B.CUST_NO,B.CUST_NAME,D.CONTRACT_SUB_BH,B.CARD_ID,C.PRODUCT_CODE,C.PRODUCT_NAME,E.LIST_NAME,E.LIST_NAME AS SUB_PRODUCT_NAME
            FROM INTRUST..TBENIFITOR A,INTRUST..TCUSTOMERINFO B,INTRUST..TPRODUCT C,INTRUST..TCONTRACT D LEFT JOIN INTRUST..TSUBPRODUCT E ON (D.SUB_PRODUCT_ID = E.SUB_PRODUCT_ID)
            WHERE A.BOOK_CODE = @IN_BOOK_CODE AND A.MODI_ACCT_CHECK_FLAG = 11 AND
                 (A.PRODUCT_ID = D.PRODUCT_ID AND A.CONTRACT_BH = D.CONTRACT_BH) AND
                 (A.SERIAL_NO = @IN_SERIAL_NO OR ISNULL(@IN_SERIAL_NO,0) = 0) AND
                 (A.PRODUCT_ID = @IN_PRODUCT_ID OR ISNULL(@IN_PRODUCT_ID,0) = 0) AND
                 (ISNULL(@IN_SUB_PRODUCT_ID,0) =0 OR D.SUB_PRODUCT_ID =@IN_SUB_PRODUCT_ID) AND
                 (@V_SW20409 = 0 OR @V_SW20409 IS NULL OR A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCTS)) AND
                 A.CUST_ID = B.CUST_ID AND A.PRODUCT_ID = C.PRODUCT_ID AND B.CUST_NAME LIKE '%' + @IN_CUST_NAME + '%' AND
                 (C.PRODUCT_NAME LIKE  '%' + @IN_PRODUCT_NAME + '%' OR ISNULL(@IN_PRODUCT_NAME,'') = '') AND
                 (A.MODI_BANK_DATE >= @IN_START_DATE OR ISNULL(@IN_START_DATE,0) = 0) AND
                 (A.MODI_BANK_DATE <= @IN_END_DATE OR ISNULL(@IN_END_DATE,0) = 0) 
GO
