USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TCustClassDetail @IN_CLASSDEFINE_ID   INTEGER,        --分级定义ID
                                           @IN_CLASSDETAIL_ID   INTEGER,        --分级明细ID
                                           @IN_INPUT_MAN        INTEGER         --操作员
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    SELECT [CLASSDEFINE_ID]
		  ,[CLASSDEFINE_NAME]
		  ,[CLASSDETAIL_ID]
		  ,[CLASSDETAIL_NAME]
		  ,[CLASS_MINVALUE]
		  ,[CLASS_MAXVALUE]
		  ,[CANMODI]
		  ,[CANADD]
		  ,[CANDEL], 1 AS BOTTOM_FLAG INTO #TMP_QUERY_TCustClassDetail FROM TCustClassDetail WHERE 1=0
    INSERT INTO #TMP_QUERY_TCustClassDetail
        SELECT A.[CLASSDEFINE_ID]
			  ,[CLASSDEFINE_NAME]
			  ,[CLASSDETAIL_ID]
			  ,[CLASSDETAIL_NAME]
			  ,[CLASS_MINVALUE]
			  ,[CLASS_MAXVALUE]
			  ,[CANMODI]
			  ,[CANADD]
			  ,[CANDEL], 1
        FROM TCustClassDetail A
        WHERE (A.CLASSDEFINE_ID   = @IN_CLASSDEFINE_ID   OR @IN_CLASSDEFINE_ID   IS NULL OR @IN_CLASSDEFINE_ID   = 0 )
           AND(A.CLASSDETAIL_ID   = @IN_CLASSDETAIL_ID   OR @IN_CLASSDETAIL_ID   IS NULL OR @IN_CLASSDETAIL_ID   = 0 )
    UPDATE #TMP_QUERY_TCustClassDetail
        SET BOTTOM_FLAG = 2
        FROM #TMP_QUERY_TCustClassDetail A, (SELECT DISTINCT PARENT_VALUE FROM TCustClassDefine ) B
        WHERE A.CLASSDETAIL_ID = B.PARENT_VALUE

    SELECT * FROM #TMP_QUERY_TCustClassDetail
GO
