USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_STAT_TCONTRACT_GUOLIAN
										@IN_PRODUCT_CODE        NVARCHAR(40),           --产品ID
										@IN_QS_DATE1            INTEGER       = NULL,   --认购日期（起）
										@IN_QS_DATE2            INTEGER       = NULL,   --认购日期（止）
										@IN_INPUT_MAN           INTEGER                 --操作员
										
WITH ENCRYPTION
AS
    
    SET @IN_QS_DATE1 = ISNULL(@IN_QS_DATE1,0)
    SET @IN_QS_DATE2 = ISNULL(@IN_QS_DATE2,0)
    IF @IN_QS_DATE2 =0 SET @IN_QS_DATE2 = 20991231
    --建立临时表
    CREATE TABLE #TEMP12(T_ID INT IDENTITY, 
          CONTRACT_SUB_BH NVARCHAR(60),SEX NVARCHAR(4),CUST_NAME NVARCHAR(90),QS_DATE NVARCHAR(20),RG_MONEY NUMERIC(18,3),MOBILE NVARCHAR(20),BANK_ACCT NVARCHAR(60),BANK_NAME NVARCHAR(60),CARD_ID NVARCHAR(60),PROV_LEVEL_NAME NVARCHAR(60),POST_ADDRESS NVARCHAR(60),CHANNEL_NAME NVARCHAR(60)
    )
    --合同号	性别	姓名	认购日期	金额	联系电话	受益卡号	所属银行	证件号码	受益类型	区域	联系地址	渠道
    INSERT INTO #TEMP12(CONTRACT_SUB_BH,SEX,CUST_NAME,QS_DATE,RG_MONEY,MOBILE,BANK_ACCT,BANK_NAME,CARD_ID,PROV_LEVEL_NAME,POST_ADDRESS,CHANNEL_NAME)
    SELECT A.CONTRACT_SUB_BH,CASE B.CUST_TYPE WHEN 2 THEN '机构' ELSE B.SEX_NAME END SEX,B.CUST_NAME,dbo.GETDATESTRYMD(A.QS_DATE) QS_DATE,
               A.RG_MONEY,B.MOBILE,A.BANK_ACCT,A.BANK_NAME,B.CARD_ID,A.PROV_LEVEL_NAME,b.POST_ADDRESS,H.CHANNEL_NAME
            FROM INTRUST..TCONTRACT A LEFT JOIN INTRUST..TSUBPRODUCT D ON A.SUB_PRODUCT_ID = D.SUB_PRODUCT_ID
                 LEFT JOIN INTRUST..TCHANNEL H ON A.CHANNEL_ID = H.CHANNEL_ID AND A.CHANNEL_TYPE = H.CHANNEL_TYPE,
                 INTRUST..TCUSTOMERINFO B, INTRUST..TPRODUCT C
            WHERE A.CUST_ID = B.CUST_ID AND A.PRODUCT_ID = C.PRODUCT_ID AND A.BOOK_CODE  = 1 AND A.HT_STATUS <>'120104'
                --AND (A.CHECK_FLAG = 1)
                --AND (A.PRODUCT_ID = @IN_PRODUCT_ID OR ISNULL(@IN_PRODUCT_ID,0) = 0)
                AND (A.PRODUCT_CODE = @IN_PRODUCT_CODE OR ISNULL(@IN_PRODUCT_CODE,'') = '')
               -- AND (A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM INTRUST..TPRODUCT WHERE (PRODUCT_STATUS = '110202' OR (PRODUCT_STATUS = '110203' AND  FPRG_FLAG =1)) AND (INTRUST_TYPE1 = '113801'OR INTRUST_TYPE1 = '113804')))
                --AND (@V_SW20409 = 0 OR @V_SW20409 IS NULL OR A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCTS))
                AND (A.QS_DATE>=ISNULL(@IN_QS_DATE1,0))
				AND (A.QS_DATE<=ISNULL(@IN_QS_DATE2,20991231))
            ORDER BY A.PRODUCT_ID,A.SUB_PRODUCT_ID,A.CONTRACT_SUB_BH
    INSERT INTO #TEMP12(CONTRACT_SUB_BH,QS_DATE,RG_MONEY)
    SELECT '合计','', SUM(RG_MONEY) RG_MONEY FROM #TEMP12
    SELECT CONTRACT_SUB_BH,SEX,CUST_NAME,QS_DATE,CAST(RG_MONEY AS VARCHAR),MOBILE,BANK_ACCT,BANK_NAME,CARD_ID,PROV_LEVEL_NAME,POST_ADDRESS,CHANNEL_NAME FROM #TEMP12 ORDER BY T_ID

GO
