USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_QUICKSEARCH_TCUSTOMERS	@IN_CUST_NAME		NVARCHAR(60),
													@IN_CUST_TYPE		INTEGER,
													@IN_CARD_TYPE		NVARCHAR(10),
													@IN_CARD_ID			NVARCHAR(30),
													@IN_CUST_TEL		NVARCHAR(20),
													@IN_EMAIL			NVARCHAR(30),
													@IN_PRODUCT_NAME	NVARCHAR(60),
													@IN_INPUT_MAN		INTEGER = 0
WITH ENCRYPTION
AS
	--通过产品名称来过滤受益人表中客户
	DECLARE @V_FLAG_ENCRYPTION INT,@V_IS_DEAL INT,@V_FACT_POTE_FLAG INT,@V_ENCRYPTION_SIZE INT
	SELECT @V_FACT_POTE_FLAG = VALUE FROM TSYSCONTROL WHERE  FLAG_TYPE = 'FACT_POTENTIAL_FLAG'--事实潜在客户加密条件

	SET @V_FLAG_ENCRYPTION = 0 --加密标志
	--如果操作员的角色中存在保密限制的角色，则根据保密优先的原则，则进行保密限制
    IF EXISTS(SELECT 1 FROM TOPROLE WHERE OP_CODE = @IN_INPUT_MAN AND ROLE_ID IN(SELECT ROLE_ID FROM TROLE WHERE FLAG_ENCRYPTION = 1))
        SELECT @V_FLAG_ENCRYPTION = 1
	--加密显示位数	
	IF EXISTS(SELECT 1 FROM TDICTPARAM WHERE TYPE_VALUE = '800701')
		SELECT @V_ENCRYPTION_SIZE = CAST(TYPE_CONTENT AS INT) FROM TDICTPARAM WHERE TYPE_VALUE = '800701'
	ELSE
		SET  @V_ENCRYPTION_SIZE = 4

	BEGIN
		SELECT A.CUST_ID INTO #TEMP_PRODUCT_TABLE FROM INTRUST..TBENIFITOR A,INTRUST..TPRODUCT B
			WHERE (A.PRODUCT_ID = B.PRODUCT_ID)
				AND (B.PRODUCT_NAME LIKE '%'+@IN_PRODUCT_NAME+'%' OR ISNULL(@IN_PRODUCT_NAME,'')='')
			GROUP BY A.CUST_ID

		SELECT A.* INTO  #TEMP_TCUSTOMERS FROM TCUSTOMERS A
		    WHERE (A.CUST_NAME LIKE '%'+@IN_CUST_NAME+'%' OR ISNULL(@IN_CUST_NAME,'')='')
			AND (A.CUST_TYPE = @IN_CUST_TYPE OR ISNULL(@IN_CUST_TYPE,0)=0)
			AND (A.CARD_TYPE = @IN_CARD_TYPE OR ISNULL(@IN_CARD_TYPE,0)=0)
			AND (A.CARD_ID LIKE '%'+@IN_CARD_ID+'%' OR ISNULL(@IN_CARD_ID,'')='')
			AND (A.E_MAIL LIKE '%'+@IN_EMAIL+'%' OR ISNULL(@IN_EMAIL,'')='')
			AND (A.O_TEL LIKE '%'+@IN_CUST_TEL+'%' OR A.H_TEL LIKE '%'+@IN_CUST_TEL+'%' OR A.MOBILE LIKE '%'+@IN_CUST_TEL+'%')
    END



	--开关控制 加密重要联系信息
    IF(@V_FLAG_ENCRYPTION = 1)
    BEGIN
        UPDATE #TEMP_TCUSTOMERS
        SET CARD_ID = ISNULL(stuff(CARD_ID,1,len(CARD_ID)-@V_ENCRYPTION_SIZE,'******'),'****'),
            CUST_TEL = ISNULL(stuff(CUST_TEL,1,len(CUST_TEL)-@V_ENCRYPTION_SIZE,'******'),'****'),
            H_TEL = ISNULL(stuff(H_TEL,1,len(H_TEL)-@V_ENCRYPTION_SIZE,'******'),'****'),
            O_TEL = ISNULL(stuff(O_TEL,1,len(O_TEL)-@V_ENCRYPTION_SIZE,'******'),'****'),
            E_MAIL = ISNULL(stuff(E_MAIL,1,charindex('@',E_MAIL)-1,'******'),''),
            MOBILE = ISNULL(stuff(MOBILE,1,len(MOBILE)-@V_ENCRYPTION_SIZE,'******'),'****'),
            BP = ISNULL(stuff(BP,1,len(BP)-@V_ENCRYPTION_SIZE,'******'),'****'),
            POST_ADDRESS = ISNULL(stuff(POST_ADDRESS,1,len(POST_ADDRESS)-@V_ENCRYPTION_SIZE,'******'),'****')
        WHERE ( (SERVICE_MAN <> @IN_INPUT_MAN ) OR MODI_FLAG <> 1 )  --仅只读的记录才加密数据
            AND (IS_DEAL = @V_IS_DEAL OR ISNULL(@V_IS_DEAL,0)=0)

      --  WHERE ( (SERVICE_MAN <> @IN_INPUT_MAN ) OR MODI_FLAG <> 1 )  --仅只读的记录才加密数据

    END

	BEGIN
	SELECT A.* FROM #TEMP_TCUSTOMERS A,#TEMP_PRODUCT_TABLE B
		WHERE (A.CUST_ID = B.CUST_ID)
	END
GO
