USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_PRECUSTOMERCON  @IN_CUST_NAME     NVARCHAR(60),
                                          @IN_PRODUCT_ID    INTEGER,
                                          @IN_PRODUCT_NAME  NVARCHAR(100),
                                          @IN_INPUT_MAN     INTEGER,
										  @IN_START_DATE	INTEGER = 0,
										  @IN_END_DATE		INTEGER = 0,
										  @IN_PRODUCT_CODE	NVARCHAR(10) = '',
										  @IN_TURN_FLAG		INTEGER = 0
WITH ENCRYPTION
AS

    SELECT CASE TURN_FLAG
				WHEN 1 THEN '未转认购'
			ELSE '已转认购' END AS TURN_FLAG_NAME,* FROM PRECUSTOMERCON
        WHERE  (CUST_NAME LIKE '%'+ISNULL(@IN_CUST_NAME,NULL)+'%')
            AND (PRODUCT_NAME LIKE '%'+ISNULL(@IN_PRODUCT_NAME,NULL)+'%')
			AND (PRODUCT_CODE = @IN_PRODUCT_CODE OR ISNULL(@IN_PRODUCT_CODE,'')='')
            AND (PRODUCT_ID = @IN_PRODUCT_ID OR ISNUll(@IN_PRODUCT_ID,0)=0)
			AND (TURN_FLAG = @IN_TURN_FLAG OR ISNULL(@IN_TURN_FLAG,0)=0)
			AND (dbo.GETDATEINT(INPUT_TIME) >= ISNULL(@IN_START_DATE,0))
			AND (DBO.GETDATEINT(INPUT_TIME) <= ISNULL(@IN_END_DATE,0))
GO
