USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TDEPARTMENT_TREE @IN_DEPART_ID INT
WITH ENCRYPTION
AS
    IF ISNULL(@IN_DEPART_ID,0) = 0
        SELECT * FROM TDEPARTMENT WHERE ISNULL(PARENT_ID,0) = 0 ORDER BY DEPART_ID
    ELSE
        SELECT * FROM TDEPARTMENT WHERE PARENT_ID = @IN_DEPART_ID ORDER BY DEPART_ID
GO
