USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_STAT_QUARTER_STATISTICS_3   @IN_BEGIN_DATE  INT=0,
                                              @IN_END_DATE    INT=0
                                              --@IN_INPUT_MAN   INT

WITH ENCRYPTION
AS

    --新增投资客户数
    DECLARE @V_TEMP_ADDCUST TABLE(PRODUCT_ID INT,CUST_COUNT INT)
    BEGIN
        INSERT INTO @V_TEMP_ADDCUST
            SELECT B.PRODUCT_ID,COUNT(B.CUST_ID) FROM(
                SELECT CUST_ID,MIN(BEN_DATE) AS BEN_DATE,min(product_id) AS PRODUCT_ID
                FROM INTRUST..TBENIFITOR GROUP BY CUST_ID) B
            GROUP BY B.PRODUCT_ID ORDER BY B.PRODUCT_ID
    END

	DECLARE @V_TEMP_DIRECT TABLE(PRODUCT_ID INT,DIRECT_MONEY DECIMAL(16,3))
	BEGIN	--产品认购总金额(先添加产品)
		INSERT INTO @V_TEMP_DIRECT(PRODUCT_ID)
			SELECT PRODUCT_ID FROM INTRUST..TPRODUCT

        --由于遗留的数据会出现问题，所以先取TMONEYDETAIL表中的to_money字段
        UPDATE @V_TEMP_DIRECT SET DIRECT_MONEY = C.TO_MONEY
            FROM @V_TEMP_DIRECT A LEFT JOIN (SELECT A.PRODUCT_ID,SUM(A.TO_MONEY) AS TO_MONEY FROM INTRUST..TMONEYDETAIL A,INTRUST..TCONTRACT B
                WHERE A.PRODUCT_ID = B.PRODUCT_ID
                AND A.CUST_ID = B.CUST_ID
                AND A.CONTRACT_BH = B.CONTRACT_BH
                AND A.IS_JK_DATA = 1 AND ISNULL(A.FEE_TYPE,0) <> 4
                GROUP BY A.PRODUCT_ID)C ON A.PRODUCT_ID = C.PRODUCT_ID

        --
        UPDATE @V_TEMP_DIRECT SET DIRECT_MONEY = C.RG_MONEY
            FROM @V_TEMP_DIRECT A LEFT JOIN (SELECT PRODUCT_ID,SUM(RG_MONEY) AS RG_MONEY FROM INTRUST..TCONTRACT
                                    --WHERE CHANNEL_TYPE LIKE '550001%'
                                    GROUP BY PRODUCT_ID) C ON A.PRODUCT_ID = C.PRODUCT_ID
            WHERE ISNULL(DIRECT_MONEY,0)=0

	END

	--自由资金认购
	DECLARE @V_TEMP_OWNBUY TABLE(PRODUCT_ID INT,OWN_BUY_MONEY DECIMAL(16,3))
	INSERT INTO @V_TEMP_OWNBUY
		SELECT A.PRODUCT_ID,SUM(A.RG_MONEY) FROM INTRUST..TCONTRACT A,INTRUST..TCUSTOMERINFO B
		WHERE A.CUST_ID = B.CUST_ID AND B.STR_FLAG = 1
		GROUP BY A.PRODUCT_ID

	--劣后认购
	DECLARE @V_TEMP_LEVELBUY TABLE(PRODUCT_ID INT,AFTER_BAD_MONEY DECIMAL(16,3))
	INSERT INTO @V_TEMP_LEVELBUY
		SELECT PRODUCT_ID,RG_MONEY FROM INTRUST..TCONTRACT WHERE PROV_FLAG = 3

    DECLARE @V_TEMP_TABLE TABLE(SERIAL_NO INT NOT NULL IDENTITY,
                                NUM_VIEW  NVARCHAR(10),
                                PRODUCT_ID INT,
                                PRODUCT_NAME NVARCHAR(200),
                                VALID_PERIOD_NAME NVARCHAR(30),
                                PRE_MONEY	 DECIMAL(16,3),
                                FACT_MONEY	 DECIMAL(16,3),
                                DIRECT_MONEY DECIMAL(16,3),
                                DIRECT_RATE DECIMAL(5,4),
                                CUST_COUNT INT,
                                OWN_BUY_MONEY DECIMAL(16,3),
                                AFTER_BAD_MONEY DECIMAL(16,3),
                                SALE_MONEY DECIMAL(16,3),
                                WITH_BANK_NAME NVARCHAR(50))

    --产品信息（成立期限=产品期限，计划发现规模=预期发行金额，募集规模=FACT_MONEY,）
    BEGIN
        INSERT INTO @V_TEMP_TABLE(PRODUCT_ID,PRODUCT_NAME,VALID_PERIOD_NAME,
                        PRE_MONEY,FACT_MONEY,DIRECT_MONEY,DIRECT_RATE,CUST_COUNT,OWN_BUY_MONEY,AFTER_BAD_MONEY,WITH_BANK_NAME)
        SELECT A.PRODUCT_ID,A.PRODUCT_NAME,
            CASE ISNULL(A.VALID_PERIOD,0) WHEN 0 THEN B.CONTENT ELSE CONVERT(VARCHAR,A.VALID_PERIOD)+B.CONTENT END AS VALID_PERIOD_NAME ,
            A.PRE_MONEY,A.FACT_MONEY,C.DIRECT_MONEY,
            CASE ISNULL(C.DIRECT_MONEY,0)
				WHEN 0 THEN 0
            ELSE
            	CASE ISNULL(A.FACT_MONEY,0) WHEN 0 THEN 0 ELSE C.DIRECT_MONEY/ISNULL(A.FACT_MONEY,0) END
            END AS DIRECT_RATE ,'',E.OWN_BUY_MONEY,F.AFTER_BAD_MONEY,ISNULL(G.WITH_BANK_NAME,'其他')
            FROM INTRUST..TPRODUCT A LEFT JOIN @V_TEMP_DIRECT C ON A.PRODUCT_ID = C.PRODUCT_ID
									 LEFT JOIN @V_TEMP_OWNBUY E ON A.PRODUCT_ID = E.PRODUCT_ID
									 LEFT JOIN @V_TEMP_LEVELBUY F ON  A.PRODUCT_ID = F.PRODUCT_ID,
				INTRUST..TINIPARAM B,INTRUST..TITEM G
           WHERE A.PERIOD_UNIT = B.TYPE_VALUE AND B.TYPE_ID = 114
            AND A.ITEM_ID = G.ITEM_ID AND G.WITH_BANK_FLAG = 1

    END

    BEGIN
        UPDATE @V_TEMP_TABLE SET CUST_COUNT = A.CUST_COUNT
            FROM @V_TEMP_ADDCUST A,@V_TEMP_TABLE B
            WHERE A.PRODUCT_ID = B.PRODUCT_ID
    END

	BEGIN
		UPDATE @V_TEMP_TABLE SET NUM_VIEW = SERIAL_NO,
								 SALE_MONEY = FACT_MONEY - DIRECT_MONEY
	END
    --合计
    BEGIN
        INSERT INTO @V_TEMP_TABLE(NUM_VIEW,PRE_MONEY,FACT_MONEY,DIRECT_MONEY,CUST_COUNT,OWN_BUY_MONEY,AFTER_BAD_MONEY,SALE_MONEY)
            SELECT '合计',SUM(PRE_MONEY),SUM(FACT_MONEY),SUM(DIRECT_MONEY),SUM(CUST_COUNT),SUM(OWN_BUY_MONEY),SUM(AFTER_BAD_MONEY),SUM(SALE_MONEY)
            FROM @V_TEMP_TABLE
    END
   SELECT NUM_VIEW,PRODUCT_NAME,WITH_BANK_NAME,VALID_PERIOD_NAME,PRE_MONEY,FACT_MONEY,
	CUST_COUNT,DIRECT_MONEY,DIRECT_RATE*100 AS DIRECT_RATE,OWN_BUY_MONEY,AFTER_BAD_MONEY,SALE_MONEY,
	'' AS OTHER_2,'' AS OTHER_3 FROM @V_Temp_Table

GO
