USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE SP_MODI_TMANUALSCORING @IN_MANUAL_ID        INT,             --操作数ID(打分项)
                                       @IN_OPERAND_ID       INT,             --操作数ID(打分项)
                                       @IN_OPERATION_VALUE  NVARCHAR(120),   --选项值
                                       @IN_SCORE            INT,             --得分
                                       @IN_INPUT_MAN        INT              --操作员
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    SELECT @SBUSI_NAME = N'修改人工打分信息'
    SELECT @SSUMMARY = N'修改人工打分信息'
    SELECT @IBUSI_FLAG = 21004
    SELECT @V_RET_CODE = -21004000

    IF NOT EXISTS(SELECT * FROM TMANUALSCORING WHERE MANUAL_ID = @IN_MANUAL_ID)
        RETURN @V_RET_CODE - 1   --人工打分信息不存在

    BEGIN TRANSACTION
    	
    UPDATE TMANUALSCORING
        SET OPERAND_ID = @IN_OPERAND_ID,OPERATION_VALUE = @IN_OPERATION_VALUE,SCORE = @IN_SCORE,INPUT_MAN = @IN_INPUT_MAN
        WHERE MANUAL_ID = @IN_MANUAL_ID
        
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SELECT @SSUMMARY = N'修改人工打分信息:'+RTRIM(CONVERT(NVARCHAR(16),@IN_MANUAL_ID))
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
