USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_DEL_TQuestInfo     @IN_QUES_ID             INT,
                                       @IN_INPUT_MAN           INT = 0         --操作员
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT, @IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)
    SELECT @V_RET_CODE = -30501000, @IBUSI_FLAG = 30501
    SELECT @SBUSI_NAME = N'删除问卷信息', @SSUMMARY = N'删除问卷信息'

    IF NOT EXISTS(SELECT 1 FROM TQuestInfo WHERE QUES_ID = @IN_QUES_ID)
        RETURN @V_RET_CODE - 1 --问卷信息不存在

BEGIN TRANSACTION
    UPDATE TQuestInfo
    SET STATUS = 2
    WHERE QUES_ID = @IN_QUES_ID
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SET @SSUMMARY = N'删除问卷信息，操作员：' + CAST(@IN_INPUT_MAN AS NVARCHAR(10))
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

COMMIT TRANSACTION
    RETURN 100
GO
