USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_STAT_PRODUCT_DETAIL @P_BOOK_CODE    INT,
                                        @P_PRODUCT_CODE VARCHAR(6),--产品编号,空全部
                                        @P_CUST_NO      VARCHAR(8), --客户编号，空全部
                                        @P_RG_MONEY     DEC(16,3),  --零全部，认购金额大于
                                        @P_CUST_TYPE    INT,
                                        @P_SELECT_FLAG  INT = 0,
                                        @IN_INPUT_MAN   INT = NULL,
                                        @P_CELL_FLAG INT = 1,   -- 模式： 1 原来模式 2 产品单元模式
                                        @P_CELL_ID INT = 0   -- 单元ID
WITH ENCRYPTION
AS
    SET NOCOUNT ON

--20409: The Products can be accessed. START REPORT
    DECLARE @V_SW20409_R INT
    SELECT @V_SW20409_R = VALUE FROM INTRUST..TSYSCONTROL WHERE FLAG_TYPE = 'SW20409R'
    DECLARE @V_PRODUCTS TABLE(PRODUCT_ID INT)
--20409: The Products can be accessed. END

   ------临时表
     CREATE TABLE #STAT_PRODUCT_DETAIL(
        PRODUCT_ID       INT,
        PRODUCT_CODE     NVARCHAR(6),
        PRODUCT_NAME     NVARCHAR(100),
        CURRENCY_ID      NVARCHAR(2),
        CONTRACT_BH      NVARCHAR(100),
        VALID_PERIOD     INT,
        QS_DATE          INT,
        START_DATE       INT,
        LINK_MAN         INT,
        LINK_MAN_NAME    NVARCHAR(20),
        END_DATE         INT,
        RG_MONEY         DECIMAL(16,3),
        TO_MONEY         DECIMAL(16,3),
        TO_AMOUNT        DECIMAL(16,3),
        JK_TYPE_NAME     NVARCHAR(30),
        JK_DATE          INT,
        BANK_NAME        NVARCHAR(30),
        BANK_ACCT        NVARCHAR (30) ,
        INPUT_MAN        INT,
        INPUT_MAN_NAME   NVARCHAR(20),
        INPUT_TIME       INT,
        INPUT_CHECK_MAN  INT,
        INPUT_CHECK_MAN_NAME  NVARCHAR(20),
        ZJ_CHECK_MAN     INT,
        ZJ_CHECK_MAN_NAME  NVARCHAR(20),
        HT_STATUS_NAME   NVARCHAR(30),
        SUMMARY          NVARCHAR(200),
        CUST_NO          NVARCHAR (8),
        CUST_NAME        NVARCHAR (100),
        POST_ADDRESS     NVARCHAR (100),
        POST_CODE        NVARCHAR(6),
        CARD_TYPE_NAME   NVARCHAR (30),
        CARD_ID          NVARCHAR (40),
        AGE              INTEGER,
        SEX_NAME         NVARCHAR (10),
        O_TEL            NVARCHAR (40),
        H_TEL            NVARCHAR (40),
        MOBILE           NVARCHAR (100),
        BP               NVARCHAR (60),
        FAX              NVARCHAR (40),
        E_MAIL           NVARCHAR (30),
        CUST_TYPE_NAME   NVARCHAR (10),
        CUST_LEVEL_NAME  NVARCHAR (30),
        TOUCH_TYPE_NAME  NVARCHAR (30),
        CUST_SOURCE_NAME NVARCHAR (30),
        DEPART_ID        INT,
        DEPART_NAME      NVARCHAR(24),
        PERIOD_UNIT      INT,
        PERIOD_STR       NVARCHAR(20),
        DATA_TYPE        INT,
		SUB_PRODUCT_ID   INT,
		EXPECT_ROR_LOWER DEC(5,4),
		EXPECT_ROR_UPPER DEC(5,4),
		PROV_FLAG		 INT ,
		PROV_LEVEL		 NVARCHAR(20)
     )

IF @P_CELL_FLAG = 1
BEGIN
    IF @V_SW20409_R = 1
        INSERT INTO @V_PRODUCTS
            SELECT PRODUCT_ID FROM INTRUST..TPRODUCT WHERE BOOK_CODE = @P_BOOK_CODE
                AND(INTRUST_FLAG1 IN ( SELECT FUNC_ID-2040900 FROM TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID > 2040900 AND FUNC_ID <= 2040999 AND OP_CODE = @IN_INPUT_MAN )
                    OR PRODUCT_ID IN ( SELECT FUNC_ID FROM TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID < 2040900 AND OP_CODE = @IN_INPUT_MAN)
                    OR ADMIN_MANAGER = @IN_INPUT_MAN OR INPUT_MAN = @IN_INPUT_MAN OR SUB_MAN = @IN_INPUT_MAN OR SUB_MAN2 = @IN_INPUT_MAN OR ADMIN_MANAGER IN(SELECT OP_CODE FROM INTRUST..TOPCUSTRIGHT WHERE ENABLE_OP_CODE = @IN_INPUT_MAN) OR ISNULL(@IN_INPUT_MAN,0)=0 )
     IF @P_SELECT_FLAG = 0
     BEGIN
        --全选
        INSERT INTO #STAT_PRODUCT_DETAIL(PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,CURRENCY_ID,CONTRACT_BH,VALID_PERIOD,QS_DATE,START_DATE,
                    LINK_MAN,END_DATE,RG_MONEY,TO_MONEY,TO_AMOUNT,JK_TYPE_NAME,JK_DATE,BANK_NAME,BANK_ACCT,
                    INPUT_MAN,INPUT_TIME,INPUT_CHECK_MAN,ZJ_CHECK_MAN,HT_STATUS_NAME,SUMMARY,
                    CUST_NO, CUST_NAME, POST_ADDRESS, POST_CODE,CARD_TYPE_NAME,CARD_ID,AGE,
                    SEX_NAME,O_TEL,H_TEL,MOBILE,BP,FAX,E_MAIL,CUST_TYPE_NAME,
                    CUST_LEVEL_NAME,TOUCH_TYPE_NAME,CUST_SOURCE_NAME,DATA_TYPE,PERIOD_UNIT,SUB_PRODUCT_ID,
					EXPECT_ROR_LOWER,EXPECT_ROR_UPPER,PROV_FLAG,PROV_LEVEL)
        SELECT A.PRODUCT_ID,A.PRODUCT_CODE,D.PRODUCT_NAME,A.CURRENCY_ID,A.CONTRACT_SUB_BH,A.VALID_PERIOD,A.QS_DATE,A.START_DATE,
              A.LINK_MAN,A.END_DATE,A.RG_MONEY,A.TO_MONEY,A.TO_AMOUNT,A.JK_TYPE_NAME,A.JK_DATE,E.BANK_NAME+E.BANK_SUB_NAME,E.BANK_ACCT,
              A.INPUT_MAN,YEAR(A.INPUT_TIME)*10000 + MONTH(A.INPUT_TIME)*100 + DAY(A.INPUT_TIME) AS INPUT_TIME,
              A.CHECK_MAN,A.ZJ_CHECK_MAN,A.HT_STATUS_NAME,A.SUMMARY,
              C.CUST_NO, C.CUST_NAME, C.POST_ADDRESS, C.POST_CODE, C.CARD_TYPE_NAME, C.CARD_ID, C.AGE,
              C.SEX_NAME, C.O_TEL, C.H_TEL, C.MOBILE, C.BP, C.FAX, C.E_MAIL, C.CUST_TYPE_NAME,
              C.CUST_LEVEL_NAME, C.TOUCH_TYPE_NAME, C.CUST_SOURCE_NAME,1,D.PERIOD_UNIT,A.SUB_PRODUCT_ID,
			  A.EXPECT_ROR_LOWER,A.EXPECT_ROR_UPPER,A.PROV_FLAG,A.PROV_LEVEL
        FROM INTRUST..TCONTRACT A, INTRUST..TCUSTOMERINFO C,INTRUST..TPRODUCT D,INTRUST..TBENIFITOR E
        WHERE A.CUST_ID = C.CUST_ID AND A.BOOK_CODE = @P_BOOK_CODE AND A.PRODUCT_ID = D.PRODUCT_ID
             AND (@P_CUST_NO IS NULL OR @P_CUST_NO = '' OR @P_CUST_NO = C.CUST_NO)
             AND (C.CUST_TYPE = @P_CUST_TYPE OR @P_CUST_TYPE = 0 OR @P_CUST_TYPE IS NULL)
             AND ISNULL(A.RG_MONEY,0) >= ISNULL(@P_RG_MONEY,0) AND A.HT_STATUS <> '120104'
             AND(ISNULL(@V_SW20409_R,0) = 0 OR A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCTS))
			 AND A.CUST_ID = E.CUST_ID
			 AND A.CONTRACT_BH = E.CONTRACT_BH
			 AND A.PRODUCT_ID = E.PRODUCT_ID 
    END
    ELSE IF @P_SELECT_FLAG = 1
    BEGIN
       --单选
        INSERT INTO #STAT_PRODUCT_DETAIL(PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,CURRENCY_ID,CONTRACT_BH,VALID_PERIOD,QS_DATE,START_DATE,
                    LINK_MAN,END_DATE,RG_MONEY,TO_MONEY,TO_AMOUNT,JK_TYPE_NAME,JK_DATE,BANK_NAME,BANK_ACCT,
                    INPUT_MAN,INPUT_TIME,INPUT_CHECK_MAN,ZJ_CHECK_MAN,HT_STATUS_NAME,SUMMARY,
                    CUST_NO, CUST_NAME, POST_ADDRESS, POST_CODE,CARD_TYPE_NAME,CARD_ID,AGE,
                    SEX_NAME,O_TEL,H_TEL,MOBILE,BP,FAX,E_MAIL,CUST_TYPE_NAME,
                    CUST_LEVEL_NAME,TOUCH_TYPE_NAME,CUST_SOURCE_NAME,DATA_TYPE,PERIOD_UNIT,SUB_PRODUCT_ID,
					EXPECT_ROR_LOWER,EXPECT_ROR_UPPER,PROV_FLAG,PROV_LEVEL)
        SELECT A.PRODUCT_ID,A.PRODUCT_CODE,D.PRODUCT_NAME,A.CURRENCY_ID,A.CONTRACT_SUB_BH,A.VALID_PERIOD,A.QS_DATE,A.START_DATE,
              A.LINK_MAN,A.END_DATE,A.RG_MONEY,A.TO_MONEY,A.TO_AMOUNT,A.JK_TYPE_NAME,A.JK_DATE,E.BANK_NAME+E.BANK_SUB_NAME,E.BANK_ACCT,
              A.INPUT_MAN,YEAR(A.INPUT_TIME)*10000 + MONTH(A.INPUT_TIME)*100 + DAY(A.INPUT_TIME) AS INPUT_TIME,
              A.CHECK_MAN,A.ZJ_CHECK_MAN,A.HT_STATUS_NAME,A.SUMMARY,
              C.CUST_NO, C.CUST_NAME, C.POST_ADDRESS, C.POST_CODE, C.CARD_TYPE_NAME, C.CARD_ID, C.AGE,
              C.SEX_NAME, C.O_TEL, C.H_TEL, C.MOBILE, C.BP, C.FAX, C.E_MAIL, C.CUST_TYPE_NAME,
              C.CUST_LEVEL_NAME, C.TOUCH_TYPE_NAME, C.CUST_SOURCE_NAME,1,D.PERIOD_UNIT,A.SUB_PRODUCT_ID,
			  A.EXPECT_ROR_LOWER,A.EXPECT_ROR_UPPER,A.PROV_FLAG,A.PROV_LEVEL
        FROM INTRUST..TCONTRACT A, INTRUST..TCUSTOMERINFO C,INTRUST..TPRODUCT D,INTRUST..TBENIFITOR E
        WHERE A.CUST_ID = C.CUST_ID AND A.PRODUCT_ID = D.PRODUCT_ID AND
             A.BOOK_CODE = @P_BOOK_CODE AND (A.PRODUCT_CODE = @P_PRODUCT_CODE)
             AND (@P_CUST_NO IS NULL OR @P_CUST_NO = '' OR @P_CUST_NO = C.CUST_NO)
             AND (C.CUST_TYPE = @P_CUST_TYPE OR @P_CUST_TYPE = 0 OR @P_CUST_TYPE IS NULL)
             AND ISNULL(A.RG_MONEY,0) >= ISNULL(@P_RG_MONEY,0) AND A.HT_STATUS <> '120104'
             AND(ISNULL(@V_SW20409_R,0) = 0 OR A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCTS))
			 AND A.CUST_ID = E.CUST_ID
			 AND A.CONTRACT_BH = E.CONTRACT_BH
			 AND A.PRODUCT_ID = E.PRODUCT_ID 
    END
    ELSE
    BEGIN
       --多选
        INSERT INTO #STAT_PRODUCT_DETAIL(PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,CURRENCY_ID,CONTRACT_BH,VALID_PERIOD,QS_DATE,START_DATE,
                    LINK_MAN,END_DATE,RG_MONEY,TO_MONEY,TO_AMOUNT,JK_TYPE_NAME,JK_DATE,BANK_NAME,BANK_ACCT,
                    INPUT_MAN,INPUT_TIME,INPUT_CHECK_MAN,ZJ_CHECK_MAN,HT_STATUS_NAME,SUMMARY,
                    CUST_NO, CUST_NAME, POST_ADDRESS, POST_CODE,CARD_TYPE_NAME,CARD_ID,AGE,
                    SEX_NAME,O_TEL,H_TEL,MOBILE,BP,FAX,E_MAIL,CUST_TYPE_NAME,
                    CUST_LEVEL_NAME,TOUCH_TYPE_NAME,CUST_SOURCE_NAME,DATA_TYPE,PERIOD_UNIT,SUB_PRODUCT_ID,
					EXPECT_ROR_LOWER,EXPECT_ROR_UPPER,PROV_FLAG,PROV_LEVEL)
        SELECT A.PRODUCT_ID,A.PRODUCT_CODE,D.PRODUCT_NAME,A.CURRENCY_ID,A.CONTRACT_SUB_BH,A.VALID_PERIOD,A.QS_DATE,A.START_DATE,
              A.LINK_MAN,A.END_DATE,A.RG_MONEY,A.TO_MONEY,A.TO_AMOUNT,A.JK_TYPE_NAME,A.JK_DATE,E.BANK_NAME+E.BANK_SUB_NAME,E.BANK_ACCT,
              A.INPUT_MAN,YEAR(A.INPUT_TIME)*10000 + MONTH(A.INPUT_TIME)*100 + DAY(A.INPUT_TIME) AS INPUT_TIME,
              A.CHECK_MAN,A.ZJ_CHECK_MAN,A.HT_STATUS_NAME,A.SUMMARY,
              C.CUST_NO, C.CUST_NAME, C.POST_ADDRESS, C.POST_CODE, C.CARD_TYPE_NAME, C.CARD_ID, C.AGE,
              C.SEX_NAME, C.O_TEL, C.H_TEL, C.MOBILE, C.BP, C.FAX, C.E_MAIL, C.CUST_TYPE_NAME,
              C.CUST_LEVEL_NAME, C.TOUCH_TYPE_NAME, C.CUST_SOURCE_NAME,1,D.PERIOD_UNIT,A.SUB_PRODUCT_ID,
			  A.EXPECT_ROR_LOWER,A.EXPECT_ROR_UPPER,A.PROV_FLAG,A.PROV_LEVEL
        FROM INTRUST..TCONTRACT A, INTRUST..TCUSTOMERINFO C,INTRUST..TPRODUCT D,INTRUST..TBENIFITOR E
        WHERE A.CUST_ID = C.CUST_ID AND A.PRODUCT_ID = D.PRODUCT_ID AND
             A.BOOK_CODE = @P_BOOK_CODE AND D.SL_FLAG = 1
             AND (C.CUST_NO = @P_CUST_NO OR @P_CUST_NO IS NULL OR @P_CUST_NO = '')
             AND (C.CUST_TYPE = @P_CUST_TYPE OR @P_CUST_TYPE = 0 OR @P_CUST_TYPE IS NULL)
             AND ISNULL(A.RG_MONEY,0) >= ISNULL(@P_RG_MONEY,0) AND A.HT_STATUS <> '120104'
             AND(ISNULL(@V_SW20409_R,0) = 0 OR A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCTS))
			 AND A.CUST_ID = E.CUST_ID
			 AND A.CONTRACT_BH = E.CONTRACT_BH
			 AND A.PRODUCT_ID = E.PRODUCT_ID 
    END
END
ELSE
BEGIN
        --2 产品单元模式
        DECLARE @V_CELLALL TABLE(CELL_ID      INT,
                           CELL_CODE    VARCHAR(10),
                           CELL_NAME    VARCHAR(100),
                           CELL_TYPE    INT,
                           PRODUCT_ID   INT,
                           PRODUCT_CODE VARCHAR(6),
                           PRODUCT_NAME VARCHAR(100))

        INSERT INTO @V_CELLALL(CELL_ID,CELL_CODE,CELL_NAME,PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME)
        SELECT SERIAL_NO,CELL_CODE,CELL_NAME,PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME FROM INTRUST..TPRODUCT_CELL
        WHERE SERIAL_NO = @P_CELL_ID


        WHILE @@ROWCOUNT > 0
            INSERT INTO @V_CELLALL(CELL_ID)
            SELECT A.SUB_CELL_ID
            FROM  INTRUST..TPRODUCT_CELL_DETAIL A, @V_CELLALL B
            WHERE A.DF_SERIAL_NO = B.CELL_ID AND A.SUB_CELL_ID NOT IN(SELECT CELL_ID FROM @V_CELLALL)

        UPDATE @V_CELLALL
        SET CELL_CODE = B.CELL_CODE,
            CELL_NAME = B.CELL_NAME,
            CELL_TYPE = B.CELL_TYPE,
            PRODUCT_ID = B.PRODUCT_ID,
            PRODUCT_CODE = B.PRODUCT_CODE,
            PRODUCT_NAME = B.PRODUCT_NAME
        FROM @V_CELLALL A , INTRUST..TPRODUCT_CELL B
        WHERE A.CELL_ID = B.SERIAL_NO

        INSERT INTO @V_PRODUCTS
        SELECT PRODUCT_ID FROM @V_CELLALL WHERE CELL_TYPE = 1 GROUP BY PRODUCT_ID

        --多选
        INSERT INTO #STAT_PRODUCT_DETAIL(PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,CURRENCY_ID,CONTRACT_BH,VALID_PERIOD,QS_DATE,START_DATE,
                    LINK_MAN,END_DATE,RG_MONEY,TO_MONEY,TO_AMOUNT,JK_TYPE_NAME,JK_DATE,BANK_NAME,BANK_ACCT,
                    INPUT_MAN,INPUT_TIME,INPUT_CHECK_MAN,ZJ_CHECK_MAN,HT_STATUS_NAME,SUMMARY,
                    CUST_NO, CUST_NAME, POST_ADDRESS, POST_CODE,CARD_TYPE_NAME,CARD_ID,AGE,
                    SEX_NAME,O_TEL,H_TEL,MOBILE,BP,FAX,E_MAIL,CUST_TYPE_NAME,
                    CUST_LEVEL_NAME,TOUCH_TYPE_NAME,CUST_SOURCE_NAME,DATA_TYPE,PERIOD_UNIT,SUB_PRODUCT_ID,
					EXPECT_ROR_LOWER,EXPECT_ROR_UPPER,PROV_FLAG,PROV_LEVEL)
        SELECT A.PRODUCT_ID,A.PRODUCT_CODE,D.PRODUCT_NAME,A.CURRENCY_ID,A.CONTRACT_SUB_BH,A.VALID_PERIOD,A.QS_DATE,A.START_DATE,
              A.LINK_MAN,A.END_DATE,A.RG_MONEY,A.TO_MONEY,A.TO_AMOUNT,A.JK_TYPE_NAME,A.JK_DATE,E.BANK_NAME+E.BANK_SUB_NAME,E.BANK_ACCT,
              A.INPUT_MAN,YEAR(A.INPUT_TIME)*10000 + MONTH(A.INPUT_TIME)*100 + DAY(A.INPUT_TIME) AS INPUT_TIME,
              A.CHECK_MAN,A.ZJ_CHECK_MAN,A.HT_STATUS_NAME,A.SUMMARY,
              C.CUST_NO, C.CUST_NAME, C.POST_ADDRESS, C.POST_CODE, C.CARD_TYPE_NAME, C.CARD_ID, C.AGE,
              C.SEX_NAME, C.O_TEL, C.H_TEL, C.MOBILE, C.BP, C.FAX, C.E_MAIL, C.CUST_TYPE_NAME,
              C.CUST_LEVEL_NAME, C.TOUCH_TYPE_NAME, C.CUST_SOURCE_NAME,1,D.PERIOD_UNIT,A.SUB_PRODUCT_ID,
			  A.EXPECT_ROR_LOWER,A.EXPECT_ROR_UPPER,A.PROV_FLAG,A.PROV_LEVEL
        FROM INTRUST..TCONTRACT A, INTRUST..TCUSTOMERINFO C,INTRUST..TPRODUCT D,@V_PRODUCTS B,INTRUST..TBENIFITOR E
        WHERE A.CUST_ID = C.CUST_ID AND A.PRODUCT_ID = D.PRODUCT_ID AND B.PRODUCT_ID = D.PRODUCT_ID
             AND A.BOOK_CODE = @P_BOOK_CODE
             AND (C.CUST_NO = @P_CUST_NO OR @P_CUST_NO IS NULL OR @P_CUST_NO = '')
             AND (C.CUST_TYPE = @P_CUST_TYPE OR @P_CUST_TYPE = 0 OR @P_CUST_TYPE IS NULL)
             AND ISNULL(A.RG_MONEY,0) >= ISNULL(@P_RG_MONEY,0) AND A.HT_STATUS <> '120104'
			 AND A.CUST_ID = E.CUST_ID
			 AND A.CONTRACT_BH = E.CONTRACT_BH
			 AND A.PRODUCT_ID = E.PRODUCT_ID 
END

    UPDATE #STAT_PRODUCT_DETAIL
        SET LINK_MAN_NAME = B.OP_NAME,DEPART_ID = B.DEPART_ID
    FROM #STAT_PRODUCT_DETAIL A,TOPERATOR B
    WHERE A.LINK_MAN = B.OP_CODE
    UPDATE #STAT_PRODUCT_DETAIL
        SET DEPART_NAME = B.DEPART_NAME
    FROM #STAT_PRODUCT_DETAIL A,TDEPARTMENT B
    WHERE A.DEPART_ID = B.DEPART_ID
    UPDATE #STAT_PRODUCT_DETAIL
        SET INPUT_MAN_NAME = B.OP_NAME
    FROM #STAT_PRODUCT_DETAIL A,TOPERATOR B
    WHERE A.INPUT_MAN = B.OP_CODE
    UPDATE #STAT_PRODUCT_DETAIL
        SET ZJ_CHECK_MAN_NAME = B.OP_NAME
    FROM #STAT_PRODUCT_DETAIL A,TOPERATOR B
    WHERE A.ZJ_CHECK_MAN = B.OP_CODE

    UPDATE #STAT_PRODUCT_DETAIL SET PERIOD_STR = '无期限' WHERE PERIOD_UNIT = 0
    UPDATE #STAT_PRODUCT_DETAIL SET PERIOD_STR = RTRIM(CONVERT(CHAR(8),VALID_PERIOD))+'天' WHERE PERIOD_UNIT = 1
    UPDATE #STAT_PRODUCT_DETAIL SET PERIOD_STR = RTRIM(CONVERT(CHAR(8),VALID_PERIOD))+'月' WHERE PERIOD_UNIT = 2
    INSERT INTO #STAT_PRODUCT_DETAIL(PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,CONTRACT_BH,RG_MONEY,TO_MONEY,TO_AMOUNT,DATA_TYPE)
        SELECT PRODUCT_ID,PRODUCT_CODE,'小计',RTRIM(CONVERT(CHAR(16),COUNT(*)))+'份',SUM(ISNULL(RG_MONEY,0)),SUM(ISNULL(TO_MONEY,0)),SUM(ISNULL(TO_AMOUNT,0)), 2
            FROM #STAT_PRODUCT_DETAIL GROUP BY PRODUCT_ID,PRODUCT_CODE

    SELECT A.PRODUCT_CODE,A.PRODUCT_NAME,B.LIST_NAME,A.CONTRACT_BH,A.PERIOD_STR,A.QS_DATE,A.START_DATE,A.END_DATE,
              A.LINK_MAN_NAME,A.RG_MONEY,A.TO_MONEY,A.TO_AMOUNT,A.JK_TYPE_NAME,A.JK_DATE,A.BANK_NAME,
              A.BANK_ACCT,A.INPUT_MAN_NAME,A.INPUT_TIME,A.INPUT_CHECK_MAN_NAME,
              A.ZJ_CHECK_MAN_NAME,A.HT_STATUS_NAME,A.SUMMARY,
              A.CUST_NO,A.CUST_NAME,A.POST_ADDRESS,A.POST_CODE,A.CARD_TYPE_NAME,A.CARD_ID,AGE,
              A.SEX_NAME,A.O_TEL,A.H_TEL,MOBILE,A.BP,A.FAX,E_MAIL,A.CUST_TYPE_NAME,
              A.CUST_LEVEL_NAME,A.TOUCH_TYPE_NAME,A.CUST_SOURCE_NAME,A.DEPART_NAME,
			  A.EXPECT_ROR_LOWER,A.EXPECT_ROR_UPPER,C.TYPE_CONTENT,E.CONTENT
          FROM #STAT_PRODUCT_DETAIL A 
			LEFT JOIN INTRUST..TSUBPRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID AND A.SUB_PRODUCT_ID = B.SUB_PRODUCT_ID
			LEFT JOIN INTRUST..TDICTPARAM C ON A.PROV_LEVEL = C.TYPE_VALUE AND C.TYPE_ID = 1204
			LEFT JOIN INTRUST..TINTEGERPARAM E ON A.PROV_LEVEL = E.TYPE_VALUE AND E.TYPE_ID = 3003
		  ORDER BY A.PRODUCT_CODE,A.DATA_TYPE,A.CONTRACT_BH
    RETURN @@ROWCOUNT
GO
