USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TATTACHMENTTYPE @IN_ATTACHMENT_TYPE_ID    INT,
                                          @IN_ATTACHMENT_TYPE_NAME  NVARCHAR(30) = NULL,    --附件类别名称
                                          @IN_DF_TABLE_ID           NVARCHAR(60) = NULL,    --对应表名
                                          @IN_INPUT_MAN             INT = NULL
WITH ENCRYPTION
AS
    IF (@IN_ATTACHMENT_TYPE_ID = 0)
    BEGIN
        SELECT * FROM TATTACHMENTTYPE
            WHERE (ATTACHMENT_TYPE_NAME LIKE '%'+@IN_ATTACHMENT_TYPE_NAME+'%' OR ISNULL(@IN_ATTACHMENT_TYPE_NAME,'') ='')
            AND ((DF_TABLE_ID = @IN_DF_TABLE_ID) OR (@IN_DF_TABLE_ID = 0) OR (@IN_DF_TABLE_ID IS NULL))
    END
    ELSE
    BEGIN
        SELECT * FROM TATTACHMENTTYPE WHERE ATTACHMENT_TYPE_ID = @IN_ATTACHMENT_TYPE_ID
            --@IN_ATTACHMENT_TYPE_ID = 0
    END

    RETURN 100
GO
