USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_DEL_TDIRECTSENDDETAIL @IN_SERIAL_NO  INTEGER,               --TDIRECTSENDTOTAL.SERIAL_NO
										  @IN_INPUT_MAN      INT

WITH ENCRYPTION
AS

    DECLARE @V_RET_CODE INT, @IBUSI_FLAG INT
    DECLARE @SBUSI_NAME VARCHAR(40), @SSUMMARY VARCHAR(200)
    DECLARE @V_WAY_TYPE        INTEGER            --1:sms; 2:mail;
    DECLARE @V_CONTENT_TEMPLET NVARCHAR(MAX)      --发送内容，如果通过客户取手机号/邮箱，可以使用%1代表客户名称；自填则不能使用%1
    DECLARE @V_CUST_NAME   NVARCHAR(60)           --客户名称
    DECLARE @V_SMS_SERIAL_NO   INT     --信息表SERIAL_NO
    DECLARE @V_CUST_ID         INT

    SELECT @V_RET_CODE = -23001000, @IBUSI_FLAG = 23001
    SET @SBUSI_NAME = '删除短信息发送人'
    SET @SSUMMARY = '删除短信息发送人'
    
    SELECT @V_SMS_SERIAL_NO = SEND_SERIAL_NO,@V_CUST_ID =CUST_ID FROM TDIRECTSENDDETAIL WHERE SERIAL_NO =@IN_SERIAL_NO
    SELECT @V_WAY_TYPE = WAY_TYPE,@V_CONTENT_TEMPLET = CONTENT_TEMPLET FROM TDIRECTSENDTOTAL WHERE SERIAL_NO = @V_SMS_SERIAL_NO
    SELECT @V_CUST_NAME =CUST_NAME FROM TCustomers WHERE CUST_ID = @V_CUST_ID

    BEGIN TRANSACTION
    
    DELETE FROM TDIRECTSENDDETAIL WHERE SERIAL_NO =@IN_SERIAL_NO
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    --
    IF @V_WAY_TYPE =1 --短信
    BEGIN
        SET @SBUSI_NAME = '删除短信息发送人'
        SET @SSUMMARY = '删除短信息发送人，主题：' + RTRIM(@V_CONTENT_TEMPLET) + '，发送人：'+ ISNULL(@V_CUST_NAME,'')
    END
    ELSE
    BEGIN
        SET @SBUSI_NAME = '删除邮件信息发送人'
        SET @SSUMMARY = '删除邮件信息发送人，主题：' + RTRIM(@V_CONTENT_TEMPLET) + '，发送人：'+ ISNULL(@V_CUST_NAME,'')
    END
    
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
