USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_COUNT_TFAQS @IN_SERIAL_NO  INT,  --序号
                                @IN_FLAG       INT,  --1支持 2反对
                                @IN_INPUT_MAN  INT   --操作员
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    DECLARE @V_RET_CODE INT, @IBUSI_FLAG INT, @SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)
    SELECT @V_RET_CODE = -19003000, @IBUSI_FLAG = 19003
    SELECT @SBUSI_NAME = N'知识库计数', @SSUMMARY = N'知识库计数'

    BEGIN TRANSACTION

    IF @IN_FLAG = 1
    BEGIN
        UPDATE TFAQS SET SUPPORT_TIMES = ISNULL(SUPPORT_TIMES,0) + 1 WHERE SERIAL_NO = @IN_SERIAL_NO
    END
    ELSE
    BEGIN
        UPDATE TFAQS SET OPPOSE_TIMES = ISNULL(OPPOSE_TIMES,0) + 1 WHERE SERIAL_NO = @IN_SERIAL_NO
    END
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SELECT @SSUMMARY = N'知识库计数'
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
