USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_CREATE_MONEYTASKREMIND @IN_INPUT_MAN        INT,        --录入人员，对应表TOPERATOR.OP_CODE
                                           @IN_COCONTRACT_ID    INT = NULL, --主合同ID，对应TCOCONTRACT.COCONTRACT_ID
                                           @IN_MAINTAIN_ID      INT = NULL  --维护合同(维护费)ID，对应TCOCONTRACTMAINTAIN.MAINTAIN_ID
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    SELECT @SBUSI_NAME = N'合同管理之生成收款计划提醒'
    SELECT @SSUMMARY = N'合同管理之生成收款计划提醒'
    SELECT @IBUSI_FLAG = 50001
    SELECT @V_RET_CODE = -50001000

    DECLARE @V_VALUE INT,@V_REMIND_DATE INT,@V_TODAY_DATE INT,@V_LAST_DATE INT,@V_MAX_ID INT
    SELECT @V_VALUE = VALUE FROM TSYSCONTROL WHERE FLAG_TYPE ='MONEYTASK'
    SELECT @V_TODAY_DATE = CONVERT(INT,CONVERT(CHAR(8),GETDATE(),112))   --取当前日期
    SELECT @V_REMIND_DATE = dbo.GETDAY(@V_TODAY_DATE,@V_VALUE)
    SELECT @V_MAX_ID = MAX(SERIAL_NO) FROM TMONEYTASKINFO  --用于保证TMONEYTASKLIST添加记录时只添加TMONEYTASKINFO的最新记录
    SELECT @V_MAX_ID = ISNULL(@V_MAX_ID,0)
    BEGIN TRANSACTION
        --生成合同收款计划提醒
        INSERT INTO TMONEYTASKINFO(RECORD_ID,TASK_TYPE,TITLE,INFO_STR,MENU_ID,INPUT_MAN)
            SELECT PAYPLAN_ID,1, PAY_NUM_NAME,PAY_SUMMARY,'70402',INPUT_MAN FROM TCOCONTRACTPAYPLAN
                WHERE (EXP_DATE<@V_REMIND_DATE)
                    AND ARRIVEMONEY_FLAG <> 3
                    AND PAYPLAN_ID NOT IN (SELECT RECORD_ID FROM TMONEYTASKINFO)

        INSERT INTO TMONEYTASKLIST(REC_NO,OP_CODE,OP_NAME,READ_FLAG)
            SELECT A.SERIAL_NO, B.INPUT_MAN, C.OP_NAME, 1
                FROM TMONEYTASKINFO A, TCOCONTRACTPAYPLAN B, TOPERATOR C
                    WHERE A.RECORD_ID = B.PAYPLAN_ID AND B.INPUT_MAN = C.OP_CODE AND A.SERIAL_NO>@V_MAX_ID
        ----生成维护合同收款计划提醒
        INSERT INTO TMONEYTASKINFO(RECORD_ID,TASK_TYPE,TITLE,INFO_STR,MENU_ID,INPUT_MAN)
            SELECT MAINTAIN_ID,2, MAIN_PRO_NAME,MAIN_SUMMARY,'70403',INPUT_MAN FROM TCOCONTRACTMAINTAIN
                WHERE COLLECT_TIME<@V_REMIND_DATE
                    AND ARRIVEMONEY_FLAG <>3
                    AND MAINTAIN_ID NOT IN (SELECT RECORD_ID FROM TMONEYTASKINFO)

        INSERT INTO TMONEYTASKLIST(REC_NO,OP_CODE,OP_NAME,READ_FLAG)
            SELECT A.SERIAL_NO, B.INPUT_MAN, C.OP_NAME, 1
                FROM TMONEYTASKINFO A, TCOCONTRACTMAINTAIN B, TOPERATOR C
                    WHERE A.RECORD_ID = B.MAINTAIN_ID AND B.INPUT_MAN = C.OP_CODE AND A.SERIAL_NO>@V_MAX_ID

    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SELECT @SSUMMARY = N'合同管理之生成收款计划提醒'
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,'000000',@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
