USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_DEL_TQUOTIENTCHANGE @IN_SERIAL_NO     INT,    --主键
                                        @IN_INPUT_MAN     INT     --录入操作员

WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    SELECT @SBUSI_NAME = N'删除非信托产品份额信息'
    SELECT @SSUMMARY = N'删除非信托产品份额信息'
    SELECT @IBUSI_FLAG = 39011
    SELECT @V_RET_CODE = -39011000

    IF NOT EXISTS(SELECT * FROM TQUOTIENTCHANGE WHERE SERIAL_NO = @IN_SERIAL_NO)
        RETURN @V_RET_CODE - 11   --非信托产品份额信息不存在

    BEGIN TRANSACTION

    DELETE FROM TQUOTIENTCHANGE WHERE SERIAL_NO = @IN_SERIAL_NO
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SELECT @SSUMMARY = N'删除非信托产品份额信息：'+RTRIM(CONVERT(NVARCHAR(16),@IN_SERIAL_NO))
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    COMMIT TRANSACTION
    RETURN 100
GO
