USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TCUSTADDRESS @IN_CUST_ID               INTEGER,        --客户ID
                                   @IN_INPUT_MAN                 INTEGER         --操作员
WITH ENCRYPTION 
AS
    IF NOT EXISTS (SELECT * FROM TCUSTADDRESS WHERE CUST_ID=@IN_CUST_ID)
    BEGIN
		SELECT @IN_CUST_ID CUST_ID,1 LIST_ID,1 DEFAULT_FLAG,NULL PROVINCE,NULL CITY,NULL DISTRICT,POST_ADDRESS TOWN_DETAIL
				,POST_CODE,NULL CONTACT_MAN,MOBILE TEL,FAX,NULL PROVINCE_NAME,NULL CITY_NAME,NULL DISTRICT_NAME
			FROM TCustomers WHERE CUST_ID=@IN_CUST_ID
		UNION ALL
		SELECT @IN_CUST_ID CUST_ID,2 LIST_ID,0 DEFAULT_FLAG,NULL PROVINCE,NULL CITY,NULL DISTRICT,POST_ADDRESS2 TOWN_DETAIL
				,POST_CODE2,NULL CONTACT_MAN,MOBILE TEL,FAX,NULL PROVINCE_NAME,NULL CITY_NAME,NULL DISTRICT_NAME
			FROM TCustomers WHERE CUST_ID=@IN_CUST_ID
		RETURN
    END
    SELECT A.*,B.TYPE_CONTENT PROVINCE_NAME,C.TYPE_CONTENT CITY_NAME,D.TYPE_CONTENT DISTRICT_NAME
		FROM TCUSTADDRESS A LEFT JOIN TDICTPARAM B ON B.TYPE_ID='9999' AND A.PROVINCE=B.TYPE_VALUE
			LEFT JOIN TDICTPARAM C ON C.TYPE_ID='9999' AND A.CITY=C.TYPE_VALUE
			LEFT JOIN TDICTPARAM D ON D.TYPE_ID='9999' AND A.DISTRICT=D.TYPE_VALUE
		WHERE CUST_ID=@IN_CUST_ID
        ORDER BY A.LIST_ID
        
GO
