USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TCUSTOMER_SOURCE   @IN_BEGIN_DATE  INT =0,
                                             @IN_SCOPE      INT =0,   --统计范围:0全部，1本人；2本部门
                                             @IN_INPUT_MAN  INT = NULL 
WITH ENCRYPTION
AS
    DECLARE @V_OPCODES TABLE(OP_CODE INT)
    IF @IN_SCOPE=2 --保存下本部门的客户经理列表
		INSERT INTO @V_OPCODES
			SELECT OP_CODE FROM TOPERATOR WHERE DEPART_ID=(SELECT DEPART_ID FROM TOPERATOR WHERE OP_CODE=@IN_INPUT_MAN)
    CREATE TABLE #TEMP_TABLE5
    (
        CUST_SOURCE_NAME    NVARCHAR(100),
        CUST_SOURCE         NVARCHAR(100),
        TOTAL               INT,
        RG_MONEY            DECIMAL(16,3),
        NUMBER_RATE         DECIMAL(16,4),
        RG_RATE             DECIMAL(16,4)
    )

    DECLARE @V_NUMBER_TOTAL DECIMAL(16,4),@V_RG_TOTAL DECIMAL(16,4)

    IF ISNULL(@IN_BEGIN_DATE,0)=0
        SET @IN_BEGIN_DATE = dbo.GETDATEINT(GETDATE())

    BEGIN
        INSERT INTO #TEMP_TABLE5(CUST_SOURCE_NAME,CUST_SOURCE,TOTAL,RG_MONEY)
            SELECT A.CUST_SOURCE_NAME,A.CUST_SOURCE,COUNT(DISTINCT A.CUST_ID),SUM(B.RG_MONEY)
                FROM TCUSTOMERS A LEFT JOIN INTRUST..TCONTRACT B ON A.CUST_ID = B.CUST_ID
                WHERE dbo.GETDATEINT(A.INPUT_TIME) <= @IN_BEGIN_DATE
				    AND (@IN_SCOPE=0 --全部
                        OR @IN_SCOPE=1 AND A.SERVICE_MAN=@IN_INPUT_MAN --本人
                        OR @IN_SCOPE=2 AND EXISTS(SELECT * FROM @V_OPCODES WHERE OP_CODE=A.SERVICE_MAN)--本部门
                        )
                GROUP BY A.CUST_SOURCE_NAME , A.CUST_SOURCE
    END

    SET @V_NUMBER_TOTAL = (SELECT SUM(TOTAL) FROM #TEMP_TABLE5)
    SET @V_RG_TOTAL    = (SELECT SUM(RG_MONEY) FROM #TEMP_TABLE5)

    BEGIN
        UPDATE #TEMP_TABLE5 SET NUMBER_RATE = TOTAL/@V_NUMBER_TOTAL,
                               RG_RATE = RG_MONEY/@V_RG_TOTAL
    END

    SELECT * FROM #TEMP_TABLE5
GO
