USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_DEL_TCOCONTRACTPAYPLAN @IN_PAYPLAN_ID               INT,                   --付款计划ID
                                           @IN_INPUT_MAN                INT,                   --录入人员，对应表TOPERATOR.OP_CODE
                                           @IN_COCONTRACT_ID            INT                    --合同ID
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    DECLARE @V_COCONTRACT_SUB_BH NVARCHAR(200),@V_COCONTRACT_ID INT,@V_PAY_NUM_NAME NVARCHAR(60)

    SELECT @SBUSI_NAME = N'合同管理之删除付款计划'
    SELECT @SSUMMARY = N'合同管理之删除付款计划'
    SELECT @IBUSI_FLAG = 50001
    SELECT @V_RET_CODE = -50001000

    IF EXISTS(SELECT 1 FROM TCOCONTRACTMONEYMX WHERE PAYPLAN_ID = @IN_PAYPLAN_ID)
        RETURN @V_RET_CODE -2   --已还款记录，不允许删除
    IF NOT EXISTS(SELECT 1 FROM TCOCONTRACTPAYPLAN WHERE COCONTRACT_ID = @IN_COCONTRACT_ID)
        RETURN 100
    IF ISNULL(@IN_PAYPLAN_ID,0) = 0 AND ISNULL(@IN_COCONTRACT_ID,0) = 0
        RETURN 100

    SELECT @V_COCONTRACT_ID =COCONTRACT_ID,@V_PAY_NUM_NAME =PAY_NUM_NAME FROM TCOCONTRACTPAYPLAN WHERE PAYPLAN_ID =@IN_PAYPLAN_ID
    SELECT @V_COCONTRACT_SUB_BH = COCONTRACT_SUB_BH FROM TCOCONTRACT WHERE COCONTRACT_ID =@V_COCONTRACT_ID

    BEGIN TRANSACTION

    DELETE FROM TCOCONTRACTPAYPLAN
        WHERE (PAYPLAN_ID = @IN_PAYPLAN_ID OR ISNULL(@IN_PAYPLAN_ID,0) = 0) AND (COCONTRACT_ID = @IN_COCONTRACT_ID)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    --
    SELECT @SSUMMARY = N'合同管理之删除付款计划，合同编号：'+@V_COCONTRACT_SUB_BH+'，合同期数说明：'+@V_PAY_NUM_NAME
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
