USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_ADD_TROLERIGHT_ALL  @IN_ROLE_ID INT,
                                        @IN_MENU_ID NVARCHAR (10),
                                        @IN_MENU_NAME NVARCHAR(60),
                                        @IN_FLAG INT,
                                        @IN_INPUT_MAN INT,
                                        @OUT_RET_CODE INT OUTPUT
WITH ENCRYPTION
AS
    DECLARE @IBUSI_FLAG INT
    DECLARE @SBUSI_NAME NVARCHAR(40)
    DECLARE @SSUMMARY NVARCHAR(200)
    SELECT @IBUSI_FLAG = 10701
    SELECT @SBUSI_NAME = N'增加角色权限'
    SELECT @SSUMMARY = N'增加角色权限'

    SELECT @OUT_RET_CODE = 100

    BEGIN TRANSACTION

    DELETE FROM TROLERIGHT
        WHERE ROLE_ID = @IN_ROLE_ID
            AND (MENU_ID LIKE @IN_MENU_ID + '%' OR @IN_MENU_ID IS NULL OR @IN_MENU_ID = N'')
            AND (MENU_ID IN (SELECT MENU_ID FROM TMENUINFO
                WHERE MENU_NAME LIKE '%'+@IN_MENU_NAME+'%' OR @IN_MENU_NAME IS NULL OR @IN_MENU_NAME = N''))
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    IF @IN_FLAG = 1
    BEGIN
        INSERT INTO TROLERIGHT(ROLE_ID,MENU_ID,FUNC_ID)
            SELECT @IN_ROLE_ID,MENU_ID,FUNC_ID
                FROM TFUNCTYPE
                WHERE (MENU_ID LIKE @IN_MENU_ID + '%' OR @IN_MENU_ID IS NULL OR @IN_MENU_ID = N'')
                    AND (MENU_ID IN (SELECT MENU_ID FROM TMENUINFO
                        WHERE MENU_NAME LIKE '%'+@IN_MENU_NAME+'%' OR @IN_MENU_NAME IS NULL OR @IN_MENU_NAME = N''))
                    AND(MENU_ID <> '20409')
        IF @@ERROR <> 0
        BEGIN
            ROLLBACK TRANSACTION
            RETURN -100
        END

    END

    SELECT @SSUMMARY = N'增加角色权限，角色编号：' + CONVERT(NVARCHAR(16),@IN_ROLE_ID)
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
