USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TMENUINFO @IN_MENU_ID NVARCHAR(10),
                                    @IN_PARENT_ID NVARCHAR(10)
WITH ENCRYPTION
AS
    SELECT * FROM TMENUINFO
        WHERE ((MENU_ID LIKE @IN_MENU_ID+'%') OR (@IN_MENU_ID = N'') OR (@IN_MENU_ID IS NULL))
            AND ((PARENT_ID = @IN_PARENT_ID) OR (@IN_PARENT_ID = N'') OR (@IN_PARENT_ID IS NULL))
        ORDER BY MENU_ID
GO
