USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_STAT_PRODUCTCOMMISSION @IN_PRODUCT_CODE NVARCHAR(6),   --产品编号
                                           @IN_INPUT_MAN    INT            --操作员
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    SELECT A.PRODUCT_ID,A.PRODUCT_NAME,LINK_MAN,B.OP_NAME, ISNULL(T.TEAM_NAME,'无') AS TEAM_NAME,SUM(RG_MONEY) AS RG_MONEY, 
           P.COMMISSION_RATE, SUM(RG_MONEY)*P.COMMISSION_RATE AS COMMISSION
    FROM INTRUST..TCONTRACT A LEFT JOIN TOPERATOR B ON A.LINK_MAN = B.OP_CODE
         LEFT JOIN (SELECT T.LEADER, B.MANAGERID, T.TEAM_NAME FROM TManagerTeams T, TManagerTeamMembers B WHERE T.TEAM_ID = B.TEAM_ID) T ON (A.LINK_MAN = T.LEADER OR A.LINK_MAN = T.MANAGERID)
         LEFT JOIN TPRODUCT P ON A.PRODUCT_ID = P.PRODUCT_ID
    WHERE A.PRODUCT_CODE = @IN_PRODUCT_CODE
    GROUP BY A.PRODUCT_ID,A.PRODUCT_NAME,LINK_MAN,B.OP_NAME, T.TEAM_NAME, P.COMMISSION_RATE
GO
