USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TDICTPARAM_LIST
WITH ENCRYPTION
AS
    SELECT TYPE_ID,TYPE_NAME FROM TDICTPARAM GROUP BY TYPE_ID,TYPE_NAME ORDER BY TYPE_ID
GO
