USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TSYSTEMCONDITION @IN_OPERAND_V_ID  INT,                  --主键
                                           @IN_INPUT_MAN     INT                   --操作员
WITH ENCRYPTION
AS
    BEGIN
          SELECT A.*,B.TABLE_NAME, B.FIELD_NAME
          FROM TSYSTEMCONDITION A LEFT JOIN TDATASOURCE B ON(B.FIELD_NAME_CN = A.SOURCE_FIELD AND  B.TABLE_NAME_CN = A.SOURCE_TABLE)
            WHERE  (A.OPERAND_V_ID = @IN_OPERAND_V_ID OR ISNULL(@IN_OPERAND_V_ID,'') = N'')
    END
    RETURN 100
GO
