USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE dbo.SP_QUERY_TCUSTOMERSCONNECTION @IN_SERIAL_NO      INT,            --序号
						  @IN_CUST_ID  INT,            --客户ID
						  @IN_FLAG_CHECK  INT,         --是否有审核权限
						  @IN_STATUS  INT,             --信息审核状态
						  @IN_INPUT_MAN      INT       --操作员
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    IF @IN_SERIAL_NO IS NULL SET @IN_SERIAL_NO = 0
    IF @IN_CUST_ID IS NULL SET @IN_CUST_ID = 0

    --IF ISNULL(@IN_SL_DATE,0) = 0 SET @IN_SL_DATE = 299991231
	DECLARE @V_IS_FLAG INT,@V_TEAM_ID INT
	SELECT @V_TEAM_ID = TEAM_ID FROM TManagerTeamMembers WHERE MANAGERID = @IN_INPUT_MAN
    SELECT @V_IS_FLAG = 0
	
	
	IF ISNULL(@IN_CUST_ID,0) <> 0 and ISNULL(@IN_SERIAL_NO ,0)=0
		BEGIN
			IF @IN_FLAG_CHECK = 0 --只能看自己添加的
			BEGIN
				SELECT A.[SERIAL_NO],A.[CUST_ID],A.[INPUT_MAN],A.[INPUT_TIME],A.[STATUS],A.[STATUS_NAME],A.[CHECKER]
				,A.[CHECK_TIME],A.[RE_CHECKER],A.[RE_CHECK_TIME],A.[O_CUST_TEL],A.[N_CUST_TEL],A.[O_MOBILE]
				,A.[N_MOBILE],A.[O_O_TEL],A.[N_O_TEL],A.[O_H_TEL],A.[N_H_TEL],A.[O_BP],A.[N_BP],A.APPLY_REASON
				,A.CHECK_REASON,A.RE_CHECK_REASON
				,B.CUST_NAME
				FROM TCUSTOMOERS_CONNECTION_MODI A 
				LEFT JOIN TCustomers B ON  A.CUST_ID = B.CUST_ID 
				WHERE (A.CUST_ID = @IN_CUST_ID OR @IN_CUST_ID = 0)
				AND A.INPUT_MAN = @IN_INPUT_MAN
				ORDER BY A.INPUT_TIME DESC
			END
			ELSE
			BEGIN
				SELECT A.[SERIAL_NO],A.[CUST_ID],A.[INPUT_MAN],A.[INPUT_TIME],A.[STATUS],A.[STATUS_NAME],A.[CHECKER]
				,A.[CHECK_TIME],A.[RE_CHECKER],A.[RE_CHECK_TIME],A.[O_CUST_TEL],A.[N_CUST_TEL],A.[O_MOBILE]
				,A.[N_MOBILE],A.[O_O_TEL],A.[N_O_TEL],A.[O_H_TEL],A.[N_H_TEL],A.[O_BP],A.[N_BP],A.APPLY_REASON
				,A.CHECK_REASON,A.RE_CHECK_REASON
				,B.CUST_NAME
				FROM TCUSTOMOERS_CONNECTION_MODI A 
				LEFT JOIN TCustomers B ON  A.CUST_ID = B.CUST_ID 
				WHERE (A.CUST_ID = @IN_CUST_ID OR @IN_CUST_ID = 0)
				ORDER BY A.INPUT_TIME DESC
			END
		END 
		ELSE 
		BEGIN
			SELECT A.[SERIAL_NO],A.[CUST_ID],A.[INPUT_MAN],A.[INPUT_TIME],A.[STATUS],A.[STATUS_NAME],A.[CHECKER]
			,A.[CHECK_TIME],A.[RE_CHECKER],A.[RE_CHECK_TIME],A.[O_CUST_TEL],A.[N_CUST_TEL],A.[O_MOBILE]
			,A.[N_MOBILE],A.[O_O_TEL],A.[N_O_TEL],A.[O_H_TEL],A.[N_H_TEL],A.[O_BP],A.[N_BP],A.APPLY_REASON
			,A.CHECK_REASON,A.RE_CHECK_REASON
			,B.CUST_NAME
			FROM TCUSTOMOERS_CONNECTION_MODI A 
			LEFT JOIN TCustomers B ON  A.CUST_ID = B.CUST_ID 
            WHERE A.SERIAL_NO=@IN_SERIAL_NO
            AND (A.STATUS=@IN_STATUS OR ISNULL(@IN_STATUS,0) = 0 OR @IN_STATUS = '')
            ORDER BY A.INPUT_TIME DESC
		END
GO
