USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE SP_MODI_TDEPARTMENT
                                   @IN_DEPART_ID  INT,
                                   @IN_DEPART_NAME NVARCHAR(24),
                                   @IN_DEPART_JC NVARCHAR(12),
                                   @IN_MANAGER_MAN NVARCHAR(20),
                                   @IN_LEADER_MAN NVARCHAR(20),
                                   @IN_INPUT_MAN INT
WITH ENCRYPTION
AS
  DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
  DECLARE @V_DEPART_NAME NVARCHAR(24)

  SELECT @V_RET_CODE = -10101000
  SELECT @IBUSI_FLAG = 10101
  SELECT @SBUSI_NAME = N'修改部门信息'
  SELECT @SSUMMARY = N'修改部门信息'

  IF NOT EXISTS(SELECT * FROM TDEPARTMENT WHERE DEPART_ID = @IN_DEPART_ID)
  BEGIN
      RETURN @V_RET_CODE - 11
  END

  BEGIN TRANSACTION

  UPDATE TDEPARTMENT
  SET
      DEPART_NAME = @IN_DEPART_NAME,
      DEPART_JC = @IN_DEPART_JC,
      MANAGER_MAN = @IN_MANAGER_MAN,
      LEADER_MAN = @IN_LEADER_MAN
  WHERE DEPART_ID = @IN_DEPART_ID
  IF @@ERROR <> 0
  BEGIN
       ROLLBACK TRANSACTION
       RETURN -100
  END
  INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
  VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)

   COMMIT TRANSACTION
   return 100
GO
