USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TCustomers_NAME @IN_CUST_NAME  NVARCHAR(80),--客户姓名
                                          @IN_CUST_ID    INT,
                                          @IN_FLAG       INT,         --1仅相同的名称2仅仅相同的证件号
                                          @IN_CARD_ID    NVARCHAR(80)=''

WITH ENCRYPTION
AS
    DECLARE @IN_CARD_ID18 NVARCHAR(18)
    SET @IN_CUST_NAME=ISNULL(@IN_CUST_NAME,'')
    SET @IN_CARD_ID=ISNULL(@IN_CARD_ID,'')
    IF @IN_CUST_NAME<>'' AND @IN_CARD_ID<>'' --当客户姓名与客户证件号码都传进来，表示都要提示下是否已存在（单个相同验证，多个验证放在新建的过程中）
    BEGIN --姓名、证件号都相同，也做个提示
		IF EXISTS (SELECT 1 FROM TCustomers WHERE CUST_NAME=@IN_CUST_NAME AND CARD_ID=@IN_CARD_ID AND CUST_ID<>@IN_CUST_ID AND STATUS <> '112805')
		BEGIN
			SELECT CUST_ID,CUST_NO,CUST_NAME,CARD_TYPE,CARD_TYPE_NAME,CARD_ID,3 SAME_TYPE
				FROM TCustomers WHERE CUST_NAME = @IN_CUST_NAME  AND CUST_ID <>@IN_CUST_ID AND CARD_ID = @IN_CARD_ID AND STATUS <> '112805'
            RETURN
		END
		SELECT CUST_ID,CUST_NO,CUST_NAME,CARD_TYPE,CARD_TYPE_NAME,CARD_ID,1 SAME_TYPE
            FROM TCustomers WHERE CUST_NAME = @IN_CUST_NAME  AND CUST_ID <>@IN_CUST_ID AND STATUS <> '112805'
        UNION ALL
        SELECT CUST_ID,CUST_NO,CUST_NAME,CARD_TYPE,CARD_TYPE_NAME,CARD_ID,2 SAME_TYPE
            FROM TCustomers WHERE CARD_ID = @IN_CARD_ID  AND CUST_ID <>@IN_CUST_ID AND STATUS <> '112805'
		RETURN
    END
    IF @IN_FLAG = 1  --相同的名称
        SELECT CUST_ID,CUST_NO,CUST_NAME,A.CARD_TYPE,CARD_TYPE_NAME,A.CARD_ID,A.SERVICE_MAN,B.OP_NAME SERVICE_MAN_NAME
            FROM TCustomers A LEFT JOIN TOPERATOR B ON A.SERVICE_MAN=B.OP_CODE
            WHERE CUST_NAME = @IN_CUST_NAME  AND CUST_ID <>@IN_CUST_ID AND A.STATUS <> '112805'
    ELSE IF @IN_FLAG = 3 --相同的证件号
        SELECT CUST_ID,CUST_NO,CUST_NAME,CARD_TYPE,CARD_TYPE_NAME,CARD_ID
            FROM TCustomers WHERE CARD_ID = @IN_CUST_NAME  AND CUST_ID <>@IN_CUST_ID AND STATUS <> '112805'
GO
