USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_MODI_TCONTRACTMODI @IN_SERIAL_NO                INTEGER,
                                       @IN_CONTRACT_SUB_BH          NVARCHAR(50),		
                                       @IN_QS_DATE                  INTEGER,
									   @IN_JK_DATE                  INTEGER,									
									   @IN_JK_TYPE                  NVARCHAR(10),
									   @IN_BANK_ID                  NVARCHAR(10),
									   @IN_BANK_SUB_NAME            NVARCHAR(60),
									   @IN_BANK_ACCT                NVARCHAR(30),
									   @IN_GAIN_ACCT                NVARCHAR(60) = NULL,	
									   @IN_BONUS_FLAG               INTEGER      = 1,          --1、兑付　2、转份额
									   @IN_BONUS_RATE               DECIMAL(5,4) = 0,          --转份额比例
									   @IN_PROV_FLAG                INTEGER      = 1,          --1.优先，2一般，3劣后
									   @IN_PROV_LEVEL               NVARCHAR(10) = '120401',   --收益级别（1204） 							   
									   @IN_LINK_MAN                 INTEGER,
									   @IN_CHANNEL_ID               INTEGER      = 0,          --销售渠道ID									   	   
									   @IN_CHANNEL_TYPE             NVARCHAR(10) = NULL,       --交银:渠道类别(5500)
									   @IN_CHANNEL_MEMO             NVARCHAR(200) = NULL,      --渠道附加信息
									   @IN_CHANNEL_COOPERTYPE       NVARCHAR(10)  = NULL,      --渠道合作方式(5502)
									   @IN_MARKET_MONEY            DECIMAL(16,3)    = 0,           --渠道费用
									   @IN_SUMMARY                  NVARCHAR(200),		
                                       @IN_INPUT_MAN                INTEGER
WITH ENCRYPTION
AS
    DECLARE @V_ERRMSG NVARCHAR(100)
    DECLARE @V_CONTRACT_SERIAL INT
    DECLARE @V_CONTRACT_BH NVARCHAR(16),@V_RG_MONEY DECIMAL(16,3),@V_CUST_ID INT,@V_HT_STATUS NVARCHAR(10),
            @V_CARD_ID NVARCHAR(40),@V_CARD_TYPE NVARCHAR(10),@V_LINK_MAN INT,@V_CHECK_FLAG INT,
            @V_START_DATE INT,@V_END_DATE INT,@V_CONTRACT_SUB_BH NVARCHAR(50)
    DECLARE @V_HT_BANK_NAME NVARCHAR(30),@V_JK_TYPE_NAME NVARCHAR(30),@V_BANK_NAME NVARCHAR(30),
            @V_CITY_NAME NVARCHAR(20),@V_PROV_LEVEL_NAME NVARCHAR(30)
    DECLARE @V_RG_MONEY2 DECIMAL(16,3), @V_RG_FEE_RATE DECIMAL(5,4), @V_RG_FEE_MONEY DECIMAL(16,3),
            @V_JK_TOTAL_MONEY DECIMAL(16,3), @V_GS_RATE DECIMAL(5,4),@V_MODE_FLAG INT
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200),@V_ENTITY_TYPE_NAME NVARCHAR(30)
    DECLARE @V_INTTEMP INT, @V_CHANNEL_COOPERTYPE_NAME NVARCHAR(30)

    BEGIN TRY
    
    SELECT @V_CONTRACT_SERIAL=CONTRACT_SERIAL FROM TCONTRACTMODI WHERE SERIAL_NO=@IN_SERIAL_NO AND CHECK_FLAG=1
    IF @@ROWCOUNT=0
		RAISERROR('没有可修改的记录！',16,3)
		
    SET @IN_CONTRACT_SUB_BH = LTRIM(RTRIM(ISNULL(@IN_CONTRACT_SUB_BH,'')))
    IF EXISTS (SELECT * FROM INTRUST..TCONTRACT WHERE SERIAL_NO<>@V_CONTRACT_SERIAL AND CONTRACT_SUB_BH=@IN_CONTRACT_SUB_BH)
    BEGIN 
        SELECT @V_ERRMSG = '录入合同编号[' + @IN_CONTRACT_SUB_BH  + ']已经被使用，请检查！'
        RAISERROR(@V_ERRMSG,16,3)
    END
    
    SELECT @V_JK_TYPE_NAME = TYPE_CONTENT FROM INTRUST..TDICTPARAM WHERE TYPE_VALUE = @IN_JK_TYPE
    SELECT @V_BANK_NAME = TYPE_CONTENT FROM INTRUST..TDICTPARAM WHERE TYPE_VALUE = @IN_BANK_ID
    SELECT @V_CHANNEL_COOPERTYPE_NAME = TYPE_CONTENT FROM INTRUST..TDICTPARAM WHERE TYPE_ID = 5502 AND TYPE_VALUE = @IN_CHANNEL_COOPERTYPE
    
    SELECT @IN_PROV_LEVEL = '120401' WHERE ISNULL(@IN_PROV_LEVEL,'') = ''
    SELECT @V_PROV_LEVEL_NAME = TYPE_CONTENT FROM INTRUST..TDICTPARAM WHERE TYPE_VALUE = @IN_PROV_LEVEL

    BEGIN TRANSACTION	
    
	UPDATE TCONTRACTMODI
	    SET CONTRACT_SUB_BH=@IN_CONTRACT_SUB_BH, QS_DATE=@IN_QS_DATE
	        ,JK_DATE=@IN_JK_DATE,JK_TYPE=@IN_JK_TYPE,JK_TYPE_NAME=@V_JK_TYPE_NAME
	        ,LINK_MAN=@IN_LINK_MAN,BONUS_FLAG=@IN_BONUS_FLAG,BONUS_RATE=@IN_BONUS_RATE
	        ,CHANNEL_ID=@IN_CHANNEL_ID,CHANNEL_TYPE=@IN_CHANNEL_TYPE,CHANNEL_MEMO=@IN_CHANNEL_MEMO
			,CHANNEL_COOPERTYPE=@IN_CHANNEL_COOPERTYPE,CHANNEL_COOPERTYPE_NAME=@V_CHANNEL_COOPERTYPE_NAME,MARKET_MONEY=@IN_MARKET_MONEY
			,BANK_ID=@IN_BANK_ID,BANK_SUB_NAME=@IN_BANK_SUB_NAME,BANK_ACCT=@IN_BANK_ACCT,GAIN_ACCT=@IN_GAIN_ACCT
			,SUMMARY=@IN_SUMMARY,PROV_FLAG=@IN_PROV_FLAG,PROV_LEVEL=@IN_PROV_LEVEL,PROV_LEVEL_NAME=@V_PROV_LEVEL_NAME
		WHERE SERIAL_NO=@IN_SERIAL_NO

    COMMIT TRANSACTION
    
    END TRY

    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION

        DECLARE @V_ERROR_STR NVARCHAR(1000),@V_ERROR_NUMBER INT,@V_ERROR_SEVERITY INT,@V_ERROR_STATE INT,
                @V_ERROR_PROCEDURE sysname,@V_ERROR_LINE INT,@V_ERROR_MESSAGE NVARCHAR(4000)

        SELECT @V_ERROR_STR = N'Message:%s,Procedure:%s,Line:%d',
               @V_ERROR_NUMBER = ERROR_NUMBER(),
               @V_ERROR_SEVERITY = ERROR_SEVERITY(),
               @V_ERROR_STATE = ERROR_STATE(),
               @V_ERROR_PROCEDURE = ERROR_PROCEDURE(),
               @V_ERROR_LINE = ERROR_LINE(),
               @V_ERROR_MESSAGE = ERROR_MESSAGE()

        RAISERROR(@V_ERROR_STR,@V_ERROR_SEVERITY,1,@V_ERROR_MESSAGE,@V_ERROR_PROCEDURE,@V_ERROR_LINE)

        RETURN -100
    END CATCH
    RETURN 100
GO
