USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_GET_CONTRACT_BH_INFO
                                  @IN_CONTRACT_TYPE    INT,    --合同类型：1,认购合同，2 申购合同
                                  @IN_PRODUCT_ID       INT,    --产品ID
                                  @IN_CONTRACT_SUB_BH  NVARCHAR(50) 
WITH ENCRYPTION
AS
    IF @IN_CONTRACT_TYPE =1 --认购合同
    BEGIN
        SELECT '使用客户名：'+ISNULL(B.CUST_NAME,'')+'；认购金额：'+ISNULL(CAST(A.RG_MONEY AS VARCHAR),'')+'；认购日期：'+ISNULL(CAST(A.QS_DATE AS VARCHAR),'') INFO
			FROM INTRUST..TCONTRACT A LEFT JOIN TCustomers B ON A.CUST_ID=B.CUST_ID
			WHERE PRODUCT_ID =@IN_PRODUCT_ID AND CONTRACT_SUB_BH =@IN_CONTRACT_SUB_BH
    END
    ELSE IF @IN_CONTRACT_TYPE =2 --申购合同
    BEGIN
        SELECT '使用客户名：'+ISNULL(B.CUST_NAME,'')+'；申购金额：'+ISNULL(CAST(A.SG_MONEY AS VARCHAR),'')+'；申购日期：'+ISNULL(CAST(A.QS_DATE AS VARCHAR),'') INFO
			FROM INTRUST..TCONTRACTSG A LEFT JOIN TCustomers B ON A.CUST_ID=B.CUST_ID
			WHERE PRODUCT_ID =@IN_PRODUCT_ID AND CONTRACT_SUB_BH =@IN_CONTRACT_SUB_BH
    END
GO
