USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TCUSTMANAGERS_FORTREE
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    DECLARE @V_MANAGER001 INT
    SELECT @V_MANAGER001 = VALUE FROM TSYSCONTROL WHERE FLAG_TYPE = 'MANAGER001'
    SELECT @V_MANAGER001 = ISNULL(@V_MANAGER001,1)

    SELECT * FROM TCustManagers A
        WHERE NOT EXISTS(SELECT 1 FROM TCustManagerTree B WHERE A.ManagerID = B.MANAGERID)
            AND(@V_MANAGER001 <> 1 OR (NOT EXISTS(SELECT 1 FROM TCustManagerTreeMembers C WHERE A.ManagerID = C.MANAGERID) AND @V_MANAGER001 = 1) )
GO
