USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_ADD_TTopicScore  @IN_QUES_ID            INTEGER,
                                     @IN_TOPIC_ID           INTEGER,
                                     @IN_QUES_TITLE         NVARCHAR(30),
                                     @IN_TOPIC_VALUE        NVARCHAR(30),
                                     @IN_Score              INTEGER =0,
                                     @IN_REMARK             NVARCHAR(512),
                                     @IN_INPUT_MAN          INT = 0         --操作员
WITH ENCRYPTION
AS
DECLARE @V_TOPIC_VALUE_NO INTEGER
DECLARE @V_RET_CODE INT, @IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)
SELECT @V_RET_CODE = -30503000, @IBUSI_FLAG = 30503
SELECT @SBUSI_NAME = N'添加问卷分值表信息', @SSUMMARY = N'添加问卷分值表信息'

IF NOT EXISTS(SELECT 1 FROM TQuesTopic WHERE TOPIC_ID = @IN_TOPIC_ID)
    RETURN -30503001   --问卷题目信息不存在

SELECT @V_TOPIC_VALUE_NO = ISNULL(MAX(TOPIC_VALUE_NO),0)+1 FROM TTopicScore WHERE TOPIC_ID = @IN_TOPIC_ID
BEGIN TRANSACTION
    INSERT INTO TTopicScore (QUES_ID,TOPIC_ID,QUES_TITLE,TOPIC_VALUE_NO,TOPIC_VALUE,Score,REMARK)
    VALUES (@IN_QUES_ID,@IN_TOPIC_ID,@IN_QUES_TITLE,@V_TOPIC_VALUE_NO,@IN_TOPIC_VALUE,@IN_Score,@IN_REMARK)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SET @SSUMMARY = N'添加问卷分值表信息，操作员：' + CAST(@IN_INPUT_MAN AS NVARCHAR(10))
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

COMMIT TRANSACTION
RETURN 100

GO
