USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_DEL_TCustomers @IN_CUST_ID INT,
                                   @IN_INPUT_MAN INT
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    SET XACT_ABORT ON

    DECLARE @V_STATUS NVARCHAR(10),@V_STATUS_NAME NVARCHAR(30),@V_CUST_NAME NVARCHAR(100),@V_RG_TIMES INT,@V_IS_DEL INT,
            @V_CURRENT_MONEY DECIMAL(16,3),@V_ENABLE_QUERY_TYPE INT
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    SELECT @V_RET_CODE = -20603000
    SELECT @IBUSI_FLAG = 20603;
    SELECT @SBUSI_NAME = N'注销客户基本信息'
    SELECT @SSUMMARY = N'注销客户基本信息'

    DECLARE @RET INT, @V_DT_INTRUST INT
    SELECT @V_DT_INTRUST = VALUE FROM TSYSCONTROL WHERE FLAG_TYPE = N'DT_INTRUST'

	
	BEGIN TRY
	
    IF NOT EXISTS(SELECT * FROM TCustomers WHERE CUST_ID = @IN_CUST_ID)
       RAISERROR('客户编号不存在',16,1)  -- 客户编号不存在
--校验客户信息是否可以删除
    SELECT @V_IS_DEL = 1
    IF @V_DT_INTRUST = 1 --启用分布式
    BEGIN
        IF EXISTS(SELECT * FROM SRV_Intrust.INTRUST.dbo.TCONTRACT WHERE CUST_ID = @IN_CUST_ID AND HT_STATUS NOT IN('120104','120105'))
           RAISERROR('客户有认购不能删除',16,1)   -- 客户有认购不能删除
        IF EXISTS(SELECT * FROM SRV_Intrust.INTRUST.dbo.TBENIFITOR WHERE CUST_ID = @IN_CUST_ID AND BEN_AMOUNT <> 0)
           RAISERROR('客户有受益份额不能删除',16,1)  -- 客户有受益份额不能删除
        IF @V_RG_TIMES > 0 OR EXISTS(SELECT 1 FROM SRV_Intrust.INTRUST.dbo.TDEPLOY WHERE CUST_ID = @IN_CUST_ID)
            OR EXISTS(SELECT 1 FROM SRV_Intrust.INTRUST.dbo.TMONEYDETAIL WHERE CUST_ID = @IN_CUST_ID)
           SELECT @V_IS_DEL = 0
    END
    ELSE IF (@V_DT_INTRUST = 2) AND EXISTS(SELECT * FROM master..sysdatabases WHERE NAME = N'INTRUST') --本地信托数据库
    BEGIN
        IF EXISTS(SELECT * FROM TPRECONTRACT WHERE CUST_ID = @IN_CUST_ID)
           SELECT @V_IS_DEL = 0
		IF EXISTS(SELECT * FROM INTRUST..TCONTRACT WHERE CUST_ID = @IN_CUST_ID AND HT_STATUS NOT IN('120104','120105'))
           RAISERROR('客户有认购不能删除',16,1)   -- 客户有认购不能删除  
        IF EXISTS(SELECT * FROM INTRUST..TBENIFITOR WHERE CUST_ID = @IN_CUST_ID AND BEN_AMOUNT <> 0)
           RAISERROR('客户有受益份额不能删除',16,1)   -- 客户有受益份额不能删除
        IF @V_RG_TIMES > 0 OR EXISTS(SELECT 1 FROM INTRUST..TDEPLOY WHERE CUST_ID = @IN_CUST_ID) OR EXISTS(SELECT 1 FROM INTRUST..TMONEYDETAIL WHERE CUST_ID = @IN_CUST_ID)
           SELECT @V_IS_DEL = 0
    END
    SELECT @V_STATUS = STATUS,@V_CUST_NAME = CUST_NAME,@V_RG_TIMES = RG_TIMES,@V_CURRENT_MONEY = CURRENT_MONEY
        FROM TCustomers WHERE CUST_ID = @IN_CUST_ID
    IF @V_CURRENT_MONEY <> 0 AND @V_CURRENT_MONEY IS NOT NULL
       RAISERROR('客户有未结清的合同或受益权不能删除',16,1)   -- 客户有未结清的合同或受益权不能删除
/*
    SELECT @V_ENABLE_QUERY_TYPE = 1
    --如果有客户访问权限控制，则执行客户信息加密
    IF EXISTS(SELECT * FROM TSYSCONTROL WHERE FLAG_TYPE = N'CUSTRIGHT' AND VALUE = 1)
        SELECT @V_ENABLE_QUERY_TYPE = dbo.GETCUSTRIGHT(@IN_CUST_ID,@IN_INPUT_MAN)
    IF @V_ENABLE_QUERY_TYPE = 2
        RETURN -22001004
*/

    SELECT @V_STATUS = N'112805'
    SELECT @V_STATUS_NAME = N'删除'

    IF @V_DT_INTRUST = 1 --启用分布式
        BEGIN DISTRIBUTED TRANSACTION
    ELSE --无分布式或本地信托数据库
        BEGIN TRANSACTION
	SET @V_IS_DEL = 0--注销时，全部都改客户状态，不真正删除数据
    IF @V_IS_DEL = 0 --注销，不可删除记录
    BEGIN
        UPDATE TCustomers
            SET STATUS = @V_STATUS,
                STATUS_NAME = @V_STATUS_NAME,
                CANCEL_MAN = @IN_INPUT_MAN,
                CANCEL_TIME = dbo.GETDATEINT(GETDATE())
				--IS_DEAL = 3 --注销客户
            WHERE CUST_ID = @IN_CUST_ID
        IF @V_DT_INTRUST = 1 --启用分布式
            UPDATE SRV_Intrust.INTRUST.dbo.TCUSTOMERINFO
            SET STATUS = @V_STATUS,
                STATUS_NAME = @V_STATUS_NAME,
                CANCEL_MAN = @IN_INPUT_MAN,
                CANCEL_TIME = dbo.GETDATEINT(GETDATE())
            WHERE CUST_ID = @IN_CUST_ID
        ELSE IF (@V_DT_INTRUST = 2) AND EXISTS(SELECT * FROM master..sysdatabases WHERE NAME = N'INTRUST') --本地信托数据库
            UPDATE INTRUST..TCUSTOMERINFO
            SET STATUS = @V_STATUS,
                STATUS_NAME = @V_STATUS_NAME,
                CANCEL_MAN = @IN_INPUT_MAN,
                CANCEL_TIME = dbo.GETDATEINT(GETDATE())
            WHERE CUST_ID = @IN_CUST_ID
    END
    ELSE
    BEGIN
        DELETE FROM TCustomers WHERE CUST_ID = @IN_CUST_ID
        DELETE FROM TCustomerContacts WHERE CUST_ID = @IN_CUST_ID
        --删除客户积分卡
        IF EXISTS(SELECT 1 FROM sysobjects WHERE NAME = 'IM_CUST_INTEGRAL_CARD') AND EXISTS(SELECT 1 FROM IM_CUST_INTEGRAL_CARD WHERE CUST_ID = @IN_CUST_ID)
        BEGIN
            DELETE FROM IM_CUST_INTEGRAL_CARD WHERE CUST_ID = @IN_CUST_ID
        END
        IF @V_DT_INTRUST = 1 --启用分布式
            DELETE FROM SRV_Intrust.INTRUST.dbo.TCUSTOMERINFO WHERE CUST_ID = @IN_CUST_ID
        ELSE IF (@V_DT_INTRUST = 2) AND EXISTS(SELECT * FROM master..sysdatabases WHERE NAME = N'INTRUST') --本地信托数据库
            DELETE FROM INTRUST..TCUSTOMERINFO WHERE CUST_ID = @IN_CUST_ID
    END

    SELECT @SSUMMARY = N'注销客户基本信息，客户名称：'+@V_CUST_NAME
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
	COMMIT TRANSACTION
    SET XACT_ABORT OFF
    RETURN 100
	END TRY
	
	BEGIN CATCH
        IF @@TRANCOUNT > 0 BEGIN
            ROLLBACK TRANSACTION
        END
        
        DECLARE @V_ERROR_STR NVARCHAR(1000),@V_ERROR_NUMBER INT,@V_ERROR_SEVERITY INT,@V_ERROR_STATE INT,
                @V_ERROR_PROCEDURE sysname,@V_ERROR_LINE INT,@V_ERROR_MESSAGE NVARCHAR(4000)

        SELECT @V_ERROR_STR = N'Error %d,Level %d,State %d,Procedure %s,Line %d,Message %s',
               @V_ERROR_NUMBER = ERROR_NUMBER(),
               @V_ERROR_SEVERITY = ERROR_SEVERITY(),
               @V_ERROR_STATE = ERROR_STATE(),
               @V_ERROR_PROCEDURE = ERROR_PROCEDURE(),
               @V_ERROR_LINE = ERROR_LINE(),
               @V_ERROR_MESSAGE = ERROR_MESSAGE()

        RAISERROR(@V_ERROR_STR,@V_ERROR_SEVERITY,1,@V_ERROR_NUMBER,@V_ERROR_SEVERITY,@V_ERROR_STATE,
                  @V_ERROR_PROCEDURE,@V_ERROR_LINE,@V_ERROR_MESSAGE)

        RETURN -100
    END CATCH	
    
	
GO
