USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_ADD_TOPERATOR_UUID  @IN_OP_CODE 		INTEGER,                 	--操作员ID													
										@IN_UUID        	NVARCHAR(60), 			    --UUID										
										@IN_INPUT_MAN       INTEGER          			--录入员
WITH ENCRYPTION										
AS	
DECLARE @IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)
SELECT  @IBUSI_FLAG = 10105    SELECT @SBUSI_NAME = N'增加操作员UUID对应记录', @SSUMMARY = N'增加操作员UUID对应记录'

BEGIN TRANSACTION
	IF EXISTS(SELECT 1 FROM TOPERATOR_UUID WHERE OP_CODE = @IN_OP_CODE)
	BEGIN
		UPDATE TOPERATOR_UUID
			SET UUID = @IN_UUID,
				INSERT_TIME = CONVERT(DATETIME,CONVERT(NVARCHAR(64),GETDATE(),120))
			WHERE OP_CODE = @IN_OP_CODE
	END
	ELSE 
	BEGIN
		INSERT INTO TOPERATOR_UUID (OP_CODE,UUID,INSERT_TIME)
			VALUES (@IN_OP_CODE,@IN_UUID,CONVERT(DATETIME,CONVERT(NVARCHAR(64),GETDATE(),120)))
	END

	IF @@ERROR <> 0
	BEGIN        
		ROLLBACK TRANSACTION        
		RETURN -100    
	END	

	SET @SSUMMARY = N'增加操作员UUID对应记录，操作员：' + CAST(@IN_INPUT_MAN AS NVARCHAR(10))    
	INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)        
		VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)    
	IF @@ERROR <> 0    
	BEGIN       
		ROLLBACK TRANSACTION       
		RETURN -100    
	END
COMMIT TRANSACTION
RETURN 100 
	
GO
