USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TCUSTMERGE
                            @IN_SERIAL_NO   INT = 0, 
                            @IN_CHECK_FLAG  INT = 0, 
                            @IN_CUST_NAME   VARCHAR(100) = '',
                            @IN_INPUT_MAN  INT 
WITH ENCRYPTION
AS
    SELECT M.*
        , C1.CUST_NAME AS FROM_CUST_NAME, C1.CARD_ID AS FROM_CARD_ID
        , C1.CARD_TYPE AS FROM_CARD_TYPE, C1.CARD_TYPE_NAME AS FROM_CARD_TYPE_NAME
        , C1.CUST_TYPE AS FROM_CUST_TYPE, C1.CUST_TYPE_NAME AS FROM_CUST_TYPE_NAME
        , C2.CUST_NAME AS TO_CUST_NAME, C2.CARD_ID AS TO_CARD_ID
        , C1.IS_DEAL AS FROM_IS_DEAL, CASE C1.IS_DEAL WHEN 1 THEN '事实客户' WHEN 2 THEN '潜在客户' ELSE '其他' END AS FROM_IS_DEAL_NAME
        , C2.CARD_TYPE AS TO_CARD_TYPE, C2.CARD_TYPE_NAME AS TO_CARD_TYPE_NAME
        , C2.CUST_TYPE AS TO_CUST_TYPE, C2.CUST_TYPE_NAME AS TO_CUST_TYPE_NAME
        , C2.IS_DEAL AS TO_IS_DEAL, CASE C2.IS_DEAL WHEN 1 THEN '事实客户' WHEN 2 THEN '潜在客户' ELSE '其他' END AS TO_IS_DEAL_NAME
        , D1.CLASSDETAIL_NAME FROM_CUST_LEVEL_NAME,D2.CLASSDETAIL_NAME TO_CUST_LEVEL_NAME
      FROM TCUSTMERGE M
        JOIN TCustomers C1 ON C1.CUST_ID=M.FROM_CUST_ID
        JOIN TCustomers C2 ON C2.CUST_ID=M.TO_CUST_ID
        LEFT JOIN TCustomerClass D1 ON D1.CLASSDEFINE_ID=12 AND D1.CUST_ID=M.FROM_CUST_ID
        LEFT JOIN TCustomerClass D2 ON D2.CLASSDEFINE_ID=12 AND D2.CUST_ID=M.TO_CUST_ID
      WHERE M.CHECK_FLAG IN (1, 2)
        AND (M.SERIAL_NO=@IN_SERIAL_NO OR ISNULL(@IN_SERIAL_NO,0)=0)
        AND (M.CHECK_FLAG=@IN_CHECK_FLAG OR ISNULL(@IN_CHECK_FLAG,0)=0)
        AND (ISNULL(@IN_CUST_NAME,'')='' OR C1.CUST_NAME LIKE '%'+@IN_CUST_NAME+'%' OR C2.CUST_NAME LIKE '%'+@IN_CUST_NAME+'%')
GO
