USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_ADD_TCUSTGROUPS    @IN_PARENTGROUPID    INT,            --父级组ID（TCUSTGROUPS.GROUPID）
                                       @IN_GROUPNAME        NVARCHAR(60),   --子分组名称
                                       @IN_INPUT_MAN        INT =  0        --输入员
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT, @IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)
    SELECT @V_RET_CODE = -30301000, @IBUSI_FLAG = 30301
    SELECT @SBUSI_NAME = N'添加客户分组（需要指定父级组）', @SSUMMARY = N'添加客户分组（需要指定父级组）'
    DECLARE @V_RIGHT_ID INT,@V_LEVEL_ID INT
    SET XACT_ABORT ON
    IF EXISTS (SELECT 1 FROM TCustGroups WHERE GroupID = @IN_PARENTGROUPID)
    BEGIN
        BEGIN TRANSACTION
        SELECT @V_RIGHT_ID=RIGHT_ID,@V_LEVEL_ID = LEVEL_ID FROM TCustGroups WHERE GroupID = @IN_PARENTGROUPID
        UPDATE TCustGroups SET RIGHT_ID=RIGHT_ID+2 WHERE RIGHT_ID>=@V_RIGHT_ID
        UPDATE TCustGroups SET LEFT_ID=LEFT_ID+2 WHERE LEFT_ID>=@V_RIGHT_ID

        INSERT INTO TCustGroups (GroupName,LEFT_ID,RIGHT_ID,LEVEL_ID)
            VALUES (@IN_GROUPNAME,@V_RIGHT_ID,@V_RIGHT_ID+1,@V_LEVEL_ID + 1 )

        SET @SSUMMARY = N'添加下级子节点，，下级客户经理，操作员：' + CAST(@IN_INPUT_MAN AS NVARCHAR(10))
        INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)

        COMMIT TRANSACTION
        SET XACT_ABORT OFF
    END
GO
