USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TPRODUCT_LIST @IN_SALE_STATUS    INT = 1,
                                        @IN_PRODUCT_STATUS NVARCHAR(10) ='',
                                        @IN_OPEN_FLAG      INT = 0,  --101:正常期开放式集合产品;102推介期，或者是子产品在推介期的集合产品
                                        @IN_INPUT_MAN      INT,
                                        @IN_PRODUCT_CODE   NVARCHAR(6)='',   --产品编号
                                        @IN_PRODUCT_NAME   NVARCHAR(60)= ''  --产品名称
                                        
WITH ENCRYPTION
AS
    DECLARE @V_DT_INTRUST INT,@V_SINGLE INT,@V_USER_ID INT
    SELECT @V_DT_INTRUST = VALUE FROM TSYSCONTROL WHERE FLAG_TYPE = N'DT_INTRUST'
    SELECT @V_SINGLE = VALUE FROM TSYSCONTROL WHERE FLAG_TYPE = 'SINGLE'
    SELECT @V_SINGLE = ISNULL(@V_SINGLE,0)
    SELECT @V_USER_ID=USER_ID FROM TSYSTEMINFO
	
    IF @V_DT_INTRUST = 1 --启用分布式
    BEGIN
        IF @IN_OPEN_FLAG=102 --推介期，或者是子产品在推介期的集合产品
        BEGIN
			SELECT A.PRODUCT_ID,A.PRODUCT_CODE,A.PRODUCT_NAME,B.SUB_FLAG
                FROM TPRODUCT A LEFT JOIN SRV_Intrust.INTRUST.dbo.TPRODUCT B ON B.PRODUCT_ID=A.PRODUCT_ID
                WHERE B.BOOK_CODE = 1
                    AND (B.PRODUCT_STATUS = '110202' OR (B.SUB_FLAG=1 AND EXISTS (SELECT * FROM SRV_Intrust.INTRUST.dbo.TSUBPRODUCT WHERE PRODUCT_ID=A.PRODUCT_ID AND PRODUCT_STATUS='110202')))
                    AND (B.INTRUST_FLAG1=2 OR EXISTS (SELECT * FROM TSYSCONTROL WHERE FLAG_TYPE='SINGLE' AND VALUE=1)) --集合信托
                    AND (ISNULL(@IN_PRODUCT_CODE,'')='' OR A.PRODUCT_CODE LIKE @IN_PRODUCT_CODE+'%')
                    AND (ISNULL(@IN_PRODUCT_NAME,'')='' OR A.PRODUCT_NAME LIKE '%'+@IN_PRODUCT_NAME+'%')
                ORDER BY A.PRODUCT_CODE DESC
			RETURN
        END
        SELECT A.*,B.RISK_LEVEL,B.SALE_STATUS FROM SRV_Intrust.INTRUST.dbo.TPRODUCT A LEFT JOIN TPRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
            WHERE A.BOOK_CODE  = 1
            AND (A.PRODUCT_STATUS = @IN_PRODUCT_STATUS OR @IN_PRODUCT_STATUS IS NULL OR @IN_PRODUCT_STATUS = ''
				OR A.FPRG_FLAG=1/*分批募集阶段*/)
            AND (A.OPEN_FLAG = @IN_OPEN_FLAG OR ISNULL(@IN_OPEN_FLAG,0) = 0)
            AND (((B.SALE_STATUS = @IN_SALE_STATUS OR ISNULL(@IN_SALE_STATUS,0) = 0)AND(A.INTRUST_FLAG1 = 2)) OR (A.INTRUST_FLAG1 = 1) )
            AND A.CHECK_FLAG = 2 AND ((A.INTRUST_FLAG1 = 2 AND @V_SINGLE = 0) OR (@V_SINGLE = 1))
        --    AND A.SUB_FLAG = 0--没有子产品
        --加上子产品
       -- UNION ALL SELECT 1,A.*,B.RISK_LEVEL,B.SALE_STATUS FROM SRV_Intrust.INTRUST.dbo.TSUBPRODUCT A LEFT JOIN TSUBPRODUCT B ON A.SUB_PRODUCT_ID = B.SUB_PRODUCT_ID
            --WHERE A.BOOK_CODE  = 1
        ORDER BY A.INTRUST_FLAG1,A.PRODUCT_CODE DESC
        
    END
    ELSE IF (@V_DT_INTRUST = 2) AND EXISTS(SELECT * FROM master..sysdatabases WHERE NAME = N'INTRUST') --本地信托数据库
    BEGIN
        IF @IN_OPEN_FLAG=101 --101:正常期开放式集合产品
        BEGIN
			SELECT A.INTRUST_FLAG1,A.*,B.RISK_LEVEL FROM INTRUST..TPRODUCT A LEFT JOIN TPRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
				WHERE A.BOOK_CODE  = 1 AND A.CHECK_FLAG = 2
					AND A.OPEN_FLAG =1  --开放式
					AND (A.PRODUCT_STATUS = '110203'/*正常期*/ OR (@V_USER_ID=17 AND A.PRODUCT_STATUS='110202')/*方正东亚要求在推介期也可申购*/)
					AND (A.INTRUST_FLAG1 = 2 OR EXISTS (SELECT * FROM TSYSCONTROL WHERE FLAG_TYPE='SINGLE' AND VALUE=1)) --集合信托
			RETURN
        END
        IF @IN_OPEN_FLAG=102 --推介期，或者是子产品在推介期的集合产品
        BEGIN
			SELECT A.PRODUCT_ID,A.PRODUCT_CODE,A.PRODUCT_NAME,B.SUB_FLAG
                FROM TPRODUCT A LEFT JOIN INTRUST..TPRODUCT B ON B.PRODUCT_ID=A.PRODUCT_ID
                WHERE B.BOOK_CODE = 1
                    AND (B.PRODUCT_STATUS = '110202' OR (B.SUB_FLAG=1 AND EXISTS (SELECT * FROM INTRUST..TSUBPRODUCT WHERE PRODUCT_ID=A.PRODUCT_ID AND PRODUCT_STATUS='110202')))
                    AND (B.INTRUST_FLAG1=2 OR EXISTS (SELECT * FROM TSYSCONTROL WHERE FLAG_TYPE='SINGLE' AND VALUE=1)) --集合信托
                    AND (ISNULL(@IN_PRODUCT_CODE,'')='' OR A.PRODUCT_CODE LIKE @IN_PRODUCT_CODE+'%')
                    AND (ISNULL(@IN_PRODUCT_NAME,'')='' OR A.PRODUCT_NAME LIKE '%'+@IN_PRODUCT_NAME+'%')
                ORDER BY A.PRODUCT_CODE DESC
			RETURN
        END
        SELECT A.*,B.RISK_LEVEL,B.SALE_STATUS FROM INTRUST..TPRODUCT A LEFT JOIN TPRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
            WHERE A.BOOK_CODE  = 1
            AND A.CHECK_FLAG = 2 
            AND (A.PRODUCT_STATUS = @IN_PRODUCT_STATUS OR @IN_PRODUCT_STATUS IS NULL OR @IN_PRODUCT_STATUS = '' OR (@IN_PRODUCT_STATUS = '110202' AND A.PRODUCT_STATUS = '110203' AND FPRG_FLAG = 1))
            AND (A.OPEN_FLAG = @IN_OPEN_FLAG OR ISNULL(@IN_OPEN_FLAG,0) = 0)
            AND (((B.SALE_STATUS = @IN_SALE_STATUS OR ISNULL(@IN_SALE_STATUS,0) = 0)AND(A.INTRUST_FLAG1 = 2)) OR (A.INTRUST_FLAG1 = 1) )
            AND ((A.INTRUST_FLAG1 = 2 AND @V_SINGLE = 0) OR (@V_SINGLE = 1))
			
            ORDER BY A.INTRUST_FLAG1,A.PRODUCT_CODE DESC
    END
GO
