USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_DEL_TCUSTMANAGERS   @IN_MANAGERID           INT,            --关联对应于TOperator.OP_CODE（主键）
                                        @IN_INPUT_MAN           INT = 0         --操作员
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT, @IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)
    SELECT @V_RET_CODE = -30401000, @IBUSI_FLAG = 30401
    SELECT @SBUSI_NAME = N'删除客户经理信息', @SSUMMARY = N'删除客户经理信息'

    IF NOT EXISTS(SELECT 1 FROM TCustManagers WHERE ManagerID = @IN_MANAGERID)
        RETURN @V_RET_CODE - 1 --客户经理记录不存在
    IF EXISTS(SELECT 1 FROM TCustManagerTree WHERE MANAGERID = @IN_MANAGERID)
        RETURN @V_RET_CODE - 6 --该客户经理已经被使用不能删除
    IF EXISTS(SELECT 1 FROM TServiceTasks WHERE ManagerID = @IN_MANAGERID OR Executor = @IN_MANAGERID OR InsertMan = @IN_MANAGERID)
        RETURN @V_RET_CODE - 6 --该客户经理已经被使用不能删除
    IF EXISTS(SELECT 1 FROM TCUSTMANAGERCHANGES WHERE MANAGERID_BEFORE =  @IN_MANAGERID OR MANAGERID_NOW = @IN_MANAGERID)
        RETURN @V_RET_CODE - 6 --该客户经理已经被使用不能删除

    BEGIN TRANSACTION
    DELETE FROM  TCustManagers
    WHERE ManagerID = @IN_MANAGERID
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SET @SSUMMARY = '删除客户经理信息，操作员：' + CAST(@IN_INPUT_MAN AS NVARCHAR(10))
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
