USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_DEL_TTEAMINFO   @IN_TEAM_ID                 INT,       --项目组ID
                                    @IN_INPUT_MAN               INT        --录入人员，对应表TOPERATOR.OP_CODE
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    DECLARE @V_TEAM_NAME NVARCHAR(200)
    SELECT @SBUSI_NAME = N'合同管理之删除项目组'
    SELECT @SSUMMARY = N'合同管理之删除项目组'
    SELECT @IBUSI_FLAG = 50001
    SELECT @V_RET_CODE = -50001000

    SELECT @V_TEAM_NAME =TEAM_NAME FROM TTEAMINFO WHERE TEAM_ID =@IN_TEAM_ID

    BEGIN TRANSACTION

    DELETE FROM TTEAMINFO WHERE TEAM_ID =@IN_TEAM_ID
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SELECT @SSUMMARY = N'合同管理之删除项目组,项目组名称：'+@V_TEAM_NAME
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
