USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TCONTRACTMODI_LOAD @IN_SERIAL_NO INT
WITH ENCRYPTION
AS
    SELECT D.*,ISNULL(E.MIN_BUY_LIMIT,0) MIN_BUY_LIMIT,ISNULL(E.MAX_BUY_LIMIT,0) MAX_BUY_LIMIT
        FROM ( SELECT M.SERIAL_NO, M.CONTRACT_SERIAL, A.BOOK_CODE,A.PRODUCT_ID,A.PRODUCT_CODE,A.PRODUCT_NAME,A.CURRENCY_ID,A.CUST_ID
                    ,A.PRE_CODE,A.CONTRACT_BH,A.TOUCH_TYPE,A.TOUCH_TYPE_NAME,A.VALID_PERIOD,A.START_DATE,A.END_DATE
                    ,A.RG_MONEY,A.TO_MONEY,A.TO_AMOUNT,A.JK_STATUS,A.TRANS_FLAG,A.TRANS_FLAG_NAME,A.LAST_TRANS_DATE
                    ,A.INPUT_MAN,A.INPUT_TIME,A.MODI_MAN,A.MODI_TIME,A.CHECK_MAN,A.CHECK_TIME,A.ZJ_CHECK_MAN,A.ZJ_CHECK_TIME
                    ,A.HT_STATUS,A.HT_STATUS_NAME,A.ZJ_CHECK_FLAG,A.SERVICE_MAN,A.TEMP_STATUS,A.TEMP_END_DATE
                    ,A.TEMP_RG_MONEY,A.TEMP_QS_DATE,A.PRE_FLAG,A.ENTITY_NAME,A.ENTITY_TYPE,A.ENTITY_TYPE_NAME,A.ENTITY_PRICE
                    ,A.PZ_FLAG,A.CITY_SERIAL_NO,A.CITY_NAME,A.TERMINATE_DATE,A.ORIGINAL_END_DATE,A.DF_CUST_ID,A.ZY_FLAG
                    ,A.FEE_JK_TYPE,A.RG_MONEY2,A.RG_FEE_RATE,A.RG_FEE_MONEY,A.JK_TOTAL_MONEY,A.SUB_PRODUCT_ID
                    ,A.WITH_BANK_FLAG,A.HT_BANK_ID,A.HT_BANK_NAME,A.HT_BANK_SUB_NAME,A.WITH_SECURITY_FLAG,A.WITH_PRIVATE_FLAG
                    ,A.TA_FLAG,A.TA_ACCOUNT_ID,A.TRADE_ACCOUNT_ID,A.MODE_FLAG,A.MEND_CHECK_FLAG,A.BZJ_FLAG
                    ,A.BANK_PROVINCE,A.BANK_PROVINCE_NAME,A.BANK_CITY,A.BANK_CITY_NAME,A.RECOMMEND_MAN,A.RECOMMEND_MAN_NAME
                    ,A.SUBMIT_FLAG,A.EXPECT_ROR_LOWER,A.EXPECT_ROR_UPPER,A.FPRG_TIMES,A.SALE_CON_FLAG,A.FPRG_FLAG
                    ,A.IS_YKGL,A.XTHTYJSYL,A.PERIOD_UNIT,A.CONTACT_ID,A.LOST_DATE
                    ,A.HT_CUST_NAME,A.HT_CUST_ADDRESS,A.HT_CUST_TEL,A.MONEY_ORIGIN,A.MONEY_ORIGIN_NAME,A.SUB_MONEY_ORIGIN,A.SUB_MONEY_ORIGIN_NAME
                   ,M.CONTRACT_SUB_BH, M.BANK_ID, M.BANK_SUB_NAME, M.BANK_ACCT, M.GAIN_ACCT,M.BONUS_FLAG,M.BONUS_RATE
                   ,M.QS_DATE, M.JK_DATE, M.JK_TYPE, M.JK_TYPE_NAME,M.LINK_MAN,M.PROV_FLAG,M.PROV_LEVEL,M.PROV_LEVEL_NAME,M.SUMMARY
                   , M.CHANNEL_COOPERTYPE, M.CHANNEL_COOPERTYPE_NAME, M.CHANNEL_ID, M.CHANNEL_TYPE, M.CHANNEL_MEMO, M.MARKET_MONEY
                    ,C.CUST_NO,C.CUST_NAME,C.CARD_ID
                    ,M.CHECK_FLAG,M.CHECK_SUMMARY
                FROM INTRUST..TCONTRACT A, INTRUST..TPRODUCT B, INTRUST..TCUSTOMERINFO C, TCONTRACTMODI M
                WHERE M.CONTRACT_SERIAL=A.SERIAL_NO AND A.PRODUCT_ID = B.PRODUCT_ID AND A.CUST_ID = C.CUST_ID  
                    AND M.SERIAL_NO = @IN_SERIAL_NO
            ) D
        LEFT JOIN INTRUST..TSUBPRODUCT E
        ON D.SUB_PRODUCT_ID = E.SUB_PRODUCT_ID
GO
