USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_CHECK_TCOCONTRACTMAINTAIN @IN_MAINTAIN_ID   INT,   --维护合同(维护费)ID
                                              @IN_INPUT_MAN     INT    --录入人员，对应表TOPERATOR.OP_CODE
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    DECLARE @V_COCONTRACTMAINTAIN_SUB_BH     NVARCHAR(200)   --维护合同编号
    SELECT @SBUSI_NAME = N'合同管理之复核维护合同'
    SELECT @SSUMMARY = N'合同管理之复核维护合同'
    SELECT @IBUSI_FLAG = 50001
    SELECT @V_RET_CODE = -50001000

    SELECT @V_COCONTRACTMAINTAIN_SUB_BH = COCONTRACTMAINTAIN_SUB_BH FROM TCOCONTRACTMAINTAIN WHERE MAINTAIN_ID =@IN_MAINTAIN_ID

    BEGIN TRANSACTION

    UPDATE TCOCONTRACTMAINTAIN
        SET CHECK_FLAG =2
        WHERE MAINTAIN_ID =@IN_MAINTAIN_ID
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    --
    SELECT @SSUMMARY = N'合同管理之复核维护合同，合同编号'+@V_COCONTRACTMAINTAIN_SUB_BH
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
