USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE SP_MODI_TPROFIT @IN_SERIAL_NO       INT,          --序号
                                 @IN_PROFIT_MONEY    DEC(16,3),    --收益金额
                                 @IN_SY_DATE         INT,          --收益分配日期
                                 @IN_INPUT_MAN       INT           --操作员
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200),@TABLE_ID NVARCHAR(60)
    DECLARE @V_SUBSCRIBE_ID INT
    SELECT @SBUSI_NAME = N'修改非信托产品份额信息'
    SELECT @SSUMMARY = N'修改非信托产品份额信息'
    SELECT @IBUSI_FLAG = 39016
    SELECT @V_RET_CODE = -39016000

    IF NOT EXISTS(SELECT * FROM TPROFIT WHERE SERIAL_NO = @IN_SERIAL_NO)
        RETURN @V_RET_CODE - 12   --非信托产品收益信息不存在

    BEGIN TRANSACTION

    SELECT @V_SUBSCRIBE_ID = SUBSCRIBE_ID FROM TPROFIT WHERE SERIAL_NO = @IN_SERIAL_NO

    UPDATE TPROFIT
        SET PROFIT_MONEY = @IN_PROFIT_MONEY,
            SY_DATE = @IN_SY_DATE,
            INPUT_MAN = @IN_INPUT_MAN,
            INPUT_TIME = GETDATE()
        WHERE SERIAL_NO= @IN_SERIAL_NO

    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SELECT @SSUMMARY = N'修改非信托产品收益，合同编号：'+RTRIM(CONVERT(NVARCHAR(16),@V_SUBSCRIBE_ID))
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
