USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE  SP_QUERY_TOPERATOR_VALID
WITH ENCRYPTION
AS
    SELECT A.* FROM TOPERATOR A
        WHERE A.OP_CODE <> 0 AND ISNULL(A.ONLINE,0) = 1
        ORDER BY A.OP_CODE
GO
