USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_GET_MANAGERREE_CHILDREN @IN_SERIAL_NO INT --给定节点标识

WITH ENCRYPTION
AS
    DECLARE @V_LEFT_ID INT,@V_RIGHT_ID INT,@V_LEVEL_ID INT
    IF EXISTS (SELECT 1 FROM TCustManagerTree WHERE SERIAL_NO = @IN_SERIAL_NO)
    BEGIN
        SELECT @V_LEFT_ID = LEFT_ID,@V_RIGHT_ID = RIGHT_ID,@V_LEVEL_ID  = LEVEL_ID
        FROM TCustManagerTree WHERE SERIAL_NO = @IN_SERIAL_NO
        SELECT SERIAL_NO,MANAGERID,MANAGERNAME,LEFT_ID,RIGHT_ID,LEVEL_ID,LEVEL_NO,LEVEL_NAME
        FROM TCustManagerTree WHERE LEVEL_ID = @V_LEVEL_ID + 1 AND LEFT_ID > @V_LEFT_ID AND LEFT_ID < @V_RIGHT_ID
        ORDER BY LEFT_ID ASC
    END
GO
