USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_FAQ_CLASS @IN_FAQ_CLASS_NO   NVARCHAR(10), --知识库分类编号
									@IN_INPUT_MAN      INT
WITH ENCRYPTION
AS
	IF @IN_FAQ_CLASS_NO  <> '' AND @IN_FAQ_CLASS_NO IS NOT NULL
		SELECT MENU_ID AS FAQ_CLASS_NO, MENU_NAME AS FAQ_CLASS_NAME
		FROM TMENUINFO WHERE MENU_ID LIKE 'W05%' AND MENU_ID = @IN_FAQ_CLASS_NO	
	ELSE
		SELECT MENU_ID AS FAQ_CLASS_NO, MENU_NAME AS FAQ_CLASS_NAME
		FROM TMENUINFO WHERE MENU_ID LIKE 'W05%' AND MENU_ID <> 'W05'
GO
