USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_DEL_TROLERIGHT @IN_ROLE_ID INT,
                                   @IN_MENU_ID NVARCHAR(10),
                                   @IN_FUNC_ID INT,
                                   @IN_INPUT_MAN INT
WITH ENCRYPTION
AS
    DECLARE @IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    SELECT @SBUSI_NAME = N'删除角色权限'
    SELECT @SSUMMARY = N'删除角色权限'
    SELECT @IBUSI_FLAG = 10702

    IF NOT EXISTS(SELECT * FROM TROLERIGHT WHERE ROLE_ID = @IN_ROLE_ID AND MENU_ID = @IN_MENU_ID AND FUNC_ID = @IN_FUNC_ID )
    BEGIN
        RETURN -2   -- 角色权限不存在
    END

    BEGIN TRANSACTION

    DELETE FROM TROLERIGHT WHERE ROLE_ID = @IN_ROLE_ID AND MENU_ID = @IN_MENU_ID AND FUNC_ID = @IN_FUNC_ID
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    /*
    DELETE FROM TOPRIGHT WHERE  MENU_ID = @IN_MENU_ID AND FUNC_ID = @IN_FUNC_ID
                AND OP_CODE IN (SELECT OP_CODE FROM TOPERATOR WHERE ROLE_ID = @IN_ROLE_ID)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    */

    SELECT @SSUMMARY = N'删除角色权限，角色编号：'+RTRIM(CONVERT(NVARCHAR(16),@IN_ROLE_ID))+N'，菜单编号：'+@IN_MENU_ID+N',功能编号:'+RTRIM(CONVERT(CHAR(8),@IN_FUNC_ID))
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
