USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_ADD_TEMAILRECIPIENTS @IN_MAIL_SERIAL_NO  INT,
                                         @IN_CUST_ID         INT,
                                         @IN_RECIPIENTS      VARCHAR(30),
                                         @IN_INPUT_MAN       INT,
                                         @OUT_SERIAL_NO      INT OUTPUT,
                                         @IN_TB_FLAG         INT = 1,    -- ADD BY JINXR 2009/6/1
                                         @IN_DF_SERIAL_NO    INT = 0     -- ADD BY JINXR 2009/6/1
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT, @IBUSI_FLAG INT
    DECLARE @SBUSI_NAME VARCHAR(40), @SSUMMARY VARCHAR(200)
    SELECT @V_RET_CODE = -23003000, @IBUSI_FLAG = 23003
    SELECT @SBUSI_NAME = '增加EMAIL收件人', @SSUMMARY = '增加EMAIL收件人'

    BEGIN TRANSACTION

    INSERT INTO TEMAILRECIPIENTS(MAIL_SERIAL_NO, CUST_ID, RECIPIENTS,TB_FLAG,DF_SERIAL_NO)
        VALUES(@IN_MAIL_SERIAL_NO, @IN_CUST_ID, @IN_RECIPIENTS,@IN_TB_FLAG,@IN_DF_SERIAL_NO)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    SELECT @OUT_SERIAL_NO = @@IDENTITY

    SELECT @SSUMMARY = '增加EMAIL收件人，邮件序号：' + RTRIM(CONVERT(CHAR(16),@IN_MAIL_SERIAL_NO)) + ' 收件人：' + RTRIM(CONVERT(CHAR(16),@IN_CUST_ID)) + ' - ' + @IN_RECIPIENTS
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
