USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TMANAGERTEAMMEMBERS   @IN_SERIAL_NO           INT,        --团队成员ID
                                                @IN_TEAM_ID             INT         --团队ID
WITH ENCRYPTION
AS

    SELECT SERIAL_NO,TEAM_ID,TEAM_NO,TEAM_NAME,MANAGERID,MANAGERNAME,DESCRIPTION
    FROM TManagerTeamMembers
    WHERE (SERIAL_NO = @IN_SERIAL_NO OR ISNULL(@IN_SERIAL_NO,0) = 0)
        AND (TEAM_ID = @IN_TEAM_ID OR ISNULL(@IN_TEAM_ID,0) = 0 )
    RETURN 100
GO
