USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_ADD_TBENCHANGES_TPROBLEMS   @IN_SERIAL_NO       INTEGER,            --序号
                                                @IN_PROJECTID       INTEGER,            --受益权转让审批类别
                                                @IN_INPUT_MAN       INTEGER,            --操作员
                                                @OUT_PROBLEM_ID     INTEGER = 0 OUTPUT  --流程ID
WITH ENCRYPTION
AS
    SET NOCOUNT ON

    DECLARE @V_RET_CODE INT, @IBUSI_FLAG INT, @SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)
    DECLARE @V_PROBLEMTYPEID INT, @V_PROBLEMSTATEID INT,@V_RET INT,@V_APPLY_DATE INT
    DECLARE @V_PROBLEMSEVERITYID INT,@V_PROBLEMPRIORITYID INT,@V_DEADLINE INT
    DECLARE @V_TITLE NVARCHAR(50),@V_DESCRIPTION NVARCHAR(3000),@V_PROBLEMID INT,@V_CUST_MANAGER INT

    BEGIN TRY
    IF ISNULL(@IN_PROJECTID,0) <>0
    BEGIN
        SELECT @V_PROBLEMSTATEID =PROBLEMSTATEID FROM INTRUST..TPROBLEMSTATE WHERE PROJECTID =@IN_PROJECTID AND TYPE = N'start'
        SELECT @V_PROBLEMTYPEID =MIN(PROBLEMTYPEID) FROM INTRUST..TPROBLEMTYPE WHERE PROJECTID =@IN_PROJECTID
        SELECT @V_PROBLEMSEVERITYID =MIN(PROBLEMSEVERITYID) FROM INTRUST..TPROBLEMSEVERITY WHERE PROJECTID =@IN_PROJECTID
        SELECT @V_PROBLEMPRIORITYID =MIN(PROBLEMPRIORITYID) FROM INTRUST..TPROBLEMPRIORITY WHERE PROJECTID =@IN_PROJECTID
        
        --START
        SELECT @V_TITLE = N'关于《'+D.PRODUCT_NAME+'》受益权转的审批',
               @V_DESCRIPTION = N'<table border="1" width="100%" cellpadding="10"><tr><td>合同编号：' + A.CONTRACT_BH
                   +N';<P>产品名称：' + D.PRODUCT_NAME
                   +N';<P>转让方：' + B.CUST_NAME
                   +N';<P>受让方：' + C.CUST_NAME
                   +N';<P>转让方式：' + E.TYPE_CONTENT
                   +N';<P>转让金额：' + CAST(CAST(ISNULL(A.TO_AMOUNT,0) AS DECIMAL(16,2)) AS NVARCHAR(30))
                   +N'</td></tr></table>'
            FROM INTRUST..TBENCHANGES A, INTRUST..TCUSTOMERINFO B, INTRUST..TCUSTOMERINFO C, INTRUST..TPRODUCT D, 
                    (SELECT * FROM INTRUST..TDICTPARAM WHERE TYPE_ID=1115) E
                WHERE A.SERIAL_NO = @IN_SERIAL_NO
                    AND A.FROM_CUST_ID = B.CUST_ID
                    AND A.TO_CUST_ID = C.CUST_ID
                    AND A.PRODUCT_ID = D.PRODUCT_ID
                    AND A.TRANS_FLAG = E.TYPE_VALUE
        --END

        SET @V_APPLY_DATE =CONVERT(INT,CONVERT(CHAR(8),GETDATE(),112))
        SET @V_DEADLINE =@V_APPLY_DATE
    END
    SET @V_CUST_MANAGER = ISNULL(@V_CUST_MANAGER,@IN_INPUT_MAN)

    BEGIN TRANSACTION

    IF ISNULL(@IN_PROJECTID,0) <>0
    BEGIN
        IF ISNULL(@V_TITLE,'') = '' SELECT @V_TITLE = '关于**项目的立项审批'
        EXEC @V_RET =SP_ADD_TPROBLEMS @IN_PROJECTID,@IN_SERIAL_NO,@V_PROBLEMTYPEID,@V_PROBLEMSTATEID,
                    @V_PROBLEMSEVERITYID,@V_PROBLEMPRIORITYID,@V_DEADLINE,@V_CUST_MANAGER,@V_TITLE,@V_DESCRIPTION,
                    @V_APPLY_DATE,@V_CUST_MANAGER,@V_PROBLEMID OUTPUT
        SET @OUT_PROBLEM_ID = @V_PROBLEMID
        
        UPDATE INTRUST..TBENCHANGES
            SET APPR_STATUS ='110001',  --审批中
                APPR_STATUS_NAME = N'审批中',
                PROBLEM_ID =@V_PROBLEMID
           WHERE SERIAL_NO = @IN_SERIAL_NO
    END
    ELSE
    BEGIN
        UPDATE INTRUST..TBENCHANGES
            SET APPR_STATUS = '110003',  --审批通过
                APPR_STATUS_NAME = N'审批通过',
                PROBLEM_ID = @V_PROBLEMID
           WHERE SERIAL_NO = @IN_SERIAL_NO
    END
    
    COMMIT TRANSACTION
    END TRY

    BEGIN CATCH
        IF @@TRANCOUNT > 0 
            ROLLBACK TRANSACTION 

        DECLARE @V_ERROR_STR NVARCHAR(1000),@V_ERROR_NUMBER INT,@V_ERROR_SEVERITY INT,@V_ERROR_STATE INT,
                @V_ERROR_PROCEDURE sysname,@V_ERROR_LINE INT,@V_ERROR_MESSAGE NVARCHAR(4000)
        SELECT @V_ERROR_STR = N',Message %s,Error %d,Level %d,State %d,Procedure %s,Line %d',
               @V_ERROR_NUMBER = ERROR_NUMBER(),
               @V_ERROR_SEVERITY = ERROR_SEVERITY(),
               @V_ERROR_STATE = ERROR_STATE(),
               @V_ERROR_PROCEDURE = ERROR_PROCEDURE(),
               @V_ERROR_LINE = ERROR_LINE(),
               @V_ERROR_MESSAGE = ERROR_MESSAGE()

        RAISERROR(@V_ERROR_STR,@V_ERROR_MESSAGE,@V_ERROR_SEVERITY,1,@V_ERROR_NUMBER,@V_ERROR_SEVERITY,
                  @V_ERROR_STATE,@V_ERROR_PROCEDURE,@V_ERROR_LINE)
        RETURN -100

    END CATCH
    RETURN 100
GO
