USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TGAINLEVEL @IN_SERIAL_NO      INTEGER,              --1.记录号
                                     @IN_PREPRODUCT_ID  INTEGER,              --2.预发行产品ID
                                     @IN_PROV_FLAG      INTEGER,              --3.优先级
                                     @IN_PROV_LEVEL     NVARCHAR(10),         --4.收益级别编号
                                     @IN_INPUT_MAN      INTEGER               --5.操作员
WITH ENCRYPTION
AS
    
    SELECT A.*,C.PREPRODUCT_NAME AS PRODUCT_NAME ,D.GAIN_RATE,CASE A.PROV_FLAG WHEN 1 THEN '优先' WHEN 2 THEN '一般' ELSE '劣后' END PROV_FLAG_NAME, 
           D.SERIAL_NO AS RATE_SERIAL_NO, D.START_DATE, D.END_DATE
        FROM TGAINLEVEL A LEFT JOIN (SELECT A.SERIAL_NO, A.START_DATE,A.END_DATE, B.DF_SERIAL_NO,A.GAIN_RATE FROM TGAINLEVELRATE A, (SELECT MAX(END_DATE) END_DATE,DF_SERIAL_NO 
                                        FROM TGAINLEVELRATE GROUP BY DF_SERIAL_NO) B
                                            WHERE A.END_DATE = B.END_DATE AND A.DF_SERIAL_NO = B.DF_SERIAL_NO) D ON A.SERIAL_NO = D.DF_SERIAL_NO
            LEFT JOIN TPREPRODUCT C ON C.PREPRODUCT_ID=A.PREPRODUCT_ID
        WHERE (A.SERIAL_NO = @IN_SERIAL_NO OR ISNULL(@IN_SERIAL_NO,0) = 0) 
            AND (A.PREPRODUCT_ID = @IN_PREPRODUCT_ID OR ISNULL(@IN_PREPRODUCT_ID,0) = 0)
            AND (A.PROV_FLAG = @IN_PROV_FLAG OR ISNULL(@IN_PROV_FLAG,0) = 0)
            AND (A.PROV_LEVEL = @IN_PROV_LEVEL OR ISNULL(@IN_PROV_LEVEL,'') = '')
       ORDER BY A.PREPRODUCT_ID DESC,A.PROV_FLAG,A.PROV_LEVEL
GO
