USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_MODI_TPRODUCT_INVESTMENT @IN_PRODUCT_ID  INT,
											 @INVEST_FIELD	 VARCHAR (80),
											 @IN_INPUT_MAN	 INT
WITH ENCRYPTION
AS
	DECLARE @V_TYPE_CONTENT NVARCHAR(20)
    DECLARE @V_BOOK_CODE INT,@V_END_DATE INT,@V_OLD_END_DATE INT,@V_LIST_ID INT
    DECLARE @V_PRODUCT_CODE VARCHAR(6),@V_PRODUCT_NAME NVARCHAR(60)
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME VARCHAR(40),@SSUMMARY VARCHAR(200)
    SELECT @IBUSI_FLAG = 20315
    SELECT @SBUSI_NAME = 'CRM投资领域'
    SELECT @SSUMMARY = 'CRM投资领域'

	BEGIN TRY
	BEGIN TRANSACTION
	SELECT @V_TYPE_CONTENT = TYPE_CONTENT FROM TDICTPARAM WHERE TYPE_ID = 1139 AND TYPE_VALUE = @INVEST_FIELD
    IF EXISTS(SELECT 1 FROM TPRODUCT WHERE @IN_PRODUCT_ID = PRODUCT_ID)   --CRM库是否存在该产品
     BEGIN
        UPDATE TPRODUCT 
		SET INVEST_FIELD = @INVEST_FIELD , INVEST_FIELD_NAME = @V_TYPE_CONTENT
		WHERE @IN_PRODUCT_ID = PRODUCT_ID
    END

	ELSE
	 BEGIN
		SELECT @V_PRODUCT_CODE = PRODUCT_CODE,@V_PRODUCT_NAME = PRODUCT_NAME FROM INTRUST..TPRODUCT WHERE PRODUCT_ID = @IN_PRODUCT_ID
		
		INSERT INTO TPRODUCT(PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,INPUT_TIME,INVEST_FIELD,INVEST_FIELD_NAME) 
		VALUES(@IN_PRODUCT_ID,@V_PRODUCT_CODE,@V_PRODUCT_NAME,GETDATE(),@INVEST_FIELD,@V_TYPE_CONTENT)
	 END 
	 
    SELECT @SSUMMARY = @V_PRODUCT_CODE + '-' + @V_PRODUCT_NAME + ',CRM投资领域,' + @V_TYPE_CONTENT
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)

    COMMIT TRANSACTION
	END TRY
	
	BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
        
        DECLARE @V_ERROR_STR NVARCHAR(1000),@V_ERROR_NUMBER INT,@V_ERROR_SEVERITY INT,@V_ERROR_STATE INT,
                @V_ERROR_PROCEDURE sysname,@V_ERROR_LINE INT,@V_ERROR_MESSAGE NVARCHAR(4000)

        SELECT @V_ERROR_STR = N'Message:%s,Procedure:%s,Line:%d',
               @V_ERROR_NUMBER = ERROR_NUMBER(),
               @V_ERROR_SEVERITY = ERROR_SEVERITY(),
               @V_ERROR_STATE = ERROR_STATE(),
               @V_ERROR_PROCEDURE = ERROR_PROCEDURE(),
               @V_ERROR_LINE = ERROR_LINE(),
               @V_ERROR_MESSAGE = ERROR_MESSAGE()

        RAISERROR(@V_ERROR_STR,@V_ERROR_SEVERITY,1,@V_ERROR_MESSAGE,@V_ERROR_PROCEDURE,@V_ERROR_LINE)
        
        RETURN -100
    END CATCH
    RETURN 100
GO
