USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_THOLIDAYDATE @IN_SERIAL_NO    INT = NULL, --序号
                                       @IN_HOLIDAY_ID   INT = NULL, --节假日ID
                                       @IN_INPUT_MAN    INT = NULL
WITH ENCRYPTION
AS
    IF @IN_HOLIDAY_ID IS NULL SET @IN_HOLIDAY_ID = 0
    IF @IN_SERIAL_NO <> 0
        SELECT *, dbo.fn_getmonthday(MMDDINT) AS MMDD_CN
        FROM THOLIDAYDATE WHERE SERIAL_NO = @IN_SERIAL_NO
    ELSE
        SELECT *, dbo.fn_getmonthday(MMDDINT) AS MMDD_CN
        FROM THOLIDAYDATE
        WHERE (HOLIDAY_ID = @IN_HOLIDAY_ID OR @IN_HOLIDAY_ID = 0)
GO
