USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TEAMPRE1 @IN_TEAM_ID      INT,                 --团队ID
                                  @IN_MANAGERNAME  NVARCHAR(128),       --团队成员名称(客户经理)
                                  @IN_INPUT_MAN    INT = NULL,          --操作员
                                  @IN_QUERY_DATE   INT = NULL          --查询日期
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    IF @IN_QUERY_DATE = 0 OR @IN_QUERY_DATE IS NULL
        SET @IN_QUERY_DATE = dbo.GETDATEINT(GETDATE())
    DECLARE @V_WEEKSTART DATETIME, @V_WEEKEND DATETIME
    DECLARE @V_WEEKSTARTINT INT, @V_WEEKENDINT INT
    SET @V_WEEKSTART = dateadd(week,-1,GETDATE())
    SET @V_WEEKEND = dateadd(week,-1,GETDATE())
    WHILE DATEPART(weekday, @V_WEEKSTART ) > 2
    BEGIN
        SET @V_WEEKSTART = dateadd(DAY,-1,@V_WEEKSTART)
    END
    WHILE DATEPART(weekday, @V_WEEKEND ) > 1
    BEGIN
        SET @V_WEEKEND = dateadd(DAY,1,@V_WEEKEND)
    END
    SET @V_WEEKSTARTINT = dbo.GETDATEINT(@V_WEEKSTART)
    SET @V_WEEKENDINT = dbo.GETDATEINT(@V_WEEKEND)

    CREATE TABLE #TEMP_QUERY_TEAMPRE
    (
        SERIAL_NO       INT NOT NULL IDENTITY,
        TEAM_ID         INT,             --团队ID
        TEAM_NO         NVARCHAR(60),    --团队编号
        TEAM_NAME       NVARCHAR(160),   --团队名称
        LEADER          INT,             --负责人ID
        LEADER_NAME     NVARCHAR(60),    --团队负责人
        LINK_MAN        INT,             --销售人员
        LINK_MAN_NAME   NVARCHAR(30),    --销售人员名称
        PRE_DATE        INT,             --预约日期
        PRE_MONEY       DEC(20,3),       --预约金额
        RG_MONEY        DEC(20,3),       --到帐金额
        LESS300_NUMBER  INT             --小额份数
    )
    INSERT INTO #TEMP_QUERY_TEAMPRE(LINK_MAN,LINK_MAN_NAME,PRE_MONEY,RG_MONEY,PRE_DATE)
		SELECT B.SERVICE_MAN,C.OP_NAME,A.PRE_MONEY,A.RG_MONEY,A.PRE_DATE 
		FROM TPRECONTRACT A,TCUSTOMERS B,TOPERATOR C
		WHERE A.CUST_ID = B.CUST_ID AND B.SERVICE_MAN = C.OP_CODE AND (A.PRE_DATE BETWEEN @V_WEEKSTARTINT AND @V_WEEKENDINT)
        --SELECT A.LINK_MAN,B.OP_NAME,A.PRE_MONEY,A.RG_MONEY,A.PRE_DATE
        --FROM TPRECONTRACT A, TOPERATOR B
        --WHERE A.LINK_MAN = B.OP_CODE AND (A.PRE_DATE BETWEEN @V_WEEKSTARTINT AND @V_WEEKENDINT)
select @V_WEEKSTARTINT,@V_WEEKENDINT
select * from #TEMP_QUERY_TEAMPRE
    UPDATE #TEMP_QUERY_TEAMPRE
        SET TEAM_ID = B.TEAM_ID, TEAM_NO = B.TEAM_NO, TEAM_NAME = B.TEAM_NAME
        FROM #TEMP_QUERY_TEAMPRE A, TManagerTeamMembers B
        WHERE A.LINK_MAN = B.MANAGERID
    UPDATE #TEMP_QUERY_TEAMPRE
        SET TEAM_ID = B.TEAM_ID, TEAM_NO = B.TEAM_NO, TEAM_NAME = B.TEAM_NAME
        FROM #TEMP_QUERY_TEAMPRE A, TManagerTeams B
        WHERE A.LINK_MAN = B.LEADER
    UPDATE #TEMP_QUERY_TEAMPRE
        SET LEADER = B.LEADER, LEADER_NAME = B.LEADER_NAME
        FROM #TEMP_QUERY_TEAMPRE A, TManagerTeams B
        WHERE A.TEAM_ID = B.TEAM_ID
    UPDATE #TEMP_QUERY_TEAMPRE SET LESS300_NUMBER = 1 WHERE PRE_MONEY < 3000000
   
    SELECT  B.TEAM_ID,B.TEAM_NO,B.TEAM_NAME,PRE_MONEY,RG_MONEY,LESS300_NUMBER
    FROM (SELECT TEAM_ID,TEAM_NO,TEAM_NAME,SUM(PRE_MONEY) AS PRE_MONEY,SUM(RG_MONEY) AS RG_MONEY, SUM(LESS300_NUMBER) AS LESS300_NUMBER
			FROM #TEMP_QUERY_TEAMPRE A 
			WHERE (A.TEAM_ID = @IN_TEAM_ID OR @IN_TEAM_ID IS NULL OR @IN_TEAM_ID = 0)
				AND(LINK_MAN_NAME LIKE '%'+@IN_MANAGERNAME+'%' OR @IN_MANAGERNAME IS NULL OR LINK_MAN_NAME IS NULL)
			GROUP BY A.TEAM_ID,A.TEAM_NO,A.TEAM_NAME) A RIGHT JOIN TManagerTeams B ON A.TEAM_ID = B.TEAM_ID
     ORDER BY B.TEAM_ID,B.TEAM_NO,B.TEAM_NAME
GO
