USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TSQSTOPCONTRACT_CRM @IN_SERIAL_NO         INT,            --序号
											  @IN_PRODUCT_ID        INT,            --产品ID
											  @IN_CONTRACT_BH       NVARCHAR(16),   --合同编号
											  @IN_REASON            NVARCHAR(200),  --退款原因，字符串描述
											  @IN_SQ_DATE           INT,            --申请办理退款日期
											  @IN_CHECK_FLAG        INT,            --1查询未审核记录;2查询已普通审核记录;3查询已财务审核记录
											  @IN_REBATE_FLAG       INT,            --1.认购期退款，2.申购期退款
											  @IN_SUB_PRODUCT_ID    INT   =0        --子产品ID

WITH ENCRYPTION
AS
    IF @IN_REBATE_FLAG = 1
        SELECT A.*, B.PRODUCT_NAME, C.CUST_NAME, A.SQ_MONEY AS RG_MONEY,D.LIST_NAME,D.LIST_NAME AS SUB_PRODUCT_NAME
            FROM INTRUST..TSQSTOPCONTRACT A,INTRUST..TCUSTOMERINFO C,INTRUST..TCONTRACT B LEFT JOIN INTRUST..TSUBPRODUCT D ON (B.SUB_PRODUCT_ID = D.SUB_PRODUCT_ID)
            WHERE A.HT_SERIAL_NO = B.SERIAL_NO AND B.CUST_ID = C.CUST_ID
                AND (A.SERIAL_NO = @IN_SERIAL_NO OR @IN_SERIAL_NO IS NULL OR @IN_SERIAL_NO = 0)
                AND (A.PRODUCT_ID = @IN_PRODUCT_ID OR @IN_PRODUCT_ID IS NULL OR @IN_PRODUCT_ID = 0)
                AND (A.CONTRACT_BH = @IN_CONTRACT_BH OR @IN_CONTRACT_BH IS NULL OR @IN_CONTRACT_BH = '')
                AND (A.REASON LIKE '%'+@IN_REASON+'%' OR @IN_REASON IS NULL OR @IN_REASON = '')
                AND (A.SQ_DATE = @IN_SQ_DATE OR @IN_SQ_DATE IS NULL OR @IN_SQ_DATE = 0)
                AND (A.CHECK_FLAG = @IN_CHECK_FLAG OR @IN_CHECK_FLAG IS NULL OR @IN_CHECK_FLAG = 0)
                AND (B.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID OR ISNULL(@IN_SUB_PRODUCT_ID,0) = 0)
                AND A.REBATE_FLAG = @IN_REBATE_FLAG
    ELSE
        SELECT A.*, B.PRODUCT_NAME, C.CUST_NAME, A.SQ_MONEY AS RG_MONEY,D.LIST_NAME,D.LIST_NAME AS SUB_PRODUCT_NAME
            FROM INTRUST..TSQSTOPCONTRACT A,INTRUST..TCUSTOMERINFO C,INTRUST..TCONTRACTSG B LEFT JOIN INTRUST..TSUBPRODUCT D ON (B.SUB_PRODUCT_ID = D.SUB_PRODUCT_ID)
            WHERE A.HT_SERIAL_NO = B.SERIAL_NO AND B.CUST_ID = C.CUST_ID
                AND (A.SERIAL_NO = @IN_SERIAL_NO OR @IN_SERIAL_NO IS NULL OR @IN_SERIAL_NO = 0)
                AND (A.PRODUCT_ID = @IN_PRODUCT_ID OR @IN_PRODUCT_ID IS NULL OR @IN_PRODUCT_ID = 0)
                AND (A.CONTRACT_BH = @IN_CONTRACT_BH OR @IN_CONTRACT_BH IS NULL OR @IN_CONTRACT_BH = '')
                AND (A.REASON LIKE '%'+@IN_REASON+'%' OR @IN_REASON IS NULL OR @IN_REASON = '')
                AND (A.SQ_DATE = @IN_SQ_DATE OR @IN_SQ_DATE IS NULL OR @IN_SQ_DATE = 0)
                AND (A.CHECK_FLAG = @IN_CHECK_FLAG OR @IN_CHECK_FLAG IS NULL OR @IN_CHECK_FLAG = 0)
                AND (B.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID OR ISNULL(@IN_SUB_PRODUCT_ID,0) = 0)
                AND A.REBATE_FLAG = @IN_REBATE_FLAG
GO
