USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE SP_QUERY_TDICTPARAM_TREE2 @IN_TYPE_ID          INTEGER,
                                           @IN_TYPE_VALUE       NVARCHAR(10) = NULL                              
WITH ENCRYPTION
AS
    DECLARE @V_TYPE_ID NVARCHAR(4)
    SET @V_TYPE_ID = CONVERT(NVARCHAR,@IN_TYPE_ID)
    SET @IN_TYPE_VALUE = ISNULL(@IN_TYPE_VALUE,@V_TYPE_ID)

    SELECT *
        FROM TDICTPARAM
        WHERE TYPE_ID = @IN_TYPE_ID AND TYPE_VALUE LIKE @IN_TYPE_VALUE + '__'
        
GO
