USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_SYNC_CUST_FROM_INTRUST
WITH ENCRYPTION
AS
    DECLARE @V_MAX_CUST_ID_CRM INT,@V_MAX_CUST_ID_INTRUST INT,@V_USER_ID INT
    DECLARE @V_ReceiveServices BIGINT
    DECLARE @V_SQL NVARCHAR(2000),@V_COLUMN_NAME NVARCHAR(80)
    DECLARE @IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    SELECT @IBUSI_FLAG = 20701
    SELECT @V_USER_ID=USER_ID FROM TSYSTEMINFO
    
    BEGIN TRY
    --同步新客户
    SELECT @V_MAX_CUST_ID_CRM = ISNULL(MAX(CUST_ID),0) FROM TCustomers
    SELECT @V_MAX_CUST_ID_INTRUST = ISNULL(MAX(CUST_ID),0) FROM INTRUST..TCUSTOMERINFO
    IF @V_MAX_CUST_ID_INTRUST>@V_MAX_CUST_ID_CRM
    BEGIN
		SELECT @V_ReceiveServices = SUM(ServiceType) FROM TServiceDefine
		INSERT INTO TCustomers(ReceiveServices, --添加客户时，默认接收所有服务
				CUST_ID,CUST_NO,CUST_NAME,CUST_TEL,POST_ADDRESS,POST_ADDRESS2,
				CARD_TYPE,CARD_TYPE_NAME,CARD_ID,AGE,SEX,SEX_NAME,POST_CODE2,
				O_TEL,H_TEL,MOBILE,BP,FAX,E_MAIL,CUST_TYPE,CUST_TYPE_NAME,
				WT_FLAG,WT_FLAG_NAME,PASSWORD,
				TOUCH_TYPE,TOUCH_TYPE_NAME,CUST_SOURCE,CUST_SOURCE_NAME,
				SUMMARY,INPUT_MAN,POST_CODE,CHECK_FLAG,LIST_ID, LEGAL_MAN, LEGAL_ADDRESS, BIRTHDAY,
				PRINT_DEPLOY_BILL, PRINT_POST_INFO, IS_LINK, SERVICE_MAN,VIP_CARD_ID,VIP_DATE,HGTZR_BH,
				VOC_TYPE,VOC_TYPE_NAME,CARD_VALID_DATE,COUNTRY,JG_CUST_TYPE, CONTACT_MAN,MONEY_SOURCE,MONEY_SOURCE_NAME,FACT_CONTROLLER,
				ImageIdentification,POTENTIAL_MONEY,
				PinYinSimple,IS_DEAL,GOV_PROV_REGIONAL,GOV_PROV_REGIONAL_NAME,GOV_REGIONAL,
				GOV_REGIONAL_NAME,RECOMMENDED,COMPLETE_FLAG,EAST_JG_TYPE,EAST_JG_TYPE_NAME,JG_WTRLX2,TRUE_FLAG
				)
		SELECT @V_ReceiveServices,
				CUST_ID,CUST_NO,CUST_NAME,CUST_TEL,POST_ADDRESS,POST_ADDRESS2,
				CARD_TYPE,CARD_TYPE_NAME,CARD_ID,AGE,SEX,SEX_NAME,POST_CODE2,
				O_TEL,H_TEL,MOBILE,BP,FAX,E_MAIL,CUST_TYPE,CUST_TYPE_NAME,
				2,'否','000000',
				ISNULL(TOUCH_TYPE,'110911')/*为空的话，用其他代替*/,ISNULL(TOUCH_TYPE_NAME,'其它网络通讯'),CUST_SOURCE,CUST_SOURCE_NAME,
				SUMMARY,INPUT_MAN,POST_CODE,2,LIST_ID, LEGAL_MAN, LEGAL_ADDRESS, BIRTHDAY,
				PRINT_DEPLOY_BILL, PRINT_POST_INFO, IS_LINK, NULL,VIP_CARD_ID,VIP_DATE,HGTZR_BH,
				VOC_TYPE,VOC_TYPE_NAME,CARD_VALID_DATE,COUNTRY,JG_CUST_TYPE, CONTACT_MAN,MONEY_SOURCE,MONEY_SOURCE_NAME,FACT_CONTROLLER,
				NULL,NULL,
				dbo.fGetPy(CUST_NAME),0,GOV_PROV_REGIONAL,GOV_PROV_REGIONAL_NAME,GOV_REGIONAL,
				GOV_REGIONAL_NAME,RECOMMENDED,COMPLETE_FLAG,EAST_JG_TYPE,EAST_JG_TYPE_NAME,JG_WTRLX2,1
			FROM INTRUST..TCUSTOMERINFO WHERE CUST_ID>@V_MAX_CUST_ID_CRM
	END
	IF @V_USER_ID=21/*金汇信托*/
		RETURN
    --INTRUST中客户修改同步
    --SELECT TOP 11 * FROM INTRUST..TCUSTINFODETAIL WHERE INPUT_TIME>='2013-12-06' ORDER BY INPUT_TIME DESC
    DECLARE CUR_D CURSOR FOR SELECT DISTINCT FIELD_NAME FROM INTRUST..TCUSTINFODETAIL
		WHERE INPUT_TIME>=GETDATE()-2 AND FIELD_NAME NOT IN ('SERVICE_MAN','CUST_TEL','H_TEL','O_TEL','MOBILE','POST_CODE','POST_CODE2','POST_ADDRESS','POST_ADDRESS2','E_MAIL','TO_CUST_ID','FROM_CUST_ID')
	OPEN CUR_D
	FETCH NEXT FROM CUR_D INTO @V_COLUMN_NAME
	WHILE @@FETCH_STATUS=0
	BEGIN
		--UPDATE TCustomers SET CARD_ID=(SELECT TOP 1 NEW_FIELD_INFO FROM INTRUST..TCUSTINFODETAIL WHERE CUST_ID=TCustomers.CUST_ID AND FIELD_NAME='CARD_ID' ORDER BY SERIAL_NO DESC) WHERE CUST_ID IN (SELECT DISTINCT CUST_ID FROM INTRUST..TCUSTINFODETAIL WHERE INPUT_TIME>=GETDATE()-2)
		SET @V_SQL='UPDATE TCustomers SET '+@V_COLUMN_NAME+'=(SELECT TOP 1 NEW_FIELD_INFO FROM INTRUST..TCUSTINFODETAIL WHERE CUST_ID=TCustomers.CUST_ID AND FIELD_NAME='''+@V_COLUMN_NAME+''' ORDER BY SERIAL_NO DESC) WHERE CUST_ID IN (SELECT DISTINCT CUST_ID FROM INTRUST..TCUSTINFODETAIL WHERE FIELD_NAME='''+@V_COLUMN_NAME+''' AND ISNULL(NEW_FIELD_INFO,'''')<>'''' AND INPUT_TIME>=GETDATE()-2)'
		EXEC (@V_SQL)
		FETCH NEXT FROM CUR_D INTO @V_COLUMN_NAME
	END
	CLOSE CUR_D
	DEALLOCATE CUR_D
	
	END TRY

    --异常处理
    BEGIN CATCH
        IF EXISTS(SELECT * FROM MASTER.dbo.syscursors where cursor_name='CUR_D')
        BEGIN
			CLOSE CUR_D
			DEALLOCATE CUR_D
        END
        DECLARE @V_ERROR_STR NVARCHAR(1000),@V_ERROR_NUMBER INT,@V_ERROR_SEVERITY INT,@V_ERROR_STATE INT,
                @V_ERROR_PROCEDURE sysname,@V_ERROR_LINE INT,@V_ERROR_MESSAGE NVARCHAR(4000)

        SELECT @V_ERROR_STR = N'%s<br>Procedure:%s,Line:%d',
               @V_ERROR_NUMBER = ERROR_NUMBER(),
               @V_ERROR_SEVERITY = ERROR_SEVERITY(),
               @V_ERROR_STATE = ERROR_STATE(),
               @V_ERROR_PROCEDURE = ERROR_PROCEDURE(),
               @V_ERROR_LINE = ERROR_LINE(),
               @V_ERROR_MESSAGE = ERROR_MESSAGE()

        RAISERROR(@V_ERROR_STR,@V_ERROR_SEVERITY,1,@V_ERROR_MESSAGE,@V_ERROR_PROCEDURE,@V_ERROR_LINE)
    END CATCH
GO
