USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TMENUINFO_NEW @IN_PARENT_ID NVARCHAR(10),
                                        @IN_OP_CODE   INT
WITH ENCRYPTION
AS
    --顶级
    IF LEN(@IN_PARENT_ID) = 1
        SELECT * FROM TMENUINFO
          WHERE ISNULL(PARENT_ID,'') = N'' AND LEFT(MENU_ID,1) = @IN_PARENT_ID AND
                (SELECT COUNT(*) FROM TOPRIGHT WHERE OP_CODE = @IN_OP_CODE AND LEFT(MENU_ID,LEN(@IN_PARENT_ID)) = @IN_PARENT_ID) > 0

    ELSE
        SELECT * FROM TMENUINFO
          WHERE PARENT_ID = @IN_PARENT_ID AND
               (SELECT COUNT(*) FROM TOPRIGHT WHERE OP_CODE = @IN_OP_CODE AND LEFT(MENU_ID,LEN(@IN_PARENT_ID)) = @IN_PARENT_ID) > 0

GO
