USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_ADD_TMANUALSCORING @IN_OPERAND_ID       INT,             --操作数ID(打分项)
                                       @IN_OPERATION_VALUE  NVARCHAR(120),   --选项值
                                       @IN_SCORE            INT,             --得分
                                       @IN_INPUT_MAN        INT              --操作员
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    SELECT @SBUSI_NAME = N'增加人工打分信息'
    SELECT @SSUMMARY = N'增加人工打分信息'
    SELECT @IBUSI_FLAG = 21004
    SELECT @V_RET_CODE = -21004000

    IF EXISTS(SELECT * FROM TMANUALSCORING WHERE OPERAND_ID = @IN_OPERAND_ID AND OPERATION_VALUE = @IN_OPERATION_VALUE)
        RETURN @V_RET_CODE - 11   --人工打分信息已存在
    BEGIN TRANSACTION
    INSERT INTO TMANUALSCORING(OPERAND_ID,OPERATION_VALUE,SCORE,INPUT_MAN)
         VALUES(@IN_OPERAND_ID,@IN_OPERATION_VALUE,@IN_SCORE,@IN_INPUT_MAN)
         
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    SELECT @SSUMMARY = N'增加人工打分信息，操作数ID：'+RTRIM(@IN_OPERAND_ID)
	
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
