USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_ADD_TLOGLIST @IN_BUSI_FLAG INT,
                                 @IN_BUSI_NAME NVARCHAR(40),
                                 @IN_INPUT_MAN INT,
                                 @IN_SUMMARY NVARCHAR(200)
WITH ENCRYPTION
AS
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
    VALUES(@IN_BUSI_FLAG,@IN_BUSI_NAME,@IN_INPUT_MAN,@IN_SUMMARY)
    RETURN 100
GO
