USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE SP_STAT_LEVEL2_DATA_STATI_4 @IN_YAER_DATE INT = 0,
                                             @IN_INPUT_MAN INT = 0

WITH ENCRYPTION
AS
DECLARE @IN_YEAR INT
SELECT @IN_YEAR = 2011
CREATE TABLE #TEMP_VIEW_TABLE(CHANNEL_UNIT     NVARCHAR(10),
                           CHANNEL_TYPE     NVARCHAR(20),
                           CHANNEL_DETAIL   NVARCHAR(60),
                           ONE_MONTH        DECIMAL(16,3),
                           TWO_MONTH        DECIMAL(16,3),
                           THREE_MONTH      DECIMAL(16,3),
                           FOUR_MONTH       DECIMAL(16,3),
                           FIVE_MONTH       DECIMAL(16,3),
                           SIX_MONTH        DECIMAL(16,3),
                           SEVEN_MONTH      DECIMAL(16,3),
                           EIGHT_MONTH      DECIMAL(16,3),
                           NINE_MONTH       DECIMAL(16,3),
                           TEN_MONTH        DECIMAL(16,3),
                           ELEVEN_MONTH     DECIMAL(16,3),
                           TWELVE_MONTH     DECIMAL(16,3)
                           )

CREATE TABLE #TMP_STAT_CHANNELTOTAL1(PRODUCT_CODE        NVARCHAR(6),
                                     PRODUCT_NAME        NVARCHAR(60),
                                     CHANNEL_TYPE        NVARCHAR(10),
                                     CHANNEL_TYPE_NAME   NVARCHAR(30),
                                     CHANNEL_ID          INT,
                                     CHANNEL_CODE        NVARCHAR(6),
                                     CHANNEL_NAME        NVARCHAR(60),
                                     DATENO              NVARCHAR(10),
                                     RG_MONEY            DEC(16,3),
                                     PARENT_CHANNEL      INT
                                    )
BEGIN
INSERT INTO #TMP_STAT_CHANNELTOTAL1(CHANNEL_TYPE,CHANNEL_ID,CHANNEL_CODE,CHANNEL_NAME,RG_MONEY,DATENO,CHANNEL_TYPE_NAME)
    SELECT ISNULL(A.CHANNEL_TYPE,''),ISNULL(A.CHANNEL_ID,0),B.CHANNEL_CODE,B.CHANNEL_NAME,SUM(A.RG_MONEY) AS RG_MONEY, A.START_DATE/10000*100+DATEPART(month,dbo.GetDateTime(A.START_DATE)) AS DATENO, E.TYPE_CONTENT AS CHANNEL_TYPE_NAME
        FROM INTRUST..TPRODUCT G,INTRUST..TCONTRACT A LEFT JOIN INTRUST..TCHANNEL B ON A.CHANNEL_ID = B.CHANNEL_ID --AND (B.CHANNEL_NAME LIKE '%'+@IN_CHANNEL_NAME+'%' OR ISNULL(@IN_CHANNEL_NAME,'') = '')
                     LEFT JOIN INTRUST..TDICTPARAM E ON A.CHANNEL_TYPE = E.TYPE_VALUE
                WHERE A.START_DATE /10000 = @IN_YEAR
                    --AND(A.CHANNEL_TYPE = @IN_CHANNEL_TYPE OR ISNULL(@IN_CHANNEL_TYPE,'') = '')
                    --AND(A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCT_IDS) OR NOT EXISTS(SELECT 1 FROM @V_PRODUCT_IDS))
                    AND(G.PRODUCT_ID = A.PRODUCT_ID)
                    AND(G.INTRUST_FLAG1 = 2)
        GROUP BY ISNULL(A.CHANNEL_TYPE,''),ISNULL(A.CHANNEL_ID,0),B.CHANNEL_CODE,B.CHANNEL_NAME,A.START_DATE/10000*100+DATEPART(month,dbo.GetDateTime(A.START_DATE)),E.TYPE_CONTENT
        ORDER BY DATENO,ISNULL(A.CHANNEL_TYPE,'');
    SELECT A.CHANNEL_TYPE,A.CHANNEL_TYPE_NAME,B.TOP_PARENT AS CHANNEL_ID,C.CHANNEL_CODE,C.CHANNEL_NAME,RIGHT(A.DATENO,2) AS DATENO,SUM(A.RG_MONEY) AS RG_MONEY,NULL AS PARENT_CHANNEL,C.CHANNEL_NAME AS FULL_NAME
        INTO #TMP_STAT_CHANNEL30
        FROM #TMP_STAT_CHANNELTOTAL1 A LEFT JOIN INTRUST..V_CHANNEL B ON A.CHANNEL_ID = B.CHANNEL_ID LEFT JOIN INTRUST..TCHANNEL C ON B.TOP_PARENT = C.CHANNEL_ID
        GROUP BY A.CHANNEL_TYPE,A.CHANNEL_TYPE_NAME,B.TOP_PARENT,C.CHANNEL_CODE,C.CHANNEL_NAME,A.DATENO
END

INSERT INTO #TEMP_VIEW_TABLE
    SELECT '渠道(万)',CASE CHANNEL_TYPE_NAME WHEN '交通银行' THEN '交行渠道' ELSE '非交行渠道' END,CHANNEL_NAME,[01] AS [M01],[02] AS [M02],[03] AS [M03],[04] AS [M04],[05] AS [M05],[06] AS [M06],[07] AS [M07],[08] AS [M08],[09] AS [M09],[10] AS [M10],[11] AS [M11],[12] AS [M12]
    FROM #TMP_STAT_CHANNEL30 PIVOT
    (
        SUM(RG_MONEY) FOR DATENO IN ([01],[02],[03],[04],[05],[06],[07],[08],[09],[10],[11],[12])
    ) AS PVT
    WHERE (CHANNEL_TYPE LIKE '550002%' OR CHANNEL_TYPE LIKE '550003%')

INSERT INTO #TEMP_VIEW_TABLE
    SELECT '小计','','',SUM(ONE_MONTH),SUM(TWO_MONTH),SUM(THREE_MONTH),SUM(FOUR_MONTH),SUM(FIVE_MONTH),SUM(SIX_MONTH),SUM(SEVEN_MONTH),SUM(EIGHT_MONTH),SUM(NINE_MONTH),SUM(TEN_MONTH),SUM(ELEVEN_MONTH),SUM(TWELVE_MONTH) FROM #TEMP_VIEW_TABLE

    --UNION ALL
INSERT INTO #TEMP_VIEW_TABLE
    SELECT '直营(万)','','',SUM([01]) AS [M01],SUM([02]) AS [M02],SUM([03]) AS [M03],SUM([04]) AS [M04],SUM([05]) AS [M05],SUM([06]) AS [M06],SUM([07]) AS [M07],SUM([08]) AS [M08],SUM([09]) AS [M09],SUM([10]) AS [M10],SUM([11]) AS [M11],SUM([12]) AS [M12]
    FROM #TMP_STAT_CHANNEL30 PIVOT
    (
        SUM(RG_MONEY) FOR DATENO IN ([01],[02],[03],[04],[05],[06],[07],[08],[09],[10],[11],[12])
    ) AS PVT
    WHERE (CHANNEL_TYPE LIKE '550001%')

 INSERT INTO #TEMP_VIEW_TABLE
       SELECT '总计','','',SUM(ONE_MONTH),SUM(TWO_MONTH),SUM(THREE_MONTH),SUM(FOUR_MONTH),SUM(FIVE_MONTH),SUM(SIX_MONTH),SUM(SEVEN_MONTH),SUM(EIGHT_MONTH),SUM(NINE_MONTH),SUM(TEN_MONTH),SUM(ELEVEN_MONTH),SUM(TWELVE_MONTH)
       FROM #TEMP_VIEW_TABLE WHERE (CHANNEL_UNIT = '小计' OR CHANNEL_UNIT = '直营(万)')
 SELECT * FROM #TEMP_VIEW_TABLE
GO
