USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_DEL_TBENCHANGES @IN_SERIAL_NO INT,
                    @IN_INPUT_MAN INT
WITH ENCRYPTION
AS
    DECLARE @V_CONTRACT_BH varchar(16),@V_CHECK_FLAG INT,@V_DF_REC_NO INT,@V_TRANS_TYPE VARCHAR(10),
            @V_TO_AMOUNT DECIMAL(16,3),@V_FROZEN_MONEY DECIMAL(16,3),@V_FROZEN_TMP DECIMAL(16,3)
    DECLARE @V_LIST_ID INT,@V_PRODUCT_ID INT
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME VARCHAR(40),@SSUMMARY VARCHAR(200)
    DECLARE @V_CHECK_FLAG2 INT
    SELECT @V_RET_CODE = -21703000
    SELECT @IBUSI_FLAG = 21703
    SELECT @SBUSI_NAME = '删除受益权转让'
    SELECT @SSUMMARY = '删除受益权转让'

    IF NOT EXISTS(SELECT * FROM INTRUST..TBENCHANGES WHERE SERIAL_NO = @IN_SERIAL_NO)
       RETURN @V_RET_CODE-1   -- 受益人转让信息不存在
    SELECT @V_CONTRACT_BH = CONTRACT_BH,@V_CHECK_FLAG = CHECK_FLAG,@V_DF_REC_NO = DF_REC_NO,@V_PRODUCT_ID = PRODUCT_ID,
           @V_TRANS_TYPE = TRANS_TYPE,@V_TO_AMOUNT = TO_AMOUNT,@V_LIST_ID = FROM_LIST_ID
        FROM INTRUST..TBENCHANGES WHERE SERIAL_NO = @IN_SERIAL_NO
    IF @V_CHECK_FLAG <> 1
       RETURN @V_RET_CODE - 2  -- 已审核不能删除

    BEGIN TRANSACTION

    --删除解押、解冻录入时，将对应的CHECK_FLAG = 2
    IF @V_TRANS_TYPE IN('181512','181514')
        --更新质押、冻结明细
        UPDATE INTRUST..TBENCHANGES SET FROZEN_TMP = ISNULL(FROZEN_TMP,0) - @V_TO_AMOUNT WHERE SERIAL_NO = @V_DF_REC_NO
    ELSE
        --PRINT '更新TBENIFITOR 记录的FROZEN_TMP'
        UPDATE INTRUST..TBENIFITOR
        SET FROZEN_TMP = ISNULL(FROZEN_TMP,0) - @V_TO_AMOUNT
        WHERE PRODUCT_ID = @V_PRODUCT_ID AND CONTRACT_BH = @V_CONTRACT_BH AND LIST_ID = @V_LIST_ID
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    DELETE FROM INTRUST..TBENCHANGES  WHERE SERIAL_NO = @IN_SERIAL_NO
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SELECT @SSUMMARY = '删除受益权转让，合同编号：'+@V_CONTRACT_BH
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
