USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_CHECK_TNONPRODUCT @IN_NONPRODUCT_ID INT,    --主键
                                      @IN_CHECK_FLAG    INT,    --1审核通过2审核不通过
                                      @IN_INPUT_MAN     INT     --录入操作员
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    SELECT @SBUSI_NAME = N'非信托产品信息审核'
    SELECT @SSUMMARY = N'非信托产品信息审核'
    SELECT @IBUSI_FLAG = 39001
    SELECT @V_RET_CODE = -39001000

    IF NOT EXISTS(SELECT 1 FROM TNONPRODUCT WHERE NONPRODUCT_ID = @IN_NONPRODUCT_ID)
        RETURN @V_RET_CODE - 11   --非信托产品信息不存在

    BEGIN TRANSACTION
    UPDATE TNONPRODUCT
    SET CHECK_FLAG = @IN_CHECK_FLAG,
        CHECK_TIME = GETDATE(),
        CHECK_MAN = @IN_INPUT_MAN
    WHERE NONPRODUCT_ID = @IN_NONPRODUCT_ID
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SET @SSUMMARY = N'非信托产品信息审核，操作员：' + CAST(@IN_INPUT_MAN AS NVARCHAR(10))
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
