USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TGAINLEVELFLAG @IN_PREPRODUCT_ID  INTEGER     --预发行产品ID
WITH ENCRYPTION 
AS
    SELECT GL.PROV_FLAG, P.CONTENT AS PROV_FLAG_NAME 
        FROM TGAINLEVEL GL, INTRUST..TINTEGERPARAM P
        WHERE GL.PROV_FLAG = P.TYPE_VALUE AND P.TYPE_ID = 3003
            AND GL.PREPRODUCT_ID = @IN_PREPRODUCT_ID
        GROUP BY GL.PROV_FLAG, P.CONTENT
GO
