USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TCOMPLAINT @IN_SERIAL			  INTEGER,				--序号
									@IN_CUST_NAME		  NVARCHAR(100),       --客户姓名
									@IN_INPUT_DATE_START  INTEGER,		        --投诉日期(起始)
									@IN_INPUT_DATE_END	  INTEGER,		        --投诉日期(终止)
									@IN_COMP_TYPE		  INTEGER,              --投诉方式:1电话；2短信；3EMAIL；4其他
									@IN_CONTENT           NVARCHAR(MAX),        --投诉内容
									@IN_DO_STATUS		  INTEGER				--处理状态:1未完成、2完成、3转给相关部门
									
WITH ENCRYPTION
AS
    SET NOCOUNT ON

    --DECLARE @V_ERROR NVARCHAR(200), @IBUSI_FLAG INT, @SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)
	IF ISNULL(@IN_INPUT_DATE_START,0) = 0
		SET @IN_INPUT_DATE_START = 20121101
    IF ISNULL(@IN_INPUT_DATE_END,0) = 0
		SET @IN_INPUT_DATE_END = 20991230
    
	SELECT * FROM TCOMPLAINT 
		WHERE (SERIAL=@IN_SERIAL OR ISNULL(@IN_SERIAL,0)=0)
		AND (CUST_NAME LIKE '%'+@IN_CUST_NAME+'%' OR ISNULL(@IN_CUST_NAME,'')='')
		AND INPUT_DATE >= @IN_INPUT_DATE_START  AND INPUT_DATE <= @IN_INPUT_DATE_END
		AND (COMP_TYPE=@IN_COMP_TYPE OR ISNULL(@IN_COMP_TYPE,0)=0)
		AND (CONTENT LIKE '%'+@IN_CONTENT+'%' OR ISNULL(@IN_CONTENT,'')='')
		AND (DO_STATUS=@IN_DO_STATUS OR ISNULL(@IN_DO_STATUS,0)=0)
		
		
GO
