USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_LOGIN_INI   @IN_OP_CODE INT
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT,@V_RET INT,@IBUSI_FLAG INT,@V_IF_MANAGER TINYINT
    DECLARE @SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    SELECT @V_RET_CODE = -11301000
    SELECT @IBUSI_FLAG = 11301
    SELECT @SBUSI_NAME = N'操作员登录做初始化'
    SELECT @SSUMMARY = N'操作员登录做初始化'

/*
    SELECT @V_IF_MANAGER = IF_MANAGER  FROM TOPERATOR WHERE OP_CODE = @IN_OP_CODE
    IF @V_IF_MANAGER = 0 AND @IN_OP_CODE <> 888
    BEGIN
        BEGIN TRANSACTION
        -------------系统初始化
        EXEC @V_RET = SP_INNER_TTASKINFO @IN_OP_CODE
        IF @@ERROR <> 0 OR @V_RET <0
        BEGIN
            ROLLBACK TRANSACTION
            RETURN -100
        END

        SELECT @SSUMMARY = N'操作员登录做初始化，操作员编号：' + CAST(@IN_OP_CODE AS CHAR(10))
        INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
            VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_OP_CODE,@SSUMMARY)
        IF @@ERROR <> 0
        BEGIN
            ROLLBACK TRANSACTION
            RETURN -100
        END

        COMMIT TRANSACTION
    END
*/

    RETURN 100
GO
