USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TMONEYDATA_PRECONTRACT
                                          @IN_PRE_SERIAL_NO  INT,            --预约表主键(EFCRM..TPRECONTRACT.SERIAL_NO)
                                          @IN_INPUT_MAN      INT             --操作员
WITH ENCRYPTION
AS
    DECLARE @V_PRODUCT_ID INT,@V_SUB_PRODUCT_ID INT,@V_CUST_ID INT,@V_PREPRODUCT_ID INT
    IF @IN_PRE_SERIAL_NO IS NULL SET @IN_PRE_SERIAL_NO = 0
    --由于预约表的记录号必需传入，访问权限就不必验证了
	
    --DECLARE @V_OPERATOR_KEY NVARCHAR(10)
    --SELECT @V_OPERATOR_KEY = Extension FROM TCustManagers WHERE ManagerID = @IN_INPUT_MAN
    --IF ISNULL(@V_OPERATOR_KEY,0) = 0
    --    SET @V_OPERATOR_KEY = @IN_INPUT_MAN
    SELECT @V_CUST_ID=CUST_ID,@V_PRODUCT_ID=PRODUCT_ID,@V_SUB_PRODUCT_ID=SUB_PRODUCT_ID,@V_PREPRODUCT_ID=PREPRODUCT_ID
      FROM TPRECONTRACT 
      WHERE SERIAL_NO=@IN_PRE_SERIAL_NO
    IF ISNULL(@V_PRODUCT_ID,0)=0
        SELECT @V_PRODUCT_ID=BIND_PRODUCT_ID FROM TPREPRODUCT WHERE PREPRODUCT_ID=@V_PREPRODUCT_ID
        
    IF ISNULL(@V_PRODUCT_ID,0)=0 --产品未绑定时
    BEGIN
		--调用预发行产品的到账明细
		--EXECUTE SP_QUERY_TPREMONEYDETAIL  0 , @IN_PRE_SERIAL_NO , 0 , 0 , 0 , N'' , N'' , @IN_INPUT_MAN , N'' , N'0'
		SELECT P.SERIAL_NO,DBO.GETDATEINT(P.DZ_DATE) DZ_DATE,P.DZ_MONEY,P.JK_TYPE,P.JK_TYPE_NAME,'TPREMONEYDETAIL' [SOURCE]
		  FROM TPREMONEYDETAIL P
		  WHERE P.PRE_SERIAL_NO=@IN_PRE_SERIAL_NO
		  
		RETURN
    END
    SELECT SERIAL_NO,DZ_DATE,TO_MONEY DZ_MONEY,JK_TYPE,JK_TYPE_NAME, 'TMONEYDATA' [SOURCE]
        FROM INTRUST..TMONEYDATA
		WHERE CUST_ID=@V_CUST_ID AND PRODUCT_ID=@V_PRODUCT_ID AND SUB_PRODUCT_ID=@V_SUB_PRODUCT_ID
    
GO
