USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_DEL_TCUSTLEVELAUTH @IN_OP_CODE        INTEGER,   --操作员
                                       @IN_PRODUCT_ID     INTEGER,   --产品ID
                                       @IN_LEVEL_VALUE_ID INTEGER,   --当前类别的分类值ID
                                       @IN_INPUT_MAN      INTEGER    --执行操作员
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    SELECT @SBUSI_NAME = N'删除认购份额、受益份额分级权限分配'
    SELECT @SSUMMARY = N'删除认购份额、受益份额分级权限分配'
    SELECT @IBUSI_FLAG = 10111
    SELECT @V_RET_CODE = -10111000

    IF NOT EXISTS(SELECT 1 FROM TCUSTLEVELAUTH WHERE OP_CODE = @IN_OP_CODE AND PRODUCT_ID = @IN_PRODUCT_ID AND LEVEL_VALUE_ID = @IN_LEVEL_VALUE_ID)
        RETURN -20702001 --记录不存在

    BEGIN TRANSACTION

    DELETE FROM TCUSTLEVELAUTH WHERE OP_CODE = @IN_OP_CODE AND PRODUCT_ID = @IN_PRODUCT_ID AND LEVEL_VALUE_ID = @IN_LEVEL_VALUE_ID
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SELECT @SSUMMARY = N'删除认购份额、受益份额分级权限分配'
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
