USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_GET_MANAGERLIST_BYNODE @IN_MANAGERID INT --给定节点标识

WITH ENCRYPTION
AS
    DECLARE @V_LEFT_ID INT,@V_RIGHT_ID INT
    IF EXISTS (SELECT 1 FROM TCustManagerTree WHERE MANAGERID=@IN_MANAGERID)
    BEGIN
        CREATE TABLE #TEMP_CUSTMANAGERTREE(
                SERIAL_NO       INT,
                MANAGERID       INT,
                MANAGERNAME     NVARCHAR(64),
                LEFT_ID         INT,
                RIGHT_ID        INT,
                LEVEL_ID        INT )
        DECLARE CUR_CUSTMANAGERTREE CURSOR FOR
                SELECT LEFT_ID,RIGHT_ID
                FROM TCustManagerTree
                WHERE MANAGERID = @IN_MANAGERID
                ORDER BY SERIAL_NO
        OPEN CUR_CUSTMANAGERTREE
            FETCH NEXT FROM CUR_CUSTMANAGERTREE INTO @V_LEFT_ID,@V_RIGHT_ID
        WHILE @@FETCH_STATUS = 0
        BEGIN
            INSERT INTO #TEMP_CUSTMANAGERTREE(SERIAL_NO,MANAGERID,MANAGERNAME,LEFT_ID,RIGHT_ID,LEVEL_ID)
                SELECT SERIAL_NO,MANAGERID,MANAGERNAME,LEFT_ID,RIGHT_ID,LEVEL_ID
                FROM TCustManagerTree WHERE LEFT_ID > @V_LEFT_ID AND LEFT_ID < @V_RIGHT_ID
                ORDER BY LEFT_ID ASC

            FETCH NEXT FROM CUR_CUSTMANAGERTREE INTO @V_LEFT_ID,@V_RIGHT_ID
        END
        DEALLOCATE CUR_CUSTMANAGERTREE

        SELECT SERIAL_NO,MANAGERID,MANAGERNAME,LEFT_ID,RIGHT_ID,LEVEL_ID
        FROM #TEMP_CUSTMANAGERTREE
        ORDER BY LEFT_ID

        DROP TABLE #TEMP_CUSTMANAGERTREE
    END
GO
