USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_ADD_TROLERIGHT  @IN_ROLE_ID INT,
                                    @IN_MENU_ID NVARCHAR(10),
                                    @IN_FUNC_ID INT,
                                    @IN_INPUT_MAN INT
WITH ENCRYPTION
AS
    DECLARE @IBUSI_FLAG INT, @V_OP_CODE INT
    DECLARE @SBUSI_NAME NVARCHAR(40)
    DECLARE @SSUMMARY NVARCHAR(200)
    SELECT @IBUSI_FLAG = 10701
    SELECT @SBUSI_NAME = N'增加角色权限'
    SELECT @SSUMMARY = N'增加角色权限'

    IF EXISTS(SELECT * FROM TROLERIGHT WHERE ROLE_ID = @IN_ROLE_ID AND MENU_ID = @IN_MENU_ID AND FUNC_ID = @IN_FUNC_ID )
    BEGIN
        RETURN 100   -- 角色权限已存在
    END
    IF @IN_MENU_ID = N'20409'
    BEGIN
        RETURN 100   -- 20409不能设置
    END

    BEGIN TRANSACTION

    INSERT INTO TROLERIGHT VALUES(@IN_ROLE_ID,@IN_MENU_ID,@IN_FUNC_ID)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    /*
--为该角色下的所有操作员添加该权限,20409(产品访问控制权除外)
    IF @IN_MENU_ID <> '20409'
    BEGIN
        DELETE FROM TOPRIGHT WHERE OP_CODE IN (SELECT OP_CODE FROM TOPERATOR WHERE ROLE_ID = @IN_ROLE_ID)
            AND MENU_ID = @IN_MENU_ID AND FUNC_ID = @IN_FUNC_ID
        IF @@ERROR <> 0
        BEGIN
            ROLLBACK TRANSACTION
            RETURN -100
        END
        INSERT INTO TOPRIGHT SELECT OP_CODE, @IN_MENU_ID, @IN_FUNC_ID FROM TOPERATOR WHERE ROLE_ID = @IN_ROLE_ID
        IF @@ERROR <> 0
        BEGIN
            ROLLBACK TRANSACTION
            RETURN -100
        END
    END
    */

    SELECT @SSUMMARY = N'增加角色权限，角色编号：' + CONVERT(NVARCHAR(8),@IN_ROLE_ID) + N'，菜单编号：' + @IN_MENU_ID + N',功能编号:' + CONVERT(CHAR(8),@IN_FUNC_ID)
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
