USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_ADD_TQuesTopic      @IN_QUES_ID             INTEGER,
                                        @IN_TOPIC_CONTENT       NVARCHAR(512),
                                        @IN_TOPIC_TYPE          NVARCHAR(8),
                                        @IN_REMARK              NVARCHAR(512),
                                        @IN_INPUT_MAN           INT = 0,         --操作员
                                        @OUT_TOPIC_ID           INT OUTPUT
WITH ENCRYPTION
AS
DECLARE @V_MAX_ID INTEGER,@V_CREATOR_NAME NVARCHAR(30),@V_QUES_NO NVARCHAR(8),@V_QUES_TITLE NVARCHAR(60),@V_TOPIC_SERIAL_NO INTEGER
DECLARE @V_RET_CODE INT, @IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)

SELECT @V_RET_CODE = -30502000, @IBUSI_FLAG = 30502
SELECT @SBUSI_NAME = N'添加问卷题目信息', @SSUMMARY = N'添加问卷题目信息'

IF NOT EXISTS(SELECT 1 FROM TQuestInfo WHERE QUES_ID = @IN_QUES_ID)
    RETURN -30502001   --问卷信息不存在

-- 生成TOPIC_ID
SELECT @OUT_TOPIC_ID = 0
SELECT @V_MAX_ID = ISNULL(MAX(TOPIC_ID),0)+1 FROM TQuesTopic
SELECT @V_QUES_NO = ISNULL(QUES_NO,''),@V_QUES_TITLE = ISNULL(QUES_TITLE,'') FROM TQuestInfo WHERE QUES_ID = @IN_QUES_ID
SELECT @V_TOPIC_SERIAL_NO = ISNULL(MAX(TOPIC_SERIAL_NO),0)+1 FROM TQuesTopic WHERE QUES_ID = @IN_QUES_ID
SELECT @V_CREATOR_NAME = OP_NAME FROM TOPERATOR WHERE OP_CODE = @IN_INPUT_MAN

BEGIN TRANSACTION
    INSERT INTO TQuesTopic (QUES_ID,QUES_NO,QUES_TITLE,TOPIC_SERIAL_NO,TOPIC_CONTENT,TOPIC_TYPE,CREATOR,CREATOR_NAME,INPUT_TIME,REMARK)
    VALUES (@IN_QUES_ID,@V_QUES_NO,@V_QUES_TITLE,@V_TOPIC_SERIAL_NO,@IN_TOPIC_CONTENT,@IN_TOPIC_TYPE,@IN_INPUT_MAN,@V_CREATOR_NAME,CONVERT(DATETIME,CONVERT(NVARCHAR(64),GETDATE(),120)),@IN_REMARK )
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SET @SSUMMARY = N'添加问卷题目信息，操作员：' + CAST(@IN_INPUT_MAN AS NVARCHAR(10))
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    SELECT @OUT_TOPIC_ID = @V_MAX_ID
COMMIT TRANSACTION
RETURN 100
GO
