USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_DEL_TNONPRODUCT @IN_NONPRODUCT_ID INT,    --主键
                                    @IN_INPUT_MAN     INT     --录入操作员

WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    SELECT @SBUSI_NAME = N'删除非信托产品信息'
    SELECT @SSUMMARY = N'删除非信托产品信息'
    SELECT @IBUSI_FLAG = 39001
    SELECT @V_RET_CODE = -39001000

    IF NOT EXISTS(SELECT * FROM TNONPRODUCT WHERE NONPRODUCT_ID = @IN_NONPRODUCT_ID)
        RETURN @V_RET_CODE - 11   --非信托产品信息不存在

    BEGIN TRANSACTION

    DELETE FROM TNONPRODUCT WHERE NONPRODUCT_ID = @IN_NONPRODUCT_ID
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SELECT @SSUMMARY = N'删除非信托产品信息：'+RTRIM(CONVERT(NVARCHAR(16),@IN_NONPRODUCT_ID))
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    COMMIT TRANSACTION
    RETURN 100
GO
