USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_MODI_TOPERATOR_MAIN_MENU @IN_OP_CODE   INT,
                                             @IN_MAIN_MENU CHAR(1) = N'0'
WITH ENCRYPTION
AS

    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    SELECT @V_RET_CODE = -10601000 ,@IBUSI_FLAG = 10601
    SELECT @SBUSI_NAME = N'修改员工缺省登录模块' ,@SSUMMARY = N'修改员工缺省登录模块'

    IF NOT EXISTS(SELECT 1 FROM TOPERATOR WHERE OP_CODE = @IN_OP_CODE)
        RETURN @V_RET_CODE - 4  --操作员不存在

    BEGIN TRANSACTION

    UPDATE TOPERATOR SET MAIN_MENU = @IN_MAIN_MENU WHERE OP_CODE = @IN_OP_CODE
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SELECT @SSUMMARY = N'修改员工缺省登录模块，员工编号：' + @IN_MAIN_MENU
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_OP_CODE,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
