USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_ADD_TACTIVITIES     @IN_ACTIVE_TYPE         NVARCHAR(16),    --活动类别
                                        @IN_ACTIVE_THEME        NVARCHAR(128),   --活动主题
                                        @IN_START_DATE          DATETIME,       --开始时间
                                        @IN_END_DATE            DATETIME,       --结束时间
                                        @IN_MANAGE_CODE         INT ,           --负责人
                                        @IN_CUSTOMER_TYPE       NVARCHAR(64),   --对应客户群
                                        @IN_ACTIVE_PLAN         NVARCHAR(256),  --活动计划与目标
                                        @IN_ACTIVE_TRACE        NVARCHAR(640),  --活动记录
                                        @IN_ACTIVE_RESULT       NVARCHAR(256),  --活动结果评价
                                        @IN_ACTIVE_FLAG         INT,            --活动标记(1 - 新建；2 - 进行中；3 - 活动结束；)
                                        @IN_COMPLETE_TIME       DATETIME,       --活动完成时间
                                        @IN_CREATOR             INT,            --活动创建人
                                        @IN_INPUT_MAN           INT = 0,         --操作员
                                        @OUT_SERIAL_NO          INT OUTPUT
WITH ENCRYPTION
AS
    DECLARE @V_ACTIVE_TYPE_NAME NVARCHAR(64),@V_MANAGE_MAN NVARCHAR(64),@V_CREATOR_NAME NVARCHAR(64),@V_ACTIVE_CODE NVARCHAR(32)
    DECLARE @V_RET_CODE INT, @IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)
    SELECT @V_RET_CODE = -30401000, @IBUSI_FLAG = 30401
    SELECT @SBUSI_NAME = N'添加营销活动记录信息', @SSUMMARY = N'添加营销活动记录信息'
    IF NOT EXISTS(SELECT 1 FROM TOPERATOR WHERE OP_CODE = @IN_MANAGE_CODE)
        RETURN -10104003   --操作员不存在

    SELECT @V_ACTIVE_TYPE_NAME = TYPE_CONTENT FROM TDICTPARAM WHERE TYPE_VALUE = @IN_ACTIVE_TYPE
    SELECT @V_ACTIVE_TYPE_NAME = ISNULL(@V_ACTIVE_TYPE_NAME,'')
    SELECT @V_MANAGE_MAN = OP_NAME FROM TOPERATOR WHERE OP_CODE = @IN_MANAGE_CODE
    SELECT @V_CREATOR_NAME = OP_NAME FROM TOPERATOR WHERE OP_CODE = @IN_CREATOR


    SELECT @V_ACTIVE_CODE = CONVERT(NVARCHAR(32),1*10000+1+ISNULL(MAX(SERIAL_NO),0)) FROM TACTIVITIES
    SELECT @V_ACTIVE_CODE = RIGHT(@V_ACTIVE_CODE,4)

    BEGIN TRANSACTION
    INSERT INTO TACTIVITIES(ACTIVE_TYPE,ACTIVE_TYPE_NAME,ACTIVE_THEME,START_DATE,END_DATE,MANAGE_CODE,MANAGE_MAN,CUSTOMER_TYPE,ACTIVE_PLAN,ACTIVE_TRACE,ACTIVE_RESULT,ACTIVE_FLAG,COMPLETE_TIME,CREATOR_NAME,CREATOR,ACTIVE_CODE)
    VALUES(@IN_ACTIVE_TYPE,@V_ACTIVE_TYPE_NAME,@IN_ACTIVE_THEME,@IN_START_DATE,@IN_END_DATE,@IN_MANAGE_CODE,@V_MANAGE_MAN,@IN_CUSTOMER_TYPE,@IN_ACTIVE_PLAN,@IN_ACTIVE_TRACE,@IN_ACTIVE_RESULT,@IN_ACTIVE_FLAG,@IN_COMPLETE_TIME,@V_CREATOR_NAME,@IN_CREATOR,@V_ACTIVE_CODE)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SET @OUT_SERIAL_NO =@@IDENTITY

    SET @SSUMMARY = N'添加营销活动记录信息，操作员：' + CAST(@IN_INPUT_MAN AS NVARCHAR(10))
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
