USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_ADD_TREMINDERS  @IN_SCHEDULE_DATE       INT,                --时间
                                    @IN_CONTENT             NVARCHAR(MAX),      --日程内容
                                    @IN_INPUT_MAN           INT = 0             --操作员
WITH ENCRYPTION
AS
    DECLARE @V_OP_NAME NVARCHAR(64)
    DECLARE @V_RET_CODE INT, @IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)
    SELECT @V_RET_CODE = -30403000, @IBUSI_FLAG = 30403
    SELECT @SBUSI_NAME = N'添加备忘录记录', @SSUMMARY = N'添加备忘录记录'

    IF NOT EXISTS(SELECT 1 FROM TOPERATOR WHERE OP_CODE = @IN_INPUT_MAN)
        RETURN -10104003 --操作员不存在

    SELECT @V_OP_NAME = OP_NAME FROM TOPERATOR WHERE OP_CODE = @IN_INPUT_MAN

    BEGIN TRANSACTION
    INSERT INTO TREMINDERS(SCHEDULE_DATE,OP_CODE,OP_NAME,CONTENT,CHECK_FLAG)
    VALUES(@IN_SCHEDULE_DATE,@IN_INPUT_MAN,@V_OP_NAME,@IN_CONTENT,1)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SET @SSUMMARY = N'添加备忘录记录，操作员：' + CAST(@IN_INPUT_MAN AS NVARCHAR(10))
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
