USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TCONTRACTLIST_DETAIL @IN_PRODUCT_ID   INT,
                                               @IN_CONTRACT_BH  VARCHAR(16),
                                               @IN_HT_STATUS    VARCHAR(10),
                                               @IN_LIST_ID      INT = 0,
                                               @IN_CONTRACT_SUB_BH  VARCHAR(50) = NULL, -- 合同编号查询  20080104 by wangc
                                               @IN_SUB_PRODUCT_ID        INT   =0    --子产品ID   20111112  LUOHH
WITH ENCRYPTION
AS
    DECLARE @V_BEN_REC_NO INT
    CREATE TABLE #TEMPLIST(BEN_REC_NO INT)
    IF @IN_LIST_ID <> 0
    BEGIN
        SELECT @V_BEN_REC_NO = SERIAL_NO  FROM INTRUST..TBENIFITOR 
            WHERE PRODUCT_ID = @IN_PRODUCT_ID AND CONTRACT_BH = @IN_CONTRACT_BH AND LIST_ID = @IN_LIST_ID
        INSERT INTO #TEMPLIST VALUES(@V_BEN_REC_NO)
        INSERT INTO #TEMPLIST SELECT SERIAL_NO FROM INTRUST..TBENIFITOR WHERE DF_BEN_REC_NO = @V_BEN_REC_NO
        SELECT A.*,0 AS LIST_ID,0.00 AS FROZEN_MONEY,'' AS CUST_NAME,'' AS PRODUCT_NAME,@IN_CONTRACT_BH AS CONTRACT_BH,C.CONTRACT_SUB_BH,D.LIST_NAME
            FROM INTRUST..TCONTRACTLIST A,#TEMPLIST B,INTRUST..TCONTRACT C LEFT JOIN TSUBPRODUCT D ON (C.SUB_PRODUCT_ID = D.SUB_PRODUCT_ID)
                WHERE A.BEN_REC_NO = B.BEN_REC_NO AND A.CONTRACT_ID = C.SERIAL_NO
        ORDER BY A.INPUT_TIME DESC
    END
    ELSE
    SELECT A.*,B.LIST_ID,B.FROZEN_MONEY,(CASE WHEN A.HT_STATUS IN('121001','121002','121003','121004','121005','121006','121007') THEN A.CUST_NAME ELSE B.CUST_NAME END) AS CUST_NAME
     FROM
        (SELECT A.*,B.PRODUCT_NAME,C.CONTRACT_BH,C.CONTRACT_SUB_BH,D.CUST_NAME,E.LIST_NAME
        FROM INTRUST..TCONTRACTLIST A,INTRUST..TPRODUCT B,INTRUST..TCONTRACT C LEFT JOIN INTRUST..TSUBPRODUCT E ON (C.SUB_PRODUCT_ID = E.SUB_PRODUCT_ID),INTRUST..TCUSTOMERINFO D
        WHERE A.CONTRACT_ID = C.SERIAL_NO AND B.PRODUCT_ID = C.PRODUCT_ID AND C.CUST_ID = D.CUST_ID 
            AND (B.PRODUCT_ID = @IN_PRODUCT_ID OR ISNULL(@IN_PRODUCT_ID,0) = 0)
            AND (C.CONTRACT_BH LIKE '%' + @IN_CONTRACT_BH + '%' OR ISNULL(@IN_CONTRACT_BH,'') = '') 
            AND (C.CONTRACT_SUB_BH LIKE '%' + @IN_CONTRACT_SUB_BH + '%' OR ISNULL(@IN_CONTRACT_SUB_BH,'') = '') 
            AND (ISNULL(@IN_SUB_PRODUCT_ID,0) =0 OR C.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID)
            AND (A.HT_STATUS = @IN_HT_STATUS OR ISNULL(@IN_HT_STATUS,'') = '')) A
    LEFT JOIN
        (SELECT A.*,B.CUST_NAME FROM INTRUST..TBENIFITOR A LEFT JOIN INTRUST..TCUSTOMERINFO B ON A.CUST_ID = B.CUST_ID ) B
    ON A.BEN_REC_NO = B.SERIAL_NO

GO
