USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE SP_QUERY_TCUSTOMERCHANGES @IN_CUST_ID INT
WITH ENCRYPTION
AS
	
   IF EXISTS(SELECT 1 FROM TSYSTEM_CTRL WHERE CTRL_TYPE='IS_SHOW_REALPHONE' AND CTRL_VALUE = '1') 
   BEGIN
	SELECT A.*,B.OP_NAME  FROM TCustomerChanges A LEFT JOIN TOPERATOR B ON  A.INPUT_MAN = B.OP_CODE 
	WHERE CUST_ID = @IN_CUST_ID 
   END
   ELSE
   BEGIN
   	SELECT A.*,B.OP_NAME  FROM TCustomerChanges A LEFT JOIN TOPERATOR B ON  A.INPUT_MAN = B.OP_CODE 
	WHERE CUST_ID = @IN_CUST_ID 
	AND a.FIELD_NAME  NOT in ('CUST_TEL','O_TEL','H_TEL','MOBILE','BP')
   END
   
GO
