USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_DICTCONTENT @IN_TYPE_VALUE NVARCHAR(10)
WITH ENCRYPTION
AS
    SELECT SERIAL_NO,TYPE_VALUE,TYPE_CONTENT, ADDITIVE_VALUE
        FROM TDICTPARAM
        WHERE TYPE_VALUE = @IN_TYPE_VALUE
GO
