USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TCOMONEYTASK   @IN_INPUT_MAN    INT   --操作人员,对应表TOPERATOR.OP_CODE
WITH ENCRYPTION

AS
    SELECT A.*
    FROM TMONEYTASKINFO A,TMONEYTASKLIST B
    WHERE A.SERIAL_NO = B.REC_NO AND B.READ_FLAG = 1
        AND B.OP_CODE = @IN_INPUT_MAN
GO
