USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TEAM_TEAMMEMBERS    @IN_TEAM_TYPE           INT = 1     --个人1，团队2

WITH ENCRYPTION
AS
    IF ISNULL(@IN_TEAM_TYPE,1) = 1
        SELECT MANAGERID,MANAGERNAME FROM TManagerTeamMembers

    ELSE IF ISNULL(@IN_TEAM_TYPE,1) = 2
        SELECT TEAM_ID,TEAM_NAME FROM TManagerTeams
GO
