USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
/*
   项目统计信息更新
*/
CREATE PROCEDURE SP_INNER_PROJECTSTAT  @IN_PROJECTID  INT,
                                       @IN_PROBLEMID  INT = 0
WITH ENCRYPTION
AS
    SET NOCOUNT ON

    DECLARE @V_TOTALPROBLEMS INT,@V_TOTALTHREADS INT,@V_TOTALRECORDS INT
    --总记录数
    SELECT @V_TOTALPROBLEMS = COUNT(*) FROM INTRUST..TPROBLEMS WHERE PROJECTID = @IN_PROJECTID AND ISDELETED = 0
    --在线记录数
    SELECT @V_TOTALTHREADS = COUNT(*) FROM INTRUST..TPROBLEMS
    WHERE PROJECTID = @IN_PROJECTID AND ISFINALSTATE = 0 AND ISDELETED = 0

    SELECT @V_TOTALRECORDS = COUNT(*) FROM INTRUST..TRECORDS WHERE PROJECTID = @IN_PROJECTID AND RECORDFLAG <> 0

    UPDATE INTRUST..TPROJECTS SET TOTALPROBLEMS = @V_TOTALPROBLEMS,TOTALTHREADS = @V_TOTALTHREADS,TOTALRECORDS = @V_TOTALRECORDS
    WHERE PROJECTID = @IN_PROJECTID
    --如果事务ID不为0，同时更新事务表的记录数字段
    IF ISNULL(@IN_PROBLEMID,0) <> 0
    BEGIN
        SELECT @V_TOTALRECORDS = 0
        SELECT @V_TOTALRECORDS = COUNT(*) FROM INTRUST..TRECORDS WHERE PROBLEMID = @IN_PROBLEMID AND RECORDFLAG <> 0
        UPDATE INTRUST..TPROBLEMS SET RECORDNUM = @V_TOTALRECORDS WHERE PROBLEMID = @IN_PROBLEMID
    END
GO
