USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TPRECONTRACT_LOAD @IN_SERIAL_NO INT
WITH ENCRYPTION
AS
    SELECT A.*, B.CUST_NO,B.CUST_NAME, B.CUST_TEL,E.PRE_CODE AS PRE_CODE2,
            CASE WHEN ISNULL(A.PRODUCT_ID,0)>0 THEN (SELECT PRODUCT_NAME FROM INTRUST..TPRODUCT WHERE PRODUCT_ID=A.PRODUCT_ID)
                ELSE (SELECT PREPRODUCT_NAME FROM TPREPRODUCT WHERE PREPRODUCT_ID=A.PREPRODUCT_ID) END AS PRODUCT_NAME
        FROM TPRECONTRACT A LEFT JOIN INTRUST..TPRECONTRACT E ON A.BIND_SERIAL_NO=E.SERIAL_NO, TCUSTOMERS B
        WHERE A.SERIAL_NO = @IN_SERIAL_NO AND A.CUST_ID = B.CUST_ID
GO
