USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_BACKUP_DATABASE @IN_FLAG INT,  --1、主数据库 2、历史数据库
                                    @IN_BACKUP_FILE   NVARCHAR(60),
                                    @IN_COMMENT       NVARCHAR(200),
                                    @IN_INPUT_MAN     INT
WITH ENCRYPTION
AS
    DECLARE @V_DATABASE_NAME NVARCHAR(100)
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    SELECT @V_RET_CODE =  -9999900, @IBUSI_FLAG  = 99999
    SELECT @SBUSI_NAME = N'备份数据库', @SSUMMARY = N'备份数据库'
    DECLARE @V_SQL NVARCHAR(2000)
    DECLARE @V_BACK_PATH NVARCHAR(2000)

    IF @IN_FLAG = 1
        SET @V_DATABASE_NAME = N'EFCRM'
    ELSE IF @IN_FLAG = 2
        SET @V_DATABASE_NAME = N'EFCRMHistory'


    SELECT TOP 1 @V_BACK_PATH = BACKUP_URL FROM TSYSTEMINFO
    IF ISNULL(@V_BACK_PATH ,'') = N''
        RETURN  -100
    ELSE
    BEGIN
        IF RIGHT(@V_BACK_PATH,1) <> '\' SET @V_BACK_PATH = @V_BACK_PATH + '\'
        SET @IN_BACKUP_FILE = @V_BACK_PATH  + '' + @IN_BACKUP_FILE
    END

    SET @V_SQL = N'backup database  '+@V_DATABASE_NAME +N' to disk='''+@IN_BACKUP_FILE+N'''' +N'WITH  INIT ,  NOUNLOAD , NAME = N' + '''' + @IN_COMMENT + ''''
    EXEC (@V_SQL)

    IF @@ERROR <> 0 RETURN - 100

    BEGIN TRANSACTION
    SELECT @SSUMMARY = N'备份数据库' + '[' + @V_DATABASE_NAME + ']'
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    COMMIT TRANSACTION
    RETURN 100
GO
