USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TCUSTOMER_VOLUE   @IN_PRODUCT_ID INT = NULL,
                                            @IN_START_TIME INT = NULL,
                                            @IN_END_TIME   INT = NULL,
                                            @IN_FLAG       INT = 2, --1按日 2按月 3按年
                                            @IN_SCOPE      INT =0,   --统计范围:0全部，1本人；2本部门
                                            @IN_INPUT_MAN  INT = NULL 
WITH ENCRYPTION
AS
    DECLARE @V_OPCODES TABLE(OP_CODE INT)
    IF @IN_SCOPE=2 --保存下本部门的客户经理列表
		INSERT INTO @V_OPCODES
			SELECT OP_CODE FROM TOPERATOR WHERE DEPART_ID=(SELECT DEPART_ID FROM TOPERATOR WHERE OP_CODE=@IN_INPUT_MAN)

    SELECT @IN_START_TIME = 0 WHERE @IN_START_TIME IS NULL
    SELECT @IN_END_TIME = 99999999 WHERE ISNULL(@IN_END_TIME,0)=0 
    SELECT @IN_PRODUCT_ID=0 WHERE @IN_PRODUCT_ID IS NULL
    SELECT @IN_FLAG=2 WHERE @IN_FLAG IS NULL OR @IN_FLAG NOT IN (1, 2, 3)
    
    IF @IN_FLAG = 1     --1按日
        SELECT  CONVERT(INT,CONVERT(CHAR(8),A.INPUT_TIME,112)) AS DATA,
                COUNT(A.IS_DEAL) AS TOTAL_COUNT,
                SUM(CASE WHEN A.IS_DEAL = 1 THEN 1 ELSE 0 END) AS TOTAL_1 ,
                SUM(CASE WHEN A.IS_DEAL = 2 THEN 1 ELSE 0 END) AS TOTAL_2
        FROM TCUSTOMERS A
        WHERE (EXISTS (SELECT * FROM INTRUST..TCONTRACT WHERE PRODUCT_ID = @IN_PRODUCT_ID AND CUST_ID=A.CUST_ID) OR @IN_PRODUCT_ID=0)
            AND (CONVERT(INT,CONVERT(CHAR(8),A.INPUT_TIME,112)) BETWEEN @IN_START_TIME AND @IN_END_TIME)
            AND (@IN_SCOPE=0 --全部
                OR @IN_SCOPE=1 AND SERVICE_MAN=@IN_INPUT_MAN --本人
                OR @IN_SCOPE=2 AND EXISTS(SELECT * FROM @V_OPCODES WHERE OP_CODE=A.SERVICE_MAN)--本部门
                )
        GROUP BY CONVERT(INT,CONVERT(CHAR(8),A.INPUT_TIME,112))
    ELSE IF @IN_FLAG = 2    --2按月
        SELECT  CONVERT(INT,CONVERT(CHAR(6),A.INPUT_TIME,112)) AS DATA,
                COUNT(A.IS_DEAL) AS TOTAL_COUNT,
                SUM(CASE WHEN A.IS_DEAL = 1 THEN 1 ELSE 0 END) AS TOTAL_1,
                SUM(CASE WHEN A.IS_DEAL = 2 THEN 1 ELSE 0 END) AS TOTAL_2
        FROM TCUSTOMERS A
        WHERE (EXISTS (SELECT * FROM INTRUST..TCONTRACT WHERE PRODUCT_ID = @IN_PRODUCT_ID AND CUST_ID=A.CUST_ID) OR @IN_PRODUCT_ID=0)
            AND (CONVERT(INT,CONVERT(CHAR(6),A.INPUT_TIME,112)) BETWEEN @IN_START_TIME/100 AND @IN_END_TIME/100)
            AND (@IN_SCOPE=0 --全部
                OR @IN_SCOPE=1 AND SERVICE_MAN=@IN_INPUT_MAN --本人
                OR @IN_SCOPE=2 AND EXISTS(SELECT * FROM @V_OPCODES WHERE OP_CODE=A.SERVICE_MAN)--本部门
                )
        GROUP BY CONVERT(INT,CONVERT(CHAR(6),A.INPUT_TIME,112))
    ELSE --IF @IN_FLAG = 3    --3按年
        SELECT  CONVERT(INT,CONVERT(CHAR(4),A.INPUT_TIME,112)) AS DATA,
                COUNT(A.IS_DEAL) AS TOTAL_COUNT, -- 增加客户量
                SUM(CASE WHEN A.IS_DEAL = 1 THEN 1 ELSE 0 END) AS TOTAL_1 , -- 事实客户
                SUM(CASE WHEN A.IS_DEAL = 2 THEN 1 ELSE 0 END) AS TOTAL_2   -- 潜在客户
        FROM TCUSTOMERS A
        WHERE (EXISTS (SELECT * FROM INTRUST..TCONTRACT WHERE PRODUCT_ID = @IN_PRODUCT_ID AND CUST_ID=A.CUST_ID) OR @IN_PRODUCT_ID=0)
            AND (CONVERT(INT,CONVERT(CHAR(4),A.INPUT_TIME,112)) BETWEEN @IN_START_TIME/10000 AND @IN_END_TIME/10000)
            AND (@IN_SCOPE=0 --全部
                OR @IN_SCOPE=1 AND SERVICE_MAN=@IN_INPUT_MAN --本人
                OR @IN_SCOPE=2 AND EXISTS(SELECT * FROM @V_OPCODES WHERE OP_CODE=A.SERVICE_MAN)--本部门
                )
        GROUP BY CONVERT(INT,CONVERT(CHAR(4),A.INPUT_TIME,112))

GO
