USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_INIT_FLOW_WORKLOG_WEEK @IN_ROLE_ID  INT
WITH ENCRYPTION
AS
	DECLARE @V_OP_CODE INT, @V_OBJECT_NO INT --操作员编号、流程关联的对象编号（即工作日志主键）
    DECLARE @V_FLOW_NO NVARCHAR(40), @V_OBJECT_TYPE NVARCHAR(40) --流程编号、流程对象类别
	DECLARE  @V_CURRENT_DATE NVARCHAR(10) --当前日期
	
    SELECT @V_FLOW_NO = 'WorkLogFLow', @V_OBJECT_TYPE = 'WorkLog'
    SELECT @V_CURRENT_DATE = CONVERT(NVARCHAR(10),CONVERT(NVARCHAR(10),GETDATE(),23)) --当前日期
    BEGIN TRANSACTION

	--定义游标
	DECLARE C1 CURSOR FOR 
		select A.OP_CODE from TOPERATOR A, TOPROLE B where A.OP_CODE = B.OP_CODE and B.ROLE_ID = @IN_ROLE_ID 
	OPEN C1				
		FETCH NEXT FROM C1 INTO @V_OP_CODE  --把从游标取得的值赋给@V_OP_CODE
		
	WHILE @@FETCH_STATUS =0 --判断游标状态
	BEGIN
		--插入工作日志表--
		
		INSERT INTO TSTAFFWORKLOG(DATE, LOG_TYPE, LOG_TYPE_NAME, LOG_STATE, INPUT_MAN)
			VALUES(@V_CURRENT_DATE, '2', '工作周报', '1020', @V_OP_CODE)
		IF @@ERROR <> 0
		BEGIN
			ROLLBACK TRANSACTION
			RETURN -100
		END
		SELECT @V_OBJECT_NO = @@IDENTITY --日志表主键

		-------初始化流程信息------
		--流程任务表--
		INSERT INTO FLOW_TASK(RELATIVE_NO,OBJECT_NO, OBJECT_TYPE,FLOW_DESC, FLOW_NO, FLOW_NAME, NODE_NO, NODE_NAME, NODE_FLAG, 
			USER_ID, USER_NAME, DEPT_ID, DEPT_NAME, BEGIN_TIME,Input_date)
		SELECT '0',@V_OBJECT_NO, @V_OBJECT_TYPE,NULL, FN.flow_no, FN.flow_name, FN.Node_no, FN.node_name, FN.node_flag, 
			@V_OP_CODE, dbo.GETUSERNAME(@V_OP_CODE), dbo.GETORGNAME(@V_OP_CODE,'OPCODEID'), dbo.GETORGNAME(@V_OP_CODE,'OPCODENAME'),
			getdate(),convert(nvarchar(10),getdate(),120)
			from FLOW_CATALOG FC,FLOW_NODE FN where FC.flow_no=FN.flow_no and FC.init_Node=FN.Node_no and FC.flow_no=@V_FLOW_NO
		IF @@ERROR <> 0
		BEGIN
			ROLLBACK TRANSACTION
			RETURN -100
		END
		
		--流程状态表--
		INSERT INTO FLOW_STATE(OBJECT_NO, OBJECT_TYPE, FLOW_NO, FLOW_NAME, NODE_NO, NODE_NAME, NODE_FLAG, 
			USER_ID,USER_NAME,DEPT_ID, DEPT_NAME, INPUT_TIME,INPUT_DATE)
		SELECT @V_OBJECT_NO, @V_OBJECT_TYPE, FN.flow_no, FN.flow_name, FN.Node_no, FN.node_name, FN.node_flag,
			@V_OP_CODE, dbo.GETUSERNAME(@V_OP_CODE) ,dbo.GETORGNAME(@V_OP_CODE,'OPCODEID') ,dbo.GETORGNAME(@V_OP_CODE,'OPCODENAME'), 
			getdate(), convert(nvarchar(10),getdate(),120)
				from FLOW_CATALOG FC,FLOW_NODE FN where FC.flow_no=FN.flow_no and FC.init_Node=FN.Node_no and FC.flow_no=@V_FLOW_NO
		IF @@ERROR <> 0
		BEGIN
			ROLLBACK TRANSACTION
			RETURN -100
		END		
		
		FETCH NEXT FROM C1 INTO @V_OP_CODE  
	END
	CLOSE C1 --循环结束关闭游标
	DEALLOCATE C1
	
    COMMIT TRANSACTION
    RETURN 100
GO
