USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_DEL_TTopicScore    @IN_SERIAL_NO           INT,
                                       @IN_INPUT_MAN           INT = 0         --操作员
WITH ENCRYPTION
AS
    DECLARE @V_TOPIC_ID INTEGER,@V_TOPIC_VALUE_NO INTEGER
    DECLARE @V_RET_CODE INT, @IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)
    SELECT @V_RET_CODE = -30503000, @IBUSI_FLAG = 30503
    SELECT @SBUSI_NAME = N'删除问卷分值表信息', @SSUMMARY = N'删除问卷分值表信息'

    IF NOT EXISTS(SELECT 1 FROM TTopicScore WHERE SERIAL_NO = @IN_SERIAL_NO)
        RETURN @V_RET_CODE - 1 --问卷题目分值表不存在

    SELECT @V_TOPIC_ID = TOPIC_ID,@V_TOPIC_VALUE_NO = TOPIC_VALUE_NO
    FROM TTopicScore WHERE SERIAL_NO = @IN_SERIAL_NO

BEGIN TRANSACTION
    UPDATE TTopicScore
    SET TOPIC_VALUE_NO = TOPIC_VALUE_NO - 1
    WHERE TOPIC_ID = @V_TOPIC_ID
        AND TOPIC_VALUE_NO IN(
            SELECT TOPIC_VALUE_NO
            FROM TTopicScore
            WHERE TOPIC_ID = @V_TOPIC_ID
                AND TOPIC_VALUE_NO > @V_TOPIC_VALUE_NO
        )
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    -- 删除问卷分值表中问卷相关信息
    DELETE FROM TTopicScore
    WHERE SERIAL_NO = @IN_SERIAL_NO
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SET @SSUMMARY = N'删除问卷分值表信息，操作员：' + CAST(@IN_INPUT_MAN AS NVARCHAR(10))
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
COMMIT TRANSACTION
    RETURN 100
GO
