USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TQUARTER_CHART	@IN_CUST_ID             NVARCHAR(600),
											@IN_BEGIN_DATE          INT,
											@IN_END_DATE            INT,
											@IN_FLAG         		INT=1, --1按年,2按月,3按季度
											@IN_PRODUCT_ID          INT=0,
											@IN_TABLE_FLAG			INT=1 --1查询已购买的金额，2查询存量金额
WITH ENCRYPTION
AS
    SET NOCOUNT ON
	CREATE TABLE #TMP_QUERY_CustByClass(DATEMONTH INT,TOTAL_MONEY DEC(16,3),QUERTER_FLAG INT)
	CREATE TABLE #TMP_BENIFITOR(PRODUCT_ID INT,CUST_ID INT,TO_AMOUNT DEC(16,3),BEN_AMOUNT DEC(16,3),BEN_DATE INT)
	
	DECLARE @V_LOOP INT
	DECLARE @V_SQL NVARCHAR(2000)
	
	SET  @IN_BEGIN_DATE = @IN_BEGIN_DATE/10000
	SET	 @IN_END_DATE = @IN_END_DATE/10000
	
	INSERT INTO #TMP_BENIFITOR
		SELECT PRODUCT_ID,CUST_ID,TO_AMOUNT,BEN_AMOUNT,BEN_DATE FROM INTRUST..TBENIFITOR
		WHERE (PRODUCT_ID = @IN_PRODUCT_ID OR ISNULL(@IN_PRODUCT_ID,0)=0)
	
	IF @IN_TABLE_FLAG = 1--已购买金额
	BEGIN
		IF @IN_FLAG=1 --按年
		BEGIN
			WHILE  @IN_BEGIN_DATE<=@IN_END_DATE
			BEGIN
				INSERT INTO #TMP_QUERY_CustByClass(DATEMONTH,TOTAL_MONEY) VALUES(@IN_BEGIN_DATE,0.00) 
				SET @IN_BEGIN_DATE = @IN_BEGIN_DATE+1
			END	
			SET @V_SQL = 'UPDATE #TMP_QUERY_CustByClass SET TOTAL_MONEY = C.TO_AMOUNT'+
				' FROM #TMP_QUERY_CustByClass A,(SELECT B.BEN_DATE/10000 AS BEN_DATE,SUM(B.BEN_AMOUNT) AS TO_AMOUNT FROM #TMP_BENIFITOR B WHERE B.CUST_ID IN('+@IN_CUST_ID+') GROUP BY B.BEN_DATE/10000)C '+
				' WHERE A.DATEMONTH = C.BEN_DATE'
			EXECUTE(@V_SQL)		
		END
		ELSE IF @IN_FLAG=2--按季度
		BEGIN 
			WHILE @IN_BEGIN_DATE <= @IN_END_DATE
			BEGIN
				SET @V_LOOP = 1
				WHILE @V_LOOP <= 4
				BEGIN
					INSERT INTO #TMP_QUERY_CustByClass(DATEMONTH,TOTAL_MONEY,QUERTER_FLAG) SELECT @IN_BEGIN_DATE,0.00,@V_LOOP
					SET @V_LOOP = @V_LOOP + 1
				END
				SELECT @IN_BEGIN_DATE = @IN_BEGIN_DATE + 1
			END	
			
			SET @V_SQL = 'UPDATE #TMP_QUERY_CustByClass SET TOTAL_MONEY = C.TO_MONEY '+
				' FROM  #TMP_QUERY_CustByClass A,(SELECT BEN_DATE/10000 AS BEN_YEAR,SUM(TO_AMOUNT) AS TO_MONEY,CASE RIGHT(BEN_DATE,2)/4 '+  
				' WHEN 0 THEN 1 WHEN 1 THEN 2 WHEN 2 THEN 3 ELSE 4 END AS ''QUERTER'' FROM #TMP_BENIFITOR WHERE CUST_ID IN('+@IN_CUST_ID+') GROUP BY BEN_DATE ) C '+
				' WHERE A.DATEMONTH =	C.BEN_YEAR	AND A.QUERTER_FLAG = C.QUERTER '
			EXECUTE(@V_SQL)		
		END
		ELSE IF @IN_FLAG=3--按月
		BEGIN
			WHILE @IN_BEGIN_DATE <= @IN_END_DATE
			BEGIN
				SET @V_LOOP = 1
				WHILE @V_LOOP <= 12
				BEGIN
					INSERT INTO #TMP_QUERY_CustByClass(DATEMONTH,TOTAL_MONEY) SELECT @IN_BEGIN_DATE*100+@V_LOOP,0.00
					SET @V_LOOP = @V_LOOP + 1
				END
				SELECT @IN_BEGIN_DATE = @IN_BEGIN_DATE + 1
			END	
			SET @V_SQL = 'UPDATE #TMP_QUERY_CustByClass SET TOTAL_MONEY = B.TO_AMOUNT FROM #TMP_QUERY_CustByClass A, '+
			' (SELECT BEN_DATE/100 AS BEN_DATE,SUM(TO_AMOUNT) AS TO_AMOUNT FROM #TMP_BENIFITOR WHERE CUST_ID IN('+@IN_CUST_ID+') GROUP BY BEN_DATE/100)B '+
			' WHERE A.DATEMONTH = B.BEN_DATE '
			EXECUTE(@V_SQL)
		END
	END
	ELSE IF @IN_TABLE_FLAG = 2--存量金额
	BEGIN
		IF @IN_FLAG=1 --按年
		BEGIN
			WHILE  @IN_BEGIN_DATE<=@IN_END_DATE
			BEGIN
				INSERT INTO #TMP_QUERY_CustByClass(DATEMONTH,TOTAL_MONEY) VALUES(@IN_BEGIN_DATE,0.00) 
				SET @IN_BEGIN_DATE = @IN_BEGIN_DATE+1
			END	
			SET @V_SQL = 'UPDATE #TMP_QUERY_CustByClass SET TOTAL_MONEY = C.TO_AMOUNT'+
				' FROM #TMP_QUERY_CustByClass A,(SELECT B.BEN_DATE/10000 AS BEN_DATE,SUM(B.BEN_AMOUNT) AS TO_AMOUNT FROM #TMP_BENIFITOR B WHERE B.CUST_ID IN('+@IN_CUST_ID+') GROUP BY B.BEN_DATE/10000)C '+
				' WHERE A.DATEMONTH = C.BEN_DATE'
			EXECUTE(@V_SQL)		
		END
		ELSE IF @IN_FLAG=2--按季度
		BEGIN 
			WHILE @IN_BEGIN_DATE <= @IN_END_DATE
			BEGIN
				SET @V_LOOP = 1
				WHILE @V_LOOP <= 4
				BEGIN
					INSERT INTO #TMP_QUERY_CustByClass(DATEMONTH,TOTAL_MONEY,QUERTER_FLAG) SELECT @IN_BEGIN_DATE,0.00,@V_LOOP
					SET @V_LOOP = @V_LOOP + 1
				END
				SELECT @IN_BEGIN_DATE = @IN_BEGIN_DATE + 1
			END	
			
			SET @V_SQL = 'UPDATE #TMP_QUERY_CustByClass SET TOTAL_MONEY = C.TO_MONEY '+
				' FROM  #TMP_QUERY_CustByClass A,(SELECT BEN_DATE/10000 AS BEN_YEAR,SUM(BEN_AMOUNT) AS TO_MONEY,CASE RIGHT(BEN_DATE,2)/4 '+  
				' WHEN 0 THEN 1 WHEN 1 THEN 2 WHEN 2 THEN 3 ELSE 4 END AS ''QUERTER'' FROM #TMP_BENIFITOR WHERE CUST_ID IN('+@IN_CUST_ID+') GROUP BY BEN_DATE ) C '+
				' WHERE A.DATEMONTH =	C.BEN_YEAR	AND A.QUERTER_FLAG = C.QUERTER '
			EXECUTE(@V_SQL)		
		END
		ELSE IF @IN_FLAG=3--按月
		BEGIN
			WHILE @IN_BEGIN_DATE <= @IN_END_DATE
			BEGIN
				SET @V_LOOP = 1
				WHILE @V_LOOP <= 12
				BEGIN
					INSERT INTO #TMP_QUERY_CustByClass(DATEMONTH,TOTAL_MONEY) SELECT @IN_BEGIN_DATE*100+@V_LOOP,0.00
					SET @V_LOOP = @V_LOOP + 1
				END
				SELECT @IN_BEGIN_DATE = @IN_BEGIN_DATE + 1
			END	
			SET @V_SQL = 'UPDATE #TMP_QUERY_CustByClass SET TOTAL_MONEY = B.TO_AMOUNT FROM #TMP_QUERY_CustByClass A, '+
			' (SELECT BEN_DATE/100 AS BEN_DATE,SUM(BEN_AMOUNT) AS TO_AMOUNT FROM #TMP_BENIFITOR WHERE CUST_ID IN('+@IN_CUST_ID+') GROUP BY BEN_DATE/100)B '+
			' WHERE A.DATEMONTH = B.BEN_DATE '
			EXECUTE(@V_SQL)
		END
	END
	SELECT DATEMONTH AS INTERVAL_FIELD,QUERTER_FLAG AS CUST_NUM,TOTAL_MONEY FROM #TMP_QUERY_CustByClass

GO
