USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_MODI_TQuestInfo     @IN_QUES_ID             INTEGER,
                                        @IN_QUES_NO             NVARCHAR(8),    --问卷编号
                                        @IN_QUES_TITLE          NVARCHAR(60),   --问卷题目
                                        @IN_QUES_TYPE           NVARCHAR(16),
                                        @IN_REMARK              NVARCHAR(512),
                                        @IN_INPUT_MAN           INT = 0         --操作员
WITH ENCRYPTION
AS
DECLARE @V_MAX_ID INTEGER,@V_QUES_NO NVARCHAR(8),@V_QUES_TYPE_NAME NVARCHAR(60)
DECLARE @V_RET_CODE INT, @IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)

SELECT @V_RET_CODE = -30501000, @IBUSI_FLAG = 30501
SELECT @SBUSI_NAME = N'修改问卷信息', @SSUMMARY = N'修改问卷信息'

SELECT @V_QUES_TYPE_NAME = TYPE_CONTENT FROM TDICTPARAM WHERE TYPE_VALUE = @IN_QUES_TYPE

-- 生成QUES_ID
SELECT @V_MAX_ID = ISNULL(MAX(QUES_ID),0)+ 1 FROM TQuestInfo

-- 生成问卷编号
IF @IN_QUES_NO IS NULL OR @IN_QUES_NO = N''
    BEGIN
        SELECT @V_QUES_NO = CONVERT(CHAR(3), ISNULL(@IN_QUES_TYPE,0)*100 + @V_MAX_ID)
    END
ELSE
    BEGIN
        IF EXISTS(SELECT * FROM TQuestInfo WHERE QUES_NO = @IN_QUES_NO)
            RETURN @V_RET_CODE - 1  --问卷编号已存在
        SELECT @V_QUES_NO = @IN_QUES_NO
    END
BEGIN TRANSACTION
    UPDATE TQuestInfo
    SET QUES_NO = @V_QUES_NO,
        QUES_TITLE = @IN_QUES_TITLE,
        QUES_TYPE = @IN_QUES_TYPE,
        QUES_TYPE_NAME = @V_QUES_TYPE_NAME,
        REMARK = @IN_REMARK
    WHERE QUES_ID = @IN_QUES_ID
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SET @SSUMMARY = N'修改问卷信息，操作员：' + CAST(@IN_INPUT_MAN AS NVARCHAR(10))
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
COMMIT TRANSACTION
RETURN 100

GO
