USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TGAINLEVELRATE_CRM @IN_PRODUCT_ID   INTEGER,        --产品ID
                                         @IN_SUB_PRODUCT_ID   INTEGER         --子产品ID
WITH ENCRYPTION 
AS
    IF EXISTS (SELECT * FROM INTRUST..TGAINLEVEL A WHERE PRODUCT_ID=@IN_PRODUCT_ID AND SUB_PRODUCT_ID>0) --以子产品为单位定义收益级别              
        SELECT GL.PROV_FLAG
            , (SELECT CONTENT FROM INTRUST..TINTEGERPARAM WHERE TYPE_ID=3003 AND TYPE_VALUE=GL.PROV_FLAG) AS PROV_FLAG_NAME
            , GL.PROV_LEVEL, GL.PROV_LEVEL_NAME
            , GL.LOWER_LIMIT, GL.UPPER_LIMIT
            ,(SELECT GAIN_RATE FROM INTRUST..TGAINLEVELRATE WHERE DF_SERIAL_NO=GL.SERIAL_NO AND END_DATE=MAX(GLR.END_DATE)) AS GAIN_RATE
          FROM INTRUST..TGAINLEVEL GL LEFT JOIN INTRUST..TGAINLEVELRATE GLR ON GLR.DF_SERIAL_NO=GL.SERIAL_NO
          WHERE GL.PRODUCT_ID = @IN_PRODUCT_ID AND GL.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID
          GROUP BY GL.SERIAL_NO,GL.PROV_FLAG, GL.PROV_LEVEL, GL.PROV_LEVEL_NAME, GL.LOWER_LIMIT, GL.UPPER_LIMIT
          ORDER BY GL.PROV_FLAG, GL.PROV_LEVEL
    ELSE -- 以产品为单位定义收益级别
        SELECT GL.PROV_FLAG
            , (SELECT CONTENT FROM INTRUST..TINTEGERPARAM WHERE TYPE_ID=3003 AND TYPE_VALUE=GL.PROV_FLAG) AS PROV_FLAG_NAME
            , GL.PROV_LEVEL, GL.PROV_LEVEL_NAME
            , GL.LOWER_LIMIT, GL.UPPER_LIMIT
            ,(SELECT GAIN_RATE FROM INTRUST..TGAINLEVELRATE WHERE DF_SERIAL_NO=GL.SERIAL_NO AND END_DATE=MAX(GLR.END_DATE)) AS GAIN_RATE
          FROM INTRUST..TGAINLEVEL GL LEFT JOIN INTRUST..TGAINLEVELRATE GLR ON GLR.DF_SERIAL_NO=GL.SERIAL_NO
          WHERE GL.PRODUCT_ID = @IN_PRODUCT_ID 
          GROUP BY GL.SERIAL_NO,GL.PROV_FLAG, GL.PROV_LEVEL, GL.PROV_LEVEL_NAME, GL.LOWER_LIMIT, GL.UPPER_LIMIT
          ORDER BY GL.PROV_FLAG, GL.PROV_LEVEL
GO
