USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_SERACH_TFAQS @IN_FAQ_KEYWORDS VARCHAR(200),
								 @IN_INPUT_MAN INT 
WITH ENCRYPTION
AS
		IF @IN_FAQ_KEYWORDS = ''
		BEGIN
			SELECT * FROM TFAQS
		END
		ELSE
		BEGIN
			
			IF EXISTS (SELECT * FROM TFAQS
					WHERE FAQ_TITLE LIKE '%'+@IN_FAQ_KEYWORDS+'%' OR FAQ_KEYWORDS LIKE '%' + @IN_FAQ_KEYWORDS + '%' OR
							FAQ_CONTENT LIKE '%' + @IN_FAQ_KEYWORDS + '%')
				UPDATE TFAQS SET MATCH_TIMES = MATCH_TIMES + 1 
					WHERE  FAQ_TITLE LIKE '%'+@IN_FAQ_KEYWORDS+'%' OR FAQ_KEYWORDS LIKE '%' + @IN_FAQ_KEYWORDS + '%' OR
							FAQ_CONTENT LIKE '%' + @IN_FAQ_KEYWORDS + '%' 
			SELECT * FROM TFAQS
					WHERE FAQ_TITLE LIKE '%'+@IN_FAQ_KEYWORDS+'%' OR FAQ_KEYWORDS LIKE '%' + @IN_FAQ_KEYWORDS + '%' OR
							FAQ_CONTENT LIKE '%' + @IN_FAQ_KEYWORDS + '%'
		END
GO
