USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
--DROP PROCEDURE SP2_QUERY_TEAMID_OPCODE
CREATE PROCEDURE SP2_QUERY_TEAMID_OPCODE
					@IN_INPUT_MAN         INT         --操作员
					
WITH ENCRYPTION
AS
    IF EXISTS (SELECT 1 FROM TManagerTeams WHERE LEADER=@IN_INPUT_MAN)
    BEGIN
		SELECT TEAM_ID,TEAM_NAME,TEAM_NO,LEADER,LEADER_NAME FROM TManagerTeams WHERE LEADER=@IN_INPUT_MAN
		RETURN
	END
	--IF EXISTS (SELECT 1 FROM TManagerTeams WHERE TEAM_ID=(SELECT TOP 1 TEAM_ID FROM TManagerTeamMembers WHERE MANAGERID=@IN_INPUT_MAN))
	BEGIN
        SELECT TEAM_ID,TEAM_NAME,TEAM_NO,LEADER,LEADER_NAME FROM TManagerTeams WHERE TEAM_ID=(SELECT TOP 1 TEAM_ID FROM TManagerTeamMembers WHERE MANAGERID=@IN_INPUT_MAN)
		RETURN
	END
	--ELSE
	--	SELECT -1 TEAM_ID,'' TEAM_NAME,'' TEAM_NO,0 LEADER,'' LEADER_NAME
		
GO
