USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TCUSTMANAGERCHANGES   @IN_SERIAL_NO           INT,                --序列号
                                                @IN_MANAGERNAME_BEFORE  NVARCHAR(64)='',    --前客户经理名称
                                                @IN_MANAGERNAME_NOW     NVARCHAR(64)='',    --现客户经理名称
                                                @IN_CHECK_FLAG          INT = 0,            --审核标志 1未审核2审核通过3审核不通过
                                                @IN_INPUT_MAN           INT = NULL,         --操作员
                                                @IN_FLAG1               INT = 1             --标志: 0查全部 1仅操作员有审核权限时才返回待审核记录（20140123：此参数不用）
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    DECLARE @V_HAS_CHECK INT
    IF EXISTS(SELECT 1 FROM TOPROLE A, TROLERIGHT B WHERE A.ROLE_ID = B.ROLE_ID AND B.MENU_ID = '40105' AND B.FUNC_ID = '100' AND OP_CODE = @IN_INPUT_MAN)
        SET @V_HAS_CHECK = 1
    ELSE
        SET @V_HAS_CHECK = 0
    IF @IN_SERIAL_NO <> 0
        SELECT A.SERIAL_NO, A.CUST_ID, A.MANAGERID_BEFORE, A.MANAGERNAME_BEFORE, A.MANAGERID_NOW, A.MANAGERNAME_NOW, A.CHECK_FLAG, A.CHECK_MAN, B.CUST_NAME
			FROM TCUSTMANAGERCHANGES A LEFT JOIN TCustomers B ON A.CUST_ID=B.CUST_ID
			WHERE SERIAL_NO = @IN_SERIAL_NO 
				--AND ((@IN_FLAG1 = 1 AND @V_HAS_CHECK = 1 AND CHECK_FLAG = 1) OR (@IN_FLAG1 = 1 AND CHECK_FLAG <> 1) OR (@IN_FLAG1 = 0))
    ELSE
        SELECT A.SERIAL_NO, A.CUST_ID, A.MANAGERID_BEFORE, A.MANAGERNAME_BEFORE, A.MANAGERID_NOW, A.MANAGERNAME_NOW, A.CHECK_FLAG, A.CHECK_MAN, B.CUST_NAME
			FROM TCUSTMANAGERCHANGES A LEFT JOIN TCustomers B ON A.CUST_ID=B.CUST_ID
			WHERE (MANAGERNAME_BEFORE LIKE '%' + @IN_MANAGERNAME_BEFORE + '%' OR ISNULL(@IN_MANAGERNAME_BEFORE,'') = N'')
				AND (MANAGERNAME_NOW LIKE '%' + @IN_MANAGERNAME_NOW + '%' OR ISNULL(@IN_MANAGERNAME_NOW,'') = N'')
				AND (A.CHECK_FLAG = @IN_CHECK_FLAG OR ISNULL(@IN_CHECK_FLAG,0) = 0 )
				AND @V_HAS_CHECK = 1 --有查询权限
    RETURN 100
GO
