USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TDEPARTMENT @IN_DEPART_ID     INT,
                                      @IN_PARENT_ID     INT,
                                      @IN_BOTTOM_FLAG   INT,
                                      @IN_OP_CODE       INT = 0   --add  by luohh 20090316
WITH ENCRYPTION
AS
    SET NOCOUNT ON

    SELECT A.* FROM TDEPARTMENT A
        WHERE (A.DEPART_ID = @IN_DEPART_ID OR @IN_DEPART_ID IS NULL OR @IN_DEPART_ID = 0)
            AND(A.PARENT_ID = @IN_PARENT_ID OR @IN_PARENT_ID IS NULL OR @IN_PARENT_ID = 0)
            AND(A.BOTTOM_FLAG = @IN_BOTTOM_FLAG OR @IN_BOTTOM_FLAG IS NULL OR @IN_BOTTOM_FLAG = 0)
            AND(EXISTS(SELECT 1 FROM TOPERATOR B WHERE B.DEPART_ID = A.DEPART_ID AND OP_CODE = @IN_OP_CODE)
                OR @IN_OP_CODE IS NULL OR @IN_OP_CODE = 0)
GO
