USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TCustomer_ByCardID @IN_CARD_TYPE      NVARCHAR(10),
                                             @IN_CARD_ID        NVARCHAR(30),
                                             @IN_CUST_ID        INT,
                                             @IN_INPUT_MAN      INT
WITH ENCRYPTION
AS
    DECLARE @IN_CARD_ID18 NVARCHAR(18)
    IF EXISTS(SELECT * FROM TSYSCONTROL WHERE FLAG_TYPE = N'A_CARDID' AND VALUE = 1)
    BEGIN
        IF LEN(@IN_CARD_ID)=15   --15位身份证号码转18位
            SELECT @IN_CARD_ID18 = dbo.IDCARD15TO18(@IN_CARD_ID)
        ELSE IF LEN(@IN_CARD_ID)=18 --18位转成15位
            SELECT @IN_CARD_ID18 = dbo.IDCARD18TO15(@IN_CARD_ID)
    END
    SELECT @IN_CARD_ID18 = ISNULL(@IN_CARD_ID18, @IN_CARD_ID)

    SELECT CUST_ID,CUST_NO,CUST_NAME,CARD_TYPE,CARD_TYPE_NAME,CARD_ID
        ,(SELECT OP_NAME FROM TOPERATOR WHERE OP_CODE=TCustomers.SERVICE_MAN) SERVICE_MAN_NAME,CUST_TYPE_NAME,O_TEL,H_TEL,MOBILE,E_MAIL
        ,POST_ADDRESS,POST_CODE
    FROM TCustomers
    WHERE (CUST_ID <> @IN_CUST_ID OR ISNULL(@IN_CUST_ID,0) = 0)
        AND (CARD_TYPE = @IN_CARD_TYPE OR ISNULL(@IN_CARD_TYPE,'') = '')
        AND (CARD_ID LIKE '%'+@IN_CARD_ID+'%' OR CARD_ID LIKE '%'+@IN_CARD_ID18+'%' OR @IN_CARD_ID IS NULL OR @IN_CARD_ID = N'')
        AND ((CHECK_FLAG = 2 AND STATUS = N'112801') OR (STATUS = N'112803'))
GO
