USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TCustomersDel @IN_CUST_ID    INT,
										@IN_CUST_NAME  NVARCHAR(80),
										@IN_CARD_ID    NVARCHAR(40)
WITH ENCRYPTION
AS
	SELECT CUST_ID,CUST_NO,CUST_NAME,CARD_ID,IS_DEAL,CUST_TYPE_NAME,CUST_SOURCE_NAME FROM TCustomers WHERE (CUST_ID = @IN_CUST_ID OR ISNULL(@IN_CUST_ID,0) = 0)
																								AND (CUST_NAME LIKE '%'+@IN_CUST_NAME+'%' OR ISNULL(@IN_CUST_NAME,'') = '')
																								AND (CARD_ID LIKE '%'+@IN_CARD_ID +'%' OR ISNULL(@IN_CARD_ID,'') = '')
																								AND (STATUS = '112805');
GO
