USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_STAT_CHANNELBUYDETAIL @IN_CELL_ID       	INTEGER,        --产品单元ID
                                          @IN_CHANNEL_TYPE  	NVARCHAR(10),   --渠道类别
                                          @IN_CHANNEL_NAME  	NVARCHAR(200),  --渠道机构名称
                                          @IN_BEGIN_DATE    	INTEGER,        --起始日期
                                          @IN_END_DATE      	INTEGER,        --截止日期
                                          @IN_CUST_ID       	INT = NULL,     --客户ID
                                          @IN_PRODUCT_ID    	INT = NULL,     --产品ID
                                          @IN_CHANNEL_ID    	INT = NULL,     --渠道ID
                                          @IN_SALE_MAN      	INT = NULL,     --销售人员ID
                                          @IN_SERVICE_MAN   	INT = NULL,     --客户经理ID
										  @IN_SUB_PRODUCT_ID	INT = 0 		--子产品ＩＤ
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    IF @IN_END_DATE = 0 SET @IN_END_DATE = NULL
    DECLARE @V_DT_INTRUST INT
    SELECT @V_DT_INTRUST = VALUE FROM TSYSCONTROL WHERE FLAG_TYPE = N'DT_INTRUST'
    --处理产品单元，如果@IN_CELL_ID参数有效，@V_PRODUCT_IDS中才有记录
    DECLARE @V_PRODUCT_IDS TABLE(PRODUCT_ID INT)
    DECLARE @V_CELLALL TABLE(CELL_ID      INT,
                             CELL_CODE    NVARCHAR(10),
                             CELL_NAME    NVARCHAR(60),
                             CELL_TYPE    INT,
                             PRODUCT_ID   INT,
                             PRODUCT_CODE NVARCHAR(6),
                             PRODUCT_NAME NVARCHAR(60))
    IF @IN_CELL_ID IS NOT NULL AND @IN_CELL_ID <> 0
    BEGIN
        
		INSERT INTO @V_CELLALL(CELL_ID,CELL_CODE,CELL_NAME,PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME)
			SELECT SERIAL_NO,CELL_CODE,CELL_NAME,PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME FROM INTRUST..TPRODUCT_CELL
			WHERE SERIAL_NO = @IN_CELL_ID
        WHILE @@ROWCOUNT > 0
        BEGIN
			INSERT INTO @V_CELLALL(CELL_ID)
				SELECT A.SUB_CELL_ID
				FROM  INTRUST..TPRODUCT_CELL_DETAIL A, @V_CELLALL B
				WHERE A.DF_SERIAL_NO = B.CELL_ID AND A.SUB_CELL_ID NOT IN(SELECT CELL_ID FROM @V_CELLALL)
        END
        
		UPDATE @V_CELLALL
			SET CELL_CODE = B.CELL_CODE,
				CELL_NAME = B.CELL_NAME,
				CELL_TYPE = B.CELL_TYPE,
				PRODUCT_ID = B.PRODUCT_ID,
				PRODUCT_CODE = B.PRODUCT_CODE,
				PRODUCT_NAME = B.PRODUCT_NAME
			FROM @V_CELLALL A , INTRUST..TPRODUCT_CELL B
			WHERE A.CELL_ID = B.SERIAL_NO
        INSERT INTO @V_PRODUCT_IDS(PRODUCT_ID) SELECT PRODUCT_ID FROM @V_CELLALL WHERE CELL_TYPE = 1 GROUP BY PRODUCT_ID
    END
    --界面上没提供产品单元作查询条件，提供的是产品列表，暂时修改一下这里，取传入产品的数据
    DELETE FROM @V_PRODUCT_IDS
    IF @IN_CELL_ID IS NOT NULL AND @IN_CELL_ID <> 0
        INSERT INTO @V_PRODUCT_IDS VALUES(@IN_CELL_ID)

    CREATE TABLE #TEMP_STAT_CHANNELBUYDETAIL (
        PRODUCT_ID          INT,
        PRODUCT_CODE        nvarchar(6) NULL,
        PRODUCT_NAME        nvarchar(60) NULL,
        CHANNEL_TYPE        nvarchar(10) NULL,
        CHANNEL_ID          int NULL,
        CHANNEL_CODE        nvarchar(6) NULL,
        CHANNEL_NAME        nvarchar(60) NULL,
        CHANNEL_MEMO        nvarchar(200) NULL,
        CUST_ID             int NULL,
        CUST_NAME           nvarchar(100) NULL,
        START_DATE          int NULL,
        RG_MONEY            decimal(16, 3) NOT NULL,
        CHANNEL_TYPE_NAME   nvarchar(256) NULL,
        PROV_LEVEL_NAME     nvarchar(30) NULL,
        CHANNEL_FARE        DEC(16,3),
        TOP_CHANNEL_NAME    NVARCHAR(200),
        SALE_MAN            INT,
        SALE_MAN_NAME       NVARCHAR(30),
        SERVICE_MAN         INT,
        SERVICE_MAN_NAME    NVARCHAR(30),
        CONTRACT_SUB_BH     NVARCHAR(60)
    )
	
    BEGIN
        INSERT INTO #TEMP_STAT_CHANNELBUYDETAIL(PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,CHANNEL_TYPE,CHANNEL_ID,CHANNEL_CODE,CHANNEL_NAME,CHANNEL_MEMO,CUST_ID,CUST_NAME,START_DATE,RG_MONEY,CHANNEL_TYPE_NAME,PROV_LEVEL_NAME,TOP_CHANNEL_NAME,SALE_MAN,SERVICE_MAN,CONTRACT_SUB_BH)
        SELECT A.PRODUCT_ID,A.PRODUCT_CODE, C.PRODUCT_NAME, A.CHANNEL_TYPE,A.CHANNEL_ID,B.CHANNEL_CODE,B.CHANNEL_NAME,A.CHANNEL_MEMO,A.CUST_ID,D.CUST_NAME,A.START_DATE,A.RG_MONEY,E.TYPE_CONTENT AS CHANNEL_TYPE_NAME,A.PROV_LEVEL_NAME,B.FULL_NAME,A.LINK_MAN,A.SERVICE_MAN,A.CONTRACT_SUB_BH
        FROM INTRUST..TCONTRACT A LEFT JOIN INTRUST..V_CHANNEL B ON A.CHANNEL_ID = B.CHANNEL_ID
             LEFT JOIN INTRUST..TDICTPARAM E ON A.CHANNEL_TYPE = E.TYPE_VALUE,
             INTRUST..TPRODUCT C, INTRUST..TCUSTOMERINFO D
        WHERE A.PRODUCT_ID = C.PRODUCT_ID AND A.CUST_ID = D.CUST_ID
            AND A.START_DATE BETWEEN @IN_BEGIN_DATE AND ISNULL(@IN_END_DATE,30001231)
            AND(A.CHANNEL_TYPE = @IN_CHANNEL_TYPE OR ISNULL(@IN_CHANNEL_TYPE,'') = '')
            AND(A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCT_IDS) OR NOT EXISTS(SELECT 1 FROM @V_PRODUCT_IDS))
            AND(A.PRODUCT_ID = @IN_PRODUCT_ID OR ISNULL(@IN_PRODUCT_ID,0) = 0)
            AND(A.CUST_ID = @IN_CUST_ID OR ISNULL(@IN_CUST_ID,0) = 0)
            AND(D.SERVICE_MAN = @IN_SERVICE_MAN OR ISNULL(@IN_SERVICE_MAN,0) = 0)
            AND(A.LINK_MAN = @IN_SALE_MAN OR ISNULL(@IN_SALE_MAN,0) = 0)
            AND(B.TOP_PARENT = @IN_CHANNEL_ID OR ISNULL(@IN_CHANNEL_ID,0) = 0)
			AND(A.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID OR ISNULL(@IN_SUB_PRODUCT_ID,0)=0)
        ORDER BY A.PRODUCT_ID,A.START_DATE
        UPDATE #TEMP_STAT_CHANNELBUYDETAIL SET SALE_MAN_NAME = B.OP_NAME
            FROM #TEMP_STAT_CHANNELBUYDETAIL A, INTRUST..TOPERATOR B
            WHERE A.SALE_MAN = B.OP_CODE
        UPDATE #TEMP_STAT_CHANNELBUYDETAIL SET SERVICE_MAN_NAME = B.OP_NAME
            FROM #TEMP_STAT_CHANNELBUYDETAIL A, INTRUST..TOPERATOR B
            WHERE A.SERVICE_MAN = B.OP_CODE
    END
    UPDATE #TEMP_STAT_CHANNELBUYDETAIL
        SET CHANNEL_FARE = A.RG_MONEY * B.CHANNEL_FARE_RATE
        FROM #TEMP_STAT_CHANNELBUYDETAIL A, EFCRM..TPRODUCT B
        WHERE A.PRODUCT_ID = B.PRODUCT_ID AND A.CHANNEL_ID = B.CHANNEL_ID
    UPDATE #TEMP_STAT_CHANNELBUYDETAIL SET SALE_MAN = NULL WHERE SALE_MAN = 0
    UPDATE #TEMP_STAT_CHANNELBUYDETAIL SET SERVICE_MAN = NULL WHERE SERVICE_MAN = 0
    SELECT * FROM #TEMP_STAT_CHANNELBUYDETAIL
        WHERE ISNULL(TOP_CHANNEL_NAME,'') LIKE '%'+ISNULL(@IN_CHANNEL_NAME,'')+'%'
GO
