USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE SP_QUERY_TDIRECTSENDDETAIL @IN_SERIAL_NO      INT,
                                            @IN_SMS_SERIAL_NO  INTEGER,               --TDIRECTSENDTOTAL.SERIAL_NO
										    @IN_INPUT_MAN      INT

WITH ENCRYPTION
AS

	--判断是否显示真实信息
	DECLARE @V_IS_SHOW_REALPHONE NVARCHAR(50)
	SELECT @V_IS_SHOW_REALPHONE=A.CTRL_VALUE FROM TSYSTEM_CTRL A WHERE A.CTRL_TYPE='IS_SHOW_REALPHONE'
	
	IF ISNULL(@V_IS_SHOW_REALPHONE,'0') = '1' 
		BEGIN
			IF ISNULL(@IN_SERIAL_NO,0) <> 0
				SELECT A.*,B.CUST_NAME,B.MOBILE,B.BP,B.E_MAIL FROM TDIRECTSENDDETAIL A,TCustomers B
					WHERE A.SERIAL_NO =@IN_SERIAL_NO AND A.CUST_ID =B.CUST_ID
			ELSE
				SELECT A.*,B.CUST_NAME,B.MOBILE,B.BP,B.E_MAIL FROM TDIRECTSENDDETAIL A,TCustomers B
					WHERE (ISNULL(@IN_SMS_SERIAL_NO,0) =0 OR A.SEND_SERIAL_NO = @IN_SMS_SERIAL_NO)
						AND A.CUST_ID =B.CUST_ID
		END
	ELSE
		BEGIN
			IF ISNULL(@IN_SERIAL_NO,0) <> 0
				SELECT A.*,B.CUST_NAME,TR.TC_TEL AS MOBILE,NULL AS BP,B.E_MAIL FROM TDIRECTSENDDETAIL A,TCustomers B 
				--隐藏号码显示
				LEFT JOIN TNUMBER_RELATION TR ON TR.FK_TCUSTOMERS=B.CUST_ID 
					WHERE A.SERIAL_NO =@IN_SERIAL_NO AND A.CUST_ID =B.CUST_ID
			ELSE
				SELECT A.*,B.CUST_NAME,TR.TC_TEL AS MOBILE,NULL AS BP,B.E_MAIL FROM TDIRECTSENDDETAIL A,TCustomers B 
				--隐藏号码显示
				LEFT JOIN TNUMBER_RELATION TR ON TR.FK_TCUSTOMERS=B.CUST_ID 
					WHERE (ISNULL(@IN_SMS_SERIAL_NO,0) =0 OR A.SEND_SERIAL_NO = @IN_SMS_SERIAL_NO)
						AND A.CUST_ID =B.CUST_ID
		END
GO
