USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_MODI_TCUSTOMERINFO @IN_CUST_ID                  INTEGER,                    --1.客户ID
                                       @IN_CUST_NAME                NVARCHAR(100),              --2.客户名称
                                       @IN_CUST_TEL                 NVARCHAR(20),               --3.客户电话
                                       @IN_POST_ADDRESS             NVARCHAR(200),              --4.联系地址
                                       @IN_POST_CODE                NVARCHAR(6),                --5.邮编
                                       @IN_CARD_TYPE                NVARCHAR(10),               --6.证件类型
                                       @IN_CARD_ID                  NVARCHAR(40),               --7.证件号
                                       @IN_AGE                      INTEGER,                    --8.年龄
                                       @IN_SEX                      INTEGER,                    --9.性别:1男2女
                                       @IN_O_TEL                    NVARCHAR(20),               --0.办公电话
                                       @IN_H_TEL                    NVARCHAR(20),               --11.家庭电话
                                       @IN_MOBILE                   NVARCHAR(100),              --12.手机
                                       @IN_BP                       NVARCHAR(60),               --13.BP机
                                       @IN_FAX                      NVARCHAR(20),               --14.传真
                                       @IN_E_MAIL                   NVARCHAR(30),               --15.E-mail地址
                                       @IN_CUST_TYPE                INTEGER,                    --16.客户类型:1个人、2机构
                                       @IN_TOUCH_TYPE               NVARCHAR(10),               --17.联系方式（1109）
                                       @IN_CUST_SOURCE              NVARCHAR(10),               --18.客户来源（1110）
                                       @IN_SUMMARY                  NVARCHAR(200),              --19.备注
                                       @IN_INPUT_MAN                INTEGER,                    --20.操作员
                                       @IN_CUST_NO                  NVARCHAR(8),                --21.客户编号
                                       @IN_LEGAL_MAN                NVARCHAR(20),               --22.法人代表
                                       @IN_LEGAL_ADDRESS            NVARCHAR(60),               --23.法人代表地址
                                       @IN_BIRTHDAY                 INTEGER,                    --24.生日
                                       @IN_POST_ADDRESS2            NVARCHAR(60),               --25.联系地址2
                                       @IN_POST_CODE2               NVARCHAR(6),                --26.邮编2
                                       @IN_PRINT_DEPLOY_BILL        INTEGER,                    --27.
                                       @IN_PRINT_POST_INFO          INTEGER,                    --28.
                                       @IN_IS_LINK                  INTEGER,                    --29.
                                       @IN_SERVICE_MAN              INTEGER         = NULL,     --30.客户经理
                                       @IN_VIP_CARD_ID              NVARCHAR(20)    = NULL,     --31.VIP卡编号
                                       @IN_VIP_DATE                 INTEGER         = NULL,     --32.VIP发卡日期
                                       @IN_HGTZR_BH                 NVARCHAR(20)    = NULL,     --33.合格投资人编号
                                       @IN_VOC_TYPE                 NVARCHAR(10)    = '',       --34.个人职业/机构行业类别(1142/2142)
                                       @IN_CARD_VALID_DATE          INTEGER         = NULL,     --35.客户身份证件有效期限8位日期表示
                                       @IN_COUNTRY                  NVARCHAR(10)    = NULL,     --36.客户国籍(9901)
                                       @IN_JG_CUST_TYPE             NVARCHAR(10)    = NULL,     --37.机构客户类别(9921)，仅在CUST_TYPE=2机构时有效
                                       @IN_CONTACT_MAN              NVARCHAR(30)    = NULL,     --38.机构客户联系人
                                       @IN_MONEY_SOURCE             NVARCHAR(300)   = NULL,     --39.资金来源
                                       @IN_FACT_CONTROLLER          NVARCHAR(100)   = NULL,     --40.实际控制人
                                       @IN_LINK_TYPE                INTEGER         = NULL,     --41. 关联类型（1302）
                                       @IN_LINK_GD_MONEY            DECIMAL(16,3)   = 0,        --42.股东投资入股信托公司金额
                                       @IN_GRADE_LEVEL              VARCHAR(10)     = '320301', --43.风险等级
                                       @IN_COMPLETE_FLAG            INTEGER         = NULL,     --44.资料完整标志 1完整 2不完整 默认2
                                       @IN_GOV_PROV_REGIONAL        NVARCHAR(10)    = NULL,     --45.省级行政区域
                                       @IN_GOV_REGIONAL             NVARCHAR(10)    = NULL,     --46.行政区域
                                       @IN_LEGAL_TEL                NVARCHAR(20)    = NULL,     --47.法人固定电话
                                       @IN_LEGAL_MOBILE             NVARCHAR(20)    = NULL,     --48.法人手机
                                       @IN_ISSUED_ORG               NVARCHAR(100)   = NULL,     --49.发证机关
                                       @IN_INDUSTRY_POST            NVARCHAR(10)    = NULL,     --50.行业岗位
                                       @IN_CUST_INDUSTRY            NVARCHAR(10)    = NULL,     --51.行业
                                       @IN_CUST_CORP_NATURE         NVARCHAR(10)    = NULL,     --52.客户单位性质
                                       @IN_CORP_BRANCH              NVARCHAR(60)    = NULL,     --53.信托分支机构
                                       @IN_SERVICE_MAN_TEL          NVARCHAR(20)    = NULL,     --54.客户经理电话
                                       @IN_GRADE_SCORE              NVARCHAR(10)    = NULL,     --55.风险测评得分
                                       @IN_FC_CARD_TYPE             NVARCHAR(10)    = NULL,     --56.实际控制人 证件类型
                                       @IN_FC_CARD_ID               NVARCHAR(40)    = NULL,     --57.实际控制人 证件有号
                                       @IN_FC_CARD_VALID_DATE       INTEGER         = NULL,     --58.实际控制人 证件有效期
                                       @IN_SUMMARY1                 NVARCHAR(200)   = NULL,     --59.备注1
                                       @IN_SUMMARY2                 NVARCHAR(200)   = NULL,     --60.备注2
                                       @IN_LEGAL_POST_CODE          NVARCHAR(6)     = NULL,     --61.法人邮编
                                       @IN_TRANS_NAME               NVARCHAR(20)    = NULL,     --62.经办人姓名
                                       @IN_TRANS_TEL                NVARCHAR(20)    = NULL,     --63.经办人固定电话
                                       @IN_TRANS_MOBILE             NVARCHAR(20)    = NULL,     --64.经办人手机
                                       @IN_TRANS_ADDRESS            NVARCHAR(120)   = NULL,     --65.经办人地址
                                       @IN_TRANS_POST_CODE          NVARCHAR(6)     = NULL,     --66.经办人邮编
                                       @IN_REGISTER_ADDRESS         NVARCHAR(120)   = NULL,     --67.注册地址
                                       @IN_REGISTER_POST_CODE       NVARCHAR(6)     = NULL,     --68.注册地邮编
                                       @IN_EAST_JG_TYPE             NVARCHAR(12)	='',		--机构类型2109（依据EAST委托人类型WTRLX）
									   @IN_JG_WTRLX2                NVARCHAR(2)		=''			--机构有效：1金融性公司 2政府 3非金融性公司 4境外金融性公司
                                    
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    DECLARE @V_ERROR NVARCHAR(200),@V_MODI_CHECK_FLAG INT, @V_PinYinSimple NVARCHAR(100)
    DECLARE @V_STATUS NVARCHAR(10),@V_STATUS_NAME NVARCHAR(30),@V_CHECK_FLAG INT,@V_BOOK_CODE INT, @V_TEMP1 INT
    DECLARE @V_VOC_TYPE_NAME NVARCHAR(30),@V_CARD_TYPE_NAME NVARCHAR(30),@V_TOUCH_TYPE_NAME NVARCHAR(30),@V_CUST_SOURCE_NAME NVARCHAR(30)
    DECLARE @V_CUST_TYPE_NAME NVARCHAR(10),@V_SEX_NAME NVARCHAR(10)
    DECLARE @OLD_CUST_NAME NVARCHAR(100), @OLD_CUST_NO NVARCHAR(8), @OLD_IS_LINK INT
    DECLARE @OLD_CUST_TEL NVARCHAR(20),@OLD_O_TEL NVARCHAR(20),@OLD_H_TEL NVARCHAR(20),@OLD_MOBILE NVARCHAR(20),@OLD_BP NVARCHAR(60),@OLD_FAX NVARCHAR(20)
    DECLARE @OLD_POST_ADDRESS NVARCHAR(60), @OLD_POST_ADDRESS2 NVARCHAR(60)
    DECLARE @OLD_POST_CODE NVARCHAR(6), @OLD_POST_CODE2 NVARCHAR(6), @OLD_SERVICE_MAN INT
    DECLARE @OLD_CARD_TYPE NVARCHAR(10),@OLD_CUST_TYPE_NAME NVARCHAR(10),@OLD_CUST_SOURCE NVARCHAR(10),@OLD_TOUCH_TYPE NVARCHAR(10)
    DECLARE @OLD_VOC_TYPE_NAME NVARCHAR(30),@OLD_CARD_TYPE_NAME NVARCHAR(30),@OLD_EMAIL NVARCHAR(30),@OLD_CUST_SOURCE_NAME NVARCHAR(30),@OLD_TOUCH_TYPE_NAME NVARCHAR(30)
    DECLARE @OLD_CARD_ID NVARCHAR(40), @OLD_LEGAL_MAN NVARCHAR(20), @OLD_LEGAL_ADDRESS NVARCHAR(60), @V_CUST_LEVEL NVARCHAR(10)
    DECLARE @OLD_SEX INT,@OLD_CUST_TYPE INT, @OLD_BIRTHDAY INT, @V_LIST_ID INT
    DECLARE @OLD_SEX_NAME NVARCHAR(2), @OLD_PRINT_DEPLOY_BILL INT, @OLD_PRINT_POST_INFO INT
    DECLARE @OLD_SUMMARY NVARCHAR(200)
    DECLARE @OLD_EAST_JG_TYPE NVARCHAR(10),@OLD_EAST_JG_TYPE_NAME NVARCHAR(50),@OLD_JG_WTRLX2 NVARCHAR(2)
    DECLARE @OLD_VIP_CARD_ID NVARCHAR(20),@OLD_VIP_DATE INT,@OLD_HGTZR_BH NVARCHAR(20)
    DECLARE @OLD_LEGAL_TEL NVARCHAR(20),@OLD_LEGAL_MOBILE NVARCHAR(20),@OLD_ISSUED_ORG NVARCHAR(100),@OLD_INDUSTRY_POST NVARCHAR(100),@OLD_MONEY_SOURCE NVARCHAR(300)
    DECLARE @OLD_FACT_CONTROLLER NVARCHAR(100),@OLD_FC_CARD_TYPE NVARCHAR(10),@OLD_FC_CARD_ID NVARCHAR(40),@OLD_FC_CARD_VALID_DATE INTEGER
    DECLARE @OLD_TRANS_NAME NVARCHAR(20),@OLD_TRANS_CARD_TYPE NVARCHAR(10),@OLD_TRANS_CARD_NAME NVARCHAR(60)
    DECLARE @OLD_TRANS_CARD_NO NVARCHAR(18),@OLD_TRANS_TEL NVARCHAR(20),@OLD_TRANS_MOBILE NVARCHAR(20)
    DECLARE @OLD_TRANS_ADDRESS NVARCHAR(120),@OLD_TRANS_POST_CODE NVARCHAR(6)
    DECLARE @OLD_SERVICE_MAN_TEL NVARCHAR(20),@OLD_GOV_PROV_REGIONAL NVARCHAR(200),@OLD_GOV_REGIONAL NVARCHAR(200)
    
    DECLARE @OLD_JG_CUST_TYPE NVARCHAR(10)
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT
    DECLARE @V_GRADE_LEVEL_NAME NVARCHAR(30),@V_EAST_JG_TYPE_NAME NVARCHAR(100)
    DECLARE @SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    DECLARE @V_GOV_PROV_REGIONAL_NAME  NVARCHAR(30)     --省级行政区域说明
    DECLARE @V_GOV_REGIONAL_NAME       NVARCHAR(30)     --行政区域说明
    DECLARE @V_MONEY_SOURCE_NAME  NVARCHAR(30) --信托资金来源说明
    DECLARE @V_CUST_INDUSTRY_NAME NVARCHAR(30),@V_CUST_CORP_NATURE_NAME NVARCHAR(30),@V_INDUSTRY_POST_NAME NVARCHAR(30)
    DECLARE @V_USER_ID INT,@V_CRNM NVARCHAR(120),@V_PCNM NVARCHAR(120),@V_PROJECTID INT, @V_CUST_DETAIL_SERIAL_NO INT    
    DECLARE @V_PROBLEMTYPEID INT, @V_PROBLEMSTATEID INT,@V_RET INT, @V_TITLE NVARCHAR(2000), @V_DESCRIPTION NVARCHAR(2000)
    DECLARE @V_PROBLEMSEVERITYID INT,@V_PROBLEMPRIORITYID INT, @V_PROBLEMID INT,@V_APPLY_DATE INT,@V_DEADLINE INT,@V_CUST_MANAGER INT

    BEGIN TRY
    BEGIN TRANSACTION

    SELECT @V_USER_ID = USER_ID FROM TSYSTEMINFO
    SELECT @V_RET_CODE = -20602000,@IBUSI_FLAG = 20602
    SELECT @SBUSI_NAME = N'修改客户基本信息',@SSUMMARY = N'修改客户基本信息'

    IF NOT EXISTS(SELECT 1 FROM TCustomers WHERE CUST_ID = @IN_CUST_ID) BEGIN
       RAISERROR('指定客户不存在，请检查！',16,1)
       --RETURN @V_RET_CODE-1   -- 客户编号不存在
    END
	SET @V_BOOK_CODE = 1 
    SELECT @V_STATUS = STATUS,@V_CHECK_FLAG = CHECK_FLAG FROM TCustomers WHERE CUST_ID = @IN_CUST_ID
    IF @V_STATUS = '112805' BEGIN
        RAISERROR('已销户不能修改，请检查！',16,1)
        --RETURN @V_RET_CODE - 2  -- 已销户不能修改
    END

    IF EXISTS(SELECT 1 FROM TSYSCONTROL WHERE FLAG_TYPE = 'A_CARDID' AND VALUE = 1) BEGIN
        IF @IN_CARD_TYPE = '110801' AND LEN(@IN_CARD_ID)=15   --15位身份证号码转18位
            SELECT @IN_CARD_ID = dbo.IDCARD15TO18(@IN_CARD_ID)
    END
    SELECT @V_CARD_TYPE_NAME = TYPE_CONTENT FROM TDICTPARAM  WHERE TYPE_VALUE = @IN_CARD_TYPE
    IF EXISTS ( SELECT 1 FROM TCustomers WHERE CARD_TYPE = @IN_CARD_TYPE AND 
                                                  CARD_ID = @IN_CARD_ID AND CUST_ID <> @IN_CUST_ID AND STATUS <> '112805') AND
       EXISTS(SELECT 1 FROM TSYSCONTROL WHERE FLAG_TYPE = 'CUSTCARD' AND VALUE = 1) BEGIN
        SET @V_ERROR = '指定的证件已存在!证件类型：' + @V_CARD_TYPE_NAME + '，证件号：' + @IN_CARD_ID
        RAISERROR(@V_ERROR,16,2)
        --RETURN @V_RET_CODE - 3 --该身份证号已存在
    END
    SET @V_PinYinSimple = dbo.fGetPy(@IN_CUST_NAME)

    SELECT @OLD_CUST_NAME = CUST_NAME,@OLD_CUST_TEL = CUST_TEL,@OLD_POST_ADDRESS = POST_ADDRESS,@OLD_POST_CODE = POST_CODE,
           @OLD_CARD_TYPE = CARD_TYPE,@OLD_CARD_TYPE_NAME = CARD_TYPE_NAME,@OLD_CARD_ID = CARD_ID,@OLD_SEX = SEX,@OLD_SEX_NAME = SEX_NAME,
           @OLD_O_TEL = O_TEL,@OLD_H_TEL = H_TEL,@OLD_MOBILE = MOBILE,@OLD_BP = BP,@OLD_FAX = FAX,@OLD_EMAIL = E_MAIL,
           @OLD_CUST_TYPE = CUST_TYPE,@OLD_CUST_TYPE_NAME = CUST_TYPE_NAME,@OLD_TOUCH_TYPE = TOUCH_TYPE,@OLD_TOUCH_TYPE_NAME = TOUCH_TYPE_NAME,
           @OLD_CUST_SOURCE = CUST_SOURCE,@OLD_CUST_SOURCE_NAME = CUST_SOURCE_NAME,@OLD_SUMMARY = SUMMARY, @OLD_CUST_NO = CUST_NO,
           @OLD_LEGAL_MAN = LEGAL_MAN, @OLD_LEGAL_ADDRESS = LEGAL_ADDRESS, @OLD_POST_ADDRESS2 = POST_ADDRESS2,
           @OLD_POST_CODE2 = POST_CODE2, @V_LIST_ID = LIST_ID,
           @OLD_PRINT_DEPLOY_BILL = PRINT_DEPLOY_BILL, @OLD_PRINT_POST_INFO = PRINT_POST_INFO, @OLD_IS_LINK = IS_LINK,
           @OLD_SERVICE_MAN = SERVICE_MAN,@OLD_VIP_CARD_ID = VIP_CARD_ID,@OLD_VIP_DATE = VIP_DATE,@OLD_HGTZR_BH = HGTZR_BH,
           @OLD_VOC_TYPE_NAME = VOC_TYPE_NAME,
           @OLD_MONEY_SOURCE = MONEY_SOURCE,
           @OLD_FACT_CONTROLLER = FACT_CONTROLLER,@OLD_FC_CARD_TYPE=FC_CARD_TYPE,@OLD_FC_CARD_ID=FC_CARD_ID,@OLD_FC_CARD_VALID_DATE=FC_CARD_VALID_DATE,
           @OLD_JG_CUST_TYPE=JG_CUST_TYPE,
           @OLD_TRANS_NAME=TRANS_NAME,@OLD_TRANS_CARD_TYPE=TRANS_CARD_TYPE,@OLD_TRANS_CARD_NAME=TRANS_CARD_NAME,
           @OLD_TRANS_CARD_NO=TRANS_CARD_NO,@OLD_TRANS_TEL=TRANS_TEL,@OLD_TRANS_MOBILE=TRANS_MOBILE,
           @OLD_TRANS_ADDRESS=TRANS_ADDRESS,@OLD_TRANS_POST_CODE=TRANS_POST_CODE,
           @OLD_EAST_JG_TYPE = EAST_JG_TYPE,@OLD_EAST_JG_TYPE_NAME =EAST_JG_TYPE_NAME ,@OLD_JG_WTRLX2 =JG_WTRLX2
           ,@OLD_GOV_PROV_REGIONAL=GOV_PROV_REGIONAL,@OLD_GOV_REGIONAL=GOV_REGIONAL
        FROM TCustomers WHERE CUST_ID = @IN_CUST_ID
    --CRM表中不存在的字段
    SELECT @V_CUST_LEVEL = CUST_LEVEL,@OLD_LEGAL_TEL = LEGAL_TEL,@OLD_LEGAL_MOBILE = LEGAL_MOBILE,@OLD_ISSUED_ORG = ISSUED_ORG
			,@OLD_INDUSTRY_POST = INDUSTRY_POST
		FROM INTRUST..TCUSTOMERINFO WHERE CUST_ID = @IN_CUST_ID
	--客户经理电话
	IF ISNULL(@IN_SERVICE_MAN_TEL,'')<>''
	BEGIN
		--如果是手机号码
		IF LEN(@IN_SERVICE_MAN_TEL)=11 AND @IN_SERVICE_MAN_TEL NOT LIKE '0%'
			SELECT @OLD_SERVICE_MAN_TEL=MOBILE FROM TOPERATOR WHERE OP_CODE=@IN_SERVICE_MAN
		ELSE
			SELECT @OLD_SERVICE_MAN_TEL=O_TEL FROM TOPERATOR WHERE OP_CODE=@IN_SERVICE_MAN
	END
	
	--当@@IN_EAST_JG_TYPE和@IN_JG_WTRLX2参数值空值时，不做更新，为了防止把原有的数据覆盖掉。其实在界面中已先把值取出来了
	IF ISNULL(@IN_EAST_JG_TYPE,'') = ''
		SET @IN_EAST_JG_TYPE = @OLD_EAST_JG_TYPE
	IF ISNULL(@IN_JG_WTRLX2,'') = ''
		SET @IN_JG_WTRLX2 = @OLD_JG_WTRLX2
	
    IF @IN_SERVICE_MAN IS NULL OR @IN_SERVICE_MAN = 0 SELECT @IN_SERVICE_MAN = @OLD_SERVICE_MAN
    
/*
    IF LEN(@IN_CUST_NO) = 8
        SELECT @IN_CUST_NO = LEFT(@OLD_CUST_NO,1) + RIGHT(@IN_CUST_NO,7)
    ELSE
    BEGIN
        IF @IN_CUST_TYPE = 1
        BEGIN
            IF @V_CUST_LEVEL = '111102'
            BEGIN
                SELECT @IN_CUST_NO = CONVERT(CHAR(8), @IN_CUST_TYPE * 10000000 + @V_LIST_ID)
                SELECT @IN_CUST_NO = 'V' + RIGHT(@IN_CUST_NO,7)
            END
            ELSE
            BEGIN
                SELECT @V_TEMP1 = ISNULL(COUNT(*),0) FROM TPRODUCT
                    WHERE PRODUCT_ID IN ( SELECT PRODUCT_ID FROM TBENIFITOR WHERE CUST_ID = @IN_CUST_ID
                            AND BEN_AMOUNT > 0 )
                IF @V_TEMP1 > 9
                    SELECT @V_TEMP1 = 9
                SELECT @IN_CUST_NO = CONVERT(CHAR(8), @IN_CUST_TYPE * 10000000 + @V_LIST_ID)
                SELECT @IN_CUST_NO = CONVERT(CHAR(1),@V_TEMP1) + RIGHT(@IN_CUST_NO,7)
            END
        END
        ELSE IF @IN_CUST_TYPE = 2
        BEGIN
            SELECT @IN_CUST_NO = CONVERT(CHAR(8), @IN_CUST_TYPE * 10000000 + @V_LIST_ID)
            SELECT @IN_CUST_NO = 'J' + RIGHT(@IN_CUST_NO,7)
        END
    END
*/
/*     IF @IN_CUST_NO IS NULL OR @IN_CUST_NO = ''
        SELECT @IN_CUST_NO = @OLD_CUST_NO
    ELSE
    BEGIN
          IF EXISTS(SELECT 1 FROM TCUSTOMERINFO WHERE BOOK_CODE = @V_BOOK_CODE AND CUST_NO = @IN_CUST_NO AND CUST_ID <> @IN_CUST_ID)
            RETURN @V_RET_CODE - 5  --该帐套内客户编号已经存在
    END */
    IF @V_STATUS = '112801' AND @V_CHECK_FLAG = 2
       SELECT @V_STATUS = '112803'

    SELECT @V_STATUS_NAME = TYPE_CONTENT FROM TDICTPARAM  WHERE TYPE_VALUE = @V_STATUS
    IF @IN_CUST_TYPE = 1
       SELECT @V_CUST_TYPE_NAME = N'个人'
    ELSE
       SELECT @V_CUST_TYPE_NAME = N'机构'

    IF @IN_SEX = 1
       SELECT @V_SEX_NAME = N'男'
    ELSE
       SELECT @V_SEX_NAME = N'女'

    IF ISNULL(@IN_TOUCH_TYPE,'') = '' SELECT @IN_TOUCH_TYPE = '110901'
    SELECT @V_TOUCH_TYPE_NAME = TYPE_CONTENT FROM TDICTPARAM  WHERE TYPE_VALUE = @IN_TOUCH_TYPE
    IF ISNULL(@IN_CUST_SOURCE,'') = '' SELECT @IN_CUST_SOURCE = '111004'
    SELECT @V_CUST_SOURCE_NAME = TYPE_CONTENT FROM TDICTPARAM  WHERE TYPE_VALUE = @IN_CUST_SOURCE

    SELECT @V_VOC_TYPE_NAME = TYPE_CONTENT FROM TDICTPARAM  WHERE TYPE_VALUE = @IN_VOC_TYPE
    --风险等级
    IF ISNULL(@IN_GRADE_LEVEL,'') =''
    BEGIN
        IF @V_USER_ID = 21  --金汇要求风险等级可以不填写
            SELECT @IN_GRADE_LEVEL = ''
        ELSE
            SELECT @IN_GRADE_LEVEL = '320301'
    END
    
    IF @IN_GRADE_LEVEL = ''
        SELECT @V_GRADE_LEVEL_NAME = ''
    ELSE
        SELECT @V_GRADE_LEVEL_NAME = ISNULL(TYPE_CONTENT,'') FROM TDICTPARAM WHERE TYPE_VALUE = @IN_GRADE_LEVEL
    SELECT @V_GOV_PROV_REGIONAL_NAME = TYPE_CONTENT FROM TDICTPARAM WHERE TYPE_VALUE = @IN_GOV_PROV_REGIONAL
    SELECT @V_GOV_REGIONAL_NAME = TYPE_CONTENT FROM TDICTPARAM WHERE TYPE_VALUE = @IN_GOV_REGIONAL
    SELECT @V_MONEY_SOURCE_NAME = TYPE_CONTENT FROM TDICTPARAM WHERE TYPE_VALUE = @IN_MONEY_SOURCE
    SELECT @V_CUST_INDUSTRY_NAME = TYPE_CONTENT FROM TDICTPARAM WHERE TYPE_VALUE = @IN_CUST_INDUSTRY
    SELECT @V_CUST_CORP_NATURE_NAME = TYPE_CONTENT FROM TDICTPARAM WHERE TYPE_VALUE = @IN_CUST_CORP_NATURE
    SELECT @V_INDUSTRY_POST_NAME = TYPE_CONTENT FROM TDICTPARAM WHERE TYPE_VALUE = @IN_INDUSTRY_POST
    --查找机构类型名称
    SELECT @V_EAST_JG_TYPE_NAME = TYPE_CONTENT FROM TDICTPARAM WHERE TYPE_VALUE = @IN_EAST_JG_TYPE
    --客户信息变更审核 1是 2否
	IF EXISTS (SELECT 1 FROM TSYSCONTROL WHERE FLAG_TYPE='CUSTINFO_CHANGE' AND VALUE=1)
		SET @V_MODI_CHECK_FLAG =1
	ELSE SET @V_MODI_CHECK_FLAG=0
    --------------------修改tcustinfodetail表---------------------
    IF LTRIM(RTRIM(@OLD_CUST_NAME)) <> LTRIM(RTRIM(@IN_CUST_NAME))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'CUST_NAME',N'客户名称',@OLD_CUST_NAME,@IN_CUST_NAME,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END

    IF LTRIM(RTRIM(@OLD_CUST_TEL)) <> LTRIM(RTRIM(@IN_CUST_TEL))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'CUST_TEL',N'联系电话',@OLD_CUST_TEL,@IN_CUST_TEL,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END

    IF LTRIM(RTRIM(@OLD_POST_ADDRESS)) <> LTRIM(RTRIM(@IN_POST_ADDRESS))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'POST_ADDRESS',N'邮寄地址',@OLD_POST_ADDRESS,@IN_POST_ADDRESS,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END

    IF LTRIM(RTRIM(@OLD_POST_ADDRESS2)) <> LTRIM(RTRIM(@IN_POST_ADDRESS2))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'POST_ADDRESS2',N'邮寄地址2',@OLD_POST_ADDRESS2,@IN_POST_ADDRESS2,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END

    IF LTRIM(RTRIM(@OLD_POST_CODE)) <> LTRIM(RTRIM(@IN_POST_CODE))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'POST_CODE',N'邮政编码',@OLD_POST_CODE,@IN_POST_CODE,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END

    IF LTRIM(RTRIM(@OLD_POST_CODE2)) <> LTRIM(RTRIM(@IN_POST_CODE2))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'POST_CODE2',N'邮政编码2',@OLD_POST_CODE2,@IN_POST_CODE2,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END

    IF LTRIM(RTRIM(@OLD_CARD_TYPE_NAME)) <> LTRIM(RTRIM(@V_CARD_TYPE_NAME))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'CARD_TYPE_NAME',N'证件类型',@OLD_CARD_TYPE_NAME,@V_CARD_TYPE_NAME,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END

    IF LTRIM(RTRIM(@OLD_CARD_ID)) <> LTRIM(RTRIM(@IN_CARD_ID))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'CARD_ID',N'证件号码',@OLD_CARD_ID,@IN_CARD_ID,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END

    IF @OLD_SEX <> @IN_SEX
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'SEX_NAME',N'性别',@OLD_SEX_NAME,@V_SEX_NAME,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END

    IF LTRIM(RTRIM(@OLD_O_TEL)) <> LTRIM(RTRIM(@IN_O_TEL))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'O_TEL',N'单位电话',@OLD_O_TEL,@IN_O_TEL,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END

    IF LTRIM(RTRIM(@OLD_H_TEL)) <> LTRIM(RTRIM(@IN_H_TEL))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'H_TEL',N'家庭电话',@OLD_H_TEL,@IN_H_TEL,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END

    IF LTRIM(RTRIM(@OLD_MOBILE)) <> LTRIM(RTRIM(@IN_MOBILE))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'MOBILE',N'手机',@OLD_MOBILE,@IN_MOBILE,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END

    IF LTRIM(RTRIM(@OLD_BP)) <> LTRIM(RTRIM(@IN_BP))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'BP',N'BP机(手机2)',@OLD_BP,@IN_BP,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END

    IF LTRIM(RTRIM(@OLD_FAX)) <> LTRIM(RTRIM(@IN_FAX))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'FAX',N'传真',@OLD_FAX,@IN_FAX,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END

    IF LTRIM(RTRIM(@OLD_EMAIL)) <> LTRIM(RTRIM(@IN_E_MAIL))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'E_MAIL',N'EMAIL',@OLD_EMAIL,@IN_E_MAIL,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END

    IF @OLD_CUST_TYPE <> @IN_CUST_TYPE
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'CUST_TYPE_NAME',N'客户类别',@OLD_CUST_TYPE_NAME,@V_CUST_TYPE_NAME,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END

    IF LTRIM(RTRIM(@OLD_TOUCH_TYPE)) <> LTRIM(RTRIM(@IN_TOUCH_TYPE))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'TOUCH_TYPE_NAME',N'联系方式',@OLD_TOUCH_TYPE_NAME,@V_TOUCH_TYPE_NAME,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END

    IF LTRIM(RTRIM(@OLD_CUST_SOURCE)) <> LTRIM(RTRIM(@IN_CUST_SOURCE))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'CUST_SOURCE_NAME',N'客户来源',@OLD_CUST_SOURCE_NAME,@V_CUST_SOURCE_NAME,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END

    IF LTRIM(RTRIM(@OLD_SUMMARY)) <> LTRIM(RTRIM(@IN_SUMMARY))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'SUMMARY',N'备注',@OLD_SUMMARY,@IN_SUMMARY,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END

/*     IF LTRIM(RTRIM(@OLD_CUST_NO)) <> LTRIM(RTRIM(@IN_CUST_NO))
    BEGIN
        INSERT INTO TCUSTINFODETAIL(BOOK_CODE,CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN)
            VALUES(@V_BOOK_CODE,@IN_CUST_ID,'CUST_NO','客户编号',@OLD_CUST_NO,@IN_CUST_NO,@IN_INPUT_MAN)
    END */

    IF LTRIM(RTRIM(@OLD_LEGAL_MAN)) <> LTRIM(RTRIM(@IN_LEGAL_MAN))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'LEGAL_MAN',N'法人代表',@OLD_LEGAL_MAN,@IN_LEGAL_MAN,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END

    IF LTRIM(RTRIM(@OLD_LEGAL_ADDRESS)) <> LTRIM(RTRIM(@IN_LEGAL_ADDRESS))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'LEGAL_ADDRESS',N'法人地址',@OLD_LEGAL_ADDRESS,@IN_LEGAL_ADDRESS,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END

    IF LTRIM(RTRIM(@OLD_BIRTHDAY)) <> LTRIM(RTRIM(@IN_BIRTHDAY))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'BIRTHDAY',N'生日',@OLD_BIRTHDAY,@IN_BIRTHDAY,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END

    IF @OLD_PRINT_DEPLOY_BILL <> @IN_PRINT_DEPLOY_BILL
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'PRINT_DEPLOY_BILL',N'是否打印对帐单',@OLD_PRINT_DEPLOY_BILL,@IN_PRINT_DEPLOY_BILL,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END

    IF @OLD_PRINT_POST_INFO <> @IN_PRINT_POST_INFO
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'PRINT_POST_INFO',N'是否打印披露信息',@OLD_PRINT_POST_INFO,@IN_PRINT_POST_INFO,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END

    IF @OLD_IS_LINK <> @IN_IS_LINK
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'IS_LINK',N'是否为关联方',@OLD_IS_LINK,@IN_IS_LINK,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END
    IF @OLD_SERVICE_MAN <> @IN_SERVICE_MAN
    BEGIN
        DECLARE @OLD_SERVICE_NAME NVARCHAR(20),@V_SERVICE_NAME NVARCHAR(20)
        SELECT @OLD_SERVICE_NAME = OP_NAME FROM TOPERATOR WHERE OP_CODE = @OLD_SERVICE_MAN
        SELECT @V_SERVICE_NAME = OP_NAME FROM TOPERATOR WHERE OP_CODE = @IN_SERVICE_MAN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'SERVICE_MAN',N'客户经理',@OLD_SERVICE_NAME,@V_SERVICE_NAME,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)

        --客户信息变更不要审核 1是 2否
		IF NOT EXISTS (SELECT 1 FROM TSYSCONTROL WHERE FLAG_TYPE='CUSTINFO_CHANGE' AND VALUE=1)
			UPDATE INTRUST..TCONTRACT SET SERVICE_MAN = @IN_SERVICE_MAN WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG = 2
    END
    IF LTRIM(RTRIM(@OLD_VIP_CARD_ID)) <> LTRIM(RTRIM(@IN_VIP_CARD_ID))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'VIP_CARD_ID',N'VIP卡编号',@OLD_VIP_CARD_ID,@IN_VIP_CARD_ID,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END
    IF @OLD_VIP_DATE <> @IN_VIP_DATE
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'VIP_DATE',N'VIP发卡日期',@OLD_VIP_DATE,@IN_VIP_DATE,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END
    IF LTRIM(RTRIM(@OLD_HGTZR_BH)) <> LTRIM(RTRIM(@IN_HGTZR_BH))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'HGTZR_BH',N'合格投资人编号',@OLD_HGTZR_BH,@IN_HGTZR_BH,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END
    IF LTRIM(RTRIM(@OLD_VOC_TYPE_NAME)) <> LTRIM(RTRIM(@V_VOC_TYPE_NAME))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'VOC_TYPE_NAME',N'个人职业机构行业类别',@OLD_VOC_TYPE_NAME,@V_VOC_TYPE_NAME,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END
    IF LTRIM(RTRIM(@OLD_LEGAL_TEL)) <> LTRIM(RTRIM(@IN_LEGAL_TEL))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'LEGAL_TEL',N'法人固定电话',@OLD_LEGAL_TEL,@IN_LEGAL_TEL,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END
    IF LTRIM(RTRIM(@OLD_LEGAL_MOBILE)) <> LTRIM(RTRIM(@IN_LEGAL_MOBILE))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'LEGAL_MOBILE',N'法人手机',@OLD_LEGAL_MOBILE,@IN_LEGAL_MOBILE,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END
    IF LTRIM(RTRIM(@OLD_ISSUED_ORG)) <> LTRIM(RTRIM(@IN_ISSUED_ORG))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'ISSUED_ORG',N'发证机关',@OLD_ISSUED_ORG,@IN_ISSUED_ORG,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END
    IF LTRIM(RTRIM(@OLD_INDUSTRY_POST)) <> LTRIM(RTRIM(@IN_INDUSTRY_POST))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'INDUSTRY_POST',N'行业岗位',@OLD_INDUSTRY_POST,@IN_INDUSTRY_POST,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END
    IF LTRIM(RTRIM(@OLD_MONEY_SOURCE)) <> LTRIM(RTRIM(@IN_MONEY_SOURCE))
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'MONEY_SOURCE',N'资金来源',@OLD_MONEY_SOURCE,@IN_MONEY_SOURCE,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END
	IF ISNULL(LTRIM(RTRIM(@OLD_EAST_JG_TYPE)),'') <> ISNULL(LTRIM(RTRIM(@IN_EAST_JG_TYPE)),'')
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'EAST_JG_TYPE',N'机构类型2109',@OLD_EAST_JG_TYPE,@IN_EAST_JG_TYPE,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END
    IF ISNULL(LTRIM(RTRIM(@OLD_JG_WTRLX2)),'') <> ISNULL(LTRIM(RTRIM(@IN_JG_WTRLX2)),'')
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'JG_WTRLX2',N'委托人类型',@OLD_JG_WTRLX2,@IN_JG_WTRLX2,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END
    IF ISNULL(LTRIM(RTRIM(@OLD_FACT_CONTROLLER)),'') <> ISNULL(LTRIM(RTRIM(@IN_FACT_CONTROLLER)),'')
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'FACT_CONTROLLER',N'实际控制人',@OLD_FACT_CONTROLLER,@IN_FACT_CONTROLLER,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END
    IF ISNULL(LTRIM(RTRIM(@OLD_FC_CARD_TYPE)),'') <> ISNULL(LTRIM(RTRIM(@IN_FC_CARD_TYPE)),'')
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'FC_CARD_TYPE',N'实际控制人的证件类型',@OLD_FC_CARD_TYPE,@IN_FC_CARD_TYPE,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END
    IF ISNULL(LTRIM(RTRIM(@OLD_FC_CARD_ID)),'') <> ISNULL(LTRIM(RTRIM(@IN_FC_CARD_ID)),'')
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'FC_CARD_ID',N'实际控制人的证件号',@OLD_FC_CARD_ID,@IN_FC_CARD_ID,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END
    IF ISNULL(LTRIM(RTRIM(@OLD_FC_CARD_VALID_DATE)),'') <> ISNULL(LTRIM(RTRIM(@IN_FC_CARD_VALID_DATE)),'')
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'FC_CARD_VALID_DATE',N'实际控制人的证件有效期',@OLD_FC_CARD_VALID_DATE,@IN_FC_CARD_VALID_DATE,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END
    IF ISNULL(LTRIM(RTRIM(@OLD_JG_CUST_TYPE)),'') <> ISNULL(LTRIM(RTRIM(@IN_JG_CUST_TYPE)),'')
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'JG_CUST_TYPE',N'机构客户类别',@OLD_JG_CUST_TYPE,@IN_JG_CUST_TYPE,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END
    IF ISNULL(LTRIM(RTRIM(@OLD_TRANS_NAME)),'') <> ISNULL(LTRIM(RTRIM(@IN_TRANS_NAME)),'')
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'TRANS_NAME',N'经办人姓名',@OLD_TRANS_NAME,@IN_TRANS_NAME,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END
    IF ISNULL(LTRIM(RTRIM(@OLD_TRANS_TEL)),'') <> ISNULL(LTRIM(RTRIM(@IN_TRANS_TEL)),'')
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'TRANS_TEL',N'经办人固定电话',@OLD_TRANS_TEL,@IN_TRANS_TEL,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END
    IF ISNULL(LTRIM(RTRIM(@OLD_TRANS_MOBILE)),'') <> ISNULL(LTRIM(RTRIM(@IN_TRANS_MOBILE)),'')
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'TRANS_MOBILE',N'经办人手机',@OLD_TRANS_MOBILE,@IN_TRANS_MOBILE,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END
    IF ISNULL(LTRIM(RTRIM(@OLD_TRANS_ADDRESS)),'') <> ISNULL(LTRIM(RTRIM(@IN_TRANS_ADDRESS)),'')
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'TRANS_ADDRESS',N'经办人联系地址',@OLD_TRANS_ADDRESS,@IN_TRANS_ADDRESS,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END
    IF ISNULL(LTRIM(RTRIM(@OLD_TRANS_POST_CODE)),'') <> ISNULL(LTRIM(RTRIM(@IN_TRANS_POST_CODE)),'')
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'TRANS_POST_CODE',N'经办人邮编',@OLD_TRANS_POST_CODE,@IN_TRANS_POST_CODE,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END
    IF ISNULL(LTRIM(RTRIM(@OLD_SERVICE_MAN_TEL)),'') <> ISNULL(LTRIM(RTRIM(@IN_SERVICE_MAN_TEL)),'')
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'SERVICE_MAN_TEL',N'客户经理电话',@OLD_SERVICE_MAN_TEL,@IN_SERVICE_MAN_TEL,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END
    IF ISNULL(LTRIM(RTRIM(@OLD_GOV_PROV_REGIONAL)),'') <> ISNULL(LTRIM(RTRIM(@IN_GOV_PROV_REGIONAL)),'')
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'GOV_PROV_REGIONAL',N'省级行政区',@OLD_GOV_PROV_REGIONAL,@IN_GOV_PROV_REGIONAL,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END
    IF ISNULL(LTRIM(RTRIM(@OLD_GOV_REGIONAL)),'') <> ISNULL(LTRIM(RTRIM(@IN_GOV_REGIONAL)),'')
    BEGIN
        INSERT INTO TCustomerChanges(CUST_ID,FIELD_NAME,FIELD_CN_NAME,OLD_FIELD_INFO,NEW_FIELD_INFO,INPUT_MAN,CHECK_FLAG)
            VALUES(@IN_CUST_ID,N'GOV_REGIONAL',N'区级行政区',@OLD_GOV_REGIONAL,@IN_GOV_REGIONAL,@IN_INPUT_MAN,@V_MODI_CHECK_FLAG)
    END
    
    --------------------------------------------------------------------
    --客户信息变更不要审核 1是 2否
	IF NOT EXISTS (SELECT 1 FROM TSYSCONTROL WHERE FLAG_TYPE='CUSTINFO_CHANGE' AND VALUE=1)
	BEGIN--不审核时运行，要审核时，下面的动作放到审核的过程中去
    UPDATE TCustomers
        SET CUST_NAME = @IN_CUST_NAME,
            CUST_TEL = @IN_CUST_TEL,
            POST_ADDRESS = @IN_POST_ADDRESS,
            POST_ADDRESS2 = @IN_POST_ADDRESS2,
            POST_CODE = @IN_POST_CODE,
            POST_CODE2 = @IN_POST_CODE2,
            CARD_TYPE = @IN_CARD_TYPE,
            CARD_TYPE_NAME = @V_CARD_TYPE_NAME,
            CARD_ID = @IN_CARD_ID,
            AGE = @IN_AGE,
            SEX = @IN_SEX,
            SEX_NAME = @V_SEX_NAME,
            O_TEL = @IN_O_TEL,
            H_TEL = @IN_H_TEL,
            MOBILE = @IN_MOBILE,
            BP = @IN_BP,
            FAX = @IN_FAX,
            E_MAIL = @IN_E_MAIL,
            CUST_TYPE = @IN_CUST_TYPE,
            CUST_TYPE_NAME = @V_CUST_TYPE_NAME,
            TOUCH_TYPE = @IN_TOUCH_TYPE,
            TOUCH_TYPE_NAME = @V_TOUCH_TYPE_NAME,
            CUST_SOURCE = @IN_CUST_SOURCE,
            CUST_SOURCE_NAME = @V_CUST_SOURCE_NAME,
            SUMMARY = @IN_SUMMARY,
            CUST_NO = @IN_CUST_NO,
            STATUS = @V_STATUS,
            STATUS_NAME = @V_STATUS_NAME,
            MODI_MAN = @IN_INPUT_MAN,
            MODI_TIME = dbo.GETDATEINT(getdate()),
            LEGAL_MAN = @IN_LEGAL_MAN,
            LEGAL_ADDRESS = @IN_LEGAL_ADDRESS,
            BIRTHDAY = @IN_BIRTHDAY,
            PRINT_DEPLOY_BILL = @IN_PRINT_DEPLOY_BILL,
            PRINT_POST_INFO = @IN_PRINT_POST_INFO,
            IS_LINK = @IN_IS_LINK,
            SERVICE_MAN = @IN_SERVICE_MAN,
            VIP_CARD_ID = @IN_VIP_CARD_ID,
            VIP_DATE = @IN_VIP_DATE,
            HGTZR_BH = @IN_HGTZR_BH,
            VOC_TYPE = @IN_VOC_TYPE,
            VOC_TYPE_NAME = @V_VOC_TYPE_NAME,
            CARD_VALID_DATE = @IN_CARD_VALID_DATE,
            COUNTRY         = @IN_COUNTRY,
            JG_CUST_TYPE    = @IN_JG_CUST_TYPE,
            CONTACT_MAN     = @IN_CONTACT_MAN,
            MONEY_SOURCE    = @IN_MONEY_SOURCE,
            MONEY_SOURCE_NAME = @V_MONEY_SOURCE_NAME, --资金来源名称
            FACT_CONTROLLER = @IN_FACT_CONTROLLER,     --实际控制人     add by luohh 0090727
            --ImageIdentification = ISNULL(@IN_ImageIdentification,ImageIdentification),
            PinYinSimple = @V_PinYinSimple,
            --POTENTIAL_MONEY = @IN_POTENTIAL_MONEY,
            --IS_DEAL = @V_IS_DEAL,
            GOV_PROV_REGIONAL = @IN_GOV_PROV_REGIONAL,
            GOV_PROV_REGIONAL_NAME = @V_GOV_PROV_REGIONAL_NAME,
            GOV_REGIONAL = @IN_GOV_REGIONAL,
            GOV_REGIONAL_NAME = @V_GOV_REGIONAL_NAME,
            --RECOMMENDED = @IN_RECOMMENDED,
            COMPLETE_FLAG = @IN_COMPLETE_FLAG,
            --COMPANY_UNIT     = @IN_COMPANY_UNIT,
            --COMPANY_DEPART   = @IN_COMPANY_DEPART,
            --COMPANY_POSITION = @IN_COMPANY_POSITION,
            --CUST_AUM = @IN_CUST_AUM,
            --CUST_AUM_NAME = @V_CUST_AUM_NAME,
            --CUST_AGE_GROUP = @IN_CUST_AGE_GROUP,
            --CUST_AGE_GROUP_NAME = @V_CUST_AGE_GROUP_NAME,
            --INVES_EXPERINCE = @IN_INVES_EXPERINCE,
            --CUST_SOURCE_EXPLAIN = @IN_CUST_SOURCE_EXPLAIN,
            EAST_JG_TYPE = @IN_EAST_JG_TYPE,                    --机构类型2109（依据EAST委托人类型WTRLX）
            EAST_JG_TYPE_NAME = @V_EAST_JG_TYPE_NAME,           --机构类型名称（依据EAST委托人类型WTRLX）
            JG_WTRLX2 = @IN_JG_WTRLX2
        WHERE CUST_ID = @IN_CUST_ID
    /*UPDATE TCustomers
        SET PERSONAL_INCOME = @IN_PERSONAL_INCOME,HOUSEHOLD_INCOME = @IN_HOUSEHOLD_INCOME
            ,FEEDING_NUM_PEOPLE = @IN_FEEDING_NUM_PEOPLE,MAIN_SOURCE = @IN_MAIN_SOURCE
            ,OTHER_SOURCE = @IN_OTHER_SOURCE,HOUSE_POSITION = @IN_HOUSE_POSITION,HOUSE_PROPERTY = @IN_HOUSE_PROPERTY,HOUSE_AREA = @IN_HOUSE_AREA
            ,PLAT_ENVALUATE = @IN_PLAT_ENVALUATE,MARKET_APPRAISAL = @IN_MARKET_APPRAISAL
            ,VEHICLE_NUM = @IN_VEHICLE_NUM,VEHICLE_MAKE = @IN_VEHICLE_MAKE,VEHICLE_TYPE = @IN_VEHICLE_TYPE,CREDIT_TYPE = @IN_CREDIT_TYPE
            ,CREDIT_NUM = @IN_CREDIT_NUM,CREDIT_START_DATE = @IN_CREDIT_START_DATE
            ,CREDIT_END_DATE = @IN_CREDIT_END_DATE,OTHER_INVESTMENT_STATUS = @IN_OTHER_INVESTMENT_STATUS
            ,TYPE_PREF = @IN_TYPE_PREF,TIME_LIMIT_PREF = @IN_TIME_LIMIT_PREF,INVEST_PREF = @IN_INVEST_PREF,HOBBY_PREF = @IN_HOBBY_PREF
            ,SERVICE_PREF = @IN_SERVICE_PREF,CONTACT_PREF = @IN_CONTACT_PREF
            ,HEAD_OFFICE_CUST_ID = @IN_HEAD_OFFICE_CUST_ID,STATURE = @IN_STATURE,WEIGHT = @IN_WEIGHT,SPOUSE_NAME = @IN_SPOUSE_NAME
            ,SPOUSE_INFO = @IN_SPOUSE_INFO,CHILDREN_NAME = @IN_CHILDREN_NAME,CHILDREN_INFO = @IN_CHILDREN_INFO,NATION = @IN_NATION
            ,MARITAL = @IN_MARITAL,HEALTH = @IN_HEALTH,EDUCATION = @IN_EDUCATION,POST = @IN_POST,HOLDEROFANOFFICE = @IN_HOLDEROFANOFFICE
            ,COMPANY_CHARACTER = @IN_COMPANY_CHARACTER,COMPANY_STAFF = @IN_COMPANY_STAFF,BOCOM_STAFF = @IN_BOCOM_STAFF,CLIENT_QUALE = @IN_CLIENT_QUALE
            ,REGISTERED_PLACE = @IN_REGISTERED_PLACE,REGISTERED_CAPITAL = @IN_REGISTERED_CAPITAL,EMPLOYEE_NUM = @IN_EMPLOYEE_NUM,HOLDING = @IN_HOLDING
            ,OTHER_INVE_STATUS_NAME = @V_OTHER_INVE_STATUS_NAME,TYPE_PREF_NAME = @V_TYPE_PREF_NAME
            ,TIME_LIMIT_PREF_NAME = @V_TIME_LIMIT_PREF_NAME,INVEST_PREF_NAME = @V_INVEST_PREF_NAME
            ,HOBBY_PREF_NAME = @V_HOBBY_PREF_NAME,SERVICE_PREF_NAME = @V_SERVICE_PREF_NAME
            ,CONTACT_PREF_NAME = @V_CONTACT_PREF_NAME,NATION_NAME = @V_NATION_NAME,HEALTH_NAME = @V_HEALTH_NAME,EDUCATION_NAME = @V_EDUCATION_NAME
            ,COMPANY_CHARACTER_NAME = @V_COMPANY_CHARACTER_NAME,CLIENT_QUALE_NAME = @V_CLIENT_QUALE_NAME
            ,RISK_PREF = @IN_RISK_PREF,RISK_PREF_NAME = @V_RISK_PREF_NAME
            ,FREE_CASH_FLOW = @IN_FREE_CASH_FLOW,BUREND_OF_DEBT = @IN_BUREND_OF_DEBT,COMPLETE_FLAG = @IN_COMPLETE_FLAG
        WHERE CUST_ID = @IN_CUST_ID
    */
    --
    --同步到信托客户表中
    BEGIN
        EXEC  INTRUST..SP_MODI_TCUSTOMERINFO
                        @IN_CUST_ID              = @IN_CUST_ID,
                        @IN_CUST_NAME            = @IN_CUST_NAME,
                        @IN_CUST_TEL             = @IN_CUST_TEL,
                        @IN_POST_ADDRESS         = @IN_POST_ADDRESS,
                        @IN_POST_CODE            = @IN_POST_CODE,
                        @IN_CARD_TYPE            = @IN_CARD_TYPE,
                        @IN_CARD_ID              = @IN_CARD_ID,
                        @IN_AGE                  = @IN_AGE,
                        @IN_SEX                  = @IN_SEX,
                        @IN_O_TEL                = @IN_O_TEL,
                        @IN_H_TEL                = @IN_H_TEL,
                        @IN_MOBILE               = @IN_MOBILE,
                        @IN_BP                   = @IN_BP,
                        @IN_FAX                  = @IN_FAX,
                        @IN_E_MAIL               = @IN_E_MAIL,
                        @IN_CUST_TYPE            = @IN_CUST_TYPE,
                        @IN_TOUCH_TYPE           = @IN_TOUCH_TYPE,
                        @IN_CUST_SOURCE          = @IN_CUST_SOURCE,
                        @IN_SUMMARY              = @IN_SUMMARY,
                        @IN_INPUT_MAN            = @IN_INPUT_MAN,
                        @IN_CUST_NO              = @IN_CUST_NO,
                        @IN_LEGAL_MAN            = @IN_LEGAL_MAN,
                        @IN_LEGAL_ADDRESS        = @IN_LEGAL_ADDRESS,
                        @IN_BIRTHDAY             = @IN_BIRTHDAY,
                        @IN_POST_ADDRESS2        = @IN_POST_ADDRESS2,
                        @IN_POST_CODE2           = @IN_POST_CODE2,
                        @IN_PRINT_DEPLOY_BILL    = @IN_PRINT_DEPLOY_BILL,
                        @IN_PRINT_POST_INFO      = @IN_PRINT_POST_INFO,
                        @IN_IS_LINK              = @IN_IS_LINK,
                        @IN_SERVICE_MAN          = @IN_SERVICE_MAN,
                        @IN_VIP_CARD_ID          = @IN_VIP_CARD_ID,
                        @IN_VIP_DATE             = @IN_VIP_DATE,
                        @IN_HGTZR_BH             = @IN_HGTZR_BH,
                        @IN_VOC_TYPE             = @IN_VOC_TYPE,
                        @IN_CARD_VALID_DATE      = @IN_CARD_VALID_DATE,
                        @IN_COUNTRY              = @IN_COUNTRY,
                        @IN_JG_CUST_TYPE         = @IN_JG_CUST_TYPE,
                        @IN_CONTACT_MAN          = @IN_CONTACT_MAN,
                        @IN_MONEY_SOURCE		 = @IN_MONEY_SOURCE,
						@IN_FACT_CONTROLLER		 = @IN_FACT_CONTROLLER,
						@IN_LINK_TYPE			 = @IN_LINK_TYPE,
						@IN_LINK_GD_MONEY		 = @IN_LINK_GD_MONEY,
						@IN_GRADE_LEVEL			 = @IN_GRADE_LEVEL,
						@IN_COMPLETE_FLAG		 = @IN_COMPLETE_FLAG,
						@IN_GOV_PROV_REGIONAL	 = @IN_GOV_PROV_REGIONAL,
						@IN_GOV_REGIONAL		 = @IN_GOV_REGIONAL,
						@IN_LEGAL_TEL			 = @IN_LEGAL_TEL,
						@IN_LEGAL_MOBILE		 = @IN_LEGAL_MOBILE,
						@IN_ISSUED_ORG			 = @IN_ISSUED_ORG,
						@IN_INDUSTRY_POST		 = @IN_INDUSTRY_POST,
						@IN_CUST_INDUSTRY		 = @IN_CUST_INDUSTRY,
						@IN_CUST_CORP_NATURE	 = @IN_CUST_CORP_NATURE,
						@IN_CORP_BRANCH			 = @IN_CORP_BRANCH,
						@IN_SERVICE_MAN_TEL		 = @IN_SERVICE_MAN_TEL,
						@IN_GRADE_SCORE			 = @IN_GRADE_SCORE,
						@IN_FC_CARD_TYPE		 = @IN_FC_CARD_TYPE,
						@IN_FC_CARD_ID			 = @IN_FC_CARD_ID,
						@IN_FC_CARD_VALID_DATE	 = @IN_FC_CARD_VALID_DATE,
						@IN_SUMMARY1			 = @IN_SUMMARY1,
						@IN_SUMMARY2			 = @IN_SUMMARY2,
						@IN_LEGAL_POST_CODE		 = @IN_LEGAL_POST_CODE,
						@IN_TRANS_NAME			 = @IN_TRANS_NAME,
						@IN_TRANS_TEL			 = @IN_TRANS_TEL,
						@IN_TRANS_MOBILE		 = @IN_TRANS_MOBILE,
						@IN_TRANS_ADDRESS		 = @IN_TRANS_ADDRESS,
						@IN_TRANS_POST_CODE		 = @IN_TRANS_POST_CODE,
						@IN_REGISTER_ADDRESS	 = @IN_REGISTER_ADDRESS,
						@IN_REGISTER_POST_CODE	 = @IN_REGISTER_POST_CODE,
						@IN_EAST_JG_TYPE		 = @IN_EAST_JG_TYPE,       --机构类型2109（依据EAST委托人类型WTRLX）
						@IN_JG_WTRLX2            = @IN_JG_WTRLX2           --机构有效：1金融性公司 2政府 3非金融性公司 4境外金融性公司
                                    
      
    END
    --同步到INTRUST..TE_WTRXX表
    DECLARE @V_WTRLX NVARCHAR(2)
    IF @IN_CUST_TYPE=2 --2机构
		SELECT @V_WTRLX = ADDITIVE_VALUE FROM TDICTPARAM WHERE TYPE_VALUE = @IN_EAST_JG_TYPE
	ELSE --1个人
		SET @V_WTRLX='1'
    UPDATE INTRUST..TE_WTRXX
		SET WTRLX = @V_WTRLX,				--机构类型2109（依据EAST委托人类型WTRLX）
			JG_WTRLX2 = @IN_JG_WTRLX2		--机构有效：1金融性公司 2政府 3非金融性公司 4境外金融性公司
		WHERE CUST_ID = @IN_CUST_ID
    --客户证件信息表
    IF EXISTS(SELECT 1 FROM TCUSTCARDINFO WHERE CUST_ID = @IN_CUST_ID AND CARD_TYPE = @OLD_CARD_TYPE AND CARD_ID = @OLD_CARD_ID)
    BEGIN
        UPDATE TCUSTCARDINFO
            SET CARD_CUST_NAME = @IN_CUST_NAME,
                CARD_TYPE      = @IN_CARD_TYPE,
                CARD_TYPE_NAME = @V_CARD_TYPE_NAME,
                CARD_ID        = @IN_CARD_ID,
                VALID_DATE     = @IN_CARD_VALID_DATE,
                INPUT_TIME     = GETDATE()
               -- IMAGE1         = ISNULL(@IN_ImageIdentification,IMAGE1)
            WHERE CUST_ID = @IN_CUST_ID AND CARD_TYPE = @OLD_CARD_TYPE AND CARD_ID = @OLD_CARD_ID
    END
    ELSE
    BEGIN
        INSERT INTO TCUSTCARDINFO(CUST_ID,CARD_CUST_NAME,CUST_TYPE,CARD_TYPE,CARD_TYPE_NAME,CARD_ID,VALID_DATE,INPUT_TIME)
            VALUES(@IN_CUST_ID,@IN_CUST_NAME,@IN_CUST_TYPE,@IN_CARD_TYPE,@V_CARD_TYPE_NAME,@IN_CARD_ID,@IN_CARD_VALID_DATE,GETDATE())
    END
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
	END --是否审核判断结束
    
    SELECT @SSUMMARY = N'修改客户基本信息，客户名称：' + @IN_CUST_NAME
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)

    COMMIT TRANSACTION
    END TRY

    BEGIN CATCH

        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION

        DECLARE @V_ERROR_STR NVARCHAR(1000),@V_ERROR_NUMBER INT,@V_ERROR_SEVERITY INT,@V_ERROR_STATE INT,
                @V_ERROR_PROCEDURE sysname,@V_ERROR_LINE INT,@V_ERROR_MESSAGE NVARCHAR(4000)

        SELECT @V_ERROR_STR = N'%s<br>Procedure:%s,Line:%d',
               @V_ERROR_NUMBER = ERROR_NUMBER(),
               @V_ERROR_SEVERITY = ERROR_SEVERITY(),
               @V_ERROR_STATE = ERROR_STATE(),
               @V_ERROR_PROCEDURE = ERROR_PROCEDURE(),
               @V_ERROR_LINE = ERROR_LINE(),
               @V_ERROR_MESSAGE = ERROR_MESSAGE()

        RAISERROR(@V_ERROR_STR,@V_ERROR_SEVERITY,1,@V_ERROR_MESSAGE,@V_ERROR_PROCEDURE,@V_ERROR_LINE)
        RETURN -100
    END CATCH

    RETURN 100
GO
