USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_CHECK_TCONTRACT_AFTERCHECK_CRM @IN_SERIAL_NO   INTEGER,    --TCONTRACTMODI.SERIAL_NO
													@IN_CHECK_FLAG INTEGER,    --审核标记：1未审核；2审核通过；3审核否决
													@IN_CHECK_SUMMARY NVARCHAR(500),--审核说明
													@IN_INPUT_MAN  INTEGER     --操作员
WITH ENCRYPTION
AS
    DECLARE @V_PRODUCT_CODE NVARCHAR(6),@V_PRODUCT_NAME NVARCHAR(120),@V_CONTRACT_BH NVARCHAR(16)
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    DECLARE @V_DATE INT
    DECLARE @V_CONTRACT_SERIAL INT,@V_CONTRACT_SUB_BH NVARCHAR(120),
		@V_QS_DATE INT,@V_LINK_MAN INT,@V_SERVICE_MAN INT,@V_WITH_BANK_FLAG INT,
		@V_HT_BANK_ID NVARCHAR(10),@V_HT_BANK_NAME NVARCHAR(30),@V_HT_BANK_SUB_NAME NVARCHAR(60),@V_WITH_SECURITY_FLAG INT,
		@V_WITH_PRIVATE_FLAG INT,@V_CHANNEL_ID INT,@V_CHANNEL_TYPE NVARCHAR(10),@V_CHANNEL_COOPERTYPE NVARCHAR(10),
		@V_CHANNEL_COOPERTYPE_NAME NVARCHAR(30),@V_MARKET_MONEY DECIMAL(16,3),@V_IS_YKGL VARCHAR(1),@V_XTHTYJSYL NVARCHAR(1000),
		@V_JK_DATE INT,@V_JK_TYPE NVARCHAR(10),@V_JK_TYPE_NAME NVARCHAR (30),@V_RECOMMEND_MAN INT,
		@V_BANK_ID NVARCHAR(10),@V_BANK_SUB_NAME NVARCHAR(60),@V_BANK_ACCT NVARCHAR (30),@V_GAIN_ACCT NVARCHAR (60),
		@V_PROV_FLAG INT,@V_PROV_LEVEL NVARCHAR(10),@V_PROV_LEVEL_NAME NVARCHAR(30),@V_BONUS_FLAG INT,@V_BONUS_RATE DECIMAL(5,4),
		@V_CHANNEL_MEMO NVARCHAR(200),@V_SUMMARY NVARCHAR(200)
	DECLARE @V_O_CONTRACT_SUB_BH NVARCHAR(120),
		@V_O_QS_DATE INT,@V_O_LINK_MAN INT,@V_O_SERVICE_MAN INT,@V_O_WITH_BANK_FLAG INT,
		@V_O_HT_BANK_ID NVARCHAR(10),@V_O_HT_BANK_NAME NVARCHAR(30),@V_O_HT_BANK_SUB_NAME NVARCHAR(60),@V_O_WITH_SECURITY_FLAG INT,
		@V_O_WITH_PRIVATE_FLAG INT,@V_O_CHANNEL_ID INT,@V_O_CHANNEL_TYPE NVARCHAR(10),@V_O_CHANNEL_COOPERTYPE NVARCHAR(10),
		@V_O_CHANNEL_COOPERTYPE_NAME NVARCHAR(30),@V_O_MARKET_MONEY DECIMAL(16,3),@V_O_IS_YKGL VARCHAR(1),@V_O_XTHTYJSYL NVARCHAR(1000),
		@V_O_JK_DATE INT,@V_O_JK_TYPE NVARCHAR(10),@V_O_JK_TYPE_NAME NVARCHAR (30),@V_O_RECOMMEND_MAN INT,
		@V_O_BANK_ID NVARCHAR(10),@V_O_BANK_SUB_NAME NVARCHAR(60),@V_O_BANK_ACCT NVARCHAR (30),@V_O_GAIN_ACCT NVARCHAR (60),
		@V_O_PROV_FLAG INT,@V_O_PROV_LEVEL NVARCHAR(10),@V_O_PROV_LEVEL_NAME NVARCHAR(30),@V_O_BONUS_FLAG INT,@V_O_BONUS_RATE DECIMAL(5,4),
		@V_O_CHANNEL_MEMO NVARCHAR(200),@V_O_SUMMARY NVARCHAR(200)
    
    SET @V_RET_CODE = -20809000
    SET @IBUSI_FLAG = 20809
    SET @SBUSI_NAME = N'事后认购合同修改审核'
    SET @V_DATE = CONVERT(INT,CONVERT(CHAR(8),GETDATE(),112))
    
    BEGIN TRY
        BEGIN TRANSACTION
        
        IF @IN_CHECK_FLAG=3 --审核否决
        BEGIN
			UPDATE TCONTRACTMODI SET CHECK_FLAG=@IN_CHECK_FLAG,CHECK_DATE=@V_DATE,CHECK_MAN=@IN_INPUT_MAN,CHECK_SUMMARY=@IN_CHECK_SUMMARY WHERE SERIAL_NO=@IN_SERIAL_NO
		END
        ELSE IF @IN_CHECK_FLAG=2 --2审核通过
        BEGIN
			SELECT @V_CONTRACT_SERIAL=CONTRACT_SERIAL,@V_CONTRACT_SUB_BH=CONTRACT_SUB_BH,
				@V_QS_DATE=QS_DATE,@V_LINK_MAN=LINK_MAN,@V_SERVICE_MAN=SERVICE_MAN,@V_WITH_BANK_FLAG=WITH_BANK_FLAG,
				@V_HT_BANK_ID=HT_BANK_ID,@V_HT_BANK_NAME=HT_BANK_NAME,@V_HT_BANK_SUB_NAME=HT_BANK_SUB_NAME,@V_WITH_SECURITY_FLAG=WITH_SECURITY_FLAG,
				@V_WITH_PRIVATE_FLAG=WITH_PRIVATE_FLAG,@V_CHANNEL_ID=CHANNEL_ID,@V_CHANNEL_TYPE=CHANNEL_TYPE,@V_CHANNEL_COOPERTYPE=CHANNEL_COOPERTYPE,
				@V_CHANNEL_COOPERTYPE_NAME=CHANNEL_COOPERTYPE_NAME,@V_MARKET_MONEY=MARKET_MONEY,@V_IS_YKGL=IS_YKGL,@V_XTHTYJSYL=XTHTYJSYL,
				@V_JK_DATE=JK_DATE,@V_JK_TYPE=JK_TYPE,@V_JK_TYPE_NAME=JK_TYPE_NAME,@V_RECOMMEND_MAN=RECOMMEND_MAN,
				@V_BANK_ID=BANK_ID,@V_BANK_SUB_NAME=BANK_SUB_NAME,@V_BANK_ACCT=BANK_ACCT,@V_GAIN_ACCT=GAIN_ACCT,
				@V_PROV_FLAG=PROV_FLAG,@V_PROV_LEVEL=PROV_LEVEL,@V_PROV_LEVEL_NAME=PROV_LEVEL_NAME,@V_BONUS_FLAG=BONUS_FLAG,@V_BONUS_RATE=BONUS_RATE,
				@V_CHANNEL_MEMO=CHANNEL_MEMO,@V_SUMMARY=SUMMARY
				FROM TCONTRACTMODI WHERE SERIAL_NO=@IN_SERIAL_NO
			SELECT @V_O_CONTRACT_SUB_BH=CONTRACT_SUB_BH,
				@V_O_QS_DATE=QS_DATE,@V_O_LINK_MAN=LINK_MAN,@V_O_SERVICE_MAN=SERVICE_MAN,@V_O_WITH_BANK_FLAG=WITH_BANK_FLAG,
				@V_O_HT_BANK_ID=HT_BANK_ID,@V_O_HT_BANK_NAME=HT_BANK_NAME,@V_O_HT_BANK_SUB_NAME=HT_BANK_SUB_NAME,@V_O_WITH_SECURITY_FLAG=WITH_SECURITY_FLAG,
				@V_O_WITH_PRIVATE_FLAG=WITH_PRIVATE_FLAG,@V_O_CHANNEL_ID=CHANNEL_ID,@V_O_CHANNEL_TYPE=CHANNEL_TYPE,@V_O_CHANNEL_COOPERTYPE=CHANNEL_COOPERTYPE,
				@V_O_CHANNEL_COOPERTYPE_NAME=CHANNEL_COOPERTYPE_NAME,@V_O_MARKET_MONEY=MARKET_MONEY,@V_O_IS_YKGL=IS_YKGL,@V_O_XTHTYJSYL=XTHTYJSYL,
				@V_O_JK_DATE=JK_DATE,@V_O_JK_TYPE=JK_TYPE,@V_O_JK_TYPE_NAME=JK_TYPE_NAME,@V_O_RECOMMEND_MAN=RECOMMEND_MAN,
				@V_O_BANK_ID=BANK_ID,@V_O_BANK_SUB_NAME=BANK_SUB_NAME,@V_O_BANK_ACCT=BANK_ACCT,@V_O_GAIN_ACCT=GAIN_ACCT,
				@V_O_PROV_FLAG=PROV_FLAG,@V_O_PROV_LEVEL=PROV_LEVEL,@V_O_PROV_LEVEL_NAME=PROV_LEVEL_NAME,@V_O_BONUS_FLAG=BONUS_FLAG,@V_O_BONUS_RATE=BONUS_RATE,
				@V_O_CHANNEL_MEMO=CHANNEL_MEMO,@V_O_SUMMARY=SUMMARY
				FROM INTRUST..TCONTRACT WHERE SERIAL_NO=@V_CONTRACT_SERIAL
			--如果修改的值为空，则取原表中的值
			IF ISNULL(@V_CONTRACT_SUB_BH,'')='' SET @V_CONTRACT_SUB_BH = @V_O_CONTRACT_SUB_BH
			IF ISNULL(@V_QS_DATE                ,0)=0 SET @V_QS_DATE                =@V_O_QS_DATE          
			IF ISNULL(@V_JK_DATE                ,'')='' SET @V_JK_DATE                =@V_O_JK_DATE          
			IF ISNULL(@V_JK_TYPE                ,'')='' SET @V_JK_TYPE                =@V_O_JK_TYPE          
			IF ISNULL(@V_JK_TYPE_NAME           ,'')='' SET @V_JK_TYPE_NAME           =@V_O_JK_TYPE_NAME     
			IF ISNULL(@V_LINK_MAN               ,0)=0 SET @V_LINK_MAN               =@V_O_LINK_MAN         
			IF ISNULL(@V_SERVICE_MAN            ,0)=0 SET @V_SERVICE_MAN            =@V_O_SERVICE_MAN      
			IF ISNULL(@V_RECOMMEND_MAN          ,0)=0 SET @V_RECOMMEND_MAN          =@V_O_RECOMMEND_MAN    
			IF ISNULL(@V_WITH_BANK_FLAG         ,0)=0 SET @V_WITH_BANK_FLAG         =@V_O_WITH_BANK_FLAG   
			IF ISNULL(@V_BANK_ID                ,'')='' SET @V_BANK_ID                =@V_O_BANK_ID          
			IF ISNULL(@V_BANK_SUB_NAME          ,'')='' SET @V_BANK_SUB_NAME          =@V_O_BANK_SUB_NAME    
			IF ISNULL(@V_BANK_ACCT              ,'')='' SET @V_BANK_ACCT              =@V_O_BANK_ACCT        
			IF ISNULL(@V_GAIN_ACCT              ,'')='' SET @V_GAIN_ACCT              =@V_O_GAIN_ACCT        
			IF ISNULL(@V_HT_BANK_ID             ,'')='' SET @V_HT_BANK_ID             =@V_O_HT_BANK_ID       
			IF ISNULL(@V_HT_BANK_NAME           ,'')='' SET @V_HT_BANK_NAME           =@V_O_HT_BANK_NAME     
			IF ISNULL(@V_HT_BANK_SUB_NAME       ,'')='' SET @V_HT_BANK_SUB_NAME       =@V_O_HT_BANK_SUB_NAME 
			IF ISNULL(@V_PROV_FLAG              ,0)=0 SET @V_PROV_FLAG              =@V_O_PROV_FLAG        
    		IF ISNULL(@V_PROV_LEVEL             ,'')='' SET @V_PROV_LEVEL             =@V_O_PROV_LEVEL       
			IF ISNULL(@V_PROV_LEVEL_NAME        ,'')='' SET @V_PROV_LEVEL_NAME        =@V_O_PROV_LEVEL_NAME  
			IF ISNULL(@V_BONUS_FLAG             ,0)=0 SET @V_BONUS_FLAG             =@V_O_BONUS_FLAG       
			IF ISNULL(@V_BONUS_RATE             ,0)=0 SET @V_BONUS_RATE             =@V_O_BONUS_RATE
			IF ISNULL(@V_WITH_SECURITY_FLAG     ,0)=0 SET @V_WITH_SECURITY_FLAG     =@V_O_WITH_SECURITY_FLAG
			IF ISNULL(@V_WITH_PRIVATE_FLAG      ,0)=0 SET @V_WITH_PRIVATE_FLAG      =@V_O_WITH_PRIVATE_FLAG
			IF ISNULL(@V_CHANNEL_ID             ,0)=0 SET @V_CHANNEL_ID             =@V_O_CHANNEL_ID
			IF ISNULL(@V_CHANNEL_TYPE           ,'')='' SET @V_CHANNEL_TYPE           =@V_O_CHANNEL_TYPE
			IF ISNULL(@V_CHANNEL_COOPERTYPE     ,'')='' SET @V_CHANNEL_COOPERTYPE     =@V_O_CHANNEL_COOPERTYPE
			IF ISNULL(@V_CHANNEL_COOPERTYPE_NAME,'')='' SET @V_CHANNEL_COOPERTYPE_NAME=@V_O_CHANNEL_COOPERTYPE_NAME
			IF ISNULL(@V_CHANNEL_MEMO           ,'')='' SET @V_CHANNEL_MEMO           =@V_O_CHANNEL_MEMO
			IF ISNULL(@V_MARKET_MONEY           ,0)=0 SET @V_MARKET_MONEY           =@V_O_MARKET_MONEY
			IF ISNULL(@V_IS_YKGL                ,'')='' SET @V_IS_YKGL                =@V_O_IS_YKGL
			IF ISNULL(@V_XTHTYJSYL              ,'')='' SET @V_XTHTYJSYL              =@V_O_XTHTYJSYL
			IF ISNULL(@V_SUMMARY                ,'')='' SET @V_SUMMARY                =@V_O_SUMMARY
			
			--这些字段直接更新掉，要保证改后的数据是正确的
			UPDATE INTRUST..TCONTRACT SET
				CONTRACT_SUB_BH        = @V_CONTRACT_SUB_BH,   --合同实际编号
				QS_DATE                = @V_QS_DATE ,          --签署日期
				JK_DATE                = @V_JK_DATE,           --缴款日期
				JK_TYPE                = @V_JK_TYPE ,          --缴款方式
				JK_TYPE_NAME           = @V_JK_TYPE_NAME ,     --缴款方式说明
				LINK_MAN               = @V_LINK_MAN,          --联系人
				SERVICE_MAN            = @V_SERVICE_MAN,       --客户经理
				RECOMMEND_MAN          = @V_RECOMMEND_MAN,     --合同推荐人(内部)
				WITH_BANK_FLAG         = @V_WITH_BANK_FLAG,    --是否银信合作 1是 0否
				BANK_ID                = @V_BANK_ID ,          --受益银行
				BANK_NAME              = (SELECT TYPE_CONTENT FROM INTRUST..TDICTPARAM WHERE TYPE_VALUE=@V_BANK_ID),
				BANK_SUB_NAME          = @V_BANK_SUB_NAME,     --受益银行支行
				BANK_ACCT              = @V_BANK_ACCT ,        --受益账户
				GAIN_ACCT              = @V_GAIN_ACCT ,        --受益银行帐户户名
				HT_BANK_ID             = @V_HT_BANK_ID,        --合同银行
				HT_BANK_NAME           = @V_HT_BANK_NAME,      --合同银行名称
				HT_BANK_SUB_NAME       = @V_HT_BANK_SUB_NAME,  --合同银行下级支行名称
				PROV_FLAG              = @V_PROV_FLAG,         --受益优先级
    			PROV_LEVEL             = @V_PROV_LEVEL,        --收益级别
				PROV_LEVEL_NAME        = @V_PROV_LEVEL_NAME,   --受益级别说明
				BONUS_FLAG             = @V_BONUS_FLAG,        --收益分配方式：1、现金　2、转份额
				BONUS_RATE             = @V_BONUS_RATE,        --转份额比例
				WITH_SECURITY_FLAG     = @V_WITH_SECURITY_FLAG,--是否证信合作
				WITH_PRIVATE_FLAG      = @V_WITH_PRIVATE_FLAG, --是否私募基金合作
				CHANNEL_ID             = @V_CHANNEL_ID,        --渠道ID
				CHANNEL_TYPE           = @V_CHANNEL_TYPE,      --渠道类别(5500)
				CHANNEL_COOPERTYPE     = @V_CHANNEL_COOPERTYPE,--渠道合作方式(5502)
				CHANNEL_COOPERTYPE_NAME=@V_CHANNEL_COOPERTYPE_NAME, --渠道合作方式名称
				CHANNEL_MEMO           =@V_CHANNEL_MEMO,            --渠道附加信息
				MARKET_MONEY           =@V_MARKET_MONEY,            --渠道费用
				IS_YKGL                =@V_IS_YKGL,                 --用款方关联标志：1是
				XTHTYJSYL              =@V_XTHTYJSYL,               --信托合同预计收益率 FROM TCONTRACTMODI
				SUMMARY                =@V_SUMMARY                  --合同备注
				WHERE SERIAL_NO=@V_CONTRACT_SERIAL
			UPDATE TCONTRACTMODI SET CHECK_FLAG=@IN_CHECK_FLAG,CHECK_DATE=@V_DATE,CHECK_MAN=@IN_INPUT_MAN,CHECK_SUMMARY=@IN_CHECK_SUMMARY WHERE SERIAL_NO=@IN_SERIAL_NO
			IF EXISTS(SELECT 1 FROM INTRUST..TCONTRACTSG WHERE CONTRACT_SERIAL_NO = @V_CONTRACT_SERIAL)
			BEGIN
				UPDATE INTRUST..TCONTRACTSG SET CONTRACT_SUB_BH = @V_CONTRACT_SUB_BH WHERE CONTRACT_SERIAL_NO = @V_CONTRACT_SERIAL
			END
		END
		ELSE
			RAISERROR('审核状态非法',16,1)
        SELECT @V_PRODUCT_CODE = PRODUCT_CODE,@V_PRODUCT_NAME = PRODUCT_NAME,@V_CONTRACT_BH = CONTRACT_BH,@V_CONTRACT_SUB_BH = CONTRACT_SUB_BH
				FROM INTRUST..TCONTRACT WHERE SERIAL_NO = @IN_SERIAL_NO
	    SELECT @SSUMMARY = @SBUSI_NAME + N'，产品编号：' + @V_PRODUCT_CODE
                                       + N'，产品名称：' + @V_PRODUCT_NAME 
                                       + N'，合同序号：' + @V_CONTRACT_BH
                                       + N'，合同编号：' + @V_CONTRACT_SUB_BH
                                        
        INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
            VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
        
        COMMIT TRANSACTION
    END TRY
    
    BEGIN CATCH
        IF @@TRANCOUNT > 0 BEGIN
            ROLLBACK TRANSACTION
        END

        DECLARE @V_ERROR_STR NVARCHAR(1000),@V_ERROR_NUMBER INT,@V_ERROR_SEVERITY INT,@V_ERROR_STATE INT,
                @V_ERROR_PROCEDURE sysname,@V_ERROR_LINE INT,@V_ERROR_MESSAGE NVARCHAR(4000)

        SELECT @V_ERROR_STR = N'Message:%s<br><font color ="white">Error:%d,Level:%d,State:%d,Procedure:%s,Line:%d</font>',
               @V_ERROR_NUMBER = ERROR_NUMBER(),
               @V_ERROR_SEVERITY = ERROR_SEVERITY(),
               @V_ERROR_STATE = ERROR_STATE(),
               @V_ERROR_PROCEDURE = ERROR_PROCEDURE(),
               @V_ERROR_LINE = ERROR_LINE(),
               @V_ERROR_MESSAGE = ERROR_MESSAGE()

        RAISERROR(@V_ERROR_STR,@V_ERROR_SEVERITY,1,@V_ERROR_MESSAGE,@V_ERROR_NUMBER,@V_ERROR_SEVERITY,@V_ERROR_STATE,
                  @V_ERROR_PROCEDURE,@V_ERROR_LINE)

        RETURN -100
    END CATCH
    
    RETURN 100
GO
