USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TCustomer_ByCustNO @IN_CUST_NO        NVARCHAR(8),           --客户编号
                                             @IN_CARD_ID        NVARCHAR(20),          --证件号码
                                             @IN_VIP_CARD_ID    NVARCHAR(20) = NULL,   -- VIP卡编号
                                             @IN_HGTZR_BH       NVARCHAR(20) = NULL,   -- 合格投资人编号
                                             @IN_CUST_NAME      NVARCHAR(80) = NULL,   -- 客户名称
                                             @IN_IS_LINK        INT = NULL,            --是否为关联方:1是2否
                                             @IN_INPUT_MAN      INT = NULL

WITH ENCRYPTION
AS
    DECLARE @IN_CARD_ID18 NVARCHAR(18)
    IF EXISTS(SELECT * FROM TSYSCONTROL WHERE FLAG_TYPE = N'A_CARDID' AND VALUE = 1)
    BEGIN
        IF LEN(@IN_CARD_ID)=15   --15位身份证号码转18位
            SELECT @IN_CARD_ID18 = dbo.IDCARD15TO18(@IN_CARD_ID)
        ELSE IF LEN(@IN_CARD_ID)=18 --18位转成15位
            SELECT @IN_CARD_ID18 = dbo.IDCARD18TO15(@IN_CARD_ID)
    END
    SELECT @IN_CARD_ID18 = ISNULL(@IN_CARD_ID18, @IN_CARD_ID)
/*
该段功能给谁做的未知，dbo.GETCUSTRIGHT 函数中使用的表，涉及的菜单已注释
    IF EXISTS(SELECT * FROM TSYSCONTROL WHERE FLAG_TYPE = N'CUSTRIGHT' AND VALUE = 1)
    BEGIN
        SELECT CUST_ID,CUST_NO,CUST_NAME,CARD_TYPE,CARD_TYPE_NAME,dbo.ENCRYPTCUSTINFO(SERVICE_MAN,@IN_INPUT_MAN,CARD_ID) AS CARD_ID
        FROM TCustomers WHERE BOOK_CODE = @IN_BOOK_CODE
            AND (CUST_NO LIKE '%'+@IN_CUST_NO OR CUST_NO LIKE @IN_CUST_NO+'_______' OR @IN_CUST_NO IS NULL OR @IN_CUST_NO = N'')
            AND (CARD_ID LIKE '%'+@IN_CARD_ID+'%' OR CARD_ID LIKE '%'+@IN_CARD_ID18+'%' OR @IN_CARD_ID IS NULL OR @IN_CARD_ID = N'')
            AND ((CHECK_FLAG = 2 AND STATUS = N'112801') OR (STATUS = N'112803'))
            AND (VIP_CARD_ID LIKE '%'+@IN_VIP_CARD_ID+'%' OR ISNULL(@IN_VIP_CARD_ID,'') = N'')
            AND (HGTZR_BH LIKE '%'+@IN_HGTZR_BH+'%' OR ISNULL(@IN_HGTZR_BH,'') = N'')
            AND (CUST_NAME LIKE '%'+@IN_CUST_NAME+'%' OR @IN_CUST_NAME = N'' OR @IN_CUST_NAME IS NULL)
            AND (IS_LINK = @IN_IS_LINK OR @IN_IS_LINK = 0 OR @IN_IS_LINK IS NULL)
            AND (SERVICE_MAN IN (SELECT ENABLE_OP_CODE FROM TOPCUSTRIGHT WHERE OP_CODE = @IN_INPUT_MAN) OR SERVICE_MAN = @IN_INPUT_MAN)
        ORDER BY CUST_NAME
    END
    ELSE
    BEGIN
*/
        SELECT CUST_ID,CUST_NO,CUST_NAME,CARD_TYPE,CARD_TYPE_NAME,CARD_ID--dbo.ENCRYPTCUSTINFO(SERVICE_MAN,@IN_INPUT_MAN,CARD_ID) AS CARD_ID
			,(SELECT OP_NAME FROM TOPERATOR WHERE OP_CODE=TCustomers.SERVICE_MAN) SERVICE_MAN_NAME,CUST_TYPE_NAME,O_TEL,H_TEL,MOBILE,E_MAIL
			,POST_ADDRESS,POST_CODE
        FROM TCustomers WHERE (CUST_NO LIKE '%'+@IN_CUST_NO OR CUST_NO LIKE @IN_CUST_NO+'_______' OR @IN_CUST_NO IS NULL OR @IN_CUST_NO = N'')
            AND (CARD_ID LIKE '%'+@IN_CARD_ID+'%' OR CARD_ID LIKE '%'+@IN_CARD_ID18+'%' OR @IN_CARD_ID IS NULL OR @IN_CARD_ID = N'')
            AND ((CHECK_FLAG = 2 AND STATUS = N'112801') OR (STATUS = N'112803'))
            AND (VIP_CARD_ID LIKE '%'+@IN_VIP_CARD_ID+'%' OR ISNULL(@IN_VIP_CARD_ID,'') = N'')
            AND (HGTZR_BH LIKE '%'+@IN_HGTZR_BH+'%' OR ISNULL(@IN_HGTZR_BH,'') = N'')
            AND (CUST_NAME LIKE '%'+@IN_CUST_NAME+'%' OR @IN_CUST_NAME = N'' OR @IN_CUST_NAME IS NULL)
            AND (IS_LINK = @IN_IS_LINK OR @IN_IS_LINK = 0 OR @IN_IS_LINK IS NULL)
        ORDER BY CUST_NAME
--    END
GO
