USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE SP_STAT_LEVEL2_DATA_STATI_2 @IN_YAER_DATE INT
                                            -- @IN_INPUT_MAN INT

WITH ENCRYPTION
AS

IF ISNULL(@IN_YAER_DATE,0) =0
	SET @IN_YAER_DATE = YEAR(GETDATE())

DECLARE @V_YEAR NVARCHAR(10)
SET @V_YEAR = @IN_YAER_DATE

CREATE TABLE #V_TEMP_MONTH(JAN_AND_DEC_MONTH NVARCHAR(10),FLAG INT)
BEGIN
    INSERT INTO #V_TEMP_MONTH(JAN_AND_DEC_MONTH,FLAG)
			  SELECT @V_YEAR+'01',1
	UNION ALL SELECT @V_YEAR+'02',1
	UNION ALL SELECT @V_YEAR+'03',1
	UNION ALL SELECT @V_YEAR+'04',1
	UNION ALL SELECT @V_YEAR+'05',1
	UNION ALL SELECT @V_YEAR+'06',1
	UNION ALL SELECT @V_YEAR+'07',1
	UNION ALL SELECT @V_YEAR+'08',1
	UNION ALL SELECT @V_YEAR+'09',1
	UNION ALL SELECT @V_YEAR+'10',1
	UNION ALL SELECT @V_YEAR+'11',1
	UNION ALL SELECT @V_YEAR+'12',1

	UNION ALL SELECT @V_YEAR+'01',2
	UNION ALL SELECT @V_YEAR+'02',2
	UNION ALL SELECT @V_YEAR+'03',2
	UNION ALL SELECT @V_YEAR+'04',2
	UNION ALL SELECT @V_YEAR+'05',2
	UNION ALL SELECT @V_YEAR+'06',2
	UNION ALL SELECT @V_YEAR+'07',2
	UNION ALL SELECT @V_YEAR+'08',2
	UNION ALL SELECT @V_YEAR+'09',2
	UNION ALL SELECT @V_YEAR+'10',2
	UNION ALL SELECT @V_YEAR+'11',2
	UNION ALL SELECT @V_YEAR+'12',2

	UNION ALL SELECT @V_YEAR+'01',3
	UNION ALL SELECT @V_YEAR+'02',3
	UNION ALL SELECT @V_YEAR+'03',3
	UNION ALL SELECT @V_YEAR+'04',3
	UNION ALL SELECT @V_YEAR+'05',3
	UNION ALL SELECT @V_YEAR+'06',3
	UNION ALL SELECT @V_YEAR+'07',3
	UNION ALL SELECT @V_YEAR+'08',3
	UNION ALL SELECT @V_YEAR+'09',3
	UNION ALL SELECT @V_YEAR+'10',3
	UNION ALL SELECT @V_YEAR+'11',3
	UNION ALL SELECT @V_YEAR+'12',3

	UNION ALL SELECT @V_YEAR+'01',4
	UNION ALL SELECT @V_YEAR+'02',4
	UNION ALL SELECT @V_YEAR+'03',4
	UNION ALL SELECT @V_YEAR+'04',4
	UNION ALL SELECT @V_YEAR+'05',4
	UNION ALL SELECT @V_YEAR+'06',4
	UNION ALL SELECT @V_YEAR+'07',4
	UNION ALL SELECT @V_YEAR+'08',4
	UNION ALL SELECT @V_YEAR+'09',4
	UNION ALL SELECT @V_YEAR+'10',4
	UNION ALL SELECT @V_YEAR+'11',4
	UNION ALL SELECT @V_YEAR+'12',4
END

CREATE TABLE #V_TEMP_TABLE(日期 VARCHAR(30),
							客户个数   INT,
							金额区间          INT ---1表示100万-300万，2表示300万-1000万，3表示1000万-5000万，4表示5000万以上
						   )
--小于300万
BEGIN
INSERT INTO	#V_TEMP_TABLE
	SELECT DBO.GETDATEINT(INPUT_TIME)/100 AS '日期',COUNT(CUST_ID) AS '客户个数',1
		FROM INTRUST..TCUSTOMERINFO
		WHERE CUST_TYPE =1
		AND ISNULL(TOTAL_MONEY,0) < 3000000
		AND DBO.GETDATEINT(INPUT_TIME)/10000 = @IN_YAER_DATE
		GROUP BY DBO.GETDATEINT(INPUT_TIME)/100


--不全12个月记录 如果没有就插入0

INSERT INTO	 #V_TEMP_TABLE
SELECT A.JAN_AND_DEC_MONTH,0,A.FLAG FROM #V_TEMP_MONTH A
	WHERE NOT EXISTS(SELECT 1 FROM #V_TEMP_TABLE B
		WHERE A.JAN_AND_DEC_MONTH = B.[日期])
	AND A.FLAG = 1

--300万	--1000万
INSERT INTO	#V_TEMP_TABLE
	SELECT DBO.GETDATEINT(INPUT_TIME)/100 AS '日期',COUNT(CUST_ID) AS '客户个数',2
		FROM INTRUST..TCUSTOMERINFO
		WHERE CUST_TYPE =1
		AND ISNULL(TOTAL_MONEY,0) BETWEEN 3000000 AND 10000000
		AND DBO.GETDATEINT(INPUT_TIME)/10000 = @IN_YAER_DATE
		GROUP BY DBO.GETDATEINT(INPUT_TIME)/100

--不全12个月记录 如果没有就插入0
INSERT INTO	 #V_TEMP_TABLE
SELECT A.JAN_AND_DEC_MONTH,0,A.FLAG FROM #V_TEMP_MONTH A
	WHERE NOT EXISTS(SELECT 1 FROM #V_TEMP_TABLE B
		WHERE A.JAN_AND_DEC_MONTH = B.[日期])
	AND A.FLAG = 2

--1000万--5000万
INSERT INTO	#V_TEMP_TABLE
	SELECT DBO.GETDATEINT(INPUT_TIME)/100 AS '日期',COUNT(CUST_ID) AS '客户个数',3
		FROM INTRUST..TCUSTOMERINFO
		WHERE CUST_TYPE =1
		AND ISNULL(TOTAL_MONEY,0) BETWEEN 10000000 AND 50000000
		AND DBO.GETDATEINT(INPUT_TIME)/10000 = @IN_YAER_DATE
		GROUP BY DBO.GETDATEINT(INPUT_TIME)/100

--不全12个月记录 如果没有就插入0
INSERT INTO	 #V_TEMP_TABLE
SELECT A.JAN_AND_DEC_MONTH,0,A.FLAG FROM #V_TEMP_MONTH A
	WHERE NOT EXISTS(SELECT 1 FROM #V_TEMP_TABLE B
		WHERE A.JAN_AND_DEC_MONTH = B.[日期])
	AND A.FLAG = 3

--5000万以上
INSERT INTO	#V_TEMP_TABLE
	SELECT DBO.GETDATEINT(INPUT_TIME)/100 AS '日期',COUNT(CUST_ID) AS '客户个数',4
		FROM INTRUST..TCUSTOMERINFO
		WHERE CUST_TYPE =1
		AND ISNULL(TOTAL_MONEY,0) > 50000000
		AND DBO.GETDATEINT(INPUT_TIME)/10000 = @IN_YAER_DATE
		GROUP BY DBO.GETDATEINT(INPUT_TIME)/100

--不全12个月记录 如果没有就插入0
INSERT INTO	 #V_TEMP_TABLE
SELECT A.JAN_AND_DEC_MONTH,0,A.FLAG FROM #V_TEMP_MONTH A
	WHERE NOT EXISTS(SELECT 1 FROM #V_TEMP_TABLE B
		WHERE A.JAN_AND_DEC_MONTH = B.[日期])
	AND A.FLAG = 4
END

declare @sqlStart nvarchar(4000)
SET @sqlStart ='select ''个人'' AS 类别,CASE 金额区间 WHEN 1 THEN ''100～300万''
									    WHEN 2 THEN ''300～1000万''
									    WHEN 3 THEN ''1000～5000万''
									    WHEN 4 THEN ''5000万～''END AS ''金额区间'''
declare @sqlEnd nvarchar(200)
SET @sqlEnd=' from #V_TEMP_TABLE group by 金额区间'

select  @sqlStart= @sqlStart +',sum(case 日期 when N'''+日期+''' then 客户个数 else 0 end) as N'''+日期+'''' from (select distinct 日期 from #V_TEMP_TABLE) a
PRINT @sqlStart+@sqlEnd
exec( @sqlStart+@sqlEnd )

GO
