USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TCustByClass @IN_CLASSES    NVARCHAR(500), --各客户级别的值拼成的字符串，半角逗号分隔。例如：1001,1102,2001
                                       @IN_INPUT_MAN  INTEGER        --操作员
WITH ENCRYPTION
AS
    SET NOCOUNT ON

    --根据 @IN_CLASSES 取满足条件的客户ID到临时表，若 @IN_CLASSES 为空，临时表也为空无记录
    IF @IN_CLASSES IS NULL SET @IN_CLASSES = N''
    IF dbo.chkCustClassDetailIDs(@IN_CLASSES) = 0
        RETURN -21111001 --输入参数无效
    CREATE TABLE #TMP_QUERY_CustByClass(
        CUST_ID INT )
    DECLARE @V_SQL NVARCHAR(2000)
    IF @IN_CLASSES <> ''
    BEGIN
        SET @V_SQL = N'INSERT INTO #TMP_QUERY_CustByClass(CUST_ID) SELECT CUST_ID FROM TCUSTOMERCLASS WHERE CLASSDETAIL_ID IN ('+@IN_CLASSES+') GROUP BY CUST_ID'
        EXEC sp_executesql @V_SQL
    END

    IF @IN_CLASSES <> ''
        SELECT A.*, B.CLASS10, B.CLASS11, B.CLASS12
        FROM TCUSTOMERS A, (SELECT CUST_ID,MAX([10]) AS CLASS10, MAX([11]) AS CLASS11, MAX([12]) AS CLASS12
                            FROM TCustomerClass PIVOT(MAX(CLASSDETAIL_NAME) FOR CLASSDEFINE_ID IN ([10],[11],[12])) AS Z
                            GROUP BY CUST_ID) AS B
        WHERE A.CUST_ID = B.CUST_ID AND EXISTS(SELECT 1 FROM #TMP_QUERY_CustByClass Z WHERE A.CUST_ID = Z.CUST_ID)
    ELSE
        SELECT A.*, B.CLASS10, B.CLASS11, B.CLASS12
        FROM TCUSTOMERS A, (SELECT CUST_ID,MAX([10]) AS CLASS10, MAX([11]) AS CLASS11, MAX([12]) AS CLASS12
                            FROM TCustomerClass PIVOT(MAX(CLASSDETAIL_NAME) FOR CLASSDEFINE_ID IN ([10],[11],[12])) AS Z
                            GROUP BY CUST_ID) AS B
        WHERE A.CUST_ID = B.CUST_ID
GO
