USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TEAMQUOTA		@IN_PRODUCT_ID          INT , 
										@IN_SUB_PRODUCT_ID      INT ,
										@IN_PREPRODUCT_ID		INT	,
										@IN_TEAM_TYPE           INT ,	--个人1，团队2
										@IN_SELECT_ID           INT		--CUST_ID 或 TEAM_ID
WITH ENCRYPTION
AS
	SET @IN_PRODUCT_ID = ISNULL(@IN_PRODUCT_ID,0)
	SET @IN_SUB_PRODUCT_ID = ISNULL(@IN_SUB_PRODUCT_ID,0)
	SET @IN_PREPRODUCT_ID = ISNULL(@IN_PREPRODUCT_ID,0)
	
    IF ISNULL(@IN_TEAM_TYPE,0) = 1
    BEGIN
		IF ISNULL(@IN_PRODUCT_ID,0) <> 0
		SELECT B.MANAGERID TEAM_ID,B.MANAGERNAME TEAM_NAME,B.TEAM_NAME FATHER_TEAM_NAME,A.QUOTAMONEY,A.ALREADYSALE,A.QUOTA_QUALIFIED_NUM,A.ALREADY_QUALIFIED_NUM FROM TPERSONALQUOTA A,TManagerTeamMembers B 
			WHERE B.MANAGERID = @IN_SELECT_ID AND A.OP_CODE = @IN_SELECT_ID AND A.PRODUCT_ID = @IN_PRODUCT_ID AND A.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID 
			
		ELSE IF ISNULL(@IN_PREPRODUCT_ID,0) <> 0
		SELECT B.MANAGERID TEAM_ID,B.MANAGERNAME TEAM_NAME,B.TEAM_NAME FATHER_TEAM_NAME,A.QUOTAMONEY,A.ALREADYSALE,A.QUOTA_QUALIFIED_NUM,A.ALREADY_QUALIFIED_NUM FROM TPERSONALQUOTA A,TManagerTeamMembers B 
			WHERE B.MANAGERID = @IN_SELECT_ID AND A.OP_CODE = @IN_SELECT_ID AND A.PREPRODUCT_ID = @IN_PREPRODUCT_ID
	END
	
    ELSE IF ISNULL(@IN_TEAM_TYPE,0) = 2 
    BEGIN
		IF ISNULL(@IN_PRODUCT_ID,0) <> 0
		BEGIN
			IF EXISTS(SELECT 1 FROM TManagerTeams WHERE PARENT_ID = @IN_SELECT_ID)
				SELECT A.TEAM_ID,A.TEAM_NAME,(SELECT TEAM_NAME FROM TManagerTeams WHERE TEAM_ID = (SELECT PARENT_ID FROM TManagerTeams WHERE TEAM_ID = @IN_SELECT_ID)) FATHER_TEAM_NAME,B.QUOTAMONEY,B.ALREADYSALE,B.QUOTA_QUALIFIED_NUM,B.ALREADY_QUALIFIED_NUM FROM TManagerTeams A,TTEAMQUOTA B 
					WHERE A.TEAM_ID = @IN_SELECT_ID AND A.TEAM_ID = B.TEAM_ID AND B.PRODUCT_ID = @IN_PRODUCT_ID AND B.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID
				UNION ALL SELECT A.TEAM_ID,A.TEAM_NAME,(SELECT TEAM_NAME FROM TManagerTeams WHERE TEAM_ID = @IN_SELECT_ID) FATHER_TEAM_NAME,B.QUOTAMONEY,B.ALREADYSALE,B.QUOTA_QUALIFIED_NUM,B.ALREADY_QUALIFIED_NUM FROM TManagerTeams A,TTEAMQUOTA B 
					WHERE A.PARENT_ID = @IN_SELECT_ID AND A.TEAM_ID = B.TEAM_ID AND B.PRODUCT_ID = @IN_PRODUCT_ID AND B.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID 
			ELSE 
				SELECT A.TEAM_ID,A.TEAM_NAME,(SELECT TEAM_NAME FROM TManagerTeams WHERE TEAM_ID = (SELECT PARENT_ID FROM TManagerTeams WHERE TEAM_ID = @IN_SELECT_ID)) FATHER_TEAM_NAME,B.QUOTAMONEY,B.ALREADYSALE,B.QUOTA_QUALIFIED_NUM,B.ALREADY_QUALIFIED_NUM FROM TManagerTeams A,TTEAMQUOTA B 
					WHERE A.TEAM_ID = @IN_SELECT_ID AND A.TEAM_ID = B.TEAM_ID AND B.PRODUCT_ID = @IN_PRODUCT_ID AND B.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID
				UNION ALL SELECT B.MANAGERID TEAM_ID,B.MANAGERNAME TEAM_NAME,(SELECT TEAM_NAME FROM TManagerTeams WHERE TEAM_ID = @IN_SELECT_ID) FATHER_TEAM_NAME,A.QUOTAMONEY,A.ALREADYSALE,A.QUOTA_QUALIFIED_NUM,A.ALREADY_QUALIFIED_NUM FROM TPERSONALQUOTA A,TManagerTeamMembers B 
				WHERE A.OP_CODE = B.MANAGERID AND A.PRODUCT_ID = @IN_PRODUCT_ID AND A.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID AND B.TEAM_ID = @IN_SELECT_ID 
		END
		ELSE IF ISNULL(@IN_PREPRODUCT_ID,0) <> 0
		BEGIN
			IF EXISTS(SELECT 1 FROM TManagerTeams WHERE PARENT_ID = @IN_SELECT_ID)
				SELECT A.TEAM_ID,A.TEAM_NAME,(SELECT TEAM_NAME FROM TManagerTeams WHERE TEAM_ID = (SELECT PARENT_ID FROM TManagerTeams WHERE TEAM_ID = @IN_SELECT_ID)) FATHER_TEAM_NAME,B.QUOTAMONEY,B.ALREADYSALE,B.QUOTA_QUALIFIED_NUM,B.ALREADY_QUALIFIED_NUM FROM TManagerTeams A,TTEAMQUOTA B 
					WHERE A.TEAM_ID = @IN_SELECT_ID AND A.TEAM_ID = B.TEAM_ID AND B.PREPRODUCT_ID = @IN_PREPRODUCT_ID
				UNION ALL SELECT A.TEAM_ID,A.TEAM_NAME,(SELECT TEAM_NAME FROM TManagerTeams WHERE TEAM_ID = @IN_SELECT_ID) FATHER_TEAM_NAME,B.QUOTAMONEY,B.ALREADYSALE,B.QUOTA_QUALIFIED_NUM,B.ALREADY_QUALIFIED_NUM FROM TManagerTeams A,TTEAMQUOTA B 
					WHERE A.PARENT_ID = @IN_SELECT_ID AND A.TEAM_ID = B.TEAM_ID AND B.PREPRODUCT_ID = @IN_PREPRODUCT_ID
				
			ELSE 
				SELECT A.TEAM_ID,A.TEAM_NAME,(SELECT TEAM_NAME FROM TManagerTeams WHERE TEAM_ID = (SELECT PARENT_ID FROM TManagerTeams WHERE TEAM_ID = @IN_SELECT_ID)) FATHER_TEAM_NAME,B.QUOTAMONEY,B.ALREADYSALE,B.QUOTA_QUALIFIED_NUM,B.ALREADY_QUALIFIED_NUM FROM TManagerTeams A,TTEAMQUOTA B 
					WHERE A.TEAM_ID = @IN_SELECT_ID AND A.TEAM_ID = B.TEAM_ID AND B.PREPRODUCT_ID = @IN_PREPRODUCT_ID
				UNION ALL SELECT B.MANAGERID TEAM_ID,B.MANAGERNAME TEAM_NAME,(SELECT TEAM_NAME FROM TManagerTeams WHERE TEAM_ID = @IN_SELECT_ID) FATHER_TEAM_NAME,A.QUOTAMONEY,A.ALREADYSALE,A.QUOTA_QUALIFIED_NUM,A.ALREADY_QUALIFIED_NUM FROM TPERSONALQUOTA A,TManagerTeamMembers B 
				WHERE A.OP_CODE = B.MANAGERID AND A.PREPRODUCT_ID = @IN_PREPRODUCT_ID AND B.TEAM_ID = @IN_SELECT_ID	
		END
	END
	
	SELECT * FROM TPERSONALQUOTA WHERE 1=0
GO
