USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_ADD_TCOCONTRACTPOINTS @IN_COCONTRACT_ID              INT,                 --主合同ID，对应TCOCONTRACT.COCONTRACT_ID
                                          @IN_POINT_SUMMARY              NVARCHAR(2000),      --要点明细说明
                                          @IN_COPRODUCT_ID               INT,                 --产品ID，对应表TCOPRODUCT.COPRODUCT_ID
                                          @IN_SUB_HT_MONEY               DECIMAL(16,3),       --合同金额
                                          @IN_INPUT_MAN                  INT                  --录入人员，对应表TOPERATOR.OP_CODE
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    DECLARE @V_COCONTRACT_SUB_BH NVARCHAR(200),@V_COPRODUCT_NAME NVARCHAR(200)
    
    SELECT @SBUSI_NAME = N'合同管理之新增合同金额明细'
    SELECT @SSUMMARY = N'合同管理之新增合同金额明细'
    SELECT @IBUSI_FLAG = 50001
    SELECT @V_RET_CODE = -50001000 
    
    SELECT @V_COCONTRACT_SUB_BH = COCONTRACT_SUB_BH FROM TCOCONTRACT WHERE COCONTRACT_ID =@IN_COCONTRACT_ID
    SELECT @V_COPRODUCT_NAME = COPRODUCT_NAME FROM TCOPRODUCT WHERE COPRODUCT_ID =@IN_COPRODUCT_ID
    
    BEGIN TRANSACTION
    
    INSERT INTO TCOCONTRACTPOINTS(COCONTRACT_ID,POINT_SUMMARY,COPRODUCT_ID,COPRODUCT_NAME,SUB_HT_MONEY,INPUT_MAN)
        VALUES(@IN_COCONTRACT_ID,@IN_POINT_SUMMARY,@IN_COPRODUCT_ID,@V_COPRODUCT_NAME,@IN_SUB_HT_MONEY,@IN_INPUT_MAN)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    --
    SELECT @SSUMMARY = N'合同管理之新增合同金额明细，合同编号：'+@V_COCONTRACT_SUB_BH+'，合同要点：'+@IN_POINT_SUMMARY
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    
    COMMIT TRANSACTION
    RETURN 100
GO
