USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TCONTRACT_CRM @IN_BOOK_CODE           INTEGER,                --账套
										@IN_PRODUCT_ID          INTEGER,                --产品ID
										@IN_PRODUCT_CODE        NVARCHAR(6),            --产品编号
										@IN_CONTRACT_BH         NVARCHAR(16),           --合同编号
										@IN_CHECK_FLAG          INTEGER,                --21合同终止界面用查询
										@IN_INPUT_MAN           INTEGER,                --操作员
										@IN_CONTRACT_SUB_BH     NVARCHAR(50)  = '',     --合同编号查询  20080104 by wangc
										@IN_CONTRACT_ZJFLAG     INTEGER       = 0,      --合同性质：1 资金合同 2 财产合同 0 全部  20100629 luohh
										@IN_PRODUCT_NAME        NVARCHAR(60)  = NULL,   --产品名称
										@IN_CUST_TYPE           INTEGER       = NULL,   --客户类型
										@IN_MAX_RG_MONEY        DECIMAL(16,3) = NULL,   --最大认购金额
										@IN_MIN_RG_MONEY        DECIMAL(16,3) = NULL,   --最小认购金额
										@IN_SUB_PRODUCT_ID      INTEGER       = 0 ,     --子产品ID
										@IN_INTRUST_FLAG1       INTEGER       = 0 ,
										@IN_CUST_NAME			NVARCHAR(60)  = NULL,   --客户名称
										@IN_QS_DATE1            INTEGER       = NULL,   --认购日期（起）
										@IN_QS_DATE2            INTEGER       = NULL,    --认购日期（止）
										@IN_CONTRACT_TYPE       INT = 0,              --1 前台销售人员合同2产品部门合同3代销合同
										@IN_IF_MAIL             INT = 0               --合同是否寄回 1 是2否
WITH ENCRYPTION
AS
    --20409: The Products can be accessed. START
    DECLARE @V_SW20409 INT
    SELECT @V_SW20409 = VALUE FROM INTRUST..TSYSCONTROL WHERE FLAG_TYPE = 'SW20409'
    DECLARE @V_PRODUCTS TABLE(PRODUCT_ID INT)
    IF @V_SW20409 = 1
        INSERT INTO @V_PRODUCTS
            SELECT PRODUCT_ID FROM INTRUST..TPRODUCT WHERE BOOK_CODE = @IN_BOOK_CODE
                AND(INTRUST_FLAG1 IN ( SELECT FUNC_ID-2040900 FROM INTRUST..TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID > 2040900 AND FUNC_ID <= 2040999 AND OP_CODE = @IN_INPUT_MAN )
                    OR PRODUCT_ID IN ( SELECT FUNC_ID FROM INTRUST..TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID < 2040900 AND OP_CODE = @IN_INPUT_MAN)
                    OR ADMIN_MANAGER = @IN_INPUT_MAN OR INPUT_MAN = @IN_INPUT_MAN OR ISNULL(@IN_INPUT_MAN,0)=0
                    OR ADMIN_MANAGER IN(SELECT OP_CODE FROM INTRUST..TOPCUSTRIGHT WHERE ENABLE_OP_CODE = @IN_INPUT_MAN))
    --20409: The Products can be accessed. END

    DECLARE @V_IS_FLAG INT
    SELECT @V_IS_FLAG = 0

    --能够访问所有认购信息
    IF EXISTS(SELECT 1 FROM INTRUST..TOPRIGHT WHERE OP_CODE = @IN_INPUT_MAN AND MENU_ID ='20409' AND FUNC_ID = 2049906)
        SELECT @V_IS_FLAG = 1

    IF @IN_CHECK_FLAG = 1
        SELECT A.*,B.CUST_NO,B.CUST_NAME,dbo.ENCRYPTCUSTINFO(B.SERVICE_MAN,@IN_INPUT_MAN,B.CARD_ID) AS CARD_ID,
               D.LIST_ID,D.LIST_NAME AS SUB_PRODUCT_NAME,D.LIST_NAME,H.CHANNEL_TYPE_NAME,H.CHANNEL_NAME
            FROM INTRUST..TCONTRACT A LEFT JOIN INTRUST..TSUBPRODUCT D ON A.SUB_PRODUCT_ID = D.SUB_PRODUCT_ID
                 LEFT JOIN INTRUST..TCHANNEL H ON A.CHANNEL_ID = H.CHANNEL_ID AND A.CHANNEL_TYPE = H.CHANNEL_TYPE,
                 INTRUST..TCUSTOMERINFO B, INTRUST..TPRODUCT C
            WHERE A.CUST_ID = B.CUST_ID AND A.PRODUCT_ID = C.PRODUCT_ID AND A.BOOK_CODE  = @IN_BOOK_CODE AND A.HT_STATUS <>'120104'
                AND (A.CONTRACT_BH LIKE @IN_CONTRACT_BH+'%' OR ISNULL(@IN_CONTRACT_BH,'') = '')
                AND (A.CONTRACT_SUB_BH LIKE '%'+@IN_CONTRACT_SUB_BH+'%' OR ISNULL(@IN_CONTRACT_SUB_BH,'') = '')
                AND (A.PRODUCT_CODE = @IN_PRODUCT_CODE OR ISNULL(@IN_PRODUCT_CODE,'') = '')
                AND (A.CHECK_FLAG = 1)
                AND (A.PRODUCT_ID = @IN_PRODUCT_ID OR ISNULL(@IN_PRODUCT_ID,0) = 0)
                AND (A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM INTRUST..TPRODUCT WHERE (PRODUCT_STATUS = '110202' OR (PRODUCT_STATUS = '110203' AND  FPRG_FLAG =1)) AND (INTRUST_TYPE1 = '113801'OR INTRUST_TYPE1 = '113804')))
                AND (@V_SW20409 = 0 OR @V_SW20409 IS NULL OR A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCTS))
                AND (ISNULL(@IN_CONTRACT_ZJFLAG,0) =0 OR (@IN_CONTRACT_ZJFLAG =1 AND A.ENTITY_TYPE IS NULL) OR(@IN_CONTRACT_ZJFLAG =2 AND A.ENTITY_TYPE IS NOT NULL))
                AND (C.PRODUCT_NAME LIKE '%'+@IN_PRODUCT_NAME+'%' OR @IN_PRODUCT_NAME IS NULL OR @IN_PRODUCT_NAME='')
                AND (ISNULL(@IN_CUST_TYPE,0)=0 OR B.CUST_TYPE=@IN_CUST_TYPE)
                AND (ISNULL(@IN_MAX_RG_MONEY,0)=0 OR A.RG_MONEY <= @IN_MAX_RG_MONEY)
                AND (ISNULL(@IN_MIN_RG_MONEY,0)=0 OR A.RG_MONEY >= @IN_MIN_RG_MONEY)
                AND (A.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID OR ISNULL(@IN_SUB_PRODUCT_ID,0) = 0)
                AND (C.INTRUST_FLAG1 = @IN_INTRUST_FLAG1 OR ISNULL(@IN_INTRUST_FLAG1,0) = 0)
				AND (B.CUST_NAME LIKE '%'+@IN_CUST_NAME+'%' OR @IN_CUST_NAME IS NULL OR @IN_CUST_NAME='')
				AND (A.QS_DATE>=ISNULL(@IN_QS_DATE1,0))
				AND (A.QS_DATE<=ISNULL(@IN_QS_DATE2,20991231))
				AND (ISNULL(@IN_CONTRACT_TYPE,0)=0 OR A.CONTRACT_TYPE=@IN_CONTRACT_TYPE) --合同类型
				AND (ISNULL(@IN_IF_MAIL,0)=0 OR A.IF_MAIL=@IN_IF_MAIL) --合同是否寄回
            ORDER BY A.PRODUCT_ID,A.SUB_PRODUCT_ID,A.CONTRACT_SUB_BH
    ELSE IF @IN_CHECK_FLAG = 11
        SELECT A.*,B.CUST_NO,B.CUST_NAME,dbo.ENCRYPTCUSTINFO(B.SERVICE_MAN,@IN_INPUT_MAN,B.CARD_ID) AS CARD_ID,
               D.LIST_ID,D.LIST_NAME AS SUB_PRODUCT_NAME,D.LIST_NAME,H.CHANNEL_TYPE_NAME,H.CHANNEL_NAME
            FROM INTRUST..TCONTRACT A LEFT JOIN INTRUST..TSUBPRODUCT D ON A.SUB_PRODUCT_ID = D.SUB_PRODUCT_ID
                 LEFT JOIN INTRUST..TCHANNEL H ON A.CHANNEL_ID = H.CHANNEL_ID AND A.CHANNEL_TYPE = H.CHANNEL_TYPE,
                 INTRUST..TCUSTOMERINFO B, INTRUST..TPRODUCT C
            WHERE A.CUST_ID = B.CUST_ID AND A.PRODUCT_ID = C.PRODUCT_ID AND A.BOOK_CODE  = @IN_BOOK_CODE AND A.HT_STATUS <>'120104'
                AND (A.CONTRACT_BH LIKE @IN_CONTRACT_BH+'%' OR ISNULL(@IN_CONTRACT_BH,'') = '')
                AND (A.CONTRACT_SUB_BH LIKE '%'+@IN_CONTRACT_SUB_BH+'%' OR ISNULL(@IN_CONTRACT_SUB_BH,'') = '')
                AND (A.PRODUCT_CODE = @IN_PRODUCT_CODE OR ISNULL(@IN_PRODUCT_CODE,'') = '')
                AND (A.CHECK_FLAG = 1)
                AND (A.PRODUCT_ID = @IN_PRODUCT_ID OR ISNULL(@IN_PRODUCT_ID,0) = 0)
                AND (A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM INTRUST..TPRODUCT WHERE (PRODUCT_STATUS = '110202' OR PRODUCT_STATUS = '110203') AND (INTRUST_TYPE1 = '113801'OR INTRUST_TYPE1 = '113804')))
                AND (@V_SW20409 = 0 OR @V_SW20409 IS NULL OR A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCTS))
                AND (ISNULL(@IN_CONTRACT_ZJFLAG,0) =0 OR (@IN_CONTRACT_ZJFLAG =1 AND A.ENTITY_TYPE IS NULL) OR(@IN_CONTRACT_ZJFLAG =2 AND A.ENTITY_TYPE IS NOT NULL))
                AND (C.PRODUCT_NAME LIKE '%'+@IN_PRODUCT_NAME+'%' OR @IN_PRODUCT_NAME IS NULL OR @IN_PRODUCT_NAME='')
                AND (ISNULL(@IN_CUST_TYPE,0)=0 OR B.CUST_TYPE=@IN_CUST_TYPE)
                AND (ISNULL(@IN_MAX_RG_MONEY,0)=0 OR A.RG_MONEY <= @IN_MAX_RG_MONEY)
                AND (ISNULL(@IN_MIN_RG_MONEY,0)=0 OR A.RG_MONEY >= @IN_MIN_RG_MONEY)
                AND (A.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID OR ISNULL(@IN_SUB_PRODUCT_ID,0) = 0)
                AND (C.INTRUST_FLAG1 = @IN_INTRUST_FLAG1 OR ISNULL(@IN_INTRUST_FLAG1,0) = 0)
				AND (B.CUST_NAME LIKE '%'+@IN_CUST_NAME+'%' OR @IN_CUST_NAME IS NULL OR @IN_CUST_NAME='')
				AND (A.QS_DATE>=ISNULL(@IN_QS_DATE1,0))
				AND (A.QS_DATE<=ISNULL(@IN_QS_DATE2,20991231))
				AND (ISNULL(@IN_CONTRACT_TYPE,0)=0 OR A.CONTRACT_TYPE=@IN_CONTRACT_TYPE) --合同类型
				AND (ISNULL(@IN_IF_MAIL,0)=0 OR A.IF_MAIL=@IN_IF_MAIL) --合同是否寄回
            ORDER BY A.PRODUCT_ID,A.SUB_PRODUCT_ID,A.CONTRACT_SUB_BH
    ELSE IF @IN_CHECK_FLAG = 21    -- 合同终止界面用查询
        SELECT A.*,B.CUST_NO,B.CUST_NAME,dbo.ENCRYPTCUSTINFO(B.SERVICE_MAN,@IN_INPUT_MAN,B.CARD_ID) AS CARD_ID,
               D.LIST_ID,D.LIST_NAME AS SUB_PRODUCT_NAME,D.LIST_NAME,H.CHANNEL_TYPE_NAME,H.CHANNEL_NAME
            FROM INTRUST..TCONTRACT A LEFT JOIN INTRUST..TSUBPRODUCT D ON A.SUB_PRODUCT_ID = D.SUB_PRODUCT_ID
                 LEFT JOIN INTRUST..TCHANNEL H ON A.CHANNEL_ID = H.CHANNEL_ID AND A.CHANNEL_TYPE = H.CHANNEL_TYPE,
                 INTRUST..TCUSTOMERINFO B, INTRUST..TPRODUCT C
            WHERE A.CUST_ID = B.CUST_ID AND A.PRODUCT_ID = C.PRODUCT_ID AND A.BOOK_CODE  = @IN_BOOK_CODE AND A.HT_STATUS = '120101' AND A.CHECK_FLAG = 2
                AND (A.CONTRACT_BH LIKE @IN_CONTRACT_BH+'%' OR ISNULL(@IN_CONTRACT_BH,'') = '')
                AND (A.CONTRACT_SUB_BH LIKE '%'+@IN_CONTRACT_SUB_BH+'%' OR ISNULL(@IN_CONTRACT_SUB_BH,'') = '')
                AND (A.PRODUCT_ID = @IN_PRODUCT_ID)
                AND (ISNULL(@IN_CONTRACT_ZJFLAG,0) =0 OR (@IN_CONTRACT_ZJFLAG =1 AND A.ENTITY_TYPE IS NULL) OR(@IN_CONTRACT_ZJFLAG =2 AND A.ENTITY_TYPE IS NOT NULL))
                AND (ISNULL(@IN_CUST_TYPE,0)=0 OR B.CUST_TYPE=@IN_CUST_TYPE)
                AND (ISNULL(@IN_MAX_RG_MONEY,0)=0 OR A.RG_MONEY <= @IN_MAX_RG_MONEY)
                AND (ISNULL(@IN_MIN_RG_MONEY,0)=0 OR A.RG_MONEY >= @IN_MIN_RG_MONEY)
                AND (A.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID OR ISNULL(@IN_SUB_PRODUCT_ID,0) = 0)
                AND (C.INTRUST_FLAG1 = @IN_INTRUST_FLAG1 OR ISNULL(@IN_INTRUST_FLAG1,0) = 0)
				AND (B.CUST_NAME LIKE '%'+@IN_CUST_NAME+'%' OR @IN_CUST_NAME IS NULL OR @IN_CUST_NAME='')
				AND (A.QS_DATE>=ISNULL(@IN_QS_DATE1,0))
				AND (A.QS_DATE<=ISNULL(@IN_QS_DATE2,20991231))
				AND (ISNULL(@IN_CONTRACT_TYPE,0)=0 OR A.CONTRACT_TYPE=@IN_CONTRACT_TYPE) --合同类型
				AND (ISNULL(@IN_IF_MAIL,0)=0 OR A.IF_MAIL=@IN_IF_MAIL) --合同是否寄回
            ORDER BY A.PRODUCT_ID,A.SUB_PRODUCT_ID,A.CONTRACT_SUB_BH
    ELSE
        SELECT A.*,B.CUST_NO,B.CUST_NAME,dbo.ENCRYPTCUSTINFO(B.SERVICE_MAN,@IN_INPUT_MAN,B.CARD_ID) AS CARD_ID,
               D.LIST_ID,D.LIST_NAME AS SUB_PRODUCT_NAME,D.LIST_NAME
            FROM INTRUST..TCONTRACT A LEFT JOIN INTRUST..TSUBPRODUCT D ON A.SUB_PRODUCT_ID = D.SUB_PRODUCT_ID,
                 INTRUST..TCUSTOMERINFO B, INTRUST..TPRODUCT C
            WHERE A.CUST_ID = B.CUST_ID AND A.PRODUCT_ID = C.PRODUCT_ID AND A.BOOK_CODE  = @IN_BOOK_CODE
                AND (A.CONTRACT_BH LIKE @IN_CONTRACT_BH+'%' OR ISNULL(@IN_CONTRACT_BH,'') = '')
                AND (A.CONTRACT_SUB_BH LIKE '%'+@IN_CONTRACT_SUB_BH+'%' OR ISNULL(@IN_CONTRACT_SUB_BH,'') = '')
                AND (A.PRODUCT_CODE = @IN_PRODUCT_CODE OR ISNULL(@IN_PRODUCT_CODE,'') = '')
                AND (A.PRODUCT_ID = @IN_PRODUCT_ID OR ISNULL(@IN_PRODUCT_ID,0) =0)
--                AND (A.LINK_MAN = @IN_INPUT_MAN OR A.INPUT_MAN = @IN_INPUT_MAN OR A.SERVICE_MAN = @IN_INPUT_MAN OR @V_IS_FLAG = 1)
                AND (@V_SW20409 = 0 OR @V_SW20409 IS NULL OR A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCTS))
                AND (ISNULL(@IN_CONTRACT_ZJFLAG,0) =0 OR (@IN_CONTRACT_ZJFLAG =1 AND A.ENTITY_TYPE IS NULL) OR(@IN_CONTRACT_ZJFLAG =2 AND A.ENTITY_TYPE IS NOT NULL))
                AND (ISNULL(@IN_CUST_TYPE,0)=0 OR B.CUST_TYPE=@IN_CUST_TYPE)
                AND (ISNULL(@IN_MAX_RG_MONEY,0)=0 OR A.RG_MONEY <= @IN_MAX_RG_MONEY)
                AND (ISNULL(@IN_MIN_RG_MONEY,0)=0 OR A.RG_MONEY >= @IN_MIN_RG_MONEY)
                AND (A.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID OR ISNULL(@IN_SUB_PRODUCT_ID,0) = 0)
                AND (C.INTRUST_FLAG1 = @IN_INTRUST_FLAG1 OR ISNULL(@IN_INTRUST_FLAG1,0) = 0)
				AND (B.CUST_NAME LIKE '%'+@IN_CUST_NAME+'%' OR @IN_CUST_NAME IS NULL OR @IN_CUST_NAME='')
				AND (A.QS_DATE>=ISNULL(@IN_QS_DATE1,0))
				AND (A.QS_DATE<=ISNULL(@IN_QS_DATE2,20991231))
				AND (ISNULL(@IN_CONTRACT_TYPE,0)=0 OR A.CONTRACT_TYPE=@IN_CONTRACT_TYPE) --合同类型
				AND (ISNULL(@IN_IF_MAIL,0)=0 OR A.IF_MAIL=@IN_IF_MAIL) --合同是否寄回
            ORDER BY A.PRODUCT_ID,A.SUB_PRODUCT_ID,A.CONTRACT_SUB_BH
GO
