USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_DEL_TCOCONTRACT @IN_COCONTRACT_ID                INT,             --合同ID
                                    @IN_INPUT_MAN                     INT              --录入人员，对应表TOPERATOR.OP_CODE
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    DECLARE @V_COCONTRACT_SUB_BH NVARCHAR(200)
    SELECT @SBUSI_NAME = N'合同管理之删除主合同'
    SELECT @SSUMMARY = N'合同管理之删除主合同'
    SELECT @IBUSI_FLAG = 50001
    SELECT @V_RET_CODE = -50001000

    IF EXISTS(SELECT 1 FROM TCOCONTRACT WHERE COCONTRACT_ID =@IN_COCONTRACT_ID AND CHECK_FLAG <>1)
        RETURN @V_RET_CODE -1 --已复核，不允许删除

    SELECT @V_COCONTRACT_SUB_BH = COCONTRACT_SUB_BH FROM TCOCONTRACT WHERE COCONTRACT_ID =@IN_COCONTRACT_ID

    BEGIN TRANSACTION

    DELETE FROM TCOCONTRACT WHERE COCONTRACT_ID =@IN_COCONTRACT_ID
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    --
    DELETE FROM TCOCONTRACTPOINTS WHERE COCONTRACT_ID =@IN_COCONTRACT_ID
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    --
    DELETE FROM TCOCONTRACTPAYPLAN WHERE COCONTRACT_ID =@IN_COCONTRACT_ID
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    --
    SELECT @SSUMMARY = N'合同管理之删除主合同，合同编号'+@V_COCONTRACT_SUB_BH
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
