USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_SET_TPRODUCT_INFOREPOS @IN_PRODUCT_ID   INT,            --产品ID
                                           @IN_CLASS_TYPE1  NVARCHAR(10),   --产品分类(1113)
                                           @IN_ANNOUNCE_URL NVARCHAR(200),  --信息披露地址
                                           @IN_BZCS         NVARCHAR(2000), --保障措施
                                           @IN_ZXDX         NVARCHAR(2000), --直销/代销
                                           @IN_KFQ          NVARCHAR(2000), --开放期
                                           @IN_SHSQTJQ      NVARCHAR(2000), --赎回申请提交期
                                           @IN_SYZH         NVARCHAR(2000), --收益账户
                                           @IN_DXJG         NVARCHAR(2000), --代销机构
                                           @IN_TZGW         NVARCHAR(2000), --投资顾问/受益人代表
                                           @IN_JJJL         NVARCHAR(2000), --基金经理
                                           @IN_KFR          NVARCHAR(2000), --开放日
                                           @IN_INPUT_MAN    INT             --操作员

WITH ENCRYPTION
AS
    SET NOCOUNT ON
    DECLARE @V_RET_CODE INT, @IBUSI_FLAG INT, @SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)
    SELECT @V_RET_CODE = -19001000, @IBUSI_FLAG = 19001
    SELECT @SBUSI_NAME = N'设置“crm信息库”产品信息', @SSUMMARY = N'设置“crm信息库”产品信息'
    DECLARE @V_DT_INTRUST INT, @V_CLASS_TYPE1_NAME NVARCHAR(30), @V_EXTEND_NO INT, @V_CONDITION NVARCHAR(60)
    SELECT @V_DT_INTRUST = VALUE FROM TSYSCONTROL WHERE FLAG_TYPE = N'DT_INTRUST'
    SELECT @V_CLASS_TYPE1_NAME = TYPE_CONTENT FROM TDICTPARAM WHERE TYPE_VALUE = @IN_CLASS_TYPE1

    BEGIN TRANSACTION

    IF NOT EXISTS (SELECT * FROM TPRODUCT WHERE PRODUCT_ID = @IN_PRODUCT_ID)
    BEGIN
        IF @V_DT_INTRUST = 1 --启用分布式
        BEGIN
            INSERT INTO TPRODUCT(PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME)
                SELECT PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME FROM SRV_Intrust.INTRUST.dbo.TPRODUCT WHERE PRODUCT_ID = @IN_PRODUCT_ID
        END
        ELSE IF (@V_DT_INTRUST = 2) AND EXISTS(SELECT * FROM master..sysdatabases WHERE NAME = N'INTRUST') --本地信托数据库
        BEGIN
            INSERT INTO TPRODUCT(PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME)
                SELECT PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME FROM INTRUST..TPRODUCT WHERE PRODUCT_ID = @IN_PRODUCT_ID
        END
        IF @@ERROR <> 0
        BEGIN
            ROLLBACK TRANSACTION
            RETURN -100
        END
    END

    UPDATE TPRODUCT
        SET CLASS_TYPE1 = @IN_CLASS_TYPE1, CLASS_TYPE1_NAME = @V_CLASS_TYPE1_NAME, ANNOUNCE_URL = @IN_ANNOUNCE_URL
        WHERE PRODUCT_ID = @IN_PRODUCT_ID
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    SELECT @V_CONDITION = 'CLASS_TYPE1='''+@IN_CLASS_TYPE1+''''
    IF EXISTS(SELECT 1 FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPRODUCT' AND FIELD_NAME = '开放期' AND CONDITION = @V_CONDITION)
    BEGIN
        SELECT @V_EXTEND_NO = EXTEND_NO FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPRODUCT' AND FIELD_NAME = '开放期' AND CONDITION = @V_CONDITION
        IF EXISTS(SELECT 1 FROM TEXTENDINFO WHERE EXTEND_NO = @V_EXTEND_NO AND KEY_VALUE = @IN_PRODUCT_ID)
            UPDATE TEXTENDINFO SET EXTEND_VALUE = @IN_KFQ
        ELSE
            INSERT INTO TEXTENDINFO(EXTEND_NO,KEY_VALUE,EXTEND_VALUE) SELECT @V_EXTEND_NO,@IN_PRODUCT_ID,@IN_KFQ
    END
    IF EXISTS(SELECT 1 FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPRODUCT' AND FIELD_NAME = '保障措施' AND CONDITION = @V_CONDITION)
    BEGIN
        SELECT @V_EXTEND_NO = EXTEND_NO FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPRODUCT' AND FIELD_NAME = '保障措施' AND CONDITION = @V_CONDITION
        IF EXISTS(SELECT 1 FROM TEXTENDINFO WHERE EXTEND_NO = @V_EXTEND_NO AND KEY_VALUE = @IN_PRODUCT_ID)
            UPDATE TEXTENDINFO SET EXTEND_VALUE = @IN_BZCS
        ELSE
            INSERT INTO TEXTENDINFO(EXTEND_NO,KEY_VALUE,EXTEND_VALUE) SELECT @V_EXTEND_NO,@IN_PRODUCT_ID,@IN_BZCS
        END
    IF EXISTS(SELECT 1 FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPRODUCT' AND FIELD_NAME = '赎回申请提交期' AND CONDITION = @V_CONDITION)
    BEGIN
        SELECT @V_EXTEND_NO = EXTEND_NO FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPRODUCT' AND FIELD_NAME = '赎回申请提交期' AND CONDITION = @V_CONDITION
        IF EXISTS(SELECT 1 FROM TEXTENDINFO WHERE EXTEND_NO = @V_EXTEND_NO AND KEY_VALUE = @IN_PRODUCT_ID)
            UPDATE TEXTENDINFO SET EXTEND_VALUE = @IN_SHSQTJQ
        ELSE
            INSERT INTO TEXTENDINFO(EXTEND_NO,KEY_VALUE,EXTEND_VALUE) SELECT @V_EXTEND_NO,@IN_PRODUCT_ID,@IN_SHSQTJQ
    END
    IF EXISTS(SELECT 1 FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPRODUCT' AND FIELD_NAME = '收益账户' AND CONDITION = @V_CONDITION)
    BEGIN
        SELECT @V_EXTEND_NO = EXTEND_NO FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPRODUCT' AND FIELD_NAME = '收益账户' AND CONDITION = @V_CONDITION
        IF EXISTS(SELECT 1 FROM TEXTENDINFO WHERE EXTEND_NO = @V_EXTEND_NO AND KEY_VALUE = @IN_PRODUCT_ID)
            UPDATE TEXTENDINFO SET EXTEND_VALUE = @IN_SYZH
        ELSE
            INSERT INTO TEXTENDINFO(EXTEND_NO,KEY_VALUE,EXTEND_VALUE) SELECT @V_EXTEND_NO,@IN_PRODUCT_ID,@IN_SYZH
    END
    IF EXISTS(SELECT 1 FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPRODUCT' AND FIELD_NAME = '直销/代销' AND CONDITION = @V_CONDITION)
    BEGIN
        SELECT @V_EXTEND_NO = EXTEND_NO FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPRODUCT' AND FIELD_NAME = '直销/代销' AND CONDITION = @V_CONDITION
        IF EXISTS(SELECT 1 FROM TEXTENDINFO WHERE EXTEND_NO = @V_EXTEND_NO AND KEY_VALUE = @IN_PRODUCT_ID)
            UPDATE TEXTENDINFO SET EXTEND_VALUE = @IN_ZXDX
        ELSE
            INSERT INTO TEXTENDINFO(EXTEND_NO,KEY_VALUE,EXTEND_VALUE) SELECT @V_EXTEND_NO,@IN_PRODUCT_ID,@IN_ZXDX
    END
    IF EXISTS(SELECT 1 FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPRODUCT' AND FIELD_NAME = '代销机构' AND CONDITION = @V_CONDITION)
    BEGIN
        SELECT @V_EXTEND_NO = EXTEND_NO FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPRODUCT' AND FIELD_NAME = '代销机构' AND CONDITION = @V_CONDITION
        IF EXISTS(SELECT 1 FROM TEXTENDINFO WHERE EXTEND_NO = @V_EXTEND_NO AND KEY_VALUE = @IN_PRODUCT_ID)
            UPDATE TEXTENDINFO SET EXTEND_VALUE = @IN_DXJG
        ELSE
            INSERT INTO TEXTENDINFO(EXTEND_NO,KEY_VALUE,EXTEND_VALUE) SELECT @V_EXTEND_NO,@IN_PRODUCT_ID,@IN_DXJG
    END
    IF EXISTS(SELECT 1 FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPRODUCT' AND FIELD_NAME = '投资顾问/受益人代表' AND CONDITION = @V_CONDITION)
    BEGIN
        SELECT @V_EXTEND_NO = EXTEND_NO FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPRODUCT' AND FIELD_NAME = '投资顾问/受益人代表' AND CONDITION = @V_CONDITION
        IF EXISTS(SELECT 1 FROM TEXTENDINFO WHERE EXTEND_NO = @V_EXTEND_NO AND KEY_VALUE = @IN_PRODUCT_ID)
            UPDATE TEXTENDINFO SET EXTEND_VALUE = @IN_TZGW
        ELSE
            INSERT INTO TEXTENDINFO(EXTEND_NO,KEY_VALUE,EXTEND_VALUE) SELECT @V_EXTEND_NO,@IN_PRODUCT_ID,@IN_TZGW
    END
    IF EXISTS(SELECT 1 FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPRODUCT' AND FIELD_NAME = '基金经理' AND CONDITION = @V_CONDITION)
    BEGIN
        SELECT @V_EXTEND_NO = EXTEND_NO FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPRODUCT' AND FIELD_NAME = '基金经理' AND CONDITION = @V_CONDITION
        IF EXISTS(SELECT 1 FROM TEXTENDINFO WHERE EXTEND_NO = @V_EXTEND_NO AND KEY_VALUE = @IN_PRODUCT_ID)
            UPDATE TEXTENDINFO SET EXTEND_VALUE = @IN_JJJL
        ELSE
            INSERT INTO TEXTENDINFO(EXTEND_NO,KEY_VALUE,EXTEND_VALUE) SELECT @V_EXTEND_NO,@IN_PRODUCT_ID,@IN_JJJL
    END
    IF EXISTS(SELECT 1 FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPRODUCT' AND FIELD_NAME = '开放日' AND CONDITION = @V_CONDITION)
    BEGIN
        SELECT @V_EXTEND_NO = EXTEND_NO FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPRODUCT' AND FIELD_NAME = '开放日' AND CONDITION = @V_CONDITION
        IF EXISTS(SELECT 1 FROM TEXTENDINFO WHERE EXTEND_NO = @V_EXTEND_NO AND KEY_VALUE = @IN_PRODUCT_ID)
            UPDATE TEXTENDINFO SET EXTEND_VALUE = @IN_KFR
        ELSE
            INSERT INTO TEXTENDINFO(EXTEND_NO,KEY_VALUE,EXTEND_VALUE) SELECT @V_EXTEND_NO,@IN_PRODUCT_ID,@IN_KFR
    END

    SELECT @SSUMMARY = N'设置“crm信息库”产品信息'
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
