USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_CHECK_TCUSTMERGE
							@IN_SERIAL_NO        INTEGER,      --记录序号
							@IN_CHECK_FLAG       INTEGER,      --审核标记:1.未审核，2.审核通过，3审核否决
							@IN_INPUT_MAN        INTEGER       --操作员
WITH ENCRYPTION
AS
    SET NOCOUNT ON

    DECLARE @V_ERROR NVARCHAR(200), @IBUSI_FLAG INT, @SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)
    DECLARE @V_FROM_CUST_ID INT,@V_TO_CUST_ID INT,@V_SERIAL_NOS NVARCHAR(800),@V_INPUT_MAN INT
    DECLARE @V_User_ID INT
    SELECT @V_User_ID=User_ID FROM TSYSTEMINFO
    
    BEGIN TRY
    
    SET @IBUSI_FLAG = 30601
    SET @SBUSI_NAME = '审核客户信息合并'
    
    BEGIN TRANSACTION
    IF @IN_CHECK_FLAG=3 --审核否决
    BEGIN
		--中建投要求能自己给自己审核
		IF @V_User_ID<>22 AND EXISTS (SELECT 1 FROM TCUSTMERGE WHERE SERIAL_NO=@IN_SERIAL_NO AND INPUT_MAN=@IN_INPUT_MAN)
			RAISERROR('不能自己审核自己的操作，审核失败',16,1)
		UPDATE TCUSTMERGE SET CHECK_FLAG=@IN_CHECK_FLAG,CHECK_MAN=@IN_INPUT_MAN,CHECK_TIME=GETDATE() WHERE SERIAL_NO=@IN_SERIAL_NO
		IF @@ROWCOUNT=0
			RAISERROR('记录不存在，审核失败',16,1)
	END
	ELSE IF @IN_CHECK_FLAG=2 --审核通过
	BEGIN
		SELECT @V_FROM_CUST_ID=FROM_CUST_ID, @V_TO_CUST_ID=TO_CUST_ID, @V_INPUT_MAN=INPUT_MAN
			FROM TCUSTMERGE WHERE SERIAL_NO=@IN_SERIAL_NO
		IF @V_INPUT_MAN=@IN_INPUT_MAN AND @V_User_ID<>22
			RAISERROR('不能自己审核自己的操作，审核失败',16,1)
		--客户预约记录合并
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM TPRECONTRACT WHERE CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'TPRECONTRACT',@V_SERIAL_NOS,'CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE TPRECONTRACT SET CUST_ID = @V_TO_CUST_ID WHERE CUST_ID = @V_FROM_CUST_ID
		END
		--开始修改信托业务系统中的表
		--1.预约表
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUST..TPRECONTRACT WHERE CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUST..TPRECONTRACT',@V_SERIAL_NOS,'CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUST..TPRECONTRACT SET CUST_ID = @V_TO_CUST_ID WHERE CUST_ID = @V_FROM_CUST_ID
		END
		--2.认购合同表
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUST..TCONTRACT WHERE CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUST..TCONTRACT',@V_SERIAL_NOS,'CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUST..TCONTRACT SET CUST_ID = @V_TO_CUST_ID WHERE CUST_ID = @V_FROM_CUST_ID
		END
		--3.申购合同表
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUST..TCONTRACTSG WHERE CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUST..TCONTRACTSG',@V_SERIAL_NOS,'CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUST..TCONTRACTSG SET CUST_ID = @V_TO_CUST_ID WHERE CUST_ID = @V_FROM_CUST_ID
		END
		--4.受益人表
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUST..TBENIFITOR WHERE CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUST..TBENIFITOR',@V_SERIAL_NOS,'CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUST..TBENIFITOR SET CUST_ID = @V_TO_CUST_ID WHERE CUST_ID = @V_FROM_CUST_ID
		END
		--5.
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUST..TBENLIST WHERE CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUST..TBENLIST',@V_SERIAL_NOS,'CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUST..TBENLIST SET CUST_ID = @V_TO_CUST_ID WHERE CUST_ID = @V_FROM_CUST_ID
		END
		--6.收益分配明细表
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUST..TGAINDETAIL WHERE CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUST..TGAINDETAIL',@V_SERIAL_NOS,'CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUST..TGAINDETAIL SET CUST_ID = @V_TO_CUST_ID WHERE CUST_ID = @V_FROM_CUST_ID
		END
		--7.客户收益明细表
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUST..TDEPLOY WHERE CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUST..TDEPLOY',@V_SERIAL_NOS,'CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUST..TDEPLOY SET CUST_ID = @V_TO_CUST_ID WHERE CUST_ID = @V_FROM_CUST_ID
		END
		--8.受益权转让明细表(转让方)
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUST..TBENCHANGES WHERE FROM_CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUST..TBENCHANGES',@V_SERIAL_NOS,'FROM_CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUST..TBENCHANGES SET FROM_CUST_ID = @V_TO_CUST_ID WHERE FROM_CUST_ID = @V_FROM_CUST_ID
		END
		--9.受益权转让明细表(受让方)
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUST..TBENCHANGES WHERE TO_CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUST..TBENCHANGES',@V_SERIAL_NOS,'TO_CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUST..TBENCHANGES SET TO_CUST_ID = @V_TO_CUST_ID WHERE TO_CUST_ID = @V_FROM_CUST_ID
		END
		--10.客户家底成员信息
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUST..TCUSTFAMILYINFO WHERE CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUST..TCUSTFAMILYINFO',@V_SERIAL_NOS,'CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUST..TCUSTFAMILYINFO SET CUST_ID = @V_TO_CUST_ID WHERE CUST_ID = @V_FROM_CUST_ID
		END
		--11.认购、申购费用明细表
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUST..TCUSTFEEDETAIL WHERE CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUST..TCUSTFEEDETAIL',@V_SERIAL_NOS,'CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUST..TCUSTFEEDETAIL SET CUST_ID = @V_TO_CUST_ID WHERE CUST_ID = @V_FROM_CUST_ID
		END
		--12.份额变动明细表
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUST..TBENAMOUNTDETAIL WHERE CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUST..TBENAMOUNTDETAIL',@V_SERIAL_NOS,'CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUST..TBENAMOUNTDETAIL SET CUST_ID = @V_TO_CUST_ID WHERE CUST_ID = @V_FROM_CUST_ID
		END
		--13.客户附加信息表
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUST..TAMCUSTINFO WHERE CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUST..TAMCUSTINFO',@V_SERIAL_NOS,'CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUST..TAMCUSTINFO SET CUST_ID = @V_TO_CUST_ID WHERE CUST_ID = @V_FROM_CUST_ID
		END
		--14.股东信息表
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUST..TAMSHAREHOLDER WHERE CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUST..TAMSHAREHOLDER',@V_SERIAL_NOS,'CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUST..TAMSHAREHOLDER SET CUST_ID = @V_TO_CUST_ID WHERE CUST_ID = @V_FROM_CUST_ID
		END
		--15.客户银行账号表
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUST..TCUSTBANKACCT WHERE CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUST..TCUSTBANKACCT',@V_SERIAL_NOS,'CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUST..TCUSTBANKACCT SET CUST_ID = @V_TO_CUST_ID WHERE CUST_ID = @V_FROM_CUST_ID
		END
		--16.客户信息修改明细表
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUST..TCUSTINFODETAIL WHERE CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUST..TCUSTINFODETAIL',@V_SERIAL_NOS,'CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUST..TCUSTINFODETAIL SET CUST_ID = @V_TO_CUST_ID WHERE CUST_ID = @V_FROM_CUST_ID
		END
		--17.资金到帐明细表
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUST..TMONEYDETAIL WHERE CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUST..TMONEYDETAIL',@V_SERIAL_NOS,'CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUST..TMONEYDETAIL SET CUST_ID = @V_TO_CUST_ID WHERE CUST_ID = @V_FROM_CUST_ID
		END
		--18.资金销售流水
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUST..TMONEYDATA WHERE CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUST..TMONEYDATA',@V_SERIAL_NOS,'CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUST..TMONEYDATA SET CUST_ID = @V_TO_CUST_ID WHERE CUST_ID = @V_FROM_CUST_ID
		END
		--为辅助账做准备
			DECLARE @V_FROM_AATDETAIL_NO_1001    NVARCHAR(60)       --辅助账明细编号(源客户)-受益人
			DECLARE @V_FROM_AATDETAIL_NO_1002    NVARCHAR(60)       --辅助账明细编号(源客户)-委托人
			DECLARE @V_TO_AATDETAIL_NO_1001      NVARCHAR(60)       --辅助账明细编号(目的客户)-受益人
			DECLARE @V_TO_AATDETAIL_NO_1002      NVARCHAR(60)       --辅助账明细编号(目的客户)-委托人
			DECLARE @V_TO_AATDETAIL_NAME         NVARCHAR(100)      --辅助账明细名称(目的客户)
			SELECT @V_FROM_AATDETAIL_NO_1001 ='1001_'+CUST_NO,
				   @V_FROM_AATDETAIL_NO_1002 ='1002_'+CUST_NO--,@V_FROM_AATDETAIL_NAME =CUST_NAME
				FROM TCustomers WHERE CUST_ID = @V_FROM_CUST_ID
			SELECT @V_TO_AATDETAIL_NO_1001 ='1001_'+CUST_NO,
				   @V_TO_AATDETAIL_NO_1002 ='1002_'+CUST_NO,@V_TO_AATDETAIL_NAME =CUST_NAME
				FROM TCustomers 
				WHERE CUST_ID = @V_TO_CUST_ID
		--17.凭证分录之辅助账目TAsstActPostList
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUST..TAsstActPostList WHERE AATDETAIL_NO=@V_FROM_AATDETAIL_NO_1001
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUST..TAsstActPostList',@V_SERIAL_NOS,@V_FROM_AATDETAIL_NO_1001,@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUST..TAsstActPostList SET AATDETAIL_NO =@V_TO_AATDETAIL_NO_1001, AATDETAIL_NAME =@V_TO_AATDETAIL_NAME
                WHERE AATDETAIL_NO =@V_FROM_AATDETAIL_NO_1001
		END
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUST..TAsstActPostList WHERE AATDETAIL_NO=@V_TO_AATDETAIL_NO_1002
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUST..TAsstActPostList',@V_SERIAL_NOS,@V_FROM_AATDETAIL_NO_1002,@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUST..TAsstActPostList SET AATDETAIL_NO =@V_TO_AATDETAIL_NO_1002, AATDETAIL_NAME =@V_TO_AATDETAIL_NAME
                WHERE AATDETAIL_NO =@V_FROM_AATDETAIL_NO_1002
		END
        --18.辅助账类型明细表TAsstActTypeDetails
        /*SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUST..TAsstActTypeDetails WHERE AATDETAIL_NO=@V_FROM_AATDETAIL_NO_1001
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUST..TAsstActTypeDetails',@V_SERIAL_NOS,@V_FROM_AATDETAIL_NO_1001,@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUST..TAsstActTypeDetails SET AATDETAIL_NO =@V_TO_AATDETAIL_NO_1001, AATDETAIL_NAME =@V_TO_AATDETAIL_NAME
                WHERE AATDETAIL_NO =@V_FROM_AATDETAIL_NO_1001
		END
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUST..TAsstActTypeDetails WHERE AATDETAIL_NO=@V_TO_AATDETAIL_NO_1002
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUST..TAsstActTypeDetails',@V_SERIAL_NOS,@V_FROM_AATDETAIL_NO_1002,@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUST..TAsstActTypeDetails SET AATDETAIL_NO =@V_TO_AATDETAIL_NO_1002, AATDETAIL_NAME =@V_TO_AATDETAIL_NAME
                WHERE AATDETAIL_NO =@V_FROM_AATDETAIL_NO_1002
		END*/
        --19.辅助账历史余额表 INTRUSTHistory..TAssActDetailYE
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUSTHistory..TAssActDetailYE WHERE AATDETAIL_NO=@V_FROM_AATDETAIL_NO_1001
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUSTHistory..TAssActDetailYE',@V_SERIAL_NOS,@V_FROM_AATDETAIL_NO_1001,@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUSTHistory..TAssActDetailYE SET AATDETAIL_NO =@V_TO_AATDETAIL_NO_1001, AATDETAIL_NAME =@V_TO_AATDETAIL_NAME
                WHERE AATDETAIL_NO =@V_FROM_AATDETAIL_NO_1001
		END
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUSTHistory..TAssActDetailYE WHERE AATDETAIL_NO=@V_TO_AATDETAIL_NO_1002
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUSTHistory..TAssActDetailYE',@V_SERIAL_NOS,@V_FROM_AATDETAIL_NO_1002,@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUSTHistory..TAssActDetailYE SET AATDETAIL_NO =@V_TO_AATDETAIL_NO_1002, AATDETAIL_NAME =@V_TO_AATDETAIL_NAME
                WHERE AATDETAIL_NO =@V_FROM_AATDETAIL_NO_1002
		END
        --20.资金变动表 INTRUSTHistory..HCUSTZJBD
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUSTHistory..HCUSTZJBD WHERE CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUSTHistory..HCUSTZJBD',@V_SERIAL_NOS,'CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUSTHistory..HCUSTZJBD SET CUST_ID = @V_TO_CUST_ID WHERE CUST_ID = @V_FROM_CUST_ID
		END
		--21.受益份额明细历史表 INTRUSTHistory..HBENLIST
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUSTHistory..HBENLIST WHERE CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUSTHistory..HBENLIST',@V_SERIAL_NOS,'CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUSTHistory..HBENLIST SET CUST_ID = @V_TO_CUST_ID WHERE CUST_ID = @V_FROM_CUST_ID
		END
		--22.受益份额历史表 INTRUSTHistory..HBENIFITOR
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM INTRUSTHistory..HBENLIST WHERE CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'INTRUSTHistory..HBENLIST',@V_SERIAL_NOS,'CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE INTRUSTHistory..HBENLIST SET CUST_ID = @V_TO_CUST_ID WHERE CUST_ID = @V_FROM_CUST_ID
		END
		--23.投资人份额明细表INTRUSTHistory..HBENCUSTYE    未做恢复准备，因内部处理过于复杂
		EXEC INTRUST..SP_INNER_COMBINE_HBENCUSTYE 1,@V_FROM_CUST_ID,@V_TO_CUST_ID
		--24.非信托产品合同表(只在CRM系统内)
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SUBSCRIBE_ID AS VARCHAR)+',' FROM TSUBSCRIBE WHERE CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'TSUBSCRIBE',@V_SERIAL_NOS,'CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE TSUBSCRIBE SET CUST_ID = @V_TO_CUST_ID WHERE CUST_ID = @V_FROM_CUST_ID
		END
		--25.非信托产品持有份额表(只在CRM系统内)
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM TQUOTIENT WHERE CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'TQUOTIENT',@V_SERIAL_NOS,'CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE TQUOTIENT SET CUST_ID = @V_TO_CUST_ID WHERE CUST_ID = @V_FROM_CUST_ID
		END
		--26.非信托产品持有份额变动表(只在CRM系统内)
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM TQUOTIENTCHANGE WHERE CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'TQUOTIENTCHANGE',@V_SERIAL_NOS,'CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE TQUOTIENTCHANGE SET CUST_ID = @V_TO_CUST_ID WHERE CUST_ID = @V_FROM_CUST_ID
		END
		--27.非信托产品收益分配表(只在CRM系统内)
		SET @V_SERIAL_NOS='' --把待修改的记录号以逗号间隔的字符串保存
		SELECT @V_SERIAL_NOS=@V_SERIAL_NOS+CAST(SERIAL_NO AS VARCHAR)+',' FROM TPROFIT WHERE CUST_ID=@V_FROM_CUST_ID
		IF ISNULL(@V_SERIAL_NOS,'')<>'' --有记录才保存/修改
		BEGIN
			INSERT INTO TCUSTMERGEDETAIL(MERGE_SERIAL_NO,TABEL_NAME,RECORD_ID,COLUMN_NAME,INPUT_MAN,INPUT_TIME)
				SELECT @IN_SERIAL_NO,'TPROFIT',@V_SERIAL_NOS,'CUST_ID',@IN_INPUT_MAN,GETDATE()
			UPDATE TPROFIT SET CUST_ID = @V_TO_CUST_ID WHERE CUST_ID = @V_FROM_CUST_ID
		END
		--合并时，客户各字段信息合并，未处理
		--
		--合并时，源客户不做真正删除，只做状态标记
		UPDATE TCustomers SET STATUS = N'112805', STATUS_NAME = N'删除'  WHERE CUST_ID = @V_FROM_CUST_ID
		UPDATE INTRUST..TCUSTOMERINFO SET STATUS = N'112805', STATUS_NAME = N'删除'  WHERE CUST_ID = @V_FROM_CUST_ID
		UPDATE TCUSTMERGE SET CHECK_FLAG=@IN_CHECK_FLAG,CHECK_MAN=@IN_INPUT_MAN,CHECK_TIME=GETDATE() WHERE SERIAL_NO=@IN_SERIAL_NO
	END
    
    --日志记录
    SET @SSUMMARY = @SBUSI_NAME 
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    COMMIT TRANSACTION
    END TRY

    --异常处理
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION
        DECLARE @V_ERROR_STR NVARCHAR(1000),@V_ERROR_NUMBER INT,@V_ERROR_SEVERITY INT,@V_ERROR_STATE INT,
                @V_ERROR_PROCEDURE sysname,@V_ERROR_LINE INT,@V_ERROR_MESSAGE NVARCHAR(4000)
        SELECT @V_ERROR_STR = N'Message:%s<BR><font color = "white">Error:%d,Level:%d,State:%d,Procedure:%s,Line:%d</font>',
               @V_ERROR_NUMBER = ERROR_NUMBER(),
               @V_ERROR_SEVERITY = ERROR_SEVERITY(),
               @V_ERROR_STATE = ERROR_STATE(),
               @V_ERROR_PROCEDURE = ERROR_PROCEDURE(),
               @V_ERROR_LINE = ERROR_LINE(),
               @V_ERROR_MESSAGE = ERROR_MESSAGE()
        RAISERROR(@V_ERROR_STR,@V_ERROR_SEVERITY,1,@V_ERROR_MESSAGE,@V_ERROR_NUMBER,@V_ERROR_SEVERITY,@V_ERROR_STATE,
                  @V_ERROR_PROCEDURE,@V_ERROR_LINE)
        RETURN -100
    END CATCH
    RETURN 100
GO
