USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TPREPRODUCT @IN_PREPRODUCT_ID     INT,          --预发行产品ID
                                      @IN_PREPRODUCT_NAME   NVARCHAR(60), --预发行产品名称
                                      @IN_STATUS            NVARCHAR(10), --状态(1102)  110299:推介期和正常期的产品
                                      @IN_INPUT_MAN         INT,
                                      @IN_QUOTACHECK_FLAG   INT = NULL    --配额审核标志 1设置未审核2设置已审核3调整未审核4调整已审核
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    SET @IN_PREPRODUCT_ID = ISNULL(@IN_PREPRODUCT_ID,0)
    SET @IN_PREPRODUCT_NAME = ISNULL(@IN_PREPRODUCT_NAME,'')
    SET @IN_STATUS = ISNULL(@IN_STATUS,'')
    SET @IN_QUOTACHECK_FLAG = ISNULL(@IN_QUOTACHECK_FLAG,0)
	IF  @IN_STATUS = '110299' --推介期和正常期的产品
	BEGIN
		SELECT * FROM TPREPRODUCT
			WHERE (PREPRODUCT_ID = @IN_PREPRODUCT_ID OR @IN_PREPRODUCT_ID = 0)
				AND(PREPRODUCT_NAME LIKE '%'+@IN_PREPRODUCT_NAME+'%')
				AND(STATUS = '110202' OR STATUS = '110203')	
				AND(ISNULL(QUOTACHECK_FLAG,1) = @IN_QUOTACHECK_FLAG OR @IN_QUOTACHECK_FLAG = 0)
			ORDER BY PREPRODUCT_ID DESC
	END
	ELSE
	BEGIN
		SELECT * FROM TPREPRODUCT
			WHERE (PREPRODUCT_ID = @IN_PREPRODUCT_ID OR @IN_PREPRODUCT_ID = 0)
				AND(PREPRODUCT_NAME LIKE '%'+@IN_PREPRODUCT_NAME+'%')
				AND(STATUS = @IN_STATUS OR @IN_STATUS = '')
				AND(ISNULL(QUOTACHECK_FLAG,1) = @IN_QUOTACHECK_FLAG OR @IN_QUOTACHECK_FLAG = 0)
			ORDER BY PREPRODUCT_ID DESC	
	END
GO
