USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TActivitiesLoad   @IN_SERIAL_NO           INT                     -- 活动任务序列号
WITH ENCRYPTION
AS
    SELECT  SERIAL_NO,ACTIVE_TYPE,ACTIVE_TYPE_NAME,ACTIVE_THEME,START_DATE,END_DATE,MANAGE_CODE,MANAGE_MAN,CUSTOMER_TYPE,ACTIVE_PLAN,
            ACTIVE_TRACE,ACTIVE_RESULT,ACTIVE_FLAG,COMPLETE_TIME,ACTIVITY_FEE,CREATOR_NAME,CREATOR,ACTIVE_CODE
    FROM    TACTIVITIES
    WHERE   (SERIAL_NO = @IN_SERIAL_NO OR ISNULL(@IN_SERIAL_NO,0) = 0)
GO
