USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TEAMINFOBYREGMONEY    @IN_BOOK_CODE   INTEGER,        --帐套
                                                @IN_REG_MONEY   DECIMAL(16,3)   --预登记金额
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    DECLARE @V_ALREADY_TEAM_NO  NVARCHAR(30)    --已排到的团队编号
    DECLARE @V_ROUND_TEAM_NO    NVARCHAR(30)    --轮到的团队编号
    
    SELECT @V_ALREADY_TEAM_NO = MAX((CASE WHEN ISNULL(@IN_REG_MONEY,0) < 3000000 THEN TEAM_NO_299 ELSE TEAM_NO_300 END)) 
        FROM INTRUST..TCUSTREGINFO WHERE BOOK_CODE = @IN_BOOK_CODE
    
    IF ISNULL(@V_ALREADY_TEAM_NO,'') <> '' BEGIN
        SELECT @V_ROUND_TEAM_NO = MIN(TEAM_NO) FROM TMANAGERTEAMS WHERE TEAM_NO > @V_ALREADY_TEAM_NO AND MARK_FLAG = 1
        --只有一个营销团队
        IF ISNULL(@V_ROUND_TEAM_NO,'') = ''
            SELECT @V_ROUND_TEAM_NO = MIN(TEAM_NO) FROM TMANAGERTEAMS WHERE MARK_FLAG = 1
    END
    ELSE BEGIN
        SELECT @V_ROUND_TEAM_NO = MIN(TEAM_NO) FROM TMANAGERTEAMS WHERE MARK_FLAG = 1
    END
    
    SELECT * FROM TMANAGERTEAMS WHERE TEAM_NO = @V_ROUND_TEAM_NO
GO
