USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_DEL_TCOMAINTAINDETAIL @IN_MAINTAINDETAIL_ID             INT, --维护费明细ID
                                          @IN_INPUT_MAN                     INT,  --录入操作员
                                          @IN_MAINTAIN_ID                   INT   --维护合同ID
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    DECLARE @V_COCONTRACTMAINTAIN_SUB_BH NVARCHAR(200) --维护合同编号
    DECLARE @V_MAINTAIN_ID INT   --维护费(维护合同)ID
    DECLARE @V_MAIN_PRO_NAME NVARCHAR(60)   --维护项目名称

    SELECT @SBUSI_NAME = N'合同管理之删除维护合同明细'
    SELECT @SSUMMARY = N'合同管理之删除维护合同明细'
    SELECT @IBUSI_FLAG = 50001
    SELECT @V_RET_CODE = -50001000

    BEGIN TRANSACTION

    DELETE FROM TCOMAINTAINDETAIL WHERE MAINTAINDETAIL_ID = @IN_MAINTAINDETAIL_ID AND MAINTAIN_ID = @IN_MAINTAIN_ID
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    --
    SELECT @SSUMMARY = N'合同管理之删除维护合同明细'
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
