USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TPRINTTEMPLATE @IN_TEMPLATE_ID     INT,            --记录号
                                         @IN_CATALOG_CODE    NVARCHAR(24),   --分类代码
                                         @IN_TEMPLATE_CODE   NVARCHAR(24),   --模板代码
                                         @IN_TEMPLATE_NAME   NVARCHAR(60)    --模板名称
WITH ENCRYPTION 
AS
    DECLARE @V_USER_ID INT
    SELECT @V_USER_ID=USER_ID FROM TSYSTEMINFO
    IF @V_USER_ID=24 /*厦门信托：取用了INTRUST的打印模板*/
    BEGIN
		SELECT * FROM INTRUST..TPRINTTEMPLATE B LEFT JOIN INTRUST..TPRINTCATALOG A ON B.CATALOG_CODE=A.CATALOG_CODE
			WHERE (B.TEMPLATE_ID = @IN_TEMPLATE_ID OR ISNULL(@IN_TEMPLATE_ID,0) = 0) 
				AND (B.CATALOG_CODE = @IN_CATALOG_CODE OR ISNULL(@IN_CATALOG_CODE,'') = '')
				AND (B.TEMPLATE_CODE = @IN_TEMPLATE_CODE OR ISNULL(@IN_TEMPLATE_CODE,'') = '')
				AND (B.TEMPLATE_NAME LIKE '%' + @IN_TEMPLATE_NAME + '%' OR ISNULL(@IN_TEMPLATE_NAME,'') = '')
		RETURN
    END
    SELECT B.*,A.CATALOG_NAME
        FROM TPRINTCATALOG A,TPRINTTEMPLATE B
        WHERE A.CATALOG_CODE = B.CATALOG_CODE AND 
              (B.TEMPLATE_ID = @IN_TEMPLATE_ID OR ISNULL(@IN_TEMPLATE_ID,0) = 0) AND
              (B.CATALOG_CODE = @IN_CATALOG_CODE OR ISNULL(@IN_CATALOG_CODE,'') = '') AND 
              (B.TEMPLATE_CODE = @IN_TEMPLATE_CODE OR ISNULL(@IN_TEMPLATE_CODE,'') = '') AND 
              (B.TEMPLATE_NAME LIKE '%' + @IN_TEMPLATE_NAME + '%' OR ISNULL(@IN_TEMPLATE_NAME,'') = '')
GO
