USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_IMPORT_PRECUSTOMERCON   @IN_CUSTOMER_ID		NVARCHAR(10),		--总行客户号
                                            @IN_CUST_NAME       NVARCHAR(100), 		--客户名称
                                            @IN_SEX_NAME		NVARCHAR(10),		--性别
                                            @IN_MOBILE          NVARCHAR(100), 		--手机
                                            @IN_PRE_MONEY		DEC(16,3),			--预约金额
                                            @IN_PRE_DATE		INTEGER,            --预约日期
                                            @IN_PRODUCT_NAME	NVARCHAR(100),      --预约产品名称
											@IN_PRODUCT_CODE	NVARCHAR(10),		--预约产品编号
                                            @IN_ADDRESS         NVARCHAR(60),  		--联系地址
                                            @IN_EMAIL           NVARCHAR(60),  		--EMAIL
                                            @IN_INPUT_MAN		INTEGER,			--导入人,
											@IN_FILE_NAME		NVARCHAR(60)		--导入文件名称

WITH ENCRYPTION
AS
    SET NOCOUNT ON
    SET XACT_ABORT ON
    DECLARE @V_ERROR NVARCHAR(200),@V_PRE_CODE NVARCHAR(16)
    DECLARE @V_NUM INT,@V_NUM_MAX INT,@V_PRE_CODE_MAX NVARCHAR(16)
    DECLARE @V_RET_CODE INT, @IBUSI_FLAG INT, @SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)
	DECLARE @V_SEX INT,@V_PRODUCT_ID INT
	DECLARE @V_INPUT_TIME DATETIME

	BEGIN TRY
    SELECT @IBUSI_FLAG = 2030308,@V_RET_CODE = -10110000
	SET @V_SEX = CASE @IN_SEX_NAME WHEN '男' THEN 1 WHEN '女' THEN 2 END
	SELECT @V_INPUT_TIME = GETDATE()
	SELECT @V_PRODUCT_ID = PRODUCT_ID
		FROM INTRUST..TPRODUCT
		WHERE PRODUCT_NAME = @IN_PRODUCT_NAME
		AND (PRODUCT_CODE  = @IN_PRODUCT_CODE)
	
	--不能重复导入
	IF EXISTS(SELECT 1 FROM PRECUSTOMERCON WHERE FILE_NAME = @IN_FILE_NAME)
	BEGIN
		SET @V_ERROR = '文件:'+@IN_FILE_NAME+'已有人做过导入！'
        RAISERROR(@V_ERROR,16,1)
	END
	
	--IF EXISTS(SELECT 1 FROM PRE WHERE FILE_NAME = @IN_FILE_NAME AND TURN_FLAG = 2)
	--BEGIN
	--	SET @V_ERROR = '文件:'+@IN_FILE_NAME+'已有人做过导入！'
    --    RAISERROR(@V_ERROR,16,1)
	--END
	
    IF ISNULL(@V_PRODUCT_ID,0)= 0
    BEGIN
        SET @V_ERROR = '产品名称:'+@IN_PRODUCT_NAME+'在系统中不存在,请先录入产品信息!'
        RAISERROR(@V_ERROR,16,1)
    END
    ELSE
    BEGIN
        SELECT @V_PRE_CODE = MAX(PRE_CODE) FROM INTRUST..TPRECONTRACT WHERE PRODUCT_ID = @V_PRODUCT_ID
        SET @V_PRE_CODE = CONVERT(INT,@V_PRE_CODE)+1
    END

    -- 自动生成一个预约编号
    IF ISNULL(@V_PRE_CODE,'') = ''
    BEGIN
        SELECT @V_NUM=COUNT(*),@V_PRE_CODE_MAX=MAX(PRE_CODE) FROM INTRUST..TPRECONTRACT WHERE PRODUCT_ID = @V_PRODUCT_ID
		IF @V_NUM IS NULL OR @V_NUM = 0
			SELECT @V_NUM = 1
		ELSE
			SELECT @V_NUM = @V_NUM + 1
		IF @V_PRE_CODE_MAX IS NULL OR @V_PRE_CODE_MAX = ''
			SELECT @V_NUM_MAX = 1
			ELSE
			SELECT @V_NUM_MAX = CONVERT(INT,@V_PRE_CODE_MAX)+1
	
		IF @V_NUM_MAX > @V_NUM
			SELECT @V_NUM = @V_NUM_MAX
		END
		ELSE
		BEGIN
			SELECT @V_NUM = CONVERT(INT,@V_PRE_CODE)
	END
	--
	IF @V_NUM < 10
	SELECT @V_PRE_CODE ='00'+RTRIM(CONVERT(CHAR(8),@V_NUM))
	ELSE IF (@V_NUM < 100) AND (@V_NUM >=10)
		SELECT @V_PRE_CODE ='0'+RTRIM(CONVERT(CHAR(8),@V_NUM))
	ELSE
       SELECT @V_PRE_CODE =+RTRIM(CONVERT(CHAR(8),@V_NUM))



	INSERT INTO PRECUSTOMERCON(CUSTOMER_ID,CUST_NAME,SEX_NAME,MOBILE,PRE_MONEY,PRE_DATE,PRODUCT_NAME,
			ADDRESS,E_MAIL,PRODUCT_ID,PRODUCT_CODE,SEX,INPUT_MAN,PRE_CODE,INPUT_TIME,FILE_NAME)
		VALUES(@IN_CUSTOMER_ID,@IN_CUST_NAME,@IN_SEX_NAME,@IN_MOBILE,@IN_PRE_MONEY,@IN_PRE_DATE,@IN_PRODUCT_NAME,
			@IN_ADDRESS,@IN_EMAIL,@V_PRODUCT_ID,@IN_PRODUCT_CODE,@V_SEX,@IN_INPUT_MAN,@V_PRE_CODE,@V_INPUT_TIME,@IN_FILE_NAME)
	IF @@ERROR <> 0
	BEGIN
		ROLLBACK TRANSACTION
		RETURN -100
	END


    SET @SBUSI_NAME = N'导入预约信息'
    SET @SSUMMARY = N'导入预约信息'
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    END TRY

    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION

        DECLARE @V_ERROR_STR NVARCHAR(1000),@V_ERROR_NUMBER INT,@V_ERROR_SEVERITY INT,@V_ERROR_STATE INT,
                @V_ERROR_PROCEDURE sysname,@V_ERROR_LINE INT,@V_ERROR_MESSAGE NVARCHAR(4000)
        SELECT @V_ERROR_STR = N',Message %s,Error %d,Level %d,State %d,Procedure %s,Line %d',
               @V_ERROR_NUMBER = ERROR_NUMBER(),
               @V_ERROR_SEVERITY = ERROR_SEVERITY(),
               @V_ERROR_STATE = ERROR_STATE(),
               @V_ERROR_PROCEDURE = ERROR_PROCEDURE(),
               @V_ERROR_LINE = ERROR_LINE(),
               @V_ERROR_MESSAGE = ERROR_MESSAGE()

        RAISERROR(@V_ERROR_STR,@V_ERROR_MESSAGE,@V_ERROR_SEVERITY,1,@V_ERROR_NUMBER,@V_ERROR_SEVERITY,
                  @V_ERROR_STATE,@V_ERROR_PROCEDURE,@V_ERROR_LINE)
        RETURN -100

    END CATCH
    RETURN 100
GO
