USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TERRORINFO @IN_ERROR_ID INT,
                                     @IN_LANGUAGE_TYPE INT = 1,  --1.zh_CN;2.en_US
                                     @OUT_ERROR_NAME NVARCHAR(200) OUTPUT
WITH ENCRYPTION
AS
    DECLARE @V_MSG1 NVARCHAR(100), @V_MSG2 NVARCHAR(100), @V_MSG3 NVARCHAR(100), @V_MSG4 NVARCHAR(100), @V_MSG5 NVARCHAR(100)
    IF NOT EXISTS(SELECT * FROM TERRORINFO WHERE ERROR_ID = @IN_ERROR_ID)
    BEGIN
        SELECT @OUT_ERROR_NAME = N'错误号为：'+CONVERT(NVARCHAR(16),@IN_ERROR_ID)   -- 错误信息不存在
            RETURN 100
    END
    IF @IN_LANGUAGE_TYPE = 1
    BEGIN
        SELECT @OUT_ERROR_NAME = ERROR_NAME, @V_MSG1 = MSG1, @V_MSG2 = MSG2, @V_MSG3 = MSG3, @V_MSG4 = MSG4, @V_MSG5 = MSG5
        FROM TERRORINFO WHERE ERROR_ID = @IN_ERROR_ID
    END
    ELSE
    BEGIN
        SELECT @OUT_ERROR_NAME = ISNULL(ERROR_NAME_EN,ERROR_NAME), @V_MSG1 = MSG1, @V_MSG2 = MSG2, @V_MSG3 = MSG3, @V_MSG4 = MSG4, @V_MSG5 = MSG5
        FROM TERRORINFO WHERE ERROR_ID = @IN_ERROR_ID
    END
--    SELECT @OUT_ERROR_NAME = @OUT_ERROR_NAME + ' ' + @V_MSG1 + ' ' + @V_MSG2 + ' ' + @V_MSG3 + ' ' + @V_MSG4 + ' ' + @V_MSG5
    SELECT @OUT_ERROR_NAME = REPLACE(@OUT_ERROR_NAME, '%1', ISNULL(@V_MSG1,''))
    SELECT @OUT_ERROR_NAME = REPLACE(@OUT_ERROR_NAME, '%2', ISNULL(@V_MSG2,''))
    SELECT @OUT_ERROR_NAME = REPLACE(@OUT_ERROR_NAME, '%3', ISNULL(@V_MSG3,''))
    SELECT @OUT_ERROR_NAME = REPLACE(@OUT_ERROR_NAME, '%4', ISNULL(@V_MSG4,''))
    SELECT @OUT_ERROR_NAME = REPLACE(@OUT_ERROR_NAME, '%5', ISNULL(@V_MSG5,''))
--    UPDATE TERRORINFO SET MSG1 = N'', MSG2 = N'', MSG3 = N'', MSG4 = N'', MSG5 = N'' WHERE ERROR_ID = @IN_ERROR_ID
GO
