USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TDICTPARAM_TREE @IN_TYPE_ID   INT,
                                          @IN_TYPE_VALUE NVARCHAR(10) =''
WITH ENCRYPTION
AS

    SELECT [SERIAL_NO]
		  ,[TYPE_ID]
		  ,[TYPE_NAME]
		  ,[TYPE_VALUE]
		  ,[TYPE_CONTENT]
		  ,[ADDITIVE_VALUE]
		  ,[AML_VALUE]
		  ,0 AS BOTTOM_FLAG,0 AS LEVEL_ID,TYPE_VALUE AS P_TYPE_VALUE INTO #TEMP_TDICTPARAM
        FROM TDICTPARAM WHERE TYPE_ID =@IN_TYPE_ID AND TYPE_VALUE LIKE ISNULL(@IN_TYPE_VALUE,'') +'%'
    --匹配相似度
    SELECT A.TYPE_VALUE AS TYPE_VALUE1,B.TYPE_VALUE AS TYPE_VALUE2 INTO #TEMP_TDICTPARAM2
        FROM #TEMP_TDICTPARAM A,#TEMP_TDICTPARAM B
            WHERE B.TYPE_VALUE LIKE A.TYPE_VALUE+'%'
    --保存记录数
    SELECT TYPE_VALUE1,COUNT(*) AS NUM INTO #TEMP_TDICTPARAM3
        FROM #TEMP_TDICTPARAM2 GROUP BY TYPE_VALUE1
    --更改末级标志
    UPDATE #TEMP_TDICTPARAM
        SET BOTTOM_FLAG =1
        FROM #TEMP_TDICTPARAM A,#TEMP_TDICTPARAM3 B
        WHERE A.TYPE_VALUE =B.TYPE_VALUE1 AND B.NUM =1
    --更新级层关系
    UPDATE #TEMP_TDICTPARAM
        SET LEVEL_ID =LEN(TYPE_VALUE) -5
    --
    UPDATE  #TEMP_TDICTPARAM
        SET P_TYPE_VALUE =''
            WHERE LEN(TYPE_VALUE) =6
    --
    UPDATE  #TEMP_TDICTPARAM
        SET P_TYPE_VALUE =SUBSTRING(TYPE_VALUE,1,LEN(TYPE_VALUE) -1)
            WHERE LEN(TYPE_VALUE) >6
    --
    IF ISNULL(@IN_TYPE_VALUE,'') =''
        SELECT * FROM #TEMP_TDICTPARAM WHERE LEN(TYPE_VALUE) =6
    ELSE
        SELECT * FROM #TEMP_TDICTPARAM WHERE TYPE_VALUE LIKE @IN_TYPE_VALUE+'_'

GO
