USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_STAT_PRODUCTPRE @IN_INPUT_MAN INT = NULL
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    DECLARE @V_DT_INTRUST INT, @V_DATA_TYPE INT
    SELECT @V_DT_INTRUST = VALUE FROM TSYSCONTROL WHERE FLAG_TYPE = N'DT_INTRUST'
    IF @V_DT_INTRUST = 1 --启用分布式
        SELECT A.PRODUCT_ID,A.PRODUCT_CODE, A.PRODUCT_NAME, A.PRE_MAX_MONEY, ISNULL(C.TA_FLAG,2) AS TA_FLAG,
               CASE ISNULL(C.TA_FLAG,2) WHEN 1 THEN '代销' ELSE '直销' END AS TA_FLAG_NAME,
               CASE A.PERIOD_UNIT WHEN 1 THEN CONVERT(NVARCHAR(30),A.VALID_PERIOD) + '天'
                                  WHEN 2 THEN CONVERT(NVARCHAR(30),A.VALID_PERIOD) + '个月'
                                  WHEN 3 THEN CONVERT(NVARCHAR(30),A.VALID_PERIOD) + '年'
                                  ELSE '无期限'
               END AS PERIOD_UNIT, H.PRE_MONEY, H.RG_MONEY, H.SMALL_NUMBER, (A.PRE_MAX_MONEY-ISNULL(H.RG_MONEY,0))AS AVAILABLE_MONEY
        FROM SRV_Intrust.INTRUST.dbo.TPRODUCT A LEFT JOIN SRV_Intrust.INTRUST.dbo.TPRODUCTLIMIT C ON (A.PRODUCT_ID = C.PRODUCT_ID) LEFT JOIN
            (SELECT O.PRODUCT_ID, SUM(O.PRE_MONEY)AS PRE_MONEY,SUM(CASE WHEN O.MONEY_STATUS=1 THEN ISNULL(O.PRE_MONEY,0) ELSE 0 END)AS RG_MONEY, SUM(CASE WHEN ISNULL(O.PRE_MONEY,0)<ISNULL(P.QUALIFIED_MONEY,3000000) THEN 1 ELSE 0 END)AS SMALL_NUMBER
             FROM SRV_Intrust.INTRUST.dbo.TPRECONTRACT O LEFT JOIN SRV_Intrust.INTRUST.dbo.TPRODUCTLIMIT P ON O.PRODUCT_ID = P.PRODUCT_ID WHERE O.PRE_STATUS IN (111301,111302) GROUP BY O.PRODUCT_ID) H ON (A.PRODUCT_ID = H.PRODUCT_ID)
        WHERE A.PRODUCT_STATUS = '110202' AND INTRUST_FLAG1 = 2 
    ELSE IF (@V_DT_INTRUST = 2) AND EXISTS(SELECT * FROM master..sysdatabases WHERE NAME = N'INTRUST') --本地信托数据库
        SELECT A.PRODUCT_ID,A.PRODUCT_CODE, A.PRODUCT_NAME, A.PRE_MAX_MONEY, ISNULL(C.TA_FLAG,2) AS TA_FLAG,
               CASE ISNULL(C.TA_FLAG,2) WHEN 1 THEN '代销' ELSE '直销' END AS TA_FLAG_NAME,
               CASE A.PERIOD_UNIT WHEN 1 THEN CONVERT(NVARCHAR(30),A.VALID_PERIOD) + '天'
                                  WHEN 2 THEN CONVERT(NVARCHAR(30),A.VALID_PERIOD) + '个月'
                                  WHEN 3 THEN CONVERT(NVARCHAR(30),A.VALID_PERIOD) + '年'
                                  ELSE '无期限'
               END AS PERIOD_UNIT, H.PRE_MONEY, H.RG_MONEY, H.SMALL_NUMBER, (A.PRE_MAX_MONEY-ISNULL(H.RG_MONEY,0))AS AVAILABLE_MONEY
        FROM INTRUST..TPRODUCT A LEFT JOIN INTRUST..TPRODUCTLIMIT C ON (A.PRODUCT_ID = C.PRODUCT_ID) LEFT JOIN
            (SELECT O.PRODUCT_ID, SUM(O.PRE_MONEY)AS PRE_MONEY,SUM(CASE WHEN O.MONEY_STATUS=1 THEN ISNULL(O.PRE_MONEY,0) ELSE 0 END)AS RG_MONEY, SUM(CASE WHEN ISNULL(O.PRE_MONEY,0)<ISNULL(P.QUALIFIED_MONEY,3000000) THEN 1 ELSE 0 END)AS SMALL_NUMBER
             FROM INTRUST..TPRECONTRACT O LEFT JOIN INTRUST..TPRODUCTLIMIT P ON O.PRODUCT_ID = P.PRODUCT_ID WHERE O.PRE_STATUS IN (111301,111302)  GROUP BY O.PRODUCT_ID) H ON (A.PRODUCT_ID = H.PRODUCT_ID)
        WHERE A.PRODUCT_STATUS = '110202' AND INTRUST_FLAG1 = 2
GO
