USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_MODI_LEVELSCORE    @IN_PRODUCT_ID           INT,
                                       @IN_RISK_LEVEL           NVARCHAR(16),
                                       @IN_RISK_LEVEL_SROCE     INT,
                                       @IN_INPUT_MAN            INT
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200),@V_RISK_LEVEL_NAME NVARCHAR(60)
    SELECT @SBUSI_NAME = N'修改产品'
    SELECT @SSUMMARY = N'修改产品'
    SELECT @IBUSI_FLAG = 20402
    SELECT @V_RET_CODE = 20402000

    SELECT @V_RISK_LEVEL_NAME = TYPE_CONTENT FROM TDICTPARAM WHERE TYPE_ID = 1172 AND TYPE_VALUE = @IN_RISK_LEVEL

    BEGIN TRANSACTION
    IF NOT EXISTS(SELECT * FROM TPRODUCT WHERE PRODUCT_ID = @IN_PRODUCT_ID)
    BEGIN
            INSERT INTO TPRODUCT(PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,RISK_LEVEL,RISK_LEVEL_NAME,SALE_STATUS,RISK_LEVEL_SROCE)
            SELECT A.PRODUCT_ID,A.PRODUCT_CODE,A.PRODUCT_NAME,@IN_RISK_LEVEL,@V_RISK_LEVEL_NAME,
                CASE A.INTRUST_FLAG1 WHEN 1 THEN 2 ELSE 1 END AS SALE_STATUS,@IN_RISK_LEVEL_SROCE
             FROM INTRUST..TPRODUCT A
             WHERE A.PRODUCT_ID =  @IN_PRODUCT_ID

        IF @@ERROR <> 0
        BEGIN
            ROLLBACK TRANSACTION
            RETURN -100
        END
    END
    ELSE
    BEGIN
        UPDATE TPRODUCT
        SET RISK_LEVEL          = @IN_RISK_LEVEL,
            RISK_LEVEL_NAME     = @V_RISK_LEVEL_NAME,
            RISK_LEVEL_SROCE    = @IN_RISK_LEVEL_SROCE
        WHERE PRODUCT_ID        = @IN_PRODUCT_ID
        IF @@ERROR <> 0
        BEGIN
            ROLLBACK TRANSACTION
            RETURN -100
        END
    END
    SELECT @SSUMMARY = N'修改产品风险等级分值，产品ID：'+RTRIM(CONVERT(NVARCHAR(16),@IN_PRODUCT_ID))
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
