USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_STAT_BJITIC_NEWCUST @IN_CELL_ID    INT, --产品单元
                                        @IN_BEGIN_DATE INT, --开始日期
                                        @IN_END_DATE   INT, --结日期
                                        @IN_CUST_TYPE  INT, --客户类型1个人2机构
                                        @IN_QUERY_TYPE INT, --1:0-100W; 2:100-300W; 3:300-1000W; 4:1000W
										@IN_INPUT_MAN  INT,  --操作员,
                                        @IN_CUSTOMER_MESSAGER   NVARCHAR(20) = '', --客户经理名称
										@IN_DEPART_NAME         NVARCHAR(20) = ''  --部门名称
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    SET @IN_CUSTOMER_MESSAGER = RTRIM(LTRIM(ISNULL(@IN_CUSTOMER_MESSAGER,'')))
    DECLARE @VT_BJITIC_NEWCUST TABLE(
        PRODUCT_ID      INTEGER,
        PRODUCT_NAME    NVARCHAR(60),
        CUST_NO         NVARCHAR(8),
        CUST_NAME       NVARCHAR(100),
        CUST_TYPE       NVARCHAR(10),
        TRADE_MONEY     DEC(16,3),
        START_DATE      INTEGER,
        SERVICE_MAN     NVARCHAR(30),    --客户经理
        LINK_MAN        NVARCHAR(30),    --合同销售人员
        RECOMMENDED     NVARCHAR(60),    --联系人
		DEPART_NAME     NVARCHAR(30),    --部门名称
        BD_BUSI_ID      INTEGER,         --认购\申购
        DATA_TYPE       INTEGER          --1明细 2小计 3合计
    )
    DECLARE @V_GR_COUNT INT, @V_JG_COUNT INT
    --从份额变动记录中取认购、申购

    INSERT INTO @VT_BJITIC_NEWCUST (PRODUCT_ID, PRODUCT_NAME, CUST_NO, CUST_NAME, CUST_TYPE, TRADE_MONEY, START_DATE,
                                        SERVICE_MAN, LINK_MAN, RECOMMENDED,DEPART_NAME, BD_BUSI_ID, DATA_TYPE)
         SELECT A.PRODUCT_ID, C.PRODUCT_NAME, B.CUST_NO, B.CUST_NAME, B.CUST_TYPE, A.ADD_MONEY AS TRADE_MONEY, A.TRADE_DATE,
                  E.OP_NAME AS SERVICE_MAN, F.OP_NAME AS LINK_MAN, B.RECOMMENDED, G.DEPART_NAME,A.BD_BUSI_ID, 1
            FROM INTRUSTHistory..HCUSTZJBD A, (INTRUST..TCUSTOMERINFO B LEFT JOIN EFCRM..TOPERATOR E ON (B.SERVICE_MAN = E.OP_CODE or  (ISNULL(B.SERVICE_MAN,0)=0 AND B.INPUT_MAN=E.OP_CODE)))
				 LEFT JOIN EFCRM..TDEPARTMENT G ON E.DEPART_ID = G.DEPART_ID, 
				 INTRUST..TPRODUCT C,(INTRUST..TCONTRACT D LEFT JOIN INTRUST..TOPERATOR F ON (D.LINK_MAN = F.OP_CODE OR (ISNULL(D.LINK_MAN,0)=0 AND D.INPUT_MAN=F.OP_CODE)))
           WHERE A.CUST_ID = B.CUST_ID AND A.PRODUCT_ID = C.PRODUCT_ID AND A.PRODUCT_ID = D.PRODUCT_ID AND A.CONTRACT_BH = D.CONTRACT_BH
                AND(A.BD_BUSI_ID = 1 OR A.BD_BUSI_ID = 2)
                AND	(ISNULL(E.OP_NAME,'') LIKE '%'+@IN_CUSTOMER_MESSAGER+'%' OR ISNULL(F.OP_NAME,'') LIKE '%'+@IN_CUSTOMER_MESSAGER+'%')
				AND (ISNULL(G.DEPART_NAME,'') LIKE '%'+@IN_DEPART_NAME+'%')
                AND EXISTS(SELECT PRODUCT_ID FROM INTRUST.dbo.GETCELLPRODUCTS(@IN_CELL_ID) Z WHERE A.PRODUCT_ID = Z.PRODUCT_ID)
                AND(B.CUST_TYPE = @IN_CUST_TYPE OR ISNULL(@IN_CUST_TYPE,0) = 0)
                AND(A.TRADE_DATE BETWEEN ISNULL(@IN_BEGIN_DATE,0) AND ISNULL(@IN_END_DATE,20991231))
                --AND(NOT EXISTS(SELECT CUST_ID FROM INTRUST..TBENIFITOR Y WHERE Y.BEN_DATE < A.TRADE_DATE AND A.CUST_ID = Y.CUST_ID AND A.PRODUCT_ID <>Y.PRODUCT_ID))
				AND(NOT EXISTS(SELECT CUST_ID FROM INTRUST..TBENIFITOR Y WHERE Y.BEN_DATE < A.TRADE_DATE AND A.CUST_ID = Y.CUST_ID))
         UNION ALL --包含转让的
         SELECT A.PRODUCT_ID, C.PRODUCT_NAME, B.CUST_NO, B.CUST_NAME, B.CUST_TYPE, A.TO_AMOUNT AS TRADE_MONEY, A.CHANGE_DATE,
                  E.OP_NAME AS SERVICE_MAN, F.OP_NAME AS LINK_MAN, B.RECOMMENDED,G.DEPART_NAME, 9, 1
           FROM INTRUST..TBENCHANGES A, (INTRUST..TCUSTOMERINFO B LEFT JOIN EFCRM..TOPERATOR E ON B.SERVICE_MAN = E.OP_CODE)
				LEFT JOIN EFCRM..TDEPARTMENT G ON E.DEPART_ID = G.DEPART_ID, INTRUST..TPRODUCT C,
                (INTRUST..TCONTRACT D LEFT JOIN TOPERATOR F ON D.LINK_MAN = F.OP_CODE)
            WHERE A.TO_CUST_ID = B.CUST_ID AND A.PRODUCT_ID = C.PRODUCT_ID AND A.PRODUCT_ID = D.PRODUCT_ID AND A.CONTRACT_BH = D.CONTRACT_BH
				AND	(ISNULL(E.OP_NAME,'') LIKE '%'+@IN_CUSTOMER_MESSAGER+'%' OR ISNULL(F.OP_NAME,'') LIKE '%'+@IN_CUSTOMER_MESSAGER+'%')
				AND (ISNULL(G.DEPART_NAME,'') LIKE '%'+@IN_DEPART_NAME+'%')		
				AND EXISTS(SELECT PRODUCT_ID FROM INTRUST.dbo.GETCELLPRODUCTS(@IN_CELL_ID) Z WHERE A.PRODUCT_ID = Z.PRODUCT_ID)
                AND(B.CUST_TYPE = @IN_CUST_TYPE OR ISNULL(@IN_CUST_TYPE,0) = 0)
                AND(A.CHANGE_DATE BETWEEN ISNULL(@IN_BEGIN_DATE,0) AND ISNULL(@IN_END_DATE,20991231))
                AND(NOT EXISTS(SELECT CUST_ID FROM INTRUST..TBENIFITOR Y WHERE Y.BEN_DATE < A.CHANGE_DATE AND A.TO_CUST_ID = Y.CUST_ID))
			
    SELECT @V_GR_COUNT = COUNT(*) FROM (SELECT CUST_NO FROM @VT_BJITIC_NEWCUST WHERE CUST_TYPE = 1 GROUP BY CUST_NO) A
	SELECT @V_JG_COUNT = COUNT(*) FROM (SELECT CUST_NO FROM @VT_BJITIC_NEWCUST WHERE CUST_TYPE = 2 GROUP BY CUST_NO) A
    --插入个人、机构小计
--    INSERT INTO @VT_BJITIC_NEWCUST(PRODUCT_NAME, CUST_NAME, CUST_TYPE, TRADE_MONEY, DATA_TYPE)
--        SELECT '个人客户小计', CONVERT(VARCHAR(8), @V_GR_COUNT)+'人', 1, SUM(TRADE_MONEY), 2
--            FROM @VT_BJITIC_NEWCUST WHERE CUST_TYPE = 1 AND DATA_TYPE = 1
--    INSERT INTO @VT_BJITIC_NEWCUST(PRODUCT_NAME, CUST_NAME, CUST_TYPE, TRADE_MONEY, DATA_TYPE)
--        SELECT '机构客户小计', CONVERT(VARCHAR(8), @V_JG_COUNT)+'家', 2, SUM(TRADE_MONEY), 2
--            FROM @VT_BJITIC_NEWCUST WHERE CUST_TYPE = 2 AND DATA_TYPE = 1
    INSERT INTO @VT_BJITIC_NEWCUST(PRODUCT_ID, PRODUCT_NAME, CUST_NAME, TRADE_MONEY, DATA_TYPE)
        SELECT PRODUCT_ID, PRODUCT_NAME, '小计：'+CONVERT(VARCHAR(8),COUNT(distinct CUST_NAME))+'个客户', SUM(TRADE_MONEY), 2
            FROM @VT_BJITIC_NEWCUST WHERE DATA_TYPE = 1
            GROUP BY PRODUCT_ID, PRODUCT_NAME
    --插入合计
    INSERT INTO @VT_BJITIC_NEWCUST(PRODUCT_ID, PRODUCT_NAME, CUST_NAME, CUST_TYPE, TRADE_MONEY, DATA_TYPE)
        SELECT 9999999, '合计:'+CONVERT(VARCHAR(8), @V_GR_COUNT+@V_JG_COUNT),'个人:'+ CONVERT(VARCHAR(8), @V_GR_COUNT)+',机构:'+CONVERT(VARCHAR(8), @V_JG_COUNT), 3, SUM(TRADE_MONEY), 3
            FROM @VT_BJITIC_NEWCUST WHERE DATA_TYPE = 1 
    --输出
    SELECT PRODUCT_NAME, CUST_NAME, SUM(TRADE_MONEY) AS TRADE_MONEY, START_DATE, SERVICE_MAN, RECOMMENDED, LINK_MAN,DEPART_NAME
        FROM @VT_BJITIC_NEWCUST
        WHERE ( (@IN_QUERY_TYPE = 0)
                OR(@IN_QUERY_TYPE = 1 AND TRADE_MONEY BETWEEN 0 AND 1000000)
                OR(@IN_QUERY_TYPE = 2 AND TRADE_MONEY BETWEEN 1000000 AND 3000000)
                OR(@IN_QUERY_TYPE = 3 AND TRADE_MONEY BETWEEN 3000000 AND 10000000)
                OR(@IN_QUERY_TYPE = 4 AND TRADE_MONEY > 10000000)
              )
	    GROUP BY PRODUCT_ID,PRODUCT_NAME,DATA_TYPE, CUST_NAME, START_DATE, SERVICE_MAN, RECOMMENDED, LINK_MAN,DEPART_NAME
        ORDER BY PRODUCT_ID, DATA_TYPE, START_DATE

    RETURN @@ROWCOUNT
GO
