USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_PORTALMENU2 @IN_INPUT_MAN     NVARCHAR(60),
                                      @IN_LANGUAGE_FLAG NVARCHAR(10) = ''
WITH ENCRYPTION
AS
    SET NOCOUNT ON

    DECLARE @V_USER_ID INT
    SELECT @V_USER_ID = USER_ID FROM TSYSTEMINFO
    DECLARE @V_TMP_MENU_RIGHT TABLE
    (
        OP_CODE     INT,
        MENU_ID     NVARCHAR (20) NOT NULL ,
        MENU_NAME   NVARCHAR (400) NOT NULL ,
        MENU_INFO   NVARCHAR (2000),
        PARENT_ID   NVARCHAR (20),
        BOTTOM_FLAG INTEGER NOT NULL,
        URL         NVARCHAR(1000),
        TREE_ORDER  NVARCHAR(10),  --排序依据字段
        ICON_CLS    NVARCHAR(200)
    )
    DECLARE @V_TEMPRIGHT TABLE(MENU_ID NVARCHAR(20))
    INSERT INTO @V_TEMPRIGHT SELECT MENU_ID FROM TROLERIGHT
    WHERE ROLE_ID IN(SELECT ROLE_ID FROM TOPROLE WHERE OP_CODE = @IN_INPUT_MAN)
    GROUP BY MENU_ID

    --插入操作员有权限的菜单，并过滤
    IF EXISTS(SELECT * FROM TSYSTEMINFO WHERE INIT_FLAG = 1)
        INSERT INTO @V_TMP_MENU_RIGHT
            SELECT @IN_INPUT_MAN, B.MENU_ID, B.MENU_NAME,B.MENU_INFO, B.PARENT_ID, B.BOTTOM_FLAG, B.URL, B.TREE_ORDER, B.ICON_CLS
                FROM @V_TEMPRIGHT A, TMENUINFO B
                WHERE A.MENU_ID = B.MENU_ID AND LEFT(A.MENU_ID,1) NOT IN ('M','P')
                    AND (B.USER_ID = @V_USER_ID OR B.USER_ID = 0)
    ELSE
        INSERT INTO @V_TMP_MENU_RIGHT
            SELECT @IN_INPUT_MAN, B.MENU_ID, B.MENU_NAME,B.MENU_INFO, B.PARENT_ID, B.BOTTOM_FLAG, B.URL, B.TREE_ORDER, B.ICON_CLS
                FROM @V_TEMPRIGHT A, TMENUINFO B
                WHERE A.MENU_ID = B.MENU_ID AND LEFT(A.MENU_ID,1) NOT IN ('M','P')
                    AND B.MENU_ID NOT IN ('10104', '20409') AND (B.USER_ID = @V_USER_ID OR B.USER_ID = 0)
    --插入菜单的父菜单
    INSERT INTO @V_TMP_MENU_RIGHT
        SELECT @IN_INPUT_MAN, B.MENU_ID, B.MENU_NAME,B.MENU_INFO, B.PARENT_ID, B.BOTTOM_FLAG, B.URL, B.TREE_ORDER, B.ICON_CLS
            FROM TMENUINFO B
            WHERE B.MENU_ID IN (SELECT DISTINCT PARENT_ID FROM @V_TMP_MENU_RIGHT)
                AND (B.USER_ID = @V_USER_ID OR B.USER_ID = 0)

    INSERT INTO @V_TMP_MENU_RIGHT
        SELECT @IN_INPUT_MAN, B.MENU_ID, B.MENU_NAME,B.MENU_INFO, B.PARENT_ID, B.BOTTOM_FLAG, B.URL, B.TREE_ORDER, B.ICON_CLS
            FROM TMENUINFO B
            WHERE B.MENU_ID IN (SELECT DISTINCT PARENT_ID FROM @V_TMP_MENU_RIGHT WHERE BOTTOM_FLAG = 2)
                  AND B.MENU_ID NOT IN (SELECT MENU_ID FROM @V_TMP_MENU_RIGHT)
                  AND (B.USER_ID = @V_USER_ID OR B.USER_ID = 0)

    IF ISNULL(@IN_LANGUAGE_FLAG,'')='en'
    BEGIN
        UPDATE @V_TMP_MENU_RIGHT SET MENU_NAME = ISNULL(B.MENU_NAME,A.MENU_NAME), MENU_INFO = ISNULL(B.MENU_INFO,A.MENU_INFO)
            FROM @V_TMP_MENU_RIGHT A, TMENUINFO B
            WHERE A.MENU_ID = B.MENU_ID
    END
    UPDATE @V_TMP_MENU_RIGHT SET PARENT_ID = LEFT(MENU_ID,1) WHERE PARENT_ID = '' AND NOT (MENU_ID LIKE 'W%' OR MENU_ID LIKE '9%')
    INSERT INTO @V_TMP_MENU_RIGHT(MENU_ID,MENU_NAME,BOTTOM_FLAG,PARENT_ID,URL)
        SELECT LEFT(MENU_ID,1),'',2,'','' FROM @V_TMP_MENU_RIGHT
        WHERE NOT (MENU_ID LIKE 'W%' OR MENU_ID LIKE '9%')
        GROUP BY LEFT(MENU_ID,1)
    UPDATE @V_TMP_MENU_RIGHT SET MENU_NAME = B.MENU_NAME
        FROM @V_TMP_MENU_RIGHT A, (
            SELECT    '1' AS MAIN_ID,'配置管理' AS MENU_NAME
            UNION ALL SELECT '2','前台业务'
            UNION ALL SELECT '3','项目投资'
            UNION ALL SELECT '4','业务财务'
            UNION ALL SELECT '5','总账财务'
            UNION ALL SELECT '6','估值管理'
            UNION ALL SELECT '7','风险监控'
            UNION ALL SELECT '9','报表管理'
            UNION ALL SELECT 'C','中后期管理'
            UNION ALL SELECT 'W','信息库'
            ) B
        WHERE A.MENU_NAME = '' AND A.MENU_ID = B.MAIN_ID
    SELECT MENU_ID,PARENT_ID,MENU_ID AS MENU_CODE,MENU_NAME,'' AS APP_CODE,URL AS PATH,ICON_CLS
        FROM @V_TMP_MENU_RIGHT
        WHERE MENU_ID LIKE 'W%' OR (MENU_ID LIKE '9%' AND MENU_ID NOT LIKE '900%')
        ORDER BY MENU_ID
    --SELECT DISTINCT LEFT(MENU_ID,1) FROM @V_TMP_MENU_RIGHT
    RETURN @@ROWCOUNT
GO
