USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TROLE @IN_ROLE_ID INT =0,                --角色编号
                                @IN_ROLE_NAME  NVARCHAR(20) =NULL --角色名称
WITH ENCRYPTION
AS
        SELECT * FROM TROLE
        WHERE ((ROLE_ID = @IN_ROLE_ID) OR (@IN_ROLE_ID = 0) OR (@IN_ROLE_ID IS NULL))
            AND (ROLE_NAME LIKE '%'+@IN_ROLE_NAME+'%' OR ISNULL(@IN_ROLE_NAME,'') ='')
GO
