USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_SETTLE_TSUBSCRIBE @IN_SUBSCRIBE_ID  INT,    --非信托产品合同ID
                                      @IN_END_DATE      INT,    --结清日期
                                      @IN_INPUT_MAN     INT     --录入操作员
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    DECLARE @V_CUST_ID INT,@V_BANK_ID NVARCHAR(10), @V_BANK_NAME NVARCHAR(30),@V_BANK_SUB_NAME NVARCHAR(60)
    DECLARE @V_BANK_ACCT NVARCHAR(60),@V_PROFIT_MONEY DEC(16,3)
    SELECT @SBUSI_NAME = N'非信托产品合同结清'
    SELECT @SSUMMARY = N'非信托产品合同结清'
    SELECT @IBUSI_FLAG = 39021
    SELECT @V_RET_CODE = -39021000

    IF NOT EXISTS(SELECT 1 FROM TPROFIT WHERE SUBSCRIBE_ID = @IN_SUBSCRIBE_ID)
        RETURN @V_RET_CODE - 11   --非信托产品收益信息不存在

    IF NOT EXISTS(SELECT 1 FROM TSUBSCRIBE WHERE SUBSCRIBE_ID = @IN_SUBSCRIBE_ID)
        RETURN @V_RET_CODE - 12   --非信托产品认购信息不存在

    IF NOT EXISTS(SELECT * FROM TQUOTIENT WHERE SUBSCRIBE_ID = @IN_SUBSCRIBE_ID)
        RETURN @V_RET_CODE - 13   --非信托产品份额信息不存在

    BEGIN TRANSACTION

    SELECT @V_CUST_ID = CUST_ID,
            @V_PROFIT_MONEY = QUOTIENT_AMOUNT,
            @V_BANK_ID = BANK_ID,
            @V_BANK_NAME = BANK_NAME,
            @V_BANK_SUB_NAME = BANK_SUB_NAME,
            @V_BANK_ACCT = BANK_ACCT
            FROM TQUOTIENT WHERE SUBSCRIBE_ID = @IN_SUBSCRIBE_ID

    UPDATE TSUBSCRIBE SET TEMP_STATUS = STATUS, STATUS = '120105',STATUS_NAME = '已到期结算',
             CHECK_FLAG = 1, CHECK_TIME = GETDATE(), CHECK_MAN = @IN_INPUT_MAN
        WHERE SUBSCRIBE_ID = @IN_SUBSCRIBE_ID

    UPDATE TQUOTIENT SET TEMP_STATUS = STATUS, STATUS = '121105',STATUS_NAME = '到期结算'
            ,END_DATE = @IN_END_DATE WHERE SUBSCRIBE_ID = @IN_SUBSCRIBE_ID

    INSERT INTO TPROFIT(SUBSCRIBE_ID, CUST_ID, PROFIT_MONEY,SY_DATE, SY_TYPE, SY_TYPE_NAME,
                BANK_ID, BANK_NAME, BANK_SUB_NAME, BANK_ACCT, INPUT_MAN, INPUT_TIME, CHECK_FLAG, CHECK_TIME, CHECK_MAN)
            VALUES(@IN_SUBSCRIBE_ID, @V_CUST_ID, @V_PROFIT_MONEY ,@IN_END_DATE ,111605,'到期本金',
            @V_BANK_ID, @V_BANK_NAME, @V_BANK_SUB_NAME, @V_BANK_ACCT,@IN_INPUT_MAN, GETDATE(), 2,GETDATE(), @IN_INPUT_MAN)

    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SET @SSUMMARY = N'非信托产品合同结清，操作员：' + CAST(@IN_INPUT_MAN AS NVARCHAR(10))
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
