USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TCustomerCHANGE 	@IN_CUST_ID		INTEGER,
											@IN_CUST_NO		NVARCHAR(10),
											@IN_CUST_NAME	NVARCHAR(60) = NULL,
											@IN_CARD_ID		NVARCHAR(30) = NULL,
											@IN_CARD_TYPE	NVARCHAR(10) = NULL,
											@IN_CUST_TYPE	INTEGER,
											@IN_SERVICE_MAN	INTEGER,
											@IN_START_DATE	INTEGER,
											@IN_END_DATE	INTEGER,
											@IN_INPUT_MAN   INTEGER,
											@IN_CHECK_FLAG  INT=0        --审核标志 --0不要求审核或者全部，1未审核，2已审核通过，3审核不通过
WITH ENCRYPTION
AS  --SELECT * FROM TCUSTOMERS
    IF ISNULL(@IN_CUST_ID,0)=0 AND @IN_CHECK_FLAG=1
    BEGIN
		SELECT DISTINCT A.CUST_TYPE_NAME,A.CUST_ID,A.CUST_NO,A.CUST_NAME,A.CARD_ID,A.CUST_SOURCE_NAME,B.CHECK_FLAG,DBO.GETDATEINT(B.INPUT_TIME)
			FROM TCUSTOMERS A,TCustomerChanges B
            WHERE (A.CUST_ID = B.CUST_ID)
                AND ISNULL(B.CHECK_FLAG,0)=1
                AND (A.CUST_NAME LIKE '%'+ISNULL(@IN_CUST_NAME,'')+'%')
                AND (A.CARD_ID LIKE '%'+ISNULL(@IN_CARD_ID,'')+'%')
				AND (A.CUST_NO LIKE '%'+ISNULL(@IN_CUST_NO,'')+'%')
                AND (A.CUST_TYPE = @IN_CUST_TYPE OR ISNULL(@IN_CUST_TYPE,0)=0)
            ORDER BY DBO.GETDATEINT(B.INPUT_TIME) DESC
        RETURN
    END
    BEGIN
        SELECT A.CUST_TYPE_NAME,A.CUST_ID,A.CUST_NO,A.CUST_NAME,B.FIELD_CN_NAME,B.OLD_FIELD_INFO,B.NEW_FIELD_INFO,
				C.OP_NAME,DBO.GETDATEINT(B.INPUT_TIME) AS INPUT_TIME,B.CHECK_FLAG
			FROM TCUSTOMERS A,TCustomerChanges B LEFT JOIN TOPERATOR C ON B.INPUT_MAN = C.OP_CODE
            WHERE (A.CUST_ID = B.CUST_ID)
				AND (A.CUST_ID = @IN_CUST_ID OR ISNULL(@IN_CUST_ID,0)=0)
				AND (A.CUST_NO LIKE '%'+ISNULL(@IN_CUST_NO,'')+'%')
				AND (A.CUST_NAME LIKE '%'+ISNULL(@IN_CUST_NAME,'')+'%')
				AND (A.CARD_ID LIKE '%'+ISNULL(@IN_CARD_ID,'')+'%')
				AND (A.CARD_TYPE = @IN_CARD_TYPE OR ISNULL(@IN_CARD_TYPE,'')='')
				AND (A.CUST_TYPE = @IN_CUST_TYPE OR ISNULL(@IN_CUST_TYPE,0)=0)
				AND (DBO.GETDATEINT(B.INPUT_TIME) >= @IN_START_DATE OR ISNULL(@IN_START_DATE,0)=0) 
				AND (DBO.GETDATEINT(B.INPUT_TIME) <= @IN_END_DATE OR ISNULL(@IN_END_DATE,0)=0)
				AND (B.INPUT_MAN = @IN_SERVICE_MAN OR ISNULL(@IN_SERVICE_MAN,0)=0)
				AND (B.CHECK_FLAG = @IN_CHECK_FLAG OR ISNULL(@IN_CHECK_FLAG,0)=0)
            --GROUP BY A.CUST_ID,B.INPUT_MAN,DBO.GETDATEINT(B.INPUT_TIME),A.CUST_NO,A.CUST_NAME,A.CUST_TYPE_NAME,A.CARD_TYPE_NAME
			ORDER BY DBO.GETDATEINT(B.INPUT_TIME) DESC
    END
GO
