USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TMONEYDETAIL @IN_BOOK_CODE            INT,                            --账套
                                       @IN_PRODUCT_ID           INT,                            --产品ID
                                       @IN_CONTRACT_BH          NVARCHAR(16),                   --合同编号
                                       @IN_CHECK_FLAG           INTEGER,                        --审核标志
                                       @IN_INPUT_MAN            INTEGER,                        --操作员
                                       @IN_DZ_DATE              INTEGER         = NULL,         --缴款时间区间上限
                                       @IN_CUST_NAME            NVARCHAR(100)   = '',           --客户名称
                                       @IN_CUST_NO              NVARCHAR(8)     = '',           --客户编号
                                       @IN_MIN_TO_MONEY         DEC(16,2)       = NULL,         --缴款金额区间下限
                                       @IN_MAX_TO_MONEY         DEC(16,2)       = NULL,         --缴款金额区间上限
                                       @IN_END_DATE             INTEGER         = 0,            --缴款时间区间下限
                                       @IN_PZ_FLAG              INTEGER         = NULL,         --凭证标志
                                       @IN_LOST_FLAG            INTEGER         = NULL,         --挂失标志
                                       @IN_CONTRACT_SUB_BH      NVARCHAR(50)    = NULL,         --实际合同编号
                                       @IN_CELL_FLAG            INTEGER         = 1,            --模式： 1 原来模式 2 产品单元模式
                                       @IN_CELL_ID              INTEGER         = 0,            --单元ID
                                       @IN_DEPART_ID            INTEGER         = 0,            --设计部门
                                       @IN_INTRUST_FLAG1        INTEGER         = 0,            --1.单一 2.集合
                                       @IN_SUB_PRODUCT_ID       INT             = 0,            --子产品ID   20111112  LUOHH
                                       @IN_FPRG_TIMES           INTEGER         = 0,            --分批认购批次
                                       @IN_IS_JK_DATA           INTEGER         = NULL
WITH ENCRYPTION
AS
    --20409: The Products can be accessed. START
    DECLARE @V_SW20409 INT
    SELECT @V_SW20409 = VALUE FROM TSYSCONTROL WHERE FLAG_TYPE = 'SW20409'
    DECLARE @V_TMP_PRODUCTS TABLE(PRODUCT_ID INT)
    IF ISNULL(@IN_PRODUCT_ID,0) <> 0 
        INSERT INTO @V_TMP_PRODUCTS
            SELECT PRODUCT_ID FROM TPRODUCT WHERE PRODUCT_ID = @IN_PRODUCT_ID
    ELSE
    BEGIN
        IF @V_SW20409 = 1
        INSERT INTO @V_TMP_PRODUCTS
            SELECT PRODUCT_ID FROM INTRUST..TPRODUCT WHERE BOOK_CODE = @IN_BOOK_CODE
                AND(INTRUST_FLAG1 IN ( SELECT FUNC_ID-2040900 FROM INTRUST..TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID > 2040900 AND FUNC_ID <= 2040902 AND OP_CODE = @IN_INPUT_MAN )
                    OR DEPART_ID IN (SELECT B.DEPART_ID FROM INTRUST..TOPRIGHT A,INTRUST..TOPERATOR B WHERE A.OP_CODE = B.OP_CODE AND A.MENU_ID = '20409' AND A.FUNC_ID = 2040903 AND A.OP_CODE = @IN_INPUT_MAN)
                    OR PRODUCT_ID IN ( SELECT FUNC_ID FROM INTRUST..TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID < 2040900 AND OP_CODE = @IN_INPUT_MAN)
                    OR ADMIN_MANAGER = @IN_INPUT_MAN OR INPUT_MAN = @IN_INPUT_MAN OR ISNULL(@IN_INPUT_MAN,0)=0
                    OR SUB_MAN = @IN_INPUT_MAN OR SUB_MAN2 = @IN_INPUT_MAN
                    OR CASH_MAN = @IN_INPUT_MAN OR CASH_MAN2 = @IN_INPUT_MAN
                    OR ADMIN_MANAGER IN(SELECT OP_CODE FROM INTRUST..TOPCUSTRIGHT WHERE ENABLE_OP_CODE = @IN_INPUT_MAN))
    --20409: The Products can be accessed. END
    END
  
    CREATE TABLE #TEMPCP(
        PRODUCT_ID   INT,
        PRODUCT_CODE NVARCHAR(6)
    )

    --选择要查询的产品
    IF @IN_CELL_FLAG = 1
    BEGIN
        INSERT INTO #TEMPCP(PRODUCT_ID,PRODUCT_CODE)
            SELECT PRODUCT_ID,PRODUCT_CODE
                FROM INTRUST..TPRODUCT
                WHERE BOOK_CODE = @IN_BOOK_CODE AND (PRODUCT_ID = @IN_PRODUCT_ID OR (ISNULL(@IN_PRODUCT_ID,0) = 0)) AND
                      (DEPART_ID = @IN_DEPART_ID OR ISNULL(@IN_DEPART_ID,0) = 0)
    END
    ELSE
    BEGIN
        CREATE TABLE #CELL_ALL(
            CELL_ID      INT,
            CELL_CODE    NVARCHAR(10),
            CELL_NAME    NVARCHAR(60),
            CELL_TYPE    INT,
            PRODUCT_ID   INT,
            PRODUCT_CODE NVARCHAR(6),
            PRODUCT_NAME NVARCHAR(60)
        )

        INSERT INTO #CELL_ALL(CELL_ID,CELL_CODE,CELL_NAME,PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,CELL_TYPE)
            SELECT SERIAL_NO,CELL_CODE,CELL_NAME,PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,CELL_TYPE
             FROM INTRUST..TPRODUCT_CELL
             WHERE SERIAL_NO = @IN_CELL_ID

        IF @@ROWCOUNT > 0
            INSERT INTO #CELL_ALL(CELL_ID,CELL_CODE,CELL_NAME,CELL_TYPE,PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME)
                SELECT A.SUB_CELL_ID,C.CELL_CODE,C.CELL_NAME,C.CELL_TYPE,C.PRODUCT_ID,C.PRODUCT_CODE,C.PRODUCT_NAME
                    FROM INTRUST..TPRODUCT_CELL_DETAIL A,#CELL_ALL B,INTRUST..TPRODUCT_CELL C
                    WHERE A.DF_SERIAL_NO = B.CELL_ID AND A.SUB_CELL_ID = C.SERIAL_NO AND A.SUB_CELL_ID NOT IN(SELECT CELL_ID FROM #CELL_ALL)

        INSERT INTO #TEMPCP
            SELECT A.PRODUCT_ID,A.PRODUCT_CODE
                FROM #CELL_ALL A,INTRUST..TPRODUCT B
                WHERE A.CELL_TYPE = 1 AND A.PRODUCT_ID = B.PRODUCT_ID AND (B.DEPART_ID = @IN_DEPART_ID OR ISNULL(@IN_DEPART_ID,0) = 0)
                GROUP BY A.PRODUCT_ID,A.PRODUCT_CODE
    END
    SELECT A.SERIAL_NO,A.CARD_LOST_FLAG,A.PRODUCT_ID,A.CONTRACT_BH,A.CUST_ID,B.CUST_NO,B.CARD_ID,C.PRODUCT_NAME,A.CUST_NAME,A.DZ_DATE,A.TO_MONEY,A.TO_AMOUNT,A.TO_BANK_DATE,A.JK_TYPE_NAME,A.CHECK_FLAG,
           A.CARD_LOST_FLAG,A.CARD_LOST_DATE,A.BEN_CARD_NO,A.PZ_FLAG,A.JK_TYPE,A.BOOK_CODE,A.INPUT_MAN,A.FEE_TYPE,A.FEE_MONEY,A.SUMMARY,C.START_DATE,
           A.JS_DATE,A.BOND1,A.BOND2,A.BOND_TAX,A.BOND_DATE,A.BOND_DAYS,D.CONTRACT_SUB_BH,C.PRODUCT_CODE,C.TG_BANK_NAME,C.TG_BANK_SUB_NAME,C.CURRENCY_ID,C.TG_BANK_ACCT,F.LIST_NAME,F.LIST_NAME AS SUB_PRODUCT_NAME,
           (ISNULL(E.BANK_NAME,D.BANK_NAME) + ISNULL('-' + ISNULL(E.BANK_SUB_NAME,D.BANK_SUB_NAME),'')) AS BANK_NAME,
           ISNULL(E.BANK_ACCT,D.BANK_ACCT) AS BANK_ACCT,
           ISNULL(E.CUST_ACCT_NAME,D.GAIN_ACCT) AS GAIN_ACCT,
           G.CONTENT AS PROV_FLAG_NAME,E.PROV_LEVEL_NAME,C.MATAIN_MANAGER,
           C.TG_BANK_NAME,C.TG_BANK_SUB_NAME,C.TG_BANK_ACCT,D.SERVICE_MAN
        FROM INTRUST..TMONEYDETAIL A LEFT JOIN INTRUST..TSUBPRODUCT F ON A.SUB_PRODUCT_ID = F.SUB_PRODUCT_ID
                            LEFT JOIN INTRUST..TBENIFITOR E ON A.PRODUCT_ID = E.PRODUCT_ID AND A.CONTRACT_BH = E.CONTRACT_BH AND A.LIST_ID = E.LIST_ID
                            LEFT JOIN INTRUST..TINTEGERPARAM G ON E.PROV_FLAG = G.TYPE_VALUE AND G.TYPE_ID = 3003,
             INTRUST..TCUSTOMERINFO B,INTRUST..TPRODUCT C,INTRUST..TCONTRACT D
        WHERE A.BOOK_CODE = @IN_BOOK_CODE AND A.IS_JK_DATA IN(0,1) AND A.CUST_ID = B.CUST_ID AND A.PRODUCT_ID = C.PRODUCT_ID
              AND D.PRODUCT_ID = A.PRODUCT_ID AND D.CONTRACT_BH = A.CONTRACT_BH
              AND EXISTS(SELECT 1 FROM #TEMPCP E WHERE A.PRODUCT_ID = E.PRODUCT_ID)
              AND (A.CONTRACT_BH LIKE '%'+@IN_CONTRACT_BH+'%' OR @IN_CONTRACT_BH IS NULL OR @IN_CONTRACT_BH = '')
              AND (D.CONTRACT_SUB_BH LIKE '%'+@IN_CONTRACT_SUB_BH+'%' OR @IN_CONTRACT_SUB_BH IS NULL OR @IN_CONTRACT_SUB_BH = '')
              AND ((A.DZ_DATE BETWEEN @IN_DZ_DATE AND @IN_END_DATE) OR (ISNULL(@IN_DZ_DATE,0) = 0 AND ISNULL(@IN_END_DATE,0) = 0))
              AND (B.CUST_NAME LIKE '%' + @IN_CUST_NAME + '%' OR @IN_CUST_NAME IS NULL OR @IN_CUST_NAME = '')
              AND (B.CUST_NO LIKE '%' + @IN_CUST_NO + '%' OR @IN_CUST_NO IS NULL OR @IN_CUST_NO = '')
              AND (A.CHECK_FLAG = @IN_CHECK_FLAG OR ISNULL(@IN_CHECK_FLAG,0) = 0)
              AND (@V_SW20409 = 0 OR @V_SW20409 IS NULL OR A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_TMP_PRODUCTS))
              AND ((A.TO_MONEY BETWEEN @IN_MIN_TO_MONEY AND @IN_MAX_TO_MONEY)
                     OR (ISNULL(@IN_MIN_TO_MONEY,0) = 0 AND A.TO_MONEY <= @IN_MAX_TO_MONEY)
                     OR (ISNULL(@IN_MAX_TO_MONEY,0) = 0 AND A.TO_MONEY >= @IN_MIN_TO_MONEY)
                     OR (ISNULL(@IN_MIN_TO_MONEY,0) = 0 AND ISNULL(@IN_MAX_TO_MONEY,0) = 0))
              AND (A.PZ_FLAG = @IN_PZ_FLAG OR ISNULL(@IN_PZ_FLAG,0) = 0)
              AND (A.CARD_LOST_FLAG = @IN_LOST_FLAG  OR ISNULL(@IN_LOST_FLAG,0) = 0)
              AND ISNULL(A.CARD_LOST_FLAG,0) <> 11
              AND (C.INTRUST_FLAG1 = @IN_INTRUST_FLAG1 OR ISNULL(@IN_INTRUST_FLAG1,0) = 0)
              AND (ISNULL(@IN_SUB_PRODUCT_ID,0) =0 OR D.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID)
              AND (D.FPRG_TIMES = @IN_FPRG_TIMES OR ISNULL(@IN_FPRG_TIMES,0) = 0)
              AND (A.IS_JK_DATA = @IN_IS_JK_DATA OR @IN_IS_JK_DATA IS NULL)
        ORDER BY A.PRODUCT_ID ASC,DZ_DATE DESC,A.CONTRACT_BH ASC
GO
