USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TCustClassDetail_2 @IN_CLASSDEFINE_ID   INTEGER,        --分级定义ID
                                           @IN_CLASSDETAIL_ID   INTEGER,        --分级明细ID
                                           @IN_INPUT_MAN        INTEGER         --操作员
WITH ENCRYPTION
AS
    CREATE TABLE #TMP_QUERY_TCustClassDetail(
        CLASSDEFINE_ID      INT,
        CLASSDEFINE_NAME    NVARCHAR(60),
        CLASSDETAIL_ID      INT,
        CLASSDETAIL_NAME    NVARCHAR(60),
        CANMODI              INT,
        CANADD               INT,
        CANDEL               INT,
        BOTTOM_FLAG          INT,
        TABLE_FLAG          INT, ---TCustClassDetail为‘1’,TCustClassDefine为‘2’
        PARENT_VALUE        INT,
        PARENT_ID           INT

    )

    --IF @IN_CLASSDETAIL_ID ISNULL OR @IN_CLASSDETAIL_ID <> 0
     --   SET @IN_CLASSDEFINE_ID = 0


    IF @IN_CLASSDETAIL_ID IS NULL OR @IN_CLASSDETAIL_ID = 0
        INSERT INTO #TMP_QUERY_TCustClassDetail(CLASSDEFINE_ID,CLASSDEFINE_NAME,CLASSDETAIL_ID,CLASSDETAIL_NAME,CANMODI,CANADD,CANDEL,BOTTOM_FLAG,TABLE_FLAG)
           SELECT A.CLASSDEFINE_ID,'', A.CLASSDETAIL_ID,A.CLASSDETAIL_NAME,A.CANMODI,A.CANADD,A.CANDEL,1,1
           FROM TCustClassDetail A
           WHERE (A.CLASSDEFINE_ID   = @IN_CLASSDEFINE_ID   OR @IN_CLASSDEFINE_ID   IS NULL OR @IN_CLASSDEFINE_ID   = 0 )
               AND(A.CLASSDETAIL_ID   = @IN_CLASSDETAIL_ID   OR @IN_CLASSDETAIL_ID   IS NULL OR @IN_CLASSDETAIL_ID   = 0 )

    INSERT INTO #TMP_QUERY_TCustClassDetail(CLASSDEFINE_ID,CLASSDETAIL_NAME,CANMODI,CANADD,CANDEL,BOTTOM_FLAG,TABLE_FLAG,PARENT_VALUE,PARENT_ID)
        SELECT A.CLASSDEFINE_ID,A.CLASSDEFINE_NAME,A.CANMODI,A.CANADD,A.CANDEL,2,2,A.PARENT_VALUE,A.PARENT_ID
        FROM TCustClassDefine A
        WHERE   (A.PARENT_ID = @IN_CLASSDEFINE_ID  )
            AND (A.PARENT_VALUE = @IN_CLASSDETAIL_ID )

    UPDATE #TMP_QUERY_TCustClassDetail
        SET BOTTOM_FLAG = 2
        FROM #TMP_QUERY_TCustClassDetail A, (SELECT DISTINCT PARENT_VALUE FROM TCustClassDefine ) B
        WHERE A.CLASSDETAIL_ID = B.PARENT_VALUE

    SELECT * FROM #TMP_QUERY_TCustClassDetail
GO
