USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TTEAMQUOTA @IN_TEAM_ID        INT,    --团队ID，-1表示无团队的销售发生
                                     @IN_PRODUCT_ID     INT,    --产品ID
                                     @IN_INPUT_MAN      INT,    --操作员
                                     @IN_PREPRODUCT_ID  INT = NULL, --预发行产品ID
                                     @IN_SERVICE_MAN    INT = NULL, --传入客户经理时仅返回其所在团队数据
                                     @IN_SUB_PRODUCT_ID INT = 0
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    SET @IN_PRODUCT_ID = ISNULL(@IN_PRODUCT_ID,0)
    SET @IN_SERVICE_MAN = ISNULL(@IN_SERVICE_MAN,0)
    DECLARE @V_TEAM_ID INT, @V_USER_ID INT
    DECLARE @V_BIND_PRODUCT_ID INT
    SELECT @V_USER_ID = USER_ID FROM TSYSTEMINFO
    SELECT @V_TEAM_ID = A.TEAM_ID FROM TManagerTeams A
        WHERE A.LEADER = @IN_INPUT_MAN OR EXISTS(SELECT 1 FROM TManagerTeamMembers Z WHERE A.TEAM_ID = Z.TEAM_ID AND Z.MANAGERID = @IN_INPUT_MAN)
    IF @V_TEAM_ID IS NULL SET @V_TEAM_ID = -1
    DECLARE @V_IS_FLAG INT
    DECLARE @V_PRE_DZ_MONE TABLE(
			TEAM_ID INT,  --
			PRE_SALEMONEY DECIMAL(16,3), --团队预约总金额
			DZ_MONE DECIMAL(16,3),   --团队到账总金额
			PRE3000000 INT,          --团队预约小于300万的小额份数
			NUM3000000 INT,          --团队到账小于300万的小额份数
			PRE_QUALIFIEDNUM INT,    --团队预约总份数
			DZ_NUM INT               --团队已到账的预约总份数
			)
    DECLARE @V_TEAM_OP TABLE(TEAM_ID INT, OP_CODE INT)
    SELECT @V_IS_FLAG = 0
    --能够访问所有预约信息
    IF EXISTS(SELECT 1 FROM INTRUST..TOPRIGHT WHERE OP_CODE = @IN_INPUT_MAN AND MENU_ID ='20409' AND FUNC_ID = 2049905)
        SELECT @V_IS_FLAG = 1
	IF @V_USER_ID=2 AND @IN_PREPRODUCT_ID <> 0  --北京信托，针对预发行产品的查询
	BEGIN
		IF @IN_TEAM_ID <> -1 BEGIN
            SELECT @V_BIND_PRODUCT_ID=ISNULL(BIND_PRODUCT_ID,0) FROM TPREPRODUCT WHERE PREPRODUCT_ID=@IN_PREPRODUCT_ID
            --团队成员
            INSERT INTO @V_TEAM_OP(TEAM_ID, OP_CODE)
            SELECT TEAM_ID, LEADER FROM TManagerTeams
            INSERT INTO @V_TEAM_OP(TEAM_ID, OP_CODE)
            SELECT  A.TEAM_ID, B.MANAGERID FROM TManagerTeams A, TManagerTeamMembers B 
				WHERE A.TEAM_ID = B.TEAM_ID AND B.MANAGERID NOT IN(SELECT OP_CODE FROM @V_TEAM_OP)
            --团队预约到账金额统计
            INSERT INTO @V_PRE_DZ_MONE(TEAM_ID,PRE_SALEMONEY,DZ_MONE,PRE3000000,NUM3000000,PRE_QUALIFIEDNUM,DZ_NUM)
            SELECT C.TEAM_ID,SUM(B.PRE_MONEY) AS PRE_SALEMONEY,SUM(B.RG_MONEY) AS DZ_MONEY, 
                    SUM(CASE WHEN (B.PRE_MONEY < 3000000 AND D.CUST_TYPE =1) THEN 1 ELSE 0 END) PRE3000000,
                    SUM(CASE WHEN (B.PRE_MONEY < 3000000 AND B.RG_MONEY > 0 AND D.CUST_TYPE =1) THEN 1 ELSE 0 END) NUM3000000,
                    COUNT(B.PRE_MONEY) PRE_QUALIFIEDNUM,
                    SUM(CASE WHEN (B.RG_MONEY > 0) THEN 1 ELSE 0 END) DZ_NUM
                FROM TPRECONTRACT B,@V_TEAM_OP C,TCUSTOMERS D
                    WHERE D.SERVICE_MAN = C.OP_CODE AND B.PREPRODUCT_ID = @IN_PREPRODUCT_ID 
						AND B.CUST_ID = D.CUST_ID  AND B.PRE_STATUS = '111301'
                    GROUP BY C.TEAM_ID
            SELECT DISTINCT B.SERIAL_NO,B.PRODUCT_ID,A.TEAM_ID,A.TEAM_NO,A.TEAM_NAME,B.QUOTAMONEY,B.ALREADYSALE,B.QUOTA_QUALIFIED_NUM,B.ALREADY_QUALIFIED_NUM,
                   @IN_PREPRODUCT_ID AS PREPRODUCT_ID, ISNULL(C.QUOTAMONEY,B.QUOTAMONEY) AS INIT_QUOTAMONEY,
                   ISNULL(C.QUOTA_QUALIFIED_NUM,B.QUOTA_QUALIFIED_NUM) AS INIT_QUOTA_QUALIFIED_NUM,
                   D.PRE_SALEMONEY,B.PRE_QUALIFIEDNUM,P.PREPRODUCT_NAME, --CASE WHEN A.TEAM_ID = @V_TEAM_ID THEN 1 ELSE 0 END AS INTHISTEAM
                   (CASE WHEN A.LEADER = @IN_INPUT_MAN THEN 1
                        WHEN @V_IS_FLAG = 1 THEN 1
                        ELSE 0 END) AS INTHISTEAM,
                   D.DZ_MONE,D.NUM3000000,D.PRE_QUALIFIEDNUM PRE_TEAM_NUM,D.DZ_NUM,D.PRE3000000
                FROM TManagerTeams A LEFT JOIN TTEAMQUOTA B ON (A.TEAM_ID = B.TEAM_ID AND B.PREPRODUCT_ID = @IN_PREPRODUCT_ID)
                     LEFT JOIN HTEAMQUOTA C ON C.LIST_ID = 0 AND B.TEAM_ID = C.TEAM_ID AND B.PREPRODUCT_ID = C.PREPRODUCT_ID
                     LEFT JOIN @V_PRE_DZ_MONE D ON A.TEAM_ID = D.TEAM_ID,
                     TPREPRODUCT P
                WHERE (ISNULL(B.PREPRODUCT_ID,@IN_PREPRODUCT_ID) = P.PREPRODUCT_ID)
                    AND(A.TEAM_ID = @IN_TEAM_ID OR @IN_TEAM_ID = 0 OR @IN_TEAM_ID IS NULL)
                    AND(@IN_SERVICE_MAN = 0 OR A.LEADER = @IN_SERVICE_MAN OR EXISTS(SELECT 1 FROM TManagerTeamMembers Z WHERE A.TEAM_ID = Z.TEAM_ID AND Z.MANAGERID = @IN_SERVICE_MAN))
                ORDER BY A.TEAM_NO
        END
        ELSE
        BEGIN
            SELECT B.*, A.TEAM_NAME
                FROM TTEAMQUOTA B LEFT JOIN TManagerTeams A ON B.TEAM_ID = A.TEAM_ID
                WHERE (B.TEAM_ID = @IN_TEAM_ID OR @IN_TEAM_ID = 0 OR @IN_TEAM_ID IS NULL)
                    AND (B.PRODUCT_ID = @IN_PRODUCT_ID OR @IN_PRODUCT_ID = 0 OR @IN_PRODUCT_ID IS NULL)
                    AND (B.PREPRODUCT_ID = @IN_PREPRODUCT_ID OR @IN_PREPRODUCT_ID = 0 OR @IN_PREPRODUCT_ID IS NULL)
                    AND(@IN_SERVICE_MAN = 0 OR A.LEADER = @IN_SERVICE_MAN OR EXISTS(SELECT 1 FROM TManagerTeamMembers Z WHERE A.TEAM_ID = Z.TEAM_ID AND Z.MANAGERID = @IN_SERVICE_MAN))
		END
		RETURN
	END
    IF @IN_PRODUCT_ID <> 0-- OR @IN_PREPRODUCT_ID IS NULL --针对产品的查询
    BEGIN
        IF @IN_TEAM_ID <> -1 BEGIN
            --团队成员
            INSERT INTO @V_TEAM_OP(TEAM_ID, OP_CODE)
            SELECT TEAM_ID, LEADER FROM TManagerTeams
            INSERT INTO @V_TEAM_OP(TEAM_ID, OP_CODE)
            SELECT  A.TEAM_ID, B.MANAGERID FROM TManagerTeams A, TManagerTeamMembers B 
				WHERE A.TEAM_ID = B.TEAM_ID AND B.MANAGERID NOT IN(SELECT OP_CODE FROM @V_TEAM_OP)
            --团队预约到账金额统计
            IF @V_USER_ID=2
            BEGIN --北京信托要求：预约到账统计，按客户经理，而不是按实际预约人
				INSERT INTO @V_PRE_DZ_MONE(TEAM_ID,PRE_SALEMONEY,DZ_MONE,PRE3000000,NUM3000000,PRE_QUALIFIEDNUM,DZ_NUM)
				SELECT C.TEAM_ID,SUM(B.PRE_MONEY) AS PRE_SALEMONEY,SUM(B.RG_MONEY) AS DZ_MONEY, 
						SUM(CASE WHEN (B.PRE_MONEY < 3000000 AND D.CUST_TYPE =1) THEN 1 ELSE 0 END) PRE3000000,
						SUM(CASE WHEN (B.PRE_MONEY < 3000000 AND B.RG_MONEY > 0 AND D.CUST_TYPE =1) THEN 1 ELSE 0 END) NUM3000000
						,COUNT(B.PRE_MONEY),
						SUM(CASE WHEN (B.RG_MONEY > 0) THEN 1 ELSE 0 END) DZ_NUM
					FROM TPRECONTRACT B,@V_TEAM_OP C,TCUSTOMERS D
						WHERE D.SERVICE_MAN = C.OP_CODE AND B.PRODUCT_ID = @IN_PRODUCT_ID 
							AND B.CUST_ID = D.CUST_ID  AND B.PRE_STATUS = '111301'
						GROUP BY C.TEAM_ID
            END
            ELSE
            INSERT INTO @V_PRE_DZ_MONE(TEAM_ID,PRE_SALEMONEY,DZ_MONE,PRE3000000,NUM3000000,PRE_QUALIFIEDNUM,DZ_NUM)
            SELECT C.TEAM_ID,SUM(B.PRE_MONEY) AS PRE_SALEMONEY,SUM(B.RG_MONEY) AS DZ_MONEY, 
                    SUM(CASE WHEN (B.PRE_MONEY < 3000000 AND D.CUST_TYPE =1) THEN 1 ELSE 0 END) PRE3000000,
                    SUM(CASE WHEN (B.PRE_MONEY < 3000000 AND B.RG_MONEY > 0 AND D.CUST_TYPE =1) THEN 1 ELSE 0 END) NUM3000000
                    ,COUNT(B.PRE_MONEY),
                    SUM(CASE WHEN (B.RG_MONEY > 0) THEN 1 ELSE 0 END) DZ_NUM
                FROM TPRECONTRACT B,@V_TEAM_OP C,TCUSTOMERS D
                    WHERE B.LINK_MAN = C.OP_CODE AND B.PRODUCT_ID = @IN_PRODUCT_ID 
						AND B.CUST_ID = D.CUST_ID  AND B.PRE_STATUS = '111301'
                    GROUP BY C.TEAM_ID
            
            SELECT DISTINCT B.SERIAL_NO,@IN_PRODUCT_ID AS PRODUCT_ID,A.TEAM_ID,A.TEAM_NO,A.TEAM_NAME,B.QUOTAMONEY,B.ALREADYSALE,B.QUOTA_QUALIFIED_NUM,B.ALREADY_QUALIFIED_NUM,
                   B.PRODUCT_ID, ISNULL(C.QUOTAMONEY,B.QUOTAMONEY) AS INIT_QUOTAMONEY,
                   ISNULL(C.QUOTA_QUALIFIED_NUM,B.QUOTA_QUALIFIED_NUM) AS INIT_QUOTA_QUALIFIED_NUM,
                   D.PRE_SALEMONEY,D.PRE_QUALIFIEDNUM,D.DZ_MONE,D.NUM3000000, P.PRODUCT_NAME, --CASE WHEN A.TEAM_ID = @V_TEAM_ID THEN 1 ELSE 0 END AS INTHISTEAM
                   (CASE WHEN A.LEADER = @IN_INPUT_MAN THEN 1
                        WHEN @V_IS_FLAG = 1 THEN 1
                        ELSE 0 END) AS INTHISTEAM,D.PRE_QUALIFIEDNUM PRE_TEAM_NUM,D.DZ_NUM,D.PRE3000000
                FROM TManagerTeams A LEFT JOIN TTEAMQUOTA B ON (A.TEAM_ID = B.TEAM_ID AND B.PRODUCT_ID = @IN_PRODUCT_ID AND (ISNULL(B.SUB_PRODUCT_ID,0) = ISNULL(@IN_SUB_PRODUCT_ID,0)))
                     LEFT JOIN HTEAMQUOTA C ON C.LIST_ID = 0 AND B.TEAM_ID = C.TEAM_ID AND B.PREPRODUCT_ID = C.PREPRODUCT_ID
                     LEFT JOIN @V_PRE_DZ_MONE D ON D.TEAM_ID=B.TEAM_ID
                     ,INTRUST..TPRODUCT P
                WHERE ISNULL(B.PRODUCT_ID,@IN_PRODUCT_ID) = P.PRODUCT_ID
                    AND (A.TEAM_ID = @IN_TEAM_ID OR @IN_TEAM_ID = 0 OR @IN_TEAM_ID IS NULL)
                    AND(@IN_SERVICE_MAN = 0 OR A.LEADER = @IN_SERVICE_MAN OR EXISTS(SELECT 1 FROM TManagerTeamMembers Z WHERE A.TEAM_ID = Z.TEAM_ID AND Z.MANAGERID = @IN_SERVICE_MAN))
                ORDER BY A.TEAM_NO
        END
        ELSE
            SELECT B.*, A.TEAM_NAME
                FROM TTEAMQUOTA B LEFT JOIN TManagerTeams A ON B.TEAM_ID = A.TEAM_ID
                WHERE (B.TEAM_ID = @IN_TEAM_ID OR @IN_TEAM_ID = 0 OR @IN_TEAM_ID IS NULL)
                    AND (B.PRODUCT_ID = @IN_PRODUCT_ID OR @IN_PRODUCT_ID = 0 OR @IN_PRODUCT_ID IS NULL)
                    AND (B.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID OR @IN_SUB_PRODUCT_ID = 0 OR @IN_SUB_PRODUCT_ID IS NULL)
                    AND (B.PREPRODUCT_ID = @IN_PREPRODUCT_ID OR @IN_PREPRODUCT_ID = 0 OR @IN_PREPRODUCT_ID IS NULL)
                    AND(@IN_SERVICE_MAN = 0 OR A.LEADER = @IN_SERVICE_MAN OR EXISTS(SELECT 1 FROM TManagerTeamMembers Z WHERE A.TEAM_ID = Z.TEAM_ID AND Z.MANAGERID = @IN_SERVICE_MAN))
    END
    ELSE IF @IN_PREPRODUCT_ID <> 0  --针对预发行产品的查询 北京信托(USER_ID=2)不会进入此块
    BEGIN
		--针对国联信托:改为不用对产品及团队设置即将可预约(直接预约)
		IF NOT EXISTS (SELECT * FROM TTEAMQUOTA WHERE TEAM_ID<>-1 AND PREPRODUCT_ID=@IN_PREPRODUCT_ID) AND (@V_USER_ID=7)
		BEGIN
			SELECT (SELECT SUM(PRE_MONEY) FROM TPRECONTRACT WHERE PREPRODUCT_ID=@IN_PREPRODUCT_ID) PRE_SALEMONEY,
				PRE_MONEY QUOTAMONEY,CAST(PRE_MONEY AS INT) QUOTA_QUALIFIED_NUM ,
				(SELECT PRE_QUALIFIEDNUM FROM TTEAMQUOTA WHERE PREPRODUCT_ID=@IN_PREPRODUCT_ID) PRE_QUALIFIEDNUM
				FROM TPREPRODUCT WHERE PREPRODUCT_ID=@IN_PREPRODUCT_ID
			RETURN
		END
        IF @IN_TEAM_ID <> -1 BEGIN
            SELECT @V_BIND_PRODUCT_ID=ISNULL(BIND_PRODUCT_ID,0) FROM TPREPRODUCT WHERE PREPRODUCT_ID=@IN_PREPRODUCT_ID
            --团队成员
            INSERT INTO @V_TEAM_OP(TEAM_ID, OP_CODE)
            SELECT TEAM_ID, LEADER FROM TManagerTeams
            INSERT INTO @V_TEAM_OP(TEAM_ID, OP_CODE)
            SELECT  A.TEAM_ID, B.MANAGERID FROM TManagerTeams A, TManagerTeamMembers B 
				WHERE A.TEAM_ID = B.TEAM_ID AND B.MANAGERID NOT IN(SELECT OP_CODE FROM @V_TEAM_OP)
            --团队预约到账金额统计
            INSERT INTO @V_PRE_DZ_MONE(TEAM_ID,PRE_SALEMONEY,DZ_MONE,PRE3000000,NUM3000000,PRE_QUALIFIEDNUM,DZ_NUM)
            SELECT C.TEAM_ID,SUM(B.PRE_MONEY) AS PRE_SALEMONEY,SUM(B.RG_MONEY) AS DZ_MONEY, 
                    SUM(CASE WHEN (B.PRE_MONEY < 3000000 AND D.CUST_TYPE =1) THEN 1 ELSE 0 END) PRE3000000,
                    SUM(CASE WHEN (B.PRE_MONEY < 3000000 AND B.RG_MONEY > 0 AND D.CUST_TYPE =1) THEN 1 ELSE 0 END) NUM3000000,
                    COUNT(B.PRE_MONEY) PRE_QUALIFIEDNUM,
                    SUM(CASE WHEN (B.RG_MONEY > 0) THEN 1 ELSE 0 END) DZ_NUM
                FROM TPRECONTRACT B,@V_TEAM_OP C,TCUSTOMERS D
                    WHERE B.LINK_MAN = C.OP_CODE AND B.PREPRODUCT_ID = @IN_PREPRODUCT_ID 
						AND B.CUST_ID = D.CUST_ID  AND B.PRE_STATUS = '111301'
                    GROUP BY C.TEAM_ID
            SELECT DISTINCT B.SERIAL_NO,B.PRODUCT_ID,A.TEAM_ID,A.TEAM_NO,A.TEAM_NAME,B.QUOTAMONEY,B.ALREADYSALE,B.QUOTA_QUALIFIED_NUM,B.ALREADY_QUALIFIED_NUM,
                   @IN_PREPRODUCT_ID AS PREPRODUCT_ID, ISNULL(C.QUOTAMONEY,B.QUOTAMONEY) AS INIT_QUOTAMONEY,
                   ISNULL(C.QUOTA_QUALIFIED_NUM,B.QUOTA_QUALIFIED_NUM) AS INIT_QUOTA_QUALIFIED_NUM,
                   D.PRE_SALEMONEY,B.PRE_QUALIFIEDNUM,P.PREPRODUCT_NAME, --CASE WHEN A.TEAM_ID = @V_TEAM_ID THEN 1 ELSE 0 END AS INTHISTEAM
                   (CASE WHEN A.LEADER = @IN_INPUT_MAN THEN 1
                        WHEN @V_IS_FLAG = 1 THEN 1
                        ELSE 0 END) AS INTHISTEAM,
                   D.DZ_MONE,D.NUM3000000,D.PRE_QUALIFIEDNUM PRE_TEAM_NUM,D.DZ_NUM,D.PRE3000000
                FROM TManagerTeams A LEFT JOIN TTEAMQUOTA B ON (A.TEAM_ID = B.TEAM_ID AND B.PREPRODUCT_ID = @IN_PREPRODUCT_ID)
                     LEFT JOIN HTEAMQUOTA C ON C.LIST_ID = 0 AND B.TEAM_ID = C.TEAM_ID AND B.PREPRODUCT_ID = C.PREPRODUCT_ID
                     LEFT JOIN @V_PRE_DZ_MONE D ON A.TEAM_ID = D.TEAM_ID,
                     TPREPRODUCT P
                WHERE (ISNULL(B.PREPRODUCT_ID,@IN_PREPRODUCT_ID) = P.PREPRODUCT_ID)
                    AND(A.TEAM_ID = @IN_TEAM_ID OR @IN_TEAM_ID = 0 OR @IN_TEAM_ID IS NULL)
                    AND(@IN_SERVICE_MAN = 0 OR A.LEADER = @IN_SERVICE_MAN OR EXISTS(SELECT 1 FROM TManagerTeamMembers Z WHERE A.TEAM_ID = Z.TEAM_ID AND Z.MANAGERID = @IN_SERVICE_MAN))
                ORDER BY A.TEAM_NO
        END
        ELSE
        BEGIN
            SELECT B.*, A.TEAM_NAME
                FROM TTEAMQUOTA B LEFT JOIN TManagerTeams A ON B.TEAM_ID = A.TEAM_ID
                WHERE (B.TEAM_ID = @IN_TEAM_ID OR @IN_TEAM_ID = 0 OR @IN_TEAM_ID IS NULL)
                    AND (B.PRODUCT_ID = @IN_PRODUCT_ID OR @IN_PRODUCT_ID = 0 OR @IN_PRODUCT_ID IS NULL)
                    AND (B.PREPRODUCT_ID = @IN_PREPRODUCT_ID OR @IN_PREPRODUCT_ID = 0 OR @IN_PREPRODUCT_ID IS NULL)
                    AND(@IN_SERVICE_MAN = 0 OR A.LEADER = @IN_SERVICE_MAN OR EXISTS(SELECT 1 FROM TManagerTeamMembers Z WHERE A.TEAM_ID = Z.TEAM_ID AND Z.MANAGERID = @IN_SERVICE_MAN))
			
		END
    END
    ELSE
        SELECT B.*, A.TEAM_NAME FROM TTEAMQUOTA B LEFT JOIN TManagerTeams A ON B.TEAM_ID = A.TEAM_ID WHERE 1=0
GO
