USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TCUSTINFO_ORGAN_LOAD @IN_CUST_ID   INTEGER,
				                              @IN_INPUT_MAN INTEGER 
WITH ENCRYPTION
AS
    SELECT * FROM TCUSTINFO_ORGAN WHERE CUST_ID=@IN_CUST_ID
GO
