USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TDEPLOYEMAIL
        @IN_CUST_ID          INT          ,    --客户ID
        @IN_SEND_DATE_START  INT          ,    --发送日期(起)
        @IN_SEND_DATE_END    INT          ,    --发送日期(止)
        @IN_EMAIL            VARCHAR(40)  ,    --接收的EMAIL
        @IN_TITLE            NVARCHAR(40) ,    --邮件主题
        @IN_SEND_FLAG        INT          ,    --发送标识：1未发送，2已发送
        @IN_INPUT_MAN        INTEGER           --操作员
									
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    
    IF ISNULL(@IN_SEND_DATE_START,0)=0
		SET @IN_SEND_DATE_START=20120101
    --DECLARE @V_ERROR NVARCHAR(200), @IBUSI_FLAG INT, @SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)
    IF ISNULL(@IN_SEND_DATE_END,0)=0
		SET @IN_SEND_DATE_END=20990101
	SELECT * FROM TDEPLOYEMAIL
		WHERE (CUST_ID=@IN_CUST_ID OR ISNULL(@IN_CUST_ID,0)=0)
		AND SEND_DATE>=@IN_SEND_DATE_START
		AND SEND_DATE<=@IN_SEND_DATE_END
		AND (TITLE=@IN_TITLE OR ISNULL(@IN_TITLE,0)=0)
		AND (EMAIL LIKE '%'+@IN_EMAIL+'%' OR ISNULL(@IN_EMAIL,'')='')
		AND (SEND_FLAG=@IN_SEND_FLAG OR ISNULL(@IN_SEND_FLAG,0)=0)

		
GO
