USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_MODI_THOLIDAYDATE @IN_SERIAL_NO    INT,    --序号 如果为null则添加
                                      @IN_HOLIDAY_ID   INT,    --节假日ID
                                      @IN_YEARINT      INT,    --年份
                                      @IN_MMDDINT      INT,    --日期mmdd
                                      @IN_INPUT_MAN    INT
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    DECLARE @V_RET_CODE INT, @IBUSI_FLAG INT, @SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)
    SELECT @V_RET_CODE = -10130000, @IBUSI_FLAG = 10130
    SELECT @SBUSI_NAME = N'修改节假日例外日期', @SSUMMARY = N'修改节假日例外日期'

    IF NOT EXISTS(SELECT 1 FROM THOLIDAYS WHERE HOLIDAY_ID = @IN_HOLIDAY_ID)
        RETURN @V_RET_CODE - 4 --节假日不存在
    IF EXISTS(SELECT 1 FROM THOLIDAYDATE WHERE HOLIDAY_ID = @IN_HOLIDAY_ID AND YEARINT = @IN_YEARINT AND MMDDINT <> @IN_MMDDINT)
        RETURN @V_RET_CODE - 5 --该节日当年已存在例外日期
    IF ISDATE(20000000+@IN_MMDDINT) = 0
        RETURN @V_RET_CODE - 2 --输入节日日期无效，需要mmdd形式

    BEGIN TRANSACTION

    IF NOT EXISTS(SELECT 1 FROM THOLIDAYDATE WHERE SERIAL_NO = @IN_SERIAL_NO)
        INSERT INTO THOLIDAYDATE(HOLIDAY_ID,YEARINT,MMDDINT) VALUES(@IN_HOLIDAY_ID,@IN_YEARINT,@IN_MMDDINT)
    ELSE
        UPDATE THOLIDAYDATE SET HOLIDAY_ID = @IN_HOLIDAY_ID, YEARINT = @IN_YEARINT, MMDDINT = @IN_MMDDINT WHERE SERIAL_NO = @IN_SERIAL_NO
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SELECT @SSUMMARY = N'修改节假日例外日期'
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
