USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TROLERIGHT_MENU
    @IN_ROLE_ID INT,
    @IN_MENU_ID NVARCHAR(10) = NULL,
    @IN_MENU_NAME NVARCHAR(60) = NULL
WITH ENCRYPTION
AS
    DECLARE @V_USER_ID INT
    SELECT @V_USER_ID = USER_ID FROM TSYSTEMINFO
    SELECT DISTINCT A.MENU_ID
        FROM TROLERIGHT A, TMENUINFO B
        WHERE (A.MENU_ID = B.MENU_ID) AND (A.ROLE_ID = @IN_ROLE_ID)
            AND (A.MENU_ID LIKE @IN_MENU_ID+'%' OR @IN_MENU_ID IS NULL OR @IN_MENU_ID = N'')
            AND (B.MENU_NAME LIKE '%'+@IN_MENU_NAME+'%' OR @IN_MENU_NAME IS NULL OR @IN_MENU_NAME = N'')
            AND (B.USER_ID = @V_USER_ID OR B.USER_ID = 0)
        ORDER BY A.MENU_ID
GO
