USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_DEL_TPREPRODUCT @IN_PREPRODUCT_ID  INT,    --预发行产品ID
                                    @IN_INPUT_MAN      INT    --操作员
WITH ENCRYPTION
AS
    SET NOCOUNT ON

    DECLARE @V_RET_CODE INT, @IBUSI_FLAG INT, @SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)
    SELECT @V_RET_CODE = -19003000, @IBUSI_FLAG = 19003
    SELECT @SBUSI_NAME = N'删除“crm信息库”产品信息', @SSUMMARY = N'删除“crm信息库”产品信息'

    DECLARE @V_PRODUCT_ID INT

    IF @IN_PREPRODUCT_ID <> 0 AND NOT EXISTS(SELECT 1 FROM TPREPRODUCT WHERE PREPRODUCT_ID = @IN_PREPRODUCT_ID)
        RETURN -20402001 --记录不存在
    SELECT @V_PRODUCT_ID = BIND_PRODUCT_ID FROM TPREPRODUCT WHERE PREPRODUCT_ID = @IN_PREPRODUCT_ID

    BEGIN TRANSACTION

    DELETE FROM TPREPRODUCT WHERE PREPRODUCT_ID = @IN_PREPRODUCT_ID
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    DELETE FROM TATTACHMENTS WHERE DF_TABLE_ID = 1213 AND DF_SERIAL_NO = @IN_PREPRODUCT_ID
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SELECT @SSUMMARY = N'删除“crm信息库”产品信息'
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
