USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_ADD_TSCORESUBJECT   @IN_SUBJECT_NO      NVARCHAR(16),    --科目编号
                                        @IN_SUBJECT_NAME    NVARCHAR(60),    --科目名称
                                        @IN_SUMMARY         NVARCHAR(200),   --描述
                                        @IN_INPUT_MAN       INT              --录入操作员
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    SELECT @SBUSI_NAME = N'增加评分科目'
    SELECT @SSUMMARY = N'增加评分科目'
    SELECT @IBUSI_FLAG = 21001
    SELECT @V_RET_CODE = -21001000

    IF EXISTS(SELECT * FROM TSCORESUBJECT WHERE SUBJECT_NO = @IN_SUBJECT_NO)
        RETURN @V_RET_CODE - 11   -- 评分科目信息已存在

    BEGIN TRANSACTION

    INSERT INTO TSCORESUBJECT(SUBJECT_NO,SUBJECT_NAME,SUMMARY,INPUT_MAN)
         VALUES(@IN_SUBJECT_NO,@IN_SUBJECT_NAME,@IN_SUMMARY,@IN_INPUT_MAN)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    SELECT @SSUMMARY = N'增加评分科目，科目编号：'+RTRIM(@IN_SUBJECT_NO)+N',科目名称：'+RTRIM(@IN_SUBJECT_NAME)
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
