USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_CHECK_TCustomerChanges   @IN_CUST_ID             INT,            --客户ID
                                             @IN_CHECK_FLAG          INT = 1,        --审核标志 --0不要求审核，1未审核，2已审核通过，3审核不通过
                                             @IN_INPUT_MAN           INT = 0         --操作员
WITH ENCRYPTION
AS
    DECLARE @V_MANAGERNAME_BEFORE   NVARCHAR(64), @V_MANAGERNAME_NOW NVARCHAR(64),
            @V_MANAGERID_BEFORE INT, @V_MANAGERID_NOW INT,@V_ERROR NVARCHAR(200)
    DECLARE @V_RET_CODE INT, @IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)
    DECLARE @V_NEW_FIELD_INFO NVARCHAR(1000),@V_SEX INT,@V_CARD_TYPE INT,@V_CUST_TYPE INT,@V_TOUCH_TYPE INT
    DECLARE @V_CUST_SOURCE INT,@V_WTRLX NVARCHAR(2),@V_SERVICE_MAN INT,@V_MODI_MAN INT
    SELECT @V_RET_CODE = -50101000, @IBUSI_FLAG = 50101
    SELECT @SBUSI_NAME = N'客户信息修改审核', @SSUMMARY = N'客户信息修改审核'
    
    BEGIN TRY
    SELECT TOP 1 @V_MODI_MAN=INPUT_MAN FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND ISNULL(CHECK_FLAG,1)=1
    IF @@ROWCOUNT=0
    BEGIN
        SET @V_ERROR = N'待审核客户信息不存在！'
		RAISERROR(@V_ERROR,16,1)
	END
	IF @V_MODI_MAN=@IN_INPUT_MAN
		RAISERROR('不能自己审核',16,1)
	IF NOT EXISTS (SELECT 1 FROM TSYSCONTROL WHERE FLAG_TYPE='CUSTINFO_CHANGE' AND VALUE=1)
    BEGIN--不审核
		SET @V_ERROR = N'客户信息修改配置为不审核！如果需要审核，请配置TSYSCONTROL.CUSTINFO_CHANGE'
		RAISERROR(@V_ERROR,16,1)
    END
	BEGIN TRANSACTION
	IF @IN_CHECK_FLAG=3--3审核不通过，业务中的数据不做处理
	BEGIN
		UPDATE TCustomerChanges SET CHECK_FLAG = @IN_CHECK_FLAG, CHECK_MAN = @IN_INPUT_MAN WHERE CUST_ID = @IN_CUST_ID
	    
		SET @SSUMMARY = N'客户信息修改审核，操作员：' + CAST(@IN_INPUT_MAN AS NVARCHAR)+'；审核不通过客户ID：'+CAST(@IN_CUST_ID AS NVARCHAR)
		INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
			VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
	    
		COMMIT TRANSACTION
		RETURN
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='CUST_TYPE_NAME' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		IF @V_NEW_FIELD_INFO='个人' SET @V_CUST_TYPE = 1
		ELSE SET @V_CUST_TYPE = 2
		UPDATE TCustomers SET CUST_TYPE_NAME = @V_NEW_FIELD_INFO,CUST_TYPE=@V_CUST_TYPE WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET CUST_TYPE_NAME = @V_NEW_FIELD_INFO,CUST_TYPE=@V_CUST_TYPE WHERE CUST_ID = @IN_CUST_ID
	END
	
    SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='CUST_NAME' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET CUST_NAME = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--客户证件信息表
		UPDATE TCUSTCARDINFO SET CARD_CUST_NAME = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET CUST_NAME = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
    SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='CUST_TEL' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET CUST_TEL = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET CUST_TEL = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
    
    SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='POST_ADDRESS' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET POST_ADDRESS = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET POST_ADDRESS = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='POST_ADDRESS2' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET POST_ADDRESS2 = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET POST_ADDRESS2 = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='POST_CODE' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET POST_CODE = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET POST_CODE = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='POST_CODE2' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET POST_CODE2 = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET POST_CODE2 = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='CARD_TYPE_NAME' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		SELECT @V_CUST_TYPE=CUST_TYPE FROM TCustomers WHERE CUST_ID=@IN_CUST_ID
		IF @V_CUST_TYPE=1 --个人
			SELECT @V_CARD_TYPE = TYPE_VALUE FROM TDICTPARAM  WHERE TYPE_ID=1108 AND TYPE_CONTENT=@V_NEW_FIELD_INFO
		ELSE  --机构
			SELECT @V_CARD_TYPE = TYPE_VALUE FROM TDICTPARAM  WHERE TYPE_ID=2108 AND TYPE_CONTENT=@V_NEW_FIELD_INFO
		UPDATE TCustomers SET CARD_TYPE_NAME = @V_NEW_FIELD_INFO,CARD_TYPE=@V_CARD_TYPE WHERE CUST_ID = @IN_CUST_ID
		--客户证件信息表
		UPDATE TCUSTCARDINFO SET CARD_TYPE_NAME = @V_NEW_FIELD_INFO,CARD_TYPE=@V_CARD_TYPE WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET CARD_TYPE_NAME = @V_NEW_FIELD_INFO,CARD_TYPE=@V_CARD_TYPE WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='CARD_ID' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET CARD_ID = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--客户证件信息表
		UPDATE TCUSTCARDINFO SET CARD_ID = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET CARD_ID = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='SEX_NAME' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		IF @V_NEW_FIELD_INFO='男' SET @V_SEX = 1
		ELSE  SET @V_SEX = 2
		UPDATE TCustomers SET SEX_NAME = @V_NEW_FIELD_INFO,SEX=@V_SEX WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET SEX_NAME = @V_NEW_FIELD_INFO,SEX=@V_SEX WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='O_TEL' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET O_TEL = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET O_TEL = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='H_TEL' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET H_TEL = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET H_TEL = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='MOBILE' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET MOBILE = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET MOBILE = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='BP' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET BP = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET BP = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT  TOP 1 @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='FAX' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET FAX = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET FAX = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='E_MAIL' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET E_MAIL = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET E_MAIL = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='TOUCH_TYPE_NAME' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		SELECT @V_TOUCH_TYPE = TYPE_VALUE FROM TDICTPARAM  WHERE TYPE_ID=1109 AND TYPE_CONTENT=@V_NEW_FIELD_INFO
		UPDATE TCustomers SET TOUCH_TYPE_NAME = @V_NEW_FIELD_INFO,TOUCH_TYPE=@V_TOUCH_TYPE WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET TOUCH_TYPE_NAME = @V_NEW_FIELD_INFO,TOUCH_TYPE=@V_TOUCH_TYPE WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='CUST_SOURCE_NAME' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		SELECT @V_CUST_SOURCE = TYPE_VALUE FROM TDICTPARAM  WHERE TYPE_ID=1110 AND TYPE_CONTENT=@V_NEW_FIELD_INFO
		UPDATE TCustomers SET CUST_SOURCE_NAME = @V_NEW_FIELD_INFO,CUST_SOURCE=@V_CUST_SOURCE WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET CUST_SOURCE_NAME = @V_NEW_FIELD_INFO,CUST_SOURCE=@V_CUST_SOURCE WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT  TOP 1 @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='SUMMARY' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET SUMMARY = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET SUMMARY = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='MONEY_SOURCE' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET MONEY_SOURCE = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET MONEY_SOURCE = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='MONEY_SOURCE_NAME' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET MONEY_SOURCE_NAME = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET MONEY_SOURCE_NAME = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='CUST_NO' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET CUST_NO = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET CUST_NO = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='LEGAL_MAN' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET LEGAL_MAN = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET LEGAL_MAN = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='LEGAL_ADDRESS' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET LEGAL_ADDRESS = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET LEGAL_ADDRESS = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='BIRTHDAY' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET BIRTHDAY = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET BIRTHDAY = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='AGE' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET AGE = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET AGE = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='PRINT_DEPLOY_BILL' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET PRINT_DEPLOY_BILL = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET PRINT_DEPLOY_BILL = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='PRINT_POST_INFO' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET PRINT_POST_INFO = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET PRINT_POST_INFO = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='IS_LINK' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET IS_LINK = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET IS_LINK = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='SERVICE_MAN' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		SELECT @V_SERVICE_MAN = OP_CODE FROM TOPERATOR WHERE OP_NAME=@V_NEW_FIELD_INFO
		UPDATE TCustomers SET SERVICE_MAN = @V_SERVICE_MAN WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET SERVICE_MAN = @V_SERVICE_MAN WHERE CUST_ID = @IN_CUST_ID
		UPDATE INTRUST..TCONTRACT SET SERVICE_MAN = @V_SERVICE_MAN WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG = 2
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='VIP_CARD_ID' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET VIP_CARD_ID = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET VIP_CARD_ID = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='VIP_DATE' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET VIP_DATE = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET VIP_DATE = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='HGTZR_BH' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET HGTZR_BH = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET HGTZR_BH = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='VOC_TYPE_NAME' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		--VOC_TYPE:个人职业机构行业类别 未处理
		UPDATE TCustomers SET VOC_TYPE_NAME = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET VOC_TYPE_NAME = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='COMPANY_UNIT' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET COMPANY_UNIT = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='COMPANY_DEPART' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET COMPANY_DEPART = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='COMPANY_DOSITION' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET COMPANY_POSITION = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='EAST_JG_TYPE' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET EAST_JG_TYPE = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET EAST_JG_TYPE = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		SELECT @V_CUST_TYPE=CUST_TYPE FROM TCustomers WHERE CUST_ID = @IN_CUST_ID
		IF @V_CUST_TYPE=2 --2机构
			SELECT @V_WTRLX = ADDITIVE_VALUE FROM TDICTPARAM WHERE TYPE_VALUE = @V_NEW_FIELD_INFO
		ELSE --1个人
			SET @V_WTRLX='1'
		UPDATE INTRUST..TE_WTRXX SET WTRLX = @V_WTRLX WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='JG_WTRLX2' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET JG_WTRLX2 = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET JG_WTRLX2 = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		UPDATE INTRUST..TE_WTRXX SET JG_WTRLX2 = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='VOC_TYPE' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers 
		    SET VOC_TYPE = @V_NEW_FIELD_INFO,VOC_TYPE_NAME=(SELECT TYPE_CONTENT FROM TDICTPARAM WHERE TYPE_VALUE=@V_NEW_FIELD_INFO)
		    WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO 
		    SET VOC_TYPE = @V_NEW_FIELD_INFO,VOC_TYPE_NAME=(SELECT TYPE_CONTENT FROM TDICTPARAM WHERE TYPE_VALUE=@V_NEW_FIELD_INFO)
		    WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='JG_CUST_TYPE' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET JG_CUST_TYPE = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET JG_CUST_TYPE = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='CONTACT_MAN' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET CONTACT_MAN = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		UPDATE INTRUST..TCUSTOMERINFO SET CONTACT_MAN = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='TRUE_FLAG' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET TRUE_FLAG = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
		--同步到信托客户表中
		--UPDATE INTRUST..TCUSTOMERINFO SET TRUE_FLAG = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	SELECT TOP 1  @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='STATUS' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		DECLARE @V_STATUS_NAME NVARCHAR(40)
		SELECT @V_STATUS_NAME = TYPE_CONTENT FROM TDICTPARAM  WHERE TYPE_VALUE = @V_NEW_FIELD_INFO
		UPDATE TCustomers SET STATUS = @V_NEW_FIELD_INFO,STATUS_NAME=@V_STATUS_NAME WHERE CUST_ID = @IN_CUST_ID
	END
	SELECT TOP 1 @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='GOV_PROV_REGIONAL' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET GOV_PROV_REGIONAL = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	SELECT TOP 1 @V_NEW_FIELD_INFO=NEW_FIELD_INFO FROM TCustomerChanges WHERE CUST_ID = @IN_CUST_ID AND CHECK_FLAG=1 AND FIELD_NAME='GOV_REGIONAL' ORDER BY INPUT_TIME DESC
	IF @@ROWCOUNT>0
	BEGIN
		UPDATE TCustomers SET GOV_REGIONAL = @V_NEW_FIELD_INFO WHERE CUST_ID = @IN_CUST_ID
	END
	----------------------------------------------------------------------------------------------------------
    UPDATE TCustomerChanges SET CHECK_FLAG = @IN_CHECK_FLAG, CHECK_MAN = @IN_INPUT_MAN WHERE CUST_ID = @IN_CUST_ID
    
    SET @SSUMMARY = N'客户信息修改审核，操作员：' + CAST(@IN_INPUT_MAN AS NVARCHAR)+'；审核客户ID：'+CAST(@IN_CUST_ID AS NVARCHAR)
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    
    COMMIT TRANSACTION
    END TRY

    --3.异常处理
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION
        DECLARE @V_ERROR_STR NVARCHAR(1000),@V_ERROR_NUMBER INT,@V_ERROR_SEVERITY INT,@V_ERROR_STATE INT,
                @V_ERROR_PROCEDURE sysname,@V_ERROR_LINE INT,@V_ERROR_MESSAGE NVARCHAR(4000)
        SELECT @V_ERROR_STR = N'Message:%s<BR><font color = "white">Error:%d,Level:%d,State:%d,Procedure:%s,Line:%d</font>',
               @V_ERROR_NUMBER = ERROR_NUMBER(),
               @V_ERROR_SEVERITY = ERROR_SEVERITY(),
               @V_ERROR_STATE = ERROR_STATE(),
               @V_ERROR_PROCEDURE = ERROR_PROCEDURE(),
               @V_ERROR_LINE = ERROR_LINE(),
               @V_ERROR_MESSAGE = ERROR_MESSAGE()
        RAISERROR(@V_ERROR_STR,@V_ERROR_SEVERITY,1,@V_ERROR_MESSAGE,@V_ERROR_NUMBER,@V_ERROR_SEVERITY,@V_ERROR_STATE,
                  @V_ERROR_PROCEDURE,@V_ERROR_LINE)
        RETURN -100
    END CATCH
    RETURN 100
GO
