USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TDEPLOY_CRMBY_CUST_ID @IN_CUST_ID    INT,
                                             @IN_PRODUCT_ID INT,
                                             @IN_INPUT_MAN  INT
WITH ENCRYPTION
AS
--20409: The Products can be accessed. START
    DECLARE @V_SW20409 INT
    SELECT @V_SW20409 = VALUE FROM INTRUST..TSYSCONTROL WHERE FLAG_TYPE = 'SW20409'
    DECLARE @V_PRODUCTS TABLE(PRODUCT_ID INT)
    IF @V_SW20409 = 1
        INSERT INTO @V_PRODUCTS
            SELECT PRODUCT_ID FROM INTRUST..TPRODUCT
                WHERE (INTRUST_FLAG1 IN ( SELECT FUNC_ID-2040900 FROM INTRUST..TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID > 2040900 AND FUNC_ID <= 2040902 AND OP_CODE = @IN_INPUT_MAN )
                    OR DEPART_ID IN (SELECT B.DEPART_ID FROM INTRUST..TOPRIGHT A,TOPERATOR B WHERE A.OP_CODE = B.OP_CODE AND A.MENU_ID = '20409' AND A.FUNC_ID = 2040903 AND A.OP_CODE = @IN_INPUT_MAN)
                    OR PRODUCT_ID IN ( SELECT FUNC_ID FROM INTRUST..TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID < 2040900 AND OP_CODE = @IN_INPUT_MAN)
                    OR ADMIN_MANAGER = @IN_INPUT_MAN OR INPUT_MAN = @IN_INPUT_MAN 
                    OR SUB_MAN = @IN_INPUT_MAN OR SUB_MAN2 = @IN_INPUT_MAN
                    OR CASH_MAN = @IN_INPUT_MAN OR CASH_MAN2 = @IN_INPUT_MAN
					OR ADMIN_MANAGER IN(SELECT OP_CODE FROM INTRUST..TOPCUSTRIGHT WHERE ENABLE_OP_CODE = @IN_INPUT_MAN) OR ISNULL(@IN_INPUT_MAN,0)=0 )
--20409: The Products can be accessed. END
    DECLARE @V_CONTRACT_BH VARCHAR(16),@V_PRODUCT_NAME VARCHAR(60)
    DECLARE @V_PRODUCT_ID INT,@V_LIST_ID INT
    DECLARE @V_BOND1 DECIMAL(16,3), @V_GAIN1 DECIMAL(16,3), @V_BOND2 DECIMAL(16,3), @V_GAIN2 DECIMAL(16,3),
            @V_TO_MONEY2 DECIMAL(16,3), @V_TOTAL_MONEY DECIMAL(16,3), @V_BOND_TAX DECIMAL(16,3)

    CREATE TABLE #TMP_TABLE(
            CUST_ID           INT,
            PRODUCT_ID        INT,
            PRODUCT_NAME      VARCHAR(60),
            LIST_ID           INT,
            CONTRACT_BH       VARCHAR(16),
            BOND1             DECIMAL(16,3),
            GAIN1             DECIMAL(16,3),
            GAIN2             DECIMAL(16,3),
            BOND2             DECIMAL(16,3),
            TO_MONEY2         DECIMAL(16,3),
            BOND_TAX          DECIMAL(16,3),
            TOTAL_MONEY       DECIMAL(16,3),
            AFT_PRE_GAIN      DECIMAL(16,3)
     )
    DECLARE C1 CURSOR FOR
        SELECT A.PRODUCT_ID,A.CONTRACT_BH,A.LIST_ID
        FROM INTRUST..TBENIFITOR A,INTRUST..TCUSTOMERINFO B
        WHERE A.CUST_ID = B.CUST_ID AND A.CUST_ID = @IN_CUST_ID
              AND (A.PRODUCT_ID = @IN_PRODUCT_ID OR ISNULL(@IN_PRODUCT_ID,0) = 0)
              AND(@V_SW20409 = 0 OR @V_SW20409 IS NULL OR A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCTS))

    OPEN C1
    FETCH C1 INTO @V_PRODUCT_ID,@V_CONTRACT_BH,@V_LIST_ID
    WHILE @@FETCH_STATUS = 0
    BEGIN
        SELECT @V_PRODUCT_NAME = PRODUCT_NAME FROM INTRUST..TPRODUCT WHERE PRODUCT_ID = @V_PRODUCT_ID
        SELECT @V_BOND1 = ISNULL(SUM(ISNULL(SY_MONEY,0)),0) FROM INTRUST..TDEPLOY
        WHERE PRODUCT_ID = @V_PRODUCT_ID AND LIST_ID = @V_LIST_ID AND CONTRACT_BH = @V_CONTRACT_BH
                  AND CUST_ID = @IN_CUST_ID AND SY_TYPE = '111601' --发行期利息
        SELECT @V_GAIN1 = ISNULL(SUM(ISNULL(SY_MONEY,0)),0) FROM INTRUST..TDEPLOY
        WHERE PRODUCT_ID = @V_PRODUCT_ID AND LIST_ID = @V_LIST_ID AND CONTRACT_BH = @V_CONTRACT_BH
                  AND CUST_ID = @IN_CUST_ID AND SY_TYPE = '111602' --中间收益
        SELECT @V_GAIN2 = ISNULL(SUM(ISNULL(SY_MONEY,0)),0) FROM INTRUST..TDEPLOY
        WHERE PRODUCT_ID = @V_PRODUCT_ID AND LIST_ID = @V_LIST_ID AND CONTRACT_BH = @V_CONTRACT_BH
                  AND CUST_ID = @IN_CUST_ID AND SY_TYPE = '111603' --到期收益
        SELECT @V_BOND2 = ISNULL(SUM(ISNULL(SY_MONEY,0)),0) FROM INTRUST..TDEPLOY
        WHERE PRODUCT_ID = @V_PRODUCT_ID AND LIST_ID = @V_LIST_ID AND CONTRACT_BH = @V_CONTRACT_BH
                  AND CUST_ID = @IN_CUST_ID AND SY_TYPE = '111604' --兑付期利息
        SELECT @V_TO_MONEY2 = ISNULL(SUM(ISNULL(SY_MONEY,0)),0) FROM INTRUST..TDEPLOY
        WHERE PRODUCT_ID = @V_PRODUCT_ID AND LIST_ID = @V_LIST_ID AND CONTRACT_BH = @V_CONTRACT_BH
                  AND CUST_ID = @IN_CUST_ID AND SY_TYPE = '111605' --到期本金
        SELECT @V_BOND_TAX = ISNULL(SUM(ISNULL(BOND_TAX,0)),0) FROM INTRUST..TDEPLOY
            WHERE PRODUCT_ID = @V_PRODUCT_ID AND LIST_ID = @V_LIST_ID AND CONTRACT_BH = @V_CONTRACT_BH
            AND CUST_ID = @IN_CUST_ID AND (SY_TYPE IN ('111601','111604'))
        SELECT @V_TOTAL_MONEY = ISNULL(@V_BOND1,0) + ISNULL(@V_GAIN1,0) + ISNULL(@V_BOND2,0) + ISNULL(@V_GAIN2,0) + ISNULL(@V_TO_MONEY2,0)
        INSERT INTO #TMP_TABLE VALUES(@IN_CUST_ID,@V_PRODUCT_ID,@V_PRODUCT_NAME,@V_LIST_ID,@V_CONTRACT_BH,
                                      @V_BOND1,@V_GAIN1,@V_GAIN2,@V_BOND2,@V_TO_MONEY2,@V_BOND_TAX,ISNULL(@V_TOTAL_MONEY,0),0)
        
        IF @@ERROR <> 0
        BEGIN
            CLOSE CURSOR1
            DEALLOCATE CURSOR1
            RETURN -100
        END
        FETCH C1 INTO @V_PRODUCT_ID,@V_CONTRACT_BH,@V_LIST_ID
    END
    CLOSE C1
    DEALLOCATE C1
    --加入现金聚利类产品的未分配收益
    DECLARE @V_TMP_PRODUCT TABLE(TMP_PRODUCT_ID INT)
    --找出现金聚利类的产品，及期7日年化收益率
    --INSERT INTO @V_TMP_PRODUCT
	--	SELECT PRODUCT_ID FROM INTRUST..TPRODUCTLIMIT WHERE GAIN_FLAG=5
	INSERT INTO #TMP_TABLE(CUST_ID,PRODUCT_ID,PRODUCT_NAME,LIST_ID,CONTRACT_BH,BOND1,GAIN1,GAIN2,BOND2,TO_MONEY2,
            BOND_TAX,TOTAL_MONEY,AFT_PRE_GAIN)
    SELECT @IN_CUST_ID,A.PRODUCT_ID,C.PRODUCT_NAME,A.LIST_ID,A.CONTRACT_BH,0,0,0,0,0
			,0,0,A.AFT_PRE_GAIN FROM INTRUST..TBENGAINDETAIL A LEFT JOIN INTRUST..TCONTRACT B ON A.PRODUCT_ID=B.PRODUCT_ID AND A.CONTRACT_BH=B.CONTRACT_BH AND B.PRODUCT_ID=1683
			LEFT JOIN INTRUST..TPRODUCT C ON A.PRODUCT_ID=C.PRODUCT_ID
		WHERE B.CUST_ID=@IN_CUST_ID ORDER BY A.SERIAL_NO
    SELECT A.*,B.CONTRACT_SUB_BH FROM #TMP_TABLE A LEFT JOIN INTRUST..TCONTRACT B ON A.PRODUCT_ID = B.PRODUCT_ID AND A.CONTRACT_BH = B.CONTRACT_BH AND A.CUST_ID = B.CUST_ID
		WHERE A.TOTAL_MONEY <> 0 OR A.AFT_PRE_GAIN>0
        ORDER BY A.PRODUCT_ID,A.CONTRACT_BH,A.LIST_ID
        
    RETURN @@ROWCOUNT
GO
