USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_STAT_TPRODUCT_GUOLIAN
							@IN_PRODUCT_STATUS      NVARCHAR(20),           --产品状态(1102)
							@IN_INPUT_MAN           INTEGER                 --操作员
										
WITH ENCRYPTION
AS
    --建立统计临时表：(产品ID	自然人份数	自然人金额	机构份数	机构金额)
    CREATE TABLE #COUNT_T(PRODUCT_ID INT,GR_COUNT INT,GR_MONEY NUMERIC(18,2),JG_COUNT INT,JG_MONEY NUMERIC(18,2))
    INSERT INTO #COUNT_T(PRODUCT_ID)
		SELECT DISTINCT A.PRODUCT_ID FROM INTRUST..TCONTRACT A LEFT JOIN INTRUST..TPRODUCT B ON A.PRODUCT_ID=B.PRODUCT_ID
		    WHERE (B.PRODUCT_STATUS=@IN_PRODUCT_STATUS OR ISNULL(@IN_PRODUCT_STATUS,'')='' OR @IN_PRODUCT_STATUS='0')
	UPDATE #COUNT_T SET GR_COUNT=(SELECT COUNT(0) FROM INTRUST..TCONTRACT M LEFT JOIN INTRUST..TCUSTOMERINFO N ON M.CUST_ID=N.CUST_ID WHERE CUST_TYPE=1 AND M.PRODUCT_ID=#COUNT_T.PRODUCT_ID)
	UPDATE #COUNT_T SET GR_MONEY=(SELECT SUM(RG_MONEY) FROM INTRUST..TCONTRACT M LEFT JOIN INTRUST..TCUSTOMERINFO N ON M.CUST_ID=N.CUST_ID WHERE CUST_TYPE=1 AND M.PRODUCT_ID=#COUNT_T.PRODUCT_ID)
	UPDATE #COUNT_T SET JG_COUNT=(SELECT COUNT(0) FROM INTRUST..TCONTRACT M LEFT JOIN INTRUST..TCUSTOMERINFO N ON M.CUST_ID=N.CUST_ID WHERE CUST_TYPE=2 AND M.PRODUCT_ID=#COUNT_T.PRODUCT_ID)
	UPDATE #COUNT_T SET JG_MONEY=(SELECT SUM(RG_MONEY) FROM INTRUST..TCONTRACT M LEFT JOIN INTRUST..TCUSTOMERINFO N ON M.CUST_ID=N.CUST_ID WHERE CUST_TYPE=2 AND M.PRODUCT_ID=#COUNT_T.PRODUCT_ID)
	
    --产品名称	币种	自然人份数	自然人金额	机构份数	机构金额	实际规模份数	实际规模金额	产品状态	信托财产类型
	SELECT A.PRODUCT_NAME,B.CURRENCY_NAME,C.GR_COUNT,C.GR_MONEY,C.JG_COUNT,C.JG_MONEY,C.GR_COUNT+C.JG_COUNT T_COUNT,ISNULL(C.GR_MONEY,0)+ISNULL(C.JG_MONEY,0) T_MONEY,
		PRODUCT_STATUS_NAME,INTRUST_TYPE1_NAME
		FROM INTRUST..TPRODUCT A LEFT JOIN INTRUST..TCURRENCY B ON A.CURRENCY_ID=B.CURRENCY_ID
			LEFT JOIN #COUNT_T C ON C.PRODUCT_ID=A.PRODUCT_ID
		WHERE (A.PRODUCT_STATUS=@IN_PRODUCT_STATUS OR ISNULL(@IN_PRODUCT_STATUS,'')='' OR @IN_PRODUCT_STATUS='0')
		ORDER BY A.PRODUCT_ID
	--SELECT * FROM #COUNT_T

GO
