USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_IM_CUST_INTEGRAL  @IN_CUST_ID    INT,
                                            @IN_CUST_NAME  NVARCHAR(60)
WITH ENCRYPTION
AS
    SELECT A.*,B.*,C.CUST_LEVEL_NAME
        FROM TCustomers A,IM_CUST_INTEGRAL_CARD B,IM_CUST_LEVEL C
        WHERE A.CUST_ID = B.CUST_ID
            AND (A.CUST_ID = @IN_CUST_ID OR ISNULL(@IN_CUST_ID,0) = 0)
            AND (A.CUST_NAME LIKE '%' + @IN_CUST_NAME + '%' OR ISNULL(@IN_CUST_NAME,'') = '')
            AND C.CUST_LEVEL_ID = B.CUST_LEVEL_ID
            AND A.STATUS<>'112805'
GO
