USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TEAMMEMBERS
					    @IN_TEAM_ID           INT     --团队ID

WITH ENCRYPTION
AS
    	SELECT MANAGERID FROM TManagerTeamMembers where TEAM_ID=@IN_TEAM_ID
		UNION ALL --子团队成员列表
		SELECT DISTINCT MANAGERID FROM TManagerTeamMembers where TEAM_ID IN(SELECT TEAM_ID FROM dbo.GetTEAM_ID(@IN_TEAM_ID))
			AND MANAGERID NOT IN (SELECT MANAGERID FROM TManagerTeamMembers where TEAM_ID=@IN_TEAM_ID)
    
GO
