USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TPERSONALQUOTA @IN_TEAM_ID    INT,    --团队ID(直接上级团队)
                                     @IN_PRODUCT_ID     INT,    --产品ID
                                     @IN_SUB_PRODUCT_ID INT,    --子产品ID
                                     @IN_PREPRODUCT_ID  INT ,   --预发行产品ID
                                     @IN_INPUT_MAN      INT     --操作员
                                     
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    SET @IN_PRODUCT_ID = ISNULL(@IN_PRODUCT_ID,0)
    DECLARE  @V_TEAM_ID INT
    
    DECLARE @V_IS_FLAG INT
    DECLARE @V_PRE_DZ_MONE TABLE(TEAM_ID INT,PRE_SALEMONEY DECIMAL(16,3),DZ_MONE DECIMAL(16,3),NUM3000000 INT)
    DECLARE @V_TEAM_OP TABLE(TEAM_ID INT,TEAM_NAME NVARCHAR(60),OP_CODE INT, OP_NAME NVARCHAR(20),QUOTAMONEY DECIMAL(16,3),QUOTA_QUALIFIED_NUM INT)
    DECLARE @V_TEAM_MONEY TABLE(TEAM_ID INT,Q_MONEY DECIMAL(16,3),Q_NUM INT)
    SELECT @V_IS_FLAG = 0
    --本团队的成员表
    --如果是管理员或者是团队领导，则可看指定团队的成员配额
    IF EXISTS (SELECT 0 FROM TOPERATOR WHERE OP_CODE=@IN_INPUT_MAN AND ROLE_ID=1) OR EXISTS (SELECT * FROM TManagerTeams WHERE TEAM_ID=@IN_TEAM_ID AND LEADER=@IN_INPUT_MAN)
		SET @V_TEAM_ID=@IN_TEAM_ID
	ELSE
		SELECT @V_TEAM_ID=TEAM_ID FROM TManagerTeamMembers WHERE MANAGERID= @IN_INPUT_MAN
    
    IF @IN_PRODUCT_ID <> 0  --针对产品的查询
    BEGIN --可以看到自己属团队的所有成员配额情况
		--本团队成员的配额
		INSERT INTO @V_TEAM_OP(TEAM_ID,TEAM_NAME,OP_CODE,OP_NAME,QUOTAMONEY,QUOTA_QUALIFIED_NUM)
		SELECT A.TEAM_ID,A.TEAM_NAME,A.MANAGERID,A.MANAGERNAME,ISNULL(D.QUOTAMONEY,0),ISNULL(D.QUOTA_QUALIFIED_NUM,0) FROM TManagerTeamMembers A --LEFT JOIN TOPERATOR B ON A.MANAGERID=B.OP_CODE 
			LEFT JOIN TManagerTeams C ON C.TEAM_ID = A.TEAM_ID 
			LEFT JOIN TPERSONALQUOTA D ON A.MANAGERID=D.OP_CODE AND D.PRODUCT_ID=@IN_PRODUCT_ID AND D.SUB_PRODUCT_ID=@IN_SUB_PRODUCT_ID
			WHERE (A.TEAM_ID=@V_TEAM_ID OR ISNULL(@V_TEAM_ID,0)=0) AND C.LEADER = @IN_INPUT_MAN 
		INSERT INTO @V_TEAM_MONEY(TEAM_ID,Q_MONEY,Q_NUM)--所属团队的配额剩余额
		SELECT A.TEAM_ID,A.QUOTAMONEY-B.QUOTAMONEY2,A.QUOTA_QUALIFIED_NUM-B.QUOTA_QUALIFIED_NUM2 FROM 
			(SELECT TEAM_ID,SUM(QUOTAMONEY) QUOTAMONEY,SUM(QUOTA_QUALIFIED_NUM) QUOTA_QUALIFIED_NUM FROM TTEAMQUOTA
		    WHERE PRODUCT_ID=@IN_PRODUCT_ID
		    GROUP BY TEAM_ID) A LEFT JOIN (
		    SELECT TEAM_ID,SUM(QUOTAMONEY) QUOTAMONEY2,SUM(QUOTA_QUALIFIED_NUM) QUOTA_QUALIFIED_NUM2 FROM @V_TEAM_OP
		    GROUP BY TEAM_ID) B ON A.TEAM_ID=B.TEAM_ID
		SELECT A.OP_CODE OP_CODE2,A.OP_NAME,A.TEAM_NAME,A.TEAM_ID,B.*,D.Q_MONEY TEAMMONEY,D.Q_NUM TEAMQNUM--,D.Q_MONEY-ISNULL(C.QUOTAMONEY,0) TEAMMONEY,D.Q_NUM-ISNULL(C.QUOTA_QUALIFIED_NUM,0) TEAMQNUM
		    FROM @V_TEAM_OP A LEFT JOIN TPERSONALQUOTA B ON A.OP_CODE=B.OP_CODE AND B.PRODUCT_ID=@IN_PRODUCT_ID AND B.SUB_PRODUCT_ID=@IN_SUB_PRODUCT_ID
		    LEFT JOIN @V_TEAM_MONEY D ON D.TEAM_ID=A.TEAM_ID
		    
        RETURN
    END
    ELSE IF @IN_PREPRODUCT_ID <> 0  --针对预发行产品的查询
    BEGIN
		--本团队成员的配额
		INSERT INTO @V_TEAM_OP(TEAM_ID,TEAM_NAME,OP_CODE,OP_NAME,QUOTAMONEY,QUOTA_QUALIFIED_NUM)
		SELECT A.TEAM_ID,A.TEAM_NAME,A.MANAGERID,A.MANAGERNAME,D.QUOTAMONEY,D.QUOTA_QUALIFIED_NUM FROM TManagerTeamMembers A --LEFT JOIN TOPERATOR B ON A.MANAGERID=B.OP_CODE 
			LEFT JOIN TManagerTeams C ON C.TEAM_ID = A.TEAM_ID 
			LEFT JOIN TPERSONALQUOTA D ON A.MANAGERID=D.OP_CODE AND D.PREPRODUCT_ID=@IN_PRODUCT_ID AND D.SUB_PRODUCT_ID=@IN_SUB_PRODUCT_ID
			WHERE (A.TEAM_ID=@V_TEAM_ID OR ISNULL(@V_TEAM_ID,0)=0) AND C.LEADER = @IN_INPUT_MAN 
		INSERT INTO @V_TEAM_MONEY(TEAM_ID,Q_MONEY,Q_NUM)--所属团队的配额剩余额
		SELECT A.TEAM_ID,A.QUOTAMONEY-B.QUOTAMONEY2,A.QUOTA_QUALIFIED_NUM-B.QUOTA_QUALIFIED_NUM2 FROM 
			(SELECT TEAM_ID,SUM(QUOTAMONEY) QUOTAMONEY,SUM(QUOTA_QUALIFIED_NUM) QUOTA_QUALIFIED_NUM FROM TTEAMQUOTA
		    WHERE PREPRODUCT_ID=@IN_PREPRODUCT_ID
		    GROUP BY TEAM_ID) A LEFT JOIN (
		    SELECT TEAM_ID,SUM(QUOTAMONEY) QUOTAMONEY2,SUM(QUOTA_QUALIFIED_NUM) QUOTA_QUALIFIED_NUM2 FROM @V_TEAM_OP
		    GROUP BY TEAM_ID) B ON A.TEAM_ID=B.TEAM_ID
		--SELECT A.*,B.OP_NAME FROM TPERSONALQUOTA A LEFT JOIN @V_TEAM_OP B ON A.OP_CODE=B.OP_CODE
		SELECT A.OP_CODE OP_CODE2,A.OP_NAME ,B.*,D.Q_MONEY TEAMMONEY,D.Q_NUM TEAMQNUM
		    FROM @V_TEAM_OP A LEFT JOIN TPERSONALQUOTA B ON A.OP_CODE=B.OP_CODE
			LEFT JOIN @V_TEAM_MONEY D ON D.TEAM_ID=A.TEAM_ID
			--WHERE B.PREPRODUCT_ID=@IN_PREPRODUCT_ID AND B.SUB_PRODUCT_ID=@IN_SUB_PRODUCT_ID
        RETURN
    END
    ELSE
        SELECT A.*,B.OP_NAME FROM TPERSONALQUOTA A LEFT JOIN @V_TEAM_OP B ON A.OP_CODE=B.OP_CODE WHERE 1=0
GO
