USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE SP2_QUERY_TTEAMQUOTA_BYSERVICEMAN
                     @IN_PREPRODUCT_ID  INT,    --预发行产品ID
                     @IN_SERVICE_MAN    INT,    --传入客户经理时仅返回其所在团队数据
                     @IN_INPUT_MAN      INT     --操作员
                     
WITH ENCRYPTION
AS
    DECLARE @V_TEAM_ID INT
    DECLARE @V_IS_FLAG INT
    
    SET @IN_PREPRODUCT_ID = ISNULL(@IN_PREPRODUCT_ID,0)
    SET @IN_SERVICE_MAN = ISNULL(@IN_SERVICE_MAN,0)

	IF @IN_SERVICE_MAN = 0
	  SET @IN_SERVICE_MAN = @IN_INPUT_MAN
    --团队领导
    SELECT @V_TEAM_ID = A.TEAM_ID FROM TManagerTeams A WHERE A.LEADER = @IN_INPUT_MAN
    IF @@ROWCOUNT=0
    BEGIN
			SELECT @V_TEAM_ID=TEAM_ID FROM TManagerTeamMembers WHERE MANAGERID = @IN_SERVICE_MAN
			IF @@ROWCOUNT=0
			BEGIN
				SELECT B.*, A.TEAM_NAME FROM TTEAMQUOTA B LEFT JOIN TManagerTeams A ON B.TEAM_ID = A.TEAM_ID WHERE 1=0
				RETURN
			END
		END
    SELECT B.TEAM_ID, A.TEAM_NAME,B.QUOTAMONEY,B.QUOTA_QUALIFIED_NUM,B.PRE_SALEMONEY,B.PRE_QUALIFIEDNUM
        FROM TTEAMQUOTA B LEFT JOIN TManagerTeams A ON B.TEAM_ID = A.TEAM_ID
        WHERE B.TEAM_ID=@V_TEAM_ID
            AND (B.PREPRODUCT_ID = @IN_PREPRODUCT_ID)
    
GO
