USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE SP_MODI_TQUOTIENTCHANGE @IN_SERIAL_NO       INT,          --序号
                                        @IN_QUOTIENT_AMOUNT  DEC(16,3),    --份额
                                        @IN_CHANGE_DATE      INT,          --日期
                                        @IN_INPUT_MAN        INT           --操作员
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200),@TABLE_ID NVARCHAR(60)
    DECLARE @V_SUBSCRIBE_ID INT,@V_SUBSCRIBE_MONEY DEC(16,3)
    SELECT @SBUSI_NAME = N'修改非信托产品份额信息'
    SELECT @SSUMMARY = N'修改非信托产品份额信息'
    SELECT @IBUSI_FLAG = 39011
    SELECT @V_RET_CODE = -39011000
    SELECT @V_SUBSCRIBE_MONEY = SUBSCRIBE_MONEY FROM TSUBSCRIBE A,TQUOTIENTCHANGE B
        WHERE A.SUBSCRIBE_ID = B.SUBSCRIBE_ID AND B.SERIAL_NO = @IN_SERIAL_NO
    IF NOT EXISTS(SELECT * FROM TQUOTIENTCHANGE WHERE SERIAL_NO = @IN_SERIAL_NO)
        RETURN @V_RET_CODE - 11   --非信托产品份额信息不存在
    IF @IN_QUOTIENT_AMOUNT > @V_SUBSCRIBE_MONEY
        RETURN @V_RET_CODE - 22   --受益金额不能大于认购金额

    BEGIN TRANSACTION

    SELECT @V_SUBSCRIBE_ID = SUBSCRIBE_ID FROM TQUOTIENTCHANGE WHERE SERIAL_NO = @IN_SERIAL_NO

    UPDATE TQUOTIENTCHANGE
        SET CHANGE_AMOUNT = @IN_QUOTIENT_AMOUNT,
            CHANGE_MONEY = @IN_QUOTIENT_AMOUNT,
            CHANGE_DATE = @IN_CHANGE_DATE,
            INPUT_MAN = @IN_INPUT_MAN,
            INPUT_TIME = GETDATE()
        WHERE SERIAL_NO= @IN_SERIAL_NO

    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SELECT @SSUMMARY = N'修改非信托产品份额，合同编号：'+RTRIM(CONVERT(NVARCHAR(16),@V_SUBSCRIBE_ID))
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
