USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_MODI_LOGIN_USER @IN_LOGIN_USER     NVARCHAR(20),
                                    @IN_NEW_LOGIN_USER NVARCHAR(20)
WITH ENCRYPTION
AS
    DECLARE @IN_OP_CODE INT,@V_LOGIN_USER NVARCHAR(20),@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    SELECT @SBUSI_NAME = N'修改操作员登录号'
    SELECT @SSUMMARY = N'修改操作员登录号'
    SELECT @IBUSI_FLAG = 10605

    IF NOT EXISTS(SELECT * FROM TOPERATOR WHERE LOGIN_USER = @IN_LOGIN_USER)
    BEGIN
        return -1
    END
    SELECT @IN_OP_CODE = MAX(OP_CODE) FROM TOPERATOR WHERE LOGIN_USER = @IN_LOGIN_USER

    BEGIN TRANSACTION

    UPDATE TOPERATOR
        SET LOGIN_USER = @IN_NEW_LOGIN_USER WHERE LOGIN_USER = @IN_LOGIN_USER
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    SELECT @SSUMMARY = N'修改操作员登录号，从：'+ @IN_LOGIN_USER + N',到:' + @IN_NEW_LOGIN_USER
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_OP_CODE,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    return 100
GO
