USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE SP_QUERY_TPRINTCATALOG @IN_CATALOG_ID      INTEGER,
                                        @IN_CATALOG_CODE    NVARCHAR(24),
                                        @IN_CATALOG_NAME    NVARCHAR(60)
WITH ENCRYPTION
AS
    SELECT *
        FROM TPRINTCATALOG
        WHERE (CATALOG_ID = @IN_CATALOG_ID OR ISNULL(@IN_CATALOG_ID,0) = 0) AND
              (CATALOG_CODE LIKE '%' + @IN_CATALOG_CODE + '%' OR ISNULL(@IN_CATALOG_CODE,'') = '') AND
              (CATALOG_NAME LIKE '%' + @IN_CATALOG_NAME + '%' OR ISNULL(@IN_CATALOG_NAME,'') = '')
GO
