USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TPRODUCT_VALID    @IN_BOOK_CODE               INT,
                                            @IN_PRODUCT_CODE            VARCHAR(6),
                                            @IN_ITEM_ID                 INT,
                                            @IN_PRODUCT_STATUS          VARCHAR(10),
                                            @IN_INTRUST_TYPE            VARCHAR(10),
                                            @IN_CURRENCY_ID             VARCHAR(2),
                                            @IN_INPUT_MAN               INT ,
                                            @IN_PRODUCT_NAME            VARCHAR(60)         = NULL,
                                            @IN_IS_LOCAL                INT                 = NULL,
                                            @IN_DEPART_ID               INT                 = 0,        --设计部门   add by luohh 20090617
                                            @IN_OPEN_FLAG               INT                 = 0,        --开放式/封闭式标志：1开放式2封闭式  0 全部  add by luohh 20091026
                                            @IN_INTRUST_FLAG1           INT                 = 0,
                                            @IN_SUB_CHECK_FLAG          INTEGER             = 0,        --财务开立审核标志
                                            @IN_ELEM_STATUS             INTEGER             = 0,        --要素状态 1未审核 2审核通过 3审核不通过
											@IN_INVEST_FIELD			VARCHAR(20)			= NULL		--CRM投资领域
WITH ENCRYPTION
AS
    SET NOCOUNT ON
--20409: The Products can be accessed. START MODE2
    DECLARE @V_SW20409 INT
    SELECT @V_SW20409 = VALUE FROM INTRUST..TSYSCONTROL WHERE FLAG_TYPE = 'SW20409'
    DECLARE @V_PRODUCTS TABLE(PRODUCT_ID INT)
    IF @V_SW20409 = 1
        INSERT INTO @V_PRODUCTS
            SELECT PRODUCT_ID FROM INTRUST..TPRODUCT WHERE BOOK_CODE = @IN_BOOK_CODE
                AND(INTRUST_FLAG1 IN ( SELECT -(FUNC_ID-2040900)%2+2 FROM INTRUST..TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID >= 2040900 AND FUNC_ID <= 2040902 AND OP_CODE = @IN_INPUT_MAN )
                    OR DEPART_ID IN (SELECT B.DEPART_ID FROM INTRUST..TOPRIGHT A,TOPERATOR B WHERE A.OP_CODE = B.OP_CODE AND A.MENU_ID = '20409' AND A.FUNC_ID = 2040903 AND A.OP_CODE = @IN_INPUT_MAN)
                    OR PRODUCT_ID IN ( SELECT FUNC_ID FROM INTRUST..TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID < 2040900 AND OP_CODE = @IN_INPUT_MAN)
                    OR ADMIN_MANAGER = @IN_INPUT_MAN OR INPUT_MAN = @IN_INPUT_MAN OR ISNULL(@IN_INPUT_MAN,0)=0
                    OR SUB_MAN = @IN_INPUT_MAN OR SUB_MAN2 = @IN_INPUT_MAN
                    OR CASH_MAN = @IN_INPUT_MAN OR CASH_MAN2 = @IN_INPUT_MAN
                    OR ADMIN_MANAGER IN(SELECT OP_CODE FROM INTRUST..TOPCUSTRIGHT WHERE ENABLE_OP_CODE = @IN_INPUT_MAN)
                    )
--20409: The Products can be accessed. END
    DECLARE @V_PRODUCT_ID INT, @V_GR_NUM INT, @V_GR_MONEY DECIMAL(16,3),@V_FACT_NUM INT,@V_FACT_MONEY DECIMAL(16,3)
    SELECT [BOOK_CODE]
		  ,[PRODUCT_ID]
		  ,[PRODUCT_CODE]
		  ,[PRODUCT_NAME]
		  ,[PRODUCT_JC]
		  ,[ITEM_CODE]
		  ,[ITEM_ID]
		  ,[CURRENCY_ID]
		  ,[PRE_NUM]
		  ,[PRE_MONEY]
		  ,[MIN_MONEY]
		  ,[PRE_START_DATE]
		  ,[PRE_END_DATE]
		  ,[PRE_MAX_RATE]
		  ,[PRE_MAX_NUM]
		  ,[PRE_MAX_MONEY]
		  ,[START_DATE]
		  ,[END_DATE]
		  ,[FACT_END_DATE]
		  ,[VALID_PERIOD]
		  ,[PERIOD_UNIT]
		  ,[PRE_CODE]
		  ,[PRODUCT_STATUS]
		  ,[PRODUCT_STATUS_NAME]
		  ,[ADMIN_MANAGER]
		  ,[INFO_PERIOD]
		  ,[OPEN_FLAG]
		  ,[OPEN_FLAG_NAME]
		  ,[TG_BANK_ID]
		  ,[TG_BANK_NAME]
		  ,[TG_BANK_SUB_ID]
		  ,[TG_BANK_SUB_NAME]
		  ,[TG_BANK_ACCT]
		  ,[TG_ACCT_NAME]
		  ,[EXTEND_FLAG]
		  ,[INTRUST_FLAG1]
		  ,[INTRUST_FLAG2]
		  ,[INTRUST_TYPE]
		  ,[INTRUST_TYPE_NAME]
		  ,[INTRUST_TYPE1]
		  ,[INTRUST_TYPE1_NAME]
		  ,[INTRUST_TYPE2]
		  ,[INTRUST_TYPE2_NAME]
		  ,[FX_FEE]
		  ,[DEPART_ID]
		  ,[FPFS]
		  ,[FPFS_NAME]
		  ,[MANAGE_FEE]
		  ,[MANAGE_RATE]
		  ,[EXP_RATE1]
		  ,[EXP_RATE2]
		  ,[SUMMARY]
		  ,[FACT_PRE_NUM]
		  ,[FACT_PRE_MONEY]
		  ,[FACT_NUM]
		  ,[FACT_PERSON_NUM]
		  ,[FACT_MONEY]
		  ,[TOTAL_MONEY]
		  ,[TOTAL_AMOUNT]
		  ,[NAV_PRICE]
		  ,[ZJYE]
		  ,[INPUT_MAN]
		  ,[INPUT_TIME]
		  ,[SL_FLAG]
		  ,[ALL_FLAG]
		  ,[SUB_CODE]
		  ,[FLAG3]
		  ,[GAIN_MONEY]
		  ,[LIST_ID]
		  ,[TAX_RATE]
		  ,[LAST_GAIN_DATE]
		  ,[SUB_CODE_102]
		  ,[SUB_CODE_202]
		  ,[SUB_CODE_500_04]
		  ,[SUB_CODE_510_01]
		  ,[SUB_CODE_510_02]
		  ,[BEN_PERIOD]
		  ,[SUB_CHECK_FLAG]
		  ,[CURRENT_MONTH]
		  ,[START_MONTH]
		  ,[LAST_POST_DATE]
		  ,[RGLX_FLAG]
		  ,[IS_LOCAL]
		  ,[PUBLISH_CHECK_FLAG]
		  ,[CHECK_FLAG]
		  ,[CHECK_MAN]
		  ,[ADMIN_MANAGER2]
		  ,[MATAIN_MANAGER]
		  ,[CHANGE_WT_FLAG]
		  ,[INTRUST_FLAG3]
		  ,[INTRUST_FLAG4]
		  ,[ENTITY_TYPE]
		  ,[ENTITY_TYPE_NAME]
		  ,[ORIGINAL_END_DATE]
		  ,[DEAL_TYPE]
		  ,[DEAL_TYPE_NAME]
		  ,[PRODUCT_INFO]
		  ,[QUALITY_LEVEL]
		  ,[QUALITY_LEVEL_NAME]
		  ,[PURCHANSE_FEE_TYPE]
		  ,[BG_BANK_ID]
		  ,[BG_BANK_NAME]
		  ,[BUSINESS_END_FLAG]
		  ,[BUSINESS_END_DATE]
		  ,[SUB_MAN]
		  ,[SUB_FLAG]
		  ,[NAV_FLOAT_NUM]
		  ,[DZ_SUB_FLAG]
		  ,[TRADE_TAX_RATE]
		  ,[MANAGERTYPE]
		  ,[NATRUST_TYPE]
		  ,[NATRUST_TYPE_NAME]
		  ,[NATRUST_TYPE_SUB]
		  ,[NATRUST_TYPE_SUB_NAME]
		  ,[TRUST_CONTRACT_NAME]
		  ,[SHARE_FLAG]
		  ,[SUB_FUND_FLAG]
		  ,[TRUST_FEE_PERIOD]
		  ,[SERVICE_MAN]
		  ,[NAV_UNIT]
		  ,[ELEM_STATUS]
		  ,[SC4001_UNIT]
		  ,[NC_ITEM_CODE]

		  ,[SUB_MAN2]
		  ,[PRODUCTTREE_ID]



		  ,[FPRG_FLAG]
		  ,[FPRG_TIMES]
		  ,[FPRG_START_DATE]
		  ,[FPRG_CL_DATE]
		  ,[APPROVAL_FLAG]
		  ,[MANAGER_MODI_FLAG]
		  ,[SAFEKEEP_FLAG]
		  ,[CASH_MAN]
		  ,[CASH_MAN2]
		  ,[FINANCIAL_CONSULTANT]
		  ,[PRE_BANK_SERIAL_NO]
		  ,[NVSUB_FLAG]
		  ,[NVLHZC_FLAG]
		  ,[PERIOD_DAY]
		  ,[ITEM_ORIGIN]
		  ,[ITEM_ORIGIN_NAME]
		  ,[CASH_SOURCE]
		  ,[CASH_SOURCE_NAME]
		  ,[EXTENSION_DAY]
		  ,[PRODUCT_NEW_CODE]
		  ,[MATAIN_MANAGER2]
		  ,[ACCOUNTING_STAFF1]
		  ,[ACCOUNTING_STAFF2]
		  ,[COMPLIANCE_MAN]
		  ,[RISK_CONTROLLER]
		  ,[S_ADMIN_MANAGER]
		  ,[YUNYING_FLAG]
		  ,[IS_ITEM_FLAG], GR_NUM = 0, GR_MONEY = CONVERT(DEC(16,3),0.00),CONVERT(INT,REPLACE(PRODUCT_CODE,'T','0')) AS PRODUCT_CODE_INT
        INTO #TEMP_QUERY_TPRODUCT
        FROM INTRUST..TPRODUCT WHERE BOOK_CODE  = @IN_BOOK_CODE
            AND(PRODUCT_CODE LIKE '%'+@IN_PRODUCT_CODE+'%' OR ISNULL(@IN_PRODUCT_CODE,'') = '')
            AND(PRODUCT_NAME LIKE '%'+@IN_PRODUCT_NAME+'%' OR ISNULL(@IN_PRODUCT_NAME,'') = '')
            AND(ITEM_ID = @IN_ITEM_ID OR ISNULL(@IN_ITEM_ID,0) = 0)
            AND(PRODUCT_STATUS NOT IN ('110201', '110204'))
            AND(PRODUCT_STATUS = @IN_PRODUCT_STATUS OR ISNULL(@IN_PRODUCT_STATUS,'') = '')
            AND(INTRUST_TYPE = @IN_INTRUST_TYPE OR ISNULL(@IN_INTRUST_TYPE,'') = '')
            AND(CURRENCY_ID = @IN_CURRENCY_ID OR ISNULL(@IN_CURRENCY_ID,'') = '')
            AND(@V_SW20409 = 0 OR @V_SW20409 IS NULL OR PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCTS))
            AND(IS_LOCAL = @IN_IS_LOCAL OR ISNULL(@IN_IS_LOCAL,0) = 0)
            AND (ISNULL(@IN_DEPART_ID,0) =0 OR DEPART_ID =@IN_DEPART_ID)
            AND (ISNULL(@IN_OPEN_FLAG,0) = 0 OR OPEN_FLAG =@IN_OPEN_FLAG)
            AND (ISNULL(@IN_INTRUST_FLAG1,0) = 0 OR INTRUST_FLAG1 =@IN_INTRUST_FLAG1)
            AND (ISNULL(@IN_SUB_CHECK_FLAG,0) = 0 OR SUB_CHECK_FLAG = @IN_SUB_CHECK_FLAG)
            AND (ISNULL(@IN_ELEM_STATUS,0) = 0 OR ELEM_STATUS = @IN_ELEM_STATUS)
            AND APPROVAL_FLAG = 1
        ORDER BY PRODUCT_CODE DESC
    --
    IF NOT EXISTS(SELECT 1 FROM TSYSTEMINFO WHERE USER_ID =9 )     --广东粤财信托有限公司 不删除
    BEGIN
        IF @IN_PRODUCT_STATUS = '110203'   -- 查询正常期产品, 把业务结束的数据删除
            DELETE FROM #TEMP_QUERY_TPRODUCT WHERE PRODUCT_STATUS = '110203' AND BUSINESS_END_FLAG IN(3,4)
    END
    DECLARE CUR_QUERY_TPRODUCT CURSOR FOR SELECT PRODUCT_ID FROM #TEMP_QUERY_TPRODUCT
    OPEN CUR_QUERY_TPRODUCT
    FETCH NEXT FROM CUR_QUERY_TPRODUCT INTO @V_PRODUCT_ID
    WHILE @@FETCH_STATUS = 0
    BEGIN
        SELECT @V_GR_NUM = COUNT(*), @V_GR_MONEY = SUM(RG_MONEY) FROM INTRUST..TCONTRACT
            WHERE CUST_ID IN ( SELECT CUST_ID FROM INTRUST..TCUSTOMERINFO WHERE CUST_TYPE = 1 )
                AND PRODUCT_ID = @V_PRODUCT_ID AND CHECK_FLAG = 2 AND HT_STATUS <> '120104'
       SELECT @V_FACT_NUM = COUNT(*),@V_FACT_MONEY = SUM(RG_MONEY) FROM INTRUST..TCONTRACT
            WHERE PRODUCT_ID = @V_PRODUCT_ID AND CHECK_FLAG = 2 AND HT_STATUS <> '120104'

        UPDATE #TEMP_QUERY_TPRODUCT
            SET GR_NUM = @V_GR_NUM,
                GR_MONEY = ISNULL(@V_GR_MONEY,0.00),
                FACT_NUM = @V_FACT_NUM,
                FACT_MONEY = @V_FACT_MONEY
            WHERE PRODUCT_ID = @V_PRODUCT_ID
        FETCH NEXT FROM CUR_QUERY_TPRODUCT INTO @V_PRODUCT_ID
    END
    CLOSE CUR_QUERY_TPRODUCT
    DEALLOCATE CUR_QUERY_TPRODUCT
    SELECT A.*,A1.OP_NAME AS ADMIN_MANAGER_NAME,A2.OP_NAME AS SUB_MAN_NAME,A3.INVEST_FIELD INVEST_FIELD,A3.INVEST_FIELD_NAME INVEST_FIELD_NAME
    FROM #TEMP_QUERY_TPRODUCT A LEFT JOIN TOPERATOR A1 ON A.ADMIN_MANAGER = A1.OP_CODE
								LEFT JOIN TOPERATOR A2 ON A.SUB_MAN = A2.OP_CODE
								LEFT JOIN TPRODUCT A3 ON A.PRODUCT_ID = A3.PRODUCT_ID
	WHERE A3.INVEST_FIELD = @IN_INVEST_FIELD OR ISNULL(@IN_INVEST_FIELD,'')=''
    ORDER BY PRODUCT_CODE_INT DESC
GO
