USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE SP_MODI_TCUSTSCORE_DETAIL   @IN_CUST_ID     		INT,   --主键
											 @IN_OPERAND_ID       	INT,   --操作数ID
											 @IN_SCORING_DATE		INT,   --评分日期
											 @IN_CUST_SCORING		INT,   --得分
											 @IN_INPUT_MAN        	INT,    --操作员
											 @IN_SUBJECT_ID			INT,	   --科目ID
											 @IN_SOURCE_NUM			DEC(16,3)
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
	DECLARE @V_END_DATE INT,@V_CUST_SCORING INT,@V_SCORE_END_DATE INT,@V_CURRENT_SOURE INT
	DECLARE @V_ALL_SCORE INT --总分值
	DECLARE  @V_INCLUDE_TOP INT,@V_INCLUDE_END INT
    SELECT @SBUSI_NAME = N'修改系统打分取值信息'
    SELECT @SSUMMARY = N'修改系统打分取值信息'
    SELECT @IBUSI_FLAG = 21005
    SELECT @V_RET_CODE = -21005000
    
	
	--查询客户在打分明细表中是否有记录存在
	SELECT @V_END_DATE = END_DATE,@V_CUST_SCORING = CUST_SOURCE FROM TCustScoreDetail 
		WHERE CUST_ID = @IN_CUST_ID AND SUBJECT_ID = @IN_SUBJECT_ID 
		AND OPERAND_ID = @IN_OPERAND_ID AND END_DATE = 21001231	
	
    BEGIN TRANSACTION
	
	IF(ISNULL(@V_END_DATE,0)<>0) --修改客户得分明细上次评分的截止日期
	BEGIN
		UPDATE TCustScoreDetail SET END_DATE = dbo.GETDATE(@IN_SCORING_DATE,-1),INPUT_MAN = @IN_INPUT_MAN
								WHERE CUST_ID = @IN_CUST_ID AND SUBJECT_ID = @IN_SUBJECT_ID 
								AND OPERAND_ID = @IN_OPERAND_ID AND END_DATE = 21001231
	END
	
	--插入客户得分明细数据
	INSERT INTO TCustScoreDetail(CUST_ID,SUBJECT_ID,OPERAND_ID,SCORING_DATE,CUST_SOURCE,REGULATION,END_DATE,INPUT_MAN,CUST_NUM)
		VALUES(@IN_CUST_ID,@IN_SUBJECT_ID,@IN_OPERAND_ID,@IN_SCORING_DATE,@IN_CUST_SCORING,ISNULL(@IN_CUST_SCORING,0)-ISNULL(@V_CUST_SCORING,0),21001231,@IN_INPUT_MAN,@IN_SOURCE_NUM)
		
	IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
	
    SELECT @SSUMMARY = N'修改系统打分取值信息:'
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
