USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_STAT_TCONTRACT_GUOLIAN_TOTAL
										@IN_PRODUCT_CODE        NVARCHAR(40),           --产品ID
										@IN_QS_DATE1            INTEGER       = NULL,   --认购日期（起）
										@IN_QS_DATE2            INTEGER       = NULL,   --认购日期（止）
										@IN_INPUT_MAN           INTEGER                 --操作员
										
WITH ENCRYPTION
AS
    
    SET @IN_QS_DATE1 = ISNULL(@IN_QS_DATE1,0)
    SET @IN_QS_DATE2 = ISNULL(@IN_QS_DATE2,0)
    IF @IN_QS_DATE2 =0 SET @IN_QS_DATE2 = 20991231
    --机构		
	--个人	300万以上	
	--		300万以下	
	SELECT '机构' CUST_TYPE_NAME,'' WAN,COUNT(B.CUST_TYPE) NUM,CAST(SUM(A.RG_MONEY)AS VARCHAR) TOTAL_MONEY 
		FROM INTRUST..TCONTRACT A LEFT JOIN INTRUST..TCUSTOMERINFO B ON A.CUST_ID=B.CUST_ID
		WHERE B.CUST_TYPE = 2 --机构
			--AND (A.CHECK_FLAG = 1)
			AND (A.PRODUCT_CODE = @IN_PRODUCT_CODE OR ISNULL(@IN_PRODUCT_CODE,'') = '')
           -- AND (A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM INTRUST..TPRODUCT WHERE (PRODUCT_STATUS = '110202' OR (PRODUCT_STATUS = '110203' AND  FPRG_FLAG =1)) AND (INTRUST_TYPE1 = '113801'OR INTRUST_TYPE1 = '113804')))
            AND (A.QS_DATE>=ISNULL(@IN_QS_DATE1,0))
			AND (A.QS_DATE<=ISNULL(@IN_QS_DATE2,20991231))
		GROUP BY B.CUST_TYPE
	UNION 
	SELECT '个人' CUST_TYPE_NAME,'300万以上' WAN,COUNT(B.CUST_TYPE) NUM,CAST(SUM(A.RG_MONEY) AS VARCHAR) TOTAL_MONEY
		FROM INTRUST..TCONTRACT A LEFT JOIN INTRUST..TCUSTOMERINFO B ON A.CUST_ID=B.CUST_ID
		WHERE B.CUST_TYPE = 1 --个人
			--AND (A.CHECK_FLAG = 1)
			AND (A.RG_MONEY >= 3000000)
			AND (A.PRODUCT_CODE = @IN_PRODUCT_CODE OR ISNULL(@IN_PRODUCT_CODE,'') = '')
           -- AND (A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM INTRUST..TPRODUCT WHERE (PRODUCT_STATUS = '110202' OR (PRODUCT_STATUS = '110203' AND  FPRG_FLAG =1)) AND (INTRUST_TYPE1 = '113801'OR INTRUST_TYPE1 = '113804')))
            AND (A.QS_DATE>=ISNULL(@IN_QS_DATE1,0))
			AND (A.QS_DATE<=ISNULL(@IN_QS_DATE2,20991231))
		GROUP BY B.CUST_TYPE
	UNION
    SELECT '个人' CUST_TYPE_NAME,'300万以下' WAN,COUNT(B.CUST_TYPE) NUM,CAST(SUM(A.RG_MONEY) AS VARCHAR) TOTAL_MONEY
		FROM INTRUST..TCONTRACT A LEFT JOIN INTRUST..TCUSTOMERINFO B ON A.CUST_ID=B.CUST_ID
		WHERE B.CUST_TYPE = 1 --个人
			--AND (A.CHECK_FLAG = 1)
			AND (A.RG_MONEY < 3000000)
			AND (A.PRODUCT_CODE = @IN_PRODUCT_CODE OR ISNULL(@IN_PRODUCT_CODE,'') = '')
            --AND (A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM INTRUST..TPRODUCT WHERE (PRODUCT_STATUS = '110202' OR (PRODUCT_STATUS = '110203' AND  FPRG_FLAG =1)) AND (INTRUST_TYPE1 = '113801'OR INTRUST_TYPE1 = '113804')))
            AND (A.QS_DATE>=ISNULL(@IN_QS_DATE1,0))
			AND (A.QS_DATE<=ISNULL(@IN_QS_DATE2,20991231))
		GROUP BY B.CUST_TYPE
    

GO
