USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_STAT_TPRECONTRACT2 @IN_PRODUCT_ID INT,
                                       @IN_PREPRODUCT_ID INT
WITH ENCRYPTION
AS
    IF @IN_PRODUCT_ID>0 
/* 分成3个部分：
  信托库预约已签认购合同的部分（缴款数据在intrust..tmoneydetail）；
  信托库预约未签认购合同的部分（缴款数据在efcrm..tpremoneydetail）；
  CRM库预约未绑定(未同步)到信托库的部分(缴款数据在efcrm..tpremoneydetail)
*/
---------------------   信托库预约已签认购合同的部分（缴款数据在intrust..tmoneydetail） ------------------------------------------
        SELECT 1 AS ENTRY_TYPE, '预约记录' AS ENTRY_TYPE_NAME, P.PRE_DATE AS DATE,CUS.CUST_NAME,P.PRE_MONEY*P.PRE_NUM AS MONEY, CUS.CUST_TEL, 
            CASE WHEN EXISTS 
                (SELECT *
                  FROM INTRUST..TCONTRACT CON, INTRUST..TMONEYDETAIL M
                  WHERE P.PRODUCT_ID=CON.PRODUCT_ID AND P.PRE_CODE=CON.PRE_CODE
                    AND CON.PRODUCT_ID=M.PRODUCT_ID AND CON.CONTRACT_BH=M.CONTRACT_BH AND M.CHECK_FLAG=2) THEN
                '是'       
            ELSE
                '否' 
            END AS IS_PAID, 
            (SELECT ISNULL(SUM(M.TO_MONEY),0.0) 
              FROM INTRUST..TCONTRACT CON, INTRUST..TMONEYDETAIL M
              WHERE P.PRODUCT_ID=CON.PRODUCT_ID AND P.PRE_CODE=CON.PRE_CODE
                AND CON.PRODUCT_ID=M.PRODUCT_ID AND CON.CONTRACT_BH=M.CONTRACT_BH AND M.CHECK_FLAG=2) AS PAY_MONEY
        FROM INTRUST..TPRECONTRACT P JOIN INTRUST..TCUSTOMERINFO CUS ON CUS.CUST_ID=P.CUST_ID
        WHERE P.PRODUCT_ID=@IN_PRODUCT_ID AND P.PRE_STATUS<>'111304'--不是已作废(做删除操作后)的预约记录
            AND EXISTS (SELECT * FROM INTRUST..TCONTRACT WHERE PRODUCT_ID=P.PRODUCT_ID AND PRE_CODE=P.PRE_CODE AND CHECK_FLAG=2) 
            
       UNION ALL
       
        SELECT 2 AS ENTRY_TYPE, '缴款记录' AS ENTRY_TYPE_NAME, M.DZ_DATE,M.CUST_NAME,M.TO_MONEY AS MONEY,CUS.CUST_TEL, 
            NULL AS IS_PAID, NULL AS PAY_MONEY
        FROM INTRUST..TPRECONTRACT P,INTRUST..TCONTRACT CON, INTRUST..TMONEYDETAIL M, INTRUST..TCUSTOMERINFO CUS
        WHERE P.PRODUCT_ID=CON.PRODUCT_ID AND P.PRE_CODE=CON.PRE_CODE 
            AND CON.PRODUCT_ID=M.PRODUCT_ID AND CON.CONTRACT_BH=M.CONTRACT_BH AND M.CHECK_FLAG=2
            AND CON.CUST_ID=CUS.CUST_ID
            AND P.PRODUCT_ID=@IN_PRODUCT_ID AND P.PRE_STATUS<>'111304'--不是已作废(做删除操作后)的预约记录  
---------------------   信托库预约已签认购合同的部分（缴款数据在intrust..tmoneydetail）------------------------------------------

      UNION ALL
---------------------   信托库预约未签认购合同的部分（缴款数据在efcrm..tpremoneydetail） ---------------------------- 
      SELECT 1 AS ENTRY_TYPE, '预约记录' AS ENTRY_TYPE_NAME, P.PRE_DATE AS DATE,CUS.CUST_NAME,P.PRE_MONEY*P.PRE_NUM AS MONEY, CUS.CUST_TEL, 
            CASE WHEN NOT EXISTS 
                (SELECT * FROM TPRECONTRACT WHERE BIND_SERIAL_NO=P.SERIAL_NO)
               OR NOT EXISTS 
                 (SELECT * FROM TPREMONEYDETAIL WHERE PRE_SERIAL_NO=(SELECT SERIAL_NO FROM TPRECONTRACT WHERE BIND_SERIAL_NO=P.SERIAL_NO)) THEN
                '否'       
            ELSE
                '是' 
            END AS IS_PAID, 
            CASE WHEN NOT EXISTS (SELECT * FROM TPRECONTRACT WHERE BIND_SERIAL_NO=P.SERIAL_NO) THEN
                0.0
            ELSE
                (SELECT ISNULL(SUM(DZ_MONEY),0.0) 
                  FROM TPREMONEYDETAIL 
                  WHERE PRE_SERIAL_NO=(SELECT SERIAL_NO FROM TPRECONTRACT WHERE BIND_SERIAL_NO=P.SERIAL_NO))
            END AS PAY_MONEY
        FROM INTRUST..TPRECONTRACT P JOIN INTRUST..TCUSTOMERINFO CUS ON CUS.CUST_ID=P.CUST_ID
        WHERE P.PRODUCT_ID=@IN_PRODUCT_ID AND P.PRE_STATUS<>'111304'--不是已作废(做删除操作后)的预约记录
            AND NOT EXISTS (SELECT * FROM INTRUST..TCONTRACT WHERE PRODUCT_ID=P.PRODUCT_ID AND PRE_CODE=P.PRE_CODE AND CHECK_FLAG=2) 
            
       UNION ALL
       
        SELECT 2 AS ENTRY_TYPE, '缴款记录' AS ENTRY_TYPE_NAME, DBO.GETDATEINT(M.DZ_DATE) AS DZ_DATE,CUS.CUST_NAME,M.DZ_MONEY AS MONEY,CUS.CUST_TEL, 
            NULL AS IS_PAID, NULL AS PAY_MONEY
        FROM INTRUST..TPRECONTRACT P, TPREMONEYDETAIL M, INTRUST..TCUSTOMERINFO CUS
        WHERE P.PRODUCT_ID=@IN_PRODUCT_ID AND P.PRE_STATUS<>'111304'--不是已作废(做删除操作后)的预约记录  
            AND NOT EXISTS (SELECT * FROM INTRUST..TCONTRACT WHERE PRODUCT_ID=P.PRODUCT_ID AND PRE_CODE=P.PRE_CODE AND CHECK_FLAG=2)
            AND EXISTS (SELECT * FROM TPRECONTRACT WHERE BIND_SERIAL_NO=P.SERIAL_NO) 
            AND M.PRE_SERIAL_NO=(SELECT SERIAL_NO FROM TPRECONTRACT WHERE BIND_SERIAL_NO=P.SERIAL_NO) 
            AND P.CUST_ID=CUS.CUST_ID
---------------------   信托库预约未签认购合同的部分（缴款数据在efcrm..tpremoneydetail） ----------------------------

      UNION ALL
      
---------------------      CRM库预约未绑定(未同步)到信托库的部分(缴款数据在efcrm..tpremoneydetail) --------------------------------------------------------
       SELECT 1 AS ENTRY_TYPE, '预约记录' AS ENTRY_TYPE_NAME, P.PRE_DATE AS DATE,CUS.CUST_NAME,P.PRE_MONEY*P.PRE_NUM AS MONEY, CUS.CUST_TEL, 
            CASE WHEN EXISTS (SELECT * FROM TPREMONEYDETAIL WHERE PRE_SERIAL_NO=P.SERIAL_NO) THEN
                '是'       
            ELSE
                '否' 
            END AS IS_PAID, 
            (SELECT ISNULL(SUM(DZ_MONEY),0.0) FROM TPREMONEYDETAIL WHERE PRE_SERIAL_NO=P.SERIAL_NO) AS PAY_MONEY
        FROM TPRECONTRACT P JOIN INTRUST..TCUSTOMERINFO CUS ON CUS.CUST_ID=P.CUST_ID
        WHERE P.PRODUCT_ID=@IN_PRODUCT_ID AND P.PRE_STATUS<>'111304'--不是已作废(做删除操作后)的预约记录
            AND ISNULL(P.BIND_SERIAL_NO,0)=0 -- 未绑定，也即未转成可认购的预约
            
       UNION ALL
       
        SELECT 2 AS ENTRY_TYPE, '缴款记录' AS ENTRY_TYPE_NAME, DBO.GETDATEINT(M.DZ_DATE) AS DZ_DATE,CUS.CUST_NAME,M.DZ_MONEY AS MONEY,CUS.CUST_TEL, 
            NULL AS IS_PAID, NULL AS PAY_MONEY
        FROM TPREMONEYDETAIL M 
            JOIN TPRECONTRACT P ON P.SERIAL_NO=M.PRE_SERIAL_NO
            JOIN INTRUST..TCUSTOMERINFO CUS ON CUS.CUST_ID=P.CUST_ID
        WHERE P.PRODUCT_ID=@IN_PRODUCT_ID AND P.PRE_STATUS<>'111304'--不是已作废(做删除操作后)的预约记录  
            AND ISNULL(P.BIND_SERIAL_NO,0)=0 -- 未绑定，也即未转成可认购的预约
 ---------------------  CRM库预约未绑定(未同步)到信托库的部分(缴款数据在efcrm..tpremoneydetail) --------------------------------------------------------     
 
        /*UNION ALL
        
        SELECT 2 AS ENTRY_TYPE, '缴款记录' AS ENTRY_TYPE_NAME, M.DZ_DATE,M.CUST_NAME,M.TO_MONEY AS MONEY,CUS.CUST_TEL, 
            NULL AS IS_PAID, NULL AS PAY_MONEY
        FROM INTRUST..TMONEYDETAIL M, INTRUST..TCUSTOMERINFO CUS
        WHERE M.CUST_ID=CUS.CUST_ID
            AND M.CHECK_FLAG=2 AND M.PRODUCT_ID=@@IN_PRODUCT_ID*/ -- 加上 未做预约合同的缴款
       ORDER BY ENTRY_TYPE
       
    ELSE -- 对未绑定到正式信托产品的预发行产品的统计
        SELECT 1 AS ENTRY_TYPE, '预约记录' AS ENTRY_TYPE_NAME, P.PRE_DATE AS DATE,CUS.CUST_NAME,P.PRE_MONEY*P.PRE_NUM AS MONEY, CUS.CUST_TEL, 
            CASE WHEN EXISTS 
                (SELECT *
                  FROM TPRECONTRACT PC 
                    JOIN TPREMONEYDETAIL M ON M.PRE_SERIAL_NO=PC.SERIAL_NO 
                  WHERE PC.SERIAL_NO=P.SERIAL_NO) THEN
                '是'       
            ELSE
                '否' 
            END AS IS_PAID, 
            (SELECT ISNULL(SUM(DZ_MONEY),0.0)
              FROM TPRECONTRACT PC 
                JOIN TPREMONEYDETAIL M ON M.PRE_SERIAL_NO=PC.SERIAL_NO
              WHERE PC.SERIAL_NO=P.SERIAL_NO) AS PAY_MONEY
        FROM TPRECONTRACT P JOIN INTRUST..TCUSTOMERINFO CUS ON CUS.CUST_ID=P.CUST_ID
        WHERE P.PREPRODUCT_ID=@IN_PREPRODUCT_ID AND P.PRE_STATUS<>'111304'--不是已作废(做删除操作后)的预约记录
        
       UNION ALL
       
        SELECT 2 AS ENTRY_TYPE, '缴款记录' AS ENTRY_TYPE_NAME, DBO.GETDATEINT(M.DZ_DATE) AS DZ_DATE,CUS.CUST_NAME,M.DZ_MONEY AS MONEY
            ,CUS.CUST_TEL, NULL AS IS_PAID, NULL AS PAY_MONEY
        FROM TPRECONTRACT P
            JOIN TPREMONEYDETAIL M ON M.PRE_SERIAL_NO=P.SERIAL_NO
            JOIN INTRUST..TCUSTOMERINFO CUS ON CUS.CUST_ID=P.CUST_ID
        WHERE P.PREPRODUCT_ID=@IN_PREPRODUCT_ID AND P.PRE_STATUS<>'111304' --不是已作废(做删除操作后)的预约记录    
        
       ORDER BY ENTRY_TYPE
GO
