USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_MYPORTAL @IN_INPUT_MAN    NVARCHAR(60),
                                   @IN_APP_CODE     NVARCHAR(60) = NULL --EFTRUST/EFCRM/...
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    DECLARE @VT_PORTALINFO TABLE(
        PORTAL_CODE     NVARCHAR(30) NOT NULL,              --Portal编号
        PORTAL_NAME     NVARCHAR(60) NOT NULL,              --Portal名称
        POS_TYPE        INTEGER NOT NULL DEFAULT '1',       --Portal位置1通栏2左侧3右侧
        BODY_URL        NVARCHAR(500),                      --Portal内容URL
        APP_CODE        NVARCHAR(60),                       --URL所属APP
        FIXED_HEIGHT    INTEGER DEFAULT '0',                --固定高度0表示不固定
        SCROLLBAR       INTEGER DEFAULT '2',                --是否支持滚动条显示1是并且只有固定高度时滚动条才有效
        VISIBLE         INTEGER,                            --是否显示默认值1是
        POSSORT         INTEGER,                            --位置顺序默认值从小到大排序
        EXPAND          INTEGER                             --是否展开默认值1是
    )
    --取portal信息
    INSERT INTO @VT_PORTALINFO(PORTAL_CODE,PORTAL_NAME,POS_TYPE,BODY_URL,APP_CODE,FIXED_HEIGHT,SCROLLBAR,VISIBLE,POSSORT,EXPAND)
        SELECT PORTAL_CODE,PORTAL_NAME,POS_TYPE,BODY_URL,APP_CODE,FIXED_HEIGHT,SCROLLBAR,DEFAULT_VISIBLE,DEFAULT_POSSORT,DEFAULT_EXPAND
        FROM TPORTALINFO
    --用角色portal覆盖默认配置
    UPDATE @VT_PORTALINFO
        SET VISIBLE = ISNULL(B.VISIBLE,A.VISIBLE), POSSORT = ISNULL(B.POSSORT,A.POSSORT), EXPAND = ISNULL(B.EXPAND,A.EXPAND)
        FROM @VT_PORTALINFO A,
            (   SELECT B.PORTAL_CODE, MAX(VISIBLE) AS VISIBLE, MAX(POSSORT) AS POSSORT, MIN(EXPAND) AS EXPAND
                FROM TPORTALROLE B, TOPERATOR C, TOPROLE D WHERE B.ROLE_CODE = D.ROLE_ID AND C.OP_CODE = D.OP_CODE AND C.OP_CODE = @IN_INPUT_MAN
                GROUP BY B.PORTAL_CODE
            ) B
        WHERE A.PORTAL_CODE = B.PORTAL_CODE
    --用用户portal覆盖默认配置
    UPDATE @VT_PORTALINFO
        SET VISIBLE = ISNULL(B.VISIBLE,A.VISIBLE), POSSORT = ISNULL(B.POSSORT,A.POSSORT), EXPAND = ISNULL(B.EXPAND,A.EXPAND)
        FROM @VT_PORTALINFO A,
            (   SELECT B.PORTAL_CODE, MAX(VISIBLE) AS VISIBLE, MAX(POSSORT) AS POSSORT, MIN(EXPAND) AS EXPAND
                FROM TPORTALUSER B, TOPERATOR C WHERE B.USER_CODE = C.OP_CODE AND C.OP_CODE = @IN_INPUT_MAN
                GROUP BY B.PORTAL_CODE
            ) B
        WHERE A.PORTAL_CODE = B.PORTAL_CODE

    --输出
    SELECT * FROM @VT_PORTALINFO  ORDER BY POS_TYPE, POSSORT
    RETURN @@ROWCOUNT
GO
