USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_DEL_TCOCONTRACTPOINTS @IN_SUBCOCONTRACT_ID           INT,                 --合同金额明细ID
                                          @IN_INPUT_MAN                  INT,                 --录入人员，对应表TOPERATOR.OP_CODE
                                          @IN_COCONTRACT_ID              INT                  --合同ID
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT,@IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40),@SSUMMARY NVARCHAR(200)
    DECLARE @V_COCONTRACT_SUB_BH NVARCHAR(200),@V_COCONTRACT_ID INT,@V_POINT_SUMMARY NVARCHAR(2000)

    SELECT @SBUSI_NAME = N'合同管理之删除合同金额明细'
    SELECT @SSUMMARY = N'合同管理之删除合同金额明细'
    SELECT @IBUSI_FLAG = 50001
    SELECT @V_RET_CODE = -50001000

    SELECT @V_COCONTRACT_ID =COCONTRACT_ID,@V_POINT_SUMMARY =POINT_SUMMARY FROM TCOCONTRACTPOINTS WHERE SUBCOCONTRACT_ID =@IN_SUBCOCONTRACT_ID
    SELECT @V_COCONTRACT_SUB_BH = COCONTRACT_SUB_BH FROM TCOCONTRACT WHERE COCONTRACT_ID =@V_COCONTRACT_ID
    IF NOT EXISTS(SELECT 1 FROM TCOCONTRACT WHERE COCONTRACT_ID = @IN_COCONTRACT_ID)
        RETURN 100
    IF ISNULL(@IN_SUBCOCONTRACT_ID,0) = 0 AND ISNULL(@IN_COCONTRACT_ID,0) = 0
        RETURN 100

    BEGIN TRANSACTION
    DELETE FROM TCOCONTRACTPOINTS
        WHERE (ISNULL(@IN_SUBCOCONTRACT_ID,0)=0 OR SUBCOCONTRACT_ID = @IN_SUBCOCONTRACT_ID)
            AND (COCONTRACT_ID = @IN_COCONTRACT_ID)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END
    --
    SELECT @SSUMMARY = N'合同管理之删除合同金额明细，合同编号：'+@V_COCONTRACT_SUB_BH+'，合同要点：'+@V_POINT_SUMMARY
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
