USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TCONTRACTSTAT_TOSERVICEMAN @IN_SERVICE_MAN INT	--客户经理编号
                                   
WITH ENCRYPTION
AS
    
    --SELECT * FROM TCONTRACTSTAT WHERE SERVICE_MAN = @IN_SERVICE_MAN
    SELECT PRODUCT_ID,(SELECT PRODUCT_NAME FROM INTRUST..TPRODUCT WHERE PRODUCT_ID=TCONTRACTSTAT.PRODUCT_ID) PRODUCT_NAME,
		COUNT(PRODUCT_ID) CONTRACT_NUMBER
		FROM TCONTRACTSTAT WHERE SERVICE_MAN = @IN_SERVICE_MAN GROUP BY PRODUCT_ID

 
GO
