USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_STAT_CHANNELTOTAL1 @IN_CELL_ID                  INTEGER,                --产品单元ID
                                       @IN_CHANNEL_TYPE             NVARCHAR(10),           --渠道类别
                                       @IN_CHANNEL_NAME             NVARCHAR(200),          --渠道机构名称
                                       @IN_BEGIN_DATE               INTEGER,                --起始日期
                                       @IN_END_DATE                 INTEGER,                --截止日期
                                       @IN_GROUP_TYPE               INTEGER,                --汇总方式 1按周 2按月 3按季 4按年 5全部
                                       @IN_LIST_PRODUCT             INTEGER,                --是否列示产品 1是 2否
                                       @IN_LIST_CHANNEL             INTEGER = 2,            --是否列示渠道 0否 1列示所有渠道(按具体渠道统计) 
                                                                                            --                 2列示第1级渠道(按第1级渠道即省级渠道汇总)
                                       @IN_LIST_SALEMAN             INTEGER = 2,            --是否列示销售人员 1是 2否
                                       @IN_LIST_SERVICEMAN          INTEGER = 2,            --是否列示客户经理 1是 2否
                                       @IN_INTRUST_FLAG1            INTEGER = 2,            --集合单一标志 0全部 1单一 2集合
                                       @IN_CHANNEL_ID               INT = NULL,             --渠道ID
                                       @IN_SALE_MAN                 INT = NULL,             --销售人员ID
                                       @IN_SERVICE_MAN              INT = NULL,             --客户经理ID
                                       @IN_LIST_CUST                INTEGER = 2,            --是否列示客户 1是 2否
                                       @IN_CUST_NAME                NVARCHAR(100) = '',     --客户名称
                                       @IN_PRODUCT_NAME             NVARCHAR(100) = '',     --产品名称
                                       @IN_LIST_CHANNEL_COOPERTYPE  INTEGER = 2,            --是否列示渠道合作方式 1是   2否
                                       @IN_CHANNEL_COOPERTYPE       NVARCHAR(10) = '',      --渠道合作方式（5502）
                                       @IN_RECOMMEND_FLAG           INT=1,                  --推荐状态 1是,2否
                                       @IN_NORMAL_FLAG              INT=1,                  --正常状态 1是,2否
                                       @IN_END_FLAG                 INT=1,                  --结束状态 1是,2否
									   @IN_SUB_PRODUCT_ID			INT=0					--子产品ID
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    IF @IN_END_DATE = 0 SET @IN_END_DATE = NULL
    IF @IN_CUST_NAME IS NULL SET @IN_CUST_NAME = ''
    DECLARE @V_DT_INTRUST INT, @V_DATA_TYPE INT
    DECLARE @V_RECOMMEND_NAME NVARCHAR(10),@V_NORMAL_NAME NVARCHAR(10),@V_END_NAME NVARCHAR(10) --产品状态
    SELECT @V_DT_INTRUST = VALUE FROM TSYSCONTROL WHERE FLAG_TYPE = N'DT_INTRUST'
    --处理产品单元，如果@IN_CELL_ID参数有效，@V_PRODUCT_IDS中才有记录
    DECLARE @V_PRODUCT_IDS TABLE(PRODUCT_ID INT)
    DECLARE @V_CELLALL TABLE(CELL_ID      INT,
                             CELL_CODE    NVARCHAR(10),
                             CELL_NAME    NVARCHAR(60),
                             CELL_TYPE    INT,
                             PRODUCT_ID   INT,
                             PRODUCT_CODE NVARCHAR(6),
                             PRODUCT_NAME NVARCHAR(60))
   -- IF @IN_CELL_ID IS NOT NULL AND @IN_CELL_ID <> 0
    IF @IN_RECOMMEND_FLAG = 1 
    BEGIN
        SET @V_RECOMMEND_NAME = '110202'
    END
    
    IF @IN_NORMAL_FLAG = 1 
    BEGIN
        SET @V_NORMAL_NAME = '110203'
    END
    
    IF @IN_END_FLAG =1 
    BEGIN
        SET @V_END_NAME = '110204'
    END
    
    BEGIN
        INSERT INTO @V_CELLALL(CELL_ID,CELL_CODE,CELL_NAME,PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME)
            SELECT A.SERIAL_NO,A.CELL_CODE,A.CELL_NAME,A.PRODUCT_ID,A.PRODUCT_CODE,A.PRODUCT_NAME 
                FROM INTRUST..TPRODUCT_CELL A,INTRUST..TPRODUCT B
                WHERE (A.SERIAL_NO = @IN_CELL_ID OR ISNULL(@IN_CELL_ID,0)=0)
                AND   (A.PRODUCT_NAME LIKE '%'+ISNULL(@IN_PRODUCT_NAME,'')+'%')
                AND   (A.PRODUCT_ID = B.PRODUCT_ID)
                AND   (B.PRODUCT_STATUS = ISNULL(@V_RECOMMEND_NAME,'') OR B.PRODUCT_STATUS = ISNULL(@V_NORMAL_NAME,'') OR B.PRODUCT_STATUS = ISNULL(@V_END_NAME,''))
        WHILE @@ROWCOUNT > 0
        BEGIN
            INSERT INTO @V_CELLALL(CELL_ID)
                SELECT A.SUB_CELL_ID
                FROM  INTRUST..TPRODUCT_CELL_DETAIL A, @V_CELLALL B
                WHERE A.DF_SERIAL_NO = B.CELL_ID AND A.SUB_CELL_ID NOT IN(SELECT CELL_ID FROM @V_CELLALL)
        END
        
        UPDATE @V_CELLALL
            SET CELL_CODE = B.CELL_CODE,
                CELL_NAME = B.CELL_NAME,
                CELL_TYPE = B.CELL_TYPE,
                PRODUCT_ID = B.PRODUCT_ID,
                PRODUCT_CODE = B.PRODUCT_CODE,
                PRODUCT_NAME = B.PRODUCT_NAME
            FROM @V_CELLALL A , INTRUST..TPRODUCT_CELL B
            WHERE A.CELL_ID = B.SERIAL_NO
            
        INSERT INTO @V_PRODUCT_IDS(PRODUCT_ID) SELECT PRODUCT_ID FROM @V_CELLALL WHERE CELL_TYPE = 1 GROUP BY PRODUCT_ID
    END
    --界面上没提供产品单元作查询条件，提供的是产品列表，暂时修改一下这里，取传入产品的数据
    DELETE FROM @V_PRODUCT_IDS
    IF @IN_CELL_ID IS NOT NULL AND @IN_CELL_ID <> 0
    BEGIN
        INSERT INTO @V_PRODUCT_IDS VALUES(@IN_CELL_ID)
    END
    ELSE
    BEGIN
        INSERT INTO @V_PRODUCT_IDS 
            SELECT PRODUCT_ID FROM INTRUST..TPRODUCT
                WHERE (PRODUCT_ID = @IN_CELL_ID OR ISNULL(@IN_CELL_ID,0)=0)
                AND (PRODUCT_NAME LIKE '%'+ISNULL(@IN_PRODUCT_NAME,'')+'%')
				AND (PRODUCT_STATUS = ISNULL(@V_RECOMMEND_NAME,'') OR PRODUCT_STATUS = ISNULL(@V_NORMAL_NAME,'') OR PRODUCT_STATUS = ISNULL(@V_END_NAME,''))
            
    END         
    
    CREATE TABLE #TMP_STAT_CHANNELTOTAL1
    (
        PRODUCT_ID              INT,
        PRODUCT_CODE            NVARCHAR(6),    --产品编号
        PRODUCT_NAME            NVARCHAR(60),   --产品名称
        CHANNEL_TYPE            NVARCHAR(10),   --渠道类型
        CHANNEL_TYPE_NAME       NVARCHAR(30),   --渠道类型名称
        CHANNEL_ID              INT,            --渠道ID
        CHANNEL_CODE            NVARCHAR(6),    --渠道编号
        CHANNEL_NAME            NVARCHAR(60),   --渠道名称
        SALE_MAN                INT,            --销售人员ID
        SALE_MAN_NAME           NVARCHAR(30),   --销售人员名称
        PARENT_CHANNEL          INT,            --父渠道ID
        SERVICE_MAN             INT,            --客户经理
        SERVICE_MAN_NAME        NVARCHAR(30),   --客户经理名称
        CUST_ID                 INT,            --客户ID
        CUST_NAME               NVARCHAR(100),  --客户名称
        DATENO                  NVARCHAR(10),   --全部/年/季/月/周
        RG_MONEY                DEC(16,3),      --认购金额
        BEN_AMOUNT              DEC(16,3),      --存续
        NEWCUST_NUMBER          INT,            --新增客户数
        CONTRACT_NUMBER         INT,            --合同数
        ACTIVECUST_NUMBER       INT,            --存续客户数
        DATA_TYPE               INT,            --数据类型，每插入一次编一个号，最后返回编号最大的那组数据
        CHANNEL_COOPERTYPE      NVARCHAR(10),   --渠道合作方式
        CHANNEL_COOPERTYPE_NAME NVARCHAR(30),   --渠道合作方式名称
        FACT_MONEY      		DEC(16,3),      --产品总规模
		SUB_PRODUCT_NAME 		NVARCHAR(100),  --子产品名称
		PRODUCT_STATUS_NAME		NVARCHAR(20)	--产品状态名称
    )
    --注：由于是多阶段group，无法计算“交易发生客户数”，只能计算合同数、新增客户数、存续客户数
    BEGIN
        IF @IN_GROUP_TYPE = 1 --按周
            INSERT INTO #TMP_STAT_CHANNELTOTAL1(PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,CHANNEL_TYPE,
				  CHANNEL_ID,CHANNEL_CODE,CHANNEL_NAME,RG_MONEY,DATENO,CHANNEL_TYPE_NAME,SALE_MAN,
				  SERVICE_MAN,NEWCUST_NUMBER,BEN_AMOUNT,CONTRACT_NUMBER,CUST_ID,CHANNEL_COOPERTYPE,
				  CHANNEL_COOPERTYPE_NAME,SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME)
            SELECT A.PRODUCT_ID,A.PRODUCT_CODE,C.PRODUCT_NAME,ISNULL(A.CHANNEL_TYPE,''),
				  ISNULL(A.CHANNEL_ID,0),B.CHANNEL_CODE,B.CHANNEL_NAME,SUM(F.TO_MONEY) AS RG_MONEY, 
				  A.START_DATE/10000*100+DATEPART(week,dbo.GetDateTime(A.START_DATE)) AS DATENO, 
				  E.TYPE_CONTENT AS CHANNEL_TYPE_NAME,A.LINK_MAN,A.SERVICE_MAN,
                  SUM(CASE WHEN A.QS_DATE = M.FIRST_RG_DATE THEN 1 ELSE 0 END), SUM(N.BEN_AMOUNT), 
				  COUNT(A.SERIAL_NO), A.CUST_ID,A.CHANNEL_COOPERTYPE,A.CHANNEL_COOPERTYPE_NAME,
				  P.LIST_NAME AS SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME
            FROM INTRUST..TCONTRACT A 
				 LEFT JOIN INTRUST..TCHANNEL B ON A.CHANNEL_ID = B.CHANNEL_ID AND (B.CHANNEL_NAME LIKE '%'+@IN_CHANNEL_NAME+'%' OR ISNULL(@IN_CHANNEL_NAME,'') = '')
                 LEFT JOIN INTRUST..TSUBPRODUCT P ON A.SUB_PRODUCT_ID = P.SUB_PRODUCT_ID
				 LEFT JOIN INTRUST..TDICTPARAM E ON A.CHANNEL_TYPE = E.TYPE_VALUE, INTRUST..TPRODUCT C,
                 (SELECT CUST_ID,MIN(QS_DATE)AS FIRST_RG_DATE FROM INTRUST..TCONTRACT GROUP BY CUST_ID) M,
                 INTRUST..TBENIFITOR N
				 ,(SELECT PRODUCT_ID,SUB_PRODUCT_ID,CONTRACT_BH,CUST_ID,SUM(TO_MONEY) AS TO_MONEY 
                  FROM INTRUST..TMONEYDETAIL GROUP BY PRODUCT_ID,SUB_PRODUCT_ID,CONTRACT_BH,CUST_ID) F
            WHERE (A.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID OR ISNULL(@IN_SUB_PRODUCT_ID,0)=0)
				AND (A.PRODUCT_ID = C.PRODUCT_ID)
				AND (A.CUST_ID = M.CUST_ID) 
				AND (C.INTRUST_FLAG1 = @IN_INTRUST_FLAG1 OR ISNULL(@IN_INTRUST_FLAG1 ,0)= 0)
                AND (A.PRODUCT_ID = N.PRODUCT_ID)
				AND (A.CONTRACT_BH = N.CONTRACT_BH)
                AND (A.START_DATE BETWEEN @IN_BEGIN_DATE AND ISNULL(@IN_END_DATE,30001231))
                AND (A.CHANNEL_TYPE LIKE '%'+ISNULL(@IN_CHANNEL_TYPE,'')+'%')
                AND (A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCT_IDS) OR NOT EXISTS(SELECT 1 FROM @V_PRODUCT_IDS))
				AND (A.PRODUCT_ID = F.PRODUCT_ID)
				AND (A.CUST_ID = F.CUST_ID)
				AND (A.CONTRACT_BH = F.CONTRACT_BH)
				AND (ISNULL(A.SUB_PRODUCT_ID,0)  = ISNULL(F.SUB_PRODUCT_ID,0))--AND (A.SUB_PRODUCT_ID  = F.SUB_PRODUCT_ID)
            GROUP BY A.PRODUCT_ID,A.PRODUCT_CODE,C.PRODUCT_NAME,ISNULL(A.CHANNEL_TYPE,''),ISNULL(A.CHANNEL_ID,0),
				B.CHANNEL_CODE,B.CHANNEL_NAME,A.START_DATE/10000*100+DATEPART(week,dbo.GetDateTime(A.START_DATE)),
				E.TYPE_CONTENT,A.LINK_MAN,A.SERVICE_MAN,A.CUST_ID,A.CHANNEL_COOPERTYPE,
				A.CHANNEL_COOPERTYPE_NAME,P.LIST_NAME,PRODUCT_STATUS_NAME
            ORDER BY DATENO,ISNULL(A.CHANNEL_TYPE,''),A.PRODUCT_CODE,C.PRODUCT_NAME
        ELSE IF @IN_GROUP_TYPE = 2 --按月
            INSERT INTO #TMP_STAT_CHANNELTOTAL1(PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,CHANNEL_TYPE,
					CHANNEL_ID,CHANNEL_CODE,CHANNEL_NAME,RG_MONEY,DATENO,CHANNEL_TYPE_NAME,SALE_MAN,
					SERVICE_MAN,NEWCUST_NUMBER,BEN_AMOUNT,CONTRACT_NUMBER,CUST_ID,CHANNEL_COOPERTYPE,
					CHANNEL_COOPERTYPE_NAME,SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME)
            SELECT A.PRODUCT_ID,A.PRODUCT_CODE,C.PRODUCT_NAME,ISNULL(A.CHANNEL_TYPE,''),
					ISNULL(A.CHANNEL_ID,0),B.CHANNEL_CODE,B.CHANNEL_NAME,SUM(F.TO_MONEY) AS RG_MONEY, 
					A.START_DATE/10000*100+DATEPART(month,dbo.GetDateTime(A.START_DATE)) AS DATENO, 
					E.TYPE_CONTENT AS CHANNEL_TYPE_NAME,A.LINK_MAN,A.SERVICE_MAN,
                   SUM(CASE WHEN A.QS_DATE = M.FIRST_RG_DATE THEN 1 ELSE 0 END), SUM(N.BEN_AMOUNT), 
				   COUNT(A.SERIAL_NO), A.CUST_ID,A.CHANNEL_COOPERTYPE,A.CHANNEL_COOPERTYPE_NAME,
				   P.LIST_NAME AS SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME
            FROM INTRUST..TCONTRACT A 
				LEFT JOIN INTRUST..TCHANNEL B ON A.CHANNEL_ID = B.CHANNEL_ID AND (B.CHANNEL_NAME LIKE '%'+@IN_CHANNEL_NAME+'%' OR ISNULL(@IN_CHANNEL_NAME,'') = '')
				LEFT JOIN INTRUST..TSUBPRODUCT P ON A.SUB_PRODUCT_ID = P.SUB_PRODUCT_ID
				LEFT JOIN INTRUST..TDICTPARAM E ON A.CHANNEL_TYPE = E.TYPE_VALUE,INTRUST..TPRODUCT C,
                (SELECT CUST_ID,MIN(QS_DATE)AS FIRST_RG_DATE FROM INTRUST..TCONTRACT GROUP BY CUST_ID) M,
                INTRUST..TBENIFITOR N
				,(SELECT PRODUCT_ID,SUB_PRODUCT_ID,CONTRACT_BH,CUST_ID,SUM(TO_MONEY) AS TO_MONEY 
                 FROM INTRUST..TMONEYDETAIL GROUP BY PRODUCT_ID,SUB_PRODUCT_ID,CONTRACT_BH,CUST_ID) F
            WHERE (A.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID OR ISNULL(@IN_SUB_PRODUCT_ID,0)=0)
				AND (A.PRODUCT_ID = C.PRODUCT_ID) 
				AND (A.CUST_ID = M.CUST_ID) 
				AND (C.INTRUST_FLAG1 = @IN_INTRUST_FLAG1 OR ISNULL(@IN_INTRUST_FLAG1 ,0)= 0)
                AND (A.PRODUCT_ID = N.PRODUCT_ID   )
				AND (A.CONTRACT_BH = N.CONTRACT_BH )
                AND (A.START_DATE BETWEEN @IN_BEGIN_DATE AND ISNULL(@IN_END_DATE,30001231))
                AND (A.CHANNEL_TYPE LIKE '%'+ISNULL(@IN_CHANNEL_TYPE,'')+'%')
                AND (A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCT_IDS) OR NOT EXISTS(SELECT 1 FROM @V_PRODUCT_IDS))
				AND (A.PRODUCT_ID = F.PRODUCT_ID)
				AND (A.CUST_ID = F.CUST_ID)
				AND (A.CONTRACT_BH = F.CONTRACT_BH)
            GROUP BY A.PRODUCT_ID,A.PRODUCT_CODE,C.PRODUCT_NAME,ISNULL(A.CHANNEL_TYPE,''),ISNULL(A.CHANNEL_ID,0),
					B.CHANNEL_CODE,B.CHANNEL_NAME,A.START_DATE/10000*100+DATEPART(month,dbo.GetDateTime(A.START_DATE)),
					E.TYPE_CONTENT,A.LINK_MAN,A.SERVICE_MAN,A.CUST_ID,A.CHANNEL_COOPERTYPE,
					A.CHANNEL_COOPERTYPE_NAME,P.LIST_NAME,PRODUCT_STATUS_NAME
            ORDER BY DATENO,ISNULL(A.CHANNEL_TYPE,''),A.PRODUCT_CODE
        ELSE IF @IN_GROUP_TYPE = 3 --按季
            INSERT INTO #TMP_STAT_CHANNELTOTAL1(PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,CHANNEL_TYPE,
				CHANNEL_ID,CHANNEL_CODE,CHANNEL_NAME,RG_MONEY,DATENO,CHANNEL_TYPE_NAME,SALE_MAN,
				SERVICE_MAN,NEWCUST_NUMBER,BEN_AMOUNT,CONTRACT_NUMBER,CUST_ID,CHANNEL_COOPERTYPE,
				CHANNEL_COOPERTYPE_NAME,SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME)
            SELECT A.PRODUCT_ID,A.PRODUCT_CODE,C.PRODUCT_NAME,ISNULL(A.CHANNEL_TYPE,''),
				ISNULL(A.CHANNEL_ID,0),B.CHANNEL_CODE,B.CHANNEL_NAME,SUM(F.TO_MONEY) AS RG_MONEY, 
				A.START_DATE/10000*100+DATEPART(quarter,dbo.GetDateTime(A.START_DATE)) AS DATENO, 
				E.TYPE_CONTENT AS CHANNEL_TYPE_NAME,A.LINK_MAN,A.SERVICE_MAN,
                SUM(CASE WHEN A.QS_DATE = M.FIRST_RG_DATE THEN 1 ELSE 0 END), SUM(N.BEN_AMOUNT), 
				COUNT(A.SERIAL_NO), A.CUST_ID,A.CHANNEL_COOPERTYPE,A.CHANNEL_COOPERTYPE_NAME,
				P.LIST_NAME AS SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME
            FROM INTRUST..TCONTRACT A 
				LEFT JOIN INTRUST..TCHANNEL B ON A.CHANNEL_ID = B.CHANNEL_ID AND (B.CHANNEL_NAME LIKE '%'+@IN_CHANNEL_NAME+'%' OR ISNULL(@IN_CHANNEL_NAME,'') = '')
                LEFT JOIN INTRUST..TSUBPRODUCT P ON A.SUB_PRODUCT_ID = P.SUB_PRODUCT_ID
				LEFT JOIN INTRUST..TDICTPARAM E ON A.CHANNEL_TYPE = E.TYPE_VALUE, INTRUST..TPRODUCT C,
                (SELECT CUST_ID,MIN(QS_DATE)AS FIRST_RG_DATE FROM INTRUST..TCONTRACT GROUP BY CUST_ID) M,
                INTRUST..TBENIFITOR N
				,(SELECT PRODUCT_ID,SUB_PRODUCT_ID,CONTRACT_BH,CUST_ID,SUM(TO_MONEY) AS TO_MONEY 
                 FROM INTRUST..TMONEYDETAIL GROUP BY PRODUCT_ID,SUB_PRODUCT_ID,CONTRACT_BH,CUST_ID) F
            WHERE (A.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID OR ISNULL(@IN_SUB_PRODUCT_ID,0)=0)  
				AND (A.PRODUCT_ID = C.PRODUCT_ID )
				AND (A.CUST_ID = M.CUST_ID       )
				AND (C.INTRUST_FLAG1 = @IN_INTRUST_FLAG1 OR ISNULL(@IN_INTRUST_FLAG1 ,0)= 0)
                AND (A.PRODUCT_ID = N.PRODUCT_ID )
				AND (A.CONTRACT_BH = N.CONTRACT_BH)
                AND (A.START_DATE BETWEEN @IN_BEGIN_DATE AND ISNULL(@IN_END_DATE,30001231))
                AND (A.CHANNEL_TYPE LIKE '%'+ISNULL(@IN_CHANNEL_TYPE,'')+'%')
                AND (A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCT_IDS) OR NOT EXISTS(SELECT 1 FROM @V_PRODUCT_IDS))
				AND (A.PRODUCT_ID = F.PRODUCT_ID)
				AND (A.CUST_ID = F.CUST_ID)
				AND (A.CONTRACT_BH = F.CONTRACT_BH)
				AND (ISNULL(A.SUB_PRODUCT_ID,0)  = ISNULL(F.SUB_PRODUCT_ID,0))--AND (A.SUB_PRODUCT_ID  = F.SUB_PRODUCT_ID)
            GROUP BY A.PRODUCT_ID,A.PRODUCT_CODE,C.PRODUCT_NAME,ISNULL(A.CHANNEL_TYPE,''),ISNULL(A.CHANNEL_ID,0),
				B.CHANNEL_CODE,B.CHANNEL_NAME,A.START_DATE/10000*100+DATEPART(quarter,dbo.GetDateTime(A.START_DATE)),
				E.TYPE_CONTENT,A.LINK_MAN,A.SERVICE_MAN,A.CUST_ID,A.CHANNEL_COOPERTYPE,
				A.CHANNEL_COOPERTYPE_NAME,P.LIST_NAME,PRODUCT_STATUS_NAME
            ORDER BY DATENO,ISNULL(A.CHANNEL_TYPE,''),A.PRODUCT_CODE
        ELSE IF @IN_GROUP_TYPE = 4 --按年
            INSERT INTO #TMP_STAT_CHANNELTOTAL1(PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,CHANNEL_TYPE,
				CHANNEL_ID,CHANNEL_CODE,CHANNEL_NAME,RG_MONEY,DATENO,CHANNEL_TYPE_NAME,SALE_MAN,
				SERVICE_MAN,NEWCUST_NUMBER,BEN_AMOUNT,CONTRACT_NUMBER,CUST_ID,CHANNEL_COOPERTYPE,
				CHANNEL_COOPERTYPE_NAME,SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME)
            SELECT A.PRODUCT_ID,A.PRODUCT_CODE,C.PRODUCT_NAME,ISNULL(A.CHANNEL_TYPE,''),
				ISNULL(A.CHANNEL_ID,0),B.CHANNEL_CODE,B.CHANNEL_NAME,SUM(F.TO_MONEY) AS RG_MONEY, 
				DATEPART(year,dbo.GetDateTime(A.START_DATE)) AS DATENO, E.TYPE_CONTENT AS CHANNEL_TYPE_NAME,
				A.LINK_MAN,A.SERVICE_MAN,SUM(CASE WHEN A.QS_DATE = M.FIRST_RG_DATE THEN 1 ELSE 0 END), 
				SUM(N.BEN_AMOUNT), COUNT(A.SERIAL_NO), A.CUST_ID,A.CHANNEL_COOPERTYPE,A.CHANNEL_COOPERTYPE_NAME,
				P.LIST_NAME AS SUB_RPODUCT_NAME,PRODUCT_STATUS_NAME
            FROM INTRUST..TCONTRACT A 
				LEFT JOIN INTRUST..TCHANNEL B ON A.CHANNEL_ID = B.CHANNEL_ID AND (B.CHANNEL_NAME LIKE '%'+@IN_CHANNEL_NAME+'%' OR ISNULL(@IN_CHANNEL_NAME,'') = '')
                LEFT JOIN INTRUST..TSUBPRODUCT P ON A.SUB_PRODUCT_ID = P.SUB_PRODUCT_ID
				LEFT JOIN INTRUST..TDICTPARAM E ON A.CHANNEL_TYPE = E.TYPE_VALUE, INTRUST..TPRODUCT C,
                (SELECT CUST_ID,MIN(QS_DATE)AS FIRST_RG_DATE FROM INTRUST..TCONTRACT GROUP BY CUST_ID) M,
                INTRUST..TBENIFITOR N
				,(SELECT PRODUCT_ID,SUB_PRODUCT_ID,CONTRACT_BH,CUST_ID,SUM(TO_MONEY) AS TO_MONEY 
                 FROM INTRUST..TMONEYDETAIL GROUP BY PRODUCT_ID,SUB_PRODUCT_ID,CONTRACT_BH,CUST_ID) F
            WHERE (A.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID OR ISNULL(@IN_SUB_PRODUCT_ID,0)=0) 
				AND (A.PRODUCT_ID = C.PRODUCT_ID )
				AND (A.CUST_ID = M.CUST_ID )
				AND (C.INTRUST_FLAG1 = @IN_INTRUST_FLAG1 OR ISNULL(@IN_INTRUST_FLAG1 ,0)= 0)
                AND (A.PRODUCT_ID = N.PRODUCT_ID )
				AND (A.CONTRACT_BH = N.CONTRACT_BH)
                AND (A.START_DATE BETWEEN @IN_BEGIN_DATE AND ISNULL(@IN_END_DATE,30001231))
                AND (A.CHANNEL_TYPE LIKE '%'+ISNULL(@IN_CHANNEL_TYPE,'')+'%')
                AND (A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCT_IDS) OR NOT EXISTS(SELECT 1 FROM @V_PRODUCT_IDS))
				AND (A.PRODUCT_ID = F.PRODUCT_ID)
				AND (A.CUST_ID = F.CUST_ID)
				AND (A.CONTRACT_BH = F.CONTRACT_BH)
				AND (ISNULL(A.SUB_PRODUCT_ID,0)  = ISNULL(F.SUB_PRODUCT_ID,0))--AND (A.SUB_PRODUCT_ID  = F.SUB_PRODUCT_ID)
            GROUP BY A.PRODUCT_ID,A.PRODUCT_CODE,C.PRODUCT_NAME,ISNULL(A.CHANNEL_TYPE,''),ISNULL(A.CHANNEL_ID,0),
				B.CHANNEL_CODE,B.CHANNEL_NAME,DATEPART(year,dbo.GetDateTime(A.START_DATE)),E.TYPE_CONTENT,
				A.LINK_MAN,A.SERVICE_MAN,A.CUST_ID,CHANNEL_COOPERTYPE,A.CHANNEL_COOPERTYPE_NAME,
				P.LIST_NAME,PRODUCT_STATUS_NAME
            ORDER BY DATENO,ISNULL(A.CHANNEL_TYPE,''),A.PRODUCT_CODE
        ELSE IF @IN_GROUP_TYPE = 5 --全部
            INSERT INTO #TMP_STAT_CHANNELTOTAL1(PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,CHANNEL_TYPE,
				CHANNEL_ID,CHANNEL_CODE,CHANNEL_NAME,RG_MONEY,DATENO,CHANNEL_TYPE_NAME,SALE_MAN,
				SERVICE_MAN,NEWCUST_NUMBER,BEN_AMOUNT,CONTRACT_NUMBER,CUST_ID,CHANNEL_COOPERTYPE,
				CHANNEL_COOPERTYPE_NAME,SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME)
            SELECT A.PRODUCT_ID,A.PRODUCT_CODE,C.PRODUCT_NAME,ISNULL(A.CHANNEL_TYPE,''),
				ISNULL(A.CHANNEL_ID,0),B.CHANNEL_CODE,B.CHANNEL_NAME,SUM(F.TO_MONEY) AS RG_MONEY, 
				NULL AS DATENO, E.TYPE_CONTENT AS CHANNEL_TYPE_NAME,A.LINK_MAN,A.SERVICE_MAN,
                SUM(CASE WHEN A.QS_DATE = M.FIRST_RG_DATE THEN 1 ELSE 0 END), SUM(N.BEN_AMOUNT), 
				COUNT(A.SERIAL_NO), A.CUST_ID,A.CHANNEL_COOPERTYPE,A.CHANNEL_COOPERTYPE_NAME,
				P.LIST_NAME AS SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME
            FROM INTRUST..TCONTRACT A 
				LEFT JOIN INTRUST..TCHANNEL B ON A.CHANNEL_ID = B.CHANNEL_ID AND (B.CHANNEL_NAME LIKE '%'+@IN_CHANNEL_NAME+'%' OR ISNULL(@IN_CHANNEL_NAME,'') = '')
                LEFT JOIN INTRUST..TSUBPRODUCT P ON A.SUB_PRODUCT_ID = P.SUB_PRODUCT_ID
				LEFT JOIN INTRUST..TDICTPARAM E ON A.CHANNEL_TYPE = E.TYPE_VALUE, INTRUST..TPRODUCT C,
                (SELECT CUST_ID,MIN(QS_DATE)AS FIRST_RG_DATE FROM INTRUST..TCONTRACT GROUP BY CUST_ID) M,
                INTRUST..TBENIFITOR N
				,(SELECT PRODUCT_ID,SUB_PRODUCT_ID,CONTRACT_BH,CUST_ID,SUM(TO_MONEY) AS TO_MONEY 
                 FROM INTRUST..TMONEYDETAIL GROUP BY PRODUCT_ID,SUB_PRODUCT_ID,CONTRACT_BH,CUST_ID) F
            WHERE (A.SUB_PRODUCT_ID = @IN_SUB_PRODUCT_ID OR ISNULL(@IN_SUB_PRODUCT_ID,0)=0) 
				AND (A.PRODUCT_ID = C.PRODUCT_ID) 
				AND (A.CUST_ID = M.CUST_ID )
				AND (C.INTRUST_FLAG1 = @IN_INTRUST_FLAG1 OR ISNULL(@IN_INTRUST_FLAG1 ,0)= 0)
                AND (A.PRODUCT_ID = N.PRODUCT_ID )
				AND (A.CONTRACT_BH = N.CONTRACT_BH)
                AND (A.START_DATE BETWEEN @IN_BEGIN_DATE AND ISNULL(@IN_END_DATE,30001231))
                AND (A.CHANNEL_TYPE LIKE '%'+ISNULL(@IN_CHANNEL_TYPE,'')+'%')
                AND (A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCT_IDS) OR NOT EXISTS(SELECT 1 FROM @V_PRODUCT_IDS))
				AND (A.PRODUCT_ID = F.PRODUCT_ID)
				AND (A.CUST_ID = F.CUST_ID)
				AND (A.CONTRACT_BH = F.CONTRACT_BH)
				AND (ISNULL(A.SUB_PRODUCT_ID,0)  = ISNULL(F.SUB_PRODUCT_ID,0))--AND (A.SUB_PRODUCT_ID  = F.SUB_PRODUCT_ID)
            GROUP BY A.PRODUCT_ID,A.PRODUCT_CODE,C.PRODUCT_NAME,C.PRODUCT_NAME,ISNULL(A.CHANNEL_TYPE,''),
				ISNULL(A.CHANNEL_ID,0),B.CHANNEL_CODE,B.CHANNEL_NAME,E.TYPE_CONTENT,A.LINK_MAN,A.SERVICE_MAN,
				A.CUST_ID,A.CHANNEL_COOPERTYPE,A.CHANNEL_COOPERTYPE_NAME,P.LIST_NAME,PRODUCT_STATUS_NAME
            ORDER BY ISNULL(A.CHANNEL_TYPE,''),A.PRODUCT_CODE
        UPDATE #TMP_STAT_CHANNELTOTAL1 SET SALE_MAN_NAME = B.OP_NAME
            FROM #TMP_STAT_CHANNELTOTAL1 A, INTRUST..TOPERATOR B
            WHERE A.SALE_MAN = B.OP_CODE
        UPDATE #TMP_STAT_CHANNELTOTAL1 SET SERVICE_MAN_NAME = B.OP_NAME
            FROM #TMP_STAT_CHANNELTOTAL1 A, INTRUST..TOPERATOR B
            WHERE A.SERVICE_MAN = B.OP_CODE
    END

    UPDATE #TMP_STAT_CHANNELTOTAL1 SET ACTIVECUST_NUMBER = B.ACTIVECUST_NUMBER
        FROM #TMP_STAT_CHANNELTOTAL1 A,
           (SELECT A.PRODUCT_ID,ISNULL(A.CHANNEL_TYPE,'') AS CHANNEL_TYPE,ISNULL(A.CHANNEL_ID,0)AS CHANNEL_ID,
                   ISNULL(A.LINK_MAN,0)AS LINK_MAN,ISNULL(A.SERVICE_MAN,0)AS SERVICE_MAN,CUST_ID,
				   ISNULL(A.CHANNEL_COOPERTYPE,'') AS CHANNEL_COOPERTYPE,COUNT(*)AS ACTIVECUST_NUMBER FROM (
                SELECT A.PRODUCT_ID,A.CHANNEL_TYPE,A.CHANNEL_ID,A.LINK_MAN,A.SERVICE_MAN,A.CUST_ID,A.CHANNEL_COOPERTYPE
                FROM INTRUST..TCONTRACT a, INTRUST..TBENIFITOR B
                WHERE A.PRODUCT_ID = B.PRODUCT_ID 
                AND A.CONTRACT_BH = B.CONTRACT_BH 
                AND B.BEN_AMOUNT>0
                AND (A.PRODUCT_ID = @IN_CELL_ID OR ISNULL(@IN_CELL_ID,0)=0)
                GROUP BY A.PRODUCT_ID,A.CHANNEL_TYPE,A.CHANNEL_ID,A.LINK_MAN,A.SERVICE_MAN,A.CUST_ID,A.CHANNEL_COOPERTYPE) A
            GROUP BY A.PRODUCT_ID,ISNULL(A.CHANNEL_TYPE,''),ISNULL(A.CHANNEL_ID,0),
				ISNULL(A.LINK_MAN,0),ISNULL(A.SERVICE_MAN,0),A.CUST_ID,ISNULL(A.CHANNEL_COOPERTYPE,'')) B
        WHERE A.PRODUCT_ID = B.PRODUCT_ID 
			AND ISNULL(A.CHANNEL_TYPE,'') = ISNULL(B.CHANNEL_TYPE,'') 
			AND ISNULL(A.CHANNEL_ID,0) = ISNULL(B.CHANNEL_ID,0)
            AND ISNULL(A.SALE_MAN,0) = ISNULL(B.LINK_MAN,0) 
			AND ISNULL(A.SERVICE_MAN,0) = ISNULL(B.SERVICE_MAN,0)
            AND A.CUST_ID = B.CUST_ID
            AND (A.CHANNEL_COOPERTYPE = B.CHANNEL_COOPERTYPE OR ISNULL(A.CHANNEL_COOPERTYPE,'')='')

    --更新客户名称
    UPDATE #TMP_STAT_CHANNELTOTAL1 SET CUST_NAME = B.CUST_NAME
        FROM #TMP_STAT_CHANNELTOTAL1 A, EFCRM..TCustomers B
        WHERE A.CUST_ID = B.CUST_ID
    UPDATE #TMP_STAT_CHANNELTOTAL1 SET SALE_MAN = NULL WHERE SALE_MAN = 0
    UPDATE #TMP_STAT_CHANNELTOTAL1 SET SERVICE_MAN = NULL WHERE SERVICE_MAN = 0
    UPDATE #TMP_STAT_CHANNELTOTAL1 SET ACTIVECUST_NUMBER = 0 WHERE ACTIVECUST_NUMBER IS NULL
    --第1批，明细（包含产品、渠道、销售人员、客户经理、渠道合作方式）
    UPDATE #TMP_STAT_CHANNELTOTAL1 SET DATA_TYPE = 1
        WHERE DATA_TYPE IS NULL
            AND(CHANNEL_ID = @IN_CHANNEL_ID OR ISNULL(@IN_CHANNEL_ID,0) = 0)
            AND(SALE_MAN = @IN_SALE_MAN OR ISNULL(@IN_SALE_MAN,0) = 0)
            AND(SERVICE_MAN = @IN_SERVICE_MAN OR ISNULL(@IN_SERVICE_MAN,0) = 0)
            AND(CUST_NAME LIKE '%'+@IN_CUST_NAME+'%')
            AND(CHANNEL_COOPERTYPE = @IN_CHANNEL_COOPERTYPE OR ISNULL(@IN_CHANNEL_COOPERTYPE,'')='')
    SELECT @V_DATA_TYPE = MAX(DATA_TYPE) FROM #TMP_STAT_CHANNELTOTAL1
    
    --更新产品的总规模
    UPDATE #TMP_STAT_CHANNELTOTAL1 SET FACT_MONEY = B.FACT_MONEY
        FROM #TMP_STAT_CHANNELTOTAL1 A,INTRUST..TPRODUCT B
        WHERE A.PRODUCT_ID = B.PRODUCT_ID
    
    DELETE FROM #TMP_STAT_CHANNELTOTAL1 WHERE DATA_TYPE IS NULL

    IF @IN_LIST_PRODUCT = 2 --不列示产品，所有产品汇总掉
    BEGIN
        INSERT INTO #TMP_STAT_CHANNELTOTAL1(RG_MONEY,BEN_AMOUNT,CONTRACT_NUMBER,NEWCUST_NUMBER,
				ACTIVECUST_NUMBER,CHANNEL_TYPE,CHANNEL_TYPE_NAME,CHANNEL_ID,CHANNEL_CODE,CHANNEL_NAME,
				PARENT_CHANNEL,SALE_MAN,SALE_MAN_NAME,SERVICE_MAN,SERVICE_MAN_NAME,DATENO,CUST_ID,CUST_NAME,
				CHANNEL_COOPERTYPE,CHANNEL_COOPERTYPE_NAME)
            SELECT SUM(RG_MONEY),SUM(BEN_AMOUNT),SUM(CONTRACT_NUMBER),SUM(NEWCUST_NUMBER),
				SUM(ACTIVECUST_NUMBER),CHANNEL_TYPE,CHANNEL_TYPE_NAME,CHANNEL_ID,CHANNEL_CODE,
				CHANNEL_NAME,PARENT_CHANNEL,SALE_MAN,SALE_MAN_NAME,SERVICE_MAN,SERVICE_MAN_NAME,
				DATENO,CUST_ID,CUST_NAME,CHANNEL_COOPERTYPE,CHANNEL_COOPERTYPE_NAME
            FROM #TMP_STAT_CHANNELTOTAL1 WHERE DATA_TYPE = @V_DATA_TYPE
            GROUP BY CHANNEL_TYPE,CHANNEL_TYPE_NAME,CHANNEL_ID,CHANNEL_CODE,CHANNEL_NAME,PARENT_CHANNEL,
				SALE_MAN,SALE_MAN_NAME,SERVICE_MAN,SERVICE_MAN_NAME,DATENO,CUST_ID,CUST_NAME,
				CHANNEL_COOPERTYPE,CHANNEL_COOPERTYPE_NAME
        UPDATE #TMP_STAT_CHANNELTOTAL1 SET DATA_TYPE = @V_DATA_TYPE+1 WHERE DATA_TYPE IS NULL
        SELECT @V_DATA_TYPE = MAX(DATA_TYPE) FROM #TMP_STAT_CHANNELTOTAL1
    END
    IF @IN_LIST_SALEMAN = 2 --不列示销售人员，所有销售人员汇总掉
    BEGIN
        INSERT INTO #TMP_STAT_CHANNELTOTAL1(RG_MONEY,BEN_AMOUNT,CONTRACT_NUMBER,NEWCUST_NUMBER,
				ACTIVECUST_NUMBER,PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,CHANNEL_TYPE,CHANNEL_TYPE_NAME,
				CHANNEL_ID,CHANNEL_CODE,CHANNEL_NAME,PARENT_CHANNEL,SERVICE_MAN,SERVICE_MAN_NAME,DATENO,
				CUST_ID,CUST_NAME,CHANNEL_COOPERTYPE,CHANNEL_COOPERTYPE_NAME,FACT_MONEY,
				SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME)
            SELECT SUM(RG_MONEY),SUM(BEN_AMOUNT),SUM(CONTRACT_NUMBER),SUM(NEWCUST_NUMBER),
				SUM(ACTIVECUST_NUMBER),PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,CHANNEL_TYPE,
				CHANNEL_TYPE_NAME,CHANNEL_ID,CHANNEL_CODE,CHANNEL_NAME,PARENT_CHANNEL,SERVICE_MAN,
				SERVICE_MAN_NAME,DATENO,CUST_ID,CUST_NAME,CHANNEL_COOPERTYPE,CHANNEL_COOPERTYPE_NAME,
				FACT_MONEY,SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME
            FROM #TMP_STAT_CHANNELTOTAL1 WHERE DATA_TYPE = @V_DATA_TYPE
            GROUP BY PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,CHANNEL_TYPE,CHANNEL_TYPE_NAME,CHANNEL_ID,
				CHANNEL_CODE,CHANNEL_NAME,PARENT_CHANNEL,SERVICE_MAN,SERVICE_MAN_NAME,DATENO,CUST_ID,
				CUST_NAME,CHANNEL_COOPERTYPE,CHANNEL_COOPERTYPE_NAME,FACT_MONEY,
				SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME
        UPDATE #TMP_STAT_CHANNELTOTAL1 SET DATA_TYPE = @V_DATA_TYPE+1 WHERE DATA_TYPE IS NULL
        SELECT @V_DATA_TYPE = MAX(DATA_TYPE) FROM #TMP_STAT_CHANNELTOTAL1
    END
    IF @IN_LIST_SERVICEMAN = 2 --不列示客户经理，所有客户经理汇总掉
    BEGIN
        INSERT INTO #TMP_STAT_CHANNELTOTAL1(RG_MONEY,BEN_AMOUNT,CONTRACT_NUMBER,NEWCUST_NUMBER,
				ACTIVECUST_NUMBER,PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,CHANNEL_TYPE,CHANNEL_TYPE_NAME,
				CHANNEL_ID,CHANNEL_CODE,CHANNEL_NAME,PARENT_CHANNEL,SALE_MAN,SALE_MAN_NAME,DATENO,
				CUST_ID,CUST_NAME,CHANNEL_COOPERTYPE,CHANNEL_COOPERTYPE_NAME,FACT_MONEY,
				SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME)
            SELECT SUM(RG_MONEY),SUM(BEN_AMOUNT),SUM(CONTRACT_NUMBER),SUM(NEWCUST_NUMBER),
				SUM(ACTIVECUST_NUMBER),PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,CHANNEL_TYPE,
				CHANNEL_TYPE_NAME,CHANNEL_ID,CHANNEL_CODE,CHANNEL_NAME,PARENT_CHANNEL,SALE_MAN,
				SALE_MAN_NAME,DATENO,CUST_ID,CUST_NAME,CHANNEL_COOPERTYPE,CHANNEL_COOPERTYPE_NAME,
				FACT_MONEY,SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME
            FROM #TMP_STAT_CHANNELTOTAL1 WHERE DATA_TYPE = @V_DATA_TYPE
            GROUP BY PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,CHANNEL_TYPE,CHANNEL_TYPE_NAME,CHANNEL_ID,
				CHANNEL_CODE,CHANNEL_NAME,PARENT_CHANNEL,SALE_MAN,SALE_MAN_NAME,DATENO,CUST_ID,
				CUST_NAME,CHANNEL_COOPERTYPE,CHANNEL_COOPERTYPE_NAME,FACT_MONEY,
				SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME
        UPDATE #TMP_STAT_CHANNELTOTAL1 SET DATA_TYPE = @V_DATA_TYPE+1 WHERE DATA_TYPE IS NULL
        SELECT @V_DATA_TYPE = MAX(DATA_TYPE) FROM #TMP_STAT_CHANNELTOTAL1
    END
    IF @IN_LIST_CUST = 2 --不列示客户，所有客户汇总掉
    BEGIN
        INSERT INTO #TMP_STAT_CHANNELTOTAL1(RG_MONEY,BEN_AMOUNT,CONTRACT_NUMBER,NEWCUST_NUMBER,
				ACTIVECUST_NUMBER,PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,CHANNEL_TYPE,CHANNEL_TYPE_NAME,
				CHANNEL_ID,CHANNEL_CODE,CHANNEL_NAME,PARENT_CHANNEL,SALE_MAN,SALE_MAN_NAME,SERVICE_MAN,
				SERVICE_MAN_NAME,DATENO,CHANNEL_COOPERTYPE,CHANNEL_COOPERTYPE_NAME,FACT_MONEY,
				SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME)
            SELECT SUM(RG_MONEY),SUM(BEN_AMOUNT),SUM(CONTRACT_NUMBER),SUM(NEWCUST_NUMBER),
				SUM(ACTIVECUST_NUMBER),PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,CHANNEL_TYPE,
				CHANNEL_TYPE_NAME,CHANNEL_ID,CHANNEL_CODE,CHANNEL_NAME,PARENT_CHANNEL,SALE_MAN,
				SALE_MAN_NAME,SERVICE_MAN,SERVICE_MAN_NAME,DATENO,CHANNEL_COOPERTYPE,
				CHANNEL_COOPERTYPE_NAME,FACT_MONEY,SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME
            FROM #TMP_STAT_CHANNELTOTAL1 WHERE DATA_TYPE = @V_DATA_TYPE
            GROUP BY PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,CHANNEL_TYPE,CHANNEL_TYPE_NAME,CHANNEL_ID,
				CHANNEL_CODE,CHANNEL_NAME,PARENT_CHANNEL,SALE_MAN,SALE_MAN_NAME,SERVICE_MAN,
				SERVICE_MAN_NAME,DATENO,CHANNEL_COOPERTYPE,CHANNEL_COOPERTYPE_NAME,FACT_MONEY,
				SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME
        UPDATE #TMP_STAT_CHANNELTOTAL1 SET DATA_TYPE = @V_DATA_TYPE+1 WHERE DATA_TYPE IS NULL
        SELECT @V_DATA_TYPE = MAX(DATA_TYPE) FROM #TMP_STAT_CHANNELTOTAL1
    END
    IF @IN_LIST_CHANNEL_COOPERTYPE = 2 --不列示渠道合作方式，所有渠道合作方式汇总掉
    BEGIN
        INSERT INTO #TMP_STAT_CHANNELTOTAL1(RG_MONEY,BEN_AMOUNT,CONTRACT_NUMBER,NEWCUST_NUMBER,
				ACTIVECUST_NUMBER,PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,CHANNEL_TYPE,CHANNEL_TYPE_NAME,
				CHANNEL_ID,CHANNEL_CODE,CHANNEL_NAME,PARENT_CHANNEL,SALE_MAN,SALE_MAN_NAME,SERVICE_MAN,
				SERVICE_MAN_NAME,DATENO,CUST_ID,CUST_NAME,FACT_MONEY,SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME)
            SELECT SUM(RG_MONEY),SUM(BEN_AMOUNT),SUM(CONTRACT_NUMBER),SUM(NEWCUST_NUMBER),
				SUM(ACTIVECUST_NUMBER),PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,CHANNEL_TYPE,
				CHANNEL_TYPE_NAME,CHANNEL_ID,CHANNEL_CODE,CHANNEL_NAME,PARENT_CHANNEL,SALE_MAN,
				SALE_MAN_NAME,SERVICE_MAN,SERVICE_MAN_NAME,DATENO,CUST_ID,CUST_NAME,FACT_MONEY,
				SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME
            FROM #TMP_STAT_CHANNELTOTAL1 WHERE DATA_TYPE = @V_DATA_TYPE
            GROUP BY PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,CHANNEL_TYPE,CHANNEL_TYPE_NAME,CHANNEL_ID,
				CHANNEL_CODE,CHANNEL_NAME,PARENT_CHANNEL,SALE_MAN,SALE_MAN_NAME,SERVICE_MAN,
				SERVICE_MAN_NAME,DATENO,CUST_ID,CUST_NAME,FACT_MONEY,SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME
        UPDATE #TMP_STAT_CHANNELTOTAL1 SET DATA_TYPE = @V_DATA_TYPE+1 WHERE DATA_TYPE IS NULL
        SELECT @V_DATA_TYPE = MAX(DATA_TYPE) FROM #TMP_STAT_CHANNELTOTAL1
    END
    
  
    BEGIN
        UPDATE #TMP_STAT_CHANNELTOTAL1 SET PARENT_CHANNEL = B.PARENT_CHANNEL, 
				CHANNEL_NAME = B.CHANNEL_NAME, CHANNEL_CODE = B.CHANNEL_CODE
            FROM #TMP_STAT_CHANNELTOTAL1 A, INTRUST..TCHANNEL B WHERE A.CHANNEL_ID = B.CHANNEL_ID;
        IF @IN_LIST_CHANNEL = 0 --不列示渠道，所有渠道汇总掉
        BEGIN
            INSERT INTO #TMP_STAT_CHANNELTOTAL1(RG_MONEY,BEN_AMOUNT,CONTRACT_NUMBER,NEWCUST_NUMBER,
					ACTIVECUST_NUMBER,PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,SERVICE_MAN,
					SERVICE_MAN_NAME,SALE_MAN,SALE_MAN_NAME,DATENO,CUST_ID,CUST_NAME,CHANNEL_COOPERTYPE,
					CHANNEL_COOPERTYPE_NAME,FACT_MONEY,SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME)
                SELECT SUM(RG_MONEY),SUM(BEN_AMOUNT),SUM(CONTRACT_NUMBER),SUM(NEWCUST_NUMBER),
					SUM(ACTIVECUST_NUMBER),PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,SERVICE_MAN,
					SERVICE_MAN_NAME,SALE_MAN,SALE_MAN_NAME,DATENO,CUST_ID,CUST_NAME,CHANNEL_COOPERTYPE,
					CHANNEL_COOPERTYPE_NAME,FACT_MONEY,SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME
                FROM #TMP_STAT_CHANNELTOTAL1
                WHERE DATA_TYPE = @V_DATA_TYPE AND ISNULL(CHANNEL_NAME,'') LIKE '%'+ISNULL(@IN_CHANNEL_NAME,'')+'%'
                GROUP BY PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,SERVICE_MAN,SERVICE_MAN_NAME,SALE_MAN,
					SALE_MAN_NAME,DATENO,CUST_ID,CUST_NAME,CHANNEL_COOPERTYPE,CHANNEL_COOPERTYPE_NAME,
					FACT_MONEY,SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME
            UPDATE #TMP_STAT_CHANNELTOTAL1 SET DATA_TYPE = @V_DATA_TYPE+1 WHERE DATA_TYPE IS NULL
            SELECT @V_DATA_TYPE = MAX(DATA_TYPE) FROM #TMP_STAT_CHANNELTOTAL1
            SELECT A.*,CONVERT(NVARCHAR(200),'') AS FULL_NAME FROM #TMP_STAT_CHANNELTOTAL1 A WHERE DATA_TYPE = @V_DATA_TYPE
                ORDER BY A.PRODUCT_CODE DESC,A.CHANNEL_TYPE,A.DATENO  DESC
        END
        ELSE IF @IN_LIST_CHANNEL = 1 --列示所有渠道(按具体渠道统计)
        BEGIN
            SELECT A.*,B.FULL_NAME FROM #TMP_STAT_CHANNELTOTAL1 A LEFT JOIN INTRUST..V_CHANNEL B ON A.CHANNEL_ID = B.CHANNEL_ID
            WHERE A.DATA_TYPE = @V_DATA_TYPE AND ISNULL(B.FULL_NAME,'') LIKE '%'+ISNULL(@IN_CHANNEL_NAME,'')+'%'
            ORDER BY A.PRODUCT_CODE DESC,A.CHANNEL_TYPE,A.DATENO  DESC
        END
        ELSE --按1级渠道列示
        BEGIN
            SELECT SUM(A.RG_MONEY) AS RG_MONEY,SUM(BEN_AMOUNT) AS BEN_AMOUNT,
					SUM(CONTRACT_NUMBER) AS CONTRACT_NUMBER,SUM(NEWCUST_NUMBER) AS NEWCUST_NUMBER,
					SUM(ACTIVECUST_NUMBER) AS ACTIVECUST_NUMBER,A.PRODUCT_ID,A.PRODUCT_CODE,
					A.PRODUCT_NAME,A.CHANNEL_TYPE,A.CHANNEL_TYPE_NAME,B.TOP_PARENT AS CHANNEL_ID,
					C.CHANNEL_CODE,C.CHANNEL_NAME,A.DATENO,NULL AS PARENT_CHANNEL,C.CHANNEL_NAME AS FULL_NAME,
                    A.SALE_MAN,A.SALE_MAN_NAME,A.SERVICE_MAN,A.SERVICE_MAN_NAME,A.CUST_ID,A.CUST_NAME,
					CHANNEL_COOPERTYPE,CHANNEL_COOPERTYPE_NAME,FACT_MONEY,SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME
                FROM #TMP_STAT_CHANNELTOTAL1 A 
					LEFT JOIN INTRUST..V_CHANNEL B ON A.CHANNEL_ID = B.CHANNEL_ID 
					LEFT JOIN INTRUST..TCHANNEL C ON B.TOP_PARENT = C.CHANNEL_ID
                WHERE A.DATA_TYPE = @V_DATA_TYPE AND ISNULL(C.CHANNEL_NAME,'') LIKE '%'+ISNULL(@IN_CHANNEL_NAME,'')+'%'
                GROUP BY A.PRODUCT_ID,A.PRODUCT_CODE,A.PRODUCT_NAME,A.CHANNEL_TYPE,A.CHANNEL_TYPE_NAME,
					B.TOP_PARENT,C.CHANNEL_CODE,C.CHANNEL_NAME,A.DATENO,A.SALE_MAN,A.SALE_MAN_NAME,
					A.SERVICE_MAN,A.SERVICE_MAN_NAME,A.CUST_ID,A.CUST_NAME,CHANNEL_COOPERTYPE,
					CHANNEL_COOPERTYPE_NAME,FACT_MONEY,SUB_PRODUCT_NAME,PRODUCT_STATUS_NAME
            ORDER BY A.PRODUCT_CODE DESC,A.CHANNEL_TYPE,A.DATENO DESC
        END
    END
   -- ELSE
   --    SELECT A.*,CONVERT(NVARCHAR(200),'') AS FULL_NAME FROM #TMP_STAT_CHANNELTOTAL1 A WHERE 1=0
GO
