USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TSTAFFREIMBURSE @IN_BEGIN_DATE        INT,          	--开始日期
										  @IN_END_DATE          INT,            --结束日期
										  @IN_MIN_MONEY			NUMERIC(18,2),	--金额min
										  @IN_MAX_MONEY 		NUMERIC(18,2),	--金额max
										  @IN_REIMBURSE_TYPE    NVARCHAR(10),   --费用类别 
										  @IN_ISNEWCUST         INT, 			--新老客户 0全部， 1是，2否
										  @IN_ASSUME            INT,   			--承担方：1团队承担2部门承担3业务部承担4公司承担
										  @IN_DEVELOPMENT       INT,       		--中长期开拓与维护:0全部， 1是，2否
										  @IN_IS_PRODUCT        INT,           	--信托项目 0全部， 1是，2否
										  @IN_IS_DEPART_ITEM	INT,			--部门级项目0全部， 1是，2否
										  @IN_REIMBURSE_MAN     NVARCHAR(50),	--报销人员
										  @IN_INPUT_MAN			INT             --
WITH ENCRYPTION
AS	
	DECLARE @V_FLAG_ACCESS_ALL INT
	SELECT @V_FLAG_ACCESS_ALL = 0 --访问全部标志

    --如果操作员的角色中存在访问所有报销信息权限的标志 则赋予能够访问所有客户信息权限
    IF EXISTS(SELECT 1 FROM TOPROLE WHERE OP_CODE = @IN_INPUT_MAN AND ROLE_ID = 91)
        SELECT @V_FLAG_ACCESS_ALL = 1

	SELECT DATE,B.TYPE_CONTENT,MONEY,D.OP_NAME,INVOICES,CASE WHEN ISNEWCUST = 1 THEN '新客户' WHEN ISNEWCUST = 2 THEN '老客户' ELSE '' END,
			ISNULL(Y.ITEM_NAME,''), CASE WHEN DEVELOPMENT = 1 THEN '是' WHEN DEVELOPMENT = 2 THEN '否' ELSE '' END,
			ISNULL(Z.PRODUCT_NAME,''),ISNULL(X.ITEM_NAME,''),ISNULL(A.CITY_AREA,'')
		FROM TSTAFFREIMBURSE A LEFT JOIN TPRODUCT Z ON A.PRODUCT_ID = Z.PRODUCT_ID 
			LEFT JOIN CONFIG_REGION Y ON Y.ITEM_CODE = A.ASSUME AND Y.REGION_CODE ='CdDept010' 
			LEFT JOIN DEPTITEM_INFO X ON X.ITEM_ID = A.DEPART_PRODUCT,TDICTPARAM B,TOPERATOR D
		WHERE A.REIMBURSE_TYPE = B.TYPE_VALUE AND A.INPUT_MAN = D.OP_CODE 
			AND (ISNULL(@IN_BEGIN_DATE,'') ='' OR REPLACE(DATE,'-','') >= CONVERT(INT,@IN_BEGIN_DATE))
			AND (ISNULL(@IN_END_DATE,'') ='' OR REPLACE(DATE,'-','') <= CONVERT(INT,@IN_END_DATE))
			AND (ISNULL(MONEY,0) >= @IN_MIN_MONEY OR ISNULL(@IN_MIN_MONEY,0) = 0)
			AND (ISNULL(MONEY,0) <= @IN_MAX_MONEY OR ISNULL(@IN_MAX_MONEY,0) = 0)
			AND	(A.REIMBURSE_TYPE = @IN_REIMBURSE_TYPE OR ISNULL(@IN_REIMBURSE_TYPE,'') = '' OR ISNULL(@IN_REIMBURSE_TYPE,'') = '0')
			AND	(A.ISNEWCUST = @IN_ISNEWCUST OR ISNULL(@IN_ISNEWCUST,0) = 0)
			AND	(A.ASSUME = @IN_ASSUME OR ISNULL(@IN_ASSUME,0) = 0)
			AND	(A.DEVELOPMENT = @IN_DEVELOPMENT OR ISNULL(@IN_DEVELOPMENT,0) = 0)
			AND	((A.PRODUCT_ID > 0 AND @IN_IS_PRODUCT = 1) OR (ISNULL(A.PRODUCT_ID,0) = 0 AND @IN_IS_PRODUCT = 2) OR ISNULL(@IN_IS_PRODUCT,0) = 0)
			AND	(A.DEPART_PRODUCT = @IN_IS_DEPART_ITEM OR ISNULL(@IN_IS_DEPART_ITEM,0) = 0)
			AND	(D.OP_NAME LIKE '%'+@IN_REIMBURSE_MAN+'%' OR @IN_REIMBURSE_MAN IS NULL OR @IN_REIMBURSE_MAN = '')
			AND (A.INPUT_MAN = @IN_INPUT_MAN OR @V_FLAG_ACCESS_ALL = 1
				OR A.INPUT_MAN IN (SELECT B.OP_CODE FROM TOPERATOR A,TOPERATOR B 
									WHERE A.DEPART_ID = B.DEPART_ID  AND  A.OP_CODE = @IN_INPUT_MAN  
									AND EXISTS(SELECT * FROM TOPROLE C WHERE C.ROLE_ID = 102 AND OP_CODE = @IN_INPUT_MAN)))
GO
