USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_CustomerClass2 @IN_CUST_ID    INTEGER,    --客户ID（TCustomers.CUST_ID）
                                         @IN_INPUT_MAN  INTEGER     --操作员
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    SELECT A.*, B.CLASS10, B.CLASS11, B.CLASS12
    FROM TCustomers A, (SELECT CUST_ID,MAX([10]) AS CLASS10, MAX([11]) AS CLASS11, MAX([12]) AS CLASS12
                        FROM TCustomerClass PIVOT(MAX(CLASSDETAIL_NAME) FOR CLASSDEFINE_ID IN ([10],[11],[12])) AS Z
                        WHERE (CUST_ID = @IN_CUST_ID OR @IN_CUST_ID IS NULL OR @IN_CUST_ID = 0)
                        GROUP BY CUST_ID) AS B
    WHERE A.CUST_ID = B.CUST_ID
GO
