USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE  SP_QUERY_TPROJECTS_BYFLAG @IN_INTRUST_FLAG    INTEGER = 0,   --流程类别:  对应TINTEGERPARAM参数: 1002
                                            @IN_PROBLEMS_TYPE   INTEGER = 0,   --事务子类别: 对应TINTEGERPARAM参数: 1005/1007
                                            @IN_BOOK_CODE       INTEGER = 0    --帐套
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    SELECT A.PROBLEMS_TYPE,A.PROJECTID,A.NAME
        FROM INTRUST..TPROJECTS A, INTRUST..TPROJECTSTATES B
            WHERE A.PROJECTSTATEID = B.PROJECTSTATEID AND B.ISCLOSESTATE = 0
                AND (A.INTRUST_FLAG = @IN_INTRUST_FLAG OR ISNULL(@IN_INTRUST_FLAG,0) = 0)
                AND (A.PROBLEMS_TYPE = @IN_PROBLEMS_TYPE
                    OR ISNULL(@IN_PROBLEMS_TYPE,0) = 0
                    OR (ISNULL(@IN_INTRUST_FLAG,0) = 5 AND A.PROBLEMS_TYPE = 99))
                AND A.CHECK_FLAG = 2
                AND (A.BOOK_CODE = @IN_BOOK_CODE OR ISNULL(@IN_BOOK_CODE,0)=0)
GO
