USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_SET_TPREPRODUCT @IN_PRODUCT_ID          INT,            --INTRUST..TPRODUCT.PRODUCT_ID
                                    @IN_PREPRODUCT_NAME     NVARCHAR(60),   --预发行产品名称
                                    @IN_PERIOD              NVARCHAR(500),  --期限
                                    @IN_EXPRE_START_DATE    NVARCHAR(60),   --开始预约日期
                                    @IN_PRE_MONEY           DECIMAL(16,3),  --预募集规模
                                    @IN_PROFIT_DATE         NVARCHAR(4000), --收益分配时间
                                    @IN_PRE_RATE            NTEXT,           --预期收益率
                                    @IN_CASH_USETYPE        NVARCHAR(4000), --资金运用方式
                                    @IN_ENSURE_METHOD       NVARCHAR(4000), --保障措施
                                    @IN_PRE_START_DATE      INT,            --推介开始日期
                                    @IN_PRE_END_DATE        INT,            --推介结束日期
                                    @IN_CLASS_TYPE1         NVARCHAR(10),   --产品分类(1113)
                                    @IN_ADMIN_MANAGER       NVARCHAR(30),   --项目责任人
                                    @IN_DIRECT_SALE         INT,            --1代销 2直销
                                    @IN_ANNOUNCE_URL        NVARCHAR(200),  --信息披露地址
                                    @IN_SUMMARY             NTEXT,          --简介（格式文本）
                                    @IN_KFQ                 NVARCHAR(2000), --开放期
                                    @IN_SHSQTJQ             NVARCHAR(2000), --赎回申请提交期
                                    @IN_SYZH                NVARCHAR(2000), --账户信息
                                    @IN_DXJG                NVARCHAR(2000), --代销机构
                                    @IN_TZGW                NVARCHAR(2000), --投资顾问/受益人代表
                                    @IN_JJJL                NVARCHAR(2000), --基金经理
                                    @IN_KFR                 NVARCHAR(2000), --开放日
                                    @IN_STATUS              NVARCHAR(10),   --状态(1102)
                                    @IN_INPUT_MAN           INT,            --操作员
                                    @IN_START_DATE          INT = NULL,     --产品成立日
                                    @IN_PREPRODUCT_ID       INT OUTPUT,     --预发行产品ID（既输入又输出）
                                    @IN_EXPRE_END_TIME      NVARCHAR(20)=NULL,--预约结束时间，按'2013-10-08 17:00'格式输入
                                    @IN_PRE_VALID_DAYS      INT=0             --预约有效天数,用于预约时控制有效天数，不能大于此处设置的值，当不需要控制时设置为0
                                    
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    SET @IN_PREPRODUCT_ID = ISNULL(@IN_PREPRODUCT_ID,0)
    SET @IN_PRODUCT_ID = ISNULL(@IN_PRODUCT_ID,0)

    DECLARE @V_RET_CODE INT, @IBUSI_FLAG INT, @SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)
    SELECT @V_RET_CODE = -19003000, @IBUSI_FLAG = 19003
    SELECT @SBUSI_NAME = N'设置“crm信息库”产品信息', @SSUMMARY = N'设置“crm信息库”产品信息'

    DECLARE @V_PRODUCT_ID INT, @V_CLASS_TYPE1_NAME NVARCHAR(30), @V_EXTEND_NO INT, @V_CONDITION NVARCHAR(200), @V_PREPRODUCT_ID INT,
            @V_STATUS_NAME NVARCHAR(30)
    SELECT @V_CLASS_TYPE1_NAME = TYPE_CONTENT FROM TDICTPARAM WHERE TYPE_VALUE = @IN_CLASS_TYPE1

    IF EXISTS(SELECT 1 FROM TPREPRODUCT WHERE PREPRODUCT_NAME = @IN_PREPRODUCT_NAME AND PREPRODUCT_ID <> @IN_PREPRODUCT_ID)
        RETURN @V_RET_CODE - 1 --产品名称已存在
    IF EXISTS(SELECT 1 FROM INTRUST..TPRODUCT WHERE PRODUCT_NAME = @IN_PREPRODUCT_NAME)
    BEGIN
        SELECT @V_PRODUCT_ID = PRODUCT_ID FROM INTRUST..TPRODUCT WHERE PRODUCT_NAME = @IN_PREPRODUCT_NAME --业务系统中产品名称已存在自动绑定
        IF @IN_PRODUCT_ID <> 0 AND @IN_PRODUCT_ID <> @V_PRODUCT_ID
            RETURN @V_RET_CODE - 3 --传入产品ID与产品名称不一致
    END
    IF @IN_PREPRODUCT_ID <> 0 AND NOT EXISTS(SELECT 1 FROM TPREPRODUCT WHERE PREPRODUCT_ID = @IN_PREPRODUCT_ID)
        RETURN -20402001 --记录不存在
    IF @IN_PRODUCT_ID <> 0 AND NOT EXISTS(SELECT 1 FROM INTRUST..TPRODUCT WHERE PRODUCT_ID = @IN_PRODUCT_ID)
        RETURN -20402001 --记录不存在

    IF @IN_STATUS IS NULL OR @IN_STATUS = ''
        SELECT @IN_STATUS = STATUS, @V_STATUS_NAME = STATUS_NAME FROM TPREPRODUCT WHERE PREPRODUCT_ID = @IN_PREPRODUCT_ID
    IF @IN_STATUS IS NULL OR @IN_STATUS = ''
        SET @IN_STATUS = '110202'
    SELECT @V_STATUS_NAME = TYPE_CONTENT FROM TDICTPARAM WHERE TYPE_VALUE = @IN_STATUS
    IF @IN_EXPRE_START_DATE='' OR @IN_EXPRE_START_DATE='0' SET @IN_EXPRE_START_DATE=CONVERT(varchar,GETDATE(),120)

    BEGIN TRANSACTION

    IF @IN_PREPRODUCT_ID = 0
    BEGIN
        INSERT INTO TPREPRODUCT(PREPRODUCT_NAME,PERIOD,EXPRE_START_TIME,PRE_MONEY,PROFIT_DATE,PRE_RATE,
                CASH_USETYPE,ENSURE_METHOD,PRE_START_DATE,PRE_END_DATE,CLASS_TYPE1,CLASS_TYPE1_NAME,ADMIN_MANAGER,
                DIRECT_SALE,ANNOUNCE_URL,SUMMARY,INPUT_MAN,INPUT_TIME,BIND_PRODUCT_ID,STATUS,STATUS_NAME,START_DATE,
                EXPRE_END_TIME,PRE_VALID_DAYS)
            VALUES(@IN_PREPRODUCT_NAME,@IN_PERIOD,@IN_EXPRE_START_DATE,@IN_PRE_MONEY,@IN_PROFIT_DATE,@IN_PRE_RATE,
                @IN_CASH_USETYPE,@IN_ENSURE_METHOD,@IN_PRE_START_DATE,@IN_PRE_END_DATE,@IN_CLASS_TYPE1,@V_CLASS_TYPE1_NAME,@IN_ADMIN_MANAGER,
                @IN_DIRECT_SALE,@IN_ANNOUNCE_URL,@IN_SUMMARY,@IN_INPUT_MAN,GETDATE(),@V_PRODUCT_ID,@IN_STATUS,@V_STATUS_NAME,@IN_START_DATE,
                @IN_EXPRE_END_TIME,@IN_PRE_VALID_DAYS)
        IF @@ERROR <> 0
        BEGIN
            ROLLBACK TRANSACTION
            RETURN -100
        END
        SET @V_PREPRODUCT_ID = @@IDENTITY
        SET @IN_PREPRODUCT_ID = @V_PREPRODUCT_ID
    END
    ELSE
    BEGIN
        UPDATE TPREPRODUCT
            SET PREPRODUCT_NAME     = @IN_PREPRODUCT_NAME,
                PERIOD              = @IN_PERIOD,
                EXPRE_START_TIME    = @IN_EXPRE_START_DATE,
                PRE_MONEY           = @IN_PRE_MONEY,
                PROFIT_DATE         = @IN_PROFIT_DATE,
                PRE_RATE            = @IN_PRE_RATE,
                CASH_USETYPE        = @IN_CASH_USETYPE,
                ENSURE_METHOD       = @IN_ENSURE_METHOD,
                PRE_START_DATE      = @IN_PRE_START_DATE,
                PRE_END_DATE        = @IN_PRE_END_DATE,
                CLASS_TYPE1         = @IN_CLASS_TYPE1,
                CLASS_TYPE1_NAME    = @V_CLASS_TYPE1_NAME,
                ADMIN_MANAGER       = @IN_ADMIN_MANAGER,
                DIRECT_SALE         = @IN_DIRECT_SALE,
                ANNOUNCE_URL        = @IN_ANNOUNCE_URL,
                SUMMARY             = @IN_SUMMARY,
                --BIND_PRODUCT_ID     = @V_PRODUCT_ID, --修改预发行产品时，不能改产品的绑定，绑定在"更改绑定"按钮中改
                STATUS              = @IN_STATUS,
                STATUS_NAME         = @V_STATUS_NAME,
                START_DATE          = @IN_START_DATE,
                EXPRE_END_TIME      = @IN_EXPRE_END_TIME,
                PRE_VALID_DAYS      = @IN_PRE_VALID_DAYS
            WHERE PREPRODUCT_ID = @IN_PREPRODUCT_ID
        IF @@ERROR <> 0
        BEGIN
            ROLLBACK TRANSACTION
            RETURN -100
        END
        SET @V_PREPRODUCT_ID = @IN_PREPRODUCT_ID
    END

    --20111229 不控制这些产品要素的条件
    --SELECT @V_CONDITION = 'CLASS_TYPE1='''+@IN_CLASS_TYPE1+''''
    SELECT @V_CONDITION = ''
    IF EXISTS(SELECT 1 FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPREPRODUCT' AND FIELD_NAME = N'开放期' AND CONDITION = @V_CONDITION)
    BEGIN
        SELECT @V_EXTEND_NO = EXTEND_NO FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPREPRODUCT' AND FIELD_NAME = N'开放期' AND CONDITION = @V_CONDITION
        IF EXISTS(SELECT 1 FROM TEXTENDINFO WHERE EXTEND_NO = @V_EXTEND_NO AND KEY_VALUE = @V_PREPRODUCT_ID)
            UPDATE TEXTENDINFO SET EXTEND_VALUE = @IN_KFQ WHERE EXTEND_NO = @V_EXTEND_NO AND KEY_VALUE = @V_PREPRODUCT_ID
        ELSE
            INSERT INTO TEXTENDINFO(EXTEND_NO,KEY_VALUE,EXTEND_VALUE) SELECT @V_EXTEND_NO,@V_PREPRODUCT_ID,@IN_KFQ
        IF @@ERROR <> 0
        BEGIN
            ROLLBACK TRANSACTION
            RETURN -100
        END
    END
    IF EXISTS(SELECT 1 FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPREPRODUCT' AND FIELD_NAME = N'赎回申请提交期' AND CONDITION = @V_CONDITION)
    BEGIN
        SELECT @V_EXTEND_NO = EXTEND_NO FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPREPRODUCT' AND FIELD_NAME = N'赎回申请提交期' AND CONDITION = @V_CONDITION
        IF EXISTS(SELECT 1 FROM TEXTENDINFO WHERE EXTEND_NO = @V_EXTEND_NO AND KEY_VALUE = @V_PREPRODUCT_ID)
            UPDATE TEXTENDINFO SET EXTEND_VALUE = @IN_SHSQTJQ WHERE EXTEND_NO = @V_EXTEND_NO AND KEY_VALUE = @V_PREPRODUCT_ID
        ELSE
            INSERT INTO TEXTENDINFO(EXTEND_NO,KEY_VALUE,EXTEND_VALUE) SELECT @V_EXTEND_NO,@V_PREPRODUCT_ID,@IN_SHSQTJQ
        IF @@ERROR <> 0
        BEGIN
            ROLLBACK TRANSACTION
            RETURN -100
        END
    END
    IF EXISTS(SELECT 1 FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPREPRODUCT' AND FIELD_NAME = N'账户信息' AND CONDITION = @V_CONDITION)
    BEGIN
        SELECT @V_EXTEND_NO = EXTEND_NO FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPREPRODUCT' AND FIELD_NAME = N'账户信息' AND CONDITION = @V_CONDITION
        IF EXISTS(SELECT 1 FROM TEXTENDINFO WHERE EXTEND_NO = @V_EXTEND_NO AND KEY_VALUE = @V_PREPRODUCT_ID)
            UPDATE TEXTENDINFO SET EXTEND_VALUE = @IN_SYZH WHERE EXTEND_NO = @V_EXTEND_NO AND KEY_VALUE = @V_PREPRODUCT_ID
        ELSE
            INSERT INTO TEXTENDINFO(EXTEND_NO,KEY_VALUE,EXTEND_VALUE) SELECT @V_EXTEND_NO,@V_PREPRODUCT_ID,@IN_SYZH
        IF @@ERROR <> 0
        BEGIN
            ROLLBACK TRANSACTION
            RETURN -100
        END
    END
    IF EXISTS(SELECT 1 FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPREPRODUCT' AND FIELD_NAME = N'代销机构' AND CONDITION = @V_CONDITION)
    BEGIN
        SELECT @V_EXTEND_NO = EXTEND_NO FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPREPRODUCT' AND FIELD_NAME = N'代销机构' AND CONDITION = @V_CONDITION
        IF EXISTS(SELECT 1 FROM TEXTENDINFO WHERE EXTEND_NO = @V_EXTEND_NO AND KEY_VALUE = @V_PREPRODUCT_ID)
            UPDATE TEXTENDINFO SET EXTEND_VALUE = @IN_DXJG WHERE EXTEND_NO = @V_EXTEND_NO AND KEY_VALUE = @V_PREPRODUCT_ID
        ELSE
            INSERT INTO TEXTENDINFO(EXTEND_NO,KEY_VALUE,EXTEND_VALUE) SELECT @V_EXTEND_NO,@V_PREPRODUCT_ID,@IN_DXJG
        IF @@ERROR <> 0
        BEGIN
            ROLLBACK TRANSACTION
            RETURN -100
        END
    END
    IF EXISTS(SELECT 1 FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPREPRODUCT' AND FIELD_NAME = N'投资顾问/受益人代表' AND CONDITION = @V_CONDITION)
    BEGIN
        SELECT @V_EXTEND_NO = EXTEND_NO FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPREPRODUCT' AND FIELD_NAME = N'投资顾问/受益人代表' AND CONDITION = @V_CONDITION
        IF EXISTS(SELECT 1 FROM TEXTENDINFO WHERE EXTEND_NO = @V_EXTEND_NO AND KEY_VALUE = @V_PREPRODUCT_ID)
            UPDATE TEXTENDINFO SET EXTEND_VALUE = @IN_TZGW WHERE EXTEND_NO = @V_EXTEND_NO AND KEY_VALUE = @V_PREPRODUCT_ID
        ELSE
            INSERT INTO TEXTENDINFO(EXTEND_NO,KEY_VALUE,EXTEND_VALUE) SELECT @V_EXTEND_NO,@V_PREPRODUCT_ID,@IN_TZGW
        IF @@ERROR <> 0
        BEGIN
            ROLLBACK TRANSACTION
            RETURN -100
        END
    END
    IF EXISTS(SELECT 1 FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPREPRODUCT' AND FIELD_NAME = N'基金经理' AND CONDITION = @V_CONDITION)
    BEGIN
        SELECT @V_EXTEND_NO = EXTEND_NO FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPREPRODUCT' AND FIELD_NAME = N'基金经理' AND CONDITION = @V_CONDITION
        IF EXISTS(SELECT 1 FROM TEXTENDINFO WHERE EXTEND_NO = @V_EXTEND_NO AND KEY_VALUE = @V_PREPRODUCT_ID)
            UPDATE TEXTENDINFO SET EXTEND_VALUE = @IN_JJJL WHERE EXTEND_NO = @V_EXTEND_NO AND KEY_VALUE = @V_PREPRODUCT_ID
        ELSE
            INSERT INTO TEXTENDINFO(EXTEND_NO,KEY_VALUE,EXTEND_VALUE) SELECT @V_EXTEND_NO,@V_PREPRODUCT_ID,@IN_JJJL
        IF @@ERROR <> 0
        BEGIN
            ROLLBACK TRANSACTION
            RETURN -100
        END
    END
    IF EXISTS(SELECT 1 FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPREPRODUCT' AND FIELD_NAME = N'开放日' AND CONDITION = @V_CONDITION)
    BEGIN
        SELECT @V_EXTEND_NO = EXTEND_NO FROM TEXTENDDEFINE WHERE TABLE_NAME = 'TPREPRODUCT' AND FIELD_NAME = N'开放日' AND CONDITION = @V_CONDITION
        IF EXISTS(SELECT 1 FROM TEXTENDINFO WHERE EXTEND_NO = @V_EXTEND_NO AND KEY_VALUE = @V_PREPRODUCT_ID)
            UPDATE TEXTENDINFO SET EXTEND_VALUE = @IN_KFR WHERE EXTEND_NO = @V_EXTEND_NO AND KEY_VALUE = @V_PREPRODUCT_ID
        ELSE
            INSERT INTO TEXTENDINFO(EXTEND_NO,KEY_VALUE,EXTEND_VALUE) SELECT @V_EXTEND_NO,@V_PREPRODUCT_ID,@IN_KFR
        IF @@ERROR <> 0
        BEGIN
            ROLLBACK TRANSACTION
            RETURN -100
        END
    END

    SELECT @SSUMMARY = N'设置“crm信息库”产品信息'
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
