USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TFUNCTYPE @IN_FUNC_ID INT,
                                    @IN_MENU_ID NVARCHAR (10)
WITH ENCRYPTION
AS
    DECLARE @V_USER_ID INT
    SELECT @V_USER_ID = USER_ID FROM TSYSTEMINFO
    SELECT * FROM TFUNCTYPE
        WHERE ((FUNC_ID = @IN_FUNC_ID) OR (@IN_FUNC_ID = 0) OR (@IN_FUNC_ID IS NULL))
            AND MENU_ID = @IN_MENU_ID
            AND (USER_ID = @V_USER_ID OR USER_ID = 0)
GO
