USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_DEL_TCOMMISSIONRATE @IN_PRODUCT_ID     INT,    
                                        @IN_SUB_PRODUCT_ID INT,
                                        @IN_INPUT_MAN      INT     --操作员

WITH ENCRYPTION
AS
    DELETE FROM TCOMMISSIONRATE 
      WHERE PRODUCT_ID = @IN_PRODUCT_ID AND ISNULL(SUBPRODUCT_ID,0)=ISNULL(@IN_SUB_PRODUCT_ID,0)
GO
