USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_CONTRACT_FOR_2ND_EDIT @IN_BOOK_CODE           INTEGER,                --账套
                                                @IN_CONTRACT_TYPE       INTEGER  = 0,           -- 1:认购合同；2:申购合同；3:全部
                                                @IN_SERIAL_NO           INTEGER  = 0,                                                                 
                                                @IN_PRODUCT_ID          INTEGER  = 0,           --产品ID
                                                @IN_PRODUCT_CODE        NVARCHAR(6) = '',       --产品编号
                                                @IN_PRODUCT_NAME        NVARCHAR(60)  = '',     --产品名称
                                                @IN_CONTRACT_SUB_BH     NVARCHAR(50)  = '',     --合同编号查询  
                                                @IN_CUST_NAME			NVARCHAR(60)  = '',     --客户名称
                                                @IN_INPUT_MAN           INTEGER                 --操作员
WITH ENCRYPTION
AS
    --20409: The Products can be accessed. START
    DECLARE @V_SW20409 INT
    SELECT @V_SW20409 = VALUE FROM INTRUST..TSYSCONTROL WHERE FLAG_TYPE = 'SW20409'
    DECLARE @V_PRODUCTS TABLE(PRODUCT_ID INT)
    DECLARE @V_PRODUCTS2 TABLE(PRODUCT_ID INT)
    IF @V_SW20409 = 1
        INSERT INTO @V_PRODUCTS
            SELECT PRODUCT_ID 
              FROM INTRUST..TPRODUCT 
              WHERE BOOK_CODE = @IN_BOOK_CODE
                AND(INTRUST_FLAG1 IN ( SELECT FUNC_ID-2040900 FROM INTRUST..TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID > 2040900 AND FUNC_ID <= 2040902 AND OP_CODE = @IN_INPUT_MAN )
                OR DEPART_ID IN (SELECT B.DEPART_ID FROM INTRUST..TOPRIGHT A,INTRUST..TOPERATOR B WHERE A.OP_CODE = B.OP_CODE AND A.MENU_ID = '20409' AND A.FUNC_ID = 2040903 AND A.OP_CODE = @IN_INPUT_MAN)
                OR PRODUCT_ID IN ( SELECT FUNC_ID FROM INTRUST..TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID < 2040900 AND OP_CODE = @IN_INPUT_MAN)
                OR ADMIN_MANAGER = @IN_INPUT_MAN OR INPUT_MAN = @IN_INPUT_MAN OR ISNULL(@IN_INPUT_MAN,0)=0  
                OR SUB_MAN = @IN_INPUT_MAN OR SUB_MAN2 = @IN_INPUT_MAN
                OR CASH_MAN = @IN_INPUT_MAN OR CASH_MAN2 = @IN_INPUT_MAN
				OR ADMIN_MANAGER IN(SELECT OP_CODE FROM INTRUST..TOPCUSTRIGHT WHERE ENABLE_OP_CODE = @IN_INPUT_MAN))
    --20409: The Products can be accessed. END
    
    --20409: The Products can be accessed. START
    IF @V_SW20409 = 1
        INSERT INTO @V_PRODUCTS2
            SELECT PRODUCT_ID FROM INTRUST..TPRODUCT WHERE BOOK_CODE = @IN_BOOK_CODE
                AND(INTRUST_FLAG1 IN ( SELECT FUNC_ID-2040900 FROM INTRUST..TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID > 2040900 AND FUNC_ID <= 2040999 AND OP_CODE = @IN_INPUT_MAN )
                    OR PRODUCT_ID IN ( SELECT FUNC_ID FROM INTRUST..TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID < 2040900 AND OP_CODE = @IN_INPUT_MAN)
                    OR ADMIN_MANAGER = @IN_INPUT_MAN OR INPUT_MAN = @IN_INPUT_MAN OR ISNULL(@IN_INPUT_MAN,0)=0
                    OR ADMIN_MANAGER IN(SELECT OP_CODE FROM INTRUST..TOPCUSTRIGHT WHERE ENABLE_OP_CODE = @IN_INPUT_MAN))
    --20409: The Products can be accessed. END
    
 
    SELECT 2 CONTRACT_TYPE,
           A.BANK_ACCT,A.BANK_ACCT_TYPE,A.BANK_CITY,A.BANK_CITY_NAME,A.BANK_ID,A.BANK_NAME,A.BANK_PROVINCE,A.BANK_PROVINCE_NAME,A.BANK_SUB_NAME,
            A.BONUS_FLAG,A.BONUS_RATE,A.BOOK_CODE,A.BZJ_FLAG,A.CHANNEL_COOPERTYPE,A.CHANNEL_COOPERTYPE_NAME,A.CHANNEL_ID,A.CHANNEL_MEMO,A.CHANNEL_TYPE,
            A.CITY_NAME,A.CITY_SERIAL_NO,A.CONTACT_ID,A.CONTRACT_BH,A.CONTRACT_SUB_BH,A.SG_MONEY AS MONEY,
            A.CURRENCY_ID,A.CUST_ID,A.END_DATE,A.EXPECT_ROR_LOWER,A.EXPECT_ROR_UPPER,A.FEE_JK_TYPE,A.GAIN_ACCT,A.HT_BANK_ID,A.HT_BANK_NAME,
            A.HT_BANK_SUB_NAME,A.HT_STATUS,A.HT_STATUS_NAME,A.INPUT_MAN,A.INPUT_TIME,A.JK_DATE,A.JK_STATUS,A.JK_TOTAL_MONEY,A.JK_TYPE,A.JK_TYPE_NAME,
            A.LINK_MAN,A.MARKET_MONEY,A.MODI_MAN,A.MODI_TIME,A.ORIGINAL_END_DATE,A.PERIOD_UNIT,A.PRODUCT_CODE,A.PRODUCT_ID,A.PRODUCT_NAME,A.PROV_FLAG,
            A.PROV_LEVEL,A.PROV_LEVEL_NAME,A.QS_DATE,A.RECOMMEND_MAN,A.RECOMMEND_MAN_NAME,A.SALE_CON_FLAG,A.SERIAL_NO,A.SERVICE_MAN,A.START_DATE,
            A.SUB_PRODUCT_ID,A.SUBMIT_FLAG,A.SUMMARY,A.TA_ACCOUNT_ID,A.TA_FLAG,A.TERMINATE_DATE,A.TO_AMOUNT,A.TO_MONEY,A.TOUCH_TYPE,A.TOUCH_TYPE_NAME,
            A.TRADE_ACCOUNT_ID,A.VALID_PERIOD,A.WITH_BANK_FLAG,A.WITH_PRIVATE_FLAG,A.WITH_SECURITY_FLAG,A.ZJ_CHECK_FLAG,A.ZJ_CHECK_MAN,A.ZJ_CHECK_TIME,
           B.CUST_NO,B.CUST_NAME,ISNULL(D.MIN_BUY_LIMIT,0) AS MIN_BUY_LIMIT,ISNULL(D.MAX_BUY_LIMIT,0) AS MAX_BUY_LIMIT,
           D.LIST_ID,D.LIST_NAME,D.LIST_NAME AS SUB_PRODUCT_NAME,E.TYPE_CONTENT AS CHANNEL_TYPE_NAME,F.CHANNEL_NAME,
           B.CARD_ID,B.MOBILE,B.POST_ADDRESS,B.JG_WTRLX2,C.IS_LOCAL AS PRODUCT_FROM 
        FROM INTRUST..TCONTRACTSG A LEFT JOIN INTRUST..TSUBPRODUCT D ON A.SUB_PRODUCT_ID = D.SUB_PRODUCT_ID
                           LEFT JOIN INTRUST..TDICTPARAM E ON A.CHANNEL_TYPE = E.TYPE_VALUE 
                           LEFT JOIN INTRUST..TCHANNEL F ON A.CHANNEL_ID = F.CHANNEL_ID, 
             INTRUST..TCUSTOMERINFO B, INTRUST..TPRODUCT C
        WHERE A.CUST_ID = B.CUST_ID AND A.PRODUCT_ID = C.PRODUCT_ID
            AND (ISNULL(@IN_CONTRACT_TYPE,0)=0 OR @IN_CONTRACT_TYPE=2)
            AND (ISNULL(@IN_SERIAL_NO,0)=0 OR @IN_SERIAL_NO=A.SERIAL_NO)
            AND (A.PRODUCT_ID = @IN_PRODUCT_ID OR ISNULL(@IN_PRODUCT_ID,0) = 0)
            AND (A.PRODUCT_CODE = @IN_PRODUCT_CODE OR ISNULL(@IN_PRODUCT_CODE,'') = '')
            AND (B.CUST_NAME LIKE '%'+@IN_CUST_NAME+'%' OR ISNULL(@IN_CUST_NAME,'') = '')
            AND (A.CONTRACT_SUB_BH = '%'+@IN_CONTRACT_SUB_BH+'%' OR ISNULL(@IN_CONTRACT_SUB_BH,'') = '')
            AND A.CHECK_FLAG=1
            AND (@V_SW20409 = 0 OR @V_SW20409 IS NULL OR A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCTS))
            AND (C.PRODUCT_NAME LIKE '%'+@IN_PRODUCT_NAME+'%' OR @IN_PRODUCT_NAME IS NULL OR @IN_PRODUCT_NAME='')
            AND (C.INTRUST_FLAG1 = 2 OR (C.INTRUST_FLAG1 = 1 AND A.JK_TYPE = '111450'))
    UNION     
    SELECT 1 CONTRACT_TYPE, 
           A.BANK_ACCT,A.BANK_ACCT_TYPE,A.BANK_CITY,A.BANK_CITY_NAME,A.BANK_ID,A.BANK_NAME,A.BANK_PROVINCE,A.BANK_PROVINCE_NAME,A.BANK_SUB_NAME,
            A.BONUS_FLAG,A.BONUS_RATE,A.BOOK_CODE,A.BZJ_FLAG,A.CHANNEL_COOPERTYPE,A.CHANNEL_COOPERTYPE_NAME,A.CHANNEL_ID,A.CHANNEL_MEMO,A.CHANNEL_TYPE,
            A.CITY_NAME,A.CITY_SERIAL_NO,A.CONTACT_ID,A.CONTRACT_BH,A.CONTRACT_SUB_BH,A.RG_MONEY AS MONEY,
            A.CURRENCY_ID,A.CUST_ID,A.END_DATE,A.EXPECT_ROR_LOWER,A.EXPECT_ROR_UPPER,A.FEE_JK_TYPE,A.GAIN_ACCT,A.HT_BANK_ID,A.HT_BANK_NAME,
            A.HT_BANK_SUB_NAME,A.HT_STATUS,A.HT_STATUS_NAME,A.INPUT_MAN,A.INPUT_TIME,A.JK_DATE,A.JK_STATUS,A.JK_TOTAL_MONEY,A.JK_TYPE,A.JK_TYPE_NAME,
            A.LINK_MAN,A.MARKET_MONEY,A.MODI_MAN,A.MODI_TIME,A.ORIGINAL_END_DATE,A.PERIOD_UNIT,A.PRODUCT_CODE,A.PRODUCT_ID,A.PRODUCT_NAME,A.PROV_FLAG,
            A.PROV_LEVEL,A.PROV_LEVEL_NAME,A.QS_DATE,A.RECOMMEND_MAN,A.RECOMMEND_MAN_NAME,A.SALE_CON_FLAG,A.SERIAL_NO,A.SERVICE_MAN,A.START_DATE,
            A.SUB_PRODUCT_ID,A.SUBMIT_FLAG,A.SUMMARY,A.TA_ACCOUNT_ID,A.TA_FLAG,A.TERMINATE_DATE,A.TO_AMOUNT,A.TO_MONEY,A.TOUCH_TYPE,A.TOUCH_TYPE_NAME,
            A.TRADE_ACCOUNT_ID,A.VALID_PERIOD,A.WITH_BANK_FLAG,A.WITH_PRIVATE_FLAG,A.WITH_SECURITY_FLAG,A.ZJ_CHECK_FLAG,A.ZJ_CHECK_MAN,A.ZJ_CHECK_TIME,
           B.CUST_NO,B.CUST_NAME,ISNULL(D.MIN_BUY_LIMIT,0) AS MIN_BUY_LIMIT,ISNULL(D.MAX_BUY_LIMIT,0) AS MAX_BUY_LIMIT,--dbo.ENCRYPTCUSTINFO(B.SERVICE_MAN,@IN_INPUT_MAN,B.CARD_ID) AS CARD_ID,
           D.LIST_ID,D.LIST_NAME, D.LIST_NAME AS SUB_PRODUCT_NAME,H.CHANNEL_TYPE_NAME,H.CHANNEL_NAME,
           B.CARD_ID,B.MOBILE,B.POST_ADDRESS,B.JG_WTRLX2, C.IS_LOCAL AS PRODUCT_FROM 
        FROM INTRUST..TCONTRACT A LEFT JOIN INTRUST..TSUBPRODUCT D ON A.SUB_PRODUCT_ID = D.SUB_PRODUCT_ID
             LEFT JOIN INTRUST..TCHANNEL H ON A.CHANNEL_ID = H.CHANNEL_ID AND A.CHANNEL_TYPE = H.CHANNEL_TYPE,
             INTRUST..TCUSTOMERINFO B, INTRUST..TPRODUCT C
        WHERE A.CUST_ID = B.CUST_ID AND A.PRODUCT_ID = C.PRODUCT_ID AND A.BOOK_CODE  = @IN_BOOK_CODE AND A.HT_STATUS <>'120104'
            AND (ISNULL(@IN_CONTRACT_TYPE,0)=0 OR @IN_CONTRACT_TYPE=1)
            AND (ISNULL(@IN_SERIAL_NO,0)=0 OR @IN_SERIAL_NO=A.SERIAL_NO)
            AND (A.CONTRACT_SUB_BH LIKE '%'+@IN_CONTRACT_SUB_BH+'%' OR ISNULL(@IN_CONTRACT_SUB_BH,'') = '')
            AND (A.PRODUCT_CODE = @IN_PRODUCT_CODE OR ISNULL(@IN_PRODUCT_CODE,'') = '')
            AND A.CHECK_FLAG = 1
            AND (A.PRODUCT_ID = @IN_PRODUCT_ID OR ISNULL(@IN_PRODUCT_ID,0) = 0)
            AND (A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM INTRUST..TPRODUCT WHERE (PRODUCT_STATUS = '110202' OR (PRODUCT_STATUS = '110203' AND  FPRG_FLAG =1)) AND (INTRUST_TYPE1 = '113801'OR INTRUST_TYPE1 = '113804')))
            AND (@V_SW20409 = 0 OR @V_SW20409 IS NULL OR A.PRODUCT_ID IN (SELECT PRODUCT_ID FROM @V_PRODUCTS2))
            AND (C.PRODUCT_NAME LIKE '%'+@IN_PRODUCT_NAME+'%' OR @IN_PRODUCT_NAME IS NULL OR @IN_PRODUCT_NAME='')
			AND (B.CUST_NAME LIKE '%'+@IN_CUST_NAME+'%' OR @IN_CUST_NAME IS NULL OR @IN_CUST_NAME='') 
    ORDER BY CONTRACT_TYPE, A.PRODUCT_ID,A.SUB_PRODUCT_ID,A.CONTRACT_SUB_BH
    
GO
