USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_STAT_TPRECONTRACT @IN_PREPRODUCT_ID     INT,            --预发行产品ID
                                      @IN_PREPRODUCT_NAME   NVARCHAR(200),  --预发行产品名称
                                      @IN_STATUS            NVARCHAR(10),   --产品状态(1102)
                                      @IN_INPUT_MAN         INT
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    SET @IN_PREPRODUCT_ID = ISNULL(@IN_PREPRODUCT_ID,0)
    SET @IN_PREPRODUCT_NAME = ISNULL(@IN_PREPRODUCT_NAME,'')
    SET @IN_STATUS = ISNULL(@IN_STATUS,'')

    --各产品的在途金额汇总
    SELECT A.PREPRODUCT_ID,SUM(B.DZ_MONEY) ONWAY_MONEY INTO #T_ONWAY_MONEY FROM TPRECONTRACT A LEFT JOIN TPREMONEYDETAIL B ON A.SERIAL_NO=B.PRE_SERIAL_NO
		WHERE ISNULL(B.ONWAY_FLAG,0)=1 AND A.PRODUCT_ID=0
		GROUP BY A.PREPRODUCT_ID
    --预约合同中的收益率
    SELECT *, DBO.GETGAINRATE(0,PREPRODUCT_ID,1,DZ_MONEY) GAINRATE INTO #T_TPRECONTRACT_GAINRATE
		FROM (SELECT A.PREPRODUCT_ID,A.SERIAL_NO TPRECONTRACT_SERIAL,SUM(ISNULL(B.DZ_MONEY,0)) DZ_MONEY FROM TPRECONTRACT A LEFT JOIN TPREMONEYDETAIL B ON A.SERIAL_NO=B.PRE_SERIAL_NO GROUP BY A.PREPRODUCT_ID,A.SERIAL_NO) A
	
    SELECT B.PREPRODUCT_ID, B.BIND_PRODUCT_ID, B.PREPRODUCT_NAME, B.PRE_START_DATE, B.PRE_END_DATE, B.PERIOD, B.DIRECT_SALE ,B.PRE_MONEY,
           A.PRE_FACT_MONEY,A.RG_MONEY,B.CLASS_TYPE1, B.CLASS_TYPE1_NAME, B.STATUS, B.STATUS_NAME,C.MAX_RATIO,
           A.LESS300_NUMBER,A.TOTAL_COUNT,A.VALID_COUNT,A.HUGE_COUNT,A.HUGE_VALID_COUNT,T.ONWAY_MONEY,
           CASE ISNULL(U.DZ_MONEY,0) WHEN 0 THEN 0 ELSE 100*U.GAINRATE/U.DZ_MONEY END SELL_COST
        FROM TPREPRODUCT B
             LEFT JOIN (SELECT PREPRODUCT_ID, SUM(PRE_MONEY) AS PRE_FACT_MONEY, SUM(RG_MONEY) AS RG_MONEY, SUM(RECORD_VALUE) AS TOTAL_COUNT, SUM(VALID_VALUE) AS VALID_COUNT, SUM(HUGE_VALUE) AS HUGE_COUNT, SUM(HUGE_VALID_VALUE) AS HUGE_VALID_COUNT, SUM(LESS300_VALUE) AS LESS300_NUMBER
                        FROM (SELECT A.PREPRODUCT_ID, A.PRE_MONEY, A.RG_MONEY, 1 AS RECORD_VALUE,
                                     CASE WHEN A.PRE_STATUS IN ('111301','111302') THEN 1 ELSE 0 END AS VALID_VALUE,
                                     CASE WHEN A.PRE_STATUS IN ('111301','111302') AND A.PRE_MONEY>ISNULL(B.HUGE_MONEY,5000000) THEN 1 ELSE 0 END AS HUGE_VALID_VALUE,
                                     CASE WHEN A.PRE_MONEY>ISNULL(B.HUGE_MONEY,5000000) THEN 1 ELSE 0 END AS HUGE_VALUE,
                                     CASE WHEN A.PRE_STATUS IN ('111301','111302') AND A.PRE_MONEY < 3000000 AND C.CUST_TYPE = 1
										THEN 1 ELSE 0 END AS LESS300_VALUE
                                FROM TPRECONTRACT A, TPREPRODUCT B,TCUSTOMERS C
                                WHERE A.PREPRODUCT_ID = B.PREPRODUCT_ID AND A.PRE_STATUS IN ('111301','111302') AND A.CUST_ID = C.CUST_ID ) Z
                        GROUP BY PREPRODUCT_ID ) A ON B.PREPRODUCT_ID = A.PREPRODUCT_ID
             LEFT JOIN (SELECT PREPRODUCT_ID,MAX(CASE WHEN QUOTAMONEY=0 THEN 0 ELSE PRE_SALEMONEY/QUOTAMONEY END) AS MAX_RATIO FROM TTEAMQUOTA GROUP BY PREPRODUCT_ID)C ON B.PREPRODUCT_ID = C.PREPRODUCT_ID
             LEFT JOIN #T_ONWAY_MONEY T ON T.PREPRODUCT_ID=B.PREPRODUCT_ID
             LEFT JOIN (SELECT PREPRODUCT_ID,SUM(DZ_MONEY*GAINRATE) GAINRATE,SUM(DZ_MONEY) DZ_MONEY FROM #T_TPRECONTRACT_GAINRATE GROUP BY PREPRODUCT_ID) U ON U.PREPRODUCT_ID=A.PREPRODUCT_ID
        WHERE (B.PREPRODUCT_ID = @IN_PREPRODUCT_ID OR @IN_PREPRODUCT_ID = 0)
            AND(B.PREPRODUCT_NAME LIKE '%'+@IN_PREPRODUCT_NAME+'%')
            AND(B.STATUS = @IN_STATUS OR @IN_STATUS = '')
GO
