USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_PORTALMENU1 @IN_INPUT_MAN     NVARCHAR(60),
                                      @IN_LANGUAGE_FLAG NVARCHAR(10) = ''
WITH ENCRYPTION
AS
    SET NOCOUNT ON

    DECLARE @V_USER_ID INT
    SELECT @V_USER_ID = USER_ID FROM TSYSTEMINFO
    DECLARE @V_TMP_MENU_RIGHT TABLE
    (
        OP_CODE     INT,
        MENU_ID     NVARCHAR (20) NOT NULL ,
        MENU_NAME   NVARCHAR (400) NOT NULL ,
        MENU_INFO   NVARCHAR (2000),
        PARENT_ID   NVARCHAR (20),
        BOTTOM_FLAG INTEGER NOT NULL,
        URL         NVARCHAR(1000),
        TREE_ORDER  NVARCHAR(10),  --排序依据字段
        ICON_CLS    NVARCHAR(200)
    )
    DECLARE @V_TEMPRIGHT TABLE(MENU_ID NVARCHAR(20))
    INSERT INTO @V_TEMPRIGHT SELECT MENU_ID FROM TROLERIGHT
    WHERE ROLE_ID IN(SELECT ROLE_ID FROM TOPROLE WHERE OP_CODE = @IN_INPUT_MAN)
    GROUP BY MENU_ID

    --插入操作员有权限的菜单，并过滤
    IF EXISTS(SELECT * FROM TSYSTEMINFO WHERE INIT_FLAG = 1)
        INSERT INTO @V_TMP_MENU_RIGHT
            SELECT @IN_INPUT_MAN, B.MENU_ID,B.MENU_NAME,B.MENU_INFO,B.PARENT_ID, B.BOTTOM_FLAG, B.URL, B.TREE_ORDER, B.ICON_CLS
                FROM @V_TEMPRIGHT A, TMENUINFO B
                WHERE A.MENU_ID = B.MENU_ID
                    AND (B.USER_ID = @V_USER_ID OR B.USER_ID = 0)
    ELSE
        INSERT INTO @V_TMP_MENU_RIGHT
            SELECT @IN_INPUT_MAN, B.MENU_ID,B.MENU_NAME,B.MENU_INFO,B.PARENT_ID, B.BOTTOM_FLAG, B.URL, B.TREE_ORDER, B.ICON_CLS
                FROM @V_TEMPRIGHT A, TMENUINFO B
                WHERE A.MENU_ID = B.MENU_ID
                    AND B.MENU_ID NOT IN ('10104', '20409') AND (B.USER_ID = @V_USER_ID OR B.USER_ID = 0)
    UPDATE @V_TMP_MENU_RIGHT SET PARENT_ID = '' WHERE PARENT_ID = 'M00'
    DELETE FROM @V_TMP_MENU_RIGHT WHERE MENU_ID = 'P0001'
    IF ISNULL(@IN_LANGUAGE_FLAG,'')='en'
    BEGIN
        UPDATE @V_TMP_MENU_RIGHT SET MENU_NAME = ISNULL(B.MENU_NAME,A.MENU_NAME), MENU_INFO = ISNULL(B.MENU_INFO,A.MENU_INFO)
            FROM @V_TMP_MENU_RIGHT A, TMENUINFO B
            WHERE A.MENU_ID = B.MENU_ID
    END
    --快捷功能项
    INSERT INTO @V_TMP_MENU_RIGHT
        SELECT @IN_INPUT_MAN, A.MENU_ID+CONVERT(NVARCHAR(10),B.FUNC_ID), B.FUNC_NAME,'',A.MENU_ID,1,B.URL,A.TREE_ORDER,B.ICON_CLS
            FROM @V_TMP_MENU_RIGHT A, TFUNCTYPE B
            WHERE A.MENU_ID = B.MENU_ID AND A.MENU_ID LIKE 'M%'

    SELECT MENU_ID,MENU_ID AS MENU_CODE,MENU_NAME,URL AS PATH,ICON_CLS
        FROM @V_TMP_MENU_RIGHT
        WHERE PARENT_ID <> ''
            --指定门户常用功能项
            AND MENU_ID IN ('10105','10303','M0001100','W0101')
        ORDER BY MENU_ID
    RETURN @@ROWCOUNT
GO
