USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TROLERIGHT @IN_ROLE_ID INT
WITH ENCRYPTION
AS
    DECLARE @V_USER_ID INT
    SELECT @V_USER_ID = USER_ID FROM TSYSTEMINFO
    SELECT * FROM TROLERIGHT
        WHERE (ROLE_ID = @IN_ROLE_ID OR @IN_ROLE_ID IS NULL OR @IN_ROLE_ID =0)
            AND (MENU_ID IN (SELECT MENU_ID FROM TMENUINFO WHERE USER_ID = @V_USER_ID OR USER_ID = 0))
            AND (FUNC_ID IN (SELECT FUNC_ID FROM TFUNCTYPE WHERE USER_ID = @V_USER_ID OR USER_ID = 0))
        ORDER BY MENU_ID,FUNC_ID
GO
