USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TPRODUCT_PRE 
                                   @IN_SALE_STATUS    INT,
                                   @IN_PRODUCT_STATUS NVARCHAR(10),
                                   @IN_INPUT_MAN      INT
WITH ENCRYPTION
AS
    DECLARE @V_DT_INTRUST INT,@V_SINGLE INT,@V_USER_ID INT
    SELECT @V_DT_INTRUST = VALUE FROM TSYSCONTROL WHERE FLAG_TYPE = N'DT_INTRUST'
    SELECT @V_SINGLE = VALUE FROM TSYSCONTROL WHERE FLAG_TYPE = 'SINGLE'
    SELECT @V_SINGLE = ISNULL(@V_SINGLE,0)
    SELECT @V_USER_ID=USER_ID FROM TSYSTEMINFO
    
    IF @V_USER_ID=15 --建信因为不设置产品销售信息，单独处理
    BEGIN
		SELECT 0 PREPRODUCT_ID,A.PRODUCT_ID,A.PRODUCT_CODE,A.PRODUCT_NAME,A.PRODUCT_JC,A.PRE_MAX_MONEY,A.PRE_MAX_NUM,A.PRE_START_DATE,A.PRE_END_DATE
			FROM INTRUST..TPRODUCT A
        WHERE A.BOOK_CODE  = 1
            AND (A.PRODUCT_STATUS = '110202' OR (A.PRODUCT_STATUS = '110203' AND A.FPRG_FLAG = 1) )--推介期产品，或者分批募集产品
            AND A.INTRUST_FLAG1 = 2 --集合产品
            AND A.CHECK_FLAG = 2 --产品已审核
		RETURN
    END
    IF @IN_PRODUCT_STATUS='0' --所有预约期、正常期的产品
    BEGIN
		SELECT PREPRODUCT_ID,0 PRODUCT_ID,'' PRODUCT_CODE,PREPRODUCT_NAME AS PRODUCT_NAME,'' PRODUCT_JC,PRE_MONEY, 0 PRE_MAX_NUM, PRE_START_DATE, PRE_END_DATE,
				0 RISK_LEVEL,0 SALE_STATUS
			FROM TPREPRODUCT 
			WHERE ISNULL(BIND_PRODUCT_ID,0)=0 --未绑定的产品
				  AND PRE_STATUS =1
		UNION ALL
		SELECT 0 PREPRODUCT_ID,A.PRODUCT_ID,A.PRODUCT_CODE,A.PRODUCT_NAME,A.PRODUCT_JC,A.PRE_MAX_MONEY,A.PRE_MAX_NUM,A.PRE_START_DATE,A.PRE_END_DATE,
                B.RISK_LEVEL,B.SALE_STATUS 
			FROM INTRUST..TPRODUCT A LEFT JOIN TPRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
			WHERE A.BOOK_CODE  = 1
				AND (PRODUCT_STATUS = '110202' OR A.PRODUCT_STATUS = '110203')
				AND (((B.SALE_STATUS = @IN_SALE_STATUS OR ISNULL(@IN_SALE_STATUS,0) = 0)AND(A.INTRUST_FLAG1 = 2)) OR (A.INTRUST_FLAG1 = 1) )
				AND A.CHECK_FLAG = 2 AND ((A.INTRUST_FLAG1 = 2 AND @V_SINGLE = 0) OR (@V_SINGLE = 1))
				AND B.PRE_STATUS=1
		ORDER BY PREPRODUCT_ID DESC,PRODUCT_ID DESC
		RETURN
    END

    SELECT 0 PREPRODUCT_ID,A.PRODUCT_ID,A.PRODUCT_CODE,A.PRODUCT_NAME,A.PRODUCT_JC,A.PRE_MAX_MONEY,A.PRE_MAX_NUM,A.PRE_START_DATE,A.PRE_END_DATE,
            B.RISK_LEVEL,B.SALE_STATUS 
        FROM INTRUST..TPRODUCT A LEFT JOIN TPRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
        WHERE A.BOOK_CODE  = 1
            --产品在推介期，或者正常期在分批募集中
            --AND (A.PRODUCT_STATUS = '110202' OR (A.PRODUCT_STATUS = '110203' AND A.FPRG_FLAG = 1 AND EXISTS (SELECT * FROM INTRUST..TBATCH_RAISE WHERE PRODUCT_ID=A.PRODUCT_ID AND BATCH_START IN(1,2))) )
            AND (A.PRODUCT_STATUS = '110202' OR (A.PRODUCT_STATUS = '110203' AND A.FPRG_FLAG = 1) )--推介期产品，或者分批募集产品
            AND (((B.SALE_STATUS = @IN_SALE_STATUS OR ISNULL(@IN_SALE_STATUS,0) = 0)AND(A.INTRUST_FLAG1 = 2)) OR (A.INTRUST_FLAG1 = 1) )
            AND A.CHECK_FLAG = 2 AND ((A.INTRUST_FLAG1 = 2 AND @V_SINGLE = 0) OR (@V_SINGLE = 1))
			AND B.PRE_STATUS=1
	UNION ALL
	SELECT PREPRODUCT_ID,0 PRODUCT_ID,'',PREPRODUCT_NAME AS PRODUCT_NAME,'',PRE_MONEY, 0, PRE_START_DATE, PRE_END_DATE,
	        0,0
	    FROM TPREPRODUCT 
	    WHERE ISNULL(BIND_PRODUCT_ID,0)=0 --未绑定的产品
			  AND PRE_STATUS=1
    ORDER BY PREPRODUCT_ID DESC,A.PRODUCT_CODE DESC
GO
