USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_DEL_TAuthorizationShare @IN_SERIAL_NO  INT,      --客户授权记录ID
                                            @IN_INPUT_MAN  INT = 0   --操作员
WITH ENCRYPTION
AS
    DECLARE @V_RET_CODE INT, @IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)
    SELECT @V_RET_CODE = -40502000, @IBUSI_FLAG = 40502
    SELECT @SBUSI_NAME = N'删除客户授权集合授权记录', @SSUMMARY = N'删除客户授权集合授权记录'
    IF NOT EXISTS(SELECT 1 FROM  TAuthorizationShare WHERE SERIAL_NO = @IN_SERIAL_NO)
        RETURN @V_RET_CODE - 6 --对应授权记录不存在
    IF EXISTS(SELECT 1 FROM  TAuthorizationShare WHERE Status = 1 AND ShareType<>3 AND SERIAL_NO = @IN_SERIAL_NO)
        RETURN @V_RET_CODE - 7 --此授权集授权已经启用，要禁用后才能删除
    BEGIN TRANSACTION
    --删除客户授权集合授权记录
    DELETE FROM  TAuthorizationShare WHERE SERIAL_NO = @IN_SERIAL_NO
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SET @SSUMMARY = N'删除客户授权集合授权记录，操作员：' + CAST(@IN_INPUT_MAN AS NVARCHAR(10))
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION

    RETURN 100
GO
