USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_DEL_TCUSTMANAGERCHANGES @IN_SERIAL_NO           INT,            --序列号
                                            @IN_INPUT_MAN           INT = 0         --操作员
WITH ENCRYPTION
AS
     DECLARE @V_RET_CODE INT, @IBUSI_FLAG INT,@SBUSI_NAME NVARCHAR(40), @SSUMMARY NVARCHAR(200)
    SELECT @V_RET_CODE = -30401000, @IBUSI_FLAG = 30401
    SELECT @SBUSI_NAME = N'删除客户移交，客户经理变更信息', @SSUMMARY = N'删除客户移交，客户经理变更信息'
    IF NOT EXISTS(SELECT 1 FROM TCUSTMANAGERCHANGES WHERE SERIAL_NO = @IN_SERIAL_NO)
        RETURN @V_RET_CODE - 3 --客户移交信息不存在
    IF EXISTS(SELECT 1 FROM TCUSTMANAGERCHANGES WHERE SERIAL_NO = @IN_SERIAL_NO AND CHECK_FLAG = 2 )
        RETURN @V_RET_CODE - 4 --该客户经理移交记录已经审批通过，不允许修改

    BEGIN TRANSACTION
    DELETE FROM  TCUSTMANAGERCHANGES
    WHERE SERIAL_NO = @IN_SERIAL_NO
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SET @SSUMMARY = N'删除客户移交，客户经理变更信息，操作员：' + CAST(@IN_INPUT_MAN AS NVARCHAR(10))
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_INPUT_MAN,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    RETURN 100
GO
