USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_LOGIN   @IN_OP_CODE     INT,
                            @IN_PASSWORD    NVARCHAR(40),
                            @IN_IP_ADDRESS  NVARCHAR(15),
                            @OUT_RET_CODE   INT = 1 OUTPUT
WITH ENCRYPTION
AS
 --   DECLARE @V_PASSWORD NVARCHAR(40)

    DECLARE @V_PASSWORD NVARCHAR(40)
    DECLARE @V_RET_CODE INT,@V_IP_ADDRESS NVARCHAR(15)
    DECLARE @IBUSI_FLAG INT
    DECLARE @SBUSI_NAME NVARCHAR(40)
    DECLARE @SSUMMARY NVARCHAR(200)
    SELECT @V_RET_CODE = -10104000
    SELECT @IBUSI_FLAG = 10104
    SELECT @SBUSI_NAME = N'操作员登录'
    SELECT @SSUMMARY = N'操作员登录'
    SELECT @OUT_RET_CODE = 100
    IF NOT EXISTS(SELECT 1 FROM TOPERATOR WHERE OP_CODE = @IN_OP_CODE AND STATUS = 1)
    BEGIN
        SELECT @OUT_RET_CODE =  @V_RET_CODE-3  -- 操作员不存在
        RETURN @OUT_RET_CODE
    END

    IF NOT EXISTS(SELECT 1 FROM TOPERATOR WHERE OP_CODE = @IN_OP_CODE AND STATUS = 1 )
    BEGIN
        SELECT @OUT_RET_CODE =  @V_RET_CODE-5  -- 该操作员没有系统操作权限
        RETURN @OUT_RET_CODE
    END
    SELECT  @V_PASSWORD = PASSWORD,@V_IP_ADDRESS =ISNULL(IP_ADDRESS,'')
        FROM TOPERATOR WHERE OP_CODE = @IN_OP_CODE

    IF NOT EXISTS(SELECT 1 FROM TOPERATOR WHERE OP_CODE = @IN_OP_CODE AND pwdcompare(@IN_PASSWORD,ENCRYPT_PASSWORD)=1 )
    BEGIN
        SELECT @OUT_RET_CODE = @V_RET_CODE-6  -- 密码不对
        RETURN @OUT_RET_CODE
    END


    BEGIN TRANSACTION

    UPDATE TOPERATOR SET LOGIN_TIME = CURRENT_TIMESTAMP, IP_ADDRESS = @IN_IP_ADDRESS,ONLINE =1
        WHERE OP_CODE = @IN_OP_CODE
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    SELECT @SSUMMARY = N'操作员登录，操作员编号：' + CONVERT(NVARCHAR(16),@IN_OP_CODE)
    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
        VALUES(@IBUSI_FLAG,@SBUSI_NAME,@IN_OP_CODE,@SSUMMARY)
    IF @@ERROR <> 0
    BEGIN
        ROLLBACK TRANSACTION
        RETURN -100
    END

    COMMIT TRANSACTION
    SELECT @OUT_RET_CODE = 100

GO
