package com.whaty.platform.entity.web.action.teaching.paper;

import com.whaty.platform.entity.util.Page;
import com.whaty.platform.entity.web.action.MyBaseAction;

public class PaperProcessTeacherAction extends MyBaseAction {

	@Override
	public void initGrid() {
		this.getGridConfig().setCapability(false, false, false);

		this.getGridConfig().setTitle(this.getText("论文进展统计（教师）"));
//		this.getGridConfig().addColumn(this.getText("row_num"),"row_num",false,false,false,"");
		this.getGridConfig().addColumn(this.getText("id"),"id",false,false,false,"");

		this.getGridConfig().addColumn(this.getText("学期"),"combobox_peSemester.peSemester_Name");
		this.getGridConfig().addColumn(this.getText("peSemester_Id"),"peSemester_Id",false,false,false,"");
		this.getGridConfig().addColumn(this.getText("peTeacher_Id"),"peTeacher_Id",false,false,false,"");
		this.getGridConfig().addColumn(this.getText("指导教师"),"peTeacher_Name");
		this.getGridConfig().addColumn(this.getText("指导人数"),"student_num",false,false,false,"");
		this.getGridConfig().addColumn(this.getText("开题报告已提交"),"kaiti_tijiao",false,false,false,"");
		this.getGridConfig().addColumn(this.getText("开题报告未提交"),"kaiti_weitijiao",false,false,false,"");
		this.getGridConfig().addColumn(this.getText("开题报告已留言"),"kaiti_liuyan",false,false,false,"");
		this.getGridConfig().addColumn(this.getText("开题报告未留言"),"kaiti_weiliuyan",false,false,false,"");
		this.getGridConfig().addColumn(this.getText("初稿已提交"),"chugao_tijiao",false,false,false,"");
		this.getGridConfig().addColumn(this.getText("初稿未提交"),"chugao_weitijiao",false,false,false,"");
		this.getGridConfig().addColumn(this.getText("初稿已留言"),"chugao_liuyan",false,false,false,"");
		this.getGridConfig().addColumn(this.getText("初稿未留言"),"chugao_weiliuyan",false,false,false,"");
		this.getGridConfig().addColumn(this.getText("终稿已提交"),"zhonggao_tijiao",false,false,false,"");
		this.getGridConfig().addColumn(this.getText("终稿未提交"),"zhonggao_weitijiao",false,false,false,"");
		this.getGridConfig().addColumn(this.getText("终稿已留言"),"zhonggao_liuyan",false,false,false,"");
		this.getGridConfig().addColumn(this.getText("终稿未留言"),"zhonggao_weiliuyan",false,false,false,"");
		this.getGridConfig().addColumn(this.getText("已提交总数"),"tijiao",false,false,false,"");
		this.getGridConfig().addColumn(this.getText("未提交总数"),"weitijiao",false,false,false,"");
		this.getGridConfig().addColumn(this.getText("已留言总数"),"liuyan",false,false,false,"");
		this.getGridConfig().addColumn(this.getText("未留言总数"),"weiliuyan",false,false,false,"");
		//查看指导的学生信息
		String stu = "<a href='/entity/teaching/studentTopic.action?bean.prTchPaperTitle.peSemester.id=\" + record.data['peSemester_Id'] + \""
			+"&bean.prTchPaperTitle.peTeacher.id=\" + record.data['peTeacher_Id'] + \""
			+"' target='_blank'>\" + record.data['student_num'] + \"</a>";
		this.getGridConfig().addRenderFunction(this.getText("指导人数"), stu);
		
		//查看已经提交的详情
		String temp = "<a href='/entity/teaching/paperProcessInfo.action?user=teacher&bean.prTchStuPaper.prTchPaperTitle.peSemester.id=\" + record.data['peSemester_Id'] + \""
			+"&bean.prTchStuPaper.prTchPaperTitle.peTeacher.id=\" + record.data['peTeacher_Id'] + \"";
		//查看未提交的学生信息
		String stuInfo = "<a href='/entity/teaching/paperProcessStuInfo.action?user=teacher&peSemester=\" + record.data['peSemester_Id'] + \""
			+"&peTeacher=\" + record.data['peTeacher_Id'] + \"";
		
		String temp0 = temp+"&type=tijiao&section=kaiti' target='_blank'>\" + record.data['kaiti_tijiao'] + \"</a>";
		this.getGridConfig().addRenderFunction(this.getText("开题报告已提交"), temp0);
		String temp8 = stuInfo+ "&type=tijiao&section=kaiti' target='_blank'>\" + record.data['kaiti_weitijiao'] + \"</a>";
		this.getGridConfig().addRenderFunction(this.getText("开题报告未提交"), temp8);
		String temp1 = temp+"&type=liuyan&section=kaiti' target='_blank'>\" + record.data['kaiti_liuyan'] + \"</a>";
		this.getGridConfig().addRenderFunction(this.getText("开题报告已留言"), temp1);
		String temp9 = stuInfo+ "&type=liuyan&section=kaiti' target='_blank'>\" + record.data['kaiti_weiliuyan'] + \"</a>";
		this.getGridConfig().addRenderFunction(this.getText("开题报告未留言"), temp9);
		
		String temp2 = temp+"&type=tijiao&section=chugao' target='_blank'>\" + record.data['chugao_tijiao'] + \"</a>";
		this.getGridConfig().addRenderFunction(this.getText("初稿已提交"), temp2);
		String temp10 = stuInfo+ "&type=tijiao&section=chugao' target='_blank'>\" + record.data['chugao_weitijiao'] + \"</a>";
		this.getGridConfig().addRenderFunction(this.getText("初稿未提交"), temp10);
		String temp3 = temp+"&type=liuyan&section=chugao' target='_blank'>\" + record.data['chugao_liuyan'] + \"</a>";
		this.getGridConfig().addRenderFunction(this.getText("初稿已留言"), temp3);
		String temp11 = stuInfo+ "&type=liuyan&section=chugao' target='_blank'>\" + record.data['chugao_weiliuyan'] + \"</a>";
		this.getGridConfig().addRenderFunction(this.getText("初稿未留言"), temp11);
		
		String temp4 = temp+"&type=tijiao&section=zhonggao' target='_blank'>\" + record.data['zhonggao_tijiao'] + \"</a>";
		this.getGridConfig().addRenderFunction(this.getText("终稿已提交"), temp4);
		String temp12 = stuInfo+ "&type=tijiao&section=zhonggao' target='_blank'>\" + record.data['zhonggao_weitijiao'] + \"</a>";
		this.getGridConfig().addRenderFunction(this.getText("终稿未提交"), temp12);
		String temp5 = temp+"&type=liuyan&section=zhonggao' target='_blank'>\" + record.data['zhonggao_liuyan'] + \"</a>";
		this.getGridConfig().addRenderFunction(this.getText("终稿已留言"), temp5);
		String temp13 = stuInfo+ "&type=liuyan&section=zhonggao' target='_blank'>\" + record.data['zhonggao_weiliuyan'] + \"</a>";
		this.getGridConfig().addRenderFunction(this.getText("终稿未留言"), temp13);
		
		String temp6 = temp+"&type=tijiao' target='_blank'>\" + record.data['tijiao'] + \"</a>";
		this.getGridConfig().addRenderFunction(this.getText("已提交总数"), temp6);
		String temp14 = stuInfo+"&type=tijiao' target='_blank'>\" + record.data['weitijiao'] + \"</a>";
		this.getGridConfig().addRenderFunction(this.getText("各阶段均未提交"), temp14);
		
		String temp7 = temp+"&type=liuyan' target='_blank'>\" + record.data['liuyan'] + \"</a>";
		this.getGridConfig().addRenderFunction(this.getText("已留言总数"), temp7);
		String temp15 = stuInfo+"&type=liuyan' target='_blank'>\" + record.data['weiliuyan'] + \"</a>";
		this.getGridConfig().addRenderFunction(this.getText("各阶段均未留言"), temp15);
		if(this.getGridConfig().checkBeforeAddMenu("/entity/teaching/paperProcess.action")){
		this.getGridConfig().addMenuScript(this.getText("以学生为对象统计"), "{window.location.href='/entity/teaching/paperProcess.action'}");
		}
	}

	public Page list() {
		StringBuffer sql_temp = new StringBuffer();
		sql_temp.append("     select rownum as id, one.*																																			");		
		sql_temp.append("       from (select shuliang.peSemester_Name as peSemester_Name,                                     ");
		sql_temp.append("                    shuliang.peSemester_Id as peSemester_Id,                                         ");
		sql_temp.append("                    shuliang.peTeacher_Id as peTeacher_Id,                                           ");
		sql_temp.append("                    shuliang.peTeacher_Name as peTeacher_Name,                                       ");
		sql_temp.append("                    shuliang.student as student_num,                                                 ");
		sql_temp.append("                    nvl(kaitijiao.num, 0) as kaiti_tijiao,                                           ");
		sql_temp.append("                    nvl(shuliang.student - nvl(kaititijiao.num, 0), 0) as kaiti_weitijiao,           ");
		sql_temp.append("                    nvl(kailiuyan.num, 0) as kaiti_liuyan,                                           ");
		sql_temp.append("                    shuliang.student - nvl(kaitiliuyan.num, 0) as kaiti_weiliuyan,                   ");
		sql_temp.append("                    nvl(chutijiao.num, 0) as chugao_tijiao,                                          ");
		sql_temp.append("                    shuliang.student - nvl(chugaotijiao.num, 0) as chugao_weitijiao,                 ");
		sql_temp.append("                    nvl(chuliuyan.num, 0) as chugao_liuyan,                                          ");
		sql_temp.append("                    shuliang.student - nvl(chugaoliuyan.num, 0) as chugao_weiliuyan,                 ");
		sql_temp.append("                    nvl(zhongtijiao.num, 0) as zhonggao_tijiao,                                      ");
		sql_temp.append("                    shuliang.student - nvl(zhonggaotijiao.num, 0) as zhonggao_weitijiao,             ");
		sql_temp.append("                    nvl(zhongliuyan.num, 0) as zhonggao_liuyan,                                      ");
		sql_temp.append("                    shuliang.student - nvl(zhonggaoliuyan.num, 0) as zhonggao_weiliuyan,             ");
		sql_temp.append("                    nvl(kaitijiao.num, 0) + nvl(chutijiao.num, 0) +                                  ");
		sql_temp.append("                    nvl(zhongtijiao.num, 0) as tijiao,                                               ");
		sql_temp.append("                    nvl(weitijiao.num, 0) as weitijiao,                  ");
		sql_temp.append("                    nvl(kailiuyan.num, 0) + nvl(chuliuyan.num, 0) +                                  ");
		sql_temp.append("                    nvl(zhongliuyan.num, 0) as liuyan,                                               ");
		sql_temp.append("                    nvl(weiliuyan.num, 0) as weiliuyan                    ");
		sql_temp.append("               from (select peSemester.Name as peSemester_Name,                                      ");
		sql_temp.append("                            peTeacher.True_Name as peTeacher_Name,                                   ");
		sql_temp.append("                            peSemester.Id as peSemester_Id,                                          ");
		sql_temp.append("                            peTeacher.Id as peTeacher_Id,                                            ");
		sql_temp.append("                            count(peStudent.Id) as student                                           ");
		sql_temp.append("                       from PR_TCH_STU_PAPER   prTchStuPaper,                                        ");
		sql_temp.append("                            PR_TCH_PAPER_TITLE prTchPaperTitle,                                      ");
		sql_temp.append("                            PE_TEACHER         peTeacher,                                            ");
		sql_temp.append("                            pe_student         peStudent,                                            ");
		sql_temp.append("                            pe_semester        peSemester                                            ");
		sql_temp.append("                      where prTchStuPaper.Fk_Paper_Title_Id = prTchPaperTitle.Id                     ");
		sql_temp.append("                        and prTchPaperTitle.Fk_Teacher = peTeacher.Id                                ");
		sql_temp.append("                        and prTchStuPaper.Fk_Stu_Id = peStudent.Id                                   ");
		sql_temp.append("                        and prTchPaperTitle.Fk_Semester = peSemester.Id                              ");
		sql_temp.append("                      group by peTeacher.True_Name,                                                  ");
		sql_temp.append("                               peSemester.Id,                                                        ");
		sql_temp.append("                               peSemester.Name,                                                      ");
		sql_temp.append("                               peTeacher.Id) shuliang,                                               ");
		sql_temp.append("                    (select kaiti.peteacher_name as peteacher_name,                                  ");
		sql_temp.append("                            kaiti.peteacher_id as peteacher_id,                                      ");
		sql_temp.append("                            kaiti.pesemester_name as pesemester_name,                                ");
		sql_temp.append("                            nvl(count(kaiti.student), 0) as num                                      ");
		sql_temp.append("                       from (select peTeacher.True_Name as peTeacher_Name,                           ");
		sql_temp.append("                                    peTeacher.Id        as peTeacher_Id,                             ");
		sql_temp.append("                                    peSemester.Name     as peSemester_Name,                          ");
		sql_temp.append("                                    peStudent.Name      as student                                   ");
		sql_temp.append("                               from pr_tch_paper_content prTchPaperContent,                          ");
		sql_temp.append("                                    PR_TCH_STU_PAPER     prTchStuPaper,                              ");
		sql_temp.append("                                    PR_TCH_PAPER_TITLE   prTchPaperTitle,                            ");
		sql_temp.append("                                    PE_TEACHER           peTeacher,                                  ");
		sql_temp.append("                                    pe_student           peStudent,                                  ");
		sql_temp.append("                                    pe_semester          peSemester,                                 ");
		sql_temp.append("                                    enum_const           enumConstUser,                              ");
		sql_temp.append("                                    enum_const           enumConstSection                            ");
		sql_temp.append("                              where prTchPaperContent.Fk_Tch_Stu_Paper =                             ");
		sql_temp.append("                                    prTchStuPaper.Id                                                 ");
		sql_temp.append("                                and prTchPaperTitle.Fk_Semester = peSemester.Id                      ");
		sql_temp.append("                                and prTchStuPaper.Fk_Paper_Title_Id =                                ");
		sql_temp.append("                                    prTchPaperTitle.Id                                               ");
		sql_temp.append("                                and prTchPaperTitle.Fk_Teacher = peTeacher.Id                        ");
		sql_temp.append("                                and prTchStuPaper.Fk_Stu_Id = peStudent.Id                           ");
		sql_temp.append("                                and prTchPaperContent.Flag_Action_User =                             ");
		sql_temp.append("                                    enumConstUser.Id                                                 ");
		sql_temp.append("                                and enumConstUser.Namespace = 'FlagActionUser'                       ");
		sql_temp.append("                                and enumConstUser.Code = '1'                                         ");
		sql_temp.append("                                and prTchPaperContent.Flag_Paper_Section =                           ");
		sql_temp.append("                                    enumConstSection.Id                                              ");
		sql_temp.append("                                and enumConstSection.Namespace = 'FlagPaperSection'                  ");
		sql_temp.append("                                and enumConstSection.Code = '0'                                      ");
		sql_temp.append("                                and prTchPaperContent.Url is not null                                ");
		sql_temp.append("                              group by peTeacher.True_Name,                                          ");
		sql_temp.append("                                       peSemester.Name,                                              ");
		sql_temp.append("                                       peStudent.Name,                                               ");
		sql_temp.append("                                       peTeacher.Id) kaiti                                           ");
		sql_temp.append("                      group by kaiti.peteacher_name,                                                 ");
		sql_temp.append("                               kaiti.peteacher_id,                                                   ");
		sql_temp.append("                               kaiti.pesemester_name) kaititijiao,                                   ");
		sql_temp.append("                    (select kaiti.peteacher_name as peteacher_name,                                  ");
		sql_temp.append("                            kaiti.peteacher_id as peteacher_id,                                      ");
		sql_temp.append("                            kaiti.pesemester_name as pesemester_name,                                ");
		sql_temp.append("                            nvl(count(kaiti.student), 0) as num                                      ");
		sql_temp.append("                       from (select peTeacher.True_Name as peTeacher_Name,                           ");
		sql_temp.append("                                    peTeacher.Id        as peTeacher_Id,                             ");
		sql_temp.append("                                    peSemester.Name     as peSemester_Name,                          ");
		sql_temp.append("                                    peStudent.Name      as student                                   ");
		sql_temp.append("                               from pr_tch_paper_content prTchPaperContent,                          ");
		sql_temp.append("                                    PR_TCH_STU_PAPER     prTchStuPaper,                              ");
		sql_temp.append("                                    PR_TCH_PAPER_TITLE   prTchPaperTitle,                            ");
		sql_temp.append("                                    PE_TEACHER           peTeacher,                                  ");
		sql_temp.append("                                    pe_student           peStudent,                                  ");
		sql_temp.append("                                    pe_semester          peSemester,                                 ");
		sql_temp.append("                                    enum_const           enumConstUser,                              ");
		sql_temp.append("                                    enum_const           enumConstSection                            ");
		sql_temp.append("                              where prTchPaperContent.Fk_Tch_Stu_Paper =                             ");
		sql_temp.append("                                    prTchStuPaper.Id                                                 ");
		sql_temp.append("                                and prTchPaperTitle.Fk_Semester = peSemester.Id                      ");
		sql_temp.append("                                and prTchStuPaper.Fk_Paper_Title_Id =                                ");
		sql_temp.append("                                    prTchPaperTitle.Id                                               ");
		sql_temp.append("                                and prTchPaperTitle.Fk_Teacher = peTeacher.Id                        ");
		sql_temp.append("                                and prTchStuPaper.Fk_Stu_Id = peStudent.Id                           ");
		sql_temp.append("                                and prTchPaperContent.Flag_Action_User =                             ");
		sql_temp.append("                                    enumConstUser.Id                                                 ");
		sql_temp.append("                                and enumConstUser.Namespace = 'FlagActionUser'                       ");
		sql_temp.append("                                and enumConstUser.Code = '1'                                         ");
		sql_temp.append("                                and prTchPaperContent.Flag_Paper_Section =                           ");
		sql_temp.append("                                    enumConstSection.Id                                              ");
		sql_temp.append("                                and enumConstSection.Namespace = 'FlagPaperSection'                  ");
		sql_temp.append("                                and enumConstSection.Code = '0'                                      ");
		sql_temp.append("                                and prTchPaperContent.Note is not null                               ");
		sql_temp.append("                              group by peTeacher.True_Name,                                          ");
		sql_temp.append("                                       peSemester.Name,                                              ");
		sql_temp.append("                                       peStudent.Name,                                               ");
		sql_temp.append("                                       peTeacher.Id) kaiti                                           ");
		sql_temp.append("                      group by kaiti.peteacher_name,                                                 ");
		sql_temp.append("                               kaiti.peteacher_id,                                                   ");
		sql_temp.append("                               kaiti.pesemester_name) kaitiliuyan,                                   ");
		sql_temp.append("                    (select kaiti.peteacher_name as peteacher_name,                                  ");
		sql_temp.append("                            kaiti.peteacher_id as peteacher_id,                                      ");
		sql_temp.append("                            kaiti.pesemester_name as pesemester_name,                                ");
		sql_temp.append("                            nvl(count(kaiti.student), 0) as num                                      ");
		sql_temp.append("                       from (select peTeacher.True_Name as peTeacher_Name,                           ");
		sql_temp.append("                                    peTeacher.Id        as peTeacher_Id,                             ");
		sql_temp.append("                                    peSemester.Name     as peSemester_Name,                          ");
		sql_temp.append("                                    peStudent.Name      as student                                   ");
		sql_temp.append("                               from pr_tch_paper_content prTchPaperContent,                          ");
		sql_temp.append("                                    PR_TCH_STU_PAPER     prTchStuPaper,                              ");
		sql_temp.append("                                    PR_TCH_PAPER_TITLE   prTchPaperTitle,                            ");
		sql_temp.append("                                    PE_TEACHER           peTeacher,                                  ");
		sql_temp.append("                                    pe_student           peStudent,                                  ");
		sql_temp.append("                                    pe_semester          peSemester,                                 ");
		sql_temp.append("                                    enum_const           enumConstUser,                              ");
		sql_temp.append("                                    enum_const           enumConstSection                            ");
		sql_temp.append("                              where prTchPaperContent.Fk_Tch_Stu_Paper =                             ");
		sql_temp.append("                                    prTchStuPaper.Id                                                 ");
		sql_temp.append("                                and prTchPaperTitle.Fk_Semester = peSemester.Id                      ");
		sql_temp.append("                                and prTchStuPaper.Fk_Paper_Title_Id =                                ");
		sql_temp.append("                                    prTchPaperTitle.Id                                               ");
		sql_temp.append("                                and prTchPaperTitle.Fk_Teacher = peTeacher.Id                        ");
		sql_temp.append("                                and prTchStuPaper.Fk_Stu_Id = peStudent.Id                           ");
		sql_temp.append("                                and prTchPaperContent.Flag_Action_User =                             ");
		sql_temp.append("                                    enumConstUser.Id                                                 ");
		sql_temp.append("                                and enumConstUser.Namespace = 'FlagActionUser'                       ");
		sql_temp.append("                                and enumConstUser.Code = '1'                                         ");
		sql_temp.append("                                and prTchPaperContent.Flag_Paper_Section =                           ");
		sql_temp.append("                                    enumConstSection.Id                                              ");
		sql_temp.append("                                and enumConstSection.Namespace = 'FlagPaperSection'                  ");
		sql_temp.append("                                and enumConstSection.Code = '1'                                      ");
		sql_temp.append("                                and prTchPaperContent.Url is not null                                ");
		sql_temp.append("                              group by peTeacher.True_Name,                                          ");
		sql_temp.append("                                       peSemester.Name,                                              ");
		sql_temp.append("                                       peStudent.Name,                                               ");
		sql_temp.append("                                       peTeacher.Id) kaiti                                           ");
		sql_temp.append("                      group by kaiti.peteacher_name,                                                 ");
		sql_temp.append("                               kaiti.peteacher_id,                                                   ");
		sql_temp.append("                               kaiti.pesemester_name) chugaotijiao,                                  ");
		sql_temp.append("                    (select kaiti.peteacher_name as peteacher_name,                                  ");
		sql_temp.append("                            kaiti.peteacher_id as peteacher_id,                                      ");
		sql_temp.append("                            kaiti.pesemester_name as pesemester_name,                                ");
		sql_temp.append("                            nvl(count(kaiti.student), 0) as num                                      ");
		sql_temp.append("                       from (select peTeacher.True_Name as peTeacher_Name,                           ");
		sql_temp.append("                                    peTeacher.Id        as peTeacher_Id,                             ");
		sql_temp.append("                                    peSemester.Name     as peSemester_Name,                          ");
		sql_temp.append("                                    peStudent.Name      as student                                   ");
		sql_temp.append("                               from pr_tch_paper_content prTchPaperContent,                          ");
		sql_temp.append("                                    PR_TCH_STU_PAPER     prTchStuPaper,                              ");
		sql_temp.append("                                    PR_TCH_PAPER_TITLE   prTchPaperTitle,                            ");
		sql_temp.append("                                    PE_TEACHER           peTeacher,                                  ");
		sql_temp.append("                                    pe_student           peStudent,                                  ");
		sql_temp.append("                                    pe_semester          peSemester,                                 ");
		sql_temp.append("                                    enum_const           enumConstUser,                              ");
		sql_temp.append("                                    enum_const           enumConstSection                            ");
		sql_temp.append("                              where prTchPaperContent.Fk_Tch_Stu_Paper =                             ");
		sql_temp.append("                                    prTchStuPaper.Id                                                 ");
		sql_temp.append("                                and prTchPaperTitle.Fk_Semester = peSemester.Id                      ");
		sql_temp.append("                                and prTchStuPaper.Fk_Paper_Title_Id =                                ");
		sql_temp.append("                                    prTchPaperTitle.Id                                               ");
		sql_temp.append("                                and prTchPaperTitle.Fk_Teacher = peTeacher.Id                        ");
		sql_temp.append("                                and prTchStuPaper.Fk_Stu_Id = peStudent.Id                           ");
		sql_temp.append("                                and prTchPaperContent.Flag_Action_User =                             ");
		sql_temp.append("                                    enumConstUser.Id                                                 ");
		sql_temp.append("                                and enumConstUser.Namespace = 'FlagActionUser'                       ");
		sql_temp.append("                                and enumConstUser.Code = '1'                                         ");
		sql_temp.append("                                and prTchPaperContent.Flag_Paper_Section =                           ");
		sql_temp.append("                                    enumConstSection.Id                                              ");
		sql_temp.append("                                and enumConstSection.Namespace = 'FlagPaperSection'                  ");
		sql_temp.append("                                and enumConstSection.Code = '1'                                      ");
		sql_temp.append("                                and prTchPaperContent.Note is not null                               ");
		sql_temp.append("                              group by peTeacher.True_Name,                                          ");
		sql_temp.append("                                       peSemester.Name,                                              ");
		sql_temp.append("                                       peStudent.Name,                                               ");
		sql_temp.append("                                       peTeacher.Id) kaiti                                           ");
		sql_temp.append("                      group by kaiti.peteacher_name,                                                 ");
		sql_temp.append("                               kaiti.peteacher_id,                                                   ");
		sql_temp.append("                               kaiti.pesemester_name) chugaoliuyan,                                  ");
		sql_temp.append("                    (select kaiti.peteacher_name as peteacher_name,                                  ");
		sql_temp.append("                            kaiti.peteacher_id as peteacher_id,                                      ");
		sql_temp.append("                            kaiti.pesemester_name as pesemester_name,                                ");
		sql_temp.append("                            count(kaiti.student) as num                                              ");
		sql_temp.append("                       from (select peTeacher.True_Name as peTeacher_Name,                           ");
		sql_temp.append("                                    peTeacher.Id        as peTeacher_Id,                             ");
		sql_temp.append("                                    peSemester.Name     as peSemester_Name,                          ");
		sql_temp.append("                                    peStudent.Name      as student                                   ");
		sql_temp.append("                               from pr_tch_paper_content prTchPaperContent,                          ");
		sql_temp.append("                                    PR_TCH_STU_PAPER     prTchStuPaper,                              ");
		sql_temp.append("                                    PR_TCH_PAPER_TITLE   prTchPaperTitle,                            ");
		sql_temp.append("                                    PE_TEACHER           peTeacher,                                  ");
		sql_temp.append("                                    pe_student           peStudent,                                  ");
		sql_temp.append("                                    pe_semester          peSemester,                                 ");
		sql_temp.append("                                    enum_const           enumConstUser,                              ");
		sql_temp.append("                                    enum_const           enumConstSection                            ");
		sql_temp.append("                              where prTchPaperContent.Fk_Tch_Stu_Paper =                             ");
		sql_temp.append("                                    prTchStuPaper.Id                                                 ");
		sql_temp.append("                                and prTchPaperTitle.Fk_Semester = peSemester.Id                      ");
		sql_temp.append("                                and prTchStuPaper.Fk_Paper_Title_Id =                                ");
		sql_temp.append("                                    prTchPaperTitle.Id                                               ");
		sql_temp.append("                                and prTchPaperTitle.Fk_Teacher = peTeacher.Id                        ");
		sql_temp.append("                                and prTchStuPaper.Fk_Stu_Id = peStudent.Id                           ");
		sql_temp.append("                                and prTchPaperContent.Flag_Action_User =                             ");
		sql_temp.append("                                    enumConstUser.Id                                                 ");
		sql_temp.append("                                and enumConstUser.Namespace = 'FlagActionUser'                       ");
		sql_temp.append("                                and enumConstUser.Code = '1'                                         ");
		sql_temp.append("                                and prTchPaperContent.Flag_Paper_Section =                           ");
		sql_temp.append("                                    enumConstSection.Id                                              ");
		sql_temp.append("                                and enumConstSection.Namespace = 'FlagPaperSection'                  ");
		sql_temp.append("                                and enumConstSection.Code = '2'                                      ");
		sql_temp.append("                                and prTchPaperContent.Url is not null                                ");
		sql_temp.append("                              group by peTeacher.True_Name,                                          ");
		sql_temp.append("                                       peSemester.Name,                                              ");
		sql_temp.append("                                       peStudent.Name,                                               ");
		sql_temp.append("                                       peTeacher.Id) kaiti                                           ");
		sql_temp.append("                      group by kaiti.peteacher_name,                                                 ");
		sql_temp.append("                               kaiti.peteacher_id,                                                   ");
		sql_temp.append("                               kaiti.pesemester_name) zhonggaotijiao,                                ");
		sql_temp.append("                    (select kaiti.peteacher_name as peteacher_name,                                  ");
		sql_temp.append("                            kaiti.peteacher_id as peteacher_id,                                      ");
		sql_temp.append("                            kaiti.pesemester_name as pesemester_name,                                ");
		sql_temp.append("                            count(kaiti.student) as num                                              ");
		sql_temp.append("                       from (select peTeacher.True_Name as peTeacher_Name,                           ");
		sql_temp.append("                                    peTeacher.Id        as peTeacher_Id,                             ");
		sql_temp.append("                                    peSemester.Name     as peSemester_Name,                          ");
		sql_temp.append("                                    peStudent.Name      as student                                   ");
		sql_temp.append("                               from pr_tch_paper_content prTchPaperContent,                          ");
		sql_temp.append("                                    PR_TCH_STU_PAPER     prTchStuPaper,                              ");
		sql_temp.append("                                    PR_TCH_PAPER_TITLE   prTchPaperTitle,                            ");
		sql_temp.append("                                    PE_TEACHER           peTeacher,                                  ");
		sql_temp.append("                                    pe_student           peStudent,                                  ");
		sql_temp.append("                                    pe_semester          peSemester,                                 ");
		sql_temp.append("                                    enum_const           enumConstUser,                              ");
		sql_temp.append("                                    enum_const           enumConstSection                            ");
		sql_temp.append("                              where prTchPaperContent.Fk_Tch_Stu_Paper =                             ");
		sql_temp.append("                                    prTchStuPaper.Id                                                 ");
		sql_temp.append("                                and prTchPaperTitle.Fk_Semester = peSemester.Id                      ");
		sql_temp.append("                                and prTchStuPaper.Fk_Paper_Title_Id =                                ");
		sql_temp.append("                                    prTchPaperTitle.Id                                               ");
		sql_temp.append("                                and prTchPaperTitle.Fk_Teacher = peTeacher.Id                        ");
		sql_temp.append("                                and prTchStuPaper.Fk_Stu_Id = peStudent.Id                           ");
		sql_temp.append("                                and prTchPaperContent.Flag_Action_User =                             ");
		sql_temp.append("                                    enumConstUser.Id                                                 ");
		sql_temp.append("                                and enumConstUser.Namespace = 'FlagActionUser'                       ");
		sql_temp.append("                                and enumConstUser.Code = '1'                                         ");
		sql_temp.append("                                and prTchPaperContent.Flag_Paper_Section =                           ");
		sql_temp.append("                                    enumConstSection.Id                                              ");
		sql_temp.append("                                and enumConstSection.Namespace = 'FlagPaperSection'                  ");
		sql_temp.append("                                and enumConstSection.Code = '2'                                      ");
		sql_temp.append("                                and prTchPaperContent.Note is not null                               ");
		sql_temp.append("                              group by peTeacher.True_Name,                                          ");
		sql_temp.append("                                       peSemester.Name,                                              ");
		sql_temp.append("                                       peStudent.Name,                                               ");
		sql_temp.append("                                       peTeacher.Id) kaiti                                           ");
		sql_temp.append("                      group by kaiti.peteacher_name,                                                 ");
		sql_temp.append("                               kaiti.peteacher_id,                                                   ");
		sql_temp.append("                               kaiti.pesemester_name) zhonggaoliuyan,                                ");
		sql_temp.append("                    (select peTeacher.True_Name as peTeacher_Name,                                   ");
		sql_temp.append("                            peTeacher.Id as peTeacher_Id,                                            ");
		sql_temp.append("                            peSemester.Name as peSemester_Name,                                      ");
		sql_temp.append("                            count(*) as num                                                          ");
		sql_temp.append("                       from pr_tch_paper_content prTchPaperContent,                                  ");
		sql_temp.append("                            PR_TCH_STU_PAPER     prTchStuPaper,                                      ");
		sql_temp.append("                            PR_TCH_PAPER_TITLE   prTchPaperTitle,                                    ");
		sql_temp.append("                            PE_TEACHER           peTeacher,                                          ");
		sql_temp.append("                            pe_student           peStudent,                                          ");
		sql_temp.append("                            pe_semester          peSemester,                                         ");
		sql_temp.append("                            enum_const           enumConstUser,                                      ");
		sql_temp.append("                            enum_const           enumConstSection                                    ");
		sql_temp.append("                      where prTchPaperContent.Fk_Tch_Stu_Paper = prTchStuPaper.Id                    ");
		sql_temp.append("                        and prTchPaperTitle.Fk_Semester = peSemester.Id                              ");
		sql_temp.append("                        and prTchStuPaper.Fk_Paper_Title_Id = prTchPaperTitle.Id                     ");
		sql_temp.append("                        and prTchPaperTitle.Fk_Teacher = peTeacher.Id                                ");
		sql_temp.append("                        and prTchStuPaper.Fk_Stu_Id = peStudent.Id                                   ");
		sql_temp.append("                        and prTchPaperContent.Flag_Action_User = enumConstUser.Id                    ");
		sql_temp.append("                        and enumConstUser.Namespace = 'FlagActionUser'                               ");
		sql_temp.append("                        and enumConstUser.Code = '1'                                                 ");
		sql_temp.append("                        and prTchPaperContent.Flag_Paper_Section =                                   ");
		sql_temp.append("                            enumConstSection.Id                                                      ");
		sql_temp.append("                        and enumConstSection.Namespace = 'FlagPaperSection'                          ");
		sql_temp.append("                        and enumConstSection.Code = '0'                                              ");
		sql_temp.append("                        and prTchPaperContent.Url is not null                                        ");
		sql_temp.append("                      group by peTeacher.True_Name, peSemester.Name, peTeacher.Id) kaitijiao,        ");
		sql_temp.append("                    (select peTeacher.True_Name as peTeacher_Name,                                   ");
		sql_temp.append("                            peTeacher.Id as peTeacher_Id,                                            ");
		sql_temp.append("                            peSemester.Name as peSemester_Name,                                      ");
		sql_temp.append("                            count(*) as num                                                          ");
		sql_temp.append("                       from pr_tch_paper_content prTchPaperContent,                                  ");
		sql_temp.append("                            PR_TCH_STU_PAPER     prTchStuPaper,                                      ");
		sql_temp.append("                            PR_TCH_PAPER_TITLE   prTchPaperTitle,                                    ");
		sql_temp.append("                            PE_TEACHER           peTeacher,                                          ");
		sql_temp.append("                            pe_student           peStudent,                                          ");
		sql_temp.append("                            pe_semester          peSemester,                                         ");
		sql_temp.append("                            enum_const           enumConstUser,                                      ");
		sql_temp.append("                            enum_const           enumConstSection                                    ");
		sql_temp.append("                      where prTchPaperContent.Fk_Tch_Stu_Paper = prTchStuPaper.Id                    ");
		sql_temp.append("                        and prTchPaperTitle.Fk_Semester = peSemester.Id                              ");
		sql_temp.append("                        and prTchStuPaper.Fk_Paper_Title_Id = prTchPaperTitle.Id                     ");
		sql_temp.append("                        and prTchPaperTitle.Fk_Teacher = peTeacher.Id                                ");
		sql_temp.append("                        and prTchStuPaper.Fk_Stu_Id = peStudent.Id                                   ");
		sql_temp.append("                        and prTchPaperContent.Flag_Action_User = enumConstUser.Id                    ");
		sql_temp.append("                        and enumConstUser.Namespace = 'FlagActionUser'                               ");
		sql_temp.append("                        and enumConstUser.Code = '1'                                                 ");
		sql_temp.append("                        and prTchPaperContent.Flag_Paper_Section =                                   ");
		sql_temp.append("                            enumConstSection.Id                                                      ");
		sql_temp.append("                        and enumConstSection.Namespace = 'FlagPaperSection'                          ");
		sql_temp.append("                        and enumConstSection.Code = '0'                                              ");
		sql_temp.append("                        and prTchPaperContent.Note is not null                                       ");
		sql_temp.append("                      group by peTeacher.True_Name, peSemester.Name, peTeacher.Id) kailiuyan,        ");
		sql_temp.append("                    (select peTeacher.True_Name as peTeacher_Name,                                   ");
		sql_temp.append("                            peTeacher.Id as peTeacher_Id,                                            ");
		sql_temp.append("                            peSemester.Name as peSemester_Name,                                      ");
		sql_temp.append("                            count(*) as num                                                          ");
		sql_temp.append("                       from pr_tch_paper_content prTchPaperContent,                                  ");
		sql_temp.append("                            PR_TCH_STU_PAPER     prTchStuPaper,                                      ");
		sql_temp.append("                            PR_TCH_PAPER_TITLE   prTchPaperTitle,                                    ");
		sql_temp.append("                            PE_TEACHER           peTeacher,                                          ");
		sql_temp.append("                            pe_student           peStudent,                                          ");
		sql_temp.append("                            pe_semester          peSemester,                                         ");
		sql_temp.append("                            enum_const           enumConstUser,                                      ");
		sql_temp.append("                            enum_const           enumConstSection                                    ");
		sql_temp.append("                      where prTchPaperContent.Fk_Tch_Stu_Paper = prTchStuPaper.Id                    ");
		sql_temp.append("                        and prTchPaperTitle.Fk_Semester = peSemester.Id                              ");
		sql_temp.append("                        and prTchStuPaper.Fk_Paper_Title_Id = prTchPaperTitle.Id                     ");
		sql_temp.append("                        and prTchPaperTitle.Fk_Teacher = peTeacher.Id                                ");
		sql_temp.append("                        and prTchStuPaper.Fk_Stu_Id = peStudent.Id                                   ");
		sql_temp.append("                        and prTchPaperContent.Flag_Action_User = enumConstUser.Id                    ");
		sql_temp.append("                        and enumConstUser.Namespace = 'FlagActionUser'                               ");
		sql_temp.append("                        and enumConstUser.Code = '1'                                                 ");
		sql_temp.append("                        and prTchPaperContent.Flag_Paper_Section =                                   ");
		sql_temp.append("                            enumConstSection.Id                                                      ");
		sql_temp.append("                        and enumConstSection.Namespace = 'FlagPaperSection'                          ");
		sql_temp.append("                        and enumConstSection.Code = '1'                                              ");
		sql_temp.append("                        and prTchPaperContent.Url is not null                                        ");
		sql_temp.append("                      group by peTeacher.True_Name, peSemester.Name, peTeacher.Id) chutijiao,        ");
		sql_temp.append("                    (select peTeacher.True_Name as peTeacher_Name,                                   ");
		sql_temp.append("                            peTeacher.Id as peTeacher_Id,                                            ");
		sql_temp.append("                            peSemester.Name as peSemester_Name,                                      ");
		sql_temp.append("                            count(*) as num                                                          ");
		sql_temp.append("                       from pr_tch_paper_content prTchPaperContent,                                  ");
		sql_temp.append("                            PR_TCH_STU_PAPER     prTchStuPaper,                                      ");
		sql_temp.append("                            PR_TCH_PAPER_TITLE   prTchPaperTitle,                                    ");
		sql_temp.append("                            PE_TEACHER           peTeacher,                                          ");
		sql_temp.append("                            pe_student           peStudent,                                          ");
		sql_temp.append("                            pe_semester          peSemester,                                         ");
		sql_temp.append("                            enum_const           enumConstUser,                                      ");
		sql_temp.append("                            enum_const           enumConstSection                                    ");
		sql_temp.append("                      where prTchPaperContent.Fk_Tch_Stu_Paper = prTchStuPaper.Id                    ");
		sql_temp.append("                        and prTchPaperTitle.Fk_Semester = peSemester.Id                              ");
		sql_temp.append("                        and prTchStuPaper.Fk_Paper_Title_Id = prTchPaperTitle.Id                     ");
		sql_temp.append("                        and prTchPaperTitle.Fk_Teacher = peTeacher.Id                                ");
		sql_temp.append("                        and prTchStuPaper.Fk_Stu_Id = peStudent.Id                                   ");
		sql_temp.append("                        and prTchPaperContent.Flag_Action_User = enumConstUser.Id                    ");
		sql_temp.append("                        and enumConstUser.Namespace = 'FlagActionUser'                               ");
		sql_temp.append("                        and enumConstUser.Code = '1'                                                 ");
		sql_temp.append("                        and prTchPaperContent.Flag_Paper_Section =                                   ");
		sql_temp.append("                            enumConstSection.Id                                                      ");
		sql_temp.append("                        and enumConstSection.Namespace = 'FlagPaperSection'                          ");
		sql_temp.append("                        and enumConstSection.Code = '1'                                              ");
		sql_temp.append("                        and prTchPaperContent.Note is not null                                       ");
		sql_temp.append("                      group by peTeacher.True_Name, peSemester.Name, peTeacher.Id) chuliuyan,        ");
		sql_temp.append("                    (select peTeacher.True_Name as peTeacher_Name,                                   ");
		sql_temp.append("                            peTeacher.Id as peTeacher_Id,                                            ");
		sql_temp.append("                            peSemester.Name as peSemester_Name,                                      ");
		sql_temp.append("                            nvl(count(*), 0) as num                                                  ");
		sql_temp.append("                       from pr_tch_paper_content prTchPaperContent,                                  ");
		sql_temp.append("                            PR_TCH_STU_PAPER     prTchStuPaper,                                      ");
		sql_temp.append("                            PR_TCH_PAPER_TITLE   prTchPaperTitle,                                    ");
		sql_temp.append("                            PE_TEACHER           peTeacher,                                          ");
		sql_temp.append("                            pe_student           peStudent,                                          ");
		sql_temp.append("                            pe_semester          peSemester,                                         ");
		sql_temp.append("                            enum_const           enumConstUser,                                      ");
		sql_temp.append("                            enum_const           enumConstSection                                    ");
		sql_temp.append("                      where prTchPaperContent.Fk_Tch_Stu_Paper = prTchStuPaper.Id                    ");
		sql_temp.append("                        and prTchPaperTitle.Fk_Semester = peSemester.Id                              ");
		sql_temp.append("                        and prTchStuPaper.Fk_Paper_Title_Id = prTchPaperTitle.Id                     ");
		sql_temp.append("                        and prTchPaperTitle.Fk_Teacher = peTeacher.Id                                ");
		sql_temp.append("                        and prTchStuPaper.Fk_Stu_Id = peStudent.Id                                   ");
		sql_temp.append("                        and prTchPaperContent.Flag_Action_User = enumConstUser.Id                    ");
		sql_temp.append("                        and enumConstUser.Namespace = 'FlagActionUser'                               ");
		sql_temp.append("                        and enumConstUser.Code = '1'                                                 ");
		sql_temp.append("                        and prTchPaperContent.Flag_Paper_Section =                                   ");
		sql_temp.append("                            enumConstSection.Id                                                      ");
		sql_temp.append("                        and enumConstSection.Namespace = 'FlagPaperSection'                          ");
		sql_temp.append("                        and enumConstSection.Code = '2'                                              ");
		sql_temp.append("                        and prTchPaperContent.Url is not null                                        ");
		sql_temp.append("                      group by peTeacher.True_Name, peSemester.Name, peTeacher.Id) zhongtijiao,      ");
		sql_temp.append("                    (select peTeacher.True_Name as peTeacher_Name,                                   ");
		sql_temp.append("                            peTeacher.Id as peTeacher_Id,                                            ");
		sql_temp.append("                            peSemester.Name as peSemester_Name,                                      ");
		sql_temp.append("                            nvl(count(*), 0) as num                                                  ");
		sql_temp.append("                       from pr_tch_paper_content prTchPaperContent,                                  ");
		sql_temp.append("                            PR_TCH_STU_PAPER     prTchStuPaper,                                      ");
		sql_temp.append("                            PR_TCH_PAPER_TITLE   prTchPaperTitle,                                    ");
		sql_temp.append("                            PE_TEACHER           peTeacher,                                          ");
		sql_temp.append("                            pe_student           peStudent,                                          ");
		sql_temp.append("                            pe_semester          peSemester,                                         ");
		sql_temp.append("                            enum_const           enumConstUser,                                      ");
		sql_temp.append("                            enum_const           enumConstSection                                    ");
		sql_temp.append("                      where prTchPaperContent.Fk_Tch_Stu_Paper = prTchStuPaper.Id                    ");
		sql_temp.append("                        and prTchPaperTitle.Fk_Semester = peSemester.Id                              ");
		sql_temp.append("                        and prTchStuPaper.Fk_Paper_Title_Id = prTchPaperTitle.Id                     ");
		sql_temp.append("                        and prTchPaperTitle.Fk_Teacher = peTeacher.Id                                ");
		sql_temp.append("                        and prTchStuPaper.Fk_Stu_Id = peStudent.Id                                   ");
		sql_temp.append("                        and prTchPaperContent.Flag_Action_User = enumConstUser.Id                    ");
		sql_temp.append("                        and enumConstUser.Namespace = 'FlagActionUser'                               ");
		sql_temp.append("                        and enumConstUser.Code = '1'                                                 ");
		sql_temp.append("                        and prTchPaperContent.Flag_Paper_Section =                                   ");
		sql_temp.append("                            enumConstSection.Id                                                      ");
		sql_temp.append("                        and enumConstSection.Namespace = 'FlagPaperSection'                          ");
		sql_temp.append("                        and enumConstSection.Code = '2'                                              ");
		sql_temp.append("                        and prTchPaperContent.Note is not null                                       ");
		sql_temp.append("                      group by peTeacher.True_Name, peSemester.Name, peTeacher.Id) zhongliuyan ,      ");
		sql_temp.append("                   (select peSemester.Name as peSemester_Name,																");		
		sql_temp.append("                            peTeacher.Id as peTeacher_Id,                                    ");
		sql_temp.append("                            count(*) as num                                                  ");
		sql_temp.append("                       from PR_TCH_STU_PAPER   prTchStuPaper,                                ");
		sql_temp.append("                            PR_TCH_PAPER_TITLE prTchPaperTitle,                              ");
		sql_temp.append("                            PE_TEACHER         peTeacher,                                    ");
		sql_temp.append("                            pe_student         peStudent,                                    ");
		sql_temp.append("                            pe_semester        peSemester                                    ");
		sql_temp.append("                      where prTchPaperTitle.Fk_Semester = peSemester.Id                      ");
		sql_temp.append("                        and prTchStuPaper.Fk_Paper_Title_Id = prTchPaperTitle.Id             ");
		sql_temp.append("                        and prTchPaperTitle.Fk_Teacher = peTeacher.Id                        ");
		sql_temp.append("                        and prTchStuPaper.Fk_Stu_Id = peStudent.Id                           ");
		sql_temp.append("                        and prTchStuPaper.Id not in                                          ");
		sql_temp.append("                            (select prTchPaperContent.Fk_Tch_Stu_Paper                       ");
		sql_temp.append("                               from pr_tch_paper_content prTchPaperContent,                  ");
		sql_temp.append("                                    PR_TCH_STU_PAPER     prTchStuPaper,                      ");
		sql_temp.append("                                    PR_TCH_PAPER_TITLE   prTchPaperTitle,                    ");
		sql_temp.append("                                    PE_TEACHER           peTeacher,                          ");
		sql_temp.append("                                    pe_student           peStudent,                          ");
		sql_temp.append("                                    pe_semester          peSemester,                         ");
		sql_temp.append("                                    enum_const           enumConstUser,                      ");
		sql_temp.append("                                    enum_const           enumConstSection                    ");
		sql_temp.append("                              where prTchPaperContent.Fk_Tch_Stu_Paper =                     ");
		sql_temp.append("                                    prTchStuPaper.Id                                         ");
		sql_temp.append("                                and prTchPaperTitle.Fk_Semester = peSemester.Id              ");
		sql_temp.append("                                and prTchStuPaper.Fk_Paper_Title_Id =                        ");
		sql_temp.append("                                    prTchPaperTitle.Id                                       ");
		sql_temp.append("                                and prTchPaperTitle.Fk_Teacher = peTeacher.Id                ");
		sql_temp.append("                                and prTchStuPaper.Fk_Stu_Id = peStudent.Id                   ");
		sql_temp.append("                                and prTchPaperContent.Flag_Action_User =                     ");
		sql_temp.append("                                    enumConstUser.Id                                         ");
		sql_temp.append("                                and enumConstUser.Namespace = 'FlagActionUser'               ");
		sql_temp.append("                                and enumConstUser.Code = '1'                                 ");
		sql_temp.append("                                and prTchPaperContent.Flag_Paper_Section =                   ");
		sql_temp.append("                                    enumConstSection.Id                                      ");
		sql_temp.append("                                and prTchPaperContent.Url is not null                        ");
		sql_temp.append("                              group by prTchPaperContent.Fk_Tch_Stu_Paper)                   ");
		sql_temp.append("                      group by peSemester.Name, peTeacher.Id) weitijiao,                     ");
		sql_temp.append("                    (select peSemester.Name as peSemester_Name,                              ");
		sql_temp.append("                            peTeacher.Id as peTeacher_Id,                                    ");
		sql_temp.append("                            count(*) as num                                                  ");
		sql_temp.append("                       from PR_TCH_STU_PAPER   prTchStuPaper,                                ");
		sql_temp.append("                            PR_TCH_PAPER_TITLE prTchPaperTitle,                              ");
		sql_temp.append("                            PE_TEACHER         peTeacher,                                    ");
		sql_temp.append("                            pe_student         peStudent,                                    ");
		sql_temp.append("                            pe_semester        peSemester                                    ");
		sql_temp.append("                      where prTchPaperTitle.Fk_Semester = peSemester.Id                      ");
		sql_temp.append("                        and prTchStuPaper.Fk_Paper_Title_Id = prTchPaperTitle.Id             ");
		sql_temp.append("                        and prTchPaperTitle.Fk_Teacher = peTeacher.Id                        ");
		sql_temp.append("                        and prTchStuPaper.Fk_Stu_Id = peStudent.Id                           ");
		sql_temp.append("                        and prTchStuPaper.Id not in                                          ");
		sql_temp.append("                            (select prTchPaperContent.Fk_Tch_Stu_Paper											");	
		sql_temp.append("                               from pr_tch_paper_content prTchPaperContent,                ");
		sql_temp.append("                                    PR_TCH_STU_PAPER     prTchStuPaper,                    ");
		sql_temp.append("                                    PR_TCH_PAPER_TITLE   prTchPaperTitle,                  ");
		sql_temp.append("                                    PE_TEACHER           peTeacher,                        ");
		sql_temp.append("                                    pe_student           peStudent,                        ");
		sql_temp.append("                                    pe_semester          peSemester,                       ");
		sql_temp.append("                                    enum_const           enumConstUser,                    ");
		sql_temp.append("                                    enum_const           enumConstSection                  ");
		sql_temp.append("                              where prTchPaperContent.Fk_Tch_Stu_Paper =                   ");
		sql_temp.append("                                    prTchStuPaper.Id                                       ");
		sql_temp.append("                                and prTchPaperTitle.Fk_Semester = peSemester.Id            ");
		sql_temp.append("                                and prTchStuPaper.Fk_Paper_Title_Id =                      ");
		sql_temp.append("                                    prTchPaperTitle.Id                                     ");
		sql_temp.append("                                and prTchPaperTitle.Fk_Teacher = peTeacher.Id              ");
		sql_temp.append("                                and prTchStuPaper.Fk_Stu_Id = peStudent.Id                 ");
		sql_temp.append("                                and prTchPaperContent.Flag_Action_User =                   ");
		sql_temp.append("                                    enumConstUser.Id                                       ");
		sql_temp.append("                                and enumConstUser.Namespace = 'FlagActionUser'             ");
		sql_temp.append("                                and enumConstUser.Code = '1'                               ");
		sql_temp.append("                                and prTchPaperContent.Flag_Paper_Section =                 ");
		sql_temp.append("                                    enumConstSection.Id                                    ");
		sql_temp.append("                                and prTchPaperContent.Note is not null                     ");
		sql_temp.append("                              group by prTchPaperContent.Fk_Tch_Stu_Paper)                 ");
		sql_temp.append("                      group by peSemester.Name, peTeacher.Id) weiliuyan                    "); 		
		sql_temp.append("              where shuliang.peTeacher_Id = chugaotijiao.peTeacher_Id(+)                             ");
		sql_temp.append("                and shuliang.peTeacher_Id = zhonggaoliuyan.peTeacher_Id(+)                           ");
		sql_temp.append("                and shuliang.peTeacher_Id = zhonggaotijiao.peTeacher_Id(+)                           ");
		sql_temp.append("                and shuliang.peTeacher_Id = chugaoliuyan.peTeacher_Id(+)                             ");
		sql_temp.append("                and shuliang.peTeacher_Id = kaititijiao.peTeacher_Id(+)                              ");
		sql_temp.append("                and shuliang.peTeacher_Id = kaitiliuyan.peTeacher_Id(+)                              ");
		sql_temp.append("                and shuliang.peSemester_Name = chugaotijiao.peSemester_Name(+)                       ");
		sql_temp.append("                and shuliang.peSemester_Name = zhonggaoliuyan.peSemester_Name(+)                     ");
		sql_temp.append("                and shuliang.peSemester_Name = zhonggaotijiao.peSemester_Name(+)                     ");
		sql_temp.append("                and shuliang.peSemester_Name = chugaoliuyan.peSemester_Name(+)                       ");
		sql_temp.append("                and shuliang.peSemester_Name = kaititijiao.peSemester_Name(+)                        ");
		sql_temp.append("                and shuliang.peSemester_Name = kaitiliuyan.peSemester_Name(+)                        ");
		sql_temp.append("                and shuliang.peTeacher_Id = kaitijiao.peTeacher_Id(+)                                ");
		sql_temp.append("                and shuliang.peTeacher_Id = chutijiao.peTeacher_Id(+)                                ");
		sql_temp.append("                and shuliang.peTeacher_Id = kailiuyan.peTeacher_Id(+)                                ");
		sql_temp.append("                and shuliang.peTeacher_Id = zhongtijiao.peTeacher_Id(+)                              ");
		sql_temp.append("                and shuliang.peTeacher_Id = chuliuyan.peTeacher_Id(+)                                ");
		sql_temp.append("                and shuliang.peTeacher_Id = zhongliuyan.peTeacher_Id(+)                              ");
		sql_temp.append("                and shuliang.peSemester_Name = kaitijiao.peSemester_Name(+)                          ");
		sql_temp.append("                and shuliang.peSemester_Name = chutijiao.peSemester_Name(+)                          ");
		sql_temp.append("                and shuliang.peSemester_Name = zhongtijiao.peSemester_Name(+)                        ");
		sql_temp.append("                and shuliang.peSemester_Name = zhongliuyan.peSemester_Name(+)                        ");
		sql_temp.append("                and shuliang.peSemester_Name = kailiuyan.peSemester_Name(+)                          ");
		sql_temp.append("                and shuliang.peSemester_Name = chuliuyan.peSemester_Name(+)                          ");
		sql_temp.append("                  and shuliang.peSemester_Name = weitijiao.peSemester_Name(+)     ");	                                           
		sql_temp.append("                  and shuliang.peSemester_Name = weiliuyan.peSemester_Name(+)     ");                                           
		sql_temp.append("                  and shuliang.peTeacher_Id = weitijiao.peTeacher_Id(+)           ");                                           
		sql_temp.append("                  and shuliang.peTeacher_Id = weiliuyan.peTeacher_Id(+)           ");                                           
		sql_temp.append("              group by shuliang.peSemester_Name,                                                     ");
		sql_temp.append("                       shuliang.peTeacher_Name,                                                      ");
		sql_temp.append("                       shuliang.student,                                                             ");
		sql_temp.append("                       chutijiao.num,                                                                ");
		sql_temp.append("                       zhongliuyan.num,                                                              ");
		sql_temp.append("                       zhongtijiao.num,                                                              ");
		sql_temp.append("                       chuliuyan.num,                                                                ");
		sql_temp.append("                       kailiuyan.num,                                                                ");
		sql_temp.append("                       kaitijiao.num,                                                                ");
		sql_temp.append("                       chugaotijiao.num,                                                             ");
		sql_temp.append("                       zhonggaoliuyan.num,                                                           ");
		sql_temp.append("                       zhonggaotijiao.num,                                                           ");
		
		sql_temp.append("                       weitijiao.num,                                                            ");
		sql_temp.append("                       weiliuyan.num,                                                              ");
		
		sql_temp.append("                       chugaoliuyan.num,                                                             ");
		sql_temp.append("                       kaitiliuyan.num,                                                              ");
		sql_temp.append("                       kaititijiao.num,                                                              ");
		sql_temp.append("                       shuliang.peSemester_Id,                                                       ");
		sql_temp.append("                       shuliang.peTeacher_Id) one																										");	
		this.setSqlCondition(sql_temp);
		Page page = null;
		try {
			page = getGeneralService().getByPageSQL(sql_temp.toString(),
					Integer.parseInt(this.getLimit()),
					Integer.parseInt(this.getStart()));
		} catch (NumberFormatException e) {
			e.printStackTrace();
		} catch (Exception e) {
			e.printStackTrace();
		}
		return page;
	}



	@Override
	public void setEntityClass() {
		// TODO Auto-generated method stub
		
	}


	@Override
	public void setServletPath() {
		this.servletPath="/entity/teaching/paperProcessTeacher";
	}

}
