ALTER TABLE `invigilation_teacher`
ADD COLUMN `BANK_CARD`  varchar(20) NULL DEFAULT '' COMMENT '交通银行银行卡卡号' AFTER `REMARK`;

ALTER TABLE `invigilation_teacher`
ADD COLUMN `OPENID`  varchar(64) NULL DEFAULT '' COMMENT '微信识别唯一ID' AFTER `BANK_CARD`;

ALTER TABLE `invigilation_teacher`
ADD COLUMN `SID`  varchar(20) NULL DEFAULT '' COMMENT '学工号' AFTER `OPENID`;

ALTER TABLE `exam_information`
MODIFY COLUMN `INFORMATION`  text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '考试信息' AFTER `INTEGRAL`,
MODIFY COLUMN `INVIGILATION_CONTRACT`  text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '监考责任书' AFTER `INFORMATION`;

ALTER TABLE `invigilation_teacher`
ADD INDEX `INDEX_OPENID` USING BTREE (`OPENID`) ;

ALTER TABLE `exam_room`
MODIFY COLUMN `EXAMINATION_TIME`  varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '单场考试时间(yyyy年mm月dd日hh:MM-hh:MM)' AFTER `ROOM_ADDRESS`;

ALTER TABLE `exam_room`
MODIFY COLUMN `EXAMINATION_INFORMATION`  varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '单场考试学科或内容' AFTER `EXAMINATION_TIME`;

ALTER TABLE `exam_teacher_room`
ADD INDEX `INDEX_TEACHERROOM_STATUS` USING BTREE (`STATUS`) ,
ADD INDEX `INDEX_TEACHERROOM_ISCONFIRM` USING BTREE (`IS_CONFIRM`) ,
ADD INDEX `INDEX_TEACHERROOM_ISFIRST` USING BTREE (`IS_FIRST_APPLY`) ,
ADD INDEX `INDEX_TEACHERROOM_ISCHIEF` USING BTREE (`IS_CHIEF`) ;

ALTER TABLE `invigilation_teacher`
ADD COLUMN `PASSWORD`  varchar(20) NOT NULL COMMENT '教师登录密码，默认为身份证后6位' AFTER `SID`;


ALTER TABLE `invigilation_teacher`
ADD UNIQUE INDEX `UNIQUE_IDCARD` USING BTREE (`IDCARD`) ;




ALTER TABLE `invigilation_teacher`
ADD UNIQUE INDEX `UNIQUE_MOBILE` USING BTREE (`MOBILE`) ;


