/*
 * JSP generated by Resin-3.1.3 (built Sun, 07 Oct 2007 03:58:02 PDT)
 */

package _jsp._entity._manager._programapply;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _prprogramunit_0batch__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html;charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    org.apache.struts2.views.jsp.ui.FormTag _jsp_FormTag_0 = null;
    org.apache.struts2.views.jsp.PropertyTag _jsp_PropertyTag_1 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      com.caucho.jsp.BodyContentImpl _jsp_endTagHack0 = null;
      if (_jsp_FormTag_0 == null) {
        _jsp_FormTag_0 = new org.apache.struts2.views.jsp.ui.FormTag();
        _jsp_FormTag_0.setPageContext(pageContext);
        _jsp_FormTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_FormTag_0.setName("usualBatch");
        _jsp_FormTag_0.setAction("/entity/programApply/prProgramUnit_applyNoBatch.action");
        _jsp_FormTag_0.setMethod("POST");
        _jsp_FormTag_0.setEnctype("multipart/form-data");
        _jsp_FormTag_0.setOnsubmit("return FileTypeCheck();");
      }

      int _jspEval2 = _jsp_FormTag_0.doStartTag();
      if (_jspEval2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspEval2 == javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_BUFFERED) {
          out = pageContext.pushBody();
          _jsp_endTagHack0 = (com.caucho.jsp.BodyContentImpl) out;
          _jsp_FormTag_0.setBodyContent(_jsp_endTagHack0);
        }
        out.write(_jsp_string1, 0, _jsp_string1.length);
        if (_jsp_PropertyTag_1 == null) {
          _jsp_PropertyTag_1 = new org.apache.struts2.views.jsp.PropertyTag();
          _jsp_PropertyTag_1.setPageContext(pageContext);
          _jsp_PropertyTag_1.setParent((javax.servlet.jsp.tagext.Tag) _jsp_FormTag_0);
          _jsp_PropertyTag_1.setEscape(false);
        }

        _jsp_PropertyTag_1.setValue("msg");
        int _jspEval5 = _jsp_PropertyTag_1.doStartTag();
        _jsp_PropertyTag_1.doEndTag();
        out.write(_jsp_string2, 0, _jsp_string2.length);
        _jsp_PropertyTag_1.setValue("bean.peProApplyno.id");
        int _jspEval9 = _jsp_PropertyTag_1.doStartTag();
        _jsp_PropertyTag_1.doEndTag();
        out.write(_jsp_string3, 0, _jsp_string3.length);
        if (_jspEval2 == javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_BUFFERED)
          out = pageContext.popBody();
      }
      _jsp_FormTag_0.doEndTag();
      if (_jsp_endTagHack0 != null) {
        pageContext.releaseBody(_jsp_endTagHack0);
        _jsp_endTagHack0 = null;
      }
      out.write(_jsp_string4, 0, _jsp_string4.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_FormTag_0 != null)
        _jsp_FormTag_0.release();
      if (_jsp_PropertyTag_1 != null)
        _jsp_PropertyTag_1.release();
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != -9019483982733035993L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    manager.addTaglibFunctions(_jsp_functionMap, "s", "/WEB-INF/struts-tags.tld");
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("entity/manager/programApply/prProgramUnit_batch.jsp"), -7452904663594418311L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/struts-tags.tld"), 2632518462704396565L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.struts2.views.jsp.PropertyTag.class, 3516723674932103087L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.struts2.views.jsp.ui.FormTag.class, -5127918882550739581L));
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }

  private final static char []_jsp_string2;
  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  private final static char []_jsp_string4;
  private final static char []_jsp_string3;
  static {
    _jsp_string2 = "</FONT></p>\r\n          <table width=\"68%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n            \r\n            <tr valign=\"bottom\" class=\"postFormBox\"> \r\n              <td width=\"23%\"  valign=\"bottom\"><span class=\"name\">\u4e0b\u8f7d\u6807\u51c6\u683c\u5f0f:</span></td>\r\n              <td width=\"77%\"> <span class=\"link\" help=\"\u4e0b\u8f7dExcel\u683c\u5f0f\u7684\u6a21\u7248\u8868\u683c\"><img src='/entity/manager/images/buttons/excel.png' alt='Print' width=\"20\" height=\"20\" title='Print'>&nbsp;<a href='prProgramUnit_batch.xls' target=_blank>Excel\u62a5\u8868</a></span></td>\r\n            </tr>\r\n            <tr valign=\"bottom\" class=\"postFormBox\"> \r\n              <td valign=\"bottom\"><span class=\"name\">\u7533\u62a5\u6570\u91cf\u4fe1\u606f*:</span></td>\r\n              <td valign=\"bottom\"><input type=file name=\"upload\" id=\"src\"/></td>\r\n            </tr>\r\n             <input type=\"text\" name=\"bean.peProApplyno.id\" value=\"".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n<title>\u7533\u62a5\u6570\u91cf\u6279\u91cf\u5bfc\u5165</title>\r\n<link href=\"/entity/manager/css/admincss.css\" rel=\"stylesheet\" type=\"text/css\">\r\n<script>\r\n	//\u6587\u4ef6\u7c7b\u578b(*.xls)\r\n	 function FileTypeCheck()\r\n  {  document.getElementById('submit1').disabled = true;\r\n  var obj =document.getElementById('src');\r\n  if(obj.value==null || obj.value ==''){\r\n  	alert('\u8bf7\u9009\u62e9\u4e0a\u4f20\u6587\u4ef6\uff01');\r\n  	this.focus();\r\n  	document.getElementById('submit1').disabled = false;\r\n  	return false;\r\n  }\r\n  var length = obj.value.length;\r\n  var charindex = obj.value.lastIndexOf(\".\");\r\n  var ExtentName = obj.value.substring(charindex,charindex+4);\r\n  if(!(ExtentName == \".xls\" )){\r\n  	alert('\u6587\u4ef6\u683c\u5f0f\u4e0d\u6b63\u786e\uff01');\r\n  	this.focus();\r\n  	document.getElementById('submit1').disabled = false;\r\n  	return false;\r\n  }\r\n  	return true;\r\n  }\r\n  	\r\n</script>\r\n</head>\r\n<body leftmargin=\"0\" topmargin=\"0\" class=\"scllbar\">\r\n".toCharArray();
    _jsp_string1 = "\r\n<table width=\"80%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n  <tr> \r\n    <td><div class=\"content_title\" id=\"zlb_title_start\">\u6279\u91cf\u5bfc\u5165\u7533\u62a5\u6570\u91cf</div></td>\r\n  </tr>\r\n  \r\n            \r\n  <tr> \r\n    <td valign=\"top\" class=\"pageBodyBorder_zlb\" align=\"center\"> \r\n        <div class=\"cntent_k\" id=\"zlb_content_start\">\r\n          <p><FONT color=\"red\">".toCharArray();
    _jsp_string4 = "\r\n</body>\r\n</html>".toCharArray();
    _jsp_string3 = "\">       \r\n            \r\n            <tr class=\"postFormBox\">\r\n              <td ></td>\r\n              <td><input type=submit id=\"submit1\" value = \"\u4e0a\u4f20\" /></td>\r\n            </tr>\r\n         </table>\r\n      </div>\r\n\r\n    </td>\r\n  </tr>\r\n    <tr> \r\n    <td><div class=\"content_title\" >\u4f7f\u7528\u8bf4\u660e</div></td>\r\n  </tr>    \r\n    <tr>\r\n    <td >\r\n        <div class=\"cntent_k\">\r\n        <span class=\"name\">\u4f7f\u7528\u65b9\u6cd5\u4e00\uff1a</span><br/>\r\n        1\u3001\u4e0b\u8f7d\u6807\u51c6\u683c\u5f0f\uff0c\u6309\u8981\u6c42\u586b\u5199\u76f8\u5e94\u5185\u5bb9\u3002\u4e0a\u4f20\u6587\u4ef6\u3002<br/>\r\n         <span class=\"name\">\u4f7f\u7528\u65b9\u6cd5\u4e8c\uff1a</span><br/>\r\n        1\u3001\u5230\u57fa\u7840\u6570\u636e\u5355\u4f4d\u7ba1\u7406\u5217\u8868\u9875\u9762\uff0c\u67e5\u8be2\u51fa\u6240\u9700\u5bfc\u5165\u7533\u62a5\u6570\u91cf\u7684\u5355\u4f4d\u3002\u4e0b\u65b9\u9009\u62e9\u62a5\u8868\u683c\u5f0f\uff0c\u9009\u62e9Excel\u5bfc\u51fa\u3002<br/>\r\n        2\u3001\u6253\u5f00\u4e0b\u8f7d\u540e\u7684\u62a5\u8868\uff0c\u4fdd\u7559 \u540d\u79f0 \u8fd9\u4e00\u5217\uff0c\u5176\u4f59\u5217\u5168\u90e8\u5220\u9664\u3002<br/>\r\n        3\u3001\u586b\u5199\u5355\u4f4d\u5bf9\u5e94\u7684\u7533\u62a5\u6570\u91cf\uff0c\u586b\u5199\u5b8c\u540e\u4fdd\u5b58\u3002<br/>\r\n        4\u3001\u4e0a\u4f20\u4fee\u6539\u5b8c\u6210\u540e\u7684Excel\u8868\u683c\u3002<br/>\r\n      </div>\r\n     </td>\r\n  </tr>\r\n</table>\r\n".toCharArray();
  }
}
