    truncate table TSALESRESULTFORSTATISTIC;
    
    DECLARE @V_PRE_PRODUCT_TYPE INT,@V_RECORDS_COUNT INT
    DECLARE @V_PRE_PRODUCT_TYPE_NAME NVARCHAR(50)  
   
    SET @V_PRE_PRODUCT_TYPE = 1
    SET @V_RECORDS_COUNT = 1
    SET @V_PRE_PRODUCT_TYPE_NAME = N'直销(工作台)'

	insert into TSALESRESULTFORSTATISTIC(PRE_SERIAL_NO,DZ_DATE,DZ_MONEY,JK_TYPE,JK_TYPE_NAME,INPUT_MAN,
	ONWAY_FLAG,PRE_PRODUCT_TYPE,PRE_PRODUCT_TYPE_NAME,FK_TPREMONEYDETAIL,RECORDS_COUNT)
	select [PRE_SERIAL_NO],[DZ_DATE],[DZ_MONEY],[JK_TYPE],[JK_TYPE_NAME],[INPUT_MAN]
      ,[ONWAY_FLAG],@V_PRE_PRODUCT_TYPE as PRE_PRODUCT_TYPE,
	@V_PRE_PRODUCT_TYPE_NAME as PRE_PRODUCT_TYPE_NAME,t.SERIAL_NO as FK_TPREMONEYDETAIL,
	@V_RECORDS_COUNT as RECORDS_COUNT 
	from TPREMONEYDETAIL t
	--(20349 行受影响)
	
	select COUNT(*) from TPREMONEYDETAIL


