
INSERT [dbo].[TMENUINFO] ([MENU_ID], [MENU_NAME], [MENU_INFO], [PARENT_ID], [BOTTOM_FLAG], [URL], [LINKTO], [TREE_ORDER], [USER_ID], [MENU_NAME_EN], [MENU_INFO_EN], [ICON_CLS]) 
VALUES (N'20199', N'客户联系方式修改', N'客户资料>>客户联系方式修改', N'201', 1, N'/client/clientinfo/client_info_list_c.jsp', NULL, NULL, 0, NULL, NULL, NULL)

INSERT [dbo].[TFUNCTYPE] ([MENU_ID], [FUNC_ID], [FUNC_NAME], [USER_ID], [URL], [ICON_CLS]) VALUES (N'20199', 102, N'查询', 0, NULL, NULL)

INSERT [dbo].[TFUNCTYPE] ([MENU_ID], [FUNC_ID], [FUNC_NAME], [USER_ID], [URL], [ICON_CLS]) VALUES (N'20199', 100, N'确认', 0, NULL, NULL)

INSERT [dbo].[TFUNCTYPE] ([MENU_ID], [FUNC_ID], [FUNC_NAME], [USER_ID], [URL], [ICON_CLS]) VALUES (N'20199', 101, N'审核', 0, NULL, NULL)

