
INSERT [dbo].[TMENUINFO] ([MENU_ID], [MENU_NAME], [MENU_INFO], [PARENT_ID], [BOTTOM_FLAG], [URL], [LINKTO], [TREE_ORDER], [USER_ID], [MENU_NAME_EN], [MENU_INFO_EN], [ICON_CLS]) 
VALUES (N'30293', N'转销量', N'销售管理>>转销量', N'302', 1, N'/marketing/sell/sales_changes_list.jsp', NULL, NULL, 0, NULL, NULL, NULL)

INSERT [dbo].[TMENUINFO] ([MENU_ID], [MENU_NAME], [MENU_INFO], [PARENT_ID], [BOTTOM_FLAG], [URL], [LINKTO], [TREE_ORDER], [USER_ID], [MENU_NAME_EN], [MENU_INFO_EN], [ICON_CLS]) 
VALUES (N'30294', N'转销量结果统计', N'销售管理>>转销量结果统计', N'302', 1, N'/marketing/sell/sales_changes_result_list.jsp', NULL, NULL, 0, NULL, NULL, NULL)

INSERT [dbo].[TFUNCTYPE] ([MENU_ID], [FUNC_ID], [FUNC_NAME], [USER_ID], [URL], [ICON_CLS]) VALUES (N'30293', 103, N'撤销', 0, NULL, NULL)

INSERT [dbo].[TFUNCTYPE] ([MENU_ID], [FUNC_ID], [FUNC_NAME], [USER_ID], [URL], [ICON_CLS]) VALUES (N'30293', 102, N'查询', 0, NULL, NULL)

INSERT [dbo].[TFUNCTYPE] ([MENU_ID], [FUNC_ID], [FUNC_NAME], [USER_ID], [URL], [ICON_CLS]) VALUES (N'30293', 100, N'确认', 0, NULL, NULL)

INSERT [dbo].[TFUNCTYPE] ([MENU_ID], [FUNC_ID], [FUNC_NAME], [USER_ID], [URL], [ICON_CLS]) VALUES (N'30293', 101, N'审核', 0, NULL, NULL)


INSERT [dbo].[TFUNCTYPE] ([MENU_ID], [FUNC_ID], [FUNC_NAME], [USER_ID], [URL], [ICON_CLS]) VALUES (N'30294', 101, N'查询', 0, NULL, NULL)

INSERT [dbo].[TFUNCTYPE] ([MENU_ID], [FUNC_ID], [FUNC_NAME], [USER_ID], [URL], [ICON_CLS]) VALUES (N'30294', 102, N'编辑', 0, NULL, NULL)

INSERT [dbo].[TFUNCTYPE] ([MENU_ID], [FUNC_ID], [FUNC_NAME], [USER_ID], [URL], [ICON_CLS]) VALUES (N'30294', 103, N'增加', 0, NULL, NULL)

