--Ôö¼Ó×Ö¶Î

--ALTER TABLE TCUSTOMOERS_CONNECTION_MODI ADD APPLY_REASON NVARCHAR(200) NULL
--ALTER TABLE TCUSTOMOERS_CONNECTION_MODI ADD CHECK_REASON NVARCHAR(200) NULL
--ALTER TABLE TCUSTOMOERS_CONNECTION_MODI ADD RE_CHECK_REASON NVARCHAR(200) NULL

--ÐÞ¸Ä×Ö¶Î
exec sp_rename 'TCUSTOMOERS_CONNECTION_MODI.RE_CHAECK_REASON','RE_CHECK_REASON'