# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lucky' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lucky
  pod 'AFNetworking'
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'
  pod 'SDWebImage'
  pod 'SDWebImageFLPlugin'
  pod 'FLAnimatedImage'
  pod 'MBProgressHUD'
  pod 'FJPreImageView'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
end
