create user tchr_reader identified by GPjh2018;

grant connect to tchr_reader;

select 'create or replace synonym tchr_reader.'||object_name||' for '||owner||'.'||object_name||';'
from dba_objects 
where owner in ('TCHR_TRAINING1') and object_type='TABLE';

select 'grant select on '||owner||'.'||object_name||' to tchr_reader;'
from dba_objects 
where owner in ('TCHR_TRAINING1') and object_type='TABLE';

commit;

select count(*) from trainee ; 

grant select on TCHR_TRAINING1.WHATYUSER_LOG4J to tchr_reader;
grant select on TCHR_TRAINING1.UNIT_TYPE to tchr_reader;
grant select on TCHR_TRAINING1.UNIT_ATTRIBUTE to tchr_reader;
grant select on TCHR_TRAINING1.TRAINHISTORY to tchr_reader;
grant select on TCHR_TRAINING1.TRAINEE to tchr_reader;
grant select on TCHR_TRAINING1.SYSTEM_VARIABLES to tchr_reader;
grant select on TCHR_TRAINING1.SUBMIT to tchr_reader;
grant select on TCHR_TRAINING1.SSO_USER to tchr_reader;
grant select on TCHR_TRAINING1.RESULT to tchr_reader;
grant select on TCHR_TRAINING1.QUESTION to tchr_reader;
grant select on TCHR_TRAINING1.PSQPROJECTMAP to tchr_reader;
grant select on TCHR_TRAINING1.PSQ to tchr_reader;
grant select on TCHR_TRAINING1.PR_VOTE_SUGGEST to tchr_reader;
grant select on TCHR_TRAINING1.PR_VOTE_RECORD to tchr_reader;
grant select on TCHR_TRAINING1.PR_VOTE_QUESTION to tchr_reader;
grant select on TCHR_TRAINING1.PR_VOTE_ANSWER to tchr_reader;
grant select on TCHR_TRAINING1.PR_PRO_SUMMARY to tchr_reader;
grant select on TCHR_TRAINING1.PR_PRO_EXPERT to tchr_reader;
grant select on TCHR_TRAINING1.PR_PROGRAM_UNIT to tchr_reader;
grant select on TCHR_TRAINING1.PR_PRI_ROLE to tchr_reader;
grant select on TCHR_TRAINING1.PR_MAN_PRONO to tchr_reader;
grant select on TCHR_TRAINING1.PR_JOB_UNIT to tchr_reader;
grant select on TCHR_TRAINING1.PROCHILDEXPERT to tchr_reader;
grant select on TCHR_TRAINING1.PROCHILDAPPLYNO to tchr_reader;
grant select on TCHR_TRAINING1.PROCHILDAPPLY to tchr_reader;
grant select on TCHR_TRAINING1.PE_WORKPLACE to tchr_reader;
grant select on TCHR_TRAINING1.PE_VOTE_PAPER to tchr_reader;
grant select on TCHR_TRAINING1.PE_VOTE_DETAIL to tchr_reader;
grant select on TCHR_TRAINING1.PE_VALUA_EXPERT to tchr_reader;
grant select on TCHR_TRAINING1.PE_UNIT to tchr_reader;
grant select on TCHR_TRAINING1.PE_TRAIN_EXPERT to tchr_reader;
grant select on TCHR_TRAINING1.PE_TRAINEE_ADU to tchr_reader;
grant select on TCHR_TRAINING1.PE_TRAINEE to tchr_reader;
grant select on TCHR_TRAINING1.PE_SUBJECT to tchr_reader;
grant select on TCHR_TRAINING1.PE_PRO_JUDGMENT_SCORE_DETAIL to tchr_reader;
grant select on TCHR_TRAINING1.PE_PRO_JUDGMENT_SCORE to tchr_reader;
grant select on TCHR_TRAINING1.PE_PRO_IMPLEMT to tchr_reader;
grant select on TCHR_TRAINING1.PE_PRO_APPLY_JUDGMENT_STAND to tchr_reader;
grant select on TCHR_TRAINING1.PE_PRO_APPLYNO to tchr_reader;
grant select on TCHR_TRAINING1.PE_PRO_APPLY to tchr_reader;
grant select on TCHR_TRAINING1.PE_PROVINCE to tchr_reader;
grant select on TCHR_TRAINING1.PE_PRI_ROLE to tchr_reader;
grant select on TCHR_TRAINING1.PE_PRI_CATEGORY to tchr_reader;
grant select on TCHR_TRAINING1.PE_PRIORITY to tchr_reader;
grant select on TCHR_TRAINING1.PE_POLICY to tchr_reader;
grant select on TCHR_TRAINING1.PE_OTHER_MATERIAL to tchr_reader;
grant select on TCHR_TRAINING1.PE_NOTE_HISTORY to tchr_reader;
grant select on TCHR_TRAINING1.PE_MANAGER to tchr_reader;
grant select on TCHR_TRAINING1.PE_JOB to tchr_reader;
grant select on TCHR_TRAINING1.PE_FEE_BUDGET_NEWTWODETAIL to tchr_reader;
grant select on TCHR_TRAINING1.PE_FEE_BUDGET_NEWDETAIL to tchr_reader;
grant select on TCHR_TRAINING1.PE_FEE_BUDGET_DETAIL to tchr_reader;
grant select on TCHR_TRAINING1.PE_FEE_BUDGET to tchr_reader;
grant select on TCHR_TRAINING1.PE_FEE_ACTUAL_BUDGET_TWODETAIL to tchr_reader;
grant select on TCHR_TRAINING1.PE_FEE_ACTUAL_BUDGET_NEWDETAIL to tchr_reader;
grant select on TCHR_TRAINING1.PE_FEE_ACTUAL_BUDGET_DETAIL to tchr_reader;
grant select on TCHR_TRAINING1.PE_FEE_ACTUAL_BUDGET to tchr_reader;
grant select on TCHR_TRAINING1.PE_EXPERT_SEARCH_HISTORY to tchr_reader;
grant select on TCHR_TRAINING1.PE_COURSE_PLAN to tchr_reader;
grant select on TCHR_TRAINING1.PE_BULLETIN to tchr_reader;
grant select on TCHR_TRAINING1.PE_BRIEF_REPORT to tchr_reader;
grant select on TCHR_TRAINING1.PEBUDGETMPNEWTWO to tchr_reader;
grant select on TCHR_TRAINING1.PEBUDGETMPNEW to tchr_reader;
grant select on TCHR_TRAINING1.PEBUDGETMP to tchr_reader;
grant select on TCHR_TRAINING1.PEACTUALBUDGETNEWTWO to tchr_reader;
grant select on TCHR_TRAINING1.PEACTUALBUDGETNEW to tchr_reader;
grant select on TCHR_TRAINING1.PEACTUALBUDGET to tchr_reader;
grant select on TCHR_TRAINING1.MAIN_TEACHING_SUBJECT to tchr_reader;
grant select on TCHR_TRAINING1.MAIN_TEACHING_GRADE to tchr_reader;
grant select on TCHR_TRAINING1.LOGINKEY to tchr_reader;
grant select on TCHR_TRAINING1.JOB_TITLE to tchr_reader;
grant select on TCHR_TRAINING1.JHTRAINEE to tchr_reader;
grant select on TCHR_TRAINING1.FOLK to tchr_reader;
grant select on TCHR_TRAINING1.ENUM_CONST to tchr_reader;
grant select on TCHR_TRAINING1.EDUCATION to tchr_reader;
grant select on TCHR_TRAINING1.COUNTY to tchr_reader;
grant select on TCHR_TRAINING1.CITY to tchr_reader;
grant select on TCHR_TRAINING1.ANSWER to tchr_reader;


create or replace synonym tchr_reader.WHATYUSER_LOG4J for TCHR_TRAINING1.WHATYUSER_LOG4J;
create or replace synonym tchr_reader.UNIT_TYPE for TCHR_TRAINING1.UNIT_TYPE;
create or replace synonym tchr_reader.UNIT_ATTRIBUTE for TCHR_TRAINING1.UNIT_ATTRIBUTE;
create or replace synonym tchr_reader.TRAINHISTORY for TCHR_TRAINING1.TRAINHISTORY;
create or replace synonym tchr_reader.TRAINEE for TCHR_TRAINING1.TRAINEE;
create or replace synonym tchr_reader.SYSTEM_VARIABLES for TCHR_TRAINING1.SYSTEM_VARIABLES;
create or replace synonym tchr_reader.SUBMIT for TCHR_TRAINING1.SUBMIT;
create or replace synonym tchr_reader.SSO_USER for TCHR_TRAINING1.SSO_USER;
create or replace synonym tchr_reader.RESULT for TCHR_TRAINING1.RESULT;
create or replace synonym tchr_reader.QUESTION for TCHR_TRAINING1.QUESTION;
create or replace synonym tchr_reader.PSQPROJECTMAP for TCHR_TRAINING1.PSQPROJECTMAP;
create or replace synonym tchr_reader.PSQ for TCHR_TRAINING1.PSQ;
create or replace synonym tchr_reader.PR_VOTE_SUGGEST for TCHR_TRAINING1.PR_VOTE_SUGGEST;
create or replace synonym tchr_reader.PR_VOTE_RECORD for TCHR_TRAINING1.PR_VOTE_RECORD;
create or replace synonym tchr_reader.PR_VOTE_QUESTION for TCHR_TRAINING1.PR_VOTE_QUESTION;
create or replace synonym tchr_reader.PR_VOTE_ANSWER for TCHR_TRAINING1.PR_VOTE_ANSWER;
create or replace synonym tchr_reader.PR_PRO_SUMMARY for TCHR_TRAINING1.PR_PRO_SUMMARY;
create or replace synonym tchr_reader.PR_PRO_EXPERT for TCHR_TRAINING1.PR_PRO_EXPERT;
create or replace synonym tchr_reader.PR_PROGRAM_UNIT for TCHR_TRAINING1.PR_PROGRAM_UNIT;
create or replace synonym tchr_reader.PR_PRI_ROLE for TCHR_TRAINING1.PR_PRI_ROLE;
create or replace synonym tchr_reader.PR_MAN_PRONO for TCHR_TRAINING1.PR_MAN_PRONO;
create or replace synonym tchr_reader.PR_JOB_UNIT for TCHR_TRAINING1.PR_JOB_UNIT;
create or replace synonym tchr_reader.PROCHILDEXPERT for TCHR_TRAINING1.PROCHILDEXPERT;
create or replace synonym tchr_reader.PROCHILDAPPLYNO for TCHR_TRAINING1.PROCHILDAPPLYNO;
create or replace synonym tchr_reader.PROCHILDAPPLY for TCHR_TRAINING1.PROCHILDAPPLY;
create or replace synonym tchr_reader.PE_WORKPLACE for TCHR_TRAINING1.PE_WORKPLACE;
create or replace synonym tchr_reader.PE_VOTE_PAPER for TCHR_TRAINING1.PE_VOTE_PAPER;
create or replace synonym tchr_reader.PE_VOTE_DETAIL for TCHR_TRAINING1.PE_VOTE_DETAIL;
create or replace synonym tchr_reader.PE_VALUA_EXPERT for TCHR_TRAINING1.PE_VALUA_EXPERT;
create or replace synonym tchr_reader.PE_UNIT for TCHR_TRAINING1.PE_UNIT;
create or replace synonym tchr_reader.PE_TRAIN_EXPERT for TCHR_TRAINING1.PE_TRAIN_EXPERT;
create or replace synonym tchr_reader.PE_TRAINEE_ADU for TCHR_TRAINING1.PE_TRAINEE_ADU;
create or replace synonym tchr_reader.PE_TRAINEE for TCHR_TRAINING1.PE_TRAINEE;
create or replace synonym tchr_reader.PE_SUBJECT for TCHR_TRAINING1.PE_SUBJECT;
create or replace synonym tchr_reader.PE_PRO_JUDGMENT_SCORE_DETAIL for TCHR_TRAINING1.PE_PRO_JUDGMENT_SCORE_DETAIL;
create or replace synonym tchr_reader.PE_PRO_JUDGMENT_SCORE for TCHR_TRAINING1.PE_PRO_JUDGMENT_SCORE;
create or replace synonym tchr_reader.PE_PRO_IMPLEMT for TCHR_TRAINING1.PE_PRO_IMPLEMT;
create or replace synonym tchr_reader.PE_PRO_APPLY_JUDGMENT_STAND for TCHR_TRAINING1.PE_PRO_APPLY_JUDGMENT_STAND;
create or replace synonym tchr_reader.PE_PRO_APPLYNO for TCHR_TRAINING1.PE_PRO_APPLYNO;
create or replace synonym tchr_reader.PE_PRO_APPLY for TCHR_TRAINING1.PE_PRO_APPLY;
create or replace synonym tchr_reader.PE_PROVINCE for TCHR_TRAINING1.PE_PROVINCE;
create or replace synonym tchr_reader.PE_PRI_ROLE for TCHR_TRAINING1.PE_PRI_ROLE;
create or replace synonym tchr_reader.PE_PRI_CATEGORY for TCHR_TRAINING1.PE_PRI_CATEGORY;
create or replace synonym tchr_reader.PE_PRIORITY for TCHR_TRAINING1.PE_PRIORITY;
create or replace synonym tchr_reader.PE_POLICY for TCHR_TRAINING1.PE_POLICY;
create or replace synonym tchr_reader.PE_OTHER_MATERIAL for TCHR_TRAINING1.PE_OTHER_MATERIAL;
create or replace synonym tchr_reader.PE_NOTE_HISTORY for TCHR_TRAINING1.PE_NOTE_HISTORY;
create or replace synonym tchr_reader.PE_MANAGER for TCHR_TRAINING1.PE_MANAGER;
create or replace synonym tchr_reader.PE_JOB for TCHR_TRAINING1.PE_JOB;
create or replace synonym tchr_reader.PE_FEE_BUDGET_NEWTWODETAIL for TCHR_TRAINING1.PE_FEE_BUDGET_NEWTWODETAIL;
create or replace synonym tchr_reader.PE_FEE_BUDGET_NEWDETAIL for TCHR_TRAINING1.PE_FEE_BUDGET_NEWDETAIL;
create or replace synonym tchr_reader.PE_FEE_BUDGET_DETAIL for TCHR_TRAINING1.PE_FEE_BUDGET_DETAIL;
create or replace synonym tchr_reader.PE_FEE_BUDGET for TCHR_TRAINING1.PE_FEE_BUDGET;
create or replace synonym tchr_reader.PE_FEE_ACTUAL_BUDGET_TWODETAIL for TCHR_TRAINING1.PE_FEE_ACTUAL_BUDGET_TWODETAIL;
create or replace synonym tchr_reader.PE_FEE_ACTUAL_BUDGET_NEWDETAIL for TCHR_TRAINING1.PE_FEE_ACTUAL_BUDGET_NEWDETAIL;
create or replace synonym tchr_reader.PE_FEE_ACTUAL_BUDGET_DETAIL for TCHR_TRAINING1.PE_FEE_ACTUAL_BUDGET_DETAIL;
create or replace synonym tchr_reader.PE_FEE_ACTUAL_BUDGET for TCHR_TRAINING1.PE_FEE_ACTUAL_BUDGET;
create or replace synonym tchr_reader.PE_EXPERT_SEARCH_HISTORY for TCHR_TRAINING1.PE_EXPERT_SEARCH_HISTORY;
create or replace synonym tchr_reader.PE_COURSE_PLAN for TCHR_TRAINING1.PE_COURSE_PLAN;
create or replace synonym tchr_reader.PE_BULLETIN for TCHR_TRAINING1.PE_BULLETIN;
create or replace synonym tchr_reader.PE_BRIEF_REPORT for TCHR_TRAINING1.PE_BRIEF_REPORT;
create or replace synonym tchr_reader.PEBUDGETMPNEWTWO for TCHR_TRAINING1.PEBUDGETMPNEWTWO;
create or replace synonym tchr_reader.PEBUDGETMPNEW for TCHR_TRAINING1.PEBUDGETMPNEW;
create or replace synonym tchr_reader.PEBUDGETMP for TCHR_TRAINING1.PEBUDGETMP;
create or replace synonym tchr_reader.PEACTUALBUDGETNEWTWO for TCHR_TRAINING1.PEACTUALBUDGETNEWTWO;
create or replace synonym tchr_reader.PEACTUALBUDGETNEW for TCHR_TRAINING1.PEACTUALBUDGETNEW;
create or replace synonym tchr_reader.PEACTUALBUDGET for TCHR_TRAINING1.PEACTUALBUDGET;
create or replace synonym tchr_reader.MAIN_TEACHING_SUBJECT for TCHR_TRAINING1.MAIN_TEACHING_SUBJECT;
create or replace synonym tchr_reader.MAIN_TEACHING_GRADE for TCHR_TRAINING1.MAIN_TEACHING_GRADE;
create or replace synonym tchr_reader.LOGINKEY for TCHR_TRAINING1.LOGINKEY;
create or replace synonym tchr_reader.JOB_TITLE for TCHR_TRAINING1.JOB_TITLE;
create or replace synonym tchr_reader.JHTRAINEE for TCHR_TRAINING1.JHTRAINEE;
create or replace synonym tchr_reader.FOLK for TCHR_TRAINING1.FOLK;
create or replace synonym tchr_reader.ENUM_CONST for TCHR_TRAINING1.ENUM_CONST;
create or replace synonym tchr_reader.EDUCATION for TCHR_TRAINING1.EDUCATION;
create or replace synonym tchr_reader.COUNTY for TCHR_TRAINING1.COUNTY;
create or replace synonym tchr_reader.CITY for TCHR_TRAINING1.CITY;
create or replace synonym tchr_reader.ANSWER for TCHR_TRAINING1.ANSWER;
