USE [EFCRM]
GO

/****** Object:  Table [dbo].[TMS_LIST]    Script Date: 05/03/2018 09:20:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TMS_LIST](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SERVICENAME] [varchar](20) NOT NULL,
	[MESSAGEID] [varchar](64) NOT NULL,
	[SERVICEKEY] [varchar](20) NOT NULL,
	[CALLID] [varchar](50) NOT NULL,
	[CALLERNUM] [varchar](20) NOT NULL,
	[CALLEDNUM] [varchar](20) NOT NULL,
	[MIDDLENUMBER] [varchar](50) NOT NULL,
	[CALLERDISPLAYNUMBER] [varchar](50) NOT NULL,
	[CALLEDDISPLAYNUMBER] [varchar](50) NULL,
	[CALLERSTREAMNO] [varchar](50) NOT NULL,
	[STARTCALLERTIME] [varchar](50) NULL,
	[ABSTARTCALLTIME] [varchar](30) NULL,
	[ABSTOPCALLTIME] [varchar](30) NULL,
	[CALLERDURATION] [varchar](20) NULL,
	[CALLERCOST] [varchar](20) NULL,
	[CALLERRELCAUSE] [varchar](10) NOT NULL,
	[CALLERORIRESCODE] [varchar](50) NULL,
	[CALLEDSTREAMNO] [varchar](50) NULL,
	[STARTCALLEDTIME] [varchar](50) NULL,
	[CALLEDDURATION] [varchar](50) NULL,
	[CALLEDCOST] [varchar](50) NULL,
	[CALLEDRELCAUSE] [varchar](50) NULL,
	[CALLEDORIRESCODE] [varchar](50) NULL,
	[SRFMSGID] [varchar](200) NULL,
	[CHARGENUMBER] [varchar](50) NULL,
	[CALLERRELREASON] [varchar](150) NULL,
	[CALLEDRELREASON] [varchar](150) NULL,
	[MSSERVER] [varchar](50) NULL,
	[MIDDLESTARTTIME] [varchar](50) NOT NULL,
	[MIDDLECALLTIME] [varchar](50) NOT NULL,
	[DURATION] [varchar](15) NOT NULL,
	[COSTCOUNT] [varchar](10) NOT NULL,
	[REALPATH] [varchar](200) NULL,
	[CREATETIME] [datetime] NOT NULL,
	[STATUS] [varchar](10) NOT NULL,
	[FK_TOPERATOR] [int] NULL,
	[FK_TCUSTOMERS] [int] NULL,
 CONSTRAINT [PK_TMS_LIST] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UK_TMS_LIST] UNIQUE NONCLUSTERED 
(
	[CALLID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

