USE [EFCRM]
GO

/****** Object:  Table [dbo].[TOPERATOR_MOBILE]    Script Date: 05/03/2018 09:21:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TOPERATOR_MOBILE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FK_TOPERATOR] [int] NOT NULL,
	[TO_MOBILE] [varchar](20) NULL,
	[TO_TEL] [varchar](20) NULL,
 CONSTRAINT [PK_TOPERATOR_MOBILE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

