USE [EFCRM]
GO

/****** Object:  Table [dbo].[TOUT_NUMBER]    Script Date: 05/03/2018 09:21:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TOUT_NUMBER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TO_MOBILE] [varchar](20) NULL,
	[TO_TEL] [varchar](20) NULL,
	[STATUS] [varchar](10) NOT NULL,
 CONSTRAINT [PK_TOUT_NUMBER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

