USE INTRUST
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE SP_STAT_CUSTOMER_LEVEL @P_FUNC_ID   INT, -- 100:忠诚客户明细表 200:潜在流失客户明细表 300:已流失客户明细表
                                        @IN_BOOK_CODE INT,
                                        @IN_INPUT_MAN INT = NULL,
                                        @IN_BEGIN_DATE INT = 0,
                                        @IN_SCOPE      INT=0 --统计范围:0全部，1本人；2本部门
WITH ENCRYPTION
AS
    SET NOCOUNT ON
    DECLARE @V_CUST_ID   INT
    DECLARE @V_CUST_NAME NVARCHAR(100)
    DECLARE @V_RG_TIMES  INT
    DECLARE @V_TOTAL_RG_MONEY   NUMERIC(16,3)
    DECLARE @V_RET_CODE INT
    
    DECLARE @V_OPCODES TABLE(OP_CODE INT)

--20409: The Products can be accessed. START REPORT3
    DECLARE @V_SW20409_R INT
    DECLARE @V_PRODUCTS TABLE(PRODUCT_ID INT)
    CREATE TABLE #TMP_CUSTS( CUST_ID INT )

    SELECT @V_SW20409_R = VALUE FROM TSYSCONTROL WHERE FLAG_TYPE = 'SW20409R'
    IF ISNULL(@IN_INPUT_MAN,0) = 0 SELECT @V_SW20409_R = 0

    IF ISNULL(@IN_BEGIN_DATE,0) = 0
        SET @IN_BEGIN_DATE = dbo.GETDATEINT(GETDATE())
        
    IF @IN_SCOPE=2 --保存下本部门的客户经理列表
		INSERT INTO @V_OPCODES
			SELECT OP_CODE FROM TOPERATOR WHERE DEPART_ID=(SELECT DEPART_ID FROM TOPERATOR WHERE OP_CODE=@IN_INPUT_MAN)

    IF @V_SW20409_R = 1
    BEGIN
        INSERT INTO @V_PRODUCTS
            SELECT PRODUCT_ID FROM TPRODUCT WHERE BOOK_CODE = @IN_BOOK_CODE
                AND(INTRUST_FLAG1 IN ( SELECT FUNC_ID-2040900 FROM TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID > 2040900 AND FUNC_ID <= 2040902 AND OP_CODE = @IN_INPUT_MAN )
                    OR DEPART_ID IN (SELECT B.DEPART_ID FROM TOPRIGHT A,TOPERATOR B WHERE A.OP_CODE = B.OP_CODE AND A.MENU_ID = '20409' AND A.FUNC_ID = 2040903 AND A.OP_CODE = @IN_INPUT_MAN)
                    OR PRODUCT_ID IN ( SELECT FUNC_ID FROM TOPRIGHT WHERE MENU_ID = '20409' AND FUNC_ID < 2040900 AND OP_CODE = @IN_INPUT_MAN)
                    OR ADMIN_MANAGER = @IN_INPUT_MAN OR INPUT_MAN = @IN_INPUT_MAN
                    OR SUB_MAN = @IN_INPUT_MAN OR SUB_MAN2 = @IN_INPUT_MAN
                    OR CASH_MAN = @IN_INPUT_MAN OR CASH_MAN2 = @IN_INPUT_MAN
                    OR ADMIN_MANAGER IN(SELECT OP_CODE FROM TOPCUSTRIGHT WHERE ENABLE_OP_CODE = @IN_INPUT_MAN) OR ISNULL(@IN_INPUT_MAN,0)=0 )
        INSERT INTO #TMP_CUSTS
            SELECT A.CUST_ID FROM TCONTRACT A,@V_PRODUCTS B
            WHERE A.PRODUCT_ID = B.PRODUCT_ID AND A.BOOK_CODE = @IN_BOOK_CODE GROUP BY A.CUST_ID
        INSERT INTO #TMP_CUSTS
            SELECT A.CUST_ID FROM TBENIFITOR A,@V_PRODUCTS B
            WHERE A.PRODUCT_ID = B.PRODUCT_ID AND A.BOOK_CODE = @IN_BOOK_CODE
                  AND A.CUST_ID NOT IN ( SELECT CUST_ID FROM #TMP_CUSTS )
                  GROUP BY A.CUST_ID
    END
--20409: The Products can be accessed. END

    SELECT @V_RET_CODE = -90004000
    IF( @P_FUNC_ID NOT IN(100,200,300,400))
        RETURN @V_RET_CODE-1 --非法的功能号

   --创建临时表保存需要统计的产品
    CREATE TABLE #FRIEND_CUST_INFO(
        CUST_ID          INT         ,--客户内部编号
        CUST_NO          NVARCHAR(8)  ,--客户编号
        CUST_NAME        NVARCHAR(100),
        RG_TIMES         INT    ,    --客户购买次数
        TOTAL_RG_MONEY   DEC(16,3),    --购买金额
        TOTAL_EXACT_MONEY  DEC(16,3),   --实际金额
        O_TEL            NVARCHAR(40),
        H_TEL            NVARCHAR(40),
        MOBILE           NVARCHAR(100),
        POST_ADDRESS     NVARCHAR(60),          --联系地址
        POST_CODE        NVARCHAR(6),           --邮编
        SERVICE_MAN      INT,
        SERVIC_MAN       NVARCHAR(20),         --客户经理
        DATA_TYPE        INT DEFAULT 0
       )
    IF( @P_FUNC_ID = 100)
    BEGIN
        INSERT INTO #FRIEND_CUST_INFO
            SELECT CUST_ID,CUST_NO,CUST_NAME,RG_TIMES,TOTAL_MONEY,CURRENT_MONEY,
                      O_TEL,H_TEL,MOBILE,POST_ADDRESS,POST_CODE,SERVICE_MAN,'',0
                FROM TCUSTOMERINFO
                WHERE STATUS <> '112805' AND CUST_LEVEL = '111102' AND BOOK_CODE = @IN_BOOK_CODE
                    AND dbo.GETDATEINT(INPUT_TIME) <= @IN_BEGIN_DATE
                    AND(ISNULL(@V_SW20409_R,0) = 0 OR CUST_ID IN (SELECT CUST_ID FROM #TMP_CUSTS))
                    AND (@IN_SCOPE=0 --全部
                        OR @IN_SCOPE=1 AND SERVICE_MAN=@IN_INPUT_MAN --本人
                        OR @IN_SCOPE=2 AND EXISTS(SELECT * FROM @V_OPCODES WHERE OP_CODE=TCUSTOMERINFO.SERVICE_MAN)--本部门
                        )
        IF @@ERROR<>0
            RETURN -100
    END
    IF( @P_FUNC_ID = 200)
    BEGIN
        INSERT INTO #FRIEND_CUST_INFO
            SELECT CUST_ID,CUST_NO,CUST_NAME,RG_TIMES,TOTAL_MONEY,CURRENT_MONEY,
                      O_TEL,H_TEL,MOBILE,POST_ADDRESS,POST_CODE,SERVICE_MAN,'' ,0
                FROM TCUSTOMERINFO
                WHERE STATUS <> '112805' AND CUST_LEVEL = '111104' AND BOOK_CODE = @IN_BOOK_CODE
                    AND dbo.GETDATEINT(INPUT_TIME) <= @IN_BEGIN_DATE
                    AND(ISNULL(@V_SW20409_R,0) = 0 OR CUST_ID IN (SELECT CUST_ID FROM #TMP_CUSTS))
                    AND (@IN_SCOPE=0 --全部
                        OR @IN_SCOPE=1 AND SERVICE_MAN=@IN_INPUT_MAN --本人
                        OR @IN_SCOPE=2 AND EXISTS(SELECT * FROM @V_OPCODES WHERE OP_CODE=TCUSTOMERINFO.SERVICE_MAN)--本部门
                        )
        IF @@ERROR<>0
            RETURN -100
    END
    IF( @P_FUNC_ID = 300)
    BEGIN
        INSERT INTO #FRIEND_CUST_INFO
               SELECT CUST_ID,CUST_NO,CUST_NAME,RG_TIMES,TOTAL_MONEY,CURRENT_MONEY,
                      O_TEL,H_TEL,MOBILE,POST_ADDRESS,POST_CODE,SERVICE_MAN,'' ,0
                 FROM TCUSTOMERINFO
                WHERE STATUS <> '112805' AND CUST_LEVEL = '111105' AND BOOK_CODE = @IN_BOOK_CODE
                    AND dbo.GETDATEINT(INPUT_TIME) <= @IN_BEGIN_DATE
                    AND(ISNULL(@V_SW20409_R,0) = 0 OR CUST_ID IN (SELECT CUST_ID FROM #TMP_CUSTS))
                    AND (@IN_SCOPE=0 --全部
                        OR @IN_SCOPE=1 AND SERVICE_MAN=@IN_INPUT_MAN --本人
                        OR @IN_SCOPE=2 AND EXISTS(SELECT * FROM @V_OPCODES WHERE OP_CODE=TCUSTOMERINFO.SERVICE_MAN)--本部门
                        )
        IF @@ERROR<>0
            RETURN -100
    END
    IF( @P_FUNC_ID = 400) --保留客户
    BEGIN
        INSERT INTO #FRIEND_CUST_INFO
               SELECT CUST_ID,CUST_NO,CUST_NAME,RG_TIMES,TOTAL_MONEY,CURRENT_MONEY,
                      O_TEL,H_TEL,MOBILE,POST_ADDRESS,POST_CODE,SERVICE_MAN,'' ,0
                 FROM TCUSTOMERINFO
                WHERE STATUS <> '112805' AND CUST_LEVEL = '111103' AND BOOK_CODE = @IN_BOOK_CODE
                    AND(ISNULL(@V_SW20409_R,0) = 0 OR CUST_ID IN (SELECT CUST_ID FROM #TMP_CUSTS))
                    AND (@IN_SCOPE=0 --全部
                        OR @IN_SCOPE=1 AND SERVICE_MAN=@IN_INPUT_MAN --本人
                        OR @IN_SCOPE=2 AND EXISTS(SELECT * FROM @V_OPCODES WHERE OP_CODE=TCUSTOMERINFO.SERVICE_MAN)--本部门
                        )
        IF @@ERROR<>0
            RETURN -100
    END
    UPDATE #FRIEND_CUST_INFO SET SERVIC_MAN = B.OP_NAME
    FROM #FRIEND_CUST_INFO A,TOPERATOR B WHERE A.SERVICE_MAN = B.OP_CODE

    INSERT INTO #FRIEND_CUST_INFO(CUST_NAME,RG_TIMES,TOTAL_RG_MONEY,TOTAL_EXACT_MONEY,DATA_TYPE)
        SELECT '合 计:' + RTRIM(CONVERT(CHAR(16),COUNT(*))), SUM(RG_TIMES), SUM(TOTAL_RG_MONEY), SUM(TOTAL_EXACT_MONEY),1
            FROM #FRIEND_CUST_INFO
    IF @@ERROR<>0
    BEGIN
        CLOSE CUR_CUSTOMER_LEVEL
        DEALLOCATE CUR_CUSTOMER_LEVEL
        RETURN -100
    END

    SELECT CUST_ID,CUST_NO,CUST_NAME,RG_TIMES,TOTAL_RG_MONEY,TOTAL_EXACT_MONEY,'' as O_TEL,'' as H_TEL,'' as MOBILE,POST_ADDRESS,POST_CODE,SERVIC_MAN,DATA_TYPE
    FROM #FRIEND_CUST_INFO ORDER BY DATA_TYPE, TOTAL_RG_MONEY DESC, RG_TIMES DESC
    RETURN @@ROWCOUNT
GO
