USE INTRUST
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
alter PROCEDURE SP_QUERY_TCUSTOMERINFO_LOAD @IN_CUST_ID INT,
                                             @IN_INPUT_MAN INT = NULL
WITH ENCRYPTION
AS
    --如果有客户访问权限控制，则执行客户信息加密
    DECLARE @V_MODI_FLAG INT, @V_IS_FLAG INT
    SELECT @V_IS_FLAG = 0
    --能够访问所有客户信息
    IF EXISTS(SELECT 1 FROM TOPRIGHT WHERE OP_CODE = @IN_INPUT_MAN AND MENU_ID ='20409' AND FUNC_ID = 2049903)
        SELECT @V_IS_FLAG = 1

    IF EXISTS(SELECT 1 FROM TSYSCONTROL WHERE FLAG_TYPE = 'CUSTRIGHT' AND VALUE = 1)  AND (@V_IS_FLAG = 0)
    BEGIN
        SET @V_MODI_FLAG = dbo.GETCUSTRIGHT(@IN_CUST_ID,@IN_INPUT_MAN)
        IF @V_MODI_FLAG = 1 --全部查看
            SELECT *,1 AS MODI_FLAG  FROM TCUSTOMERINFO WHERE CUST_ID = @IN_CUST_ID
        ELSE
            --部份查看
            IF EXISTS(SELECT 1 FROM TSYSTEMINFO WHERE USER_ID IN (2,7,24,13))
				--国联 只加密 电话
				--部份查看
            SELECT  BOOK_CODE,CUST_ID,CUST_NO,CUST_NAME,BIRTHDAY,AGE,
                    SEX,SEX_NAME,CUST_TYPE,CUST_TYPE_NAME,WT_FLAG,WT_FLAG_NAME,CUST_LEVEL,
                    CUST_LEVEL_NAME,PASSWORD,TOUCH_TYPE,TOUCH_TYPE_NAME,CUST_SOURCE,
                    CUST_SOURCE_NAME,RG_TIMES,TOTAL_MONEY,CURRENT_MONEY,LAST_RG_DATE,
                    INPUT_MAN,INPUT_TIME,CHECK_FLAG,CHECK_MAN,MODI_MAN,MODI_TIME,
                    CANCEL_MAN,CANCEL_TIME,STATUS,STATUS_NAME,SUMMARY,LEGAL_MAN,
                    REGISTRATION_ID,LIST_ID,PRINT_DEPLOY_BILL,PRINT_POST_INFO,IS_LINK,
                    SERVICE_MAN,ENT_CUST_ID,VIP_CARD_ID,VIP_DATE,HGTZR_BH,
                    VOC_TYPE,VOC_TYPE_NAME,CARD_TYPE,CARD_TYPE_NAME,CONTACT_MAN,CARD_VALID_DATE,COUNTRY,JG_CUST_TYPE,
                    CARD_ID,
					--replace('******',CARD_ID,CARD_ID) AS CARD_ID,
                    replace('******',CUST_TEL,CUST_TEL) AS CUST_TEL,
                    replace('******',MOBILE,MOBILE) AS MOBILE,
                    replace('******',O_TEL,O_TEL) AS O_TEL,
                    replace('******',H_TEL,H_TEL) AS H_TEL,
                    replace('******',BP,BP) AS BP,
                    replace('******',FAX,FAX) AS FAX,
					E_MAIL,POST_CODE,POST_CODE2,POST_ADDRESS,POST_ADDRESS2,LEGAL_ADDRESS,
                    --replace('******',E_MAIL,E_MAIL) AS E_MAIL,
                    --replace('******',POST_CODE,POST_CODE) AS POST_CODE,
                    --replace('******',POST_CODE2,POST_CODE2) AS POST_CODE2,
                    --replace('******',POST_ADDRESS,POST_ADDRESS) AS POST_ADDRESS,
                    --replace('******',POST_ADDRESS2,POST_ADDRESS2) AS POST_ADDRESS2,
                    --replace('******',LEGAL_ADDRESS,LEGAL_ADDRESS) AS LEGAL_ADDRESS,
                    replace('******',LEGAL_TEL,LEGAL_TEL) AS LEGAL_TEL,
                    replace('******',LEGAL_MOBILE,LEGAL_MOBILE) AS LEGAL_MOBILE,
                    @V_MODI_FLAG AS MODI_FLAG,MONEY_SOURCE,FACT_CONTROLLER,ISSUED_ORG,INDUSTRY_POST,
                    LINK_TYPE,LINK_GD_MONEY,GRADE_LEVEL,GRADE_LEVEL_NAME,COMPLETE_FLAG,GOV_PROV_REGIONAL,GOV_REGIONAL,
                    CUST_INDUSTRY,CUST_CORP_NATURE,CORP_BRANCH,SERVICE_MAN_TEL,GRADE_SCORE,FC_CARD_TYPE,FC_CARD_ID,
                    FC_CARD_VALID_DATE,SUMMARY1,SUMMARY2,LEGAL_POST_CODE,TRANS_NAME,TRANS_TEL,TRANS_MOBILE,TRANS_ADDRESS,
                    TRANS_POST_CODE,REGISTER_ADDRESS,REGISTER_POST_CODE,EAST_JG_TYPE,EAST_JG_TYPE_NAME,JG_WTRLX2,EAST_JG_TYPE,EAST_JG_TYPE_NAME,
                    INDUSTRY_POST_NAME,AGENCY_PROPERTIES,AGENCY_PROPERTIES_NAME,REGISTER_MONEY,MONEY_SOURCE_NAME
                FROM TCUSTOMERINFO WHERE CUST_ID = @IN_CUST_ID
			ELSE
			
			--部份查看
            SELECT  BOOK_CODE,CUST_ID,CUST_NO,CUST_NAME,BIRTHDAY,AGE,
                    SEX,SEX_NAME,CUST_TYPE,CUST_TYPE_NAME,WT_FLAG,WT_FLAG_NAME,CUST_LEVEL,
                    CUST_LEVEL_NAME,PASSWORD,TOUCH_TYPE,TOUCH_TYPE_NAME,CUST_SOURCE,
                    CUST_SOURCE_NAME,RG_TIMES,TOTAL_MONEY,CURRENT_MONEY,LAST_RG_DATE,
                    INPUT_MAN,INPUT_TIME,CHECK_FLAG,CHECK_MAN,MODI_MAN,MODI_TIME,
                    CANCEL_MAN,CANCEL_TIME,STATUS,STATUS_NAME,SUMMARY,LEGAL_MAN,
                    REGISTRATION_ID,LIST_ID,PRINT_DEPLOY_BILL,PRINT_POST_INFO,IS_LINK,
                    SERVICE_MAN,ENT_CUST_ID,VIP_CARD_ID,VIP_DATE,HGTZR_BH,
                    VOC_TYPE,VOC_TYPE_NAME,CARD_TYPE,CARD_TYPE_NAME,CONTACT_MAN,CARD_VALID_DATE,COUNTRY,JG_CUST_TYPE,
                    replace('******',CARD_ID,CARD_ID) AS CARD_ID,
                    replace('******',CUST_TEL,CUST_TEL) AS CUST_TEL,
                    replace('******',MOBILE,MOBILE) AS MOBILE,
                    replace('******',O_TEL,O_TEL) AS O_TEL,
                    replace('******',H_TEL,H_TEL) AS H_TEL,
                    replace('******',BP,BP) AS BP,
                    replace('******',FAX,FAX) AS FAX,
                    replace('******',E_MAIL,E_MAIL) AS E_MAIL,
                    replace('******',POST_CODE,POST_CODE) AS POST_CODE,
                    replace('******',POST_CODE2,POST_CODE2) AS POST_CODE2,
                    replace('******',POST_ADDRESS,POST_ADDRESS) AS POST_ADDRESS,
                    replace('******',POST_ADDRESS2,POST_ADDRESS2) AS POST_ADDRESS2,
                    replace('******',LEGAL_ADDRESS,LEGAL_ADDRESS) AS LEGAL_ADDRESS,
                    replace('******',LEGAL_TEL,LEGAL_TEL) AS LEGAL_TEL,
                    replace('******',LEGAL_MOBILE,LEGAL_MOBILE) AS LEGAL_MOBILE,
                    @V_MODI_FLAG AS MODI_FLAG,MONEY_SOURCE,FACT_CONTROLLER,ISSUED_ORG,INDUSTRY_POST,
                    LINK_TYPE,LINK_GD_MONEY,GRADE_LEVEL,GRADE_LEVEL_NAME,COMPLETE_FLAG,GOV_PROV_REGIONAL,GOV_REGIONAL,
                    CUST_INDUSTRY,CUST_CORP_NATURE,CORP_BRANCH,SERVICE_MAN_TEL,GRADE_SCORE,FC_CARD_TYPE,FC_CARD_ID,
                    FC_CARD_VALID_DATE,SUMMARY1,SUMMARY2,LEGAL_POST_CODE,TRANS_NAME,TRANS_TEL,TRANS_MOBILE,TRANS_ADDRESS,
                    TRANS_POST_CODE,REGISTER_ADDRESS,REGISTER_POST_CODE,EAST_JG_TYPE,EAST_JG_TYPE_NAME,JG_WTRLX2,EAST_JG_TYPE,EAST_JG_TYPE_NAME,
                    INDUSTRY_POST_NAME,AGENCY_PROPERTIES,AGENCY_PROPERTIES_NAME,REGISTER_MONEY,MONEY_SOURCE_NAME
                FROM TCUSTOMERINFO WHERE CUST_ID = @IN_CUST_ID
    END
    ELSE
    BEGIN
        SELECT *,1 AS MODI_FLAG  FROM TCUSTOMERINFO WHERE CUST_ID = @IN_CUST_ID
    END
GO
