USE [INTRUST]
GO

/****** Object:  UserDefinedFunction [dbo].[GETCUSTRIGHT]    Script Date: 2018/5/31 19:30:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER FUNCTION [dbo].[GETCUSTRIGHT](@IN_CUST_ID INT,@IN_INPUT_MAN INT) RETURNS NVARCHAR(30)
AS
BEGIN
    DECLARE @V_ENABLE_QUERY_TYPE INT,@V_CUSTOMER_MANAGER INT,@V_INPUT_MAN INT,@V_DEPART_ID INTEGER
    DECLARE @OUT_QUERY_TYPE INT
    DECLARE @V_CUST_SOURCE NVARCHAR(10)
    SET @V_ENABLE_QUERY_TYPE = 2
    SELECT @V_CUSTOMER_MANAGER = SERVICE_MAN,@V_INPUT_MAN = INPUT_MAN,@V_CUST_SOURCE = CUST_SOURCE
        FROM TCUSTOMERINFO 
        WHERE CUST_ID = @IN_CUST_ID
        
    IF @V_CUSTOMER_MANAGER = @IN_INPUT_MAN OR @V_INPUT_MAN = @IN_INPUT_MAN OR ISNULL(@V_CUSTOMER_MANAGER,0) = 0
        SET @V_ENABLE_QUERY_TYPE = 1
    ELSE
        SELECT @V_ENABLE_QUERY_TYPE = ENABLE_QUERY_TYPE 
            FROM TOPCUSTRIGHT 
            WHERE OP_CODE = @IN_INPUT_MAN AND ENABLE_OP_CODE = @V_CUSTOMER_MANAGER
    --厦门信托 特别处理
    IF EXISTS(SELECT 1 FROM TSYSTEMINFO WHERE USER_ID = 24) BEGIN
        SELECT @V_DEPART_ID = DEPART_ID FROM TOPERATOR WHERE OP_CODE = @IN_INPUT_MAN
        IF (@V_DEPART_ID = 16 AND @V_CUSTOMER_MANAGER = 16097) OR @V_CUSTOMER_MANAGER IN(16096,16099,16098)
            SET @V_ENABLE_QUERY_TYPE = 1
    END

    --国联 只加密 电话 且所有人 均只能允许 部份访问
    IF EXISTS(SELECT 1 FROM TSYSTEMINFO WHERE USER_ID IN (2,7))
        SET @V_ENABLE_QUERY_TYPE = 2

    RETURN ISNULL(@V_ENABLE_QUERY_TYPE,0)
END

GO


