/*
 * JSP generated by Resin-3.1.9 (built Mon, 13 Apr 2009 11:09:12 PDT)
 */

package _jsp._admin;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _right_0main__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html;charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
  String admin = (String)session.getValue("admin");
  if(admin!=null&&admin.equals("1")){
  }else{
  
      out.write(_jsp_string1, 0, _jsp_string1.length);
      out.print((request.getContextPath()));
      out.write(_jsp_string2, 0, _jsp_string2.length);
      
  }

      out.write(_jsp_string3, 0, _jsp_string3.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 5783496155892875126L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("admin/right_main.jsp"), -4739641842008643709L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("admin/pub/priv.jsp"), -6358081507721480377L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string1;
  private final static char []_jsp_string3;
  private final static char []_jsp_string2;
  private final static char []_jsp_string0;
  static {
    _jsp_string1 = "\r\n  <script language=\"javascript\">\r\n        window.parent.location.href=\"".toCharArray();
    _jsp_string3 = "\r\n\r\n<html>\r\n<head>\r\n<link href=\"css.css\" rel=\"stylesheet\" type=\"text/css\">\r\n<title>\u6743\u9650\u7ba1\u7406</title>\r\n</head>\r\n<body>\r\n\r\n\r\n<table cellPadding=2 cellSpacing=1  border=\"0\" bgcolor=#3F6C61 align=center width=\"100%\">\r\n<form action=\"platformparam_setexe.jsp\" method=post>\r\n<tr>\r\n	<td bgcolor=\"#D4E4EB\" class=\"zhengwen\" width=\"20%\">EnumConst</td>\r\n	<td bgcolor=\"#D4E4EB\" class=\"zhengwen\"><a href=\"/test/enumConst.action\">EnumConst\u7ba1\u7406(\u4ec5\u4f9b\u5f00\u53d1\u5185\u6d4b\u7528)</a></td>\r\n</tr>\r\n<tr>\r\n	<td bgcolor=\"#D4E4EB\" class=\"zhengwen\" width=\"20%\">SystemVariables</td>\r\n	<td bgcolor=\"#D4E4EB\" class=\"zhengwen\"><a href=\"/test/systemVariables.action\">SystemVariables\u7ba1\u7406(\u4ec5\u4f9b\u5f00\u53d1\u5185\u6d4b\u7528)</a></td>\r\n</tr>\r\n<tr>\r\n	<td bgcolor=\"#D4E4EB\" class=\"zhengwen\" width=\"20%\">\u6743\u9650\u7ba1\u7406</td>\r\n	<td bgcolor=\"#D4E4EB\" class=\"zhengwen\"><a href=\"/sso/admin/pricatetory.action\">\u7ba1\u7406\u6743\u9650\u7c7b\u522b(\u4ec5\u4f9b\u5f00\u53d1\u5185\u6d4b\u7528)</a></td>\r\n</tr>\r\n<tr>\r\n	<td bgcolor=\"#D4E4EB\" class=\"zhengwen\" width=\"20%\">\u6743\u9650\u7ba1\u7406</td>\r\n	<td bgcolor=\"#D4E4EB\" class=\"zhengwen\"><a href=\"/sso/admin/priority.action\">\u7ba1\u7406\u6743\u9650(\u4ec5\u4f9b\u5f00\u53d1\u5185\u6d4b\u7528)</a></td>\r\n</tr>\r\n<tr>\r\n	<td bgcolor=\"#D4E4EB\" class=\"zhengwen\" width=\"20%\">\u6743\u9650\u7ba1\u7406</td>\r\n	<td bgcolor=\"#D4E4EB\" class=\"zhengwen\"><a href=\"/sso/admin/pePriRole.action\">\u7ba1\u7406\u89d2\u8272</a></td>\r\n</tr>\r\n\r\n\r\n\r\n<form>\r\n</table>\r\n</body>\r\n</html>".toCharArray();
    _jsp_string2 = "/sso/admin/admin_adminLogin.action\";\r\n  </script>\r\n  ".toCharArray();
    _jsp_string0 = "\r\n\r\n".toCharArray();
  }
}
