 <TABLE class=flyoutMenu cellSpacing=0 cellPadding=2 width=140 border=0 xmlns:msxsl="urn:schemas-microsoft-com:xslt" menudata="../menu.xml">
              <TBODY>
              <TR>
                <TD>
                  <TABLE cellSpacing=0 cellPadding=0 width=100% border=0>
                    <TBODY>
                    <TR>
                      <TD class=flyoutLink handle="Help">系统帮助</TD></TR></TBODY></TABLE>
                  <TABLE cellSpacing=0 cellPadding=0 width=100% border=0>
                    <TBODY>
                    <TR>
                      <TD class=flyoutLink handle=""><a href="javascript:showPasswordDialog();">修改密码</a></TD></TR></TBODY></TABLE>
                  <TABLE cellSpacing=0 cellPadding=0 width=100% border=0>
                    <TBODY>
                    <TR>
                      <TD class=flyoutLink handle=""><a href="javascript:confirmReLoad();">重新登录</a></TD></TR></TBODY></TABLE>
                  <TABLE cellSpacing=0 cellPadding=0 width=100% border=0>
                    <TBODY>
                    <TR>
                      <TD class=flyoutLink handle=""><a href="javascript:confirmExit();">退出系统</a> </TD></TR></TBODY></TABLE>
            </TD></TR></TBODY></TABLE>