var type_radio_down="请选择";
var type_order="排序题";//排序题，请依次点击选项进行排序，請依次點擊選項進行排序
var type_order_upMove="上移一位";//排序题上移一位
var type_order_downMove="下移一位";//排序题下移一位
var type_order_goTop="移至最前";//排序题移至最前
var type_order_goBottom="移至最后";//排序题移至最后
var type_order_limit_begin="请选择";
var type_order_limit_end="并排序";
var type_check="多选题";//多选题
var type_check_limit1="请选择";//多选题限制选项1请选择
var type_check_limit2="可以选择";//多选题限制选项2可以选择
var type_check_limit3="<b>最少</b>选择";//多选题限制选项3最少选择
var type_check_limit4="<b>最多</b>选择";//多选题限制选项4最多选择
var type_check_limit5="项";//多选题限制选项5项
var type_order_all="全部选";
var subjectInfo="提示：";//填写提示
var jump_info="此题设置了跳转逻辑";//有跳题逻辑提示
var jump_info1="根据此题设置的跳转逻辑，请您顺序填写下题。";//跳转信息1根据此题设置的跳转逻辑，请您顺序填写下一题
var jump_info2="根据此题设置的跳转逻辑，请您填写完本题后提交答卷。";//跳转信息2根据此题设置的跳转逻辑，请您填写完本题后提交答卷
var jump_info3="根据此题设置的跳转逻辑，请您填写第";//跳转信息3根据此题设置的跳转逻辑，请您填写第
var jump_info4="页第";//跳转信息4页第
var jump_info5 = "题。"; //跳转信息5题
var page_info = "页";
var defaultOtherText="请注明...";
var validate_email="请输入正确的Email地址如cs@sojump.com";
var validate_phone = "请输入正确的电话号码（如：027-87789123或086-027-87789123），请注意使用英文字符格式。";
var validate_mobile = "请输入正确的手机号码（如：13812341234），请注意使用英文字符格式。";
var validate_mo_phone = "请输入正确的手机号码（13812341234）或固定电话号码（027-87789123），请注意使用英文字符格式。";
var validate_reticulation="请输入正确的网址如：http://www.sojump.com";
var validate_chinese="此题只允许输入汉字，请不要输入英文和标点符号。";
var validate_english="此题只允许输入英文字母";
var validate_idcardNum="请输入正确的身份证号（如：432123198912103118），请注意使用英文字符格式。";
var validate_num = "请输入正确的整数（如：12345678），请注意使用英文字符格式。";
var validate_decnum = "请输入正确的数字（如：12.34），请注意使用英文字符格式。";
var validate_num1="最大值不能超过";
var validate_num2="最小值不能小于";
var validate_date = "请输入正确的日期";
var validate_qq="请输入正确的QQ号码，可以为邮箱";
var validate_only="此题要求每个用户输入的答案都唯一，您输入的答案之前已有用户输入，请重新输入！";
var validate_list="您输入的答案不在问卷发布者预先设定的答案列表中，请重新输入！";
var validate_error="正在验证此题答案的正确性，请再次点击按钮！";//此题未通过检查，请确认您输入的内容！
var validate_textbox="文本框内容必须填写！";
var validate_submit="您某些题目填写的答案不符合本问卷的要求，页面将自动定位到第一个不符合要求的题目，请检查！";
var type_wd_limit="字以内";
var type_wd_minlimit="最少";
var type_wd_minlimitDigit="最小值";
var type_wd_maxlimitDigit="最大值";
var type_wd_digitfrom="从";
var type_wd_words="字";
var type_wd_to="到";
var validate_info="此";
var validate_info_wd1="题为必答题，请填写答案！";
var validate_info_wd2="题的填写超过了最大字数，请修改！";
var validate_info_wd3="您的输入已超过最大字数{0},当前字数为{1}";
var validate_info_wd4="您的输入小于最小输入字数{0},当前字数为{1}";
var validate_info_check1="题请选择";
var validate_info_check2="项并排序";
var validate_info_check3="题请选择所有选项并排序";
var validate_info_check4="题最多只能选择";
var validate_info_check5="题最少要选择";

var validate_info_matrix1="小题";
var validate_info_matrix2="题为必答题，";
var validate_info_matrix3="需要填写答案！";
var validate_info_matrix4="题必须填写数字";

var validate_info_submit1="请输入验证码";
var validate_info_submit2 = "提交成功......";
var validate_info_submit8="很抱歉，由于网络异常您的提交没有成功，请再试一次！";


var validate_info_submit_title1="看不清吗？请点击刷新！";
var validate_info_submit_title3="点击获取验证码";
var validate_info_submit_title2="将本题所有选项设为未选中状态";
var type_radio_clear="清除选择";
var validate_info_submit1="请输入验证码";
var slider_hint="拖动或点击滑动条";
var slider_value="当前滑动值为：";
var sum_hint="可以拖动滑动条也可以通过文本框直接输入";
var sum_warn="提示：剩余可分配比重必须为0";
var sum_total="总比重值：";
var sum_left="，剩余可分配比重：";
