/*
 * JSP generated by Resin-3.1.3 (built Sun, 07 Oct 2007 03:58:02 PDT)
 */

package _jsp._entity._manager._trainee;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _traineedetail__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    response.setCharacterEncoding("UTF-8");
    request.setCharacterEncoding("UTF-8");
    org.apache.struts2.views.jsp.PropertyTag _jsp_PropertyTag_0 = null;
    org.apache.struts2.views.jsp.IfTag _jsp_IfTag_1 = null;
    org.apache.struts2.views.jsp.PropertyTag _jsp_PropertyTag_2 = null;
    org.apache.struts2.views.jsp.ElseIfTag _jsp_ElseIfTag_3 = null;
    org.apache.struts2.views.jsp.PropertyTag _jsp_PropertyTag_4 = null;
    org.apache.struts2.views.jsp.ElseTag _jsp_ElseTag_5 = null;
    org.apache.struts2.views.jsp.PropertyTag _jsp_PropertyTag_6 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      if (_jsp_PropertyTag_0 == null) {
        _jsp_PropertyTag_0 = new org.apache.struts2.views.jsp.PropertyTag();
        _jsp_PropertyTag_0.setPageContext(pageContext);
        _jsp_PropertyTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_PropertyTag_0.setValue("bean.name");
      int _jspEval2 = _jsp_PropertyTag_0.doStartTag();
      _jsp_PropertyTag_0.doEndTag();
      out.write(_jsp_string1, 0, _jsp_string1.length);
      _jsp_PropertyTag_0.setValue("bean.enumConstByFkGender.name");
      int _jspEval6 = _jsp_PropertyTag_0.doStartTag();
      _jsp_PropertyTag_0.doEndTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _jsp_PropertyTag_0.setValue("bean.age");
      int _jspEval10 = _jsp_PropertyTag_0.doStartTag();
      _jsp_PropertyTag_0.doEndTag();
      out.write(_jsp_string3, 0, _jsp_string3.length);
      _jsp_PropertyTag_0.setValue("bean.folk");
      int _jspEval14 = _jsp_PropertyTag_0.doStartTag();
      _jsp_PropertyTag_0.doEndTag();
      out.write(_jsp_string4, 0, _jsp_string4.length);
      _jsp_PropertyTag_0.setValue("bean.workPlace");
      int _jspEval18 = _jsp_PropertyTag_0.doStartTag();
      _jsp_PropertyTag_0.doEndTag();
      out.write(_jsp_string5, 0, _jsp_string5.length);
      _jsp_PropertyTag_0.setValue("bean.education");
      int _jspEval22 = _jsp_PropertyTag_0.doStartTag();
      _jsp_PropertyTag_0.doEndTag();
      out.write(_jsp_string6, 0, _jsp_string6.length);
      _jsp_PropertyTag_0.setValue("bean.zhiCheng");
      int _jspEval26 = _jsp_PropertyTag_0.doStartTag();
      _jsp_PropertyTag_0.doEndTag();
      out.write(_jsp_string7, 0, _jsp_string7.length);
      _jsp_PropertyTag_0.setValue("bean.zhiwu");
      int _jspEval30 = _jsp_PropertyTag_0.doStartTag();
      _jsp_PropertyTag_0.doEndTag();
      out.write(_jsp_string8, 0, _jsp_string8.length);
      _jsp_PropertyTag_0.setValue("bean.workyeare");
      int _jspEval34 = _jsp_PropertyTag_0.doStartTag();
      _jsp_PropertyTag_0.doEndTag();
      out.write(_jsp_string9, 0, _jsp_string9.length);
      _jsp_PropertyTag_0.setValue("bean.telephone");
      int _jspEval38 = _jsp_PropertyTag_0.doStartTag();
      _jsp_PropertyTag_0.doEndTag();
      out.write(_jsp_string10, 0, _jsp_string10.length);
      _jsp_PropertyTag_0.setValue("bean.email");
      int _jspEval42 = _jsp_PropertyTag_0.doStartTag();
      _jsp_PropertyTag_0.doEndTag();
      out.write(_jsp_string11, 0, _jsp_string11.length);
      com.caucho.jsp.BodyContentImpl _jsp_endTagHack44 = null;
      if (_jsp_IfTag_1 == null) {
        _jsp_IfTag_1 = new org.apache.struts2.views.jsp.IfTag();
        _jsp_IfTag_1.setPageContext(pageContext);
        _jsp_IfTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_IfTag_1.setTest("getCurrentUserRoleEnumCode(getCurrentSsoUser())==2");
      }

      int _jspEval46 = _jsp_IfTag_1.doStartTag();
      if (_jspEval46 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspEval46 == javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_BUFFERED) {
          out = pageContext.pushBody();
          _jsp_endTagHack44 = (com.caucho.jsp.BodyContentImpl) out;
          _jsp_IfTag_1.setBodyContent(_jsp_endTagHack44);
        }
        out.write(_jsp_string12, 0, _jsp_string12.length);
        if (_jsp_PropertyTag_2 == null) {
          _jsp_PropertyTag_2 = new org.apache.struts2.views.jsp.PropertyTag();
          _jsp_PropertyTag_2.setPageContext(pageContext);
          _jsp_PropertyTag_2.setParent((javax.servlet.jsp.tagext.Tag) _jsp_IfTag_1);
        }

        _jsp_PropertyTag_2.setValue("bean.peSubject.name");
        int _jspEval49 = _jsp_PropertyTag_2.doStartTag();
        _jsp_PropertyTag_2.doEndTag();
        out.write(_jsp_string13, 0, _jsp_string13.length);
        _jsp_PropertyTag_2.setValue("bean.peProApplyno.name");
        int _jspEval53 = _jsp_PropertyTag_2.doStartTag();
        _jsp_PropertyTag_2.doEndTag();
        out.write(_jsp_string14, 0, _jsp_string14.length);
        _jsp_PropertyTag_2.setValue("bean.peProvince.name");
        int _jspEval57 = _jsp_PropertyTag_2.doStartTag();
        _jsp_PropertyTag_2.doEndTag();
        out.write(_jsp_string15, 0, _jsp_string15.length);
        _jsp_PropertyTag_2.setValue("bean.officePhone");
        int _jspEval61 = _jsp_PropertyTag_2.doStartTag();
        _jsp_PropertyTag_2.doEndTag();
        out.write(_jsp_string16, 0, _jsp_string16.length);
        _jsp_PropertyTag_2.setValue("bean.enumConstByFkGraduted.name");
        int _jspEval65 = _jsp_PropertyTag_2.doStartTag();
        _jsp_PropertyTag_2.doEndTag();
        out.write(_jsp_string17, 0, _jsp_string17.length);
        _jsp_PropertyTag_2.setValue("bean.enumConstByFkStatusTraining.name");
        int _jspEval69 = _jsp_PropertyTag_2.doStartTag();
        _jsp_PropertyTag_2.doEndTag();
        out.write(_jsp_string18, 0, _jsp_string18.length);
        _jsp_PropertyTag_2.setValue("bean.certificateNumber");
        int _jspEval73 = _jsp_PropertyTag_2.doStartTag();
        _jsp_PropertyTag_2.doEndTag();
        out.write(_jsp_string19, 0, _jsp_string19.length);
        if (_jspEval46 == javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_BUFFERED)
          out = pageContext.popBody();
      }
      _jsp_IfTag_1.doEndTag();
      if (_jsp_endTagHack44 != null) {
        pageContext.releaseBody(_jsp_endTagHack44);
        _jsp_endTagHack44 = null;
      }
      out.write(_jsp_string20, 0, _jsp_string20.length);
      com.caucho.jsp.BodyContentImpl _jsp_endTagHack76 = null;
      if (_jsp_ElseIfTag_3 == null) {
        _jsp_ElseIfTag_3 = new org.apache.struts2.views.jsp.ElseIfTag();
        _jsp_ElseIfTag_3.setPageContext(pageContext);
        _jsp_ElseIfTag_3.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_ElseIfTag_3.setTest("getCurrentUserRoleEnumCode(getCurrentSsoUser())==3");
      }

      int _jspEval78 = _jsp_ElseIfTag_3.doStartTag();
      if (_jspEval78 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspEval78 == javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_BUFFERED) {
          out = pageContext.pushBody();
          _jsp_endTagHack76 = (com.caucho.jsp.BodyContentImpl) out;
          _jsp_ElseIfTag_3.setBodyContent(_jsp_endTagHack76);
        }
        out.write(_jsp_string21, 0, _jsp_string21.length);
        if (_jsp_PropertyTag_4 == null) {
          _jsp_PropertyTag_4 = new org.apache.struts2.views.jsp.PropertyTag();
          _jsp_PropertyTag_4.setPageContext(pageContext);
          _jsp_PropertyTag_4.setParent((javax.servlet.jsp.tagext.Tag) _jsp_ElseIfTag_3);
        }

        _jsp_PropertyTag_4.setValue("bean.subject");
        int _jspEval81 = _jsp_PropertyTag_4.doStartTag();
        _jsp_PropertyTag_4.doEndTag();
        out.write(_jsp_string22, 0, _jsp_string22.length);
        _jsp_PropertyTag_4.setValue("bean.peProApplyno.name");
        int _jspEval85 = _jsp_PropertyTag_4.doStartTag();
        _jsp_PropertyTag_4.doEndTag();
        out.write(_jsp_string23, 0, _jsp_string23.length);
        _jsp_PropertyTag_4.setValue("bean.officePhone");
        int _jspEval89 = _jsp_PropertyTag_4.doStartTag();
        _jsp_PropertyTag_4.doEndTag();
        out.write(_jsp_string24, 0, _jsp_string24.length);
        _jsp_PropertyTag_4.setValue("bean.enumConstByFkCheckedTrainee.name");
        int _jspEval93 = _jsp_PropertyTag_4.doStartTag();
        _jsp_PropertyTag_4.doEndTag();
        out.write(_jsp_string25, 0, _jsp_string25.length);
        _jsp_PropertyTag_4.setValue("bean.enumConstByFkStatusTraining.name");
        int _jspEval97 = _jsp_PropertyTag_4.doStartTag();
        _jsp_PropertyTag_4.doEndTag();
        out.write(_jsp_string26, 0, _jsp_string26.length);
        _jsp_PropertyTag_4.setValue("bean.peUnitByFkTrainingUnit.name");
        int _jspEval101 = _jsp_PropertyTag_4.doStartTag();
        _jsp_PropertyTag_4.doEndTag();
        out.write(_jsp_string27, 0, _jsp_string27.length);
        if (_jspEval78 == javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_BUFFERED)
          out = pageContext.popBody();
      }
      _jsp_ElseIfTag_3.doEndTag();
      if (_jsp_endTagHack76 != null) {
        pageContext.releaseBody(_jsp_endTagHack76);
        _jsp_endTagHack76 = null;
      }
      out.write(_jsp_string20, 0, _jsp_string20.length);
      com.caucho.jsp.BodyContentImpl _jsp_endTagHack104 = null;
      if (_jsp_ElseTag_5 == null) {
        _jsp_ElseTag_5 = new org.apache.struts2.views.jsp.ElseTag();
        _jsp_ElseTag_5.setPageContext(pageContext);
        _jsp_ElseTag_5.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      int _jspEval106 = _jsp_ElseTag_5.doStartTag();
      if (_jspEval106 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspEval106 == javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_BUFFERED) {
          out = pageContext.pushBody();
          _jsp_endTagHack104 = (com.caucho.jsp.BodyContentImpl) out;
          _jsp_ElseTag_5.setBodyContent(_jsp_endTagHack104);
        }
        out.write(_jsp_string28, 0, _jsp_string28.length);
        if (_jsp_PropertyTag_6 == null) {
          _jsp_PropertyTag_6 = new org.apache.struts2.views.jsp.PropertyTag();
          _jsp_PropertyTag_6.setPageContext(pageContext);
          _jsp_PropertyTag_6.setParent((javax.servlet.jsp.tagext.Tag) _jsp_ElseTag_5);
        }

        _jsp_PropertyTag_6.setValue("bean.peSubject.name");
        int _jspEval109 = _jsp_PropertyTag_6.doStartTag();
        _jsp_PropertyTag_6.doEndTag();
        out.write(_jsp_string29, 0, _jsp_string29.length);
        _jsp_PropertyTag_6.setValue("bean.subject");
        int _jspEval113 = _jsp_PropertyTag_6.doStartTag();
        _jsp_PropertyTag_6.doEndTag();
        out.write(_jsp_string22, 0, _jsp_string22.length);
        _jsp_PropertyTag_6.setValue("bean.peProApplyno.name");
        int _jspEval117 = _jsp_PropertyTag_6.doStartTag();
        _jsp_PropertyTag_6.doEndTag();
        out.write(_jsp_string30, 0, _jsp_string30.length);
        _jsp_PropertyTag_6.setValue("bean.peProvince.name");
        int _jspEval121 = _jsp_PropertyTag_6.doStartTag();
        _jsp_PropertyTag_6.doEndTag();
        out.write(_jsp_string23, 0, _jsp_string23.length);
        _jsp_PropertyTag_6.setValue("bean.officePhone");
        int _jspEval125 = _jsp_PropertyTag_6.doStartTag();
        _jsp_PropertyTag_6.doEndTag();
        out.write(_jsp_string31, 0, _jsp_string31.length);
        _jsp_PropertyTag_6.setValue("bean.loginId");
        int _jspEval129 = _jsp_PropertyTag_6.doStartTag();
        _jsp_PropertyTag_6.doEndTag();
        out.write(_jsp_string32, 0, _jsp_string32.length);
        _jsp_PropertyTag_6.setValue("bean.enumConstByFkCheckedTrainee.name");
        int _jspEval133 = _jsp_PropertyTag_6.doStartTag();
        _jsp_PropertyTag_6.doEndTag();
        out.write(_jsp_string33, 0, _jsp_string33.length);
        _jsp_PropertyTag_6.setValue("bean.enumConstByFkGraduted.name");
        int _jspEval137 = _jsp_PropertyTag_6.doStartTag();
        _jsp_PropertyTag_6.doEndTag();
        out.write(_jsp_string34, 0, _jsp_string34.length);
        _jsp_PropertyTag_6.setValue("bean.peUnitByFkTrainingUnit.name");
        int _jspEval141 = _jsp_PropertyTag_6.doStartTag();
        _jsp_PropertyTag_6.doEndTag();
        out.write(_jsp_string35, 0, _jsp_string35.length);
        _jsp_PropertyTag_6.setValue("bean.peUnitByFkUnitFrom.name");
        int _jspEval145 = _jsp_PropertyTag_6.doStartTag();
        _jsp_PropertyTag_6.doEndTag();
        out.write(_jsp_string17, 0, _jsp_string17.length);
        _jsp_PropertyTag_6.setValue("bean.enumConstByFkStatusTraining.name");
        int _jspEval149 = _jsp_PropertyTag_6.doStartTag();
        _jsp_PropertyTag_6.doEndTag();
        out.write(_jsp_string36, 0, _jsp_string36.length);
        _jsp_PropertyTag_6.setValue("bean.note");
        int _jspEval153 = _jsp_PropertyTag_6.doStartTag();
        _jsp_PropertyTag_6.doEndTag();
        out.write(_jsp_string37, 0, _jsp_string37.length);
        _jsp_PropertyTag_6.setValue("bean.noteSecond");
        int _jspEval157 = _jsp_PropertyTag_6.doStartTag();
        _jsp_PropertyTag_6.doEndTag();
        out.write(_jsp_string38, 0, _jsp_string38.length);
        _jsp_PropertyTag_6.setValue("bean.certificateNumber");
        int _jspEval161 = _jsp_PropertyTag_6.doStartTag();
        _jsp_PropertyTag_6.doEndTag();
        out.write(_jsp_string39, 0, _jsp_string39.length);
        if (_jspEval106 == javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_BUFFERED)
          out = pageContext.popBody();
      }
      _jsp_ElseTag_5.doEndTag();
      if (_jsp_endTagHack104 != null) {
        pageContext.releaseBody(_jsp_endTagHack104);
        _jsp_endTagHack104 = null;
      }
      out.write(_jsp_string40, 0, _jsp_string40.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_PropertyTag_0 != null)
        _jsp_PropertyTag_0.release();
      if (_jsp_IfTag_1 != null)
        _jsp_IfTag_1.release();
      if (_jsp_PropertyTag_2 != null)
        _jsp_PropertyTag_2.release();
      if (_jsp_ElseIfTag_3 != null)
        _jsp_ElseIfTag_3.release();
      if (_jsp_PropertyTag_4 != null)
        _jsp_PropertyTag_4.release();
      if (_jsp_ElseTag_5 != null)
        _jsp_ElseTag_5.release();
      if (_jsp_PropertyTag_6 != null)
        _jsp_PropertyTag_6.release();
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != -9019483982733035993L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    manager.addTaglibFunctions(_jsp_functionMap, "s", "/WEB-INF/struts-tags.tld");
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("entity/manager/trainee/traineeDetail.jsp"), -6245370459658191757L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/struts-tags.tld"), 2632518462704396565L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.struts2.views.jsp.PropertyTag.class, 3516723674932103087L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.struts2.views.jsp.IfTag.class, 2691840914333557849L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.struts2.views.jsp.ElseIfTag.class, -3357329229987466207L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.struts2.views.jsp.ElseTag.class, 719326203869585948L));
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }

  private final static char []_jsp_string17;
  private final static char []_jsp_string30;
  private final static char []_jsp_string6;
  private final static char []_jsp_string12;
  private final static char []_jsp_string18;
  private final static char []_jsp_string27;
  private final static char []_jsp_string10;
  private final static char []_jsp_string25;
  private final static char []_jsp_string24;
  private final static char []_jsp_string21;
  private final static char []_jsp_string31;
  private final static char []_jsp_string20;
  private final static char []_jsp_string22;
  private final static char []_jsp_string32;
  private final static char []_jsp_string7;
  private final static char []_jsp_string14;
  private final static char []_jsp_string8;
  private final static char []_jsp_string34;
  private final static char []_jsp_string13;
  private final static char []_jsp_string33;
  private final static char []_jsp_string3;
  private final static char []_jsp_string9;
  private final static char []_jsp_string23;
  private final static char []_jsp_string11;
  private final static char []_jsp_string26;
  private final static char []_jsp_string29;
  private final static char []_jsp_string36;
  private final static char []_jsp_string5;
  private final static char []_jsp_string15;
  private final static char []_jsp_string39;
  private final static char []_jsp_string40;
  private final static char []_jsp_string1;
  private final static char []_jsp_string4;
  private final static char []_jsp_string19;
  private final static char []_jsp_string16;
  private final static char []_jsp_string38;
  private final static char []_jsp_string35;
  private final static char []_jsp_string2;
  private final static char []_jsp_string28;
  private final static char []_jsp_string0;
  private final static char []_jsp_string37;
  static {
    _jsp_string17 = "\"/>\r\n	                </td>\r\n                </tr>\r\n                <tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u53c2&nbsp;\u8bad&nbsp;\u72b6&nbsp;\u6001\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string30 = "\"/>\r\n	                </td>\r\n                </tr>\r\n                <tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u7701&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\u4efd\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string6 = "\"/>\r\n	                </td>\r\n               </tr>\r\n               <tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u804c&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\u79f0\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string12 = "\r\n               	<!-- \u627f\u529e\u5355\u4f4d\u7279\u522b\u663e\u793a\u5c5e\u6027\u5f00\u59cb -->\r\n               	<tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u5b66&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\u79d1\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string18 = "\"/>\r\n	                </td>\r\n                </tr>\r\n                <tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u8bc1&nbsp;\u4e66&nbsp;\u7f16&nbsp;\u53f7\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string27 = "\"/>\r\n	                </td>\r\n                </tr>\r\n				<!-- \u7701\u5385\u7279\u522b\u663e\u793a\u5c5e\u6027\u7ed3\u675f -->\r\n			".toCharArray();
    _jsp_string10 = "\" />\r\n	                </td>\r\n               </tr>\r\n               <tr valign=\"middle\">\r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u90ae&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\u7bb1\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string25 = "\" />\r\n	                </td>\r\n                </tr>\r\n                <tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u53c2&nbsp;\u8bad&nbsp;\u72b6&nbsp;\u6001\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string24 = "\"/>\r\n	                </td>\r\n                </tr>\r\n                <tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">\u662f\u5426\u901a\u8fc7\u5ba1\u6838:</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string21 = "\r\n				<!-- \u7701\u5385\u7279\u522b\u663e\u793a\u5c5e\u6027\u7ed3\u675f -->\r\n				<tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u5b66&nbsp;\u6bb5&nbsp;\u5b66&nbsp;\u79d1\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string31 = "\"/>\r\n	                </td>\r\n                </tr>\r\n                <tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u7528&nbsp;&nbsp;\u6237&nbsp;&nbsp;\u540d&nbsp;\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string20 = "\r\n			".toCharArray();
    _jsp_string22 = "\"/>\r\n	                </td>\r\n                </tr>\r\n                <tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u57f9&nbsp;\u8bad&nbsp;\u9879&nbsp;\u76ee\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string32 = "\" />\r\n	                </td>\r\n                </tr>\r\n                <tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">\u662f\u5426\u901a\u8fc7\u5ba1\u6838:</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string7 = "\" /> \r\n	                </td>\r\n               </tr>\r\n               <tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u804c&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\u52a1\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string14 = "\"/>\r\n	                </td>\r\n                </tr>\r\n				<tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u7701&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\u4efd\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string8 = "\"/>\r\n	                </td>\r\n               </tr>\r\n               <tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u6559&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\u9f84\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string34 = "\"/>\r\n	                </td>\r\n                </tr>\r\n                <tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u57f9&nbsp;\u8bad&nbsp;\u5355&nbsp;\u4f4d\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string13 = "\"/>\r\n	                </td>\r\n               	</tr>\r\n               	<tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u57f9&nbsp;\u8bad&nbsp;\u9879&nbsp;\u76ee\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string33 = "\" />\r\n	                </td>\r\n                </tr>\r\n                <tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u662f&nbsp;\u5426&nbsp;\u7ed3&nbsp;\u4e1a\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string3 = "\" />\r\n					</td>\r\n				</tr>\r\n				<tr valign=\"middle\"> \r\n                	<td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n                		<span class=\"name\">&nbsp;&nbsp;\u6c11&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\u65cf\uff1a</span>\r\n                	</td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string9 = "\" />\r\n	                </td>\r\n               </tr>\r\n               <tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u624b&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\u673a\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string23 = "\"/>\r\n	                </td>\r\n                </tr>\r\n                <tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u529e&nbsp;\u516c&nbsp;\u7535&nbsp;\u8bdd\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string11 = "\"/>\r\n	                </td>\r\n               </tr>\r\n               <!-- \u516c\u5171\u53ef\u67e5\u770b\u5c5e\u6027\u7ed3\u675f -->\r\n               ".toCharArray();
    _jsp_string26 = "\"/>\r\n	                </td>\r\n                </tr>\r\n                 <tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u57f9&nbsp;\u8bad&nbsp;\u5355&nbsp;\u4f4d\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string29 = "\"/>\r\n	                </td>\r\n                </tr>\r\n                <tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u5b66&nbsp;\u6bb5&nbsp;\u5b66&nbsp;\u79d1\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string36 = "\"/>\r\n	                </td>\r\n                </tr>\r\n                <tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u5907&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\u6ce8\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<textarea cols=\"84\" rows=\"5\" readonly=\"readonly\">".toCharArray();
    _jsp_string5 = "\" style=\"width: 300px;\"/>\r\n	                </td>\r\n               </tr>\r\n               <tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u5b66&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\u5386\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string15 = "\"/>\r\n	                </td>\r\n               	</tr>\r\n               	<tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u529e&nbsp;\u516c&nbsp;\u7535&nbsp;\u8bdd\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string39 = "\"/>\r\n	                </td>\r\n                </tr>\r\n                <!-- \u7ba1\u7406\u5458\u663e\u793a\u6240\u6709\u5c5e\u6027 -->\r\n               ".toCharArray();
    _jsp_string40 = "\r\n            <tr>\r\n	            <td height=\"40\" align=\"center\" colspan=\"2\">\r\n	              <input type=\"button\" value=\"&nbsp;\u5173&nbsp;&nbsp;\u95ed\" onclick=\"window.close()\" style=\"width:120px;cursor:pointer\" />\r\n	            </td>\r\n			</tr>\r\n       	</table>\r\n    </div>\r\n</div>\r\n</body>\r\n</html>".toCharArray();
    _jsp_string1 = "\"/>\r\n	                </td>\r\n               </tr>\r\n				<tr valign=\"middle\"> \r\n					<td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\"><span class=\"name\">&nbsp;&nbsp;\u6027&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\u522b\uff1a</span></td>\r\n					<td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	              		<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string4 = "\" />\r\n	                </td>\r\n               </tr>\r\n               <tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u5de5\u4f5c\u5355\u4f4d&nbsp;*\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string19 = "\"/>\r\n	                </td>\r\n                </tr>\r\n               	<!-- \u627f\u529e\u5355\u4f4d\u7279\u522b\u663e\u793a\u5c5e\u6027\u7ed3\u675f -->\r\n			".toCharArray();
    _jsp_string16 = "\"/>\r\n	                </td>\r\n                </tr>\r\n               	<tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u662f&nbsp;\u5426&nbsp;\u7ed3&nbsp;\u4e1a\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string38 = "</textarea>\r\n	                </td>\r\n                </tr>\r\n                <tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u8bc1&nbsp;\u4e66&nbsp;\u7f16&nbsp;\u53f7\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string35 = "\"/>\r\n	                </td>\r\n                </tr>\r\n                <tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u586b&nbsp;\u62a5&nbsp;\u5355&nbsp;\u4f4d\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string2 = "\"/>\r\n	              	</td>\r\n				</tr>\r\n				<tr valign=\"middle\"> \r\n					<td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n						<span class=\"name\">&nbsp;&nbsp;\u5e74&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\u9f84&nbsp;*\uff1a</span>\r\n					</td>\r\n					<td class=\"postFormBox\" style=\"padding-left:10px\">\r\n						<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string28 = "\r\n				<!-- \u7ba1\u7406\u5458\u663e\u793a\u6240\u6709\u5c5e\u6027 -->\r\n                <tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u5b66&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\u79d1\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n<html>\r\n  <head>\r\n    <title>\u53c2\u8bad\u5b66\u5458\u8be6\u7ec6\u4fe1\u606f</title>\r\n	<link href=\"/entity/manager/css/admincss.css\" rel=\"stylesheet\" type=\"text/css\">\r\n</head>\r\n<body topmargin=\"0\" leftmargin=\"0\" bgcolor=\"#FAFAFA\">\r\n<div id=\"main_content\">\r\n    <div class=\"content_title\">\u53c2\u8bad\u5b66\u5458\u8be6\u7ec6\u4fe1\u606f</div>\r\n    <div class=\"cntent_k\">\r\n		<table width=\"554\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n			<!-- \u516c\u5171\u53ef\u67e5\u770b\u5c5e\u6027\u5f00\u59cb -->\r\n 				<tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u59d3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\u540d&nbsp;*\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<input readonly=\"readonly\" value=\"".toCharArray();
    _jsp_string37 = "</textarea>\r\n	                </td>\r\n                </tr>\r\n                <tr valign=\"middle\"> \r\n	                <td width=\"140\" height=\"30\" align=\"left\" class=\"postFormBox\" style=\"padding-left:50px\">\r\n	                	<span class=\"name\">&nbsp;&nbsp;\u5907&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\u6ce82\uff1a</span>\r\n	                </td>\r\n	                <td class=\"postFormBox\" style=\"padding-left:10px\">\r\n	                	<textarea readonly=\"readonly\" cols=\"84\" rows=\"5\">".toCharArray();
  }
}
