USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TPROPERTY_SURVER  @IN_SERIAL_NO           INTEGER,                --序号
                                            @IN_CUST_ID             INTEGER                 --客户ID
WITH ENCRYPTION
AS
    SET NOCOUNT ON

    IF EXISTS (SELECT * FROM TPROPERTY_SURVER WHERE CUST_ID=@IN_CUST_ID)
    SELECT * FROM TPROPERTY_SURVER
        WHERE (ISNULL(@IN_SERIAL_NO,0) = 0 OR SERIAL_NO = @IN_SERIAL_NO)
            AND (ISNULL(@IN_CUST_ID,0) = 0 OR CUST_ID = @IN_CUST_ID)
    ELSE
		SELECT CUST_ID,CUST_NAME,POST_ADDRESS LINK_ADDRESS,MOBILE LINK_PHONE,COUNTRY GR_NATION,VOC_TYPE PROFESSION
		        ,CARD_TYPE FZ_CARD_TYPE,CARD_ID FZ_CARD_ID,CARD_VALID_DATE FZ_CARD_YXQ
            FROM TCustomers
			WHERE CUST_ID = @IN_CUST_ID
GO
