USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TDIRECTSENDDETAIL @IN_SERIAL_NO      INT,
                                            @IN_SMS_SERIAL_NO  INTEGER,               --TDIRECTSENDTOTAL.SERIAL_NO
										    @IN_INPUT_MAN      INT

WITH ENCRYPTION
AS
    IF ISNULL(@IN_SERIAL_NO,0) <> 0
        SELECT A.*,B.CUST_NAME,B.MOBILE,B.BP,B.E_MAIL FROM TDIRECTSENDDETAIL A,TCustomers B
            WHERE A.SERIAL_NO =@IN_SERIAL_NO AND A.CUST_ID =B.CUST_ID
    ELSE
        SELECT A.*,B.CUST_NAME,B.MOBILE,B.BP,B.E_MAIL FROM TDIRECTSENDDETAIL A,TCustomers B
            WHERE (ISNULL(@IN_SMS_SERIAL_NO,0) =0 OR A.SEND_SERIAL_NO = @IN_SMS_SERIAL_NO)
                AND A.CUST_ID =B.CUST_ID
GO
