USE EFCRM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_QUERY_TCustomers_LOAD @IN_CUST_ID INT,
                                          @IN_INPUT_MAN INT = NULL,
										  @IN_QUERY_FLAG INT = 0,   --数据查询标志 0：按原有权限模式 1：不按客户权限并且联系信息加密显示
										  @IN_EXPORT_FLAG INT = 0 --导出标记：0非导出查询 1导出客户信息 2导出手机 3导出通讯录
WITH ENCRYPTION
AS
    DECLARE @V_FLAG_ACCESS INT, @V_FLAG_ENCRYPTION INT,@V_ENCRYPTION_SIZE INT, @V_SERVICE_NAME INT
    SELECT @V_FLAG_ACCESS       = 1    --访问标志 修改为1 此过程 不需要访问控制
    SELECT @V_FLAG_ENCRYPTION   = 0    --加密标志
    --如果操作员是该客户的客户经理或录入员 可查看
    IF EXISTS(SELECT 1 FROM TCustomers WHERE CUST_ID=@IN_CUST_ID AND (SERVICE_MAN = @IN_INPUT_MAN OR INPUT_MAN = @IN_INPUT_MAN))
        SELECT @V_FLAG_ACCESS = 1
    --能够访问所有客户信息
    IF EXISTS(SELECT 1 FROM TOPRIGHT WHERE OP_CODE = @IN_INPUT_MAN AND MENU_ID ='999' AND FUNC_ID = 99903)
        SELECT @V_FLAG_ACCESS = 1
    --如果操作员的角色中存在访问所有客户信息权限的标志 则赋予能够访问所有客户信息权限
    IF EXISTS(SELECT 1 FROM TOPROLE WHERE OP_CODE = @IN_INPUT_MAN AND ROLE_ID IN(SELECT ROLE_ID FROM TROLE WHERE FLAG_ACCESS_ALL = 1))
        SELECT @V_FLAG_ACCESS = 1
    --如果操作员的角色中存在不保密限制的角色，则不进行保密限制，否则加密
    IF EXISTS(SELECT 1 FROM TOPROLE WHERE OP_CODE = @IN_INPUT_MAN AND ROLE_ID IN(SELECT ROLE_ID FROM TROLE WHERE FLAG_ENCRYPTION = 0))
        SELECT @V_FLAG_ENCRYPTION = 2
    ELSE
		SELECT @V_FLAG_ENCRYPTION = 1
    --加密显示位数
    IF EXISTS(SELECT 1 FROM TDICTPARAM WHERE TYPE_VALUE = '800701')
        SELECT @V_ENCRYPTION_SIZE = CAST(TYPE_CONTENT AS INT) FROM TDICTPARAM WHERE TYPE_VALUE = '800701'
    ELSE
        SET  @V_ENCRYPTION_SIZE = 4
		
	--导出时，做日志记录	
	IF @IN_EXPORT_FLAG=1 --客户信息导出
		INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
			VALUES('20301','客户信息导出',@IN_INPUT_MAN,'客户信息导出')
	ELSE IF @IN_EXPORT_FLAG=2 --客户手机
	    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
			VALUES('20301','客户信息导出',@IN_INPUT_MAN,'客户手机导出')
	ELSE IF @IN_EXPORT_FLAG=3 --客户通讯录
	    INSERT INTO TLOGLIST(BUSI_FLAG,BUSI_NAME,OP_CODE,SUMMARY)
			VALUES('20301','客户信息导出',@IN_INPUT_MAN,'客户通讯录导出')
			
    SELECT @V_SERVICE_NAME = SERVICE_MAN FROM TCustomers WHERE CUST_ID = @IN_CUST_ID
	IF @IN_QUERY_FLAG = 1
	BEGIN
		SELECT  CUST_ID,CUST_NO,CUST_NAME,BIRTHDAY,AGE,
				SEX,SEX_NAME,CUST_TYPE,CUST_TYPE_NAME,WT_FLAG,WT_FLAG_NAME,
				PASSWORD,TOUCH_TYPE,TOUCH_TYPE_NAME,CUST_SOURCE,
				CUST_SOURCE_NAME,RG_TIMES,TOTAL_MONEY,CURRENT_MONEY,LAST_RG_DATE,
				INPUT_MAN,INPUT_TIME,CHECK_FLAG,CHECK_MAN,MODI_MAN,MODI_TIME,
				CANCEL_MAN,CANCEL_TIME,STATUS,STATUS_NAME,SUMMARY,LEGAL_MAN,
				REGISTRATION_ID,LIST_ID,PRINT_DEPLOY_BILL,PRINT_POST_INFO,IS_LINK,
				SERVICE_MAN,ENT_CUST_ID,VIP_CARD_ID,VIP_DATE,HGTZR_BH,
				VOC_TYPE,VOC_TYPE_NAME,CARD_TYPE,CARD_TYPE_NAME,CONTACT_MAN,CARD_VALID_DATE,COUNTRY,JG_CUST_TYPE,
				POST_CODE,POST_CODE2,POST_ADDRESS,POST_ADDRESS2,LEGAL_ADDRESS,CARD_ID,
				--ISNULL(stuff(CARD_ID,1,len(CARD_ID)-@V_ENCRYPTION_SIZE,'******'),'****') AS CARD_ID,
				ISNULL(stuff(CUST_TEL,len(CUST_TEL)-@V_ENCRYPTION_SIZE+1,len(CUST_TEL),'******'),'****') AS CUST_TEL,
				ISNULL(stuff(MOBILE,len(MOBILE)-@V_ENCRYPTION_SIZE+1,len(MOBILE),'******'),'****') AS MOBILE,
				ISNULL(stuff(O_TEL,len(O_TEL)-@V_ENCRYPTION_SIZE+1,len(O_TEL),'******'),'****') AS O_TEL,
				ISNULL(stuff(H_TEL,len(H_TEL)-@V_ENCRYPTION_SIZE+1,len(H_TEL),'******'),'****') AS H_TEL,
				ISNULL(stuff(BP,len(BP)-@V_ENCRYPTION_SIZE+1,len(BP),'******'),'****') AS BP,
				ISNULL(stuff(FAX,len(FAX)-@V_ENCRYPTION_SIZE+1,len(FAX),'******'),'****') AS FAX,
				ISNULL(stuff(E_MAIL,1,charindex('@',E_MAIL)-1,'******'),'****') AS E_MAIL,
				MONEY_SOURCE,FACT_CONTROLLER,
				CARD_ID AS H_CARD_ID,
				CUST_TEL AS H_CUST_TEL,
				MOBILE AS H_MOBILE,
				O_TEL AS H_O_TEL,
				H_TEL AS H_H_TEL,
				BP AS H_BP,
				FAX AS H_FAX,
				E_MAIL AS H_E_MAIL
		FROM TCustomers WHERE CUST_ID = @IN_CUST_ID
	END
	ELSE
	BEGIN
		IF @V_FLAG_ACCESS = 1
		BEGIN
			IF @V_FLAG_ENCRYPTION = 0 OR @V_FLAG_ENCRYPTION = 2 --全部查看
				SELECT * ,
					CARD_ID AS H_CARD_ID,
					CUST_TEL AS H_CUST_TEL,
					MOBILE AS H_MOBILE,
					O_TEL AS H_O_TEL,
					H_TEL AS H_H_TEL,
					BP AS H_BP,
					FAX AS H_FAX,
					E_MAIL AS H_E_MAIL
				FROM TCustomers
				WHERE CUST_ID = @IN_CUST_ID
			ELSE
				--部份查看
				SELECT  CUST_ID,CUST_NO,CUST_NAME,BIRTHDAY,AGE,
						SEX,SEX_NAME,CUST_TYPE,CUST_TYPE_NAME,WT_FLAG,WT_FLAG_NAME,
						PASSWORD,TOUCH_TYPE,TOUCH_TYPE_NAME,CUST_SOURCE,
						CUST_SOURCE_NAME,RG_TIMES,TOTAL_MONEY,CURRENT_MONEY,LAST_RG_DATE,
						INPUT_MAN,INPUT_TIME,CHECK_FLAG,CHECK_MAN,MODI_MAN,MODI_TIME,
						CANCEL_MAN,CANCEL_TIME,STATUS,STATUS_NAME,SUMMARY,LEGAL_MAN,
						REGISTRATION_ID,LIST_ID,PRINT_DEPLOY_BILL,PRINT_POST_INFO,IS_LINK,
						SERVICE_MAN,ENT_CUST_ID,VIP_CARD_ID,VIP_DATE,HGTZR_BH,
						VOC_TYPE,VOC_TYPE_NAME,CARD_TYPE,CARD_TYPE_NAME,CONTACT_MAN,CARD_VALID_DATE,COUNTRY,JG_CUST_TYPE,
						POST_CODE,POST_CODE2,POST_ADDRESS,POST_ADDRESS2,LEGAL_ADDRESS,CARD_ID,
						--ISNULL(stuff(CARD_ID,1,len(CARD_ID)-@V_ENCRYPTION_SIZE,'******'),'****') AS CARD_ID,
						ISNULL(stuff(CUST_TEL,len(CUST_TEL)-@V_ENCRYPTION_SIZE+1,len(CUST_TEL),'******'),'****') AS CUST_TEL,
						ISNULL(stuff(MOBILE,len(MOBILE)-@V_ENCRYPTION_SIZE+1,len(MOBILE),'******'),'****') AS MOBILE,
						ISNULL(stuff(O_TEL,len(O_TEL)-@V_ENCRYPTION_SIZE+1,len(O_TEL),'******'),'****') AS O_TEL,
						ISNULL(stuff(H_TEL,len(H_TEL)-@V_ENCRYPTION_SIZE+1,len(H_TEL),'******'),'****') AS H_TEL,
						ISNULL(stuff(BP,len(BP)-@V_ENCRYPTION_SIZE+1,len(BP),'******'),'****') AS BP,
						ISNULL(stuff(FAX,len(FAX)-@V_ENCRYPTION_SIZE+1,len(FAX),'******'),'****') AS FAX,
						ISNULL(stuff(E_MAIL,1,charindex('@',E_MAIL)-1,'******'),'****') AS E_MAIL,
						MONEY_SOURCE,FACT_CONTROLLER,
						CARD_ID AS H_CARD_ID,
						CUST_TEL AS H_CUST_TEL,
						MOBILE AS H_MOBILE,
						O_TEL AS H_O_TEL,
						H_TEL AS H_H_TEL,
						BP AS H_BP,
						FAX AS H_FAX,
						E_MAIL AS H_E_MAIL
				FROM TCustomers WHERE CUST_ID = @IN_CUST_ID
		END
		ELSE
		BEGIN
			SELECT * ,
				CARD_ID AS H_CARD_ID,
				CUST_TEL AS H_CUST_TEL,
				MOBILE AS H_MOBILE,
				O_TEL AS H_O_TEL,
				H_TEL AS H_H_TEL,
				BP AS H_BP,
				FAX AS H_FAX,
				E_MAIL AS H_E_MAIL
			FROM TCustomers
			WHERE CUST_ID = 0
		END
	END	
GO
